### ISSUE TITLE
Oracle - Guid as Identity column

### ISSUE THREAD

**Issue by HemidAbbasov** [linq2db/linq2db#1010]
Hi. We have some problems while trying to use column of type Guid as Identity column.

Suppose we have this class:

```c#
    public class TestGuid
    {
        [PrimaryKey, Identity, Column(Name = "ID")]
        public Guid Id { get; set; }

        [Column(Name = "NAME",Length = 20), NotNull]
        public string Name { get; set; }

        [Column(Name = "CREATED_AT", DataType = DataType.DateTime, DbType = "DATE"), NotNull]
        public DateTime CreatedAt { get; set; }
    }
```

Let's write simple table creation code:

```c#
        [Test]
        public void Create()
        {
            using ( var db = new DataConnection() )
            {
                try
                {
                    db.DropTable<TestGuid>();
                }
                catch  { }

                db.CreateTable<TestGuid>();
            }
        }
```

And the output is:

```sql
-- Create table is OK
CREATE TABLE TestGuid
(
	ID         Raw(16)       NOT NULL,   -- RAW(16) is Guid in Oracle
	NAME       VarChar2(20)  NOT NULL,
	CREATED_AT DATE          NOT NULL,

	CONSTRAINT PK_TestGuid PRIMARY KEY (ID)
)

-- No need of this sequence
CREATE SEQUENCE SIDENTITY_TestGuid;

-- Body should be changed
CREATE OR REPLACE TRIGGER TIDENTITY_TestGuid
BEFORE INSERT ON TestGuid FOR EACH ROW
BEGIN
	SELECT SIDENTITY_TestGuid.NEXTVAL INTO :NEW.ID FROM dual;
END;
```
First of, there is NO need of sequence in this case and in the trigger must be:
```sql
SELECT SYS_GUID() INTO :NEW.ID FROM dual;
```
Without changing trigger's body we will get Oracle Exception while trying insert in this table
```
Exception Message: ORA-04098: trigger 'TEST.TIDENTITY_TESTGUID' is invalid and failed re-validation
```

I'm changing the body of trigger manual. The second test we write is InsertWithIdentity:

```c#
        [Test]
        public void TestInsertWithIdentity()
        {
            using ( var db = new DataConnection() )
            {
                var id = db.GetTable<TestGuid>()
                           .InsertWithIdentity(() => new TestGuid
                                                     {
                                                         Name = "Test",
                                                         CreatedAt = Sql.CurrentTimestamp
                                                     });
            }
        }
```
Now we are getting another exception
```
Exception message: Oracle.ManagedDataAccess.Client.OracleException : ORA-00932: inconsistent datatypes: expected NUMBER got BINARY
Stack trace: 
   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery() in c:\projects\linq2db\Source\Data\DataConnection.cs:line 992
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteScalarImpl(DataConnection dataConnection, PreparedQuery preparedQuery) in c:\projects\linq2db\Source\Data\DataConnection.QueryRunner.cs:line 363
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteScalar() in c:\projects\linq2db\Source\Data\DataConnection.QueryRunner.cs:line 396
   at LinqToDB.Linq.QueryRunner.ScalarQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters) in c:\projects\linq2db\Source\Linq\QueryRunner.cs:line 602
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass5e.<SetScalarQuery>b__5c(IDataContext db, Expression expr, Object[] ps) in c:\projects\linq2db\Source\Linq\QueryRunner.cs:line 592
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in c:\projects\linq2db\Source\Linq\ExpressionQuery.cs:line 171
   at LinqToDB.LinqExtensions.InsertWithIdentity[T](ITable`1 target, Expression`1 setter) in c:\projects\linq2db\Source\LinqExtensions.cs:line 1034
   at LinqMasterDetails.TestCodeFirst.TestInsertWithIdentity() in x:\PROJECTS\Examples\LinqMasterDetails\LinqMasterDetails\TestCodeFirst.cs:line 70
```

imho, the reason of this exception is:

```sql
DECLARE @IDENTITY_PARAMETER Decimal  --  <--reason here
SET     @IDENTITY_PARAMETER = NULL

INSERT INTO TestGuid
(
	NAME,
	CREATED_AT
)
VALUES
(
	'Test',
	CURRENT_TIMESTAMP
)
RETURNING 
	ID INTO :IDENTITY_PARAMETER
```

I found two places in library code where IDENTITY_PARAMETER is used. 
One of this is 
https://github.com/linq2db/linq2db/blob/0eb5d5f73a0976771093659471d8cb5537b4ac7a/Source/LinqToDB/Data/DataConnection.QueryRunner.cs#L352

Imho, in this place there should be some sort of differentiation based on the data type (is Numeric or Guid) of the Identity column.

### Environment details
linq2db version: *1.10.0*  
Database Server: *Oracle 11.2.0.1.0*  
Database Provider: *Oracle.ManagedDataAccess 12.2.1100*  
Operating system: *Windows 8.1*  
Framework version: *.NET Framework 4.5*

**Comment by sdanyliv** [comment]
Strange request - Identity as GUID. Usually in this case GUID Is generated on the client side.
We are working on support of DML output. In this case you can retrieve ID or other fields exactly after insert (RETURNING in Oracle)

**Comment by MaceWindu** [comment]
Right now I don't think we support server-generated Guids with Identity attribute for any provider including Oracle, only numeric types. Looks like an area for improvement.
