### ISSUE TITLE
Inheritance entity and OData WebApi

### ISSUE THREAD

**Issue by genusP** [linq2db/linq2db#1046]
I use l2db as data access layer for OData WebApi. When execute OData query with cast to derived type and expand navigation property then raise exception/
```
Exception message: Argument types do not match
Stack trace:
   at System.Linq.Expressions.Expression.Bind(MemberInfo member, Expression expression)
   at LinqToDB.Expressions.Extensions.<>c__DisplayClass34_1.<Transform>b__1(MemberBinding b) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1500
```

### Steps to reproduce
Entities:
```c#
[Table, InheritanceMapping(Code="bda.Requests", Type=typeof(BdaTask))]
class Task
{
        [Column(IsPrimaryKey=true)] public int Id { get; set; }
        [Column]public int TargetId { get; set; }
        [Column(IsDescriminator=true)] string TargetName { get; set; }
}

class BdaTask
{
        public static string Code = "bda.Requests";

        [Association(ExpressionPredicate = nameof(RequestAssociationExp))]
        public Request Request { get; set; }

        private static Expression<Func<Task, Request, bool>> RequestAssociationExp()
           => (t, r) => t.TargetName == Constants.RequestTarget
                     && t.TargetId == r.Id;
}
```
Query builded OData WebApi
```
Table(Task)
	.Where(Param_0 => (Param_0.Id == 1))
	.OfType<BdaTask>()
	.Select(Param_1 => 
		new SelectAllAndExpand<BdaTask>() {
			ModelID = "4b18d1f2-2cca-4e44-ae8f-ea010f7fd800", 
			Instance = Param_1, 
			UseInstanceForProperties = True, 
			Container = new SingleExpandedProperty`1() {
				Name = "Request", Value = new SelectAll`1() {
					ModelID = "4b18d1f2-2cca-4e44-ae8f-ea010f7fd800", 
					Instance = Param_1.Request, 
					UseInstanceForProperties = True
					}, IsNull = (Param_1.Request == null)}})
```
Error raised when l2db transform member binding expression (Instance = Param_1). After transform, the expression 'Param_1', result type has changed to Task, and the initialized member is of type BdaTask

### Environment details
linq2db version: *1.10.0, 2.0.0-beta4*  
Operating system: * Windows 10*  
Framework version: *netcoreapp*

**Comment by sdanyliv** [comment]
Why in your sampe `BdaTask` is not inherited from `Task` ?

**Comment by genusP** [comment]
Code for reproduce:
```c#
class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            DataConnection.AddConfiguration("default", "Data Source=:memory:", new LinqToDB.DataProvider.SQLite.SQLiteDataProvider());
            DataConnection.DefaultConfiguration = "default";

            var db = new DataConnection();
            db.CreateTable<Task>();

            db.GetTable<Task>()
                .OfType<BdaTask>()
                .Select(p => new SelectAllAndExpand<BdaTask>
                {
                    Instance = p
                })
                .ToArray();
        }
    }

    [Table, InheritanceMapping(Code = BdaTask.Code, Type = typeof(BdaTask))]
    class Task
    {
        [Column(IsPrimaryKey = true)]
        public int Id { get; set; }

        [Column(IsDiscriminator = true)]
        public string TargetName { get; set; }
    }

    class BdaTask:Task
    {
        public const string Code = "bda.Requests";
    }

    class SelectAllAndExpand<T>
    {
		public T Instance { get; set; } 
    }
```

**Comment by sdanyliv** [comment]
@genusP, issue fixed. You can get fixed version  from MyGet.

**Comment by genusP** [comment]
Thanks
