### ISSUE TITLE
Not load association when use entity cast

### ISSUE THREAD

**Issue by genusP** [linq2db/linq2db#1057]
Not load association when use entity cast. I use OData WebApi to generate expression.
```
Exception message:  System.NullReferenceException: 'Object reference not set to an instance of an object.'
Stack trace: at lambda_method(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 55
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__8`1.MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 337
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

### Steps to reproduce
```c#
class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            DataConnection.AddConfiguration("default", "Data Source=:memory:", new LinqToDB.DataProvider.SQLite.SQLiteDataProvider());
            DataConnection.DefaultConfiguration = "default";

            var db = new DataConnection();
            db.CreateTable<Task>();
            db.CreateTable<TaskStage>();

            db.Insert(new Task { Id = 1, TargetName = "bda.Requests" });
            db.Insert(new TaskStage { Id = 1, TaskId = 1, Actual = true});

            var query = db.GetTable<Task>()
                .OfType<BdaTask>()
                .Select(p => new
                {
                    Instance = (Task)p, //without cast throw other exception
                    ActualStageId = (p as Task).ActualStage.Id
                });
            var res = query.ToArray(); //this call throw exception
        }
    }

    [Table, InheritanceMapping(Code = "bda.Requests", Type = typeof(BdaTask))]
    class Task
    {
        [Column(IsPrimaryKey = true)]
        public int Id { get; set; }

        [Column(IsDiscriminator = true)]
        public string TargetName { get; set; }

        [Association(ExpressionPredicate =nameof(ActualStageExp))]
        public TaskStage ActualStage { get; set; }

        private static Expression<Func<Task, TaskStage, bool>> ActualStageExp()
            => (t, ts) => t.Id == ts.TaskId && ts.Actual == true;
    }

    class BdaTask:Task
    {
        public const string Code = "bda.Requests";
    }

    [Table]
    class TaskStage
    {
        [Column(IsPrimaryKey =true)]
        public int Id { get; set; }

        [Column]
        public int TaskId { get; set; }

        [Column]
        public bool Actual { get; set; }
    }
```

### Environment details
linq2db version: 2.0.0-rc2012 
Operating system: Windows 10
Framework version: .NET Core 2.0

**Comment by genusP** [comment]
When Task type change ActualStage property declaration to
```
 [Association(ExpressionPredicate =nameof(ActualStageExp))]
        public IEnumarable<TaskStage> ActualStage { get; set; }
```
then this query throws exception:
```
 LinqToDB.Linq.LinqException: Sequence '(colParam As AwtTask).ActualStage' cannot be converted to SQL.
at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 167
at LinqToDB.Linq.Builder.SelectManyBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectManyBuilder.cs:line 39
at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 175
at LinqToDB.Linq.Builder.SelectBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectBuilder.cs:line 36
at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 175
at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 146
at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 273
at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 226
at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 84
at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 176
at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
Satellite.Host>    at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
```

**Comment by sdanyliv** [comment]
@genusP, looks like you are trying to find all possible ways to broke our linq parser )
I'm never use Inheritance so it is possibly has problems.

**Comment by jogibear9988** [comment]
can you try if it works with my patches from https://github.com/linq2db/linq2db/pull/1002

**Comment by jogibear9988** [comment]
@sdanyliv  I've tested it, seems it has nothing to do with inheritance. 

Cause you can also remove the

    .OfType<BdaTask>()

and it still throws the same Exception!

**Comment by jogibear9988** [comment]
It seems not to use the ExpressionPredicate, cause the created query (without the inheritance) looks like this:

    SELECT
	[t1].[Id],
	[t1].[TargetName]
    FROM
	[Task] [t1]

**Comment by jogibear9988** [comment]
If you change

                    ActualStageId = (p as Task).ActualStage.Id

to 

                    ActualStageId = p.ActualStage.Id

it works...

@sdanyliv : do you know how we can fix this?

**Comment by jogibear9988** [comment]
It also works when you use

                ActualStageId = ((Task)p).ActualStage.Id

**Comment by sdanyliv** [comment]
Not easy but yes. Inheritance mapping - worst thing that have been added to linq2db ;)

**Comment by jogibear9988** [comment]
I think we are missing a implementation for "TypeAs" in TransformExpression in ExpressionBuilder.QueryBuilder

**Comment by genusP** [comment]
I tested last myget package (rc2145).  Work correctly.
