### ISSUE TITLE
Running transformation: System.InvalidCastException: Specified cast is not valid.

### ISSUE THREAD

**Issue by Salalimo** [linq2db/linq2db#1060]
When I save the tt template to generate the models for Sybase I get an exception

```
Exception message:
Running transformation: System.InvalidCastException: Specified cast is not valid.
Stack trace:
   at Sybase.Data.AseClient.AseConnection.FilterData(DataTable& dataTable, AseDataAdapter dataAdapter)
   at Sybase.Data.AseClient.AseConnection.GetSchema(String collectionName, String[] restrictionValues)
   at Sybase.Data.AseClient.AseConnection.GetSchema(String collectionName)
   at LinqToDB.DataProvider.Sybase.SybaseSchemaProvider.GetProcedureParameters(DataConnection dataConnection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplating8440D30C4149BD0AAAB85702D1A4C79E30A5C29637D598B5E50356398B4D57C90CD931EA76F3CD165BA065B56C14DC0603106BBC9086568D782FFFDAEF10031A.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in C:\Users\sfarhat\Documents\Visual Studio 2017\Projects\RevenueBillJobScheduler\RBJS.DAL\LinqToDB.Templates\DataModel.ttinclude:line 103
   at Microsoft.VisualStudio.TextTemplating8440D30C4149BD0AAAB85702D1A4C79E30A5C29637D598B5E50356398B4D57C90CD931EA76F3CD165BA065B56C14DC0603106BBC9086568D782FFFDAEF10031A.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in C:\Users\sfarhat\Documents\Visual Studio 2017\Projects\RevenueBillJobScheduler\RBJS.DAL\LinqToDB.Templates\DataModel.ttinclude:line 415
   at Microsoft.VisualStudio.TextTemplating8440D30C4149BD0AAAB85702D1A4C79E30A5C29637D598B5E50356398B4D57C90CD931EA76F3CD165BA065B56C14DC0603106BBC9086568D782FFFDAEF10031A.GeneratedTextTransformation.LoadSybaseMetadata(String server, String port, String database, String uid, String password) in C:\Users\sfarhat\Documents\Visual Studio 2017\Projects\RevenueBillJobScheduler\RBJS.DAL\LinqToDB.Templates\LinqToDB.Sybase.ttinclude:line 80
   at Microsoft.VisualStudio.TextTemplating8440D30C4149BD0AAAB85702D1A4C79E30A5C29637D598B5E50356398B4D57C90CD931EA76F3CD165BA065B56C14DC0603106BBC9086568D782FFFDAEF10031A.GeneratedTextTransformation.TransformText() in C:\Users\sfarhat\Documents\Visual Studio 2017\Projects\RevenueBillJobScheduler\RBJS.DAL\SybaseDataModel\SybaseDB.tt:line 48	RBJS.DAL	C:\Users\sfarhat\Documents\Visual Studio 2017\Projects\RevenueBillJobScheduler\RBJS.DAL\LinqToDB.Templates\DataModel.ttinclude	103	





Using the debugger it is at this line
	var db = sp.GetSchema(dataConnection, GetSchemaOptions);
int the method : LoadServerMetadata(DataConnection dataConnection)

**Comment by MaceWindu** [comment]
It would be helpfull if you can use debugger to see what gives sybase problems.
It could be very likely an issue in sybase provider (BTW, beware of #792).

**Comment by sdanyliv** [comment]
What can i say. Looks like it is a problem of Sybase.Data.AseClient, Try to update this library.
Also you can disable stored procedures generation. Looks like you have some stored proc that not handled properly by this library.
`GetSchemaOptions.GetProcedures = false` - documentation [here](https://github.com/linq2db/t4models#configuring-generation-process)

**Comment by MaceWindu** [comment]
I've checked FilterData method using decompiler - it could be a situation when server returns schema data with unexpected data type. This could be an issue with provider itself or incompatibility between server and provider version.

**Comment by MaceWindu** [comment]
Ok, I've analyzed related sybase code and found out that the only reason it could fail is an unexpected value for procedure parameter in syscolumns.status2 column.

I've created fix, but it would be nice if you can check what value stored for that parameter in this column. This could help us to add better support for such cases. To identify parameter, you can check parameters, returned by GetSchema method - problematic parameter(s) will have `false` for `IsIn`, `IsOut` and `IsResult` properties.

**Comment by MaceWindu** [comment]
Or you can just select all parameters from this tablee and find records with `status2 not in (1, 2, 4)`

**Comment by MaceWindu** [comment]
Ok, thanks for information. You can try fix using prerelease version from myget feed https://www.myget.org/gallery/linq2db

**Comment by MaceWindu** [comment]
Whoops, I didn't merged fixes yet, so it is not on myget. I will merge it now and it will publish new version to myget in hour

**Comment by MaceWindu** [comment]
Checked those  status values - they are not in documentation even for ASE 16.
Also taking into account that we use system procedure and this procedure also doesn't decode those flags properl - I think we will not add support for them for now. We can look into it again if anyone will ask for it.

**Comment by MaceWindu** [comment]
@senseibaka, sorry to bother, maybe you have some information about those flags?
1048576 = 0x100000
8388610 = 0x800002

@Salalimo, could you check what is usertype 56? It is not in documentation and I don't have it in systypes for my test instance
```sql
SELECT * FROM systypes  WHERE usertype = 56
```

**Comment by senseibaka** [comment]
@MaceWindu sorry, I don't know anything more than the ASE 16 documentation says (which is frustratingly incomplete in this case, grr).

**Comment by Salalimo** [comment]
@MaceWindu  
SELECT * FROM systypes  WHERE usertype = 56
I get nothing
