### ISSUE TITLE
Cancellation in the middle of reading large dataset results in SQL timeout exceltion

### ISSUE THREAD

**Issue by TheWind3** [linq2db/linq2db#1063]
Suppose, we have a linq query, and this query selects many rows of data (tens of thousands).
While iterating through them, we decide for some reason to stop. This results in timeout exception.

I think, the reason is Linq2Db should call SqlCommand.Cancel before disposing DataReader().
Here is SO question wich demostrates the similar problem: https://stackoverflow.com/questions/133374/net-sqldatareader-close-or-dispose-results-in-timeout-expired-exception

For me, this problem is frustrating. It does not allow us to get to user the ability to cancel long-running job.
```
Exception message:
System.Data.SqlClient.SqlException Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding

Stack trace:
System.Data.SqlClient.SqlException (0x80131904): Timeout expired. The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): Timeout expired
   в System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   в System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   в System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   в System.Data.SqlClient.SqlDataReader.TryCloseInternal(Boolean closeReader)
   в System.Data.SqlClient.SqlDataReader.Close()
   в System.Data.Common.DbDataReader.Dispose(Boolean disposing)
   в LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__8`1.<>m__Finally3()
   в LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__8`1.System.IDisposable.Dispose()
   в Ragtime.Reports.Excel.Table.Engine`1.WriteData(SheetWriter writer, IQueryable`1 data, IReadOnlyList`1 columns)
   в Ragtime.Reports.Excel.Table.Engine`1.SiphonData(Package package, IQueryable`1 data, IReadOnlyList`1 columns)
   в Ragtime.Reports.Excel.Table.Engine`1.Run(String fileName)
   в Ragtime.Reports.Excel.Table.Engine`1.Body()
   в Ragtime.Jobs.Manager.<>c__DisplayClass4_0`1.<<Start>g__Execute|0>d.MoveNext()
ClientConnectionId:8ca92b87-bb30-4efe-aca3-8ec3ff1ed740
Error Number: -2, State: 0, Class: 11

```

### Steps to reproduce
```c#
public void DoHardWork() {
  var query = GetQueryReturningLargeDataSet();
  try {
    foreach(var row in query) {
      if(ShouldCancel)
        throw new JobCancelledException();
    }
  }
  catch(JobCancelledException e) {
    Console.WriteLine("oh, cancellation"); // We will not be here
  }
  catch {
    Console.WriteLine("Other bad things happend"); // ... instead, we'll be here with timeout exception
  }
}
```

### Environment details
linq2db version: *2.0.0-rc*  
Database Server: *MS SQL 2014*  
Framework version: *.NET Framework 4.7.1*

**Comment by sdanyliv** [comment]
We will investigate this. Could you please try to call `db.Command.Cancel()` before throwing JobCancelledException?

**Comment by TheWind3** [comment]
Yes, I tried. It didn't work. And, as I can see looking at source code, it couldn't.
Is it ok for me to try make PR solving this issue?

**Comment by sdanyliv** [comment]
Yes, why not. Just try do not break formatting.

**Comment by AJ1987** [comment]
> Yes, why not. Just try do not break formatting.

Hi sdanyliv, i still met the time out expired problem, have you fixed this problem?

I run a hangfire job automatically to run a task to search with ling2db. but it shows:
Failed to generated flashdeal! Exception:System.Data.SqlClient.SqlException (0x80131904): Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (258): Unknown error 258
         at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
         at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
         at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
         at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
         at System.Data.SqlClient.SqlDataReader.get_MetaData()
         at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
         at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
         at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
         at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
         at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
         at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
         at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
         at LinqToDB.Data.CommandInfo.Query[T]()

**Comment by MaceWindu** [comment]
It is not clear how you able to trigger data reader disposal (we will need working example if issue still exists). In any case we are disposing command for data readers starting from `4.0.0-preview.1` release, so I would expect it to be fixed.
