### ISSUE TITLE
Not load asscoations if source distinct

### ISSUE THREAD

**Issue by genusP** [linq2db/linq2db#1096]
I found new way for broke your linq parser :)
If source query contains Distinct call. Associations property not loads.
```
Exception message: Exception of type 'System.ArgumentOutOfRangeException' was thrown.
Parameter name: ordinal
Actual value was 2.
Stack trace:    at Microsoft.Data.Sqlite.SqliteDataReader.GetSqliteType(Int32 ordinal)
   at Microsoft.Data.Sqlite.SqliteDataReader.GetFieldType(Int32 ordinal)
   at LinqToDB.DataProvider.SQLite.SQLiteDataProvider.GetReaderExpression(MappingSchema mappingSchema, IDataReader reader, Int32 idx, Expression readerExpression, Type toType) in C:\projects\linq2db\Source\LinqToDB\DataProvider\SQLite\SQLiteDataProvider.cs:line 158
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.GetColumnReader(IDataContext dataContext, MappingSchema mappingSchema, IDataReader dataReader, Type type, Int32 idx, Expression dataReaderExpr) in C:\projects\linq2db\Source\LinqToDB\Expressions\ConvertFromDataReaderExpression.cs:line 55
   at LinqToDB.Linq.QueryRunner.Mapper`1.<>c__DisplayClass6_0.<Map>b__0(Expression e) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 44
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 988
   at LinqToDB.Expressions.Extensions.<>c__DisplayClass25_0.<TransformX>b__0(MemberBinding b) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1215
   at LinqToDB.Expressions.Extensions.Transform[T](ICollection`1 source, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 953
   at LinqToDB.Expressions.Extensions.TransformX(MemberInitExpression e, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 0
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1059
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1063
   at LinqToDB.Expressions.Extensions.TransformX(BinaryExpression e, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1297
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1032
   at LinqToDB.Expressions.Extensions.Transform[T](ICollection`1 source, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 969
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1092
   at LinqToDB.Expressions.Extensions.TransformX(LambdaExpression e, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1275
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1056
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1071
   at LinqToDB.Expressions.Extensions.TransformX(LambdaExpression e, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1275
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1056
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 43
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__8`1.MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 337
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at l2db_issue_1046.Program.Main(String[] args) in C:\Users\genus\Source\Repos\l2db_issue_1046\l2db_issue_1046\Program.cs:line 32
```

### Steps to reproduce
```c#
class Program
    {
        static void Main(string[] args)
        {
            Console.WriteLine("Hello World!");

            DataConnection.AddConfiguration("default", "Data Source=:memory:", new LinqToDB.DataProvider.SQLite.SQLiteDataProvider());
            DataConnection.DefaultConfiguration = "default";

            var db = new DataConnection();
            db.CreateTable<Task>();
            db.CreateTable<TaskStage>();

            db.Insert(new Task { Id = 1, TargetName = "bda.Requests"});
            db.Insert(new TaskStage { Id = 1, TaskId = 1, Actual = true});

            var query = db.GetTable<Task>()
                .Distinct()
                .Select(t => new { t, t.ActualStage });
            var res = query.ToArray();
        }
    }

    [Table]
    class Task
    {
        [Column(IsPrimaryKey = true)]
        public int Id { get; set; }

        [Column(IsDiscriminator = true)]
        public string TargetName { get; set; }

        [Association(ExpressionPredicate =nameof(ActualStageExp))]
        public TaskStage ActualStage { get; set; }

        private static Expression<Func<Task, TaskStage, bool>> ActualStageExp()
            => (t, ts) => t.Id == ts.TaskId && ts.Actual == true;
    }

    [Table]
    class TaskStage
    {
        [Column(IsPrimaryKey =true)]
        public int Id { get; set; }

        [Column]
        public int TaskId { get; set; }

        [Column]
        public bool Actual { get; set; }
    }
```

### Environment details
linq2db version: *1.10.0*  
Database Server: *E.g. PostgreSQL 9.6.3*  
Database Provider: *E.g. Npgsql 3.2.3*  
Operating system: *E.g. Windows 10*  
Framework version: *.NET Framework 4.6.2*

**Comment by jogibear9988** [comment]
Generated Code....

Without distinct:

    SELECT
	[t2].[Id],
	[t2].[TargetName],
	[t1].[Id] as [Id1]
    FROM
	[Task] [t2]
		LEFT JOIN [TaskStage] [t1] ON [t2].[Id] = [t1].[TaskId] AND [t1].[Actual] = 1

with distinct

    SELECT
	[t3].[Id] as [Id1],
	[t3].[TargetName] as [TargetName1]
    FROM
	(
		SELECT DISTINCT
			[t2].[Id],
			[t2].[TargetName],
			[t1].[Id] as [Id2]
		FROM
			[Task] [t2]
				LEFT JOIN [TaskStage] [t1] ON [t2].[Id] = [t1].[TaskId] AND [t1].[Actual] = 1
	) [t3]

**Comment by jogibear9988** [comment]
Outer select is missing one column, so the index wich the converter requests could not be returned

**Comment by jogibear9988** [comment]
When I debug it, the subquery is build with only two parameters, because the last one "[t1].[Id] as [Id1]" seems to be added later to the query! And later it will not be included on the outer!

**Comment by sdanyliv** [comment]
Without linq query i can not figure out what happened.

**Comment by sdanyliv** [comment]
Actually i think it is correct behavior. You are trying make distinct and later get association field which was not included in the query.
Can you try to add  `db.GetTable<Task>().LoadWith(t => t.ActualStage)` before distinct?

**Comment by jogibear9988** [comment]
LoadWith does not help!

**Comment by sdanyliv** [comment]
We have to find time to fix that, but workaround is obvious - select all needed fields before Distinct in anonymous class.

**Comment by MaceWindu** [comment]
Issue fixed at least in v3
