### ISSUE TITLE
GroupBy and OrderBy throw an exception

### ISSUE THREAD

**Issue by integral-llc** [linq2db/linq2db#1129]
I have such queries
```cs
var uniqueStones = from sss in dc.StoneSupplierStone
                    where sss.StoneSupplier_id == stoneSupplierId
                    group sss by sss.Stone_id
                    into GS
                    select (int) GS.Key;


// also ignore the stones that are used by other stone suppliers
                var inUseByStoneSuppliers = (from sss in dc.StoneSupplierStone
                    where sss.StoneSupplier_id != stoneSupplierId
                    from us in uniqueStones
                    where sss.Stone_id == us
                    from ss in dc.StoneSupplier
                    where sss.StoneSupplier_id == ss.Id
                    group ss by ss.Id
                    into ssG
                    select ssG.First()
                    into ssUnique
                    select ssUnique).ToList();
```
which work as needed, but if I add an `OrderBy` as such 
```cs
// also ignore the stones that are used by other stone suppliers
                var inUseByStoneSuppliers = (from sss in dc.StoneSupplierStone
                    where sss.StoneSupplier_id != stoneSupplierId
                    from us in uniqueStones
                    where sss.Stone_id == us
                    from ss in dc.StoneSupplier
                    where sss.StoneSupplier_id == ss.Id
                    group ss by ss.Id
                    into ssG
                    select ssG.First()
                    into ssUnique
                    **orderby ssUnique.Name**
                    select ssUnique).ToList();
```
it throws an exception
`
 $exception | {"Expression 'ssG.First().Name' cannot be converted to SQL."} | LinqToDB.Linq.LinqException
`
```
   at LinqToDB.Linq.Builder.GroupByBuilder.GroupByContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\GroupByBuilder.cs:line 588
   at LinqToDB.Linq.Builder.SelectContext.<>c__DisplayClass21.<ConvertToSql>b__13(IBuildContext ctx, Expression ex, Int32 l) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 301
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 907
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 298
   at LinqToDB.Linq.Builder.SelectContext.<>c__DisplayClass21.<ConvertToSql>b__13(IBuildContext ctx, Expression ex, Int32 l) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 301
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 934
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\SelectContext.cs:line 298
   at LinqToDB.Linq.Builder.ExpressionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in c:\projects\linq2db\Source\Linq\Builder\ExpressionContext.cs:line 57
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 840
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 636
   at LinqToDB.Linq.Builder.OrderByBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in c:\projects\linq2db\Source\Linq\Builder\OrderByBuilder.cs:line 49
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in c:\projects\linq2db\Source\Linq\Builder\MethodCallBuilder.cs:line 22
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 184
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in c:\projects\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 155
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in c:\projects\linq2db\Source\Linq\Query.cs:line 295
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in c:\projects\linq2db\Source\Linq\Query.cs:line 244
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in c:\projects\linq2db\Source\Linq\ExpressionQuery.cs:line 89
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in c:\projects\linq2db\Source\Linq\ExpressionQuery.cs:line 186
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at KVManager.Utils.DatabaseLayer.DeleteStonesForStoneSupplier(Int32 stoneSupplierId, List`1 stoneIDs, StoneInUseByStoneSuppliersDelegate stoneInUseCB) in C:\z\projects\QC\main\gfd\KVManager\Utils\DatabaseLayer.cs:line 195
   at KVManager.StonesManagement.StonesReplicatorControl.<>c__DisplayClass7_0.<DeleteStonesForStoneSupplier>b__0() in C:\z\projects\QC\main\gfd\KVManager\StonesManagement\StonesReplicatorControl.cs:line 93
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
```

Any suggestions?
Thx

### Environment details
linq2db version: *1.10.2*  
Database Server: *E.g. Sql Server*  
Operating system: *E.g. Windows 10*  
Framework version: *.NET Framework 4.6.2*

**Comment by sdanyliv** [comment]
Closing for now, will reopen if needed.
