### ISSUE TITLE
Mapping error when computed column used

### ISSUE THREAD

**Issue by genusP** [linq2db/linq2db#1151]
```
Exception message: Index was outside the bounds of the array.
Stack trace:    at System.Data.SqlClient.SqlDataReader.CheckMetaDataIsReady(Int32 columnIndex, Boolean permitAsync)
   at System.Data.SqlClient.SqlDataReader.GetFieldType(Int32 i)
   at LinqToDB.DataProvider.DataProviderBase.GetReaderExpression(MappingSchema mappingSchema, IDataReader reader, Int32 idx, Expression readerExpression, Type toType) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\DataProvider\DataProviderBase.cs:line 184
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.GetReaderExpression(MappingSchema mappingSchema, IDataReader reader, Int32 idx, Expression readerExpression, Type toType) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Data\DataConnection.Linq.cs:line 56
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.GetColumnReader(IDataContext dataContext, MappingSchema mappingSchema, IDataReader dataReader, Type type, Int32 idx, Expression dataReaderExpr) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\ConvertFromDataReaderExpression.cs:line 53
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.Reduce(IDataReader dataReader) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\ConvertFromDataReaderExpression.cs:line 45
   at LinqToDB.Linq.QueryRunner.Mapper`1.<>c__DisplayClass6_0.<Map>b__0(Expression e) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 45
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 990
   at LinqToDB.Expressions.Extensions.TransformX(BinaryExpression e, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1302
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1035
   at LinqToDB.Expressions.Extensions.TransformX(BinaryExpression e, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1301
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1035
   at LinqToDB.Expressions.Extensions.TransformX(BinaryExpression e, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1302
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1035
   at LinqToDB.Expressions.Extensions.Transform[T](ICollection`1 source, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 971
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1095
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1066
   at LinqToDB.Expressions.Extensions.Transform[T](ICollection`1 source, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 971
   at LinqToDB.Expressions.Extensions.TransformX(MethodCallExpression e, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1287
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1058
   at LinqToDB.Expressions.Extensions.TransformX(UnaryExpression e, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1294
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1056
   at LinqToDB.Expressions.Extensions.TransformX(BinaryExpression e, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1302
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1035
   at LinqToDB.Expressions.Extensions.Transform[T](ICollection`1 source, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 971
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1095
   at LinqToDB.Expressions.Extensions.TransformX(LambdaExpression e, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1278
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1059
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1074
   at LinqToDB.Expressions.Extensions.TransformX(LambdaExpression e, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1278
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1059
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader) in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 44
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__9`1.MoveNext() in C:\Users\genus\Source\Repos\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 343
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at l2db_issue_1046.Program.Main(String[] args) in C:\Users\genus\Source\Repos\l2db_issue_1046\l2db_issue_1046\Program.cs:line 57
```

### Steps to reproduce
```c#
db.GetTable<Request>()
    .Where(r => r.Id == 3)
    .SelectMany(r => r.Subscribers)
    .Select(s => s.Employee )

[Table(Schema ="bda", Name ="Requests")]
    class Request
    {
        [Column] public int Id { get; set; }

        [Association(ThisKey ="Id", OtherKey ="RequestId")]
        public IEnumerable<Subscription> Subscribers { get; set; }
    }

    [Table(Schema ="bda", Name ="Subscribers")]
    class Subscription
    {
        [Column]public int Id { get; set; }
        [Column]public int EmployeeId { get; set; }
        [Column] public int RequestId { get; set; }

        [Association(ThisKey =nameof(EmployeeId), OtherKey ="Id")]
        public Employee Employee { get; set; }
    }

    [Table(Schema ="ric", Name ="Employees")]
    class Employee {
        [PrimaryKey, Identity] public int Id { get; set; } // Int
        [Column, NotNull] public string Family { get; set; } // varchar(255)
        [Column, Nullable] public string Name { get; set; } // varchar(50)
        [Column, Nullable] public string SecondName { get; set; } // varchar(50)

        [ExpressionMethod(nameof(GetFullName), IsColumn = true)]
        public string FIO { get; set; }

        private static Expression<Func<Employee, string>> GetFullName()
            => e => e.Family
                    + SqlServer.IsNull(" " + e.Name, "")
                    + SqlServer.IsNull(" " + e.SecondName, "");
    }
    public static class SqlServer
    {
        [Sql.Function(ServerSideOnly = true)]
        public static DateTime GetDate()
            => DateTime.Now;

        [Sql.Expression("ISNULL({0}, {1})", ServerSideOnly = true)]
        public static T IsNull<T>(this T val, T forNull)
            => val == null ? forNull : val;
    }
```

### Environment details
linq2db version: *2.0.0-rc2*  
Database Server: Sql Server LocalDb  
Operating system: *Windows 10*  
Framework version: *.NET Core 2*

**Comment by sdanyliv** [comment]
Fixed in #1152

**Comment by genusP** [comment]
How to get fixed version. Latest builded version on myget, for commit 7198d00bea7789e8b01ae1e6d80d38c1d2b0d223

**Comment by MaceWindu** [comment]
As CI build broken right now, the only option is to build from source...

**Comment by MaceWindu** [comment]
new build expected in 30 minutes on myget

**Comment by genusP** [comment]
Thanks
