### ISSUE TITLE
[Question] How to create where condition from dictionary of values?

### ISSUE THREAD

**Issue by ifle** [linq2db/linq2db#1172]
How to create where condition from dictionary of values?
I have dictionary that contains values for where conditions
```
var pkkeys = new Dictionary<string, object>
{
     { "pkkey1", "value1"  },
     { "pkkey2", "value2"  }
}
```

I need to create something like this

```
db.GetTable<SomeTable>().Where(t => t.pkkey1 == "value1" && t.pkkey2 == "value2");

```

Thanks

**Comment by jogibear9988** [comment]
Easiest way would be to build a string and use https://github.com/StefH/System.Linq.Dynamic.Core

**Comment by sdanyliv** [comment]
Not near computer but this is easy if you know how to create Expression Tree. Will help you tomorrow.
Keywords are `Expression.MakeBinary`, `Expression.LambdaExpression` and `Expression.Parameter`.

**Comment by drekoo** [comment]
One option is to use dynamic columns...
var  q = db.GetTable<SomeTable>();
foreach(KeyValuePair<string, string> entry in pkkeys)
{
    // do something with entry.Value or entry.Key
q = q.Where(f=> Sql.Property<object>(f, entry.Key) == entry.Value);

}

**Comment by sdanyliv** [comment]
Unfortunately dynamic columns do not take care about column name mapped to property, so this solution can be wrong.

**Comment by ifle** [comment]
Thanks. 
In case of dynamic updates I will check the Dupper.

**Comment by sdanyliv** [comment]
What does it mean dynamic updates? Linq2db can do that with ease.

**Comment by ifle** [comment]
I have 2 dictionaries. One for values and one for where condition. Pairs of dictionary are name of column and value. How can I create dynamic query with linq2db? As I understand I can create the set clause of update query, but not where clause.

**Comment by sdanyliv** [comment]
Do you store in dictionary property name or column name?

**Comment by sdanyliv** [comment]
Will post solution in several hours (still away from computer). It’s easy and i did something like this before. Generating SQL by strings concatenation is not our way and it may lead to SQL injection.

**Comment by sdanyliv** [comment]
@ifle, here we go. 
Extension methods:
```cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using LinqToDB;
using LinqToDB.Expressions;
using LinqToDB.Linq;

namespace Linq2dbUtils
{
   public static class DynamicExtensions
   {
      private static readonly MethodInfo WithIUpdatableMethod = MemberHelper
         .MethodOf<object>(o => ((IUpdatable<object>) null).Set(null, 0))
         .GetGenericMethodDefinition();

      public static IQueryable<T> FilterByValues<T>(this IQueryable<T> source,
         IEnumerable<KeyValuePair<string, object>> values)
      {
         foreach (var pair in values)
         {
            var propInfo = typeof(T).GetProperty(pair.Key);
            if (propInfo != null)
            {
               var param = Expression.Parameter(typeof(T));
               var propExpression = Expression.MakeMemberAccess(param, propInfo);
               var equality = Expression.Equal(propExpression, Expression.Constant(pair.Value, propExpression.Type));
               var lambda = Expression.Lambda<Func<T, bool>>(equality, param);
               source = source.Where(lambda);
            }
         }

         return source;
      }

      public static IUpdatable<T> SetValues<T>(this IQueryable<T> source, IEnumerable<KeyValuePair<string, object>> values)
      {
         return source.AsUpdatable().SetValues(values);
      }

      public static int UpdateDynamic<T>(this IQueryable<T> source,
         IEnumerable<KeyValuePair<string, object>> filterValues, IEnumerable<KeyValuePair<string, object>> setValues)
      {
         return source
            .FilterByValues(filterValues)
            .SetValues(setValues)
            .Update();
      }

      public static IUpdatable<T> SetValues<T>(this IUpdatable<T> source, IEnumerable<KeyValuePair<string, object>> values)
      {
         object current = source;
         foreach (var pair in values)
         {
            var propInfo = typeof(T).GetProperty(pair.Key);
            if (propInfo != null)
            {
               var param = Expression.Parameter(typeof(T));
               var propExpression = Expression.MakeMemberAccess(param, propInfo);
               var lambda = Expression.Lambda(propExpression, param);

               var method = WithIUpdatableMethod.MakeGenericMethod(typeof(T), propInfo.PropertyType);
               current = method.Invoke(null, new[] { current, lambda, pair.Value });
            }
         }

         return (IUpdatable<T>) current;
      }
   }
}
```
And usage
```cs
internal class Program
{
   public static void Main(string[] args)
   {
      using (var db = new NorthwindDB())
      {
         var filter = new Dictionary<string, object>
         {
            { "EmployeeID", 1 }
         };

         var values = new Dictionary<string, object>
         {
            { "Address", "SomeAdress" },
            { "City", "SomeCity" }
         };

         db.Employees.UpdateDynamic(filter, values);

         // OR more flexible syntax

         db.Employees.FilterByValues(filter)
            .SetValues(values)
            .Update();
      }
   }
}
```

**Comment by ifle** [comment]
Thanks a lot!!!

In case of SetValues, why did not used dynamic properties lie this?
https://github.com/linq2db/linq2db/blob/66604737cd44a7a268c7b3a9d693de7e47a0ca4d/Tests/Linq/Update/DynamicColumnsTests.cs#L115

**Comment by sdanyliv** [comment]
It is not big deal which function to use here. `Sql.Property` is new functionality and for using it here i need more efforts for playing with reflection. Also properties gives type information which may be required for updates.

**Comment by ifle** [comment]
Thanks. I think will be very helpful to anyone create example with dynamic properties too.

**Comment by sdanyliv** [comment]
I have updated sample above to use both variants.

**Comment by ifle** [comment]
I see, thanks. This is function is very good candidate to be into linq2db.
Unfortunately linq2db does not support most flexible and simple syntax like this 
```c#
var filter = new Dictionary<string, object>
{
    { "Id", 1 }
};


var values = new Dictionary<string, object>
{
    { "Address", "SomeAdress" },
    { "City", "SomeCity" }
};

var query = dbContext.TAXI.AsQueryable();
foreach (var filterPair in filter)
{
    query = query.Where(c => Sql.Property<object>(c, filterPair.Key)  == filterPair.Value);
}

var updatable = query.AsUpdatable();
foreach (var valuePair in values)
{
    updatable = updatable.Set(c => Sql.Property<object>(c, valuePair.Key), () => valuePair.Value);
}


updatable.Update();

```

**Comment by sdanyliv** [comment]
@ifle, why not supported? Looks like it works. Just tested.

We had plans to create external library with such kind of helpers.

**Comment by ifle** [comment]
Your samples works perfect. My does not works

**Comment by sdanyliv** [comment]
Your samples works also. Which error do you have?

**Comment by ifle** [comment]
```c#
System.InvalidOperationException : Reference equality is not defined for the types 'System.Int32' and 'System.Object'.
   at System.Linq.Expressions.Expression.ReferenceEqual(Expression left, Expression right)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.UpdateBuilder.Set.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.UpdateBuilder.Set.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.UpdateBuilder.Set.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
```

**Comment by sdanyliv** [comment]
You have to set appropriate Sql property type. That’s why my example works. Converting everything to strings is not an option - it may break indexes usage.

**Comment by ifle** [comment]
I understand that. Maybe linq2db will catch object values as you in your example.

**Comment by sdanyliv** [comment]
@ifle, it is very precise and hard work. Maybe sometimes. 
My extensions should be enough for your situation. Also you can create your own `Set` and `Where` extensions that do exactly same things as my samples.

**Comment by MaceWindu** [comment]
Closing as answered

**Comment by Factotum381** [comment]
@drekoo https://stackdev.space/questions/exploring-partial-searches-within-lexicons
