### ISSUE TITLE
RetryPolicy: Fail on concurrent DB instance queries

### ISSUE THREAD

**Issue by ig-sinicyn** [linq2db/linq2db#1174]
Concurrent queries fails when SqlServerRetryPolicy is applied to the db instances.
```c#
	public class SimpleLinq2DbTests
	{
		public class MyDB : LinqToDB.Data.DataConnection
		{
			private static readonly IDataProvider _dataProvider = new SqlServerDataProvider("mssql", SqlServerVersion.v2012);

			public static Func<MyDB> CreateFactory(string connectionString, int retryCount, TimeSpan delay)
			{
				return () =>
				{
					var db = new MyDB(_dataProvider, connectionString)
					{
						// No exception if policy removed
						RetryPolicy = new SqlServerRetryPolicy(retryCount, delay, null)
					};
					return db;
				};
			}
			public ITable<User> Users => GetTable<User>();

			public MyDB()
			{
			}

			public MyDB(string configuration)
				: base(configuration)
			{
			}
			public MyDB(IDataProvider dataProvider, string connectionString) : base(dataProvider, connectionString)
			{
			}
		}

		public class User
		{
			[PrimaryKey, NotNull] public Guid Id { get; set; }
			[Column, Nullable] public string Name { get; set; }
		}

		private Func<MyDB> _dbFactory;

		[OneTimeSetUp]
		public void SetUp()
		{
			CultureInfo.CurrentCulture = CultureInfo.GetCultureInfo("en-US");
			CultureInfo.CurrentUICulture = CultureInfo.GetCultureInfo("en-US");

			var dbConnStr = ConfigHelper.GetAppSetting("froldb-conn-str");
			_dbFactory = MyDB.CreateFactory(dbConnStr, 1, TimeSpan.FromSeconds(1));
		}

		[Test]
		public void TestConcurrentSelect()
		{
			// Ensures that concurrent async queries for multiple db instances are handled correctly
			using (var db1 = _dbFactory())
			using (var db2 = _dbFactory())
			{
				var user1Task = db1.Users.FirstAsync();
				var user2Task = db2.Users.FirstAsync();

				Assert.DoesNotThrowAsync(() => Task.WhenAll(user1Task, user2Task));

				Assert.IsNotNull(user1Task.Result);
				Assert.IsNotNull(user2Task.Result);
			}
		}
	}
```

The `TestConcurrentSelect` method fails with
```
Expected: No Exception to be thrown
  But was:  <System.InvalidOperationException: The connection was not closed. The connection's current state is open.
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpenInner(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Data.RetryPolicy.RetryingDbConnection.<<OpenAsync>b__20_0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Data.RetryPolicy.RetryPolicyBase.<>c__DisplayClass21_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Data.RetryPolicy.RetryPolicyBase.<ExecuteImplementationAsync>d__22`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Data.RetryPolicy.RetryPolicyBase.<ExecuteAsync>d__21.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Data.RetryPolicy.RetryingDbConnection.<OpenAsync>d__20.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Data.DataConnection.<EnsureConnectionAsync>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Data.DataConnection.QueryRunner.<ExecuteReaderAsync>d__27.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Linq.QueryRunner.<ExecuteQueryAsync>d__10`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass3_0`1.<<GetFirstElement>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Linq.ExpressionQuery`1.<LinqToDB-Linq-IQueryProviderAsync-ExecuteAsync>d__17`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NUnit.Framework.Internal.AsyncInvocationRegion.AsyncTaskInvocationRegion.WaitForPendingOperationsToComplete(Object invocationResult)
   at NUnit.Framework.Constraints.ThrowsConstraint.ExceptionInterceptor.Intercept(Object invocation)>
   at Linq2Db.SimpleLinq2DbTests.TestConcurrentSelect() 
```

### Steps to reproduce
Run tests from sample above.

### Environment details
linq2db version: *2.0.0*  
Database Server: *MS Sql 2012*  
Database Provider: *SqlServerDataProvider("mssql", SqlServerVersion.v2012);*  
Operating system: *Windows 10*  
Framework version: *.NET Framework 4.7.1*

**Comment by sdanyliv** [comment]
@andrewvk, can you look at this? 
Thanks.
