### ISSUE TITLE
Xamarin. Sqlite. Build error

### ISSUE THREAD

**Issue by Igonik** [linq2db/linq2db#1175]
Visual Studio 2017

1. Create empty Xamarin Android XAML App project
2. Install linq2db.SQLite 1.9.0 nuget package
3. Build solution

``
Error		Exception while loading assemblies: Java.Interop.Tools.Diagnostics.XamarinAndroidException: error XA0009: Error while loading assembly: C:\Users\mailm\.nuget\packages\system.runtime.loader\4.3.0\lib\MonoAndroid10\_._ ---> System.BadImageFormatException: Format of the executable (.exe) or library (.dll) is invalid.
   at Mono.Cecil.PE.ImageReader.ReadImage()
   at Mono.Cecil.PE.ImageReader.ReadImage(Disposable`1 stream, String file_name)
   at Mono.Cecil.ModuleDefinition.ReadModule(String fileName, ReaderParameters parameters)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.ReadAssembly(String file)
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Load(String fileName, Boolean forceLoad)
   --- End of inner exception stack trace ---
   at Java.Interop.Tools.Cecil.DirectoryAssemblyResolver.Load(String fileName, Boolean forceLoad)
   at Xamarin.Android.Tasks.ResolveAssemblies.ResolveRuntimeAssemblyForReferenceAssembly(LockFile lockFile, DirectoryAssemblyResolver resolver, String assemblyPath)
   at Xamarin.Android.Tasks.ResolveAssemblies.Execute(DirectoryAssemblyResolver resolver)	App2.Android			``

Tried on x86 and x64 platforms.

**Comment by MaceWindu** [comment]
Why do you use 1.9? It is very old version, you should try 2.0

**Comment by MaceWindu** [comment]
Hmm, I see that linq2db.SQLite 2.0.0 doesn't install in this type of project
```
NU1202: Package System.Data.SQLite.Core 1.0.107 is not compatible with monoandroid81 (MonoAndroid,Version=v8.1). Package System.Data.SQLite.Core 1.0.107 supports:
  - net20 (.NETFramework,Version=v2.0)
  - net40 (.NETFramework,Version=v4.0)
  - net45 (.NETFramework,Version=v4.5)
  - net451 (.NETFramework,Version=v4.5.1)
  - net46 (.NETFramework,Version=v4.6)
Package restore failed. Rolling back package changes for 'App1.Android'.
```

**Comment by MaceWindu** [comment]
As workaround I would recommend to add linq2db package and copy t4 templates from non-xamaring project manually

**Comment by Igonik** [comment]
@MaceWindu thanks. I have 
1. created .NET Standart 2.0 Class Library project
2. installed linq2db 2.0.0 and Microsoft.Data.Sqlite 2.1.0 nuget packages
3. added reference from my android project (Android 5.0) to .NET Standart 2.0 Class Library project

All works fine.

**Comment by MaceWindu** [comment]
For next release we will add new T4 package linq2db.SQLite.MS with Microsoft.Data.Sqlite provider reference. 

Also System.Data.SQLite released netstandard2.0 support several days ago, so existing package should also work
