### ISSUE TITLE
Error for ExpressionMethod with default DateTime

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#1189]
DB-Probider: Firebird
Linq2dB: Version 2.0.0

If I use the following ExpressionMethod I get a FbException for 'Data type unknown'

(The following code is a test sample with no realistic sense)

```
[Table("CUSTOMER", IsColumnAttributeRequired = true)]
public partial class Customer
{

    [Column("ID"), PrimaryKey, NotNull] public int Id { get; set; } // integer

    [Column("NAME"), NotNull] public string Name { get; set; } // varchar(20)

    [ExpressionMethod(nameof(DefaultDateTime), IsColumn = true)]
    //[Column("TO_DELETE")]
    public DateTime? ToDelete{ get; set; }

    static Expression<Func<Customer, DateTime>> DefaultDateTime()
    {
       return p => Sql.AsSql(DateTime.Now); 
    }
}
```

```
List<Customer> customers;
using (var context = new DbContext())
{
   customers= context.GetTable<Customer>().Where(k => k.ToDelete <= DateTime.Now).ToList();
 }
```

Exception:

FirebirdSql.Data.FirebirdClient Information: 0 : Command:
SELECT
	t1.ID,
	t1.NAME,
	'2001-01-01 01:01:01' as c1
FROM
	KUNDE t1
WHERE
	@p1 <= @p2

Parameters:
Name:p1	Type:TimeStamp	Used Value:14.06.2018 09:15:59
Name:p2	Type:TimeStamp	Used Value:14.06.2018 09:15:59

FirebirdSql.Data.FirebirdClient.FbException
  HResult=0x80004005
  Message=Dynamic SQL Error
SQL error code = -804
Data type unknown
  Source=FirebirdSql.Data.FirebirdClient
  StackTrace:
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteReader(CommandBehavior behavior) in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:line 517
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteDbDataReader(CommandBehavior behavior) in C:\Users\Jiri\Documents\devel\NETProvider\working\Provider\src\FirebirdSql.Data.FirebirdClient\FirebirdClient\FbCommand.cs:line 623
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 1167
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 429
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__9`1.MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 339
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ICA.WinCard.Gateway.Program.Main(String[] args) in C:\Users\User1\Documents\Visual Studio 2017\Projects\Test\Program.cs:line 191

Inner Exception 1:
IscException: Dynamic SQL Error
SQL error code = -804
Data type unknown

**Comment by Franki1986** [comment]
This seems to work, but should the other one not work also?

```
static Expression<Func<Customer, DateTime>> DefaultDateTime()
{
   return p => Sql.CurrentTimestamp;
 }
```

**Comment by sdanyliv** [comment]
@Franki1986, looks like it is specific of how to work with datet time. Better to remove Sql.AsSql and let linq2db evaluate value on client side without transferring not needed data over network.

**Comment by Franki1986** [comment]
Ok, I will use the working method

**Comment by Franki1986** [comment]
I I use a Nullable DateTime there is no way that this works.

For strings and numbers everything works fine :

      static Expression<Func<Customer, string>> GetNullable()
      {
         return (c) => null;
      }

      static Expression<Func<Customer, int?>> GetNullable()
      {
         return (c) => null;
      }

**Comment by Franki1986** [comment]
Ok, I executed it with the default Firebird Ado.Net provider with FbCommand and command parameter. This gives the same error. 
The only workaround I have found is create a custom expression:

```
      [Sql.Expression("CAST(NULL as TIMESTAMP)", ServerSideOnly = true)]
      public static DateTime? DefaultDateTimeNullable()
      {
         return null;
      }
```

then this works:

```
      static Expression<Func<Customer, DateTime?>> GetNullable()
      {
         return (c) => DefaultDateTimeNullable();
      }
```

**Comment by MaceWindu** [comment]
Retested it.
Original issue is another case of Firebird having issues with understanding types of parameters. Most of it fixed in preview 2 but this specific case should be still broken.
Anyway, now it fails for all providers with 
`.LinqException : Sequence 'AsSql(DateTime.Now)' cannot be converted to SQL.` which is probably regressin
