### ISSUE TITLE
Can't create temp table

### ISSUE THREAD

**Issue by integral-llc** [linq2db/linq2db#1245]
Sample code to create a temp table
```
        protected override async Task<JobPagedInfo> GetLatestOutgoingEntriesAsyncCore(List<int> forFabricatorIds, JobRecordKind recordKind, int page, int pageSize)
        {
            using (var dc = _database.Context)
            {
                var tempTable = dc.CreateTempTable(forFabricatorIds, tableName: "Fabricators");
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near ')' at line 3
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 1040
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 759
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass28_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 752
   at LinqToDB.Linq.QueryRunner.CreateTable`1.Query(IDataContext dataContext, String tableName, String databaseName, String schemaName, String statementHeader, String statementFooter, DefaultNullable defaultNullable) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.CreateTable.cs:line 40
   at LinqToDB.TempTable`1..ctor(IDataContext db, IEnumerable`1 items, BulkCopyOptions options, String tableName, String databaseName, String schemaName) in C:\projects\linq2db\Source\LinqToDB\TempTable.cs:line 71
   at LinqToDB.DataExtensions.CreateTempTable[T](IDataContext db, IEnumerable`1 items, BulkCopyOptions options, String tableName, String databaseName, String schemaName) in C:\projects\linq2db\Source\LinqToDB\TempTable.cs:line 354
   at GFD2.Sync.Core.Repository.AwsMySqlSyncRepository.GetLatestOutgoingEntriesAsyncCore(List`1 forFabricatorIds, JobRecordKind recordKind, Int32 page, Int32 pageSize) in D:\z\projects\QC\GFD2\src\GFD2.Sync.Core\Repository\AwsMySqlSyncRepository.cs:line 119
   at GFD2.Sync.Core.Repository.SyncRepository.GetLatestOutgoingEntriesAsync(List`1 forFabricatorIds, JobRecordKind recordKind, Nullable`1 page, Nullable`1 pageSize) in D:\z\projects\QC\GFD2\src\GFD2.Sync.Core\Repository\SyncRepository.cs:line 32
   at GFD2.Sync.WebApi.Controllers.CustomerController.Get(Nullable`1 page, Nullable`1 pageSize) in D:\z\projects\QC\GFD2\src\GFD2.Sync.WebApi\Controllers\CustomerController.cs:line 64
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Cors.Infrastructure.CorsMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Hosting.Internal.RequestServicesContainerMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.Frame`1.ProcessRequestsAsync()
```

### Steps to reproduce
Using the code above

### Environment details
linq2db version: *2.1.0*
Database Server: *E.g. MySql 5.7.22*
Operating system: *E.g. Windows 10*
Framework version: *.NET Core 2.1*

**Comment by MaceWindu** [comment]
I suspect it is a case of #749
Probably you have colum with type, for which linq2db fails to generate proper db type.
If it is so, just specify proper DbType in column mapping as workaround

**Comment by MaceWindu** [comment]
@integral-llc could you provide generated query and/or JobPagedInfo definition?

**Comment by MaceWindu** [comment]
Moving it to 2.4.0 as we don't have much time to test it for all types and need information about which type generated incorrectly.

**Comment by Corey-M** [comment]
@integral-llc Just tried to replicate on MS SQL, SQLite and MySQL.  All of them failed to create a table from a `List<int>` with some variation on the theme of "You have an error in your SQL syntax".

On MSSQL the generated SQL to create the table was:

    CREATE TABLE [Fabricators]
    (
    )

The main problem seems to be that it can't create a table from `List<int>`.  You'll need an intermediate type that has properties the table generator can use as columns, which `int` does not.

Try this:

    protected override async Task<JobPagedInfo> GetLatestOutgoingEntriesAsyncCore(List<int> forFabricatorIds, JobRecordKind recordKind, int page, int pageSize)
    {
        using (var dc = _database.Context)
        {
            var ids = forFabricatorIds.Select(_ => new { Id = _ }).ToArray();
            var tempTable = dc.CreateTempTable(forFabricatorIds, tableName: "Fabricators");
            //... rest of your code here...

On MySQL my tests had this for the Create Table section:

	CREATE TABLE `Fabricators`
	(
		`Id` Int NOT NULL
	)

This is a normal table rather than temporary (refer to first comment from sdanyliv) so you'll have to drop it manually after you are finished with it.  At least until temporary table support for MySQL is available.

**Comment by Corey-M** [comment]
@sdanyliv Not really a bug in the library, unless you count failing to notice that there are no columns to create the table from as being a bug.

**Comment by MaceWindu** [comment]
Bah, @Corey-M is correct. This is not a correct way to use this API
