### ISSUE TITLE
Correct way to implement arbitrary number of joins with the same table using linq2db

### ISSUE THREAD

**Issue by glebkozh** [linq2db/linq2db#1309]
Hello!

I'd like to ask if there is correct way to perform multiple joins with the same table using linq2db. I tried the following solution:

```c#
 var result =
                files.Select(file => new FileContainer { File = file, Attributes = new Attribute[0] })
                    .LeftJoin(
                        attributes.Where(attribute => attribute.Name == attributeName1),
                        (fileContainer, attribute) => fileContainer.File.Id == attribute.FileId,
                        (fileContainer, attribute) => new FileContainer
                        {
                            File = fileContainer.File,
                            Attributes = fileContainer.Attributes.Concat(new[] { attribute }).ToArray()
                        })
                    .LeftJoin(
                        attributes.Where(attribute2 => attribute2.Name == attributeName2),
                        (fileContainer, attribute2) => fileContainer.File.Id == attribute2.FileId,
                        (fileContainer, attribute2) => new FileContainer
                        {
                            File = fileContainer.File,
                            Attributes = fileContainer.Attributes.Concat(new[] { attribute2 }).ToArray()
                        })
                    .ToList();
```
Here I join File table with Attribute table two times and try to store retrieved attributes in array. I receive the exception:

```
LinqToDB.Linq.LinqException : Sequence 'fileContainer.Attributes.Concat(new [] {attribute}).ToArray()' cannot be converted to SQL.
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 167
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 232
   at LinqToDB.Linq.Builder.ExpressionBuilder.SubQueryToSql(IBuildContext context, MethodCallExpression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 0
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 647
   at LinqToDB.Linq.Builder.SelectContext.ConvertExpressions(Expression expression, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 401
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 342
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 554
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 430
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 211
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 151
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 139
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass74_0.<BuildExpression>b__0(Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 49
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1354
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1338
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1436
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1338
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1436
   at LinqToDB.Expressions.Extensions.<>c__DisplayClass34_0.<Transform>g__Modify|1(MemberBinding b) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1500
   at LinqToDB.Expressions.Extensions.Transform2[T](ICollection`1 source, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1322
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1546
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 50
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 112
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 65
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 161
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 269
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 233
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 84
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 179
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```
If I perform only one join (file with attribute), everything works fine.
Then, I gave a try to the following recurisve structure:

 ```c#
 var result2 =
                files.Select(file => new FileContainer2 { File = file, Container = new AttributeContainer() })
                    .LeftJoin(
                        attributes.Where(attribute => attribute.Name == attributeName1),
                        (fileContainer2, attribute) => fileContainer2.File.Id == attribute.FileId,
                        (fileContainer2, attribute) => new FileContainer2
                        {
                            File = fileContainer2.File,
                            Container = new AttributeContainer { Attribute = attribute, Container = fileContainer2.Container}
                        })
                    .LeftJoin(
                        attributes.Where(attribute2 => attribute2.Name == attributeName2),
                        (fileContainer2, attribute2) => fileContainer2.File.Id == attribute2.FileId,
                        (fileContainer2, attribute2) => new FileContainer2
                        {
                            File = fileContainer2.File,
                            Container = new AttributeContainer { Attribute = attribute2, Container = fileContainer2.Container }
                        })
                    .ToList();
```
In this case I receive the following exception:

```
System.InvalidOperationException : variable 'attribute' of type '<...>.Attribute' referenced from scope '', but it is not defined
   at System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node)
   at System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberAssignment(MemberAssignment node)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberBinding(MemberBinding node)
   at System.Linq.Expressions.ExpressionVisitor.Visit[T](ReadOnlyCollection`1 nodes, Func`2 elementVisitor)
   at System.Linq.Expressions.ExpressionVisitor.VisitMemberInit(MemberInitExpression node)
   at System.Linq.Expressions.MemberInitExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.VisitBinary(BinaryExpression node)
   at System.Linq.Expressions.BinaryExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitInvocation(InvocationExpression node)
   at System.Linq.Expressions.InvocationExpression.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.ExpressionVisitor.Visit(ReadOnlyCollection`1 nodes)
   at System.Linq.Expressions.Compiler.VariableBinder.VisitLambda[T](Expression`1 node)
   at System.Linq.Expressions.Expression`1.Accept(ExpressionVisitor visitor)
   at System.Linq.Expressions.Compiler.VariableBinder.Visit(Expression node)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at System.Linq.Expressions.Expression`1.Compile(Boolean preferInterpretation)
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 51
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 343
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```
Again, it works fine with the single join, but fails with two joins.
Please note, that I cannot use just 
new 
```c#
{
  File,
  Attribute,
  Attribute2
}
```
as the actual join clauses are expected to be constructed in runtime.
Thanks!

### Environment details
linq2db version: *2.3.0*
Database Server: *Sql Server 2016*
Framework version: *.NET Core 2.1*

**Comment by sdanyliv** [comment]
It is Eager loading with complex projection. Unfortunately it is not supported.
You have to rewrite your query and join items on the client side by yourself.
```cs
var attributeName1 = "N1";
var attributeName2 = "N2";

var containers = files
	.Select(file => new FileContainer
		{ File = file, Attributes = Array.Empty<Attribute>() })
	.ToDictionary(file => file.File.Id);

var attributesLookup =
	files
		.InnerJoin(
			attributes.Where(attribute =>
				attribute.Name == attributeName1 || attribute.Name == attributeName2),
			(file, attribute) => file.Id == attribute.FileId,
			(file, attribute) => new
			{
				FileId = file.Id,
				Attribute = attribute
			})
		.ToLookup(v => v.FileId, v => v.Attribute);

foreach (var g in attributesLookup)
{
	containers[g.Key].Attributes = g.ToArray();
}

var result = containers.Values.ToArray();
```

**Comment by glebkozh** [comment]
Ok, @sdanyliv, thank you

**Comment by glebkozh** [comment]
@sdanyliv Unfortunately, client side joins are not desired in terms of memory and performance. I've tried the solution using runtime projection class generation, and it worked, but it is not very convenient. Then I've encountered this [PR](https://github.com/linq2db/linq2db/pull/964): it seems that [DynamicColumnsStore] has similar design intention (to store arbitrary number of column values), but as far as I know, it can only be applied to table entities, not to join results. Is there any way to represent join results as a kind of "table" projection class with DynamicColumnsStore property filled? Thanks!

**Comment by sdanyliv** [comment]
DynamicColumnsStore stores only field values of the same record, no joins.
Where do you have performance penalty? For sure before retrieving files you have to filter them.

We do not support Eager loading - loading records with joined details.

**Comment by glebkozh** [comment]
@sdanyliv, Oh, I see, thanks
