### ISSUE TITLE
hi bug plz help me

### ISSUE THREAD

**Issue by MajidSafari** [linq2db/linq2db#1344]
| Mapping of column Name value failed, see inner exception for details | Input string was not in a correct format.   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
   at lambda_method(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__9`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

**Comment by sdanyliv** [comment]
@MajidSafari, you have to provide us with more details.
Model, steps to reproduce.

**Comment by MaceWindu** [comment]
Also provide information, requested in issue template.

**Comment by MaceWindu** [comment]
Closing, reopen when more details provided
