### ISSUE TITLE
DataType.SByte missing from LinqToDB.SqlQuery.SqlDataType.GetDataType

### ISSUE THREAD

**Issue by Corey-M** [linq2db/linq2db#1351]
Working with a third-party MySQL database which has fields that are declared as `tinyint(4)`.  The T4 templates generate POCOs that have these fields as `sbyte` but attempts to query against these fields results in an exception (see below) due to a missing case in `SqlDataType.GetDataType`.  The case `DataType.SByte` needs to be added to the list.

```
InvalidOperationException: Unexpected type: SByte
Stack trace:

at LinqToDB.SqlQuery.SqlDataType.GetDataType(DataType type)
   at LinqToDB.SqlQuery.SqlDataType..ctor(DataType dbType, Type type)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildExpression(ISqlExpression expr, Boolean buildTableName, Boolean checkParentheses, String alias, Boolean& addAlias, Boolean throwExceptionIfTableNotFound)
   at LinqToDB.DataProvider.MySql.MySqlSqlBuilder.BuildExpression(ISqlExpression expr, Boolean buildTableName, Boolean checkParentheses, String alias, Boolean& addAlias, Boolean throwExceptionIfTableNotFound)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildExpression(Int32 parentPrecedence, ISqlExpression expr, String alias, Boolean& addAlias)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildExpression(Int32 precedence, ISqlExpression expr)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildPredicateX(ExprExpr expr)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildPredicate(ISqlPredicate predicate)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildPredicate(Int32 parentPrecedence, Int32 precedence, ISqlPredicate predicate)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSearchCondition(SqlSearchCondition condition)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSearchCondition(Int32 parentPrecedence, SqlSearchCondition condition)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildWhereSearchCondition(SelectQuery selectQuery, SqlSearchCondition condition)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildWhereClause(SelectQuery selectQuery)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSelectQuery(SqlSelectStatement selectStatement)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql()
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql(Int32 commandNumber, SqlStatement statement, StringBuilder sb, Int32 indent, Boolean skipAlias)
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql(Int32 commandNumber, SqlStatement statement, StringBuilder sb, Int32 startIndent)
   at LinqToDB.Data.DataConnection.QueryRunner.GetCommand(DataConnection dataConnection, IQueryContext query, Int32 startIndent)
   at LinqToDB.Data.DataConnection.QueryRunner.SetQuery(DataConnection dataConnection, IQueryContext queryContext, Int32 startIndent)
   at LinqToDB.Data.DataConnection.QueryRunner.SetQuery()
   at LinqToDB.Linq.QueryRunnerBase.SetCommand(Boolean clearQueryHints)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__9`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at UserQuery
--
```

### Steps to reproduce
Create a table with `sbyte` fields.  Write any query that tests the value of one of these fields.

### Environment details
linq2db version: *2.4.0*
Database Server: *MySQL 5.6.28*
Framework version: *.NET Framework 4.6.2*

**Comment by Corey-M** [comment]
Also affects SQLite, possibly others.  Test as follows:

		public class T1351Model
		{
			public int ID { get; set; }
			public sbyte TestField { get; set; }
			public sbyte? TestNullable { get; set; }
		}

		[Test, DataContextSource(false)]
		public void TestSByteQuery(string context)
		{
			using (var db = new DataConnection(context))
			using (var table = db.CreateTempTable<T1351Model>())
			{
				Assert.DoesNotThrow(() => table.Where(_ => _.TestField == 0).ToArray(), "Compare `sbyte`");
				Assert.DoesNotThrow(() => table.Where(_ => _.TestNullable != 1).ToArray(), "Compare `sbyte?` to non-null");
			}
		}

**Comment by sdanyliv** [comment]
@Corey-M, i have noticed that you create PRs from your `master`. It limits you to create only one PR until we merege it. Also it makes your master branch not clean.
Github flow is the following: you create branch from `master` in your fork, for example `issue_1351`, make changes and create PR from this branch. In this case you can work on several issues simultaneously.

**Comment by Corey-M** [comment]
@sdanyliv Yeah, I figured that out last night :disappointed:.  I'm not that good at Git, but I'm getting better.  Was just about to try to fix that by seeing if I could refresh a fork on my repo from master on this.  Will PR when I get it working :smile:.
