### ISSUE TITLE
Insert null for fields with custom property type

### ISSUE THREAD

**Issue by genusP** [linq2db/linq2db#1373]
I define custom type for Column and register convert expressions in MappingSchema.
Where insert entity and set column value then works correctly. If value is null then throws exception.
```
System.NullReferenceException: Object reference not set to an instance of an object.
    at lambda_method(Closure , Expression , Object[] )
    at LinqToDB.Linq.QueryRunner.SetParameters(Query query, IDataContext dataContext, Expression expression, Object[] parameters, Int32 queryNumber) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 164
    at LinqToDB.Linq.QueryRunnerBase.SetCommand(Boolean clearQueryHints) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunnerBase.cs:line 67
    at LinqToDB.Data.DataConnection.QueryRunner.SetCommand() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 266
    at LinqToDB.Data.DataConnection.QueryRunner.ExecuteScalarAsync(CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 530
    at LinqToDB.Linq.QueryRunner.ScalarQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 727
Satellite.Host>    at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken token) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 89
    at LinqToDB.LinqExtensions.InsertWithIdentityAsync[T](ITable`1 target, Expression`1 setter, CancellationToken token) in C:\projects\linq2db\Source\LinqToDB\LinqExtensions.cs:line 1075
    at Satellite.Core.Services.Store.CRUDStore`1.OnInsertAsync(Expression`1 setter, Expression`1 selector, CancellationToken cancellation)
    at Satellite.Core.Services.Store.CRUDStoreBase`1.InsertAsync(Expression`1 setter, Expression`1 selector, CancellationToken cancellation)
    at Satellite.BDA.Services.RequestsManager.AddVariantsAsync(Int32 requestId, IEnumerable`1 variants, CancellationToken cancellation)
```

### Steps to reproduce
```c#
[TestFixture]
	public class MyTest:TestBase
	{
		class CustomFieldType
		{
			public string Field1 { get; set; }

			public static CustomFieldType FromString(string str)
			{
				if (string.IsNullOrEmpty(str))
					return null;
				return new CustomFieldType { Field1 = str };
			}

			public override string ToString()
			{
				return Field1;
			}
		}

		[Table]
		class Entity
		{
			[PrimaryKey, Identity] public int Id { get; set; }
			[Column] public CustomFieldType Field1 { get; set; }
		}

		[Test, DataContextSource]
		public void Test1(string context)
		{
			MappingSchema.Default.SetConvertExpression<string, CustomFieldType>(s => CustomFieldType.FromString(s));
			MappingSchema.Default.SetConvertExpression<CustomFieldType, DataParameter>(_ => new DataParameter(null, _.ToString()));
			using (var db = GetDataContext(context))
			{
				db.InsertWithIdentity(new Entity
				{
					Field1 = null
				});
			}
		}
	}
```

### Environment details
linq2db version: 2.4.0
Database Server: MS SQL Server 2008
Operating system: Windows 10
Framework version: .NET Core 2.1

**Comment by genusP** [comment]
Maybe need call code from converter expression for generate correct DataParameter. DataParemter provides DataType.

**Comment by MaceWindu** [comment]
I'm going to close it without action as I'm not convinced that linq2db do anything wrong here.

you should set 3rd parameter of `SetConvertExpression` to false for `DataParameter` conversion and specify DataType [in](https://github.com/linq2db/linq2db/commit/b87a10ceb6de5128c661fa3c2daeb31a9060126c#diff-c8f2da14011124a07c0e37f4a28b44baR101) [conversion](https://github.com/linq2db/linq2db/commit/b87a10ceb6de5128c661fa3c2daeb31a9060126c#diff-c8f2da14011124a07c0e37f4a28b44baR135) or [on mapped field](https://github.com/linq2db/linq2db/commit/b87a10ceb6de5128c661fa3c2daeb31a9060126c#diff-c8f2da14011124a07c0e37f4a28b44baR56)

It doesn't make sense to add special code for `DataParameter` conversion with `addNullCheck=true` on linq2db side, as we still need to have type information for parameter for most of databases when we pass null value in parameter
