### ISSUE TITLE
Can't install linq2db.SQLite package

### ISSUE THREAD

**Issue by Vort** [linq2db/linq2db#1401]
When I try to install linq2db.SQLite package, error is popping out:

```
Attempting to gather dependency information for package 'linq2db.SQLite.2.5.2' with respect to project 'ConsoleApplication70', targeting '.NETFramework,Version=v4.6.1'
Gathering dependency information took 2,3 sec
Attempting to resolve dependencies for package 'linq2db.SQLite.2.5.2' with DependencyBehavior 'Lowest'
Resolving dependency information took 0 ms
Resolving actions to install package 'linq2db.SQLite.2.5.2'
Resolved actions to install package 'linq2db.SQLite.2.5.2'
Retrieving package 'linq2db.SQLite 2.5.2' from 'nuget.org'.
Adding package 'linq2db.SQLite.2.5.2' to folder 'e:\_Projects\_Test\ConsoleApplication70\packages'
Added package 'linq2db.SQLite.2.5.2' to folder 'e:\_Projects\_Test\ConsoleApplication70\packages'
Install failed. Rolling back...
Package 'linq2db.SQLite.2.5.2 : linq2db [2.5.2, ), System.Data.SQLite.Core [1.0.107, )' does not exist in project 'ConsoleApplication70'
Removing package 'linq2db.SQLite.2.5.2 : linq2db [2.5.2, ), System.Data.SQLite.Core [1.0.107, )' from folder 'e:\_Projects\_Test\ConsoleApplication70\packages'
Removed package 'linq2db.SQLite.2.5.2 : linq2db [2.5.2, ), System.Data.SQLite.Core [1.0.107, )' from folder 'e:\_Projects\_Test\ConsoleApplication70\packages'
Executing nuget actions took 956,07 ms
Microsoft.Build.Exceptions.InvalidProjectFileException: The default XML namespace of the project must be the MSBuild XML namespace. If the project is authored in the MSBuild 2003 format, please add xmlns="http://schemas.microsoft.com/developer/msbuild/2003" to the <Project> element. If the project has been authored in the old 1.0 or 1.2 format, please convert it to MSBuild 2003 format.  e:\_Projects\_Test\ConsoleApplication70\packages\linq2db.SQLite.2.5.2\build\linq2db.SQLite.props
   at Microsoft.Build.Shared.ProjectErrorUtilities.ThrowInvalidProject(String errorSubCategoryResourceName, IElementLocation elementLocation, String resourceName, Object[] args)
   at Microsoft.Build.Construction.ProjectParser.Parse()
   at Microsoft.Build.Construction.ProjectParser.Parse(XmlDocumentWithLocation document, ProjectRootElement projectRootElement)
   at Microsoft.Build.Construction.ProjectRootElement..ctor(String path, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext)
   at Microsoft.Build.Construction.ProjectRootElement.CreateProjectFromPath(String projectFile, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext)
   at Microsoft.Build.Construction.ProjectRootElement.<>c__DisplayClass170_0.<OpenProjectOrSolution>b__0(String path, ProjectRootElementCache cache)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Construction.ProjectRootElement.OpenProjectOrSolution(String fullPath, IDictionary`2 globalProperties, String toolsVersion, ILoggingService loggingService, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Evaluation.Evaluator`4.<>c__DisplayClass57_1.<ExpandAndLoadImports>b__0(String p, ProjectRootElementCache c)
   at Microsoft.Build.Evaluation.ProjectRootElementCache.Get(String projectFile, OpenProjectRootElement openProjectRootElement, Boolean isExplicitlyLoaded)
   at Microsoft.Build.Evaluation.Evaluator`4.ExpandAndLoadImports(String directoryOfImportingFile, String importExpressionEscaped, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.EvaluateImportElement(String directoryOfImportingFile, ProjectImportElement importElement)
   at Microsoft.Build.Evaluation.Evaluator`4.PerformDepthFirstPass(ProjectRootElement currentProjectOrImport)
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate()
   at Microsoft.Build.Evaluation.Evaluator`4.Evaluate(IEvaluatorData`4 data, ProjectRootElement root, ProjectLoadSettings loadSettings, Int32 maxNodeCount, PropertyDictionary`1 environmentProperties, ILoggingService loggingService, IItemFactory`2 itemFactory, IToolsetProvider toolsetProvider, ProjectRootElementCache projectRootElementCache, BuildEventContext buildEventContext, ProjectInstance projectInstanceIfAnyForDebuggerOnly)
   at Microsoft.Build.Evaluation.Project.ReevaluateIfNecessary(ILoggingService loggingServiceForEvaluation)
   at NuGet.PackageManagement.VisualStudio.MicrosoftBuildEvaluationProjectUtility.AddImportStatement(Project msBuildProject, String targetsPath, ImportLocation location)
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.<>c__DisplayClass39_0.<<AddImport>b__0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.VisualStudio.Threading.JoinableTask.CompleteOnCurrentThread()
   at NuGet.PackageManagement.VisualStudio.VSMSBuildNuGetProjectSystem.AddImport(String targetFullPath, ImportLocation location)
   at NuGet.ProjectManagement.MSBuildNuGetProject.<InstallPackageAsync>d__33.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at NuGet.PackageManagement.NuGetPackageManager.<ExecuteNuGetProjectActionsAsync>d__54.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<ExecuteActionsAsync>d__8.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at NuGet.PackageManagement.UI.UIActionEngine.<PerformActionImplAsync>d__6.MoveNext()
========== Finished ==========
Time Elapsed: 00:00:05.8445504
```

### Environment details
linq2db version: *2.5.2*
Operating system: *Windows 7 SP1 x64*
Framework version: *.NET Framework 4.6.1*
Visual Studio version: *14.0.25431.01 Update 3*

**Comment by sdanyliv** [comment]
@Vort, thanks for reporting we will figure out what happened here. It is reproducible in prior versions?

As a workaround:
Linq2db contains SqLite provider in package `linq2db`. So you can use only this package. Additionally you have to install `System.Data.SQLite.Core` by yourself and package `linq2db.t4models`, if you need T4 support.

**Comment by MaceWindu** [comment]
You need to install required packages manually as @sdanyliv said.

As I can found this exception thrown when you try to open .net core format projects, supoported only by VS2017 using VS2015.
Currently we don't test our nugets for compatibility with VS2015.

**Comment by MaceWindu** [comment]
I will try to add namespace to props files. If it will not break VS2017 support - we can release fix in next version.
