### ISSUE TITLE
Database do not support CROSS/OUTER APPLY join required by the query

### ISSUE THREAD

**Issue by iouris** [linq2db/linq2db#1426]
Hi Guys,

I'm targeting SQLite - instead of SQL Server - in my unit test, and the following query results in an error:

```
var qrecalls =
    from ra in dbContext.Every<RecareAvailability>()

    join rt in dbContext.Every<RecareType>() on ra.RecareTypeId equals rt.Id

    join p in dbContext.Every<Patient>() on ra.PatientId equals p.Id

    join si in dbContext.Every<ScheduleItem>() on ra.AppointmentId equals si.Id into sis
    from si in sis.Take(1).DefaultIfEmpty()

    orderby p.Id

    select new Recall
    {
    };

```
Please note sis.Take(1) - this is the cause of the error.

I'm wondering if there is a workaround, or if not, if the issue can be fixed by generating an SQL with an operation that is alternative to APPLY.

Much appreciated

Iouri

linq2db 2.5.2 (.net core)

```
Result StackTrace:	
at LinqToDB.SqlQuery.SelectQueryOptimizer.OptimizeApply(HashSet`1 parentTableSources, SqlTableSource tableSource, SqlJoinedTable joinTable, Boolean isApplySupported, Boolean optimizeColumns) in C:\projects\linq2db\Source\LinqToDB\SqlQuery\SelectQueryOptimizer.cs:line 930
   at LinqToDB.SqlQuery.SelectQueryOptimizer.OptimizeApplies(Boolean isApplySupported, Boolean optimizeColumns) in C:\projects\linq2db\Source\LinqToDB\SqlQuery\SelectQueryOptimizer.cs:line 1032
   at LinqToDB.SqlQuery.SelectQueryOptimizer.FinalizeAndValidateInternal(Boolean isApplySupported, Boolean optimizeColumns, List`1 tables) in C:\projects\linq2db\Source\LinqToDB\SqlQuery\SelectQueryOptimizer.cs:line 418
   at LinqToDB.SqlQuery.SelectQueryOptimizer.FinalizeAndValidate(Boolean isApplySupported, Boolean optimizeColumns) in C:\projects\linq2db\Source\LinqToDB\SqlQuery\SelectQueryOptimizer.cs:line 46
   at LinqToDB.SqlProvider.BasicSqlOptimizer.<>c__DisplayClass4_0.<Finalize>b__0(SelectQuery selectQuery) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlOptimizer.cs:line 41
   at LinqToDB.SqlQuery.SqlStatementWithQueryBase.WalkQueries(Func`2 func) in C:\projects\linq2db\Source\LinqToDB\SqlQuery\SqlStatementWithQueryBase.cs:line 39
   at LinqToDB.SqlProvider.BasicSqlOptimizer.Finalize(SqlStatement statement) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlOptimizer.cs:line 45
   at LinqToDB.DataProvider.SQLite.SQLiteSqlOptimizer.Finalize(SqlStatement statement) in C:\projects\linq2db\Source\LinqToDB\DataProvider\SQLite\SQLiteSqlOptimizer.cs:line 18
   at LinqToDB.Linq.QueryRunner.FinalizeQuery(Query query) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 109
   at LinqToDB.Linq.QueryRunner.GetExecuteQuery[T](Query query, Func`7 queryFunc) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 262
   at LinqToDB.Linq.QueryRunner.SetRunQuery[T](Query`1 query, Expression`1 expression) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 522
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 161
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 269
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 233
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 84
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.IEnumerable.GetEnumerator() in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 188
   at Linquifier.LinquifiableQuery.GetEnumerator() in G:\soe\ascend-api\linquifier\LinquifiableQuery.cs:line 56
   at Linquifier.LinquifiableQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in G:\soe\ascend-api\linquifier\LinquifiableQuery.cs:line 116
   at System.Linq.Enumerable.TakeWhileIterator[TSource](IEnumerable`1 source, Func`2 predicate)+MoveNext()
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot)
--- End of stack trace from previous location where exception was thrown ---
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token) in C:\projects\linq2db\Source\LinqToDB\AsyncExtensions.cs:line 151
   
--- End of stack trace from previous location where exception was thrown ---

Result Message:	LinqToDB.LinqToDBException : Database do not support CROSS/OUTER APPLY join required by the query.
```

**Comment by iouris** [comment]
@sdanyliv , thank you for replying so quickly, I'll check and will let you know.

**Comment by sdanyliv** [comment]
@iouris, i have updated sample to be more readable. It should work if i correctly understand which SQL do you need.

**Comment by iouris** [comment]
@sdanyliv 
Svyatoslav, thank you for helping me out with this.

I have followed your suggestion - in a slightly different manner - managed to get the SQL generated the way I want it, however I get this error

````
Microsoft.Data.Sqlite.SqliteException: 'SQLite Error 1: 'near "(": syntax error'.'
````
even though the SQL looks correct to me - there is something about SQLLite perhaps which I'm not familiar with?

Do you mind please having a look - perhaps you can see what's wrong with it. 

Much appreciated!

The linq query:
````
var qpatients =
    from p in dbc.Every<Ascend.Patient>()

    join email in
        from email in dbc.Every<Ascend.PatientEmail>()
        let rn = Sql.Ext.RowNumber().Over().PartitionBy(email.Id).OrderBy(email.Id).ToValue()
        where rn == 1
        select email
    on p.PatientEmailId equals email.Id into gemails
    from email in gemails//.DefaultIfEmpty()

    select new { p.Id, emailId = (long?)email.Id };

var patients = qpatients.ToList();

````
Generated SQL found through qpatients.ToString():

````
--  SQLite.MS SQLite
SELECT
	[p].[PatientID],
	[gemails].[PatientEmailID] as [PatientEmailID1]
FROM
	[Patient] [p]
		INNER JOIN (
			SELECT
				ROW_NUMBER() OVER(PARTITION BY [t1].[PatientEmailID] ORDER BY [t1].[PatientEmailID]) as [c1],
				[t1].[PatientEmailID]
			FROM
				[PatientEmail] [t1]
		) [gemails] ON [p].[PatientEmailId] = [gemails].[PatientEmailID]
WHERE
	[gemails].[c1] = 1 AND [p].[OrganizationId] = 5012


`````

**Comment by MaceWindu** [comment]
Looks like Sqlite provider from Microsoft ships with sqlite without window functions support. I'm trying to find it in their documentation, but I would recommend to try system.data.sqlite provider instead. It supports netstandard2.0 in recent releases

**Comment by MaceWindu** [comment]
Yep, it requires SQLite 3.25, which is not available with microsoft's provider yet

**Comment by iouris** [comment]
@MaceWindu - thank you for looking into it.
I have tried System.Data.SQLite, however I'm still having this issue. 

Message: System.Data.SQLite.SQLiteException : SQL logic error near "(": syntax error

Is there anything else I could do?

**Comment by iouris** [comment]
@MaceWindu - please ignore my previous comment.

I've managed to get it working by following https://github.com/aspnet/Microsoft.Data.Sqlite/issues/526, see comment from bricelam.

**Comment by sdanyliv** [comment]
@iouris, closing as answered.
