### ISSUE TITLE
Columns to List Query

### ISSUE THREAD

**Issue by Fruchuxs** [linq2db/linq2db#1437]
Hello,

I have the following classes:

```c#
[Table("extra")]
class Extra {
   [PrimaryKey]
   public int SomeId {get;set;}
   [Column]
   public string Value {get;set;}
}

[Table("data")]
class Data {
   [PrimaryKey]
   public int SomeId {get;set;}
}

class DataModel {
  public int SomeId {get;set;}
  public List<ExtraModel > Extras {get;set;}
}

class ExtraModel {
  public string Value {get;set;}
}
```

and this Query:
```c#
(from data in fDataTable
join extra in fExtraTable
on data.SomeId equals extra.SomeId
select new ExtraModel() {
  SomeId = data.SomeId,
  Extras = new List<Extra>(new[] { new ExtraModel() { Value = extra.Value}}),
}).Where(p => p.Extras.Any(b => b.Value == "Hello World"));
```

As result I got `LinqToDB.Linq.LinqException: 'Invalid expression  p.Extras.Any(b => b.Value == "Hello World")'
`
```
   at LinqToDB.Linq.Builder.SelectContext.GetMemberExpression(Expression newExpression, Expression expression, Int32 level) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 1084
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T](Expression expression, MemberExpression levelExpression, Int32 level, Func`6 action) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 980
   at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 731
   at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 627
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T](Expression expression, MemberExpression levelExpression, Int32 level, Func`6 action) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 973
   at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 731
   at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 627
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T](Expression expression, MemberExpression levelExpression, Int32 level, Func`6 action) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 973
   at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 731
   at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 627
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T](Expression expression, MemberExpression levelExpression, Int32 level, Func`6 action) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 973
   at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 731
   at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 627
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T](Expression expression, MemberExpression levelExpression, Int32 level, Func`6 action) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 973
   at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 731
   at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 627
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertObjectComparison(ExpressionType nodeType, IBuildContext leftContext, Expression left, IBuildContext rightContext, Expression right) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1838
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1593
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1378
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1448
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2581
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2484
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 48
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\WhereBuilder.cs:line 23
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 175
   at LinqToDB.Linq.Builder.FirstSingleBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\FirstSingleBuilder.cs:line 25
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 175
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 146
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 269
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 233
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 84
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 165
   at System.Linq.Queryable.SingleOrDefault[TSource](IQueryable`1 source)
```

I know this seems a little bit arbitary, but we need to map a rather "dynamic" table structure in a more generic data structure (list).

**Comment by sdanyliv** [comment]
@Fruchuxs, it looks like eager loading which is not supported. Also it is challenge for Expression Parser to understand how to create SQL.

 We need here two queries and remapping on the client side.
```cs
var query = from data in fDataTable
where fExtraTable.Any(e = e.SomeId == data.SomeId && e.Value == "Hello World"))
select new ExtraModel
{
  SomeId = data.SomeId,
});

var data = query.ToList();

var extras = (from data in query
join extra in fExtraTable on data.SomeId equals extra.SomeId
select select new ExtraModel 
{
   extra.Value = data.Value
}).ToLookup(e => e.SomeId);

foreach (var d in data)
{
   d.Extras = new List<Extra>();
   if (extras.Contains(d.SomeId))
     d.Extras.AddRange(extras[d.SomeId])
}
```
These queries also can be simplified by associations:
```cs
[Table("data")]
class Data {
   [PrimaryKey]
   public int SomeId {get;set;}
 
   [Association(ThisKey = nameof(SomeId), OtherKey = nameof(Extra.SomeId))]
   public IEnumerable<Extra> Extras { get; set; }
}
```
```cs
var query = from data in fDataTable
where data.Extras.Any(e = e.Value == "Hello World"))
select data;

var data = query.Select(d => new ExtraModel { SomeId = d.SomeId }).ToList();

var extras = (from data in query
from extra in data.Extras
select new ExtraModel 
{
   extra.Value = data.Value
}).ToLookup(e => e.SomeId);

foreach (var d in data)
{
   d.Extras = new List<Extra>();
   if (extras.Contains(d.SomeId))
     d.Extras.AddRange(extras[d.SomeId])
}
```

**Comment by Fruchuxs** [comment]
Thank you for your answer. This is a little bit sad, because I can't apply a ExtraData-Where on my  `IQueryable<DataModel>`. So I must write some expression magic to seperate the where statements to apply them separately.

**Comment by sdanyliv** [comment]
Yes, we have to find time to implement eager loading which is also useful in OData endpoints.
But this requires a lot of our efforts.
