### ISSUE TITLE
how to exec sqlfucntion

### ISSUE THREAD

**Issue by quan01994** [linq2db/linq2db#1461]
````csharp
using (var db = new HywCrmDB(connectionStrings,ProviderName.SqlServer2008))
{
    var query =
        from c in db.MemberInfo
        where SqlFunctions.TagContain(c.MemberResTagIds, "1,2") > 1
        select c;
    var temp = query.ToList();
    foreach (var item in temp)
    {
        Console.WriteLine($"{item.MemberResTagIds}  {item.MemberName}");
    }
}
Console.WriteLine("Hello World!");
````
but i get this exception
````csharp
Unhandled Exception: System.Data.SqlClient.SqlException: 只有函数和某些扩展存储过程才能从函数内部执行。
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at System.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at System.Data.SqlClient.SqlDataReader.Read()
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 332
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at External.GenerateModel.Program.Main(String[] args) in D:\VsProjects\Hyw2\external\External.GenerateModel\Program.cs:line 22
````
this sql function is used match string.
split by  `','`  and return match string number 
such as  `1,2,3`     `1,2`  return `2`

**Comment by quan01994** [comment]
Ok,it's database error. 
I have rewritten the sql function
