### ISSUE TITLE
Compiled query comp

### ISSUE THREAD

**Issue by tkozybski** [linq2db/linq2db#1472]
Hello.
I'm having an issue I cant' find a solution for. The compiled query below throws exception that it cannot be converted to SQL. If I compile IQueryable<PlayerZoneInfo> it doesn't work either. At first I thought im doing someting wrong but if I use the same query without compilation it works fine, also if i use ToListAsync instead or SingleOrDefaultAsync it also works.

```:
Stack trace:
Exception LinqToDB.Linq.LinqException: 'gameVersion' cannot be converted to SQL.
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1030
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1682
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1425
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2670
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2573
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2573
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 48
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\WhereBuilder.cs:line 23
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.SelectBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectBuilder.cs:line 36
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.FirstSingleBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\FirstSingleBuilder.cs:line 25
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 147
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 269
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 233
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 84
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken token) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 89
   line where im calling the compiled query[...]
```

```c#
		private static readonly Func<CompanyDatabase, string, string, byte[], Task<PlayerZoneInfo>> GetPlayerZoneInfo
		= CompiledQuery.Compile((CompanyDatabase db, string gameVersion, string playerName, byte[] hash)
			=> db.ZoningHistory
				.Where(c => c.GameVersion == gameVersion && c.PlayerName == playerName && c.ZoneHash == hash)
				.Select(c => new PlayerZoneInfo { [...] })
				.SingleOrDefaultAsync(default));
```

### Environment details
linq2db version: 2.6.0
Database Server: MariaDB 10.3
Database Provider: Mysql.Data
Operating system:  Windows 10
Framework version: .NET Core 2.2.0

**Comment by sdanyliv** [comment]
@tkozybski, does query work without compilation?
Can you post also model definition?

**Comment by tkozybski** [comment]
Yes as I stated, the query works without compilation. I can't post all of the model but the part I use for Where clause

```c#
[MessagePackObject]
public class PlayerZoneInfo 
{
	[Key(0)]
	public DateTime EnterTime { get; set; }

	[Key(1)]
	public DateTime LeaveTime { get; set; }

	etc
}

[Table(Name = "ZoningHistory")]
public class PlayerZoneInfoFull
{
	[PrimaryKey(0)]
	public string GameVersion  { get; set; }

	[PrimaryKey(1)]
	public string PlayerName  { get; set; }

	[PrimaryKey(2)]
	public byte[] ZoneHash { get; set; }

	[rest of columns, all of them are the same as in PlayerZoneInfo]
}
```

the select statement is as follow
```c#
.Select(c => new PlayerZoneInfo {  EnterTime = c.EnterTime, LeaveTime = c.LeaveTime [...rest of the doubles] })
```

ZoningHistory is a ITable\<PlayerZoneInfoFull\>

**Comment by sdanyliv** [comment]
Will try to reproduce. I can’t see possible problems. It is very light query for linq2db.

**Comment by sdanyliv** [comment]
@tkozybski, i confirm problem. Bad news that there is problem with async implementation.
Will try to figure out how to deal with this.
