### ISSUE TITLE
Merge fails with MariaDB

### ISSUE THREAD

**Issue by tkozybski** [linq2db/linq2db#1480]
Hello
There's an issue with the syntax, both async and not, compiled and not. MySQL doesn't support merge but it could be substituded by InsertOrReplace like https://stackoverflow.com/a/42663205 but I can't find InsertOrReplace for IEnumerable, I'm inserting one by one for now, which is not ideal.

```c#
   	public class Entity
	{
		[PrimaryKey(0)]
		public string GameVersion { get; set; }

		[PrimaryKey(1)]
		public string NickName { get; set; }

		[PrimaryKey(2)]
		public byte[] Hash { get; set; }

		[...Rest of the columns]
	}
	
	
		private static readonly Func<Database, IEnumerable<Entity>, Task<int>> CompiledAddM
			= CompiledQuery.Compile((Database db, IEnumerable<Entity> entitites) => db.MergeAsync(entitites, null, null, null, default));
```
			
```:			
Exception MySql.Data.MySqlClient.MySqlException (0x80004005): You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near 'MERGE INTO `Entitites` Target
USING
(
        VALUES
        ('1.0.0.0','TestChar',0xE' at line 1
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.Async.cs:line 61
   at LinqToDB.Data.CommandInfo.ExecuteAsync(CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Data\CommandInfo.cs:line 529
   at LinqToDB.DataProvider.BasicMerge.MergeAsync[T](DataConnection dataConnection, Expression`1 predicate, Boolean delete, IEnumerable`1 source, String tableName, String databaseName, String schemaName, CancellationToken token) in C:\projects\linq2db\Source\LinqToDB\DataProvider\BasicMerge.cs:line 56
```   
   

	
	
### Environment details
linq2db version: 2.6.0
Database Server: MariaDB 10.3
Database Provider: Mysql.Data
Operating system:  Windows 10
Framework version: .NET Core 2.2.0

**Comment by MaceWindu** [comment]
Right now MERGE API intended for use only with databases that suppport MERGE statement: https://github.com/linq2db/linq2db/wiki/Merge-API-Background-Information-and-Providers-Support#supported-databases

For unsupported databases it will throw exception or, as in your case, if you will call _legacy_ Merge API methods, it will generate SQL Server-compatible merge statement, which will fail not only for MySQL but also for some databases that support MERGE. I would discourage anybody from using legacy merge API.

We didn't planned to support UPSERT statements here, but now I think it is not such a bad idea, but it definitely will be version 3 feature.

**Comment by MaceWindu** [comment]
Candidates for implementation: MariaDB, MySql, PostgreSQL

**Comment by ademchenko** [comment]
Merge  is still not implemented in PostgreSQL as of yet, so could you, @MaceWindu , tell if you are going to start working on that issue?

**Comment by MaceWindu** [comment]
Don't plan to work on it in near future. If somebody else wants to pick it up - you are welcome.

**Comment by kpietraszko** [comment]
Any news on this? I think it's quite important for PostgresSQL, because - quoting the docs: 

> ON CONFLICT DO UPDATE guarantees an atomic INSERT or UPDATE outcome; provided there is no independent error, one of those two outcomes is guaranteed, even under high concurrency.

**Comment by MaceWindu** [comment]
Merge already supported by PostgreSQL since version 15.

**Comment by kpietraszko** [comment]
@MaceWindu True, but there is a difference. MERGE has a possibility of a unique violation, when a concurrent INSERT happens. While ON CONFLICT is protected against that.

**Comment by kpietraszko** [comment]
Sorry, I just realized `InsertOrUpdate` does exactly what I need. And it's not really relevant to this issue.
