### ISSUE TITLE
Providing a IDbConnection when using AllowMultipleQuery results in an exception

### ISSUE THREAD

**Issue by Mitch528** [linq2db/linq2db#1486]
Example:

```csharp
public class IssueDataConnection : DataConnection
{
	public IssueTestDataConnection(string configuration) : base(GetDataProvider(configuration, true),
		GetConnection(configuration), true)
	{
	}

	private static IDataProvider GetDataProvider(string configuration, bool avoidSpecific)
	{
		LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;

		if (avoidSpecific)
		{
			LinqToDB.Common.Configuration.AvoidSpecificDataProviderAPI = true;
		}

		return GetDataProvider(configuration);
	}

	private static IDbConnection GetConnection(string configuration)
	{
		string connStr = GetConnectionString(configuration);

		return GetDataProvider(configuration).CreateConnection(connStr);
	}
}
```
The following will throw an exception since LinqToDb tries to create another connection with a null connection string.

```csharp
using (var db = new IssueDataConnection(config))
{
	db.GetTable<Child>().LoadWith(p => p.Parent.Children).First();
}
```

Exception:

```
System.ArgumentNullException : Value cannot be null.
Parameter name: key
   at System.Collections.Concurrent.ConcurrentDictionary`2.ThrowKeyNullException()
   at System.Collections.Concurrent.ConcurrentDictionary`2.TryGetValue(TKey key, TValue& value)
   at MySqlConnector.Core.ConnectionPool.GetPool(String connectionString) in C:\projects\mysqlconnector\src\MySqlConnector\Core\ConnectionPool.cs:line 368
   at MySql.Data.MySqlClient.MySqlConnection.<CreateSessionAsync>d__96.MoveNext() in C:\projects\mysqlconnector\src\MySqlConnector\MySql.Data.MySqlClient\MySqlConnection.cs:line 487
--- End of stack trace from previous location where exception was thrown ---
```

Possible solutions:
- Set `ConnectionString = connection.ConnectionString` in the constructor overload.
- Provide a factory method that can be used to retrieve an IDbConnection instead of passing one in via the constructor. This is probably the ideal solution, but would be a breaking change.

### Environment details
linq2db version: 2.7.0
Database Server: MySql
Database Provider: MySqlConnector
Operating system: Windows 10
Framework version: .NET Core 2.0

**Comment by MaceWindu** [comment]
Probably will try to implement both, as connection.ConnectionString is not reliable. Some providers remove credentials from connection string, exposed through this property

**Comment by MaceWindu** [comment]
@Mitch528 can you check that proposed PR will fix you issue?
