### ISSUE TITLE
TypeAccessor<T> doesn't respect IMetadataReader

### ISSUE THREAD

**Issue by CoskunSunali** [linq2db/linq2db#1521]
`TypeAccessor<T>` is used in relation to dynamic columns store, however, it doesn't respect custom `IMetadataReader` implementations and tries to find the member using the default `DynamicColumnsStoreAttribute` attribute.

[This is the exact line causing the issue].(https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Reflection/TypeAccessorT.cs#L94)

This matters when I have my own mapping attributes, due to wrapping the library, and the entity has custom columns store defined using a custom attribute rather than `DynamicColumnsStoreAttribute` attribute.

Do you think the `TypeAccessor<T>` should also respect a custom `IMetadataReader`?

**Comment by CoskunSunali** [comment]
Adding the exception stack trace.

```
System.ArgumentException: Tried setting dynamic column value, without setting dynamic column store on type.
   at lambda_method(Closure , Expression , Object[] )
   at LinqToDB.Linq.QueryRunner.SetParameters(Query query, IDataContext dataContext, Expression expression, Object[] parameters, Int32 queryNumber) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 146
   at LinqToDB.Linq.QueryRunnerBase.SetCommand(Boolean clearQueryHints) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunnerBase.cs:line 69
   at LinqToDB.Data.DataConnection.QueryRunner.SetCommand() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 283
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteScalarAsync(CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 549
   at LinqToDB.Linq.QueryRunner.ScalarQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 717
   at LinqToDB.Linq.QueryRunner.InsertWithIdentity`1.QueryAsync(IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, CancellationToken token) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.InsertWithIdentity.cs:line 94
```

**Comment by sdanyliv** [comment]
@CoskunSunali, what can i say. It is good first issue ;)
PR is wellcome.

**Comment by CoskunSunali** [comment]
I would love to and I believe I will do but only in the future :)

I am afraid I still don't trust myself to contribute to linq2db. Still learning it and not feeling confident.

I picked linq2db as our internal ORM. So don't be surprised when we contribute in the future but just not yet. Really sorry about that :/

**Comment by sdanyliv** [comment]
Ok, will handle this, but you can help writing failing test.
