### ISSUE TITLE
hi, help me !!!

### ISSUE THREAD

**Issue by MajidSafari** [linq2db/linq2db#1531]
some time i use linq2db 

```
Mapping of column Name value failed, see inner exception for details | Input string was not in a correct format.   
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
   at lambda_method(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__9`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

### Environment details

linq2db version: *2.6.2*
Database Server: *sql server 2017*

Framework version: *.NET Framework 4.6.2*

**Comment by sdanyliv** [comment]
@MajidSafari, we need more information. Call stack is not complete.
Which method do you call and which model do you have?

**Comment by sdanyliv** [comment]
From my experience usually it is problem in user’s projection.
Something like this 
```cs
var db.GetTable<SomeTable>()
   .Select(e => new 
       { 
            SomeStr = string.Format(“Value {1}”, e.Value)
       }).ToList();
```
Which is incorrect.

**Comment by MajidSafari** [comment]
using (var db = new WorkBookPDFdb())
                {

                    try
                    {
                        int? clientId = 0;
                        try
                        {
                       
                              

                             clientId = db.ClientIds.FirstOrDefault(r => r.Key == key && r.IsActive == true)?.Id;

**Comment by MajidSafari** [comment]
`	[Table(Database="WorkBookPDF", Schema="dbo", Name="ClientIds")]
	public partial class ClientId
	{
		[PrimaryKey, Identity   ] public int    Id       { get; set; } // int
		[Column,        Nullable] public string Name     { get; set; } // nvarchar(max)
		[Column,        Nullable] public string Key      { get; set; } // nvarchar(max)
		[Column,     NotNull    ] public bool   IsActive { get; set; } // bit
	}`

**Comment by sdanyliv** [comment]
As a quick workaround i suggest to rewrite your query in more effective way:
```cs
clientId = db.ClientIds
    .Where(r => r.Key == key && r.IsActive == true)
    .Select(r => (int?)r.Id)
    .FirstOrDefault();
```

**Comment by MajidSafari** [comment]
ok i try , tnx, for response

**Comment by MaceWindu** [comment]
Do you have any custom type mappings configured? With default mappings, linq2db will not call failing code at all...

**Comment by MajidSafari** [comment]
but , same times , i get this error

```cs
1/14/2019 12:11:34 AM ==>  | Mapping of column UrlDownload value failed, see inner exception for details | String was not recognized as a valid Boolean.   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
   at lambda_method(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__9`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass4_0`1.<GetFirstOrDefaultElement>b__0(IDataContext db, Expression expr, Object[] ps)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at WookBookPDF.Controllers.WorkBookStudentController.WorkBook()LinqToDB.Common.LinqToDBConvertException: Mapping of column UrlDownload value failed, see inner exception for details ---> System.FormatException: String was not recognized as a valid Boolean.
   at System.Boolean.Parse(String value)
   at lambda_method(Closure , IDataReader )
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
   --- End of inner exception stack trace ---
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
   at lambda_method(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__9`1.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass4_0`1.<GetFirstOrDefaultElement>b__0(IDataContext db, Expression expr, Object[] ps)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at WookBookPDF.Controllers.WorkBookStudentController.WorkBook()

```

**Comment by sdanyliv** [comment]
@MajidSafari, do you use additional MappingSchema configuration?

**Comment by MajidSafari** [comment]
is use

``` cs
<#@ template language="C#" debug="True" hostSpecific="True"                           #>
<#@ output extension=".generated.cs"                                                  #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)LinqToDB.SqlServer.Tools.ttinclude" #>
<#@ include file="$(LinqToDBT4SqlServerTemplatesDirectory)PluralizationService.ttinclude"     #>
<# //@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.SqlServer.Tools.ttinclude" #>
<# //@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"     #>
<#
	

	NamespaceName = "WorkBookPDF.DataModels";
	DatabaseName	 = "WorkBookPDF";

	DataContextName  = "WorkBookPDFdb"; 
	
//	LoadSqlServerMetadata("MyServer", "MyDatabase", "User", "Password");
//	LoadSqlServerMetadata(".", "WookBookPDF"); // Integrated Security
	LoadSqlServerMetadata("Data Source=.;Initial Catalog=Workbookpdf;Integrated Security=SSPI;Enlist=false");

	GenerateModel();
#>

```

**Comment by sdanyliv** [comment]
Since it is something new and this code always work. Several questions:

1. Do you share data context between threads?
2. It is crash exception, or it is catched by linq2db internally?

**Comment by sdanyliv** [comment]
Two problems here.

1. You use single  DataContext in multithreaded environment. Create new WorkbookPDFdb in each task run.

1. DbContext MUST be disposed. Use `using` keyword.

And as good practice, you have use async await for processing instead of getting Result from Task.

**Comment by MaceWindu** [comment]
Yes, you shouldn't use single data context in multiple threads - it is not supported nor by linq2db nor by underlying ado.net providers

**Comment by MajidSafari** [comment]
Thank you for answering ,

i try ...
