### ISSUE TITLE
MySqlException: IQueryable.Any -> ExecuteReader

### ISSUE THREAD

**Issue by rallentan** [linq2db/linq2db#155]
We received the following error twice in two days. When we call IQueryable.Any, we are testing if two values are equal (i.e. "Any(r => r.ID == id)" and "Any(r => r.String1 == someString)"). Any idea what this could be?

    Unhandled Exception: MySql.Data.MySqlClient.MySqlException: Fatal error encounte
    red during command execution. ---> MySql.Data.MySqlClient.MySqlException: Fatal
    error encountered attempting to read the resultset. ---> MySql.Data.MySqlClient.
    MySqlException: Reading from the stream has failed. ---> System.IO.EndOfStreamEx
    ception: Attempted to read past the end of the stream.
    at MySql.Data.MySqlClient.MySqlStream.ReadFully(Stream stream, Byte[] buffer,
    Int32 offset, Int32 count)
    at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
    --- End of inner exception stack trace ---
    at MySql.Data.MySqlClient.MySqlStream.LoadPacket()
    at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
    at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& i
    nsertedId)
    at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affected
    Rows, Int64& insertedId)
    at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
    at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
    --- End of inner exception stack trace ---
    at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior
    )
    --- End of inner exception stack trace ---
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior
    )
    at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior be
    havior)
    at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader()
    at LinqToDB.Data.DataConnection.ExecuteReader()
    at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.ExecuteReader(Object qu
    ery)
    at LinqToDB.Linq.Query`1.RunQuery[TE](QueryContext ctx, IDataContextInfo data
    ContextInfo, Expression expr, Object[] parameters, Func`6 mapper)
    at LinqToDB.Linq.Query`1.<>c__DisplayClass50.<SetElementQuery>b__4f(QueryCont
    ext ctx, IDataContextInfo db, Expression expr, Object[] ps)
    at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult
    ](Expression expression)
    at System.Linq.Queryable.Any[TSource](IQueryable`1 source, Expression`1 predi
    cate)

**Comment by rallentan** [comment]
This was in version 1.0.6.0 of linq2db.

**Comment by rallentan** [comment]
Unfortunately, the error occurred on a deployed application after a long run. I can't know which line caused the error, but these are the only two lines that call 'IQueryable.Any':

    public bool UserExists(uint id, LinqToDB.Data.DataConnection dataConnection)
    {
        return dataConnection.Users.Any(u => u.ID == id);
    }

    public bool OrgExists(string handle, LinqToDB.Data.DataConnection dataConnection)
    {
        return dataConnection.Orgs.Any(o => o.Handle == handle);
    }

We don't usually notice the error until a few hours after it occurs, so we may not be able to obtain the generated query.

**Comment by igor-tkachev** [comment]
It looks like you get this MySql bug - http://bugs.mysql.com/bug.php?id=57365

**Comment by rallentan** [comment]
Interesting. So, it seems to be caused by trying to read too many records in a single query. So, why does it need to read more than one record for a boolean result?

**Comment by rallentan** [comment]
Thanks, I'll capture the query next time it happens. Though, I can't imagine either query taking longer than a few seconds, at worst. The tables are very responsive to similar queries done manually.

**Comment by rallentan** [comment]
RESOLVED: This problem disappeared after fixing another bug in the host application that was causing long delays *between* queries.
