### ISSUE TITLE
NullReferenceException on InnerJoin

### ISSUE THREAD

**Issue by JechoJekov** [linq2db/linq2db#1556]
I am trying to execute the following query:

```C#
var records = await Db.Users
    .InnerJoin(
        Db.Agencies,
        (user, agency) => user.Id == agency.OwnerUserId || agency.Employees.Any(y => y.UserId == user.Id),
        (user, agency) => new { User = user, Agency = agency }
    ).ToListAsync();
```

The result is an exception while linq2db is building the query.

```
System.NullReferenceException
  HResult=0x80004003
  Message=Object reference not set to an instance of an object.
  Source=linq2db
  StackTrace:
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.GetContext(Expression expression, Int32 level, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:line 1004
   at LinqToDB.Linq.Builder.TableBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\TableBuilder.cs:line 138
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.AllAnyBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\AllAnyBuilder.cs:line 18
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 233
   at LinqToDB.Linq.Builder.ExpressionBuilder.SubQueryToSql(IBuildContext context, MethodCallExpression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1682
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1425
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1495
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2670
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2590
   at LinqToDB.Linq.Builder.AllJoinsLinqBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\AllJoinsLinqBuilder.cs:line 73
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 147
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 268
```

### Additional information

The exception occurs inside the `TableContext.GetContext` method on the following lines in [_LinqToDB/Linq/Builder/TableBuilder.TableContext.cs_](https://github.com/linq2db/linq2db/blob/v2.6.3/Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs#L1004):

```C#
1004						var tableLevel  = GetAssociation(expression, level);
1005						var association = (AssociatedTableContext)tableLevel.Table;
```

`GetAssociation` returns a null value which causes the error on the next line.

The parameters passed to `GetAssociation` are:

```
expression: PropertyExpression "agency.Employees"
level: 1
```

The `GetAssociation` method does not finds the association between the _Agency_ object and _Employees_ which is a one-to-many relationship between two tables.

### Environment details
linq2db version: *2.6.3*
Database Server: *SQL Server 2014*
Database Provider: *SQL Server 2014*
Operating system: *E.g. Windows 10*
Framework version: *.NET Core 2.2*

**Comment by JechoJekov** [comment]
The current table context is for the _User_ table (`this.EntityDescriptor.TableName` = "User")

Inside the `GetAssociation` method `levelExpression` has the same value as the parameter `expression` (`expression.GetLevelExpression` returned the value unchanged).

[_TableContext.GetAssociation_](https://github.com/linq2db/linq2db/blob/v2.6.3/Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs#L1317)

```C#
TableLevel GetAssociation(Expression expression, int level)
{
1319			var objectMapper    = EntityDescriptor;
1320			var levelExpression = expression.GetLevelExpression(Builder.MappingSchema, level);
}
```

It appears that the `GetContext` method not called on the correct `TableContext` instance.

**Comment by sdanyliv** [comment]
@JechoJekov, you are doing hard work in understanding how it works. I know it is not so easy and i’m personally trying to left comments in places which were reverse engineered.

It is hard to say in which place problem were introduced. At first create unit test and post it here, so we can decrease time for reproducing.
