### ISSUE TITLE
Incorrect query generated when groupby results are filtered using custom sql expressions

### ISSUE THREAD

**Issue by glebkozh** [linq2db/linq2db#1575]
Hello!
I've ran into the following problem: linq2db generates incorrect query when I try to use custom sql expression to filter aggregated groupby results.

### Steps to reproduce
Consider this simplified example:
I've got table entity:
```c#
        [Table]
        public class Entity
        {
            [PrimaryKey, Identity]
            public int Id { get; set; }
            [Column, NotNull]
            public int Value { get; set; }
        }
```
and Sql.Expression:
```c#
[Sql.Expression("{0} > {1}", ServerSideOnly = true)]
public static bool SqlGreater(object operand1, object operand2) => throw new InvalidOperationException();
```
Then I try to group entities by Value and filter out groups that have less than or equal 2 entries:
```c#
var result = _db.GetTable<Entity>().GroupBy(item => item.Value)
                .Where(group => SqlExtensions.SqlGreater(group.Count(), 2));
```
As a result, I receive the following SQL:
```sql
--  SqlServer SqlServer.2012
SELECT
	[t1].[Value]
FROM
	[Entity] [t1]
GROUP BY
	[t1].[Value]
HAVING
	1 = Count(*) > 2
```
The last line has got an incorrect syntax with strange "1 = ..." statement:

```c#
System.Data.SqlClient.SqlException : Incorrect syntax near '>'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 1236
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 320
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```
Thanks!

### Environment details
linq2db version: *2.6.3*
Database Server: *Sql Server 13.0.1601.5*
Database Provider: *Sql.Data.SqlClient 4.6.27110.4*
Operating system: *Windows 10 Pro 10.0.17134*
Framework version: *.NET Core 2.2.102*

**Comment by MaceWindu** [comment]
Didn't checked, but suspect you need add `CanBeNull = false`  to `Sql.Expression` attribute, otherwise linq2db will treat it as returning (TRUE, FALSE, NULL) type

**Comment by MaceWindu** [comment]
also it should have proper precedence `Precedence = LinqToDB.SqlQuery.Precedence.Comparison` (will also fix it for you)

**Comment by sdanyliv** [comment]
Also set `IsPredicate = true`

**Comment by glebkozh** [comment]
@MaceWindu @sdanyliv thanks, IsPredicate = true did the trick
