### ISSUE TITLE
Npgsql.PostgresException (0x80004005): the duplicate key value violates the uniqueness constraint " PK_Materials"

### ISSUE THREAD

**Issue by Dmitrij-Polyanin** [linq2db/linq2db#1583]
I try to add entity with `InsertWithInt32IdentityAsync` using `PostgreSQL.9.5` provider.

I have installed PostgreSQL 11 on my computer.

Exception message (This is translation from Russian): 
```
Npgsql.PostgresException (0x80004005): the duplicate key value violates the uniqueness constraint " PK_Materials" 
```
Stack trace:
```
Npgsql.PostgresException (0x80004005): 23505: повторяющееся значение ключа нарушает ограничение уникальности "PK_Materials"
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1012
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass161_0.<<ReadMessage>g__ReadMessageLong|0>d.MoveNext() in C:\projects\npgsql\src\Npgsql\NpgsqlConnector.cs:line 1032
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming) in C:\projects\npgsql\src\Npgsql\NpgsqlDataReader.cs:line 489
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1215
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken) in C:\projects\npgsql\src\Npgsql\NpgsqlCommand.cs:line 1042
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteScalarAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ScalarQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.InsertWithIdentity`1.QueryAsync(IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, CancellationToken token)
   at LinqToDB.DataExtensions.InsertWithInt32IdentityAsync[T](IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, CancellationToken token)
```

I tried to move from MySQL to PostgresSQL.
I detect this issue after moved to PostgresSQL.

Class schema:
```
mp.Entity<Material>()
                .HasTableName("Materials")
                .HasIdentity(x => x.Id).HasPrimaryKey(x => x.Id)
```
```
public class Material
{
     public int Id { get; set; }
```

### Environment details
linq2db version: *2.6.4*
Database Server: *PostgreSQL 11.1 (Ubuntu 11.1-3.pgdg18.04+1) on x86_64-pc-linux-gnu, compiled by gcc (Ubuntu 7.3.0-27ubuntu1~18.04) 7.3.0, 64-bit*
Database Provider: *PostgreSQL.9.5*
Operating system: *Kubuntu 8.10*
Framework version: *ASP.NET Core 2.2*

**Comment by Dmitrij-Polyanin** [comment]
I understand, this is no linq2db problem but FluentMigrator need to set SERIAL type for PK.

**Comment by KrisPetkov** [comment]
Hi @DmitrijOkeanij 
How did you solve this issue? I'm getting the same error and cannot figure it out?
