### ISSUE TITLE
Association Expression with subquery gives table not found exception

### ISSUE THREAD

**Issue by pnewton** [linq2db/linq2db#1614]
I've got the following model:

```
public class MyDb : DataConnection
{
    public ITable<User> Users => GetTable<User>();
    public ITable<Group> Groups => GetTable<Group>();
    public ITable<Resource> Resources => GetTable<Resource>();
    public ITable<Lookup> SystemCodes => GetTable<Lookup>();
}

public class User
{
    public int Id { get; set; }
}

public class Group
{
    public int Id { get; set; }
}

public class Lookup
{
    public int Id { get; set; }

    public string Type { get; set; }
}

public class Resource
{
    public int Id { get; set; }

    public int AssociatedObjectId { get; set; }

    public int? AssociationTypeId { get; set; }


    [Association(
        ThisKey = nameof(AssociationTypeId), 
        OtherKey = nameof(Lookup.Id), 
        CanBeNull = true, 
        Relationship = Relationship.ManyToOne)]
    public Lookup AssociationTypeCode { get; set; }

    public static Expression<Func<Resource, IDataContext, IQueryable<User>>> UserExpression =>
        (r, db) => db.GetTable<User>().Where(c => r.AssociationTypeCode.Type == "us" && c.Id == r.AssociatedObjectId);

    [Association(QueryExpressionMethod = nameof(UserExpression))]
    public User User { get; set; }

    public static Expression<Func<Resource, IDataContext, IQueryable<Group>>> GroupExpression =>
        (r, db) => db.GetTable<Group>().Where(c => r.AssociationTypeCode.Type == "gr" && c.Id == r.AssociatedObjectId);

    [Association(QueryExpressionMethod = nameof(GroupExpression))]
    public Group Group { get; set; }
}
```

As you can see, this model includes a polymorphic association (legacy system, I can't change the structure.) I'd hoped that I could use the QueryExpressionMethod on Association to map this relationship when querying.

Currently, when executing:
`using (var db = new MyDb())
{
    var resources = db.Resources
        .LoadWith(x => x.User)
        .ToList();
}`

I get the following error:

```
LinqToDB.SqlQuery.SqlException : Table '[Lookup]' not found

   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildExpression(ISqlExpression expr, Boolean buildTableName, Boolean checkParentheses, String alias, Boolean& addAlias, Boolean throwExceptionIfTableNotFound) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 2180
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildExpression(Int32 parentPrecedence, ISqlExpression expr, String alias, Boolean& addAlias) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 2369
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildPredicateX(ExprExpr expr) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 1849
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildPredicate(ISqlPredicate predicate) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 1720
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSearchCondition(SqlSearchCondition condition) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 1666
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSearchCondition(Int32 parentPrecedence, SqlSearchCondition condition) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 1708
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildJoinTable(SelectQuery selectQuery, SqlJoinedTable join, Int32& joinCounter) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 1384
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildFromClause(SqlStatement statement, SelectQuery selectQuery) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 1270
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSelectQuery(SqlSelectStatement selectStatement) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 226
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql(Int32 commandNumber, SqlStatement statement, StringBuilder sb, Int32 indent, Boolean skipAlias) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 89
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql(Int32 commandNumber, SqlStatement statement, StringBuilder sb, Int32 startIndent) in C:\projects\linq2db\Source\LinqToDB\SqlProvider\BasicSqlBuilder.cs:line 74
   at LinqToDB.Data.DataConnection.QueryRunner.GetCommand(DataConnection dataConnection, IQueryContext query, Int32 startIndent) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 183
   at LinqToDB.Data.DataConnection.QueryRunner.SetQuery() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 276
   at LinqToDB.Linq.QueryRunnerBase.SetCommand(Boolean clearQueryHints) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunnerBase.cs:line 69
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 439
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 320
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Linq2DbTest.Program.TestMethod() in Linq2DbTests\Program.cs:line 106
```

### Environment details
linq2db version: *2.6.4*
Database Server: *E.g. Sql Server 2017*
Database Provider: *E.g. SqlServerVersion.v2012*
Operating system: *E.g. Windows 10*
Framework version: *.NET Core 2.1*

**Comment by pnewton** [comment]
I think this should work as a test:

```
[TestFixture]
public class Issue1614Tests: TestBase
{
	public class User
	{
		public int Id { get; set; }
	}

	public class Group
	{
		public int Id { get; set; }
	}

	public class Lookup
	{
		public int Id { get; set; }

		public string Type { get; set; }
	}

	public class Resource
	{
		public int Id { get; set; }

		public int AssociatedObjectId { get; set; }

		public int? AssociationTypeId { get; set; }


		[Association(
			ThisKey = nameof(AssociationTypeId),
			OtherKey = nameof(Lookup.Id),
			CanBeNull = true,
			Relationship = Relationship.ManyToOne)]
		public Lookup AssociationTypeCode { get; set; }

		public static Expression<Func<Resource, IDataContext, IQueryable<User>>> UserExpression =>
			(r, db) => db.GetTable<User>().Where(c => r.AssociationTypeCode.Type == "us" && c.Id == r.AssociatedObjectId);

		[Association(QueryExpressionMethod = nameof(UserExpression))]
		public User User { get; set; }

		public static Expression<Func<Resource, IDataContext, IQueryable<Group>>> GroupExpression =>
			(r, db) => db.GetTable<Group>().Where(c => r.AssociationTypeCode.Type == "gr" && c.Id == r.AssociatedObjectId);

		[Association(QueryExpressionMethod = nameof(GroupExpression))]
		public Group Group { get; set; }
	}

	[Test]
	public void Test([DataSources] string context)
	{
		using (var db = GetDataContext(context))
		using (db.CreateLocalTable<User>())
		using (db.CreateLocalTable<Group>())
		using (db.CreateLocalTable<Resource>())
		using (db.CreateLocalTable<Lookup>())
		{
			var result = db.GetTable<Resource>()
				.LoadWith(x => x.User)
				.ToList();

			//No assert, just need to get past here without an exception
		}
	}
}
```

**Comment by sdanyliv** [comment]
It’s a time to rethink associations logic. I had one try and will try again. Thanks for the sample.
It is because current associations logic is tightly coupled to Tables but also needs to be expanded to Queries.
Sorry about that, but do not expect that this will be done quickly. A lot of situations needs to be covered by appropriate algorithm.

**Comment by SaltyDH** [comment]
@sdanyliv Interesting that you mention a rethink. I just started exploring this fantastic project and thought I'd throw my 2 cents in as I've just come up against this today.

I've been implementing some entity flattening (supporting information in a separate table) using Linq2DB Associations via Query Expressions. The expressions (via Sql.FromSql) use SQL2016's JSON support to expand JSON arrays of long Ids stored in varchar table columns into a more verbose JSON array of objects. I'm then using the JsonContent functionality that I found in one of the playground tests to deserialize that JSON string back into a List<T>.

This is working great but I haven't been able to get this to work without declaring the properties on my class. Just thought an additional use case might help with any considerations in terms of decoupling.

**Comment by sdanyliv** [comment]
@SaltyDH, please post exact tables structure and how do yo expect to work with this. I'll take a look.
There were a lot of questions about that, and I need to check how it can be implemented or just explained. Sorry for future delays, we are on vacations.

**Comment by SaltyDH** [comment]
Hi @sdanyliv 

Here's an example scenario - I've used Students and Courses in this example just to remove the domain specific models but the structure and data is representative of the intended outcome.

SQL Tables:

[Students]

Id (bigint), FirstName (nvarchar), LastName (nvarchar), Courses (nvarchar)
1, 'Student', 'Test 1', '[1, 2, 3]'
2, 'Student', 'Test 2', '[2, 3, 4]'

[Courses]

Id (bigint), Name (nvarchar), Description (nvarchar)
1, 'Course 1', 'Course 1 Description'
2, 'Course 2', 'Course 1 Description'
3, 'Course 3', 'Course 1 Description'
4, 'Course 4', 'Course 1 Description'

.NET Poco definitions:
public class Student {

	public long Id { get; set; }
	public string FirstName { get; set; }
	public string LastName { get; set; }
	public IList<Course> Courses { get; set; }

}

public class Course {

	public long Id { get; set; }
	public string Name { get; set; }
	public string Description { get; set; }

}


LINQ query equivalent to:

from student in Students
select student.*

Rendered SQL:

Select student.Id, student.FirstName, student.LastName, courses.Course
FROM Students student
		CROSS APPLY (
			SELECT
				[Course]
			FROM
				(
					SELECT (SELECT course.Id, course.Name
					FROM Courses course
					CROSS APPLY OPENJSON([student].[Courses]) Data
					WHERE Data.Value = course.Id
					FOR JSON AUTO) AS [Course]
				) [courses]
		) courses

SQL Resultset
Id	FirstName	LastName	Course
1	Student	Test 1	[{"Id":1,"Name":"Course 1"},{"Id":2,"Name":"Course 2"},{"Id":3,"Name":"Course 3"}]
2	Student	Test 2	[{"Id":2,"Name":"Course 2"},{"Id":3,"Name":"Course 3"},{"Id":4,"Name":"Course 4"}]

Notice the description is omitted here. I would like to be able to control the specific fields inside the CROSS APPLY statement.

Ideally this then correctly deserializes into an object graph so that the 'Courses' IList of each student is correctly materialized.
