### ISSUE TITLE
LinqToDB dosen't work well with EF Core soft delete.

### ISSUE THREAD

**Issue by emiliogg84** [linq2db/linq2db#1626]
I'm using Odata 4 + LinqToDB + EF Core with ASP.NET Core Web APIs

When execute a query that involve 'Apply' expression of OData4 over an entity that has soft delete enabled in EF Core an exception is throw.

Sample query: 
odata/LegalBenefitsMX?$apply=groupby((EffectiveDate))

The Entity:

public class LegalBenefitMX
    {
        [Column("LegalBenefitID")]
        public int ID { get; set; }
        public int LegalBenefitTypeID { get; set; }
        public DateTimeOffset EffectiveDate { get; set; }
        public int Seniority { get; set; }
        public int VacationDays { get; set; }
        public decimal VacationPremium { get; set; }
        public int ChristmasBonus { get; set; }
        public decimal IntegrationFactor { get; set; }
        public bool IsDeleted { get; set; }
    }
```
Exception message:
An unhandled exception was thrown by the application. LinqToDB.Linq.LinqException: 'Property(post, "IsDeleted")' cannot be converted to SQL.

Stack trace:
2019-02-27 08:54:24.8750|2|ERROR|Microsoft.AspNetCore.Server.IIS.Core.IISHttpServer|Connection ID "17798225737568747805", Request ID "8000011e-0002-f700-b63f-84710c7967bb": An unhandled exception was thrown by the application. LinqToDB.Linq.LinqException: 'Property(post, "IsDeleted")' cannot be converted to SQL.
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1038
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1690
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1433
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1503
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1032
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1690
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1433
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 1503
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2676
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2614
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 2664
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 48
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\WhereBuilder.cs:line 23
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.SelectBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectBuilder.cs:line 36
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.GroupByBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\GroupByBuilder.cs:line 49
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.SelectBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectBuilder.cs:line 36
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 147
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 268
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 232
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 84
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.IEnumerable.GetEnumerator() in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 188
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeList(JsonWriter writer, IEnumerable values, JsonArrayContract contract, JsonProperty member, JsonContainerContract collectionContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.SerializeValue(JsonWriter writer, Object value, JsonContract valueContract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerProperty)
   at Newtonsoft.Json.Serialization.JsonSerializerInternalWriter.Serialize(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.SerializeInternal(JsonWriter jsonWriter, Object value, Type objectType)
   at Newtonsoft.Json.JsonSerializer.Serialize(JsonWriter jsonWriter, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteObject(TextWriter writer, Object value)
   at Microsoft.AspNetCore.Mvc.Formatters.JsonOutputFormatter.WriteResponseBodyAsync(OutputFormatterWriteContext context, Encoding selectedEncoding)
```

### Steps to reproduce
Execute a query similar to the example above in Postman with a asp.net core web api enpoint with odata configured.

### Environment details
linq2db version: 2.6.4
linq2db.EntityFrameworkCore: 1.5.0
Database Server: SQL Server 2016
Database Provider: EF Core 2.2.2
Operating system: Windows 10 Pro
Framework version: .NET Core 2.2.0

**Comment by MaceWindu** [comment]
Is it https://github.com/voronov-maxim/OdataToEntity or some other odata library?

**Comment by emiliogg84** [comment]
Is only https://www.nuget.org/packages/Microsoft.AspNetCore.OData/7.1.0 no other lib are used.

**Comment by sdanyliv** [comment]
@emiliogg84, please post also how you define your model. I'm not so familiar with EF Core and maybe missed some extension point.

**Comment by sdanyliv** [comment]
Also, it is reproducible if you just write the same Linq query?

**Comment by emiliogg84** [comment]
Link to a sample project with instructions to reproduce the issue

[https://1drv.ms/u/s!AjU6ArLhT1xGgr1TCPE6ocb3Vxaktw](url)

**Comment by sdanyliv** [comment]
Thanks! Will check tomorrow.

**Comment by sdanyliv** [comment]
@emiliogg84, sorry for delay. I have prepared new release for EF Core integration which should support Shadow properties.

**Comment by emiliogg84** [comment]
I've tested the new version 1.5.1 and the exception persists :-( are you used the sample project to test the lilbrary?

**Comment by sdanyliv** [comment]
Looks like i have missed transformamtion for entity filters. Sorry about that will prepare fix ASAP.

**Comment by sdanyliv** [comment]
Sorry I have no chance to test it on your project but new 1.5.2 bug-fix release should work in your situation.

**Comment by emiliogg84** [comment]
Version 1.5.2 work nice!! many thanks!!

**Comment by sdanyliv** [comment]
@emiliogg84, could you please write several words how do you use our EF Core extension? And why. 
There is no feedbacks from others.

**Comment by emiliogg84** [comment]
I use Linq2Db EF Core + EF Core + OData to handle Odata query that involve grouping ("APPLY" operator in OData) doe OData for ASP.NET Core currently doesn't support these. The issue solved raises when the entity on the query is configured for soft delete in EF Core.
