### ISSUE TITLE
IQueryable use where after select build more that one tables

### ISSUE THREAD

**Issue by hambersmith** [linq2db/linq2db#1643]
If I call the method when **date** is filled, I get an error on the output.

But if i not use **select Build(lcstp, lca)** and I use select from **one** table, then everything works

```c#
Example:
GetByDateScheduleTimePoint(1, new Date(2019,01,01), false)
```
```
Exception message:
Stack trace:
ystem.NotImplementedException: The method or operation is not implemented.
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction)
   at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag)
   at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
   at LinqToDB.Linq.Builder.ExpressionContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass97_0.<CheckSubQueryForWhere>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Visit(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Visit(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Visit(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Visit(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CheckSubQueryForWhere(IBuildContext context, Expression expression, Boolean& makeHaving)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
```
```c#
        public LoanContractScheduleTimePoint GetByDateScheduleTimePoint(long loanContractId, Date? date, bool isGetAnnuity)
        {
            using (var db = CreateConnection())
            {
                IQueryable<LoanContractScheduleTimePoint> query;

                query = from lcstp in db.LoanContractScheduleTimePoints_
                    from lca in db.LoanContractAnnuities_.LeftJoin(_ => _.Id == lcstp.AnnuityId && isGetAnnuity)
                    where lcstp.ContractId == loanContractId
                          && lcstp.State == ScheduleTimePointState.New
                    orderby lcstp.StartPlanDate
                    select Build(lcstp, lca);

                if (date != null)
                    query = query.Where(_ => date >= _.StartDate && date <= _.EndDate);

                return date == null ? query.FirstOrDefault() : query.SingleOrDefault();
            }
        }

		private LoanContractScheduleTimePoint Build(LoanContractScheduleTimePoint timePoint, LoanContractAnnuity annuity)
		{
			if (timePoint == null)
				return null;

			timePoint.Annuity = annuity;
			return timePoint;
		}
```

### Environment details
linq2db version: *2.5.2*
Database Server: *MSSQL 2017*
Operating system: *Windows 7*
Framework version: *.NET Framework 4.6.2*

**Comment by sdanyliv** [comment]
@hambersmith, I agree that message is unclear, but for processing query, linq2db needs information about members transformation. After `Build` call this information is broken, because we can not trace which properties to which members are transformed. You have to provide Expression, like `Select` does, to be sure that everything is correctly converted to SQL. If it is not possible, you have to terminate query by `AsEnumerable()` exactly after `order by` clause

```cs
                var query = (from lcstp in db.LoanContractScheduleTimePoints_
                    from lca in db.LoanContractAnnuities_.LeftJoin(_ => _.Id == lcstp.AnnuityId && isGetAnnuity)
                    where lcstp.ContractId == loanContractId
                          && lcstp.State == ScheduleTimePointState.New
                    orderby lcstp.StartPlanDate;
                    select new {lcstp, lca})
                                        .AsEnumerable()
                                        .Select(c => Build(c.lcstp, c.lca)).AsQueryable();     

                if (date != null)
                    query = query.Where(_ => date >= _.StartDate && date <= _.EndDate);
```
Bad that you will retrieve whole table, so filter should be applied before AsEnumerable();

Think that `linq2db` is SQL generator and if you write ineffective query - you will get ineffective result. 
We assume that, for example, EF Core will run this query, but you also will get whole table on the client side, which is also very ineffective.

**Comment by hambersmith** [comment]
> Bad that you will retrieve whole table, so filter should be applied before AsEnumerable();

It's not good idea to get all row to client and filter them.

> You have to provide Expression, like Select does, to be sure that everything is correctly converted to SQL. 

Can you show example how i can do that

**Comment by hahn-kev** [comment]
I'll give it a shot to show you an example. There's more than one way to do this, but this might be the most straight forward
```C#
query = from lcstp in db.LoanContractScheduleTimePoints_
    from lca in db.LoanContractAnnuities_.LeftJoin(_ => _.Id == lcstp.AnnuityId && isGetAnnuity)
    where lcstp.ContractId == loanContractId
          && lcstp.State == ScheduleTimePointState.New
    orderby lcstp.StartPlanDate
    select new {lcstp, lca};

if (date != null)
    query = query.Where(_ => date >= _.lcstp.StartDate && date <= _.lcstp.EndDate);

var arg = date == null ? query.FirstOrDefault() : query.SingleOrDefault();
return Build(arg.lcstp, arg.lca);
```

keep in mind that you don't need to worry about lcstp being null in the where clause because it get's translated into SQL.

**Comment by MaceWindu** [comment]
closing as answered
