### ISSUE TITLE
LINQ expression failure with nullable cast in GroupBy + Select

### ISSUE THREAD

**Issue by AlekseyMartynov** [linq2db/linq2db#1659]
Originally reported in https://github.com/DevExpress/DevExtreme.AspNet.Data/issues/345

```
Exception message: Argument type 'System.Int32' does not match the corresponding member type 'System.Nullable`1[System.Int32]'

Stack trace:
   at System.Linq.Expressions.Expression.ValidateNewArgs(ConstructorInfo constructor, ReadOnlyCollection`1& arguments, ReadOnlyCollection`1& members)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments, IEnumerable`1 members)
   at System.Linq.Expressions.NewExpression.Update(IEnumerable`1 arguments)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 298
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass77_0.<BuildExpression>b__0(Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 51
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 1353
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 51
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 113
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 66
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 160
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 279
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 232
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 84
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 179
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at ConsoleApp1.Program.Main(String[] args) in s:\temp\ConsoleApp1\ConsoleApp1\Program.cs:line 27
```

### Steps to reproduce

`linq2db.SqlServer` version `2.6.4` with Northwind

```c#
[Table(Name = "Orders")]
public class Order {
    [PrimaryKey, Identity]
    public int OrderID { get; set; }

    [Column(Name = "OrderDate"), NotNull]
    public DateTime OrderDate { get; set; }
}

public class DbNorthwind : LinqToDB.Data.DataConnection {
    public DbNorthwind() : base("Northwind") { }
    public ITable<Order> Orders => GetTable<Order>();
}

class Program {
    static void Main(string[] args) {
        using(var db = new DbNorthwind()) {

            var groups = db.Orders
                .GroupBy(i => new {
                    Y = (int?)i.OrderDate.Year
                })
                .OrderBy(g => g.Key.Y)
                .Select(g => new {
                    Y = g.Key.Y    // HERE
                })
                .ToArray();
        }
    }
}
```

Can be worked around by adding an explicit cast

```c#
.Select(g => new {
    Y = (int?)g.Key.Y
})
```

However it's excessive and is not required by other providers (EF, EF Core, NHibernate).

**Comment by MaceWindu** [comment]
Could you try recent master from myget? Should be already fixed by #1618

**Comment by AlekseyMartynov** [comment]
Indeed, works fine with `2.7.0-rc3500`.
Thanks for your help.

**Comment by MaceWindu** [comment]
Thanks for update! Closing
