### ISSUE TITLE
postgres Array queries do not seem to be supported!

### ISSUE THREAD

**Issue by xlievo** [linq2db/linq2db#1660]
[Table(Name = "dd")]
public partial class dd
{
        [Column(Name = "dd", DataType = DataType.VarChar, Length = 255)]
        public System.String[] source { get; set; }
}

using (var con = DB.GetConnection())
 {
      var sql = con.Entity.dd.Where(c => c.source.Contains("2"));
      var data2 = sql.ToList();
}

throw:
LinqToDB.Linq.LinqException:“'c.source.Contains("2")' cannot be converted to SQL.”

**Comment by sdanyliv** [comment]
@xlievo, we know thta there are many functions for Postgres are not introduced, but you can do it by yourself.
Which SQL do you expect?

**Comment by ronnyek** [comment]
I mean to some degree I would expect functionality provided in linq2db to be within reason, to be the lowest common denominator of functionality across supported dbs.

What would happen in this case? Contains would execute a string wildcard query unless it detected it was an array and then it'd try to find array with specified element?

Just curious more than anything. I develop heavily against angular... And I too would like this functionality.

**Comment by MaceWindu** [comment]
Next release adds a lot of improvements to pgsql arrays support including mappings for existing array-related functions https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#postgresql

Still, there is no mappings for `Contains` collection method

**Comment by sdanyliv** [comment]
@ronnyek, feel free to create PR's if you think that we missed some important PostgreSQL function. Also it is good sample how to write such extensions. 
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLExtensions.cs

**Comment by Evengard** [comment]
I would like to point out that this is also a problem for me. Fortunately I managed to use a workaround from this other issue (https://github.com/linq2db/linq2db/issues/207), but I would really love to see a native solution.

**Comment by sdanyliv** [comment]
@Evengard, Which function? `= ANY` or `<= ANY`, etc. PostgreSQL is very rich in SQL constructions. If you want this in the library, faster way is to create PR.

**Comment by Evengard** [comment]
I'm not fluent enough to create for such an important library a PR, unfortunately. I meant `<value> = ANY(array_type_column)`.

**Comment by Evengard** [comment]
Now I have a kinda different question...
I have an array in my app which I want to compare with a server side array via Sql.Ext.PostgreSQL().Overlaps but the problem is that I have found no way to convert from my app array into PostgreSQL array so that the Overlaps works. It seems I am missing something... How do I translate the array from my app into SQL?
I could probably "hack it around" with some kind of temporary table and whatnot, but isn't there a simpler solution?

**Comment by MaceWindu** [comment]
Didn't tried it, but I think you should be able to configure mappings to pass array in parameter

**Comment by Evengard** [comment]
Could you please point in the documentation? I am struggling to understand how this all works, I am relatively new to linq2db.

**Comment by MaceWindu** [comment]
Hmm, tested it and it actually works quite fine out-of-box. What kind of issue you have with it specifically?

```cs
var p1 = new int[] { 1, 2, 3 };
var p2 = new int[] { 5, 4 };
var res = dc.Select(() => Sql.Ext.PostgreSQL().Overlaps(p1, p2));
```

```sql
-- both p1 and p2 are array-typed parameters
SELECT
	:p1 && :p2
```

only expected issue I found is when you put array literal directly in query. for such cases linq2db doesn't create parameter by default is something goes wrong:
```cs
var p1 = new int[] { 1, 2, 3 };
// this will not work, client-side array should be taken from field, variable or parameter
var res = dc.Select(() => Sql.Ext.PostgreSQL().Overlaps(p1, new int[] { 5, 4 }));
```

**Comment by Evengard** [comment]
Well, my query is a lot more complex, involving CTEs, using linq2db.EntityFrameworkCore, and the Overlaps is in the where part instead of select. Although the array is definitely not put literally in the middle of query and is instead contained in a variable...
I'll try to think of a simplified one for reproducing though...

**Comment by Evengard** [comment]
Managed to make a smaller sample
```csharp
var guids = new Guid[] { Guid.Parse("271425b1-ebe8-400d-b71d-a6e47a460ae3"),
    Guid.Parse("b75de94e-6d7b-4c70-bfa1-f8639a6a5b35") };

var result = await (
        from m in _context.Materials.AsQueryable()
        where Sql.Ext.PostgreSQL().Overlaps(m.ProgramIds, guids)
        select m
    )
    .ToArrayAsyncLinqToDB();
```

The exception is: System.Exception: 'While trying to write an array, one of its elements failed validation. You may be trying to mix types in a non-generic IList, or to write a jagged array.'
InnerException is: InvalidCastException: Can't write CLR type System.Byte[] with handler type UuidHandler
```
   at Npgsql.TypeHandlers.ArrayHandler`1.ValidateAndGetLengthNonGeneric(ICollection value, NpgsqlLengthCache& lengthCache)
   at Npgsql.TypeHandlers.ArrayHandler`1.ValidateAndGetLength(Object value, NpgsqlLengthCache& lengthCache)
   at Npgsql.TypeHandlers.ArrayHandler`1.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__105.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__105.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.<ExecuteDbDataReaderAsync>d__98.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at LinqToDB.Data.DataConnection.<ExecuteReaderAsync>d__14.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at LinqToDB.Data.DataConnection.QueryRunner.<ExecuteReaderAsync>d__35.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Linq.QueryRunner.AsyncEnumeratorImpl`1.<MoveNextAsync>d__18.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToListAsync>d__65`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.<ToArrayAsync>d__66`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.ConfiguredTaskAwaitable`1.ConfiguredTaskAwaiter.GetResult()
   at LinqToDB.AsyncExtensions.<ToArrayAsync>d__9`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

**Comment by MaceWindu** [comment]
which type you use to store guid?

**Comment by Evengard** [comment]
EF Core matches it to uuid.

**Comment by MaceWindu** [comment]
Which version of npgsql, ef.core and linq2db.efcore you use? I don't have any issue with raw linq2db here.

**Comment by Evengard** [comment]
Latest stable from nuget of all. I actually just updated them all to reproduce.

**Comment by MaceWindu** [comment]
Can confirm that with efcore involved it doesn't work. looking into it

**Comment by MaceWindu** [comment]
@sdanyliv , I see some ef.core converter applied, which replaces `guid[]` parameter value with `byte[][]` making it broken for npgsql:

![image](https://user-images.githubusercontent.com/1099238/115029025-d5581e80-9ec5-11eb-9082-a51a1ba7cfec.png)

**Comment by Evengard** [comment]
Thanks, I've created the issue linking to this discussion.
I'll try the workaround, thanks!

**Comment by Evengard** [comment]
The workaround didn't work, now I am getting 'Cannot convert value of type System.Byte[][] to SQL'
