### ISSUE TITLE
JSON Column Types, auto serialization with objects

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#1661]
Describe your issue.
Greetings. I'm just pinging developers to see 1) if this has actually been implemented now, and if not 2) see about spurring on development.

Long ago I took on some tasks (#324) that would allow as custom column type for a entities property, and in the right situation the idea is that it would serialize/deserialize json contents to a child object or collection of objects. I seem to recall problems with the type mapping stuff where most of the ground work was laid for it, but getting the hooks into linq2db as far as this should be de-serialized and populated onto the object never seemed to work quite right.

I'm particularly interested in this functionality, as it'd be convenient for storing user defined properties and things like that.

If this is something that currently doesn't exist, or doesn't work, I'd like to dig in again and figure out why and potentially get some guidance to help finishing this up. Seems like lots of databases now include support for querying/storing/retrieving json based data from a column pretty well, and things like postgres can even do advanced indexing and querying.

Wonder if @sdanyliv or others have any ideas/preferences on this? I was reading through that issue linked above and it seems like at the time of writing, it may be advised that achieving that would be done via converters or something?

**Comment by sdanyliv** [comment]
@ronnyek, there were several attempts to help in solving this. Why i expect from you it is REAL samples of usage. Even it is non compilable tests.

**Comment by ronnyek** [comment]
I can do that... I'll put together tests if I don't have them already and see if I can't reproduce the problems I have, and report back.

**Comment by ronnyek** [comment]
So I started digging into it, and I think the problem I was having initially was that because the properties are effectively just objects, the type mapping would be overly greedy, in essence trying to use the type mapping to say when I encounter a property of "object" type, convert it to json.

Currently Json/JSONB types in say postgres driver are actually supported, and can be used to pass data as parameter etc (tests exist for that).

An example of where this sort of thing would be nice, would be additional information that we'd unlikely ever need to be querying directly, but have on hand and have loose schema (defined by the mapped object types, not the db itself)

I created a gist to show an example kind of scenario where this functionality might be useful.
https://gist.github.com/ronnyek/02170a7852d1dd9138bc4f7581039d88

To be perfectly clear, I'm assuming this is a bigger endeavor than something trivial... and as I pointed out before, there are things I'm not aware of implications or problems that could arise from say something like having an array of items as json, and then someone trying to do: 
```
.Where(x=>x.Preferences.Contains(...)
```

**Comment by ronnyek** [comment]
I'm more than happy to continue to dig, I had some problems initializing schema for postgres from the PostgreSQL.sql scripts in source (looks like some of it has syntax that's tsql.

I'll see about adding some tests to MappingSchemaTests.cs. (executing some of those and seeign what they are doing might shed some light on the problems I'm having anyway)

Maybe a way we could avoid introducing a big change across the board,  I could create my own attribute, and in the type converter do something like if its a straight object or maybe something that implements a dummy interface (so I can just dynamically discern whether this is a type to be serialized, and stored as text/json), see if it is decorated with my attribute, perform custom conversion otherwise let the framework do its thing.

**Comment by sdanyliv** [comment]
Think in API terms. Write sample linq query
```cs
query = from q in db.GetTable<UserWithProfile>()
  where q.Profile.Name == "SomeName" 
  select q
```
and which SQL do you expect.
More samples we cover - more robust solution may appear.

**Comment by ronnyek** [comment]
That's a totally valid question... I think with databases that supported it, those could be translated into queries that would actually query json and be efficient (PostgreSQL can do this easily - `profile->>'name' = 'SomeName'`) but I know there would be databases that didn't support it at all, or stored the JSON in text/blob columns. 

An example of what queries could look like for that support could be:
``` sql
-- postgres
where profile->>'name' = 'SomeName'

--sql server
where JSON_VALUE(profile,'$.name')='SomeName'

```

Additionally, I don't think it'd be unreasonable to not be able to use json fields where criteria for child JSON properties, thought I'd assume there really is no way you could prevent that from happening with the LINQ implementation.

I use marten library to do this stuff in postgres only applications (http://jasperfx.github.io/marten/) and it works really well, but there may just be no way to do this generically and still provide value outside of db's that support json querying

**Comment by ronnyek** [comment]
Another ORM I used to use (ORMLite) used to have this feature, and I'm not sure you could actually query against the serialized json, but it was extremely handy for allowing users to just add additional key/value pairs to the entity itself (something like user defined columns, without needing a schema modification)

**Comment by Vitegor** [comment]
This is a necessary and useful feature, please, implement this

**Comment by ademchenko** [comment]
Btw, in npgsql there has been made some work for ef to map json fields: https://www.npgsql.org/efcore/mapping/json.html?tabs=data-annotations%2Cpoco

**Comment by krispetkov** [comment]
Hey @ronnyek, are there any plans or ETA for this feature? This is one of the advantages of Postgres and it would be great if it can be used by the developers (I can see other people are also wanting this functionality). I have a case where I have a class:

```C#
public class OrderRecord
{
    public string Source { get; set; }
    public Order Value { get; set; }
    public DateTime CreatedAt { get; set; }
    public DateTime UpdatedAt { get; set; }
}
    
public class Order
{
 ...
   public int Number { get; set; }
 ...
}    
```

And what I tried to achieve is to query the database by jsonb property, but it seems this is not implemented yet:

```C#
_somerepo.Table.Where(x => x.Value.Number == 123).ToList();
```

ANd it seems there are some issues with deserialization of the returned string (json) to the concrete type 🤔

**Comment by jods4** [comment]
Note EF7 has introduced support to map into JSON columns (quite interesting when mapping a relation that way, e.g. persist a list of "tags" as a JSON column in your `Product` table without needing a join to `ProductTag` table), as well as querying into JSON columns:
https://devblogs.microsoft.com/dotnet/announcing-ef7-release-candidate-2/#mapping-to-json-columns

It would be a powerful addition to linq2db, but it's a large feature to implement.

**Comment by LaXiS96** [comment]
I too am in desperate need of this feature.
In my case even EFCore7's `ToJson` owned entities are not applicable, as my JSON objects are not predefined but are just serialized `Dictionary<string, object?>`, yet I still need to efficiently query them (from user-provided dynamic filter expressions). PostgreSQL has the means to do exactly that, but the only library that implements LINQ to `jsonb` (partially though) is Npgsql.EFCore and I'd prefer to avoid EFCore for various reasons.
EFCore8 still does not support schema-less JSON column mapping, but it's "planned".

I'd suggest taking inspiration from Npgsql.EFCore as far as accesses to JSON columns are translated.

**Comment by sdanyliv** [comment]
Please check this my solution it is fastest way to get JSON filtering https://github.com/linq2db/linq2db/issues/4343#issuecomment-1816460380

Currently it is written for objects with properties, but can be easily extended.

**Comment by LaXiS96** [comment]
@sdanyliv thank you, that is a good solution when you control the expression source.
In cases where the expression cannot use custom function calls (i.e. because it's generated from another library), how can I extend linq2db to intercept the property access (like `dictionary["key"]`) and translate it?
One alternative would be to transform the original expression, replacing specific access patterns with calls to custom methods, but that's quite a bit of work.

**Comment by AudriusButkevicius** [comment]
Am I wrong, or even IUpdatable does not work with jsonb?

i.e, I have a column that stores a jsonb object using EF .ToJson(), however doing,

ctx.MyTable.Where(...).Set(o => o.NameOfJsonField,, instanceOfJsonSerializableObject).Update()

does not seem to work.

It blows up looking for a ForeignKey to the entity representing the json:
```
 ---> LinqToDB.Linq.LinqException: Association key 'OrderPreviewId' not found for type 'Server.Models.OrderPreview.
   at LinqToDB.Linq.Builder.AssociationHelper.CreateAssociationQueryLambda(ExpressionBuilder builder, AccessorMember onMember, AssociationDescriptor association, Type parentOriginalType, Type parentType, Type objectType, Boolean inline, Boolean enforceDefault, List`1 loadWith, Boolean& isLeft)
   at LinqToDB.Linq.Builder.AssociationHelper.BuildAssociationInline(ExpressionBuilder builder, BuildInfo buildInfo, TableContext tableContext, AccessorMember onMember, AssociationDescriptor descriptor, Boolean inline, Boolean& isOuter)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.FindContextExpression(Expression expression, Int32 level, Boolean forceInner, Boolean throwExceptionForNull)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.UpdateBuilder.ParseSet(ExpressionBuilder builder, LambdaExpression extract, MethodCallExpression updateMethod, Int32 valueIndex, IBuildContext select, List`1 items)
   at LinqToDB.Linq.Builder.UpdateBuilder.Set.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at LinqToDB.LinqExtensions.UpdateAsync[T](IUpdatable`1 source, CancellationToken token)
