### ISSUE TITLE
System.NotImplementedException after GroupBy OrderBy

### ISSUE THREAD

**Issue by yurriiy** [linq2db/linq2db#1664]
linq2db.SqlServer 2.6.4

```
Exception message: 
System.NotImplementedException: The method or operation is not implemented.
Stack trace:
Terirus.CustomExceptionMiddleware+<InvokeAsync>d__3.MoveNext | Произошла необработанная ошибка: System.NotImplementedException: The method or operation is not implemented.
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\TableBuilder.TableContext.cs:line 751
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 300
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 941
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 300
   at LinqToDB.Linq.Builder.GroupByBuilder.GroupByContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\GroupByBuilder.cs:line 605
   at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SubQueryContext.cs:line 39
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 374
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 859
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 662
   at LinqToDB.Linq.Builder.SelectContext.ConvertExpressions(Expression expression, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 404
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 357
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 859
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 662
   at LinqToDB.Linq.Builder.OrderByBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\OrderByBuilder.cs:line 48
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.CountBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\CountBuilder.cs:line 21
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 176
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 147
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 268
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 232
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 84
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 165
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Terirus.Data.DataService.SearchOwnerDebt(ListRequest listRequest, Int32& total, Int32 userId) in C:\Work\Projects\Terirus\backend\Terirus\Data\DataService.cs:line 1532
   at Terirus.Logic.LogicService.SearchOwnerDebt(ListRequest listRequest) in C:\Work\Projects\Terirus\backend\Terirus\Logic\LogicService.cs:line 869
   at Terirus.Controllers.CalculationController.SearchOwnerDebt(ListRequest listRequest) in C:\Work\Projects\Terirus\backend\Terirus\Controllers\CalculationController.cs:line 35
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.Extensions.Internal.ObjectMethodExecutor.Execute(Object target, Object[] parameters)
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Routing.EndpointRoutingMiddleware.Invoke(HttpContext httpContext)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
```

### Steps to reproduce
With this row
```c#
items = items.OrderBy(a => a.Owner.OwnerId);
```
i get exception at materialization in Count()

```c#
var temp = db.Calculation.LoadWith(a => a.Owner).AsQueryable();

//some conditions, for example:
temp = temp.Where(s => s.Type == 1);

var items = temp.GroupBy(a => a.Owner)
				.Join(db.ObjectOwner,
					a => a.Key.OwnerId,
					b => b.OwnerId,
					(a, b) => new Dto.OwnerDebt
					{
						Owner = a.Key,
						AccountNumber = b.AccountNumber,
						Balance = b.Balance,
						Debt = a.Sum(i => i.Debt ?? 0)
					});
					
items = items.OrderBy(a => a.Owner.OwnerId); //without this row - works fine

var total = items.Count(); //exception if OrderBy exist
```

### Environment details
linq2db version: *2.6.4*
Database Server: *14.00.2002*
Operating system: *Windows 10*
Framework version: *.NET Core 2.2*

**Comment by sdanyliv** [comment]
@yurriiy, please show me generated SQL for working situation. I can’t understand what this query do.

**Comment by yurriiy** [comment]
Without OrderBy clause, when all works
variable items befor Count() call
```
-- SqlServer SqlServer.2012
SELECT
	[a].[OwnerId],
	[a].[OrganizationId],
	[a].[LastName],
	[a].[FirstName],
	[a].[MiddleName],
	[a].[Gender],
	[a].[Birthday],
	[a].[DocumentTypeId],
	[a].[DocumentDate],
	[a].[DocumentSeries],
	[a].[DocumentNumber],
	[a].[DocumentAdd],
	[a].[Phone],
	[a].[Email],
	[a].[RegistrationAddressId],
	[a].[ActualAddressId],
	[b].[AccountNumber],
	[b].[Balance],
	[a].[c1]
FROM
	(
		SELECT
			[a_Owner].[OwnerId],
			[a_Owner].[OrganizationId],
			[a_Owner].[LastName],
			[a_Owner].[FirstName],
			[a_Owner].[MiddleName],
			[a_Owner].[Gender],
			[a_Owner].[Birthday],
			[a_Owner].[DocumentTypeId],
			[a_Owner].[DocumentDate],
			[a_Owner].[DocumentSeries],
			[a_Owner].[DocumentNumber],
			[a_Owner].[DocumentAdd],
			[a_Owner].[Phone],
			[a_Owner].[Email],
			[a_Owner].[RegistrationAddressId],
			[a_Owner].[ActualAddressId],
			Sum(IIF([t1].[Debt] IS NULL, 0, [t1].[Debt])) as [c1]
		FROM
			[dbo].[Calculation] [t1]
				INNER JOIN [dbo].[Owner] [a_Owner] ON [t1].[OwnerId] = [a_Owner].[OwnerId]
		GROUP BY
			[a_Owner].[OwnerId],
			[a_Owner].[OrganizationId],
			[a_Owner].[LastName],
			[a_Owner].[FirstName],
			[a_Owner].[MiddleName],
			[a_Owner].[Gender],
			[a_Owner].[Birthday],
			[a_Owner].[DocumentTypeId],
			[a_Owner].[DocumentDate],
			[a_Owner].[DocumentSeries],
			[a_Owner].[DocumentNumber],
			[a_Owner].[DocumentAdd],
			[a_Owner].[Phone],
			[a_Owner].[Email],
			[a_Owner].[RegistrationAddressId],
			[a_Owner].[ActualAddressId]
	) [a]
		INNER JOIN [dbo].[ObjectOwner] [b] ON [a].[OwnerId] = [b].[OwnerId]

```

With OrderBy

![exception](https://user-images.githubusercontent.com/38867716/55135680-4af8c280-5124-11e9-8f33-e3db0200917b.png)

**Comment by yurriiy** [comment]
version linq2db 2.6.2 - same behavior

**Comment by sdanyliv** [comment]
@yurriiy, will check. But i recommend to rewrite query. Grouping by whole entity will use more server resources than are needed.
Group calculations by OwnerId and then join to other required tables. Also in this case LoadWith is not needed.

**Comment by yurriiy** [comment]
@sdanyliv thx, i changed the query (group by primary key):
```C#
var temp = db.Calculation.AsQueryable();

var items = temp.GroupBy(a => a.OwnerId)
    .Join(db.ObjectOwner,
        a => a.Key,
        b => b.OwnerId,
        (a, b) => new 
        {
            OwnerId = a.Key,
            b.AccountNumber,
            b.Balance,
            Debt = a.Sum(i => i.Debt ?? 0)
        })
    .Join(db.Owner,
        a => a.OwnerId,
        b => b.OwnerId,
        (a, b) => new Dto.OwnerDebt
        {
            Owner = b,
            AccountNumber = a.AccountNumber,
            Balance = a.Balance,
            Debt = a.Debt
        });

       items = items.OrderBy(a => a.Owner.OwnerId);

       int total = items.Count();
```
SQL without OrderBy:
```SQL
-- SqlServer SqlServer.2012
SELECT
	[b_2].[OwnerId],
	[b_2].[OrganizationId],
	[b_2].[LastName],
	[b_2].[FirstName],
	[b_2].[MiddleName],
	[b_2].[Gender],
	[b_2].[Birthday],
	[b_2].[DocumentTypeId],
	[b_2].[DocumentDate],
	[b_2].[DocumentSeries],
	[b_2].[DocumentNumber],
	[b_2].[DocumentAdd],
	[b_2].[Phone],
	[b_2].[Email],
	[b_2].[RegistrationAddressId],
	[b_2].[ActualAddressId],
	[b_1].[AccountNumber],
	[b_1].[Balance],
	[a].[Debt]
FROM
	(
		SELECT
			[t1].[OwnerId],
			Sum(IIF([t1].[Debt] IS NULL, 0, [t1].[Debt])) as [Debt]
		FROM
			[dbo].[Calculation] [t1]
		GROUP BY
			[t1].[OwnerId]
	) [a]
		INNER JOIN [dbo].[ObjectOwner] [b_1] ON [a].[OwnerId] = [b_1].[OwnerId]
		INNER JOIN [dbo].[Owner] [b_2] ON [a].[OwnerId] = [b_2].[OwnerId]
```

but still get exception if OrderBy exist

**Comment by sdanyliv** [comment]
Try this one. I'm not a big fan of method chain syntax and prefer linq queries which looks like SQL.
```cs
var temp = db.Calculation.AsQueryable();

var grouping = 
   from a in temp
   group a by b.OwnerId into g
   select new 
   {
       OwnerId = g.Key,
       Debt = g.Sum(i => i.Debt ?? 0)
   };

var items = 
   from g in grouping
   from o in db.Owner.InnerJoin(o => o.OwnerId == g.OwnerId)
   from oo in db.ObjectOwner.InnerJoin(oo => oo.OwnerId == g.OwnerId)
   select new Dto.OwnerDebt
   {
        Owner = o,
        AccountNumber = oo.AccountNumber,
        Balance = oo.Balance,
        Debt = oo.Debt
    });

items = items.OrderBy(a => a.Owner.OwnerId);
int total = items.Count();
```

**Comment by yurriiy** [comment]
I localized problem, but don't understand how it solve
```C#
var items = temp.GroupBy(a => a.OwnerId)
    .Join(db.ObjectOwner,
        a => a.Key,
        b => b.OwnerId,
        (a, b) => new 
        {
            OwnerId = a.Key,
            b.AccountNumber,
            b.Balance,
            Debt = a.Sum(i => i.Debt ?? 0)
        })
    .Join(db.Owner,
        a => a.OwnerId,
        b => b.OwnerId,
        (a, b) => new Dto.OwnerDebt
        {
            Owner = b, //**problem here, type cast**
            AccountNumber = a.AccountNumber,
            Balance = a.Balance,
            Debt = a.Debt
        });

       items = items.OrderBy(a => a.Owner.OwnerId);

       int total = items.Count();
```
Property Owner in Dto.OwnerDebt it is Dto object with implicit operator Data to Dto
```C#
    public class Owner
    {
        public int OwnerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
		
	...

        public static implicit operator Owner(Data.Owner a)
        {
            if (a == null) return null;

            return new Owner()
            {
                OwnerId = a.OwnerId,
                FirstName = a.FirstName,
                LastName = a.LastName,
                ...
            };
        }
}
```
When i change property Owner class in Dto.OwnerDebt to Data class (generated by .tt) all works.

How can i get list of Dto.OwnerDebt class, where Owner property is Dto class ?

**Comment by sdanyliv** [comment]
Oh, I see. You have broken Expression Tree. If in linq queries you have used code which do not produce Expression Tree - we can not trace back which field was used, in your situation - it is field for ordering.
Not sure if it will work, but you have to try:
```cs
    public class Owner
    {
        public int OwnerId { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
		
	...

        static Expression<Data.Owner, Owner> OwnerImpl()
        {
            return a => new Owner()
            {
                OwnerId = a.OwnerId,
                FirstName = a.FirstName,
                LastName = a.LastName,
                ...
            };
        }

        [ExpressionMethod(name(OwnerImpl)]
        public static implicit operator Owner(Data.Owner a)
        {
            if (a == null) return null;

            return new Owner()
            {
                OwnerId = a.OwnerId,
                FirstName = a.FirstName,
                LastName = a.LastName,
                ...
            };
        }
}
```

**Comment by sdanyliv** [comment]
Otherwise only client evaluation may help:
```cs
items = items.AsEnumerable().OrderBy(a => a.Owner.OwnerId);
```
Which is not good for fo the following `Count()` operator.

**Comment by yurriiy** [comment]
```C#
public class Owner
    {
        public int OwnerId { get; set; }    
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        ...

        static Expression<Func<Data.Owner, Owner>> OwnerImpl()
        {
            return a => new Owner()
            {
                OwnerId = a.OwnerId,
                FirstName = a.FirstName,
                LastName = a.LastName,
                MiddleName = a.MiddleName,
                ...
            };
        }        

        [ExpressionMethod("OwnerImpl")]
        public static implicit operator Owner(Data.Owner a)
        {
            if (a == null) return null;
            return OwnerImpl().Compile()(a);
        }
    }
```
not work with code

```C#
var temp = db.Calculation.AsQueryable();

var items = temp.GroupBy(a => a.OwnerId)
	.Join(db.ObjectOwner,
		a => a.Key,
		b => b.OwnerId,
		(a, b) => new
		{
			OwnerId = a.Key,
			b.AccountNumber,
			b.Balance,
			Debt = a.Sum(i => i.Debt ?? 0)
		})
	.Join(db.Owner,
		a => a.OwnerId,
		b => b.OwnerId,
		(a, b) => new Dto.OwnerDebt
		{
			Owner = b,
			AccountNumber = a.AccountNumber,
			Balance = a.Balance,
			Debt = a.Debt
		});
items = items.OrderBy(a => a.Owner.OwnerId);

int total = items.Count();
```

Why Expression tree breaks with OrderBy, but work without?

**Comment by sdanyliv** [comment]
It is broken by implicit operator - after that we do not know which fields of Owner mapped to Data.Owner.

**Comment by yurriiy** [comment]
I try this and it's work
```C#
var temp = db.Calculation.AsQueryable();

var items = temp.GroupBy(a => a.OwnerId)
	.Join(db.ObjectOwner,
		a => a.Key,
		b => b.OwnerId,
		(a, b) => new
		{
			OwnerId = a.Key,
			b.AccountNumber,
			b.Balance,
			Debt = a.Sum(i => i.Debt ?? 0)
		})
	.Join(db.Owner,
		a => a.OwnerId,
		b => b.OwnerId,
		(a, b) => new Dto.OwnerDebt
		{
			Owner = new Dto.Owner() { OwnerId = b.OwnerId, FirstName = b.FirstName }, //костыль
			AccountNumber = a.AccountNumber,
			Balance = a.Balance,
			Debt = a.Debt
		});
items = items.OrderBy(a => a.Owner.OwnerId);

int total = items.Count();
```
SQL
```SQL
-- SqlServer SqlServer.2012
SELECT
	[b_2].[OwnerId],
	[b_2].[FirstName],
	[b_1].[AccountNumber],
	[b_1].[Balance],
	[a].[Debt]
FROM
	(
		SELECT
			[t1].[OwnerId],
			Sum(IIF([t1].[Debt] IS NULL, 0, [t1].[Debt])) as [Debt]
		FROM
			[dbo].[Calculation] [t1]
		GROUP BY
			[t1].[OwnerId]
	) [a]
		INNER JOIN [dbo].[ObjectOwner] [b_1] ON [a].[OwnerId] = [b_1].[OwnerId]
		INNER JOIN [dbo].[Owner] [b_2] ON [a].[OwnerId] = [b_2].[OwnerId]
ORDER BY
	[b_2].[OwnerId] DESC

```

are there any ideas how to make work implicit operator in this scenario?

**Comment by sdanyliv** [comment]
I’ll check. ExpressionMethod should work in this case.

**Comment by sdanyliv** [comment]
@yurriiy, i have improved this area. Next release should contain fix and you will be able to use `ExpressionMethod` here.
