### ISSUE TITLE
T4 Models Generation in .net core

### ISSUE THREAD

**Issue by Fruchuxs** [linq2db/linq2db#1674]
I think [this](https://linq2db.github.io/articles/Source/LinqToDB.Templates/README.html) readme is rly outdated. First of all it's not understandable from where the files must be copied. I found some files in `.nuget\packages\linq2db.mysql\2.6.4\content\LinqToDB.Templates`, but there is just a `CopyMe.MySql.tt.txt` (no Core in the name).

> open $(SolutionDir).tools\linq2db.t4models in Explorer

Doesn't exists. I need to create it? Maybe, but where?

> copy CopyMe.XXX.Core.tt.txt to your project's folder or subfolder, then you should use it instead of CopyMe.XXX.tt.txt

From where I shall copy it?! No file here.

I don't know what to do here.

EDIT: `LoadMatadata()` / `GenerateModel() ` I don't know which method do u mean.

**Comment by MaceWindu** [comment]
Yep. This part looks strange and outdated.

Basically you just need to create a copy of .txt file for your provider (e.g. `CopyMe.MySql.tt.txt`) and rename it to something with `.tt` extension. And of course edit it to have proper connection string and tune default generation options if you need.

**Comment by Fruchuxs** [comment]
Thank you.
But I got an exception. I don't know if this is also a documentation error (the readme says MySql.Data ist shipped) or a general problem.
```
Severity	Code	Description	Project	File	Line	Suppression State
Error		An exception was thrown while trying to compile the transformation code. The following Exception was thrown:
System.IO.FileNotFoundException: Could not find file 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\MySql.Data.dll'.
File name: 'C:\Program Files (x86)\Microsoft Visual Studio\2019\Community\Common7\IDE\MySql.Data.dll'
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
   at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share)
   at Roslyn.Utilities.FileUtilities.OpenFileStream(String path)
   at Microsoft.CodeAnalysis.MetadataReference.CreateFromFile(String path, MetadataReferenceProperties properties, DocumentationProvider documentation)
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.<>c.<.ctor>b__15_0(String x)
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Linq.Enumerable.<UnionIterator>d__67`1.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Collections.Immutable.ImmutableArray.CreateRange[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.ImmutableArrayExtensions.AsImmutableOrEmpty[T](IEnumerable`1 items)
   at Microsoft.CodeAnalysis.Compilation.ValidateReferences[T](IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.WithReferences(IEnumerable`1 references)
   at Microsoft.CodeAnalysis.CSharp.CSharpCompilation.CommonWithReferences(IEnumerable`1 newReferences)
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.PrepareNewCompilation()
   at Microsoft.VisualStudio.TextTemplating.CompilerBridge.Compile()
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.Compile(String source, String inputFile, IEnumerable`1 references, Boolean debug, SupportedLanguage language, String compilerOptions)	Essence		1	

```

**Comment by Fruchuxs** [comment]
If I copy the DLL I got a strong name verification exception and a "linq2db.dll" not found exception. Seems a general problem.

**Comment by MaceWindu** [comment]
For a moment you made me scared that Microsoft changed T4 in VS2019 :smile:

**Comment by Fruchuxs** [comment]
The correct approuch should be:
* Copy `CopyMe.MySql.tt.txt" from `%userprofile%\.nuget\packages\linq2db.mysql\<linq2db version>\content\LinqToDB.Templates` to destination folder and rename it to `*.tt`
* Open File in Visual Studio and edit Connection Data at the end of the file
