### ISSUE TITLE
DateDiff() in linq expression doesnt get translated to an SQL function supported by SQLite

### ISSUE THREAD

**Issue by iouris** [linq2db/linq2db#1688]
Hi Guys,

I'm targeting SQLite using linq over linq2db, and have encountered an issue whereby the LinqToDB.Sql.DateDiff(LinqToDB.Sql.DateParts.Day, ..) function used in linq expression gets translated to DateDiff(Day, ..) in SQL, and it is not supported by SQLite.

If you know a workaround for the issue I'd appreciate if you'd let me know.

```sql
--  SQLite.MS SQLite
DECLARE @now  -- DateTime
SET     @now = '2019-05-01'

SELECT
	[item].[PatientID]
FROM
	[Patient] [item]
WHERE
	DateDiff(Day, [item].[Created], @now) > 10
```

```
Exception message:  SQLite Error 1: 'no such column: Day'
Stack trace:
Microsoft.Data.Sqlite.SqliteException (0x80004005): SQLite Error 1: 'no such column: Day'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 1227
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 320
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source) 
```

### Steps to reproduce
The ToList() call in the code below throw the above exception.

```c#
var qpatientIdsCreatedOver10DaysAgo =
    from patient in qpatients
    let createdDaysAgo = LinqToDB.Sql.DateDiff(LinqToDB.Sql.DateParts.Day, patient.Created, now).Value
    where createdDaysAgo > 10
    select patient.Id;

var patientIdsCreatedOver10DaysAgo = qpatientIdsCreatedOver10DaysAgo.Take(10).ToList();
```

### Environment details
linq2db version: *2.6.4*
Database Server: *SQLite*
Database Provider: *SQLite.MS*
Operating system: *Windows 10*
Framework version: *.NET Core 2.1*

**Comment by MaceWindu** [comment]
Yep, right now this extension not implemented for sqlite and use default implementation, which sqlite don't understand.
As workaround you can create your own extension using sqlite datetime functions. Looks like for difference in days you can use first snippet from here: https://stackoverflow.com/posts/34383293/revisions
