### ISSUE TITLE
Hana SQL: ExecuteProcAsync issue

### ISSUE THREAD

**Issue by MichielDG** [linq2db/linq2db#1740]
I've using linq2db for SapHana and want to use the method ExecuteProcAsync from the DataConnectionExtensions class. But when I execute the flowing code 
```c#
await dataConnection.ExecuteProcAsync("TriAPI_AddPlanningElement",
                new DataParameter("@parentKey", parameters.ParentKey, DataType.VarChar),
                new DataParameter("@description", parameters.Description, DataType.VarChar),
                new DataParameter("@calendarKey", parameters.CalendarKey, DataType.VarChar),
                new DataParameter("@scheduleStart", parameters.ScheduleStart, DataType.DateTime),
                new DataParameter("@scheduleFinish", parameters.ScheduleFinish, DataType.DateTime),
                new DataParameter("@returnStatus", returnStatus, DataType.Int32) { Direction = ParameterDirection.InputOutput },
                new DataParameter("@returnKey", planningKey, DataType.VarChar) { Direction = ParameterDirection.InputOutput, Size = 20 });
```

I get an exception like this:
```
Sap.Data.Hana.HanaException (0x80004005): invalid name of function or procedure: TRIAPI_ADDPLANNINGELEMENT: line 1 col 6 (at pos 5)
   at Sap.Data.Hana.HanaCommand._ExecuteNonQuery()
   at Sap.Data.Hana.HanaCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Data.DataConnection.<ExecuteNonQueryAsync>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Data.CommandInfo.<ExecuteAsync>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at DS.SBO.Integration.DataAccessLayer.Sql.Schema.StoredProcedures.TriAPIAddPlanningElement.<ExecuteTriAPIAddPlanningElement>d__0.MoveNext(
```

I think the problem is that the store procedure is executed without double quotes around it and that's why hana thinks the store procedure is all in uppercase.

### Environment details
linq2db version: *2.7.1*
Database Server: *Hana 1.00*
Database Provider: *Sap.Data.Hana.v4.5*
Framework version: *.NET Framework 4.7.2*

**Comment by MaceWindu** [comment]
I've checked our `ExecuteProc*` and this is actually expected behavior - we expect `sql` parameter to contain escaped SQL, as it could be [FQN name with schema/database](https://github.com/linq2db/linq2db/blob/master/Tests/T4.Linq/SapHana.generated.cs#L13522).

I'll update xml documentation on those methods and leave this issue open to consider new API in future with separate parameters for procedure name fragments and escaping on linq2db side
