### ISSUE TITLE
ArgumentOutOfRangeException after using UNION with new SELECT

### ISSUE THREAD

**Issue by millworm** [linq2db/linq2db#1774]
I wanted to make a new SELECT from the result of the UNION, but I got an error. A small test that reproduces it is attached below.

```
Message: System.ArgumentOutOfRangeException : Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index

Stack trace:
at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at LinqToDB.SqlQuery.SelectQueryOptimizer.<>c__DisplayClass12_0.<OptimizeUnions>b__2(IQueryElement e)
   at LinqToDB.SqlQuery.QueryVisitor.Visit2(IQueryElement element)
   at LinqToDB.SqlQuery.QueryVisitor.Visit(IQueryElement element, Action`1 action)
   at LinqToDB.SqlQuery.SelectQueryOptimizer.OptimizeUnions()
   at LinqToDB.SqlQuery.SelectQueryOptimizer.FinalizeAndValidate(Boolean isApplySupported, Boolean optimizeColumns)
   at LinqToDB.SqlProvider.BasicSqlOptimizer.<>c__DisplayClass4_0.<Finalize>b__0(SelectQuery selectQuery)
   at LinqToDB.SqlQuery.SqlStatementWithQueryBase.WalkQueries(Func`2 func)
   at LinqToDB.SqlProvider.BasicSqlOptimizer.Finalize(SqlStatement statement)
```

### Steps to reproduce
```
[Test]
public void AfterUnionError([DataSources] string context)
{
	using (var db = GetDataContext(context))
	{
		var q1 = from p in db.Person where p.ID == 1 select new { p.ID};
		var q2 = from p in db.Person where p.ID != 1 select new { p.ID };
		var q = q1.Concat(q2);
		var f = q.Select(t => new {t.ID, rn = Sql.Ext.DenseRank().Over().OrderBy(t.ID).ToValue()}).ToList();				
	}
}
```

### Environment details
linq2db version: 2.7.1.0
.NET Framework: 4.7.2

**Comment by MaceWindu** [comment]
As temporary workaround you can put `t.ID` column to second position in `Select()`

**Comment by millworm** [comment]
Yeap. That's exactly what I did
