### ISSUE TITLE
LEFT JOIN in F#

### ISSUE THREAD

**Issue by giuliohome** [linq2db/linq2db#1813]
I'm trying to form a left join in F# but I'm getting an Exception

```
Exception message: 
variable '_arg1' of type 'Program+Names' referenced from scope '', but it is not defined
Stack trace:
Eccezione non gestita di tipo 'System.InvalidOperationException' in System.Linq.Expressions.dll
```

### Steps to reproduce

The code is quite trivial

```f#
let db = new DataConnection("SqlServer",@"Data Source=(localdb)\MSSQLLocalDB;Initial Catalog=MyDB;Integrated Security=True;Pooling=False")

let query = query {
    for n in db.GetTable<Names>() do
    for a in db.GetTable<Addresses>().Where(fun a1 -> n.Id = a1.Id).DefaultIfEmpty() do
    select (n.Id, n.Name, a)
    }

let names = query |> Seq.toArray
```

I've also tried

```f#
let query = query {
    for n in db.GetTable<Names>() do
    leftOuterJoin a in db.GetTable<Addresses>() 
        on (n.Id = a.Id) into g_a
    select (n.Id, n.Name, g_a)
    }
let names = query |> Seq.toArray
```

but it fails with

```
Exception message: 
Multiple queries are not allowed. Set the 'LinqToDB.Common.Configuration.Linq.AllowMultipleQuery' flag to 'true' to allow multiple queries.
```

and 

```f#
let query = query {
    for n in db.GetTable<Names>() do
    leftOuterJoin a in db.GetTable<Addresses>() 
        on (n.Id = a.Id) into g_a
    for a in g_a do
    select (n.Id, n.Name, a)
    }
```
that gives 

```
Exception message: 
Eccezione non gestita di tipo 'System.NotImplementedException' in linq2db.dll
The method or operation is not implemented.
```

### Environment details
linq2db version: latest
Database Server: Sql Server

**Comment by MaceWindu** [comment]
Yep, this is known issue with F# generating _a bit_ different code for left join than C# compiler, which our parser currently doesn't support. See #417 for workaround

**Comment by MaceWindu** [comment]
Duplicate #417

**Comment by giuliohome** [comment]
Thank you very much! The workaround seems very helpful!

**Comment by giuliohome** [comment]
Thank you again! The workaround does work!

However, when I use it twice for a double left join

```f#
let db = new DataConnection("AppDB") 
let tradesQuery = 
    query {
        for tr in db.GetTable<TradeValid>() do    
        groupJoin n_del in db.GetTable<NominationValid>()                 
            on ((tr.DealNumber,tr.ParcelGroupID, tr.ParcelID) = (n_del.DeliveryDealNumber, n_del.DeliveryParcelGroup, n_del.DeliveryParcelID))  into n_del_g
        for x in n_del_g.DefaultIfEmpty() do 
        groupJoin n_rec in db.GetTable<NominationValid>()                 
            on ((tr.DealNumber,tr.ParcelGroupID, tr.ParcelID) = (n_rec.ReceiptDealNumber, n_rec.ReceiptParcelGroup, n_rec.ReceiptParcelID))  into n_rec_g
        for y in n_rec_g.DefaultIfEmpty() do 
        yield (tr, x, y)
        } 
let trades = tradesQuery.Take(90).ToArray();
db.Close()
db.Dispose()

```

I get the following exception. Each single left join works if alone.
Am I doing something stupid that I can't spot?

```
[ArgumentOutOfRangeException: Index non compreso nell'intervallo. Richiesto valore non negativo e minore della dimensione della raccolta. Nome parametro: index]    System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource) +64    System.SZArrayHelper.get_Item(Int32 index) +12915184    LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:742    LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:625    LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:208    LinqToDB.Linq.Builder.GroupJoinContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\JoinBuilder.cs:464    LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:151    LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:139
--
```


Little of topic question.
This ORM is my favourite and really great, it can be used even for F# and consider that SqlTypeProvider (which is specific to F#) throws an exception even with @dsyme workaround! That's why I reverted from using SqlTypeProvider to Linq2DB also for F#! But I need to translate ` ColumnValues` from SqlTypeProvider to Linq2DB 
This is my solution with reflection, is there a better way?
```f#
let trade_cols = seq {
    for col in db.MappingSchema.GetEntityDescriptor(typedefof<TradeValid>).Columns do
    yield (col.MemberName, col.DataType, (typedefof<TradeValid>).GetField(col.MemberName))
    }
```
then later in the code I can do
```f#
for (k,dt,i) in ServerModel.trade_cols do
    yield td [] [text <| string (i.GetValue(t))]
```

**Comment by sdanyliv** [comment]
@giuliohome, how about using `LeftJoin` function?
Also, can you decompile your F# code by dotPeek, or Reflector and post it in C#? In this case we can reproduce this in our side easily.

**Comment by MaceWindu** [comment]
@sdanyliv we already have test for #417 . But it makes sense to add another one for two joins issue

**Comment by giuliohome** [comment]
Thank you for adding another test for the two left joins issue! 

Notice that if I split the two left joins into two queries (in this way I can yield from the first one), the runtime error disappears but very strangely the results are always null for the second left join (while there are matching records)

split code is
```f#
let tradesQueryL1 = 
        query {
            for tr in db.GetTable<TradeValid>() do 
            groupJoin n_rec in db.GetTable<NominationValid>()                 
                on ((tr.DealNumber,tr.ParcelGroupID, tr.ParcelID) = (n_rec.ReceiptDealNumber, n_rec.ReceiptParcelGroup, n_rec.ReceiptParcelID))  into n_rec_g
            for y in n_rec_g.DefaultIfEmpty() do 
            yield (tr, y)
            } 
let tradesQuery =
    query {
        for (tr,y) in tradesQueryL1 do    
            groupJoin n_del in db.GetTable<NominationValid>()                 
                on ((tr.DealNumber,tr.ParcelGroupID, tr.ParcelID) = (n_del.DeliveryDealNumber, n_del.DeliveryParcelGroup, n_del.DeliveryParcelID))  into n_del_g
            for x in n_del_g.DefaultIfEmpty() do
            yield (tr, x, y)
    }
```

**Comment by sdanyliv** [comment]
@giuliohome, try also this variant. It is just sample, i'm not familiar with F# syntax.
 ```fs
let tradesQueryL1 = 
        query {
            for tr in db.GetTable<TradeValid>() do 
            for y in db.GetTable<TradeValid>().Leftjoin(fun y -> 
                        y.ReceiptDealNumber = tr.DealNumber && 
                        y.ReceiptParcelGroup = tr.ParcelGroupID && 
                        y.ReceiptParcelID = tr.ParcelID) do 
            yield (tr, y)
            } 
```

**Comment by giuliohome** [comment]
If I write
```f#
let tradesQueryL1 = 
       query {
           for tr in db.GetTable<TradeValid>() do 
           for y in db.GetTable<NominationValid>()
            .LeftJoin(fun y -> 
                       y.ReceiptDealNumber = tr.DealNumber && 
                       y.ReceiptParcelGroup = tr.ParcelGroupID && 
                       y.ReceiptParcelID = tr.ParcelID) do 
           yield (tr, y)
           } 

```
it compiles and throws at runtime
```
[InvalidOperationException: la variabile '_arg1' di tipo 'Import2TSS.TradeValid' a cui viene fatto riferimento dall'ambito '' non è definita]    System.Linq.Expressions.Compiler.VariableBinder.Reference(ParameterExpression node, VariableStorageKind storage) +4859163    System.Linq.Expressions.Compiler.VariableBinder.VisitParameter(ParameterExpression node) +40    System.Linq.Expressions.ParameterExpression.Accept(ExpressionVisitor visitor) +13
```

but I can transform also the second query 

```f#
let tradesQuery =   
    query {
        for (tr,y) in tradesQueryL1 do  
           for x in db.GetTable<NominationValid>()
            .LeftJoin(fun x -> 
                       x.ReceiptDealNumber = tr.DealNumber && 
                       x.ReceiptParcelGroup = tr.ParcelGroupID && 
                       x.ReceiptParcelID = tr.ParcelID) do   
            yield (tr, x, y)
    }
```

and the exception is the same at runtime.

(By the way I spent time trying to transform f# quotations to linq expressions because I thought it was needed for methods like leftjoin but it seems it compiles with a simple f# fun.)
I guess the point of this issue is the fact that this LeftJoin is somehow different from the C# version and the only workaround till now is the groupJoin. Unfortunately, when there are a couple of left joins, I have to enumerate the first query though.

**Comment by sdanyliv** [comment]
Add this code 
```fs
let str = problematicQuery.GenerateTestString()
``` 
and post here `str` text.

**Comment by giuliohome** [comment]
```
//---------------------------------------------------------------------------------------------------
// This code was generated by LinqToDB.
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using LinqToDB;

using NUnit.Framework;

namespace Import2TSS
{
	[FileHelpers.DelimitedRecordAttribute(",")]
	[FileHelpers.IgnoreFirstAttribute()]
	[LinqToDB.Mapping.TableAttribute(Name = "EndurNominationValid", Schema = "OilPhysical")]
	public class NominationValid
	{
	}
}

namespace Import2TSS
{
	[FileHelpers.DelimitedRecordAttribute(",")]
	[FileHelpers.IgnoreFirstAttribute()]
	[LinqToDB.Mapping.TableAttribute(Name = "EndurTradeValid", Schema = "OilPhysical")]
	public class TradeValid
	{
	}
}

namespace Tests.UserTests
{
	[TestFixture]
	public class UserTest : TestBase
	{
		[Test, DataContextSource]
		public void Test(string context)
		{
			// System.Linq.Enumerable+WhereSelectEnumerableIterator`2[Microsoft.FSharp.Linq.RuntimeHelpers.AnonymousObject`3[Import2TSS.TradeValid,Import2TSS.NominationValid,Import2TSS.NominationValid],System.Tuple`3[Import2TSS.TradeValid,Import2TSS.NominationValid,Import2TSS.NominationValid]]
			using (var db = GetDataContext(context))
			{
				var quey = System.Linq.Enumerable+WhereSelectEnumerableIterator`2[Microsoft.FSharp.Linq.RuntimeHelpers.AnonymousObject`3[Import2TSS.TradeValid,Import2TSS.NominationValid,Import2TSS.NominationValid],System.Tuple`3[Import2TSS.TradeValid,Import2TSS.NominationValid,Import2TSS.NominationValid]];
			}
		}
	}
}

```

**Comment by sdanyliv** [comment]
Strange i can not see `IQueryable` expression. Something wrong here.
Set `Configuration.Linq.GenerateExpressionTest = true` and run problematic query. Test will be generated in `%Temp%\linq2db` folder.

**Comment by giuliohome** [comment]
I set 

```fsharp
Configuration.Linq.GenerateExpressionTest <- true
```
and now I have ExpressionTest.0.cs
```csharp
//---------------------------------------------------------------------------------------------------
// This code was generated by LinqToDB.
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using LinqToDB;

using NUnit.Framework;

namespace T1
{
	[FileHelpers.DelimitedRecordAttribute(",")]
	[FileHelpers.IgnoreFirstAttribute()]
	[LinqToDB.Mapping.TableAttribute(Name = "EndurNominationValid", Schema = "OilPhysical")]
	public class T0
	{
	}
}

namespace T1
{
	[FileHelpers.DelimitedRecordAttribute(",")]
	[FileHelpers.IgnoreFirstAttribute()]
	[LinqToDB.Mapping.TableAttribute(Name = "EndurTradeValid", Schema = "OilPhysical")]
	public class T2
	{
	}
}

namespace Tests.UserTests
{
	[TestFixture]
	public class UserTest : TestBase
	{
		[Test, DataContextSource]
		public void Test(string context)
		{
			// Table([OilPhysical].[EndurT2]).SelectMany(p3 => ServerModel.P4.GetTable().LeftJoin(QuotationToLambdaExpression(SubstHelper(NewDelegate (Func`2, y,
             IfThenElse (IfThenElse (Call (None, op_Equality,
                                           [FieldGet (Some (y),
                                                      ReceiptDealNumber),
                                            FieldGet (Some (p3), DealNumber)]),
                                     Call (None, op_Equality,
                                           [FieldGet (Some (y),
                                                      ReceiptParcelGroup),
                                            FieldGet (Some (p3),
                                                      ParcelGroupID)]),
                                     Value (false)),
                         Call (None, op_Equality,
                               [FieldGet (Some (y), ReceiptParcelID),
                                FieldGet (Some (p3), ParcelID)]),
                         Value (false))), new [] {p3}, new [] {Convert(p3)}))), (p3, p5) => new AnonymousObject`2(Item1 = p3, Item2 = p5))
			using (var db = GetDataContext(context))
			{
				var quey = db.GetTable<T1.T2>()
					.SelectMany(
						p3 => .P4.GetTable<T1.T0>()
							.LeftJoin(
								Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.QuotationToLambdaExpression<Func<T1.T0,bool>>(
									Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.SubstHelper<Func<T1.T0,bool>>(
										NewDelegate (Func`2, y,
             IfThenElse (IfThenElse (Call (None, op_Equality,
                                           [FieldGet (Some (y),
                                                      ReceiptDealNumber),
                                            FieldGet (Some (_arg1), DealNumber)]),
                                     Call (None, op_Equality,
                                           [FieldGet (Some (y),
                                                      ReceiptParcelGroup),
                                            FieldGet (Some (_arg1),
                                                      ParcelGroupID)]),
                                     Value (false)),
                         Call (None, op_Equality,
                               [FieldGet (Some (y), ReceiptParcelID),
                                FieldGet (Some (_arg1), ParcelID)]),
                         Value (false))),
										new Microsoft.FSharp.Quotations.FSharpVar[] { _arg1 },
										new [] { ()p3 }))),
						(p3, p5) => new Microsoft.FSharp.Linq.RuntimeHelpers.AnonymousObject<T1.T2,T1.T0>(p3, p5));
			}
		}
	}
}
```

**Comment by giuliohome** [comment]
FYI 
In the meantime I've discovered that there is the `(!!)` operator and it is working even if it seems slow.
There I have a unique query with 2 left joins (and no reflection for autogenerating my web columns).
The reference to the #6552 dotnet fsharp issue was useful also for this.
```f#
let tradesQuery = 
    query {
        for t in context.OilPhysical.EndurTradeValid do  
        join n_del in (!!) context.OilPhysical.EndurNominationValid on
                 ((t.DealNumber,t.ParcelGroupId,t.ParcelId) 
                 = (n_del.DeliveryDealNumber,n_del.DeliveryParcelGroup,n_del.DeliveryParcelId))
        join n_rec in (!!) context.OilPhysical.EndurNominationValid on
                 ((t.DealNumber,t.ParcelGroupId,t.ParcelId) 
                 = (n_rec.ReceiptDealNumber,n_rec.ReceiptParcelGroup,n_rec.ReceiptParcelId))
        select (t,n_del, n_rec)  
        }

let trades = 
    tradesQuery |> Seq.take(90) |> Seq.toArray 
    |> Array.map(fun (t,n_del,n_rec) -> (t.ColumnValues |> Seq.append n_del.ColumnValues |> Seq.append n_rec.ColumnValues))


```

**Comment by jannesiera** [comment]
We are running into the same issues. Initially, we were quite excited about using linq2db in our F# project but this is a blocker for us, as we frequently have to perform multiple left joins. Is there a current workaround or possible solution?

**Comment by MaceWindu** [comment]
There are several issues in this area with their own workarounds.

In general I would recomment:
- not use `linq` syntax but call Linq methods explicitly, as F# generates incompatible expression tree in many cases
- another issue we discovered recently (#3699) is that anonymous classes should assign properties in alphabetical order or F# will generate a lot of nested lambdas to preserve execution order

**Comment by dsyme** [comment]
It would make sense to document/link known significant  issues with F# queries in practice on the docs page

https://docs.microsoft.com/en-us/dotnet/fsharp/language-reference/query-expressions

Do you think you could take a moment to link the issues in a new "Known issues" section at the bottom of that page? In the issue list, mention that the issues may have been addressed by the time the reader reads them :)

We could also add a lint/warning for anon records init order in the compiler

**Comment by jannesiera** [comment]
@MaceWindu thank you for the quick response. When you say `linq` syntax, do you mean query expression syntax?

We have a case where (1) we are using the standard linq methods (no query syntax) and (2) the fields in the anonymous records are alphabetical.

![image](https://user-images.githubusercontent.com/370746/186879668-3246f852-4070-44a5-9e20-a53d4880d706.png)

We are getting the following error:

![image](https://user-images.githubusercontent.com/370746/186879806-e32fe2d9-173f-44f9-a8e3-fc6e9a104523.png)

Stack trace:

>    at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToExtensionSql(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor)
   at LinqToDB.EntityFrameworkCore.Internal.EFCoreExpressionAttribute.<>c__1`1.<GetExpression>b__1_1(ValueTuple`4 ctx, String v, String d)
   at LinqToDB.Sql.ExpressionAttribute.<>c__DisplayClass68_0`1.<ResolveExpressionValues>b__0(Match match)
   at System.Text.RegularExpressions.Regex.<>c.<Replace>b__84_0(ValueTuple`5& state, Match match)
   at System.Text.RegularExpressions.RegexRunner.Scan[TState](Regex regex, String text, Int32 textstart, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run[TState](String input, Int32 startat, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject)
   at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at LinqToDB.Sql.ExpressionAttribute.ResolveExpressionValues[TContext](TContext context, String expression, Func`4 valueProvider)
   at LinqToDB.EntityFrameworkCore.Internal.EFCoreExpressionAttribute.GetExpression[TContext](TContext context, IDataContext dataContext, SelectQuery query, Expression expression, Func`4 converter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToExtensionSql(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor)
   at LinqToDB.EntityFrameworkCore.Internal.EFCoreExpressionAttribute.<>c__1`1.<GetExpression>b__1_1(ValueTuple`4 ctx, String v, String d)
   at LinqToDB.Sql.ExpressionAttribute.<>c__DisplayClass68_0`1.<ResolveExpressionValues>b__0(Match match)
   at System.Text.RegularExpressions.Regex.<>c.<Replace>b__84_0(ValueTuple`5& state, Match match)
   at System.Text.RegularExpressions.RegexRunner.Scan[TState](Regex regex, String text, Int32 textstart, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run[TState](String input, Int32 startat, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject)
   at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at LinqToDB.Sql.ExpressionAttribute.ResolveExpressionValues[TContext](TContext context, String expression, Func`4 valueProvider)
   at LinqToDB.EntityFrameworkCore.Internal.EFCoreExpressionAttribute.GetExpression[TContext](TContext context, IDataContext dataContext, SelectQuery query, Expression expression, Func`4 converter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.SuggestColumnDescriptor(IBuildContext context, Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.AllJoinsLinqBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.get_SqlText()
   at Database.RepositoryExtra.getAdiLinqQuery(AdiId id) in C:\Work\Clients\Asbest Consulting\asbest-consulting\app\serverTests\RepositoryExtra.fs:line 51
   at Program.serverTests@21-1.Invoke(Unit unitVar) in C:\Work\Clients\Asbest Consulting\asbest-consulting\app\serverTests\Program.fs:line 21
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
   
Note that we are using linq2db together with EF Core (https://github.com/linq2db/linq2db.EntityFrameworkCore).

**Comment by MaceWindu** [comment]
This actually doesn't look like F#-specific issue, more like issue in linq2db or in linq2db.EntityFrameworkCore...

**Comment by MaceWindu** [comment]
@jannesiera , I've created separate issue for this error. Could you add mappings/sample code to it?
