### ISSUE TITLE
Implicit join fails: NullReferenceException

### ISSUE THREAD

**Issue by viceroypenguin** [linq2db/linq2db#1832]
Exception Details:
```
Exception message: NullReferenceException
Stack trace:

   at LinqToDB.Linq.Query.GetIQueryable(Int32 n, Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertIQueryable(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpressionImpl(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpression(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(MethodCallExpression method)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpressionImpl(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpression(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertSingleOrFirst(Expression expr, MethodCallExpression call)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpressionImpl(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpression(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressionTree(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder..ctor(Query query, IDataContext dataContext, Expression expression, ParameterExpression[] compiledParameters)
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Single[TSource](IQueryable`1 source)
   at Tests.UserTests.UserTest.Main() in C:\Users\jturnerx091995\Source\Repos\ConsoleApp1\tmp.cs:line 64
--

```

### Steps to reproduce
Code to reproduce.

```c#
//---------------------------------------------------------------------------------------------------
// This code was generated by LinqToDB.
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using LinqToDB;

using NUnit.Framework;

namespace Database
{
    public class DbContext : LinqToDB.Data.DataConnection, ICloneable, LinqToDB.IDataContext, LinqToDB.IEntityServices, IDisposable
    {
        public DbContext(string connectionString)
            : base(connectionString)
        { }

        public LinqToDB.ITable<Models.Equipment> Equipment { get; set; }
    }
}

namespace Database.Models
{
    [LinqToDB.Mapping.TableAttribute(Name = "Equipment", Schema = "dbo")]
    public class Equipment
    {
        [LinqToDB.Mapping.PrimaryKeyAttribute()]
        [LinqToDB.Mapping.NotNullAttribute()]
        public Guid EquipmentId { get; set; }

        [LinqToDB.Mapping.ColumnAttribute()]
        [LinqToDB.Mapping.NotNullAttribute()]
        public string Name { get; set; }

        [LinqToDB.Mapping.ColumnAttribute()]
        [LinqToDB.Mapping.NotNullAttribute()]
        public Int16 EquipmentTypeId { get; set; }

        [LinqToDB.Mapping.AssociationAttribute(ThisKey = "EquipmentId", OtherKey = "ToolChamberId", CanBeNull = true, IsBackReference = true, Relationship = 0)]
        public ToolChamber ToolChamber { get; set; }
    }
}

namespace Database.Models
{
    [LinqToDB.Mapping.TableAttribute(Schema = "dbo", Name = "ToolChamber")]
    public class ToolChamber
    {
        [LinqToDB.Mapping.ColumnAttribute()]
        [LinqToDB.Mapping.NotNullAttribute()]
        public Guid ToolId { get; set; }
    }
}

namespace Tests.UserTests
{
    [TestFixture]
    public class UserTest : TestBase
    {
        [Test, DataContextSource]
        public void Test(string context)
        {
            // Table([dbo].[Equipment]).Where(e => (e.EquipmentId == value(UserQuery+<>c__DisplayClass0_1).equipmentId)).Select(e => new <>f__AnonymousType0`2(EquipmentId = e.EquipmentId, FullName = IIF((Convert(e.EquipmentTypeId) == 2), ((value(UserQuery+<>c__DisplayClass0_0).context.Equipment.FirstOrDefault(t => (t.EquipmentId == e.ToolChamber.ToolId)).Name + " ") + e.Name), e.Name)))
            using (var db = GetDataContext(context))
            {
                var equipmentId = new Guid();
                var quey = db.GetTable<Database.Models.Equipment>()
                  .Where(
                    e => (e.EquipmentId == equipmentId))
                  .Select(
                    e => new
                    {
                        EquipmentId = e.EquipmentId,
                        FullName = (((int)e.EquipmentTypeId == 2) ? 
                            ((db.Equipment.FirstOrDefault(t => (t.EquipmentId == e.ToolChamber.ToolId)).Name + " ") + e.Name) : e.Name)
                    })
                  .Single();
            }
        }
    }
}
```

### Environment details
linq2db version: 2.8.1
Database Server: N/A (fails before connecting to server)
Database Provider: SqlProvider
Operating system: Windows
.NET Framework: .NET Core 2.2

**Comment by sdanyliv** [comment]
@viceroypenguin, thanks for reporting, will check.

**Comment by sdanyliv** [comment]
Unfortunately I can not reproduce. One mistake that I have found - association is not properly defined. `ToolChamberId` is not a property of `ToolChamber` class.
```cs
[LinqToDB.Mapping.AssociationAttribute(ThisKey = "EquipmentId", OtherKey = "ToolChamberId", CanBeNull = true, IsBackReference = true, Relationship = 0)]
public ToolChamber ToolChamber { get; set; }
```

**Comment by viceroypenguin** [comment]
@sdanyliv :

Editing the code slightly, to run as a .NET Core 2.2 console app (this is how I verified the above code after copying from `.GenerateTestString()`):
```c#
//---------------------------------------------------------------------------------------------------
// This code was generated by LinqToDB.
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using LinqToDB;

namespace Database
{
    public class DbContext : LinqToDB.Data.DataConnection, ICloneable, LinqToDB.IDataContext, LinqToDB.IEntityServices, IDisposable
    {
        public DbContext(string connectionString)
            : base(ProviderName.SqlServer2014, connectionString)
        { }

        public LinqToDB.ITable<Models.Equipment> Equipment { get; set; }
    }
}

namespace Database.Models
{
    [LinqToDB.Mapping.TableAttribute(Name = "Equipment", Schema = "dbo")]
    public class Equipment
    {
        [LinqToDB.Mapping.PrimaryKeyAttribute()]
        [LinqToDB.Mapping.NotNullAttribute()]
        public Guid EquipmentId { get; set; }

        [LinqToDB.Mapping.ColumnAttribute()]
        [LinqToDB.Mapping.NotNullAttribute()]
        public string Name { get; set; }

        [LinqToDB.Mapping.ColumnAttribute()]
        [LinqToDB.Mapping.NotNullAttribute()]
        public Int16 EquipmentTypeId { get; set; }

        [LinqToDB.Mapping.AssociationAttribute(ThisKey = "EquipmentId", OtherKey = "ToolChamberId", CanBeNull = true, IsBackReference = true, Relationship = 0)]
        public ToolChamber ToolChamber { get; set; }
    }
}

namespace Database.Models
{
    [LinqToDB.Mapping.TableAttribute(Schema = "dbo", Name = "ToolChamber")]
    public class ToolChamber
    {
        [LinqToDB.Mapping.ColumnAttribute()]
        [LinqToDB.Mapping.NotNullAttribute()]
        public Guid ToolId { get; set; }
    }
}

namespace Tests.UserTests
{
    public class UserTest 
    {
        public static void Main()
        {
            // Table([dbo].[Equipment]).Where(e => (e.EquipmentId == value(UserQuery+<>c__DisplayClass0_1).equipmentId)).Select(e => new <>f__AnonymousType0`2(EquipmentId = e.EquipmentId, FullName = IIF((Convert(e.EquipmentTypeId) == 2), ((value(UserQuery+<>c__DisplayClass0_0).context.Equipment.FirstOrDefault(t => (t.EquipmentId == e.ToolChamber.ToolId)).Name + " ") + e.Name), e.Name)))
            using (var db = new Database.DbContext("Server=sc-dev-140;Database=UberApplicationDevelopment;Trusted_Connection=True;App=Tempo.Web;MultipleActiveResultSets=True;"))
            {
                var equipmentId = new Guid();
                var quey = db.GetTable<Database.Models.Equipment>()
                  .Where(
                    e => (e.EquipmentId == equipmentId))
                  .Select(
                    e => new
                    {
                        EquipmentId = e.EquipmentId,
                        FullName = (((int)e.EquipmentTypeId == 2) ? 
                            ((db.Equipment.FirstOrDefault(t => (t.EquipmentId == e.ToolChamber.ToolId)).Name + " ") + e.Name) : e.Name)
                    })
                  .Single();
            }
        }
    }
}
```

**Comment by viceroypenguin** [comment]
Also, I checked adding the `ToolChamberId`, and it had no effect.

However, adding a reference to `ToolChamber` before using it in the lambda will fix L2DB internal state enough to let the query run. This could be in a `.Where()` clause or as a previous property in the object initializer (i.e. `.Select(e => new { ToolId = e.ToolChamber.ToolId, FullName = ..., })` will bypass the problem).

**Comment by sdanyliv** [comment]
Test generator is not a perfect tool and needs manual fixing.
`Equipment` property is `null`.
Correct property:
```cs
   public class DbContext : LinqToDB.Data.DataConnection, ICloneable, LinqToDB.IDataContext, LinqToDB.IEntityServices, IDisposable
    {
        public DbContext(string connectionString)
            : base(ProviderName.SqlServer2014, connectionString)
        { }

        public LinqToDB.ITable<Models.Equipment> Equipment => GetTable<Models.Equipment>();
    }
```

**Comment by viceroypenguin** [comment]
Ah, you are correct. The original bug was in 2.7, so I created this app off the test string to minimize and validate, and tested against 2.8.1 and got the NRE, which is what I reported. Using the above, it looks like 2.8 or 2.8.1 fixed the bug I encountered originally. Thanks!

**Comment by sdanyliv** [comment]
@viceroypenguin, good to hear that problem was fixed ;)
