### ISSUE TITLE
add default value to CTE

### ISSUE THREAD

**Issue by tobi77777** [linq2db/linq2db#1845]
Hi,

is there some possibilty to union custom objects to a CTE with LinqToDb?
I've the following code for example:

```cs
var someCte = someCteTmp.Select(o => new CustomObject
    {
        Value1 = o.Value1,
        Value2 = o.Value2,
    }).AsCte();

IQueryable<CustomObject> defaultValue = new List<CustomObject> 
    { 
        new CustomObject 
        { 
            Value1 = defaultValue1, 
            Value2 = defaultValue2, 
        }, 
    }.AsQueryable();

someCte = someCte.Union(defaultValue).AsCte();
```

But this leads to the following error:
Message: System.InvalidOperationException : Sequence contains no matching element

The expected SQL would be like the following for Oracle for example:

```sql
WITH CTE_1
(
	Value1, 
	Value2
)
AS
(
	SELECT
        	c_1.Value1,
        	c_1.Value2
	FROM
		cteTable c_1
	WHERE
		c_1.Value1 = 'Value'
),
CTE_2
(
	Value1, 
	Value2
)
AS
(
	SELECT
		'Value1' as Value1,
		'Value2' as Value2
	FROM
		dual
),
CTE_3
(
	Value1, 
	Value2
)
AS
(
	SELECT
        	Value1, 
        	Value2
	FROM
		CTE_1
    	UNION
	SELECT
        	Value1, 
        	Value2
	FROM
		CTE_2
)
```

```
StackTrace:	
at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at LinqToDB.Linq.Builder.ConcatUnionBuilder.UnionContext.Init() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ConcatUnionBuilder.cs:line 173
   at LinqToDB.Linq.Builder.ConcatUnionBuilder.UnionContext..ctor(SubQueryContext sequence1, SubQueryContext sequence2, MethodCallExpression methodCall) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ConcatUnionBuilder.cs:line 66
   at LinqToDB.Linq.Builder.ConcatUnionBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ConcatUnionBuilder.cs:line 31
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 177
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 148
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 268
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 232
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 84
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 180
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

Ergebnis Meldung:	System.InvalidOperationException : Sequence contains no matching element

**Comment by MaceWindu** [comment]
Conversion of enumerable data to SQL is not something we support right now (except scalar arrays), but we have such functionality implemented for 3.0.
I will add this issue to 3.0 milestone.

**Comment by MaceWindu** [comment]
As workaround you can try to replace it with real subquery like:
```cs
db.GetTable<Dual>().Select(_ => new { Value1 = value1Var, Value2 = value2Var })
```

**Comment by MaceWindu** [comment]
Also if it will not work, you can create subquery using `FromSql` API

**Comment by tobi77777** [comment]
Thank your for your fast answers.
Ok, I'll try to use the FromSql API

**Comment by tobi77777** [comment]
Hi MaceWindu,

thank you for the fast answer.
I've tried the FromSql-API but I get the same error.

The subquery tip is a good one. Its working fine for oracle but I have to support also SQLite and there is not such a Table like dual. Is it possible to select from "no table"?

**Comment by MaceWindu** [comment]
This is area, where each database behaves differently. Some support selects without from like SQL Server or SQLite, some need some table with exactly one row like Oracle with Dual.

We have db.Select() method to perform such queries, but it cannot be used as subquery.

I would say FromSql should be your option here, but if you are saying it doesn't work - probably you need to wait for fix. We plan another release this week, so maybe we can fix it here.

**Comment by sdanyliv** [comment]
@tobi77777, i have tested and `FromSql` works. 
```cs
[Table]
class SampleCteTemp
{
	[Column(Length = 50)] public string Value1 { get; set; }
	[Column(Length = 50)] public string Value2 { get; set; }
}

[Table]
class CustomObject
{
	[Column(Length = 50)] public string Value1 { get; set; }
	[Column(Length = 50)] public string Value2 { get; set; }
}

private static IQueryable<CustomObject> GenerateDefaultResultSet(DataConnection dc, string value1Var, string value2Var)
{
	var providerName = dc.DataProvider.Name;
	switch (providerName)
	{
		default:
			return dc.FromSql<CustomObject>($"SELECT {value1Var}, {value2Var} FROM Dual");
	}
}

[Test]
public void SampleSelectTest([DataSources(false)] string context)
{
	using (var db = (DataConnection)GetDataContext(context))
	using (var table = db.CreateLocalTable<CustomObject>())
	{
		var value1Var = "V1";
		var value2Var = "V2";

		var someCteTmp = db.GetTable<CustomObject>().Where(v => v.Value1 == "Value1").AsCte();
		var someCte = someCteTmp.Select(o => new CustomObject
		{
			Value1 = o.Value1,
			Value2 = o.Value2,
		}).AsCte();

		someCte = someCte.Union(GenerateDefaultResultSet(db, value1Var, value2Var)).AsCte();

		var sql = someCte.ToString();
		Console.WriteLine(sql);
	}
}
```
```sql
WITH [CTE_1] ([Value1], [Value2])
AS
(
	SELECT
		[v].[Value1],
		[v].[Value2]
	FROM
		[CustomObject] [v]
	WHERE
		[v].[Value1] = N'Value1'
),
[CTE_2] ([Value1], [Value2])
AS
(
	SELECT
		[o].[Value1],
		[o].[Value2]
	FROM
		[CTE_1] [o]
),
[CTE_3] ([Value1], [Value2])
AS
(
	SELECT
		[t1].[Value1],
		[t1].[Value2]
	FROM
		[CTE_2] [t1]
	UNION
	SELECT
		[t2].[Value1],
		[t2].[Value2]
	FROM
		(
			SELECT N'V1', N'V2' FROM Dual
		) [t2]
)
SELECT
	[t3].[Value1],
	[t3].[Value2]
FROM
	[CTE_3] [t3]
```
It is working workaround, but you right now can handle different providers by extending `GenerateDefaultResultSet` function.

**Comment by tobi77777** [comment]
Thank you for the sample code.

Yeah, this is working.
I made some stupid mistake, the "CustomObject" was had the internal access modifier because I'm using it only for the CTE. Thats also the reason for the Exception posted above. Now SQL is generated from the first approach with the expectation that "CustomObject" exists as table.

**Comment by MaceWindu** [comment]
Check this pr #1847 (planned for release tomorrow)

**Comment by MaceWindu** [comment]
As already mentioned, original code is not correct, but with minor change from:
```cs
IQueryable<CustomObject> defaultValue = new List<CustomObject> 
    { 
        new CustomObject 
        { 
            Value1 = defaultValue1, 
            Value2 = defaultValue2, 
        }, 
    }.AsQueryable();
```
to
```cs
var defaultValue = new List<CustomObject> 
    { 
        new CustomObject 
        { 
            Value1 = defaultValue1, 
            Value2 = defaultValue2, 
        }, 
    };
```

it will work starting from version 3.4.5
