### ISSUE TITLE
Too many connections after changing from default constructor to connection factory based constructor

### ISSUE THREAD

**Issue by tauqirghani** [linq2db/linq2db#1853]
There is little literature on the use of this constructor so just want your comments and if this is a known issue.

I have inserted a connection factory based LinqToDB service in the .Net Core Startup.cs 
```
services.AddScoped<IDatabase, Database>( provider =>
                {
                    IConfigurationSection sqlConfig = Configuration.GetSection("Database");
                    IDataProvider dataProvider = new SqlServerDataProvider("SqlServer", SqlServerVersion.v2008);

                    return new Database(dataProvider,
                        new WorkspaceConnectionFactory(
                        sqlConfig["clientId"],
                        sqlConfig["clientSecret"],
                        sqlConfig["authority"],
                        sqlConfig["target"],
                        sqlConfig["connectionString"]).createConnection());
                });

```
with this implementation of factory
```
namespace Workspace.Common.LinqToDB
{
    public class WorkspaceConnectionFactory
    {
        private ClientCredential ClientCredential;
        private string Authority;
        private string Target;
        private string ConnectionString;
       
        public WorkspaceConnectionFactory(string clientId, string clientSecret, string authority, string target, string connectionString)
        {
            ClientCredential = new ClientCredential(clientId, clientSecret);
            Authority = authority;
            Target = target;
            ConnectionString = connectionString;
        }
        public IDbConnection createConnection()
        {
            AuthenticationContext authenticationContext = new AuthenticationContext(Authority);
            AuthenticationResult authenticationResult = authenticationContext.AcquireTokenAsync(Target, ClientCredential).Result;
            SqlConnection WorkspaceDataConnection = new SqlConnection(ConnectionString);
            WorkspaceDataConnection.AccessToken = authenticationResult.AccessToken;

            return WorkspaceDataConnection;
        }
    }
}

```

After successful connection and few querries, I get the following exception:
 
```
System.Data.SqlClient.SqlException (0x80131904): Resource ID : 1. The request limit for the database is 90 and has been reached. See 'http://go.microsoft.com/fwlink/?LinkId=267637' for assistance.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 1227
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 320
   at LinqToDB.Linq.Builder.TableBuilder.AssociatedTableContext.SubQueryHelper`1.ExecuteSubQuery(IQueryRunner queryRunner, Object parentObject, Func`3 queryReader)+MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\TableBuilder.AssociatedTableContext.cs:line 460
   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at lambda_method(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 56
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext() in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 324
   at System.Linq.Enumerable.WhereEnumerableIterator`1.MoveNext()
   at System.Linq.Enumerable.UnionIterator`1.MoveNext()
   at System.Linq.Enumerable.SelectEnumerableIterator`2.MoveNext()
   at System.Linq.Set`1.UnionWith(IEnumerable`1 other)
   at System.Linq.Enumerable.DistinctIterator`1.FillSet()
   at System.Linq.Enumerable.DistinctIterator`1.ToArray()
   
   .........................
   at Microsoft.AspNetCore.Mvc.Internal.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeActionMethodAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeNextActionFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeNextResourceFilter()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeFilterPipelineAsync()
   at Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.InvokeAsync()
   at Microsoft.AspNetCore.Builder.RouterMiddleware.Invoke(HttpContext httpContext)
   at Workspace.API.Middlewares.AddUserHeadersMiddleware.InvokeAsync(HttpContext context, IWorkspaceRepository workspaceRepository) in C:\TFS\AT_NCSWorkspace\WorkSpaceAPI\src\API\Middlewares\AddUserHeadersMiddleware.cs:line 47
   at Workspace.API.Middlewares.ErrorLoggingMiddleware.InvokeAsync(HttpContext context) in C:\TFS\AT_NCSWorkspace\WorkSpaceAPI\src\API\Middlewares\ErrorLoggingMiddleware.cs:line 31
ClientConnectionId:3c0ec020-5be1-4bda-adc1-205038682b08```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
<code with error and mapping classes>
```

### Environment details
linq2db version: 2.6.4 with System.Data.SqlClient 4.6.1 and 
Database Server: Azure SqlServer
Database Provider: SqlServer
Operating system: Windows
.NET Framework: .net CORE 2.2

**Comment by to11mtm** [comment]
Is the error coming from a query in `AddUserHeadersMiddleware`? (that's what it looks like, but I'm not sure because the stack trace might be trimmed)

How is `Database` being injected into your class?

Is it 

```
public AddUserHeadersMiddleware(Database someDatabase)
```

or are you trying to do something like

```
//in some method:
var database = services.GetRequiredService<Database>();
```

If you try to do something like the second example I provided, you may leak connections unless you properly wrap the code in question in a scope. Also note that scope would be 'different' from your main scope. [This is a helpful read that may explain better.](https://andrewlock.net/the-dangers-and-gotchas-of-using-scoped-services-when-configuring-options-in-asp-net-core/)

**Comment by MaceWindu** [comment]
There is nothing special in using connection factory compared to other constructors, so if you have abandoned connections it only means that `Database` instance is not being disposed after use. I'm not familiar with .net core DI, so you should look into @to11mtm answer.

**Comment by tauqirghani** [comment]
I have gone through @to11mtm suggested article. My reading reveals that it is more about how to handle configurations.
The clarity I need is whether LinqToDB default connection constructor Database() under the hood creates the same SqlClient connection that I am creating explicitly in the factory. Because if it does the same thing then I can confidently replace the default constructor with 
Database(IDataProvider, Func<IDbConnection>) constructor.
and Thanks guys for your comments

**Comment by MaceWindu** [comment]
Yes, passing factory basically just replaces method we call to create connection from
`DataProvider.CreateConnection()` to `factory()`. Handling of created connection is not affected wether it came from our default factory or custom one.

**Comment by tauqirghani** [comment]
If you can just answer one question for me before closing this issue. In this factory method I am attaching an AccessToken that has a limited life. There was no such time bound token in the original token. I have tested the factory based connection for hours and it continues to work beyond the Access_Token expiry time. How does that happen, which component  replaces the token. There is no refresh token in SQL Service Provider Access Token. Does LinqToDB acquires a new connection on expiry of ToKen?

**Comment by MaceWindu** [comment]
We don't manage tokens at all on our side, so probably you have sliding expiration enabled for your token.

**Comment by MaceWindu** [comment]
BTW, why do you use factory for it? We have added events especially for this case some time ago: https://github.com/linq2db/linq2db/pull/1607

**Comment by MaceWindu** [comment]
Will add it to FAQ

**Comment by MaceWindu** [comment]
added to FAQ, will be up soon on site
