### ISSUE TITLE
Potential threading issues with .Query<T>

### ISSUE THREAD

**Issue by ronnyek** [linq2db/linq2db#1874]
I'm running into a scenario where I've got calls into a class that handles some data, and noticed that occasionally I get Object reference not set to an instance of an object, or that the command has been disposed.

Upon googling, I found an old issue here (that I can't seem to find now) that states that DataConnection is not thread safe, that a new DataConnection should be created from each thread.

My concern is I'm not always sure the origin in the calls to that data class. An example could be someone spawning a new task, then calling that pre-existing instance, or trying to query data from a timer callback.

I'm just trying to find any decent way of guard other users against running into this sort of thing.

Being that I don't know enough about linq2db's internals to know why it's not thread safe, is it something that could feasibly be added?

I feel like at this point my only option to handle this (to ensure dataconnection per thread) would be to blindly create new dataconnections each and every call/attempt to do anything in my data class.

```
Exception message:
Stack trace:

System.ObjectDisposedException
Cannot access a disposed object.
Object name: 'OracleCommand'.
   at Oracle.ManagedDataAccess.Client.OracleCommand.ValidateStatePriorToExecution()
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.CommandInfo.Query[T]()
```
and 
``` cs
System.NullReferenceException
Object reference not set to an instance of an object.
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteReader(Boolean requery, Boolean fillRequest, CommandBehavior behavior)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.CommandInfo.Query[T]()
```
### Steps to reproduce
```c#
public void Main(){
   var db = new Db();
   var timer = new System.Timers.Timer();
   timer.Interval = 1000;
   timer.Elapsed += () => {
      db.Get<T>(...);
   };
   timer.Start();

   for(var i = 0; i< 100;i++){
      db.Get<T>(...);
   }

   
}
```

create a DataConnection, and  timer, and loop querying from both. Eventually you'll run into one of these exceptions.

### Environment details
linq2db version: 2.7.4 (not sure this matters)
Database Server: *?*
Database Provider: *?*
Operating system: *?*
.NET Framework: *?*

**Comment by to11mtm** [comment]
I would posit that it's not thread safe because that is a fairly common paradigm in many data access providers.

As a consideration; let's say `DataConnection` was threadsafe. What would that mean when it comes to things like Transactions? How would that API work? (It's certainly DOABLE, but it would look very different and perhaps not clean as one would think at first glance.)

> I feel like at this point my only option to handle this (to ensure dataconnection per thread) would be to blindly create new dataconnections each and every call/attempt to do anything in my data class.

That's a pretty standard pattern in ADO.NET.

```
        protected ITable<SqlCommonDbOddJobMetaData> QueueTable(DataConnection conn)
        {
            return conn.GetTable<SqlCommonDbOddJobMetaData>().TableName(_jobQueueTableConfiguration.QueueTableName);
        }
        public virtual void MarkJobSuccess(Guid jobGuid)
        {
            using (var conn = _jobQueueConnectionFactory.CreateDataConnection())
            {
                
                QueueTable(conn)
                    .Where(q => q.JobGuid == jobGuid)
                    .Set(q => q.Status, JobStates.Processed)
                    .Set(q => q.LockClaimTime, (DateTime?) null)
                    .Update();
            }
        }
```

**Comment by sdanyliv** [comment]
@ronnyek, how to handle this in async functions, which do not belong to particular thread?
DataConnection is a lightweight class, create and dispose it every time when you need to run query. It is also good for pooling.

**Comment by ronnyek** [comment]
Ok, I think this will require some changes on my side, but definitely not impossible

**Comment by sdanyliv** [comment]
Closing issue as answered.

**Comment by filippobottega** [comment]
Hi!
I have had the same issue using Parallel.ForEach over a set of batch data sent to a DB with the Merge API. The exception stack trace was:
```
System.NullReferenceException
  HResult=0x80004003
  Messaggio=Object reference not set to an instance of an object.
  Origine=Oracle.ManagedDataAccess
  Analisi dello stack:
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at LinqToDB.Data.DbCommandProcessor.DbCommandProcessorExtensions.ExecuteNonQueryExt(IDbCommand cmd)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass34_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at LinqToDB.LinqExtensions.Merge[TTarget,TSource](IMergeable`2 merge)

```
To solve the issue I have created a new DataConnection inside the ForEach code block.
Thank you to help me to find the right direction.

**Comment by sdanyliv** [comment]
>To solve the issue I have created a new DataConnection inside the ForEach code block.
Thank you to help me to find the right direction.

You SHOULD create data connection for each thread. `DataConnection` is not thread safe. 

@MaceWindu, i think guard for such improper usage is needed.
Maybe in `DataProvider.ExecuteScope()`.
