### ISSUE TITLE
SQL Sever 2017 broke SchemaOnly

### ISSUE THREAD

**Issue by Bobsson** [linq2db/linq2db#1921]
According to [this bug report](https://feedback.azure.com/forums/908035-sql-server/suggestions/34699126-sql-2017-set-fmtonly-on-doesn-t-return-any-resu), SQL Server 2017+ broke the `SET FMTONLY ON` command.  Unfortunately, .NET uses that command to power the `CommandBehavior.SchemaOnly` value ([Framework 4.8](https://docs.microsoft.com/en-us/dotnet/api/system.data.commandbehavior?view=netframework-4.8#fields) [Core 3.0](https://docs.microsoft.com/en-us/dotnet/api/system.data.commandbehavior?view=netcore-3.0#fields)) that gets passed to `ExecuteReader()`.

At the very least, this affects auto-generating classes with the T4 templates.  I'm not sure if it has any further repercussions.  Please switch the SQL Server integration from `SchemaOnly` to something else (`KeyInfo`?).

```
Running transformation: System.NullReferenceException: Object reference not set to an instance of an object.
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.<>c__DisplayClass38_13.<GenerateTypesFromMetadata>b__83() in C:\Code\LinqToDBTest\LinqToDB.Templates\LinqToDB.ttinclude:line 736
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.MemberBase.BuildType() in C:\Code\LinqToDBTest\LinqToDB.Templates\T4Model.ttinclude:line 421
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.<GetAllClassMembers>d__41.MoveNext() in C:\Code\LinqToDBTest\LinqToDB.Templates\LinqToDB.ttinclude:line 1038
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.<GetAllClassMembers>d__41.MoveNext() in C:\Code\LinqToDBTest\LinqToDB.Templates\LinqToDB.ttinclude:line 1035
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.<GetAllClassMembers>d__41.MoveNext() in C:\Code\LinqToDBTest\LinqToDB.Templates\LinqToDB.ttinclude:line 1035
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToLookup[TSource,TKey](IEnumerable`1 source, Func`2 keySelector, IEqualityComparer`1 comparer)
   at LinqToDB.Common.Utils.MakeUniqueNames[T](IEnumerable`1 items, Func`2 validatorFunc, Func`2 nameFunc, Action`2 nameSetter, Func`2 defaultName, StringComparer comparer)
   at LinqToDB.Common.Utils.MakeUniqueNames[T](IEnumerable`1 items, IEnumerable`1 staticNames, Func`2 nameFunc, Action`2 nameSetter, Func`2 defaultName, StringComparer comparer)
   at LinqToDB.Common.Utils.MakeUniqueNames[T](IEnumerable`1 items, IEnumerable`1 staticNames, Func`2 nameFunc, Action`2 nameSetter, String defaultName, StringComparer comparer)
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.MakeMembersNamesUnique(IEnumerable`1 members, String defaultName, String[] reservedNames) in C:\Code\LinqToDBTest\LinqToDB.Templates\LinqToDB.ttinclude:line 1016
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.MakeTypeMembersNamesUnique(Class type, String defaultName, String[] exceptMethods) in C:\Code\LinqToDBTest\LinqToDB.Templates\LinqToDB.ttinclude:line 1011
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.GenerateTypesFromMetadata() in C:\Code\LinqToDBTest\LinqToDB.Templates\LinqToDB.ttinclude:line 956
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.<>c__DisplayClass0_0.<TransformText>b__1() in C:\Code\LinqToDBTest\LinqToDB.Templates\DataModel.ttinclude:line 11
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.GenerateModel() in C:\Code\LinqToDBTest\LinqToDB.Templates\T4Model.ttinclude:line 37
   at Microsoft.VisualStudio.TextTemplating32230CDCC671D78C029B2EA98EB6412A665F8319D0C87699A1DBF75CFD2145B267036FABC74A068FF4E15BDF2CDEFBB11E356EB801328123E56C2EDD8425D2FC.GeneratedTextTransformation.TransformText() in C:\Code\LinqToDBTest\Enterprise.tt:line 14	LinqToDBTest	C:\Code\LinqToDBTest\LinqToDB.Templates\LinqToDB.ttinclude	736	

```

### Environment details
linq2db version: *2.9.1*
Database Server: *SQL Server 14.0.3048.4*
Database Provider: *SqlServerSchemaProvider*
Operating system: *Windows 10*
.NET Framework: *4.7.2*

**Comment by MaceWindu** [comment]
Reproduced...
