### ISSUE TITLE
Tuple inside Analytic Functions projection

### ISSUE THREAD

**Issue by Brains** [linq2db/linq2db#1953]
## Wrong SQL query
This `F#` query:
```fs
let intervals = query {
    for x in db.GetTable<Operation>() do
    select ("username",      //          Tuple
            Sql.DateDiff(
                Sql.DateParts.Minute,
                Nullable (Sql.Ext
                             .Lag(x.time, Sql.Nulls.None)
                             .Over()
                             .PartitionBy(x.user)
                             .OrderBy(x.time)
                             .ToValue()),
                Nullable x.time)) }

query {
    for (u,i) in intervals do
    where (5  <? i && i ?<= 20)
    count }
```
produces
```sql
SELECT
        DateDiff(minute, LAG([x].[eventTime]) OVER(PARTITION BY [x].[eventUser] 
              ORDER BY [x].[eventTime]), [x].[eventTime])
FROM
        [Process_IndexedEvents] [x]

Query Execution Time (AfterExecute): 00:00:00.7769836
Total Execution Time (Completed): 00:00:01.4955837. Rows Count: 25140.
```
`Rows Count: 25140` - means second query is executed locally?

The difference between `(AfterExecute): 00:00:00.7769836` and `(Completed): 00:00:01.4955837` is a time to transmit `25140` rows back from server?

## Correct SQL query
With no `tuple` everything is fine:
```fs
let intervals = query {
    for x in db.GetTable<Operation>() do
    select (Sql.DateDiff(       //      No Tuple
                    Sql.DateParts.Minute,
                    Nullable (Sql.Ext
                                 .Lag(x.time, Sql.Nulls.None)
                                 .Over()
                                 .PartitionBy(x.user)
                                 .OrderBy(x.time)
                                 .ToValue()),
                    Nullable x.time)) }

query {
    for i in intervals do
    where (5 <? i && i ?<= 20)
    count }
```
produces
```sql
SELECT
        Count(*)
FROM
        (
                SELECT
                     DateDiff(minute, LAG([x].[eventTime]) OVER(PARTITION BY [x].[eventUser] 
                            ORDER BY [x].[eventTime]), [x].[eventTime]) as [c1]
                FROM
                     [Process_IndexedEvents] [x]
        ) [i]
WHERE
        5 < [i].[c1] AND [i].[c1] <= 20

Query Execution Time (AfterExecute): 00:00:01.8216351
Total Execution Time (Completed): 00:00:01.8219922. Rows Count: 1.
```
Almost no difference between `AfterExecute` and `Completed` means everything was executed on server?

## Reason
I guess based on my old ticket #1763 
> We have to force subqueries creation when analytic functions are in projection. Where clause is one of the way to do that.

This might be the issue? 
Do any workaround exist?

**Comment by Brains** [comment]
## C#
This query
```cs
var intervals =
    from x in db.GetTable<IndexedEvents>()
    let diff = Sql.DateDiff(
        Sql.DateParts.Minute,
        Sql.Ext
            .Lag(x.eventTime, Sql.Nulls.None)
            .Over()
            .PartitionBy(x.eventUser)
            .OrderBy(x.eventTime)
            .ToValue(),
        x.eventTime)
    select Tuple.Create(x.eventUser, diff);
    // select new Tuple<string, int?>(x.eventUser, diff);   <=== The same result

var filtered =
    from x in intervals
    where (5 < x.Item2 && x.Item2 < 120)
    select x;

var count = filtered.Count();
```
produces
```cs
Unhandled Exception: System.NotImplementedException: The method or operation is not implemented.
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 950
   at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 668
   at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 631
   at LinqToDB.Linq.Builder.ExpressionContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionContext.cs:line 119
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass104_0.<CheckSubQueryForWhere>b__0(Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 88
   at LinqToDB.Expressions.Extensions.Visit(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 373
   at LinqToDB.Expressions.Extensions.Visit(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 418
   at LinqToDB.Expressions.Extensions.Visit(Expression expr, Func`2 func) in C:\projects\linq2db\Source\LinqToDB\Expressions\Extensions.cs:line 418
   at LinqToDB.Linq.Builder.ExpressionBuilder.CheckSubQueryForWhere(IBuildContext context, Expression expression, Boolean& makeHaving) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 59
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 32
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\WhereBuilder.cs:line 23
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\MethodCallBuilder.cs:line 22
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 177
   at LinqToDB.Linq.Builder.CountBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\CountBuilder.cs:line 21
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\MethodCallBuilder.cs:line 22
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 177
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in C:\projects\linq2db\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 148
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 279
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in C:\projects\linq2db\Source\LinqToDB\Linq\Query.cs:line 232
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 84
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in C:\projects\linq2db\Source\LinqToDB\Linq\ExpressionQuery.cs:line 165
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Tests.Program.Main() in C:\Projects\Dashboard.WPF\Tests\Program.cs:line 92
```
Expression test code generated: `C:\Users\solar\AppData\Local\Temp\linq2db\ExpressionTest.0.cs`.
```cs
//---------------------------------------------------------------------------------------------------
// This code was generated by LinqToDB.
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using LinqToDB;

using NUnit.Framework;

namespace T3
{
	public class T0
	{
		public string P1;

		public DateTime P2;
	}
}

namespace Tests.UserTests
{
	[TestFixture]
	public class UserTest : TestBase
	{
		[Test, DataContextSource]
		public void Test(string context)
		{
			// Table([T0]).Select(p4 => new <>f__AnonymousType0`2(p4 = p4, P6 = DateDiff(Minute, Convert(Sql.Ep4t.Lag(p4.P2, None).Over().PartitionBy(new [] {p4.P1}).OrderBy(p4.P2).ToValue()), Convert(p4.P2)))).Select(p7 => Create(p7.p4.P1, p7.P6)).Where(p4 => ((Convert(5) < p4.Item2) AndAlso (p4.Item2 < Convert(120)))).Count()
			using (var db = GetDataContext(context))
			{
				var quey = db.GetTable<T3.T0>()
					.Select(
						p4 => new
						{
							P5 = p4,
							P6 = LinqToDB.Sql.DateDiff(
								Minute,
								(DateTime?).Ext
									.Lag<DateTime>(
										p4.P2,
										None).Over().PartitionBy(
									new [] { p4.P1 }).OrderBy<DateTime>(
									p4.P2).ToValue(),
								(DateTime?)p4.P2)
						})
					.Select(
						p7 => Tuple.Create<string,int?>(
							p7.P5.P1,
							p7.P6))
					.Where(
						p4 => (((int?)5 < p4.Item2) && (p4.Item2 < (int?)120)))
					.Count();
			}
		}
	}
}
```

**Comment by Brains** [comment]
## C#
This works fine
```cs
var intervals =
    from x in db.GetTable<IndexedEvents>()
    let diff = Sql.DateDiff(
        Sql.DateParts.Minute,
        Sql.Ext
            .Lag(x.eventTime, Sql.Nulls.None)
            .Over()
            .PartitionBy(x.eventUser)
            .OrderBy(x.eventTime)
            .ToValue(),
        x.eventTime)
    select diff;

var filtered =
    from x in intervals
    where (5 < x && x < 20)
    select x;

var count = filtered.Count();
```
```sql
SELECT
        Count(*)
FROM
        (
                SELECT
                        DateDiff(minute, LAG([x_1].[eventTime]) OVER(PARTITION BY [x_1].[eventUser] ORDER BY [x_1].[eventTime]), [x_1].[eventTime]) as [c1]
                FROM
                        [IndexedEvents] [x_1]
        ) [x_2]
WHERE
        5 < [x_2].[c1] AND [x_2].[c1] < 20

Query Execution Time (AfterExecute): 00:00:00.4206069
Total Execution Time (Completed): 00:00:00.5415270. Rows Count: 1.
```

**Comment by sdanyliv** [comment]
It is know limitation, but solvable. Even more i have create code which supports tuples and i just need to extract it from other branch.
Problem here when you use Tuple.Create - we do not collect information how members are mapped to the Sql.

**Comment by Brains** [comment]
Awesome. I will wait for the fix and update `linq2db` reference right then. Thank you.
#
You think issue with `F#` is the same, due to `Tuple` too? Because it does not produce the `System.NotImplementedException`, just the wrong query?

**Comment by Brains** [comment]
Expression test code generated for `Wrong F# query` in first post https://github.com/linq2db/linq2db/issues/1953#issue-512980693
```cs
//---------------------------------------------------------------------------------------------------
// This code was generated by LinqToDB.
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using LinqToDB;

using NUnit.Framework;

namespace T10.T11
{
	[System.SerializableAttribute()]
	[LinqToDB.Mapping.TableAttribute("Process_IndexedEvents")]
	[Microsoft.FSharp.Core.CompilationMappingAttribute((Microsoft.FSharp.Core.SourceConstructFlags)2)]
	class T0 : IEquatable<T10.T11.T24>, System.Collections.IStructuralEquatable
	{
		[System.ComponentModel.DescriptionAttribute("eventTime")]
		[LinqToDB.Mapping.ColumnAttribute("eventTime")]
		[LinqToDB.Mapping.NotNullAttribute()]
		[Microsoft.FSharp.Core.CompilationMappingAttribute((Microsoft.FSharp.Core.SourceConstructFlags)4, (Int32)3)]
		public DateTime P22 { get; set; }

		[System.ComponentModel.DescriptionAttribute("eventUser")]
		[LinqToDB.Mapping.ColumnAttribute("eventUser")]
		[LinqToDB.Mapping.NotNullAttribute()]
		[Microsoft.FSharp.Core.CompilationMappingAttribute((Microsoft.FSharp.Core.SourceConstructFlags)4, (Int32)4)]
		public string P23 { get; set; }
	}
}

namespace Tests.UserTests
{
	[TestFixture]
	public class UserTest : TestBase
	{
		[Test, DataContextSource]
		public void Test(string context)
		{
			// Table([Process_Indep25edEvents]).Select(p25 => new AnonymousObject`2(Item1 = p25.p5, Item2 = DateDiff(Minute, Convert(Sql.Ep25t.Lag(p25.p4, None).Over().PartitionBy(new [] {p25.p5}).OrderBy(p25.p4).ToValue()), Convert(p25.p4))))
			using (var db = GetDataContext(context))
			{
				var quey = db.GetTable<T10.T11.T24>()
					.Select(
						p25 => new Microsoft.FSharp.Linq.RuntimeHelpers.AnonymousObject<string,int?>(p25.P23, LinqToDB.Sql.DateDiff(
							Minute,
							(DateTime?).Ext
								.Lag<DateTime>(
									p25.P22,
									None).Over().PartitionBy(
								new [] { p25.P23 }).OrderBy<DateTime>(
								p25.P22).ToValue(),
							(DateTime?)p25.P22)));
			}
		}
	}
}
```

**Comment by sdanyliv** [comment]
I’m not F# guy, but looks like first query executed locally (not by linq2db). Maybe some compiler tricks?
Your generated test looks good but without where part, but will also not work as expected. It is like situation with Tuple - we can not track fields because here used constructror.

**Comment by Brains** [comment]
I see. Thanks. Will try `F#` version after update, maybe will help too.

**Comment by sdanyliv** [comment]
As a workaround return not tuple but anonymous object
this one:
```cs
select Tuple.Create(x.eventUser, diff);
```
Replace with:
```cs
select new {x.eventUser, diff};
```

**Comment by Brains** [comment]
Yes, sure, tried anonymous object already, it always worked in `C#`. Sorry forgot to mention this.

But I can't translate anonymous object back to `F#`, that's why I am sticking with plain `Tuple`, which is used as direct equivalent of `F#` tuple.

**Comment by sdanyliv** [comment]
I think this Thursday we will release new version with this fix.

**Comment by Brains** [comment]
Nice, thanks. Will wait.

Can you also add label `area:fsharp` to this ticket maybe somebody else will look into specific `F#` issue?

**Comment by Brains** [comment]
For future reference added expression test code generated for `F#` queries from first post https://github.com/linq2db/linq2db/issues/1953#issue-512980693

## Wrong
```cs
//---------------------------------------------------------------------------------------------------
// This code was generated by LinqToDB.
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using LinqToDB;

using NUnit.Framework;

namespace T10.T11
{
	[System.SerializableAttribute()]
	[LinqToDB.Mapping.TableAttribute("Process_IndexedEvents")]
	[Microsoft.FSharp.Core.CompilationMappingAttribute((Microsoft.FSharp.Core.SourceConstructFlags)2)]
	class T0 : IEquatable<T10.T11.T24>, System.Collections.IStructuralEquatable
	{
		[System.ComponentModel.DescriptionAttribute("eventTime")]
		[LinqToDB.Mapping.ColumnAttribute("eventTime")]
		[LinqToDB.Mapping.NotNullAttribute()]
		[Microsoft.FSharp.Core.CompilationMappingAttribute((Microsoft.FSharp.Core.SourceConstructFlags)4, (Int32)3)]
		public DateTime P22 { get; set; }

		[System.ComponentModel.DescriptionAttribute("eventUser")]
		[LinqToDB.Mapping.ColumnAttribute("eventUser")]
		[LinqToDB.Mapping.NotNullAttribute()]
		[Microsoft.FSharp.Core.CompilationMappingAttribute((Microsoft.FSharp.Core.SourceConstructFlags)4, (Int32)4)]
		public string P23 { get; set; }
	}
}

namespace Tests.UserTests
{
	[TestFixture]
	public class UserTest : TestBase
	{
		[Test, DataContextSource]
		public void Test(string context)
		{
			// Table([Process_Indep25edEvents])
			// 	.Select(p25 =>
			// 		new AnonymousObject`2(Item1 = "p5name", Item2 =
			// 			DateDiff(
			// 				Minute,
			// 				Convert(Sql.Ep25t.Lag(p25.p4, None)
			// 								 .Over()
			// 								 .PartitionBy(new [] {p25.p5})
			// 								 .OrderBy(p25.p4)
			// 								 .ToValue()),
			// 						Convert(p25.p4))))
			using (var db = GetDataContext(context))
			{
				var quey = db.GetTable<T10.T11.T24>()
					.Select(
						p25 => new Microsoft.FSharp.Linq.RuntimeHelpers.AnonymousObject<string,int?>(
							"username",
							LinqToDB.Sql.DateDiff(
								Minute,
								(DateTime?).Ext
									.Lag<DateTime>(
										p25.P22,
										None).Over().PartitionBy(
									new [] { p25.P23 }).OrderBy<DateTime>(
									p25.P22).ToValue(),
								(DateTime?)p25.P22)));
			}
		}
	}
}
```

## Correct
```cs
//---------------------------------------------------------------------------------------------------
// This code was generated by LinqToDB.
//---------------------------------------------------------------------------------------------------
using System;
using System.Linq;
using System.Linq.Expressions;
using LinqToDB;

using NUnit.Framework;

namespace T10.T11
{
	[System.SerializableAttribute()]
	[LinqToDB.Mapping.TableAttribute("Process_IndexedEvents")]
	[Microsoft.FSharp.Core.CompilationMappingAttribute((Microsoft.FSharp.Core.SourceConstructFlags)2)]
	class T0 : IEquatable<T10.T11.T24>, System.Collections.IStructuralEquatable
	{
		[System.ComponentModel.DescriptionAttribute("eventTime")]
		[LinqToDB.Mapping.ColumnAttribute("eventTime")]
		[LinqToDB.Mapping.NotNullAttribute()]
		[Microsoft.FSharp.Core.CompilationMappingAttribute((Microsoft.FSharp.Core.SourceConstructFlags)4, (Int32)3)]
		public DateTime P22 { get; set; }

		[System.ComponentModel.DescriptionAttribute("eventUser")]
		[LinqToDB.Mapping.ColumnAttribute("eventUser")]
		[LinqToDB.Mapping.NotNullAttribute()]
		[Microsoft.FSharp.Core.CompilationMappingAttribute((Microsoft.FSharp.Core.SourceConstructFlags)4, (Int32)4)]
		public string P23 { get; set; }
	}
}

namespace Tests.UserTests
{
	[TestFixture]
	public class UserTest : TestBase
	{
		[Test, DataContextSource]
		public void Test(string context)
		{
			// Table([Process_Indep25edEvents])
			// 	.Select(p25 =>
			// 			DateDp26ff(
			// 				Mp26nute,
			// 				Convert(Sql.Ep25t.Lag(p25.p4, None)
			// 								 .Over()
			// 								 .Partp26tp26onBy(new [] {p25.p5})
			// 								 .OrderBy(p25.p4)
			// 								 .ToValue()),
			// 						Convert(p25.p4)))
			// 	.Where(p26 => ((Convert(5) < p26) AndAlso (p26 <= Convert(20))))
			// 	.Count()
			using (var db = GetDataContext(context))
			{
				var quey = db.GetTable<T10.T11.T24>()
					.Select(
						p25 => LinqToDB.Sql.DateDiff(
							Minute,
							(DateTime?).Ext
								.Lag<DateTime>(
									p25.P22,
									None).Over().PartitionBy(
								new [] { p25.P23 }).OrderBy<DateTime>(
								p25.P22).ToValue(),
							(DateTime?)p25.P22))
					.Where(
						p26 => (((int?)5 < p26) && (p26 <= (int?)20)))
					.Count();
			}
		}
	}
}
```

## Difference
![image](https://user-images.githubusercontent.com/5301844/67638056-6fe72b00-f8e9-11e9-8c1f-34516002899e.png)

**Comment by Brains** [comment]
@sdanyliv Thank you for the PR, appreciate this.
