### ISSUE TITLE
SELECT-INSERT selects less columns than inserted if the same value is inserted in more than one column

### ISSUE THREAD

**Issue by JechoJekov** [linq2db/linq2db#1962]
SELECT-INSERT selects less columns than inserted when the select contains duplicate values.

```
Exception: System.Data.SqlClient.SqlException
Exception message: The select list for the INSERT statement contains fewer items than the insert list. The number of SELECT values must match the number of INSERT columns.
Stack trace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.RunExecuteNonQueryTds(String methodName, Boolean async, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite, String methodName)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery() in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 1152
```

### Steps to reproduce

SQL Server table:

```SQL
CREATE TABLE [dbo].[Entity](
	[Id] [int] IDENTITY(1,1) NOT NULL,
	[TimeCreated] [datetime2](7) NOT NULL,
	[TimeUpdated] [datetime2](7) NOT NULL,
	[Data] [nvarchar](100) NOT NULL,
 CONSTRAINT [PK_Entity] PRIMARY KEY CLUSTERED 
(
	[Id] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
```

```c#
db.Entities
	.Where(x => x.Id == 1)
	.Into(db.Entities)
	.Value(x => x.TimeCreated, () => Sql.CurrentTimestampUtc)
	.Value(x => x.TimeUpdated, () => Sql.CurrentTimestampUtc)
	.Value(x => x.Data, "123")
	.Insert();
```

Generated SQL query:

```SQL
--  SqlServer.2012
INSERT INTO [dbo].[Entity]
(
	[TimeCreated],
	[TimeUpdated],
	[Data]
)
SELECT
	SYSUTCDATETIME(),
	N'123'
FROM
	[dbo].[Entity] [x]
WHERE
	[x].[Id] = 1
```

### Environment details
linq2db version: 2.9.2
Database Server: SQL Server 2014
Operating system: Windows Server 2012R2
.NET Framework: .NET Core 2.2

**Comment by sdanyliv** [comment]
I see. Looks like we have optimized out this additional expression.
Will be fixed soon.
