### ISSUE TITLE
Arithmetic operation resulted in an overflow

### ISSUE THREAD

**Issue by theo2f** [linq2db/linq2db#1993]
I'm trying to generate POCOs from an **MySql database**, but I always receive this error.
When I do using an SQL Server database then everything works fine. Only on MySql that I'm getting this error.

```
Exception message: Running transformation: System.OverflowException: Arithmetic operation resulted in an overflow.

Stack trace:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.OverflowException: Arithmetic operation resulted in an overflow.
   at lambda_method(Closure , Object )
   at LinqToDB.Common.Converter.ChangeTypeTo[T](Object value, MappingSchema mappingSchema)
   at LinqToDB.DataProvider.MySql.MySqlSchemaProvider.<GetColumns>b__25(<>f__AnonymousType59`2 <>h__TransparentIdentifier1f)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__59`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LinqToDB.DataProvider.MySql.MySqlSchemaProvider.GetColumns(DataConnection dataConnection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplating49D42E466A2B0C6C793F648589522EFDFA6844546C46A8B15D1B73F03F6DA79D910075A35314FEC7D9443EF8314BB58D22354904ECF5879DAC21478C9F9EEB72.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in D:\Downloads\examples-master\examples-master\MySql\GetStarted\LinqToDB.Templates\DataModel.ttinclude:line 55
   at Microsoft.VisualStudio.TextTemplating49D42E466A2B0C6C793F648589522EFDFA6844546C46A8B15D1B73F03F6DA79D910075A35314FEC7D9443EF8314BB58D22354904ECF5879DAC21478C9F9EEB72.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in D:\Downloads\examples-master\examples-master\MySql\GetStarted\LinqToDB.Templates\DataModel.ttinclude:line 259
   at Microsoft.VisualStudio.TextTemplating49D42E466A2B0C6C793F648589522EFDFA6844546C46A8B15D1B73F03F6DA79D910075A35314FEC7D9443EF8314BB58D22354904ECF5879DAC21478C9F9EEB72.GeneratedTextTransformation.LoadMySqlMetadata(String server, String database, String uid, String password) in D:\Downloads\examples-master\examples-master\MySql\GetStarted\LinqToDB.Templates\LinqToDB.MySql.ttinclude:line 28
   at Microsoft.VisualStudio.TextTemplating49D42E466A2B0C6C793F648589522EFDFA6844546C46A8B15D1B73F03F6DA79D910075A35314FEC7D9443EF8314BB58D22354904ECF5879DAC21478C9F9EEB72.GeneratedTextTransformation.TransformText() in D:\Downloads\examples-master\examples-master\MySql\GetStarted\Objetos\CopyMe.MySql.tt:line 37	GetStarted	D:\Downloads\examples-master\examples-master\MySql\GetStarted\LinqToDB.Templates\DataModel.ttinclude	55	
```

### Steps to reproduce
Create this table in a clean MySql database:
```
CREATE TABLE myTable (
  id INTEGER UNSIGNED  NOT NULL   AUTO_INCREMENT,
  description VARCHAR(100)  NULL    ,
PRIMARY KEY(id));
```
Create a new project (I did as a Console .Net Framework).

Nuget package included:
```
Install-Package linq2db.MySql -Version 2.9.4
```

Template file created:
```
<#@ template language="C#" debug="True" hostSpecific="True"                       #>
<#@ output extension=".generated.cs"                                              #>
<#@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.MySql.Tools.ttinclude" #>
<#@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude" #>
<#
	NamespaceName = "DataModel";
	LoadMySqlMetadata("10.10.1.100", "mydb", "myuser", "mypass");
	GenerateModel();
#>
```

```c#
<code with error and mapping classes>
```

### Environment details
linq2db version: *2.9.4*
Database Server: *5.7.28*
Database Provider: *MySql.Data.MySqlClient*
Operating system: *Windows 10 64bits*
.NET Framework: *4 (solution)*

**Comment by MaceWindu** [comment]
@theo2f I cannot reproduce it. Could you provide resuts of this query:
```sql
SELECT
		DATA_TYPE,
		COLUMN_TYPE,
		TABLE_SCHEMA,
		TABLE_NAME,
		COLUMN_NAME,
		IS_NULLABLE,
		ORDINAL_POSITION,
		CHARACTER_MAXIMUM_LENGTH,
		NUMERIC_PRECISION,
		NUMERIC_SCALE,
		EXTRA,
		COLUMN_COMMENT
	FROM INFORMATION_SCHEMA.COLUMNS
	WHERE TABLE_SCHEMA = DATABASE()
```
or just provide details which field contains abnormal value?
It should be onle of those:
- ORDINAL_POSITION we expect to store int32 value
- CHARACTER_MAXIMUM_LENGTH we expect nullable in64 value
- NUMERIC_PRECISION we expect nullable in32 value
- NUMERIC_SCALE we expect nullable in32 value

**Comment by viceroypenguin** [comment]
Closing as outdated with no response. If this is still an issue, please file a new issue with information from a current version of l2db.
