### ISSUE TITLE
exception when trying demo code from wiki

### ISSUE THREAD

**Issue by giuliohome** [linq2db/linq2db#201]
I've installed linq2db packages from nuget and followed the example in the wiki
This is my connection class
```c#
	public class icts_userContext : LinqToDB.Data.DataConnection
	{
		public icts_userContext() : base("MyConnectionString") 
		{
		}
		public ITable<my_table> icts_user { get { return GetTable<my_table>(); } }
	}
```
and the exception I'm getting at the above constructor is 
```c#
System.IO.DirectoryNotFoundException: Could not find a part of the path 'i:\linq2db\Source\Data\DataConnection.cs'.
```
in my App.config
```c#
	<connectionStrings>
		<add name="MyConnectionString" connectionString="Data Source=c:\TestData.sqlite" providerName="SQLite" />
	</connectionStrings>
```

**Comment by giuliohome** [comment]
Sorry. It's just a *Debug* message, I don't need to Debug the *source* at the moment.
SQlite is working. I'm going to test the Sybase ASE connection (will reopen this if something fails)

**Comment by giuliohome** [comment]
I've tried to Reference the Sybase AGO.NET dll but I get the following error
```c#
Could not load file or assembly 'Sybase.AdoNet2.AseClient' or one of its dependencies. Impossibile trovare il file specificato.
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMarkHandle stackMark, Boolean loadTypeFromPartialName, ObjectHandleOnStack type)
   at System.RuntimeTypeHandle.GetTypeByName(String name, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark, Boolean loadTypeFromPartialName)
   at System.RuntimeType.GetType(String typeName, Boolean throwOnError, Boolean ignoreCase, Boolean reflectionOnly, StackCrawlMark& stackMark)
   at System.Type.GetType(String typeName, Boolean throwOnError)
   at LinqToDB.DataProvider.DynamicDataProviderBase.get_DataReaderType() in i:\linq2db\Source\DataProvider\DynamicDataProviderBase.cs:line 56
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.get_DataReaderType() in i:\linq2db\Source\Data\DataConnection.Linq.cs:line 310
   at LinqToDB.Linq.Builder.ExpressionBuilder..ctor(Query query, IDataContextInfo dataContext, Expression expression, ParameterExpression[] compiledParameters) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 115
   at LinqToDB.Linq.Query`1.GetQuery(IDataContextInfo dataContextInfo, Expression expr) in i:\linq2db\Source\Linq\Query.cs:line 165
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression expression, Boolean cache) in i:\linq2db\Source\Linq\ExpressionQuery.cs:line 77
   at LinqToDB.Linq.ExpressionQuery`1.Execute(IDataContextInfo dataContextInfo, Expression expression) in i:\linq2db\Source\Linq\ExpressionQuery.cs:line 69
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in i:\linq2db\Source\Linq\ExpressionQuery.cs:line 149
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MyEF.Window1.All() in c:\SO\TestEF\MyEF\Window1.xaml.cs:line 54
   at MyEF.Window1..ctor() in c:\SO\TestEF\MyEF\Window1.xaml.cs:line 36
```

**Comment by giuliohome** [comment]
Solved by *myself* 
You have the Redist in this repository.
Thanks for not answering)
