### ISSUE TITLE
Sybase LinqToDB.Templates timeout

### ISSUE THREAD

**Issue by fcabralj** [linq2db/linq2db#2026]
When I rename the CopyMe.Sybase.tt.txt to *.tt I'm getting the following error: 

 Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: Sybase.Data.AseClient.AseException: The command has timed out.
   at Sybase.Data.AseClient1.AseCommand.CheckResult(Int32 res)
   at Sybase.Data.AseClient1.AseCommand.Execute(CommandBehavior commandBehavior)
   at Sybase.Data.AseClient1.AseCommand._ExecuteReader(CommandBehavior commandBehavior)
   at Sybase.Data.AseClient1.AseCommand.ExecuteReader(CommandBehavior commandBehavior)
   at Sybase.Data.AseClient.AseCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.CommandInfo.ExecuteReader()
   at LinqToDB.Data.DataConnectionExtensions.ExecuteReader(DataConnection connection, String sql, CommandType commandType, CommandBehavior commandBehavior, DataParameter[] parameters)
   at LinqToDB.DataProvider.Sybase.SybaseSchemaProvider.GetProcedureParameters(DataConnection dataConnection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplating6158FFC7DCBC0759FC489824BE84D2F035E6B16775C152F3D7EA9341E0F5795EDC3B0439987706D9BB8830FE8C4BCA85975FFD38360E0281105DBCE73027BEFD.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in D:\C#_Prototypes\cabralf\DataExtraction\packages\linq2db.Sybase.2.6.4\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude:line 103
   at Microsoft.VisualStudio.TextTemplating6158FFC7DCBC0759FC489824BE84D2F035E6B16775C152F3D7EA9341E0F5795EDC3B0439987706D9BB8830FE8C4BCA85975FFD38360E0281105DBCE73027BEFD.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in D:\C#_Prototypes\cabralf\_DataExtraction\packages\linq2db.Sybase.2.6.4\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude:line 415
   at Microsoft.VisualStudio.TextTemplating6158FFC7DCBC0759FC489824BE84D2F035E6B16775C152F3D7EA9341E0F5795EDC3B0439987706D9BB8830FE8C4BCA85975FFD38360E0281105DBCE73027BEFD.GeneratedTextTransformation.LoadSybaseMetadata(String connectionString) in D:\C#__Prototypes\cabralf\_DataExtraction\packages\linq2db.Sybase.2.6.4\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.Sybase.ttinclude:line 71
   at Microsoft.VisualStudio.TextTemplating6158FFC7DCBC0759FC489824BE84D2F035E6B16775C152F3D7EA9341E0F5795EDC3B0439987706D9BB8830FE8C4BCA85975FFD38360E0281105DBCE73027BEFD.GeneratedTextTransformation.TransformText() in D:\C#__Prototypes\cabralf\_DataExtraction\_DataExtraction\DTO\Raw\CopyMe.Sybase.tt:line 45		D:\C#__Prototypes\cabralf\_DataExtraction\packages\linq2db.Sybase.2.6.4\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude	103

**Comment by sdanyliv** [comment]
At first, you have to do not RENAME but CREATE NEW tt file in your project and copy paste content.
Then you have to specify correct connection string as described in comment of original CopyMe.Sybase.tt.txt.
https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB.Templates#running

**Comment by fcabralj** [comment]
@sdanyliv I've did exactly what you said, created a new tt file and copied and pasted the content from the LinqToDB.Templates folder into this new file, but still the same error.
I've also specified the connection string as I have into my Sybase server manager. 

I believe this error is related to something I'ù trying to load which I could avoid, for example storedprocedures. Or it could be related to the sybase driver. 

I've try to comment out the stored procedures generation but I didn't find the right location to do so, could you indicate to me where could I set it as false?

**Comment by sdanyliv** [comment]
To disable stored pocs generation, just correct GetSchemaOptions in tt file.
`GetSchemaOptions.GetProcedures         = false;`

**Comment by fcabralj** [comment]
@sdanyliv after downloading the linqpackage and including what you suggested "GetProcedures = false;" it worked.

Thank you
