### ISSUE TITLE
DataConnection.GetTable<Entity> throws an exception if "Entity" type contains ref property

### ISSUE THREAD

**Issue by TheWind3** [linq2db/linq2db#2052]
Exception message:
```
The type "Test.DataPack&" may not be used as a type argument
```

Stack trace:
```
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> System.ArgumentException: The type 'Test.DataPack&' may not be used as a type argument.
   at System.RuntimeType.ThrowIfTypeNeverValidGenericArgument(RuntimeType type)
   at System.RuntimeType.SanityCheckGenericArguments(RuntimeType[] genericArguments, RuntimeType[] genericParamters)
   at System.RuntimeType.MakeGenericType(Type[] instantiation)
   at LinqToDB.Reflection.MemberAccessor.SetSimple(MemberInfo memberInfo, EntityDescriptor ed)
   at LinqToDB.Reflection.TypeAccessor`1..ctor()
   --- End of inner exception stack trace ---
   at System.RuntimeTypeHandle.CreateInstance(RuntimeType type, Boolean publicOnly, Boolean noCheck, Boolean& canBeCached, RuntimeMethodHandleInternal& ctor, Boolean& bNeedSecurityCheck)
   at System.RuntimeType.CreateInstanceSlow(Boolean publicOnly, Boolean skipCheckThis, Boolean fillCache, StackCrawlMark& stackMark)
   at System.Activator.CreateInstance(Type type, Boolean nonPublic)
   at LinqToDB.Reflection.TypeAccessor.GetAccessor(Type type)
   at LinqToDB.Mapping.EntityDescriptor..ctor(MappingSchema mappingSchema, Type type)
   at LinqToDB.Mapping.MappingSchema.<>c__DisplayClass91_0.<GetEntityDescriptor>b__0(ICacheEntry o)
   at LinqToDB.Common.Internal.Cache.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
   at LinqToDB.Mapping.MappingSchema.GetEntityDescriptor(Type type)
   at LinqToDB.Linq.Table`1.InitTable(IDataContext dataContext, Expression expression)
   at LinqToDB.Data.DataConnection.GetTable[T]()
   at Test.Database.get_Entities()
   at Test.Program.Main()
```

### Steps to reproduce
```c#
namespace Test {
  using System;
  using System.Linq;
  using LinqToDB;
  using LinqToDB.Data;
  using LinqToDB.Mapping;

  class Program {
    static void Main() {
      var db = new Database();
      var query = db.Entities.Where(_ => true);
    }
  }


  public class Database: DataConnection {
    public ITable<Entity> Entities => GetTable<Entity>();
  }


  [Table("Entity", IsColumnAttributeRequired = true)]
  public class Entity {

    public ref DataPack Data => ref _Data;
    private DataPack _Data;
  }


  public struct DataPack {
  }
}
```

### Environment details
linq2db version: 2.9.5

**Comment by sdanyliv** [comment]
@TheWind3, just ignoring such properties is OK solution?

**Comment by TheWind3** [comment]
Sure.
Thank you!

чт, 23 янв. 2020 г., 19:47 Svyatoslav Danyliv <notifications@github.com>:
