### ISSUE TITLE
JOIN always expects properties of long type in result selector

### ISSUE THREAD

**Issue by artemiusgreat** [linq2db/linq2db#2056]
Trying to use JOIN in MySQL provider. As a result of a JOIN operation I want to extract 2 fields from table A + 1 field from table B, but I'm getting either a syntax error or a mapping format exception. Tried any syntax, fluent extension methods and LINQ integrated query. Examples below.

**Expectation - group 2 tables by Record ID**

```
var groups = session
  .GroupRecords
  .Join(session.Groups, x1 => x1.GroupId, x2 => x2.Id, (v1, v2) => new
  {
    GroupId = v1.GroupId,  
    RecordId = v1.RecordId,
    Name = v2.Name
  })
  .ToList()
  .GroupBy(o => o.RecordId)
  .ToDictionary(o => o.Key, o => o.ToList());
```

**Syntax error when mapping property by property in result selector**

```
Type of conditional expression cannot be determined because there is no implicit conversion between 'string' and 'long'
```

**Stack trace when return objects in result selector**

```
LinqToDB.Common.LinqToDBConvertException: Mapping of column groups_name value failed, see inner exception for details
 ---> System.FormatException: Input string was not in a correct format.
   at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Number.ParseInt64(ReadOnlySpan`1 value, NumberStyles styles, NumberFormatInfo info)
   at System.Int64.Parse(String s)
   at lambda_method(Closure , IDataReader )
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
   --- End of inner exception stack trace ---
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
   at lambda_method(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Services.ControllerSpace.RecordsController.Records(QueryModel query) in D:\Code\Net\Emotions\Services\Controllers\RecordsController.cs:line 42
   at lambda_method(Closure , Object )
   at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```

**MySQL tables**

```
CREATE TABLE `emo_groups` (
  `groups_id` bigint(20) NOT NULL,
  `users_id` bigint(20) NOT NULL,
  `groups_name` varchar(50) COLLATE utf8_unicode_ci NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;

CREATE TABLE `emo_groups_records` (
  `groups_records_id` bigint(20) NOT NULL,
  `groups_id` bigint(20) NOT NULL,
  `records_id` bigint(20) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COLLATE=utf8_unicode_ci;
```

**Models**

```
  [Table(Name = "emo_groups")]
  public class GroupEntity : ExpandoModel
  {
    [PrimaryKey, Identity, Column(Name = "groups_id", IsIdentity = true)]
    public long Id { get; set; }

    [Column(Name = "users_id"), NotNull]
    public long UserId { get; set; }
    
    [Column(Name = "groups_name"), NotNull]
    public long Name { get; set; }
  }

  [Table(Name = "emo_groups_records")]
  public class GroupRecordEntity : ExpandoModel
  {
    [PrimaryKey, Identity, Column(Name = "groups_records_id", IsIdentity = true)]
    public long Id { get; set; }

    [Column(Name = "groups_id"), NotNull]
    public long GroupId { get; set; }

    [Column(Name = "records_id"), NotNull]
    public long RecordId { get; set; }
  }

  public class DataManager : LinqToDB.Data.DataConnection
  {
    public DataManager(string connection) : base(connection) {}
    public DataManager(IDbConnection connection) : base(new MySqlDataProvider(), connection) {}

    public ITable<InputEntity> Inputs => GetTable<InputEntity>();
    public ITable<GroupEntity> Groups => GetTable<GroupEntity>();
    public ITable<RecordEntity> Records => GetTable<RecordEntity>();
    public ITable<GroupRecordEntity> GroupRecords => GetTable<GroupRecordEntity>();
    public ITable<RecordInputEntity> RecordInputs => GetTable<RecordInputEntity>();
  }
```

**[Does NOT work] - Exception**
```
var groups = 
  from v1 in session.GroupRecords
  join v2 in session.Groups on v1.GroupId equals v2.Id
  select new 
  {
    // gives an exception about incorrect input mapping format because v1 and v2 are objects, and Linq2Db in some reason expects them all to be long
    SomeGroup = v1,  
    SomeRecord = v2  
  };
```

**[Does NOT work] - Syntax Error**

```
var groups = session
  .GroupRecords
  .Join(session.Groups, x1 => x1.GroupId, x2 => x2.Id, (v1, v2) => new
  {
    SomeGroup = v1.GroupId,
    SomeRecord = v2.RecordId,
    SomeGroupName = v2 == null ? string.Empty : v2.Name // cannot compile this, string vs long
  })
  .ToList();
```

**[Works] - When I use only "long" values in result selector it works fine**

```
var groups = session
  .GroupRecords
  .Join(session.Groups, x1 => x1.GroupId, x2 => x2.Id, (v1, v2) => new
  {
    SomeGroup = v1.GroupId,  
    SomeRecord = v1.RecordId  
  })
  .ToList()
  .GroupBy(o => o.SomeRecord);
```

### Environment details

linq2db version: 3.0.0 preview.1
Database Server: Windows 10 Pro
Database Provider: MySQL Ver 15.1 Distrib 10.4.8-MariaDB, for Win64 (AMD64), source revision 4c2464b87d58a43d1292e166bae6720b51f4b000
Operating system: Windows
.NET Framework: .NET Core 3

**Comment by artemiusgreat** [comment]
Sorry. False alarm. I'm an idiot. I used "long" as a type for "Name" property in GroupEntity model.
