### ISSUE TITLE
KeyNotFoundException

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#2072]
Hello,
  I have created chain of Cte and I have created a hierarchy of object types to use when I create the selector of each Cte.
  For example:
```cs
  Class A
    public string Property1 {get; set;}

  Class B : A
    public string Property2 {get; set;}

  Class C: B
    public string Property3 {get; set;}
  ...
  Class N:N-1
```
```cs
  Cte1: from item in db.A select new A{ property1 = ...} .AsCte...
  Cte2: from item in Cte1 select new B{ property1 = ..., property2 = ...} .AsCte...
  Cte3: from item in Cte2 select new C{ property1 = ..., property2 = ..., property3 = ... } .AsCte...
  ...
  CteN ...
```
  I get this exception:

```
System.Collections.Generic.KeyNotFoundException
  HResult=0x80131577
  Messaggio=The given key 'System.String SfcRouterBo' was not present in the dictionary.
  Origine=System.Private.CoreLib
  Analisi dello stack:
   at System.ThrowHelper.ThrowKeyNotFoundException[T](T key)
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T](Expression expression, MemberExpression levelExpression, Int32 level, Func`6 action)
   at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag)
   at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
   at LinqToDB.Linq.Builder.TableBuilder.CteTableContext.IsExpression(Expression expression, Int32 level, RequestFor requestFor)
   at LinqToDB.Linq.Builder.PassThroughContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
   at LinqToDB.Linq.Builder.SubQueryContext.IsExpression(Expression expression, Int32 level, RequestFor testFlag)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertObjectComparison(ExpressionType nodeType, IBuildContext leftContext, Expression left, IBuildContext rightContext, Expression right)
   at LinqToDB.Linq.Builder.JoinBuilder.BuildJoin(ExpressionBuilder builder, SqlSearchCondition condition, IBuildContext outerKeyContext, Expression outerKeySelector, IBuildContext innerKeyContext, Expression innerKeySelector)
   at LinqToDB.Linq.Builder.JoinBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.JoinBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.JoinBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.JoinBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.TableBuilder.<>c__DisplayClass11_0.<BuildCteContext>b__1(CteClause cteClause)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildCte(Expression cteExpression, Func`2 buildFunc)
   at LinqToDB.Linq.Builder.TableBuilder.BuildCteContext(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.TableBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.CountBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.LongCount[TSource](IQueryable`1 source)
   at EtlDatalogic.Model.CteBase`1.AppendInfo[T](IQueryable`1 queryable, StringBuilder report, Boolean includeRowsCount) in C:\GitDefaultCollection\Clienti\Datalogic\EtlDatalogic\EtlDatalogic\Model\CteBase.cs:line 78

  Questa eccezione è stata generata in origine nello stack di chiamate seguente:
	System.ThrowHelper.ThrowKeyNotFoundException<T>(T)
	System.Collections.Generic.Dictionary<TKey, TValue>.this[TKey].get(TKey)
	LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess<T>(System.Linq.Expressions.Expression, System.Linq.Expressions.MemberExpression, int, System.Func<int, LinqToDB.Linq.Builder.IBuildContext, System.Linq.Expressions.Expression, int, System.Linq.Expressions.Expression, T>)
	LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(System.Linq.Expressions.Expression, int, LinqToDB.Linq.Builder.RequestFor)
	LinqToDB.Linq.Builder.SelectContext.IsExpression(System.Linq.Expressions.Expression, int, LinqToDB.Linq.Builder.RequestFor)
	LinqToDB.Linq.Builder.TableBuilder.CteTableContext.IsExpression(System.Linq.Expressions.Expression, int, LinqToDB.Linq.Builder.RequestFor)
	LinqToDB.Linq.Builder.PassThroughContext.IsExpression(System.Linq.Expressions.Expression, int, LinqToDB.Linq.Builder.RequestFor)
	LinqToDB.Linq.Builder.SubQueryContext.IsExpression(System.Linq.Expressions.Expression, int, LinqToDB.Linq.Builder.RequestFor)
	LinqToDB.Linq.Builder.ExpressionBuilder.ConvertObjectComparison(System.Linq.Expressions.ExpressionType, LinqToDB.Linq.Builder.IBuildContext, System.Linq.Expressions.Expression, LinqToDB.Linq.Builder.IBuildContext, System.Linq.Expressions.Expression)
	LinqToDB.Linq.Builder.JoinBuilder.BuildJoin(LinqToDB.Linq.Builder.ExpressionBuilder, LinqToDB.SqlQuery.SqlSearchCondition, LinqToDB.Linq.Builder.IBuildContext, System.Linq.Expressions.Expression, LinqToDB.Linq.Builder.IBuildContext, System.Linq.Expressions.Expression)
    ...
    [Stack di chiamate troncato]
```

  Sorry but the source code it's to complex to send.
  This issue was opened only to inform you that some times the query analyzer may have some issues analyzing class hierarchies. 

### Environment details
linq2db version: 3.0.0-preview.1
Database Server: Oracle
Database Provider: Oracle.ManagedDataAccess.Core (3.0.0-preview.1)
Operating system: Windows 10
.NET Framework:.NET Core 3.1

**Comment by sdanyliv** [comment]
@filippobottega, please switch to 2.9.6, because 3.0.0-preview.1 is far behind latest version.

**Comment by MaceWindu** [comment]
you can also try to use preview2 rc from https://dev.azure.com/linq2db/linq2db/_packaging?_a=package&feed=linq2db%40Local&package=linq2db&protocolType=NuGet&version=3.0.0-rc.1436&view=versions

which is basically latest v2 + 3.0 preview1 right now. But there is one known regression in complex merge scenarios with associations.

**Comment by MaceWindu** [comment]
Looks like our builds are outdated there :) triggrered new build manually

**Comment by sdanyliv** [comment]
@filippobottega, i can not reproduce but, based on StackTrace I've got idea what happened. I hope 2.9.7 release will fix this issue.
