### ISSUE TITLE
Can i add linq2mysql and linq2sqlite in one project?

### ISSUE THREAD

**Issue by koujiangheng** [linq2db/linq2db#2079]
Can i add linq2mysql and linq2sqlite in one project? So i can choose one to use according to specific conditions?
like 
if(databaseType=="Mysql")
{
      using(var db = new MySqlDB())
}
if(databaseType=="Sqlite")
{
     using(var db = new SqliteDB())
}

**Comment by MaceWindu** [comment]
Yes, linq2db package already has all databases support. linq2db.<DBNAME> package just adds T4 scaffolding templates for specific database.
If you need scaffolding for multiple databases, it is recommended to use linq2db.t4models packages with all templates included.

**Comment by koujiangheng** [comment]
im using dot net core 3.1, under windows7 project is good, but i switch to mac, the exception happens.
```
Unhandled exception. MySql.Data.MySqlClient.MySqlException (0x80004005): Authentication method 'caching_sha2_password' not supported by any of the available plugins.
   at MySql.Data.MySqlClient.Authentication.AuthenticationPluginManager.GetPlugin(String method)
   at MySql.Data.MySqlClient.Authentication.MySqlAuthenticationPlugin.GetPlugin(String method, NativeDriver driver, Byte[] authData)
   at MySql.Data.MySqlClient.NativeDriver.Authenticate(String authMethod, Boolean reset)
   at MySql.Data.MySqlClient.NativeDriver.Open()
   at MySql.Data.MySqlClient.Driver.Open()
   at MySql.Data.MySqlClient.Driver.Create(MySqlConnectionStringBuilder settings)
   at MySql.Data.MySqlClient.MySqlPool.CreateNewPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.GetPooledConnection()
   at MySql.Data.MySqlClient.MySqlPool.TryToGetDriver()
   at MySql.Data.MySqlClient.MySqlPool.GetConnection()
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at LinqToDB.Async.AsyncDbConnection.Open()
   at LinqToDB.Data.DataConnection.EnsureConnection()
   at LinqToDB.Data.DataConnection.get_Connection()
   at LinqToDB.Data.DataConnection.CreateCommand()
   at LinqToDB.Data.DataConnection.get_Command()
   at LinqToDB.DataProvider.DataProviderBase.InitCommand(DataConnection dataConnection, CommandType commandType, String commandText, DataParameter[] parameters, Boolean withParameters)
   at LinqToDB.Data.DataConnection.InitCommand(CommandType commandType, String sql, DataParameter[] parameters, List`1 queryHints, Boolean withParameters)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.ExecuteElement[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass23_0`1.<SetRunQuery>b__0(IDataContext db, Expression expr, Object[] ps)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at Linq2RetroSpy.Program.Main(String[] args) in /Users/xiaojiuwo/Desktop/Linq2RetroSpy/Program.cs:line 18
```
Do you know how to fix this?

**Comment by MaceWindu** [comment]
You need to update MySql.Data dependency to latest v8 https://www.nuget.org/packages/MySql.Data/8.0.19

`linq2db.mysql` references lower version by default, which doesn't support this auth method

**Comment by MaceWindu** [comment]
But personally, I would recommend to use [MySqlConnector](https://www.nuget.org/packages/MySqlConnector/) provider - it's more modern and doesn't have ton of bugs MySql.Data has.

**Comment by koujiangheng** [comment]
Thank you very much. Another question: So you mean after i added linq2db, i should add sqlite nuget and mysql nuget?

**Comment by MaceWindu** [comment]
Yes, if you use `linq2db` package, you need to reference specific ado.net provider (nobody will be happy if we reference like 10 providers when they need only one specific).
For `linq2db.<db_name>` packages we reference provider (if it is available from nuget), but it could reference a bit old provider version, so it is still recommended to update it.

**Comment by koujiangheng** [comment]
OK, thank you again, linq2db is an amazing project!!!! When i start use it, i feel the great power of linq2db.
