### ISSUE TITLE
System.Runtime.InteropServices.COMException: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED)

### ISSUE THREAD

**Issue by Scratch-net** [linq2db/linq2db#209]
This happens when I create a connection. What could be a reason?

System.TypeInitializationException: The type initializer for 'LinqToDB.Data.DataConnection' threw an exception. ---> System.Runtime.InteropServices.COMException: Catastrophic failure (Exception from HRESULT: 0x8000FFFF (E_UNEXPECTED))
   at System.Security.Policy.PEFileEvidenceFactory.GetLocationEvidence(SafePEFileHandle peFile, SecurityZone& zone, StringHandleOnStack retUrl)
   at System.Security.Policy.PEFileEvidenceFactory.GenerateLocationEvidence()
   at System.Security.Policy.PEFileEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.AssemblyEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.GetHostEvidence(Type type, Boolean markDelayEvaluatedEvidenceUsed)
   at System.Security.Policy.AppDomainEvidenceFactory.GenerateEvidence(Type evidenceType)
   at System.Security.Policy.Evidence.GenerateHostEvidence(Type type, Boolean hostCanGenerate)
   at System.Security.Policy.Evidence.GetHostEvidenceNoLock(Type type)
   at System.Security.Policy.Evidence.RawEvidenceEnumerator.MoveNext()
   at System.Security.Policy.Evidence.EvidenceEnumerator.MoveNext()
   at System.Configuration.ClientConfigPaths.GetEvidenceInfo(AppDomain appDomain, String exePath, String& typeName)
   at System.Configuration.ClientConfigPaths.GetTypeAndHashSuffix(AppDomain appDomain, String exePath)
   at System.Configuration.ClientConfigPaths..ctor(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigPaths.GetPaths(String exePath, Boolean includeUserConfig)
   at System.Configuration.ClientConfigurationHost.RequireCompleteInit(IInternalConfigRecord record)
   at System.Configuration.BaseConfigurationRecord.GetSectionRecursive(String configKey, Boolean getLkg, Boolean checkPermission, Boolean getRuntimeObject, Boolean requestIsHere, Object& result, Object& resultRuntimeObject)
   at System.Configuration.BaseConfigurationRecord.GetSection(String configKey)
   at System.Configuration.ClientConfigurationSystem.System.Configuration.Internal.IInternalConfigSystem.GetSection(String sectionName)
   at System.Configuration.ConfigurationManager.GetSection(String sectionName)
   at LinqToDB.Configuration.LinqToDBSection.get_Instance() in i:\linq2db\Source\Configuration\LinqToDBSection.cs:line 33
   at LinqToDB.Data.DataConnection..cctor() in i:\linq2db\Source\Data\DataConnection.cs:line 235
   --- End of inner exception stack trace ---
   at LinqToDB.Data.DataConnection..ctor()

**Comment by igor-tkachev** [comment]
Can you open connection directly without linq2db?

**Comment by scratch-net** [comment]
@igor-tkachev Yes, other apps work with this SQL server instance fine

**Comment by igor-tkachev** [comment]
Do you use FW 4.0 and partial trust environment?

**Comment by scratch-net** [comment]
I use .Net Framework 4.0 and connection string is "Persist Security Info=False;database={DATABASE_NAME};server=.\SQL2012;Current Language=English;Connection Timeout=240;Trusted_Connection=true"

Programs are run by user, who has 'public' and 'sysadmin' roles

**Comment by sdanyliv** [comment]
@Scratch-net, Is this still an issue?

**Comment by Scratch-net** [comment]
sure not, I even don't write .net any more )
