### ISSUE TITLE
Problem with [NotMapped] property

### ISSUE THREAD

**Issue by Marka83** [linq2db/linq2db#2097]
Hi All,

First of all I would like to say that linq2db is amazing product.
After numerous problems with EF Core your library is really refreshing.

I just have one issue from migrating to linq2db. This query throws exception for specific data:
```cs
var l = _context.CreateLinqToDbConnection();
            var s = from c in l.GetTable<C>()
                    join b in l.GetTable<B>() on c.BId equals b.BId into cbx
                    from cb in cbx.DefaultIfEmpty()
                    join a in l.GetTable<A>() on cb.AId equals a.AId into ba
                    from u in ba.DefaultIfEmpty()
                    select new C()
                    {
                        CId = c.CId,
                        BId = c.BId,
                        B = new B()
                        {
                            BId = cb.BId,
                            AId = cb.AId,
                            Text = cb.Text,
                            Test=cb.Test,
                            A = u
                        }
                    };
```
```
Exception message:
"Object reference not set to an instance of an object."
Stack trace:
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__10`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```

### Steps to reproduce
I'm using sql server 2016. This is a script to create tables and populate data:
```sql
CREATE TABLE [dbo].[A](
	[AId] [int] NOT NULL,
	[X] [varchar](50) NULL,
 CONSTRAINT [PK_A] PRIMARY KEY CLUSTERED 
(
	[AId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

CREATE TABLE [dbo].[B](
	[BId] [int] NOT NULL,
	[AId] [int] NOT NULL,
	[Text] [varchar](50) NULL,
 CONSTRAINT [PK_B] PRIMARY KEY CLUSTERED 
(
	[BId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
CREATE TABLE [dbo].[C](
	[CId] [int] NOT NULL,
	[BId] [int] NULL,
	[Z] [varchar](50) NULL,
 CONSTRAINT [PK_C] PRIMARY KEY CLUSTERED 
(
	[CId] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
GO

INSERT [dbo].[A] ([AId], [X]) VALUES (1, N'dsf')
GO
INSERT [dbo].[B] ([BId], [AId], [Text]) VALUES (1, 1, N'sdf')
GO
INSERT [dbo].[B] ([BId], [AId], [Text]) VALUES (2, 1, N'sdf')
GO
INSERT [dbo].[C] ([CId], [BId], [Z]) VALUES (1, 1, N'dsf')
GO
INSERT [dbo].[C] ([CId], [BId], [Z]) VALUES (2, 2, N'dfr')
GO
INSERT [dbo].[C] ([CId], [BId], [Z]) VALUES (3, NULL, N'rrr')
GO
```
```c#
[Table("A", Schema = "dbo")]
    public class A
    {
        [Key]
        public int? AId { get; set; }
        public string X { get; set; }

        [NotMapped]
        public bool? Test { get; set; }
    }

[Table("B", Schema = "dbo")]
    public class B
    {
        [Key]
        public int? BId { get; set; }
        public int? AId { get; set; }
        public string Text { get; set; }
        [ForeignKey("AId")]
        public A A { get; set; }

        [NotMapped]
        public bool? Test { get; set; }
    }

[Table("C", Schema = "dbo")]
    public class C
    {
        [Key]
        public int? CId { get; set; }
        public int? BId { get; set; }

        public string Z { get; set; }

        [ForeignKey("BId")]
        public B B { get; set; }
    }
```
Problematic query is in title.

This query used to work in Entity Framework 2.2 but on 3.1 throws similar exception.
If you comment [NotMapped] properties everything works fine.
I also tried on .Net Core 3.1 and linq2sql 2.0.4 but it throws me same error (at least on real query, this one is simplification just to reproduce the issue)

### Environment details
linq2db version: linq2db.EntityFrameworkCore  1.7.1
Database Server: Sql Server 2016
Database Provider: Microsoft Sql Server
Operating system: Windows 10
.NET Framework: .Net Core 2.2

**Comment by sdanyliv** [comment]
`cb` can be null and you do not handle this. 
I think part `Test=cb.Test` generates exception. Rewrite to `Test = cb != null ? cb.Test : null`.
Because it is not mapped, no special code for handling null values is generated.

I don't know how to treat such situation. As a bug or feature :)

**Comment by Marka83** [comment]
Thank you very much,
that solved the problem. 
It would be nice to have a general handling, but now I know how to handle it.

**Comment by sdanyliv** [comment]
Looking into. Maybe it is possible with small efforts.

**Comment by Marka83** [comment]
I believe there is error in fix in
Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs line 3119.
I think you're missing some parentheses.

When do you plan to release 2.9.7 version?

**Comment by sdanyliv** [comment]
Looking into my PR and I think I have fixed this correctly, no parentheses missed. `DefaultValueExpression` should be treated as an NULL.

> When do you plan to release 2.9.7 version?

Possibly next Thursday

**Comment by Marka83** [comment]
Sorry, you're right. Had to remind myself of operator precedence :) 
Thanks for the info.
