### ISSUE TITLE
Insufficient sub query optimization with group statement for Sql Server

### ISSUE THREAD

**Issue by iremezoff** [linq2db/linq2db#2105]
Optimization for sub query works insufficient when the sub query contains group by statement. It works fine for SQLite database because this dbms allows thhat kind of query but on Sql Server it causes invalid sql query.

Here is the raised exception
```
Exception: System.Data.SqlClient.SqlException
Message  : Column 'Entities.Id' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
```

### Steps to reproduce

```c#
using System;
using System.Diagnostics;
using System.Linq;
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.DataProvider.SqlServer;
using LinqToDB.Mapping;

namespace Linq2DbGroupSubQueryBug
{
  class Program
  {
    static void Main(string[] args)
    {
      DataConnection.AddConfiguration("mssql", "Data Source=.;Initial Catalog=db;Integrated Security=True", new SqlServerDataProvider("mssql", SqlServerVersion.v2017));
      DataConnection.TraceSwitch.Level = TraceLevel.Verbose;
      DataConnection.WriteTraceLine    = (s, s1) => Trace.WriteLine(s);
      DataConnection.DefaultConfiguration = "mssql";

      using var db = new DataConnection();

      var query = db.GetTable<Entity>().GroupBy(x => x.Firstname); // generate valid query

      var resultQuery = query.AsSubQuery().Select(x=>new { Count = Sql.Ext.Count().ToValue() }); // omit defined in group by statement columns and substitute asterisk instead of them

      var data = resultQuery.ToList();
    }
  }

  [Table("Entities", IsColumnAttributeRequired = false)]
  public class Entity
  {
    [PrimaryKey]
    public string Id { get; set; }
    public string Firstname { get; set; }
  }
}

```

Here is invalid generated sql query:
```sql
SELECT
	COUNT(*)
FROM
	(
		SELECT
			*
		FROM
			[Entities] [t1]
		GROUP BY
			[t1].[Firstname]
	) [x]
```
As you can see, using asterisk is not allowed in a query for SQL Server.
Only workaround I've found and used is to add aggregation on any field from subquery into external wrapping query like this:
```c#
var resultQuery = query.AsSubQuery().Select(x=>new { Count = Sql.Ext.Count().ToValue(), Name = Sql.Ext.Count(x.Key).ToValue() });
```
Of course it leads to redundant code (in the example above a simple variant is shown).

### Environment details
linq2db version: 2.9.6
Database Server: Sql Server 2017
Database Provider: Sql Server
Operating system: win64
.NET Framework: .net core 2.1/3.1

**Comment by sdanyliv** [comment]
Hm, why do you use AsSubquey here? It is low level function for people who knows how to generate SQL and it definitely will not work with grouping.

**Comment by iremezoff** [comment]
> 
> 
> Hm, why do you use AsSubquey here? It is low level function for people who knows how to generate SQL and it definitely will not work with grouping.

It's a way to get single result row. In the starting ticket only simple example is presented but in real application it's more complex and contains several aggregation results but in rare cases aggregation result contains only Count. Why I've chosen this way because base query (`query variable in the example`) is composed one time and used as shared for next several derived queries.

**Comment by sdanyliv** [comment]
Show me your real query. I know why I have introduced AsSubquery and it is not case for that.
Anyway I'll check what happened.

**Comment by iremezoff** [comment]
@sdanyliv 
```c#
var baseQuery = data.GroupBy(x=> new GroupByObject{Id = x.Id, Name = x.Name, Period = x.Period});
var selector = Expression.Lambda<Func<Entity, SummaryEntity>>(Expression.New(typeof(SummaryEntity)), ColumnsConfiguration.Parameters.Item);
var summaryQuery = baseQuery.AsSubQuery().Select(selector);
var summary = summaryQuery .ToSingleAsync();
var result = baseQuery.ToListAsync();
```

I'd like to remind that it works well when there are more fields in wrapping query than just Count aggregation. It's rare case nevertheless it occurs.

**Comment by sdanyliv** [comment]
Show me the result query with more aggregations.

**Comment by iremezoff** [comment]
@sdanyliv 
```c#
var resultQuery = query.AsSubQuery().Select(x=>new { Count = Sql.Ext.Count().ToValue(), Name = Sql.Ext.Count(x.Key).ToValue() });
```

```sql
SELECT
	COUNT(*),
	COUNT([x].[Firstname])
FROM
	(
		SELECT
			[t1].[Firstname]
		FROM
			[Entities] [t1]
		GROUP BY
			[t1].[Firstname]
	) [x]
```

**Comment by sdanyliv** [comment]
Strange query, I hope you know what are you defining. I'll check how to fix that.
Anyway you can use Distinct instead of GroupBy
```cs
var query = db.GetTable<Entity>()
   .Select(x => x.Firstname)
   .Distinct();

var resultQuery = query.Select(x => new { Count = Sql.Ext.Count().ToValue(), Name = Sql.Ext.Count(x.Key).ToValue() });
```

**Comment by iremezoff** [comment]
@sdanyliv 
btw, I figured out with the issue in another way which satisfies my purposes.
Here it is:
```c#
var resultQuery = query.AsSubQuery().Select(x=>new { Count = Sql.Ext.Count(x.Key).ToValue() });
```
Yeah, it looks same as yours.

**Comment by sdanyliv** [comment]
I think we have to create special `AsSubQuery` overload which hides grouping details and return Key's IQueryable.
```cs
public static IQueryable<TKey> AsSubQuery<TKey, TElement>(this IQueryable<IGrouping<TKey, TElement>> grouping)
{
   ...
}
```
