### ISSUE TITLE
Sequential access does not work with calculations in new clause

### ISSUE THREAD

**Issue by hardhub** [linq2db/linq2db#2116]
Exception when querying using option CommandBehavior.SequentialAccess.  

```
Exception message:

System.InvalidOperationException: Invalid attempt to read from column ordinal '0'.  With CommandBehavior.SequentialAccess, you may only read from column ordinal '2' or greater.

Stack trace:

   at System.Data.SqlClient.SqlDataReader.CheckDataIsReady(Int32 columnIndex, Boolean allowPartiallyReadColumn, Boolean permitAsync, String methodName)
   at System.Data.SqlClient.SqlDataReader.TryReadColumn(Int32 i, Boolean setTimeout, Boolean allowPartiallyReadColumn)
   at System.Data.SqlClient.SqlDataReader.GetString(Int32 i)
   at lambda_method(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.<ExecuteQueryAsync>d__11`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.AsyncExtensions.<ToListAsync>d__6`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Maintenance.Queries.Job.<Execute>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.GetResult()
   at Maintenance.Queries.Program.<Main>d__0.MoveNext()
```

```c#
using (Storage storage = new Storage())
            {
                var accounts = from account in storage.Accounts
                               select new
                               {
                                   Name = account.Name,
                                   Surname = account.Surname,
                                   Fullname = $"{account.Name} {account.Surname}"
                               };


                var result = await accounts.ToListAsync();

                var data = result.First();

                Console.WriteLine($"{data.Name} {data.Surname}");
            }
```

### Environment details
linq2db version: compiled from master on date of this issue
Database Server: SQL Server 2014

--

## Reason and solution

I think it is limitation of SQL Server client or even ADO.Net at all (but other DB are not tested).  
The reason is related to multiple attempts to access the same value (but it cannot be done in sequential mode).  

If you profile SQL query it will be like this one:

```sql
SELECT
	[account].[Name],
	[account].[Surname]
FROM
	[dbo].[Account] [account]
```

So in reality it gets only one value from database and it makes sense.  
But it is mistake to access value multiple times with reader.GetValue(column).  
Instead it should be cached, so value once read with GetValue should be available in memory while it is needed.  
It will solve a lot of troubles and will provide correct work in all modes.

**Comment by sdanyliv** [comment]
@hardhub, it is critical for you now? I'm asking because i want to move this issue to 3.0, not a trivial changes.

**Comment by hardhub** [comment]
@sdanyliv It depends on release date of 3.0. How soon do you plan 3.0 as beta at least?

All is around this issue: https://github.com/linq2db/linq2db/issues/1185

I had to remove sequential access temporarily as workaround. But it drastically slows fetching binary data from database.

So in general the issue is critical because combination of binary columns, calculation in fields and sequential access do not allow me to develop desired functionality.

For this moment I can try avoid such combination, but I will finally stuck with this limitation in very close future.

**Comment by hardhub** [comment]
Still no updates on this?

**Comment by MaceWindu** [comment]
@hardhub, I'm looking into it. One thing is not clear to me is what profit you expect to get from sequential access if data row is anyway mapped to some entity class (fancy version of row)?
Main profit of sequential access is that data provider don't need to allocate memory for whole row and could just stream data to consumer. But when ORM used, memory is still allocated by ORM to materialize result object.

**Comment by hardhub** [comment]
@MaceWindu All that was made in attempt to workaround ADO.Net issue with performance during reading byte[] in async way:

![image](https://user-images.githubusercontent.com/4306334/100405572-ea4a2780-3074-11eb-9a66-50d974d91212.png)

There are a lot of discussions on stackoverflow and in SqlClient issues.
