### ISSUE TITLE
The command execution cannot proceed due to a pending asynchronous operation already in progress.

### ISSUE THREAD

**Issue by quan01994** [linq2db/linq2db#2122]
The same piece of code was successful the first time it was run, but when I went to run it again, this error would pop up. I do n’t know where my writing is wrong.

````
2020-03-05 11:21:45.465 +08:00 [ERR] 导购确认到达出错
System.InvalidOperationException: The command execution cannot proceed due to a pending asynchronous operation already in progress.
   at System.Data.SqlClient.SqlCommand.ValidateAsyncCommand()
   at System.Data.SqlClient.SqlCommand.BeginExecuteNonQuery(AsyncCallback callback, Object stateObject)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncImpl(Func`3 beginMethod, Func`2 endFunction, Action`1 endAction, Object state, TaskCreationOptions creationOptions)
   at System.Threading.Tasks.TaskFactory`1.FromAsync(Func`3 beginMethod, Func`2 endMethod, Object state)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location where exception was thrown ---
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.Async.cs:line 224
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Data\DataConnection.QueryRunner.cs:line 531
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, CancellationToken cancellationToken) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.cs:line 776
   at LinqToDB.Linq.QueryRunner.Insert`1.QueryAsync(IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, CancellationToken token) in C:\projects\linq2db\Source\LinqToDB\Linq\QueryRunner.Insert.cs:line 93
   at Hyw.Api.EmpWxApp.Application.MemberExchange.MemberExchangeService.CreateMemberExchangeProcessAsync(String flowNo, String exchangeApplyDesc, String exchangeApplyRemark, Int32 exchangeApplyStatus) in D:\RiderProjects\Hyw.Api.EmpWxApp\src\Hyw.Api.EmpWxApp\Application\MemberExchange\MemberExchangeService.cs:line 355
   at Hyw.Api.EmpWxApp.Application.MemberExchange.MemberExchangeService.ConfirmArrivalAsync(Int32 flowId, EmployeeInfoDto employee) in D:\RiderProjects\Hyw.Api.EmpWxApp\src\Hyw.Api.EmpWxApp\Application\MemberExchange\MemberExchangeService.cs:line 256
````

it's my di code
````csharp
 LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
 services.AddScoped<IDbContextProvider, DbContextProvider>();
````

````csharp

    public interface IDbContextProvider : IDisposable
    {
        HywCrmDbContext DbContext { get; }
        string CompanyId { get; set; }
        string ConnectionString { get; set; }
    }

 public sealed class DbContextProvider : IDbContextProvider
    {
        private bool _disposed;
        private string _companyId;
        private string _connectionString;

        public void Dispose()
        {
            Dispose(true);
            GC.SuppressFinalize(this);
        }

        private void Dispose(bool disposing)
        {
            if (_disposed)
                return;

            if (disposing)
            {
                _companyId = null;
                DbContext?.Dispose();
            }

            _disposed = true;
        }

        public HywCrmDbContext DbContext { get; private set; }

        public string CompanyId
        {
            get => _companyId;
            set
            {
                //如果原来是空的 那么就可以设置
                if (string.IsNullOrWhiteSpace(_companyId))
                {
                    _companyId = value;
                    DbContext = new HywCrmDbContext(_companyId);
                }
            }
        }


        public string ConnectionString
        {
            get
            {
                if (string.IsNullOrWhiteSpace(_connectionString))
                {
                    var connectionString = new MySettings().ConnectionStrings.SingleOrDefault(m => m.Name == _companyId)
                        ?.ConnectionString;
                    _connectionString = connectionString;
                }

                return _connectionString;
            }
            set => DbContext = new HywCrmDbContext(ProviderName.SqlServer2008, value);
        }
    }

 public class MySettings : ILinqToDBSettings
    {
        public IEnumerable<IDataProviderSettings> DataProviders => Enumerable.Empty<IDataProviderSettings>();

        public string DefaultConfiguration => "SqlServer";
        public string DefaultDataProvider => "SqlServer";

        public IEnumerable<IConnectionStringSettings> ConnectionStrings
        {
            get
            {
                yield return
                    new ConnectionStringSettings
                    {
                        Name = "Hyw",
                        ProviderName = ProviderName.SqlServer2008,
                        ConnectionString = "server=######;database=HYW.CRM;uid=sa;pwd=#####;MultipleActiveResultSets=True"
                    };
            }
        }
````

it's my code
````csharp
 using (var transaction = Db.BeginTransaction())
            {
                try
                {
                    var affectRows = Db.MemberExchangeFlows
                        .Where(m => m.FlowId == flowId)
                        .Set(m => m.ExchangeApplyStatus, 3)
                        .Set(m => m.LastUpdateTime, DateTime.Now)
                        .Set(m => m.ExchangeEmpName, employee.EmpName)
                        .Set(m => m.ExchangeEmpCode, employee.EmpCode)
                        .Set(m => m.ExchangeApplyRemark, "")
                        .UpdateAsync();
                    //创建兑换流程记录表
                    await CreateMemberExchangeProcessAsync(memberExchangeDetailDto.FlowNo, "导购确认到货", "导购确认到货", 3);
                    transaction.Commit();
                    return ActionResponse.Success();
                }
                catch (Exception e)
                {
                    _logger.LogError(e, "导购确认到达出错");
                    transaction.Rollback();
                    return ActionResponse.Fail("导购确认到货出错");
                }
            }

        public async Task CreateMemberExchangeProcessAsync(string flowNo, string exchangeApplyDesc,
            string exchangeApplyRemark, int exchangeApplyStatus)
        {
            var now = DateTime.Now;
            // 创建兑换过程
            var memberExchangeProcess = new MemberExchangeProcessEntity
            {
                ExchangeFlowNo = flowNo,
                CreateTime = now,
                CreateUser = "Admin",
                ExchangeApplyDesc = exchangeApplyDesc,
                ExchangeApplyRemark = exchangeApplyRemark,
                ExchangeApplyStatus = exchangeApplyStatus,
                LastUpdateTime = now,
                LastUpdateUser = "Admin",
                Status = 0
            };
// this code throw exception
// MemberExchangeService.cs:line 355
            await Db.InsertAsync(memberExchangeProcess);
        }
````

**Comment by quan01994** [comment]
Is an error on my code 。。。。
````csharp
//no await 
 var affectRows = Db.MemberExchangeFlows  No wait
````
