### ISSUE TITLE
DataProvider 'PostgreSQL' not found.  in Core 3.1 project

### ISSUE THREAD

**Issue by BAndy18ru** [linq2db/linq2db#2135]
Installed Packs:
"linq2db" Version="2.9.7" 
"linq2db.PostgreSQL" Version="2.9.7" 
"linq2db.SQLite" Version="2.9.7" 
"linq2db.SqlServer" Version="2.9.7" 
"Npgsql" Version="4.1.3.1" 

Problem only with PostgreSQL
SqlServer, SQLite working fine

```
Exception message:
DataProvider 'PostgreSQL' not found.
Stack trace:
   at LinqToDB.Data.DataConnection..ctor(String providerName, String connectionString)
   at BAnalytics.Models.DbRockDB..ctor() in C:\Ultimate\BAnalytics\BAnalytics\Models\DbRockDB.cs:line 14
   at BAnalytics.Services.DataSourceService.Test() in C:\Ultimate\BAnalytics\BAnalytics\Services\DataSourceService.cs:line 42
   at BAnalytics.Services.DataSourceService..ctor(DashboardsDB context, IMemoryCache memoryCache) in C:\Ultimate\BAnalytics\BAnalytics\Services\DataSourceService.cs:line 35
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSiteMain(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitRootCache(ServiceCallSite singletonCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2.VisitCallSite(ServiceCallSite callSite, TArgument argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.DynamicServiceProviderEngine.<>c__DisplayClass1_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngine.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.Extensions.DependencyInjection.ServiceProviderServiceExtensions.GetService[T](IServiceProvider provider)
   at BAnalytics.Updater.Startup.Configure(IApplicationBuilder app, IWebHostEnvironment env) in C:\Ultimate\BAnalytics\BAnalytics\Startup.cs:line 91
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.Invoke(Object instance, IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.ConfigureBuilder.<>c__DisplayClass4_0.<Build>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass13_0.<UseStartup>b__2(IApplicationBuilder app)
   at Microsoft.AspNetCore.Mvc.Filters.MiddlewareFilterBuilderStartupFilter.<>c__DisplayClass0_0.<Configure>g__MiddlewareFilterBuilder|0(IApplicationBuilder builder)
   at DevExpress.Web.Internal.ConfigurationSettings.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder builder)
   at Microsoft.AspNetCore.Server.IIS.Core.IISServerSetupFilter.<>c__DisplayClass2_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.HostFilteringStartupFilter.<>c__DisplayClass0_0.<Configure>b__0(IApplicationBuilder app)
   at Microsoft.AspNetCore.Hosting.GenericWebHostService.<StartAsync>d__31.MoveNext()
```

```c#
public partial class DbRockDB : LinqToDB.Data.DataConnection
{
    public DbRockDB()
           : base(LinqToDB.ProviderName.PostgreSQL, "Host=localhost;Port=5411;Database=db_rock;Username=postgres;Password=;")
    {
        InitDataContext();
        InitMappingSchema();
    }
}
```

### Environment details
linq2db version: *2.9.7*
Database Server: *PostgreSQL 10*
Database Provider: *PostgreSQL*
Operating system: *Win 10*
.NET Framework: *Core 3.1*

**Comment by MaceWindu** [comment]
This constructor expects provider to be registered by specified name, but we don't register PostgreSQL provider using this name. You should specify dialect version (PostgreSQL92, PostgreSQL93 or PostgreSQL95). So it your case (pgsql 10) it will be PostgreSQL95

**Comment by MaceWindu** [comment]
We don't plan to change it for 2.x version, but it was already refactored in v3 branch, so I will assign it to 3.0 milestone to retest that it works there.

**Comment by MaceWindu** [comment]
Retested. Confirm it works with preview2
