### ISSUE TITLE
Duplicate Columns in Mysql views

### ISSUE THREAD

**Issue by MirandaBrazil** [linq2db/linq2db#218]
I have this view

```sql
select `sgm_cliente`.`endereco_cidade`.`Nome` AS `XNome` 
from `sgm_cliente`.`endereco_cidade` 
where (`sgm_cliente`.`endereco_cidade`.`UF` = 'MG')
```

Other tables load columns correctly but all views have this bug

When i run generation tool i get :

<code>
Error	28	Running transformation: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.VisualStudio.TextTemplating7205F2CF06DFC46AEDC93CDF3FB4A7E4D17F7DB4362EA45EBA2DA254478CFAEDB2DA83F003F1371692E20B4E563B25ED68AB52831FBD8D198C29511D2C4276C0.GeneratedTextTransformation.<LoadServerMetadata>b__79(TableSchema t) in c:\Workspace\Silveira\Modules\Silveira.Data\LinqToDB.Templates\DataModel.ttinclude:line 72
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplating7205F2CF06DFC46AEDC93CDF3FB4A7E4D17F7DB4362EA45EBA2DA254478CFAEDB2DA83F003F1371692E20B4E563B25ED68AB52831FBD8D198C29511D2C4276C0.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in c:\Workspace\Silveira\Modules\Silveira.Data\LinqToDB.Templates\DataModel.ttinclude:line 70
   at Microsoft.VisualStudio.TextTemplating7205F2CF06DFC46AEDC93CDF3FB4A7E4D17F7DB4362EA45EBA2DA254478CFAEDB2DA83F003F1371692E20B4E563B25ED68AB52831FBD8D198C29511D2C4276C0.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in c:\Workspace\Silveira\Modules\Silveira.Data\LinqToDB.Templates\DataModel.ttinclude:line 280
   at Microsoft.VisualStudio.TextTemplating7205F2CF06DFC46AEDC93CDF3FB4A7E4D17F7DB4362EA45EBA2DA254478CFAEDB2DA83F003F1371692E20B4E563B25ED68AB52831FBD8D198C29511D2C4276C0.GeneratedTextTransformation.LoadMySqlMetadata(String server, String database, String uid, String password) in c:\Workspace\Silveira\Modules\Silveira.Data\LinqToDB.Templates\LinqToDB.MySql.ttinclude:line 28
   at Microsoft.VisualStudio.TextTemplating7205F2CF06DFC46AEDC93CDF3FB4A7E4D17F7DB4362EA45EBA2DA254478CFAEDB2DA83F003F1371692E20B4E563B25ED68AB52831FBD8D198C29511D2C4276C0.GeneratedTextTransformation.TransformText() in c:\Workspace\Silveira\Modules\Silveira.Data\CopyMe.MySql.tt:line 38	c:\Workspace\Silveira\Modules\Silveira.Data\LinqToDB.Templates\DataModel.ttinclude	72	1	Silveira.Data
</code>

And this is the column duplicated value

![image](https://cloud.githubusercontent.com/assets/1939153/7664673/6551e82a-fb68-11e4-920d-ebc183ea94af.png)

**Comment by MirandaBrazil** [comment]
For a temporary fix i changed DataModel.ttinclude in line 91 :

Before :
```
Columns                 = t.Columns.ToDictionary(...
```
After :
```
Columns                 = t.Columns.GroupBy(i => i.ColumnName,(key, group) => group.First()).ToDictionary(...
```
