### ISSUE TITLE
How can I add support for Enum.HasFlag?

### ISSUE THREAD

**Issue by Nevca** [linq2db/linq2db#2189]
I tried adding support for Enum.HasFlag method to linq2db like follows:

`LinqToDB.Linq.Expressions.MapMember((Enum e, Enum e2) => e.HasFlag(e2), (Expression<Func<Enum, Enum, bool>>)((t, flag) => (Sql.ConvertTo<int>.From(t) & Sql.ConvertTo<int>.From(flag)) != 0));`

I'm getting the following exception when executing this: `Expression of type 'MyEnum' cannot be used for parameter of type 'System.Enum' of method 'Int32 From[Enum](System.Enum)`

I'm not sure if I'm doing it right or this is a bug.

```
Exception message: `Expression of type 'MyEnum' cannot be used for parameter of type 'System.Enum' of method 'Int32 From[Enum](System.Enum)`
Stack trace: `   at System.Linq.Expressions.Expression.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arg, ParameterInfo pi)
   at System.Linq.Expressions.Expression.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments)
   at System.Linq.Expressions.Expression.Call(Expression instance, MethodInfo method, IEnumerable`1 arguments)
   at LinqToDB.Expressions.Extensions.TransformX(BinaryExpression e, Func`2 func) in d:\a\1\s\Source\LinqToDB\Expressions\Extensions.cs:line 1315
   at LinqToDB.Expressions.Extensions.TransformX(BinaryExpression e, Func`2 func) in d:\a\1\s\Source\LinqToDB\Expressions\Extensions.cs:line 1315
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertMethod(MethodCallExpression pi, LambdaExpression lambda) in d:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 573
   at LinqToDB.Linq.Builder.ExpressionBuilder.<ConvertExpression>b__120_0(Expression e) in d:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 449
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in d:\a\1\s\Source\LinqToDB\Expressions\Extensions.cs:line 1369
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in d:\a\1\s\Source\LinqToDB\Expressions\Extensions.cs:line 1415
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving) in d:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 29
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in d:\a\1\s\Source\LinqToDB\Linq\Builder\WhereBuilder.cs:line 24
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in d:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 193
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in d:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 164
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in d:\a\1\s\Source\LinqToDB\Linq\Query.cs:line 301
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in d:\a\1\s\Source\LinqToDB\Linq\Query.cs:line 252
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in d:\a\1\s\Source\LinqToDB\Linq\ExpressionQuery.cs:line 85
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in d:\a\1\s\Source\LinqToDB\Linq\ExpressionQuery.cs:line 180
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)`
```

### Environment details
linq2db version: 3.0.0-preview1
Database Server: SQLite
Database Provider: SQLiteClassic
Operating system: Windows 10
.NET Framework: v4.8

**Comment by sdanyliv** [comment]
It will not work now. Will prepare patch for next release.

**Comment by MaceWindu** [comment]
#2190
