### ISSUE TITLE
NRE when jumping to next Associated table

### ISSUE THREAD

**Issue by Feroks** [linq2db/linq2db#2222]
I need to perform a custom join. In order to achieve it i am using Association that returns IQueryable and uses Take(1). 
I am able to query this association's properties, but i am getting an exception, when i am trying to access next Association. As a workaround i can use a Predicate, but then i am unable to perform additional custom logic inside the Join.

I have attached a simplified sample that describes the problem better.

```
Exception message: 
System.NullReferenceException: Object reference not set to an instance of an object.
Stack trace:
at LinqToDB.Linq.Builder.TableBuilder.AssociatedTableContext..ctor(ExpressionBuilder builder, TableContext parent, AssociationDescriptor association, Boolean forceLeft, Boolean asSubquery)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.<GetAssociation>b__78_6(AssociationDescriptor a)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.GetAssociation(Expression expression, Int32 level)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.GetAssociation(Expression expression, Int32 level)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.FindTable(Expression expression, Int32 level, Boolean throwException, Boolean throwExceptionForNull)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildExpression(Expression expression, Int32 level, ParameterExpression parentObject)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass79_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass79_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)

```

### Steps to reproduce
Create Association that returns IQueryable. Query this field and navigate to its association.

```c#
[TestFixture]
public class Issue : TestBase
{
	public class Entity
	{
		[Column]
		public int Id { get; set; }

		[Association(QueryExpressionMethod = nameof(Entity2LanguageExpr), CanBeNull = true, Relationship = Relationship.OneToOne)]
		public Entity2Language Entity2Language { get; set; }

		public static Expression<Func<Entity, IDataContext, IQueryable<Entity2Language>>> Entity2LanguageExpr()
		{
			return (e, db) => db
				.GetTable<Entity2Language>()
				.Where(x => x.EntityId == e.Id)
				.Take(1);
		}
	}

	public class Entity2Language
	{
		[Column]
		public int Id { get; set; }

		[Column]
		public int EntityId { get; set; }

		[Column]
		public int LanguageId { get; set; }

		[Association(ThisKey = nameof(LanguageId), OtherKey = nameof(Issue.Language.Id), CanBeNull = false, Relationship = Relationship.OneToOne)]
		public Language Language { get; set; }
	}

	public class Language
	{
		[Column]
		public int Id { get; set; }
		
		[Column]
		public string Name { get; set; }
	}

	[Test]
	public void SelectAssociations([IncludeDataSources(TestProvName.AllSqlServer)] string context)
	{
		using (var db = GetDataContext(context))
		using (db.CreateLocalTable(new[]
		{
			new Entity {Id = 1}
		}))
		using (db.CreateLocalTable(new[]
		{
			new Entity2Language {Id = 1, EntityId = 1, LanguageId = 1}
		}))
		using (db.CreateLocalTable(new[]
		{
			new Language {Id = 1, Name = "English"}
		}))
		{
			var value = db
				.GetTable<Entity>()
				.Select(x => new
				{
					// This works
					EntityId = x.Id,
					x.Entity2Language.LanguageId,
					// This caused exception
					LanguageName = x.Entity2Language.Language.Name
				})
				.First();
			
			Assert.AreEqual(1, value.EntityId);
			Assert.AreEqual(1, value.LanguageId);
			Assert.AreEqual("English", value.LanguageName);
		}
	}
}
```

### Environment details
linq2db version: 3.0.0-preview2
Database Server: SQL Server
Database Provider: SqlServer
Operating system: Windows 10
.NET Framework: 4.6.2

**Comment by sdanyliv** [comment]
Thanks. Will add this test.
In upcoming version we have refactored associations mechanism. If you have possibility please check your test against this branch https://github.com/linq2db/linq2db/pull/2198

**Comment by Feroks** [comment]
Thank you for a quick response.
I have tried it on the branch you have mentioned. Works perfectly there. You can close this issue. 😄 

P.S. I have slightly updated the test to make it more meaningful.

**Comment by sdanyliv** [comment]
Test added. Thanks for your contribution.
