### ISSUE TITLE
Recursive CTE with entity as property results in 'circular reference' error

### ISSUE THREAD

**Issue by majbo** [linq2db/linq2db#2264]
I want to read the entire entity together with the hierarchical information. Therefor my CTE class contains a property named 'Entity'. SQLite won't execute the generated SQL with the following error: 

```
Exception message: SQLite Error 1: 'circular reference: FolderCTE'.
Stack trace: Microsoft.Data.Sqlite.SqliteException : SQLite Error 1: 'circular reference: FolderCTE'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db)
   at Microsoft.Data.Sqlite.SqliteCommand.PrepareAndEnumerateStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteCommand.GetStatements(Stopwatch timer)+MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber)+MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Test.EntityApp.QueryOptionRecursiveTests.RecursiveTest()
```

### Steps to reproduce

You can find a small demonstration here: [LinqToDbCteDemo](https://github.com/majbo/LinqToDbCteDemo)

```c#
    class CteEntity<TEntity> where TEntity : class
    {
        public TEntity Entity { get; set; } = null!;
        public Guid Id { get; set; }
        public Guid? ParentId { get; set; }
        public int Level { get; set; }
        public string Label { get; set; } = null!;
    }

    class TestFolder
    {
    	public Guid Id { get; set; }
    	public string? Label { get; set; }
    	public TestFolder? Parent { get; set; }
    	public Guid? ParentId { get; set; }
    }

    await using var db = Context.CreateLinq2DbConnectionDetached();
    var ra = db.GetCte<CteEntity<TestFolder>>("CTE", cte =>
    {
    	return (Context.Set<TestFolder>()
    			.ToLinqToDBTable()
    			.Where(c => c.ParentId == null)
    			.Select(c =>
    				new CteEntity<TestFolder>() {Level = 0, Id = c.Id, ParentId = c.ParentId, Label = c.Label, Entity = c}))
    		.Concat(
    			Context.Set<TestFolder>()
    				.ToLinqToDBTable()
    				.SelectMany(c => cte.InnerJoin(r => c.ParentId == r.Id),
    					(c, r) => new CteEntity<TestFolder>
    					{
    						Level = r.Level + 1,
    						Id = c.Id,
    						ParentId = c.ParentId,
    						Label = r.Label + '/' + c.Label,
                                                Entity = c
    					})
    		);
    });
```

### Environment details
linq2db version: *2.9.8*
Database Server: *SQLite*
Database Provider: *Microsoft.Data.Sqlite*
Operating system: *Windows 10*
.NET Framework: *.Net Core 3.1*

**Comment by sdanyliv** [comment]
Can you post SQL here?

**Comment by majbo** [comment]
```
LinqToDB BeforeExecute
--  SQLite
WITH [FolderCTE]
(
	[Entity],
	[Id],
	[ParentId],
	[Level],
	[Label],
	[Entity_1]
)
AS
(
	SELECT
		[t1].[Label_1],
		[t1].[Id_2],
		[t1].[ParentId_2],
		[t1].[Level_1],
		[t1].[Label_2],
		[t1].[Entity]
	FROM
		(
			SELECT
				[c_1].[MetaId] as [Entity],
				[c_1].[Id] as [Id_1],
				[c_1].[ParentId] as [ParentId_1],
				[c_1].[Label] as [Label_1],
				[c_1].[Id] as [Id_2],
				[c_1].[ParentId] as [ParentId_2],
				0 as [Level_1],
				[c_1].[Label] as [Label_2]
			FROM
				[TestFolder] [c_1]
			WHERE
				[c_1].[ParentId] IS NULL
			UNION ALL
			SELECT
				NULL as [Entity],
				NULL as [Id_1],
				NULL as [ParentId_1],
				NULL as [Label_1],
				[c_2].[Id] as [Id_2],
				[c_2].[ParentId] as [ParentId_2],
				[r].[Level] + 1 as [Level_1],
				[r].[Label] || Cast('/' as VarChar(4000)) || [c_2].[Label] as [Label_2]
			FROM
				[TestFolder] [c_2]
					INNER JOIN [FolderCTE] [r] ON [c_2].[ParentId] = [r].[Id]
		) [t1]
)
SELECT
	[t2].[Entity_1],
	[t2].[Id],
	[t2].[ParentId],
	[t2].[Entity],
	[t2].[Level],
	[t2].[Label]
FROM
	[FolderCTE] [t2]
```

**Comment by sdanyliv** [comment]
Could you please run modified SQL? Maybe Sqlite requires `RECURSIVE` keyword. If yes, fix will be easy.
```sql
WITH RECURSIVE [FolderCTE]
...
```

**Comment by majbo** [comment]
I tried and it didn't change the error. You can find a small project with an example here: [LinqToDbCteDemo](https://github.com/majbo/LinqToDbCteDemo)

**Comment by sdanyliv** [comment]
Thanks for the sample. Will fix that ASAP.
Which version of EF Core do you use?

**Comment by majbo** [comment]
Surprisingly, the sample project works with only the following references: 

        <PackageReference Include="linq2db" Version="2.9.8" />
        <PackageReference Include="linq2db.EntityFrameworkCore" Version="2.0.5" />
        <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="3.1.5" />
        <PackageReference Include="Microsoft.NET.Test.Sdk" Version="16.5.0" />
        <PackageReference Include="xunit" Version="2.4.0" />
        <PackageReference Include="xunit.abstractions" Version="2.0.3" />
        <PackageReference Include="xunit.runner.visualstudio" Version="2.4.0" />
        <PackageReference Include="coverlet.collector" Version="1.2.0" />

(no EF.Core, just Microsoft.EntityFrameworkCore.Sqlite)

In my main application its Microsoft.EntityFrameworkCore 3.12

**Comment by sdanyliv** [comment]
Could you try to update linq2db.EntityFrameworkCore to latest version?

**Comment by majbo** [comment]
I tried it with `linq2db 3.0.0-rc.0` and `linq2db.EntityFrameworkCore 3.2.0` but no change.

**Comment by majbo** [comment]
Thats a surprisingly simple workaround for my problem! Thanks!

**Comment by sdanyliv** [comment]
Reopening, since i have idea how support that.

**Comment by MaceWindu** [comment]
@sdanyliv do we really need to fix it?

This error generated by old sqlite versions - modern sqlite, shipped with `System.Data.Sqlite` and starting from 6.0.0 version of `Microsoft.Data.Sqlite` doesn't generate this error for me (for other test, but I will add case from this issue to tests)

**Comment by MaceWindu** [comment]
Nevermind, this case is still broken...
