### ISSUE TITLE
Executing database queries in Parallel using LinqToDb DataConnection

### ISSUE THREAD

**Issue by muradkhateeb78** [linq2db/linq2db#2280]
Executing database queries in Parallel using LinqToDb DataConnection

I was integrating IdentityServer4 with my application using LinqToDb and I was using the following code
```
using (var db = new SqlServerConnection())
            {
                var client = await db.GetTable<MyClient>()
                    .FirstOrDefaultAsync(x => x.ClientId == clientId);

                if (client != null)
                {
                    client.AllowedGrantTypes = await db.GetTable<MyClientGrantType>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.AllowedGrantType)
                        .ToListAsync();

                    client.RedirectUris = await db.GetTable<MyClientRedirectUri>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.RedirectUri)
                        .ToListAsync();

                    client.PostLogoutRedirectUris = await db.GetTable<MyClientPostLogoutRedirectUri>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.PostLogoutRedirectUri)
                        .ToListAsync();

                    client.AllowedScopes = await db.GetTable<MyClientAllowedScopes>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.AllowedScope)
                        .ToListAsync();

                    client.ClientSecrets = await db.GetTable<MyClientSecret>()
                        .Where(x => x.ClientId == clientId)
                        .AsAsyncEnumerable()
                        .ToListAsync();

                    client.Claims = await db.GetTable<MyClientClaim>()
                        .Where(x => x.ClientId == clientId)
                        .AsAsyncEnumerable()
                        .ToListAsync();

                    client.IdentityProviderRestrictions = await db.GetTable<MyClientIdentityProviderRestrictions>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.IdentityProviderRestriction)
                        .ToListAsync();

                    client.AllowedCorsOrigins = await db.GetTable<MyAllowedCorsOrigin>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.AllowedCorsOrigin)
                        .ToListAsync();
                }
                return _mapper.Map<Client>(client);
```
It was working perfectly but I wanted to run the queries in parallel and to achieve that, I made the following changes to my code.
```
using (var db = new SqlServerConnection())
            {
                var client = await db.GetTable<MyClient>()
                    .FirstOrDefaultAsync(x => x.ClientId == clientId);

                if (client != null)
                {
                    var allowedGrantTypesTask = db.GetTable<MyClientGrantType>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.AllowedGrantType)
                        .ToListAsync();

                    var redirectUrisTask =  db.GetTable<MyClientRedirectUri>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.RedirectUri)
                        .ToListAsync();

                    var postLogoutRedirectUrisTask =  db.GetTable<MyClientPostLogoutRedirectUri>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.PostLogoutRedirectUri)
                        .ToListAsync();

                    var allowedScopesTask = db.GetTable<MyClientAllowedScopes>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.AllowedScope)
                        .ToListAsync();

                    var clientSecretsTask = db.GetTable<MyClientSecret>()
                        .Where(x => x.ClientId == clientId)
                        .AsAsyncEnumerable()
                        .ToListAsync();

                    var claimsTask = db.GetTable<MyClientClaim>()
                        .Where(x => x.ClientId == clientId)
                        .AsAsyncEnumerable()
                        .ToListAsync();

                    var identityProviderRestrictionsTask = db.GetTable<MyClientIdentityProviderRestrictions>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.IdentityProviderRestriction)
                        .ToListAsync();

                    var allowedCorsOriginsTask = db.GetTable<MyAllowedCorsOrigin>()
                        .Where(x => x.ClientId == clientId)
                        .Select(x => x.AllowedCorsOrigin)
                        .ToListAsync();
                    await Task.WhenAll(allowedGrantTypesTask, redirectUrisTask, postLogoutRedirectUrisTask,
                        allowedScopesTask, clientSecretsTask, claimsTask, identityProviderRestrictionsTask,
                        allowedCorsOriginsTask);
                    client.AllowedGrantTypes = allowedGrantTypesTask.Result;
                    client.RedirectUris = redirectUrisTask.Result;
                    client.PostLogoutRedirectUris = postLogoutRedirectUrisTask.Result;
                    client.AllowedScopes = allowedScopesTask.Result;
                    client.ClientSecrets = clientSecretsTask.Result;
                    client.Claims = claimsTask.Result;
                    client.IdentityProviderRestrictions = identityProviderRestrictionsTask.Result;
                    client.AllowedCorsOrigins = allowedCorsOriginsTask.Result;
                }
                return _mapper.Map<Client>(client);
            }
```

Now, sometimes this query works just fine. But at times it fails with the following Error

```
Exception message: System.InvalidOperationException: The command execution cannot proceed due to a pending asynchronous operation already in progress.
```

```
StackTrace: [13:11:45 ERR] An unhandled exception has occurred while executing the request.
System.InvalidOperationException: The command execution cannot proceed due to a pending asynchronous operation already in progress.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__122_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__274_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Int32 queryNumber, Func`2 func, Func`3 skipAction, Func`3 takeAction, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at MyProject.Auth.Domain.IdentityServer.MyProjectClientStore.FindClientByIdAsync(String clientId) in C:\Projects\MyProject\src\MyProject.Auth\src\Domain\IdentityServer\MyProjectClientStore.cs:line 70
   at IdentityServer4.Stores.ValidatingClientStore`1.FindClientByIdAsync(String clientId)
   at IdentityServer4.Stores.IClientStoreExtensions.FindEnabledClientByIdAsync(IClientStore store, String clientId)
   at IdentityServer4.Validation.AuthorizeRequestValidator.LoadClientAsync(ValidatedAuthorizeRequest request)
   at IdentityServer4.Validation.AuthorizeRequestValidator.ValidateAsync(NameValueCollection parameters, ClaimsPrincipal subject)
   at IdentityServer4.Services.OidcReturnUrlParser.ParseAsync(String returnUrl)
   at IdentityServer4.Services.ReturnUrlParser.ParseAsync(String returnUrl)
   at IdentityServer4.Services.DefaultIdentityServerInteractionService.GetAuthorizationContextAsync(String returnUrl)
   at MyProject.Auth.IdentityServer.Common.ViewsHelper.BuildLoginViewModelAsync(String returnUrl) in C:\Projects\MyProject\src\MyProject.Auth\src\IdentityServer\Common\ViewsHelper.cs:line 53
   at MyProject.Auth.IdentityServer.Controllers.AccountController.Login(String returnUrl) in C:\Projects\MyProject\src\MyProject.Auth\src\IdentityServer\Controllers\AccountController.cs:line 75
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at IdentityServer4.Hosting.IdentityServerMiddleware.Invoke(HttpContext context, IEndpointRouter router, IUserSession session, IEventService events)
   at IdentityServer4.Hosting.MutualTlsTokenEndpointMiddleware.Invoke(HttpContext context, IAuthenticationSchemeProvider schemes)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at IdentityServer4.Hosting.BaseUrlMiddleware.Invoke(HttpContext context)
   at MyProject.CorrelationTracking.AspNetCore.Logger.LoggingMiddleware.Invoke(HttpContext httpContext, ILogger`1 logger)
   at MyProject.CorrelationTracking.AspNetCore.Correlation.CorrelationTrackingMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Builder.Extensions.MapWhenMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
If I create a new connection for every of the query above and then run those in parallel, it works fine. I traced back and tried finding some other Asynchronous calls that are not awaited but found none in my code. Any Idea of what is wrong here?

### Environment details
linq2db version: *2.9.8*
Database Server: *SqlServer18*
Operating system: *Windows10*
.NET Framework: *.NetCore 3.1*

**Comment by MaceWindu** [comment]
You cannot share connections between threads because they are not thread-safe.

**Comment by sdanyliv** [comment]
You forgot, await in last query.

Also with latest version you can use LoadWith/ThenLoad for such task.

**Comment by sdanyliv** [comment]
I think problem here that you mix two different ways how to work with async.
Just tip. Try to avoid using `Task.Result` especially in async methods.

**Comment by muradkhateeb78** [comment]
@sdanyliv I missed await intentionally as I wanted to run all of those independent queries parallel.
Also can you please point me to the documentation or release notes of what LoadWith/LoadThen do as I could not get any good online resource to get started

**Comment by sdanyliv** [comment]
`LoadWith`, and `ThenLoad` is a full equivalent of EF Core’s `Include`, `ThenInclude` which are more documented. If you have association, they can be loaded via these methods.

```cs
var clientIds = new List<int>{1, 2, 3};
var clients = await db.GetTable<MyClient>()
    .LoadWith(x => x.AllowedGrandTypes)
    .LoadWith(x => x.MyClientRedirectUri)
...
   .Where(x => x.ClientId.In(clientIds))
   .ToListAsync();
```
If there are no associations, you still can load your records in faster query.
```cs
var clientIds = new List<int>{1, 2, 3};
var clientsQuery = 
   from c in db.GetTable<MyClient>()
   where c.ClientId.In(clientIds)
   select new MyClient
   {
       AllowedGrandTypes = db.GetTable<MyClientGrantType>()
                        .Where(x => x.ClientId == c.ClientId)
                        .Select(x => x.AllowedGrantType).ToList(),

.      RedirectUris = db.GetTable<MyClientRedirectUri>()
                        .Where(x => x.ClientId == c.ClientId)
                        .Select(x => x.RedirectUri).ToList(),
    ....
   };

var clients = await clientsQuery.ToListAsync();
```
Probably you will see at first time exception - enable `AllowMultipleQueries`

Note, if you are trying to do Parallel task for such things - you have missed something from linq2db functionality. I have shown how to load multiple MyClient in fast batch.

**Comment by muradkhateeb78** [comment]
Thanks @sdanyliv :)

**Comment by muradkhateeb78** [comment]
@sdanyliv Just one more quest though, if you please can answer.
I have already created my schema using migrations. Lets say I have a table called Students. The Model class can be defined in two ways.
```
[Table(Name = "Students")]
    public class Student
    {
        [PrimaryKey]
        public  int StudentId { get; set; }
        ...
        ...
    }
```

```
[Table(Name = "Students")]
    public class Student
    {
        [Column(Name = "StudentId"), NotNull]
        public  int StudentId { get; set; }
        ...
        ...
    }
```

The question is does adding a PrimaryKey attribute here gives us any benefit over just tagging it as a column, provided that we are not going to update the schema using this class, we would only be doing the CRUD operations?

**Comment by sdanyliv** [comment]
You need PK for Insert(obj), Delete(obj), Update(obj) functions. If you do not use them - you can not define PK.
But! PK information is also used for SQL optimization, so better to define ;)
```cs
[Column(Name = "StudentId", IsPrimaryKey = true)]
```

**Comment by muradkhateeb78** [comment]
Great, thanks!
