### ISSUE TITLE
Cannot return arrays, lists, and dictionaries inside subqueries

### ISSUE THREAD

**Issue by Shane32** [linq2db/linq2db#2283]
I am trying to produce a fixed array within a subquery (e.g. `select new object[] { product.Id, product.Name }`), but am getting exceptions back from linq2db in the form of `'new [] {...}' cannot be converted to SQL`.  For fixed `List<>` and `Dictionary<>` objects, I receive an error that `Multiple queries are not allowed`.  Only anonymous objects seem to be supported.  Since my LINQ is generated dynamically (and needs to be read dynamically), and since creating an anonymous type at runtime is near-impossible (involves creating a dynamic assembly and compiling MSIL at runtime, as demonstrated by the `System.Linq.Dynamic` library), I would appreciate it if dictionaries could be supported.  Executing recursive queries are not an option due to performance requirements.

I know that linq2db can produce an array or dictionary if it is the root of the query.  Unfortunately this does not help my particular needs either.

Just FYI, the EF Core team fixed a regression in EF Core 3.0 that caused the same problems by handling `NewArrayExpression` and `ListInitExpression` in their code.  I have no idea if it helps, but I thought I'd link the relevant PRs anyway:
https://github.com/dotnet/efcore/pull/18296/files
https://github.com/dotnet/efcore/pull/18400/files

I'd be happy to help integrate the necessary changes via a pull request if I can.  If someone can provide an outline of what needs to be done, and where to look in the codebase, there's a chance I might be able to figure it out, if I have the time.

### Steps to reproduce
Below is a sample of the code I am testing with:
* Test3 shows typical construction of a query, which works but not for my needs
* Test5 shows a subquery returning a 'static' array of values from the query
* Test6 shows the code that I need working, using dictionaries within subqueries

```c#
            var provider = new SqlServerDataProvider(ProviderName.SqlServer, SqlServerVersion.v2017);
            var db = new DataContext(provider, Configuration.GetConnectionString("testdb"));
            var categories = db.GetTable<Category>();
            var productCategories = db.GetTable<Product_Category_Mapping>();
            var products = db.GetTable<Product>();

            Console.WriteLine("-----test 3 using native linq and anonymous objects-----");
            var test3 =
                from product in products
                select new {
                    Product = product,
                    Category = (
                        from cat in categories
                        join pcat in productcategories on cat.Id equals pcat.CategoryId
                        where pcat.ProductId == product.Id
                        select new { cat.Id, cat.Name }).FirstOrDefault()
                };
            var test3ret = await test3.Take(10).ToListAsync();
            foreach (var row in test3ret) {
                Console.WriteLine($"{row.Product.Name} - {row.Category?.Id}: {row.Category?.Name}");
            }

            Console.WriteLine("-----test 5 using arrays (does not work)-----");
            var test5 =
                from product in products
                select new {
                    Product = product,
                    Category = (
                        from cat in categories
                        join pcat in productcategories on cat.Id equals pcat.CategoryId
                        where pcat.ProductId == product.Id
                        select new object[] { cat.Id, cat.Name }).FirstOrDefault()
                };
            var test5ret = await test5.Take(10).ToListAsync();
            foreach (var row in test5ret) {
                Console.WriteLine($"{row.Product.Name} - {row.Category?[0]}: {row.Category?[1]}");
            }

            Console.WriteLine("-----test 6 using dictionaries (does not work)-----");
            var test6 =
                from product in products
                select new {
                    Product = product,
                    Category = (
                        from cat in categories
                        join pcat in productcategories on cat.Id equals pcat.CategoryId
                        where pcat.ProductId == product.Id
                        select new Dictionary<string, object>() { { "Id", cat.Id }, { "Name", cat.Name } }).FirstOrDefault()
                };
            var test6ret = await test6.Take(10).ToListAsync();
            foreach (var row in test6ret) {
                Console.WriteLine($"{row.Product.Name} - {row.Category?["Id"]}: {row.Category?["Name"]}");
            }
```

With these classes:
```csharp
class Product
{
    public int Id { get; set; }
    public string Name { get; set; }

}
class Product_Category_Mapping
{
    public int Id { get; set; }
    public int ProductId { get; set; }
    public int CategoryId { get; set; }
    public bool IsFeaturedProduct { get; set; }
    public bool DisplayOrder { get; set; }
}
class Category
{
    public int Id { get; set; }
    public string Name { get; set; }
    public int ParentCategoryId { get; set; }
}
```

Exception produced by Test5:
```
LinqToDB.Linq.LinqException: 'new [] {Convert(<>h__TransparentIdentifier0.cat.Id, Object), <>h__TransparentIdentifier0.cat.Name}' cannot be converted to SQL.
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryContext(IBuildContext context, MethodCallExpression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryExpression(IBuildContext context, MethodCallExpression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass77_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass77_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at TestLinq2Db.App.TestInnerJoins() in C:\...\TestLinq2Db\App.cs:line 145
   at TestLinq2Db.App.RunAsync() in C:\...\TestLinq2Db\App.cs:line 41
```

Exception produced by Test6:
```
LinqToDB.Linq.LinqException: Multiple queries are not allowed. Set the 'LinqToDB.Common.Configuration.Linq.AllowMultipleQuery' flag to 'true' to allow multiple queries.
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetMultipleQueryExpression(IBuildContext context, MappingSchema mappingSchema, Expression expression, HashSet`1 parameters, Boolean& isLazy)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildMultipleQuery(IBuildContext context, Expression expression, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass77_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass77_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at TestLinq2Db.App.TestInnerJoins() in C:\...\TestLinq2Db\App.cs:line 160
   at TestLinq2Db.App.RunAsync() in C:\...\TestLinq2Db\App.cs:line 41
```

### Environment details
linq2db version: 3.0.0-rc.1
Database Server: Microsoft Azure SQL Server
Database Provider: SqlServer v2017
Operating system: Windows 10 Pro 1909
.NET Framework: .Net Core 3.1

**Comment by sdanyliv** [comment]
I see, never met such requests :)
Ok, it is doeable and do not need heavy artillery.

**Comment by Shane32** [comment]
Thanks @sdanyliv @MaceWindu  !!
