### ISSUE TITLE
Exception ORA-12570: Network Session: Unexpected packet read error

### ISSUE THREAD

**Issue by filippobottega** [linq2db/linq2db#2302]
Hello,
  sometimes I get this exception:

```
System.AggregateException: One or more errors occurred. (ORA-12570: Network Session: Unexpected packet read error) (ORA-12570: Network Session: Unexpected packet read error)
 ---> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): ORA-12570: Network Session: Unexpected packet read error
 ---> OracleInternal.Network.NetworkException (0x80004005): ORA-12570: Network Session: Unexpected packet read error
 ---> System.Net.Sockets.SocketException (10060): A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.
   at OracleInternal.Network.ReaderStream.Read(OraBuf OB)
   at OracleInternal.Network.ReaderStream.Read(OraBuf OB)
   at OracleInternal.TTC.OraBufReader.GetDataFromNetwork()
   at OracleInternal.TTC.OraBufReader.Read(Boolean bIgnoreData)
   at OracleInternal.TTC.TTCExecuteSql.ReceiveExecuteResponse(Accessor[]& defineAccessors, Accessor[] bindAccessors, Boolean bHasReturningParams, SQLMetaData& sqlMetaData, SqlStatementType statementType, Int64 noOfRowsFetchedLastTime, Int32 noOfRowsToFetch, Int32& noOfRowsFetched, Int64& queryId, Int32 longFetchSize, Int64 initialLOBFetchSize, Int64[] scnFromExecution, Boolean bAllInputBinds, Int32 arrayBindCount, DataUnmarshaller& dataUnmarshaller, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int64[]& rowsAffectedByArrayBind, Boolean bDefineDone, Boolean& bMoreThanOneRowAffectedByDmlWithRetClause, List`1& implicitRSList, Boolean bLOBArrayFetchRequired)
   at Oracle.ManagedDataAccess.Client.OracleException.HandleError(OracleTraceLevel level, OracleTraceTag tag, OracleTraceClassName className, OracleTraceFuncName funcName, Exception ex, OracleLogicalTransaction oracleLogicalTransaction)
   at OracleInternal.TTC.TTCExecuteSql.ReceiveExecuteResponse(Accessor[]& defineAccessors, Accessor[] bindAccessors, Boolean bHasReturningParams, SQLMetaData& sqlMetaData, SqlStatementType statementType, Int64 noOfRowsFetchedLastTime, Int32 noOfRowsToFetch, Int32& noOfRowsFetched, Int64& queryId, Int32 longFetchSize, Int64 initialLOBFetchSize, Int64[] scnFromExecution, Boolean bAllInputBinds, Int32 arrayBindCount, DataUnmarshaller& dataUnmarshaller, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int64[]& rowsAffectedByArrayBind, Boolean bDefineDone, Boolean& bMoreThanOneRowAffectedByDmlWithRetClause, List`1& implicitRSList, Boolean bLOBArrayFetchRequired)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass34_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
```

I don't know how to find the cause. It could be a transitory error.
Is it possible to let linq2db to manage this types of errors calling ExecuteNonQuery until the call ends without exceptions? In projects with a lot of queries is not easy to catch this types of exceptions every time.

Thank you!

### Environment details
inq2db version: 3.0.0-rc.2303
Database Server: Oracle
Database Provider: Oracle.ManagedDataAccess.Core (3.0.0-rc.2303)
Operating system: Windows 10
.NET Framework:.NET Core 3.1

**Comment by filippobottega** [comment]
This is another exception similar to the first one:

```
System.AggregateException: One or more errors occurred. (Oracle error ORA-12571 encountered)
 ---> Oracle.ManagedDataAccess.Client.OracleException (0x80004005): Oracle error ORA-12571 encountered
 ---> OracleInternal.Network.NetworkException (0x80004005): Oracle error ORA-12571 encountered
 ---> System.Net.Sockets.SocketException (10054): An existing connection was forcibly closed by the remote host.
   at OracleInternal.Network.TcpTransportAdapter.Send(OraBuf OB)
   at OracleInternal.Network.TcpTransportAdapter.Send(OraBuf OB)
   at OracleInternal.Network.WriterStream.Write(OraBuf OB)
   at OracleInternal.TTC.OraBufWriter.FlushData()
   at OracleInternal.TTC.OraBufWriter.WriteLengthAndDataToOraBuf(Boolean bWritePrefixLength, Int32 prefixLength, Byte[] userBuffer, Int32 offset, Int32 length)
   at OracleInternal.TTC.MarshallingEngine.MarshalCLR(Byte[] value, Int32 offset, Int32 valueLen)
   at OracleInternal.TTC.TTCExecuteSql.WritePisdefData(Int64 executeOptions, Byte[] sqlStmtByteStream, ColumnDescribeInfo[] colDefinesInfoArray, Int32 arrayBindCount, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int32 startIndex)
   at Oracle.ManagedDataAccess.Client.OracleException.HandleError(OracleTraceLevel level, OracleTraceTag tag, OracleTraceClassName className, OracleTraceFuncName funcName, Exception ex, OracleLogicalTransaction oracleLogicalTransaction)
   at OracleInternal.TTC.TTCExecuteSql.WritePisdefData(Int64 executeOptions, Byte[] sqlStmtByteStream, ColumnDescribeInfo[] colDefinesInfoArray, Int32 arrayBindCount, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int32 startIndex)
   at OracleInternal.TTC.TTCExecuteSql.WriteOall8Message(Byte[] sqlStmtByteStream, Int32 cursorId, Int64 dbChangeRegistrationId, Int64 executeOptions, ColumnDescribeInfo[] colDefinesInfoArray, Int32 longFetchSize, Int32 arrayBindCount, Int32 numDefineCols, Int64 noOfRowsToFetch, SqlStatementType stmtType, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int32 startIndex)
   at OracleInternal.TTC.TTCExecuteSql.SendExecuteRequest(OracleConnectionImpl commImpl, Byte[] sqlStmtByteStream, Boolean bHasReturningClause, Int32 cursorId, Int64 dbChangeRegistrationId, ColumnDescribeInfo[] columnDefines, Int64 noOfRowsToFetch, Boolean parse, Boolean execute, Boolean fetch, Boolean define, Boolean bAutoCommit, Boolean bDisableCompressedFetch, SqlStatementType stmtType, Int32 longFetchSize, Int32 arrayBindCount, Int64[] scnForSnapshot, MarshalBindParameterValueHelper& marshalBindParamsHelper, Int32 startIndex)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass34_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) 
```

**Comment by sdanyliv** [comment]
Maybe you need `RetryPolicy`
https://github.com/linq2db/linq2db/blob/mater/Tests/Linq/Data/RetryPolicyTest.cs#L108
Currently implemented only of SqlServer
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/SqlServer/SqlServerRetryPolicy.cs#L14

**Comment by MaceWindu** [comment]
Errors like that hardly caused by linq2db, more like issues with network or some incompatibility between server and client. 
For retry functionality you should look at `RetryPolicy` mechanism we have: https://github.com/linq2db/linq2db/tree/master/Source/LinqToDB/Data/RetryPolicy

you will need to implement your own retry policy, inherited from [RetryPolicyBase](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Data/RetryPolicy/RetryPolicyBase.cs) (or IRetryPolicy) as we currently have [implementation](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/SqlServer/SqlServerRetryPolicy.cs) for Sql Server only (BTW, you can send PR with retry policy for Oracle)
