### ISSUE TITLE
In v3.0 broken Oracle BulkCopy with RetryPolicy and AlternativeBulkCopy.InsertInto

### ISSUE THREAD

**Issue by AK107** [linq2db/linq2db#2342]
BulkCopy does not work with RetryPolicy installed because it is impossible to define the underlying command in TryGetProviderCommand (in this case used RetryingDbCommand) in OracleDataProvider, and and as a result no call to Adapter.SetArrayBindCount. 
Without RetryPolicy it works ok.

	[TestFixture]
	public class Tests
	{
		[Test]
		public async Task Test()
		{
			await using var db = new StoreDb();

			using (db.CreateTempTable<Entity>())
			await using (await db.BeginTransactionAsync())
			{
				db.Entities.BulkCopy(CreateEntities(1, 10));
			}
		}

		private static IEnumerable<Entity> CreateEntities(int startId, int count) => from id in Enumerable.Range(startId, count)
																					 select new Entity { Id = id, Name = $"Name_{id}" };

		sealed class StoreDb : DataConnection
		{
			public ITable<Entity> Entities => GetTable<Entity>();

			static  StoreDb()
			{
				OracleTools.UseAlternativeBulkCopy = AlternativeBulkCopy.InsertInto;
				Configuration.RetryPolicy.Factory = connection => new DummyRetryPolicy();
			}
		}

		sealed class DummyRetryPolicy : IRetryPolicy
		{
			public TResult Execute<TResult>(Func<TResult> operation) => operation();
			public void Execute(Action operation) => operation();
			public Task<TResult> ExecuteAsync<TResult>(Func<CancellationToken, Task<TResult>> operation, CancellationToken cancellationToken = new CancellationToken()) => operation(cancellationToken);
			public Task ExecuteAsync(Func<CancellationToken, Task> operation, CancellationToken cancellationToken = new CancellationToken()) => operation(cancellationToken);
		}

		[Table(Name = "t_entity")]
		sealed class Entity
		{
			[PrimaryKey]
			[NotNull, Column("id")]
			public long Id { get; set; }

			[NotNull, Column("name", Length = 256)]
			public string Name { get; set; }
		}
	}

```
Test Failed: System.InvalidCastException : Unable to cast object of type 'System.Object[]' to type 'System.IConvertible'.
System.InvalidCastException : Unable to cast object of type 'System.Object[]' to type 'System.IConvertible'.
   at System.Convert.ToInt64(Object value)
   at OracleInternal.ServiceObjects.OracleParameterImpl.SetInt64DataInBytes(Object paramValue, Byte[]& int64ByteArray)
   at OracleInternal.ServiceObjects.OracleParameterImpl.SetInt64DataInBytes(Object paramValue)
   at Oracle.ManagedDataAccess.Client.OracleParameter.PreBind_Int64()
   at Oracle.ManagedDataAccess.Client.OracleParameter.PreBind(OracleConnectionImpl connImpl, ColumnDescribeInfo cachedParamMetadata, Boolean& bMetadataModified, Int32 arrayBindCount, ColumnDescribeInfo& paramMetaData, Object& paramValue, Boolean isEFSelectStatement, SqlStatementType stmtType)
   at OracleInternal.ServiceObjects.OracleCommandImpl.InitializeParamInfo(ICollection paramColl, OracleConnectionImpl connectionImpl, ColumnDescribeInfo[] cachedParamMetadata, Boolean& bMetadataModified, Boolean isEFSelectStatement, MarshalBindParameterValueHelper& marshalBindValuesHelper)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ProcessParameters(OracleParameterCollection paramColl, OracleConnectionImpl connectionImpl, ColumnDescribeInfo[] cachedParamMetadata, Boolean& bBindMetadataModified, Boolean isEFSelectStatement, MarshalBindParameterValueHelper& marshalBindValuesHelper)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at LinqToDB.Data.RetryPolicy.RetryingDbCommand.<ExecuteNonQuery>b__30_0()
   at LinqToDB.Data.RetryPolicy.RetryPolicyBase.ExecuteImplementation[TResult](Func`1 operation)
   at LinqToDB.Data.RetryPolicy.RetryPolicyBase.Execute[TResult](Func`1 operation)
   at LinqToDB.Data.RetryPolicy.RetryingDbCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Data.CommandInfo.Execute()
   at LinqToDB.Data.DataConnectionExtensions.Execute(DataConnection connection, String sql, DataParameter[] parameters)
   at LinqToDB.DataProvider.MultipleRowsHelper.Execute()
   at LinqToDB.DataProvider.Oracle.OracleBulkCopy.Execute(MultipleRowsHelper helper, List`1 list)
   at LinqToDB.DataProvider.Oracle.OracleBulkCopy.OracleMultipleRowsCopy2(MultipleRowsHelper helper, IEnumerable source)
   at LinqToDB.DataProvider.Oracle.OracleBulkCopy.MultipleRowsCopy[T](ITable`1 table, BulkCopyOptions options, IEnumerable`1 source)
   at LinqToDB.DataProvider.BasicBulkCopy.BulkCopy[T](BulkCopyType bulkCopyType, ITable`1 table, BulkCopyOptions options, IEnumerable`1 source)
   at LinqToDB.DataProvider.Oracle.OracleDataProvider.BulkCopy[T](ITable`1 table, BulkCopyOptions options, IEnumerable`1 source)
   at LinqToDB.Data.DataConnectionExtensions.BulkCopy[T](ITable`1 table, IEnumerable`1 source)

**Comment by MaceWindu** [comment]
As workaround you can setup mapping schema:
```cs
ms.SetConvertExpression<RetryingDbCommand, IDbCommand>(cmd => cmd.UnderlyingObject);
```
