### ISSUE TITLE
Loading 2nd level references fails

### ISSUE THREAD

**Issue by usenff-cu** [linq2db/linq2db#2351]
The documentation of "LoadWithAsTable" contains the following example for loading 2nd level references:
```
/// <code>
/// // loads records from Table1 with Reference1 collection association loaded for each Table1 record
/// // loads records from Reference2 collection association for each loaded Reference1 record
/// // loads records from Reference3 association for each loaded Reference2 record
/// // note that a way you access collection association record (by index, using First() method) doesn't affect
/// // query results and always select all records
/// db.Table1.LoadWithAsTable(r => r.References1[0].References2.First().Reference3);
/// </code>
```

Both of the variants I tried (described below) did not work.
Is this a bug or am I doing something wrong?

### Query for both variants:
```c#
var query = from p in _productRepository.Table orderby p.Id where !p.Deleted &&  p.Sku == sku select p;
var product = query.FirstOrDefault();
```

### With "_productRepository.Table" defined as:
```c#
_dataProvider.GetTable<Product>()
	.LoadWithAsTable(p => p.ProductChannelData)
	.LoadWithAsTable(p => p.ProductChannelData.First().Channel);
```
- Product is loaded
- Product.ProductChannelData is loaded
- **Product.ProductChannelData.Channel is null**

### With "_productRepository.Table" defined as:
```c#
_dataProvider.GetTable<Product>()
	.LoadWithAsTable(p => p.ProductChannelData.First().Channel);
```
**The following exception is thrown:**
```
System.ArgumentException: Expression of type 'Domain.Catalog.Channel' cannot be used for parameter of type 'System.Collections.Generic.IEnumerable`1[Domain.Catalog.ProductChannelData]' of method 'System.Linq.IQueryable`1[Domain.Catalog.ProductChannelData] AsQueryabl
e[ProductChannelData](System.Collections.Generic.IEnumerable`1[Domain.Catalog.ProductChannelData])' (Parameter 'arg0')
   at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Linq.Expressions.Expression.Call(MethodInfo method, Expression arg0)
   at LinqToDB.Linq.Builder.AssociationHelper.CreateAssociationQueryLambda(ExpressionBuilder builder, AccessorMember onMember, AssociationDescriptor association, Type parentOriginalType, Type parentType, Type objectType, Boolean inline, Boolean enforceDefault, List`1 loadWith, Boolean& isLeft)
   at LinqToDB.Linq.Builder.EagerLoading.GenerateAssociationExpression(ExpressionBuilder builder, IBuildContext context, Expression expression, AssociationDescriptor association)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildExpression(Expression expression, Int32 level, ParameterExpression parentObject)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.SetLoadWithBindings(Type objectType, ParameterExpression parentObject, List`1 exprs)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildDefaultConstructor(EntityDescriptor entityDescriptor, Type objectType, Int32[] index)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildTableExpression(Boolean buildBlock, Type objectType, Int32[] index)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery(Type tableType, TableContext tableContext, ParameterExpression parentObject)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source)
   at Services.Catalog.ProductService.GetProductBySku(String sku)
```

### Referenced Objects
```c#
public class Product
{        
	public int Id { get; set; }

	[Association(ThisKey="Id", OtherKey="ProductId")]
	public virtual ICollection<ProductChannelData> ProductChannelData
	{
		get => _productChannelData ??= new List<ProductChannelData>();
		set => _productChannelData = value;
	}
	
	// ...
}

public class ProductChannelData
{
	public int Id { get; set; }

	[Association(ThisKey="ChannelId", OtherKey="Id")]
	public Channel Channel { get; set; }
	
	public int ProductId { get; set; }
	public int ChannelId { get; set; }
	
	// ...
}

public class Channel
{
	public int Id { get; set; }
	
	// ...
}
```

### Environment details
linq2db version: 3.0.1
Database Server: MySQL
.NET Framework: netcoreapp3.1

**Comment by sdanyliv** [comment]
Try the following construction:
```cs
_dataProvider.GetTable<Product>()
	.LoadWith(p => p.ProductChannelData)
        .ThenLoad(cd => cd.Channel);
```

**Comment by usenff-cu** [comment]
Hello @sdanyliv,

thank you for your quick reply. The following code loads all entities as expected:
```c#
var query = from p in _dataProvider.GetTable<Product>()
        .LoadWith(p => p.ProductChannelData)
        .ThenLoad(cd => cd.Channel)
orderby p.Id where !p.Deleted && p.Sku == sku select p;
var product = query.FirstOrDefault();
```

The shop-framework (nop) i am working on uses a repository-pattern that needs the table-return-values. I will check if I can apply the workarround anyways but it would be nice to know if the loading of 2nd level-entities is not supported for "LoadWithAsTable" or if it is a bug.

Best regards,
Uwe

**Comment by sdanyliv** [comment]
LoadWithAsTable is added for backward compatibility with previous version. Anyway i need to handle such case.
Looks like there is LINQ parsing collision because we allow in LoadWith write real queries.
For example
```cs
from p in _dataProvider.GetTable<Product>()
        .LoadWith(p => p.ProductChannelData.Take(2))
```
Should load only first two records from detail table.

**Comment by usenff-cu** [comment]
I managed to apply the "LoadWith" solution to my usecase. Thank you very much!

I will leave the ticket open because of the bug in "LoadWithAsTable".
