### ISSUE TITLE
LinqToDB.LinqToDBException: ValueTaskToTaskMapper mapper applied to non-ValueTask type (current develop + branch)

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#2364]
I'm geeting following Exception when using current linq2db develop + branch from https://github.com/linq2db/linq2db/pull/2357
when using our newest version against PostgreSQL

   at LinqToDB.Expressions.ValueTaskToTaskMapper.LinqToDB.Expressions.ICustomMapper.Map(Expression expression) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\ValueTaskToTaskMapper.cs:line 18
   at LinqToDB.Expressions.TypeMapper.<>c__DisplayClass23_1.<MapLambdaInternal>b__3(Expression e) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 682
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\Extensions.cs:line 1007
   at LinqToDB.Expressions.TypeMapper.<>c__DisplayClass23_0.<MapLambdaInternal>g__ReplaceTypes|2(Expression expression) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 428
   at LinqToDB.Expressions.TypeMapper.MapLambdaInternal(LambdaExpression lambda, Boolean mapConvert, Boolean convertResult, Boolean ignoreMissingMembers) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 696
   at LinqToDB.Expressions.TypeMapper.BuildWrapperImpl(LambdaExpression lambda, Boolean wrapResult, Boolean optional) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 1067
   at LinqToDB.Expressions.TypeMapper.BuildWrapper(LambdaExpression lambda, Boolean optional) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 1062
   at LinqToDB.Expressions.TypeMapper.<BuildWrapperMethods>b__17_1(<>f__AnonymousType114`2 e) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 348
   at System.Linq.Enumerable.WhereSelectArrayIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LinqToDB.Expressions.TypeMapper.BuildWrapperMethods(Type wrapperType) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 344
   at LinqToDB.Expressions.TypeMapper.FinalizeMappings() in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\Expressions\TypeMapper\TypeMapper.cs:line 196
   at LinqToDB.DataProvider.PostgreSQL.NpgsqlProviderAdapter.GetInstance() in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\DataProvider\PostgreSQL\NpgsqlProviderAdapter.cs:line 194
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider..ctor(String name, PostgreSQLVersion version) in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\DataProvider\PostgreSQL\PostgreSQLDataProvider.cs:line 22
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.<>c.<.cctor>b__19_0() in D:\csharp\git\github\common\linq2db_neu\Source\LinqToDB\DataProvider\PostgreSQL\PostgreSQLTools.cs:line 18
   at System.Lazy`1.CreateValue()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by jogibear9988** [comment]
@Shane32 
maybe you could help? seems this error occures after your change: https://github.com/linq2db/linq2db/pull/2314

**Comment by sdanyliv** [comment]
We expect a reproducible test. You are not novice here and can even fix it by yourself if can not create test.

**Comment by jogibear9988** [comment]
Yes, but I first need to find out whats causing this, why does it not happen on linq2db tests.
And as @Shane32 introduce the error, Ithought maybe he could help.
I'm not so deep in the code that I would find the solution fast, and I wanted to not roll back to 2x for the next release of our software.

**Comment by jogibear9988** [comment]
And I do not understand the purpouse of the ValueTaskToTaskMapper in the TypeMapper (atm).

**Comment by jogibear9988** [comment]
@sdanyliv @Shane32  

Is this wrong? :

https://github.com/linq2db/linq2db/blob/b46b362705627561f22280c079780e0ce3472772/Source/LinqToDB/DataProvider/PostgreSQL/NpgsqlProviderAdapter.cs#L564

[return: CustomMapper(typeof(ValueTaskToTaskMapper))]

cause the result already is a Task?

**Comment by jogibear9988** [comment]
maybe it is needed here:

https://github.com/linq2db/linq2db/blob/b46b362705627561f22280c079780e0ce3472772/Source/LinqToDB/DataProvider/PostgreSQL/NpgsqlProviderAdapter.cs#L554

**Comment by jogibear9988** [comment]
I've changed this, and it works on my system. But I wait for answer from @Shane32

**Comment by MaceWindu** [comment]
I need to know npgsql version and target framework

**Comment by jogibear9988** [comment]
net 4.8 
npgsql 4.1.3.1

**Comment by MaceWindu** [comment]
That's strange error, because `CompleteAsync` returns `ValueTask<ulong>`

**Comment by jogibear9988** [comment]
Okay, I‘ll look why result is a Task<long>

Maybe we should check in ValueTaskToTaskMapper if its already a Task?

But I look if I find the root of the problem

**Comment by MaceWindu** [comment]
Problem is on this line I assume 
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Expressions/TypeMapper/ValueTaskToTaskMapper.cs#L12
we should test against open-generic type, not `expression.Type` here
