### ISSUE TITLE
Combination of LoadWith() and In() not possible in Query

### ISSUE THREAD

**Issue by BenKmann** [linq2db/linq2db#2392]
I have a query which crashes when i combine LoadWith with In.

```
Exception message:
'<>h__TransparentIdentifier0.auv.Status.In(Vertrag, Vertragsänderung)' cannot be converted to SQL.
Stack trace:
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions, Boolean isNotExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.SelectBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.LoadWithBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at LinqToDB.LinqExtensions.LoadWithQueryable`2.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

The Query:
```c#
(from auv in db.AngebotsUndVertragsdaten
join tp in db.Teilprodukte on auv.Id equals tp.SuperId
where auv.Vertragsbeginn.HasValue
where auv.Vertragsende > beginningOfNextYear
where auv.Status.In(Status.Vertrag, Status.Vertragsänderung)
where tp.Von.HasValue && tp.Von.Value.Year <= thisYear
select auv)
.LoadWith(auv => auv.Ref_Teilprodukte)
.ToList();
```

If i remove the line
```c#
where auv.Status.In(Status.Vertrag, Status.Vertragsänderung)
```
it works again, or if i Remove the 
```c#
.LoadWith(auv => auv.Ref_Teilprodukte)
```
it works again.

So the LoadWith should include the entities of the table i already joined on. 
This are the generated Queries when i just **remove** the auv.Status.In line.
In the first query Linq2Db double joins on the subtable03 (Teilprodukte).
The "tp" join is my join and the "detail" join comes from LoadWith.
In the Where Statements the "tp" join is used and in the select the "detail" Join.
My guess is that this double join will mess up the "in" and that's why i get an exception.

```sql
--  SqlServer.2012
DECLARE @Vertragsende DateTime2
SET     @Vertragsende = '2021-01-01T00:00:00'
DECLARE @p1 Int -- Int32
SET     @p1 = 2020

SELECT
	[auv].[ID],
	[detail].[CURRENCY3],
...
	[detail].[CURRENCY2]
FROM
	[ADDITIONAL] [auv]
		INNER JOIN [SUBTABLE03] [tp] ON [auv].[ID] = [tp].[SUPERID]
		INNER JOIN [SUBTABLE03] [detail] ON [auv].[ID] = [detail].[SUPERID]
WHERE
	[auv].[DATE6] IS NOT NULL AND
	[auv].[DATE8] > @Vertragsende AND
	[tp].[DATE2] IS NOT NULL AND
	DatePart(year, [tp].[DATE2]) <= @p1


DataConnection: BeforeExecute
--  SqlServer.2012
DECLARE @beginningOfNextYear DateTime2
SET     @beginningOfNextYear = '2021-01-01T00:00:00'
DECLARE @thisYear Int -- Int32
SET     @thisYear = 2020

SELECT
	[auv].[CURRENCY24],
...
	[auv].[CURRENCY12]
FROM
	[ADDITIONAL] [auv]
		INNER JOIN [SUBTABLE03] [tp] ON [auv].[ID] = [tp].[SUPERID]
WHERE
	[auv].[DATE6] IS NOT NULL AND
	[auv].[DATE8] > @beginningOfNextYear AND
	[tp].[DATE2] IS NOT NULL AND
	DatePart(year, [tp].[DATE2]) <= @thisYear
```

I generated an ExpressionTest-Class to this query, but the contents of this class are only this Exception:
(Maybe another bug? Because the Query worked.)

```
Exception in ExpressionTest-Class
System.ArgumentException
Die Zeichenfolge kann keine Länge von 0 (null) haben.
Parametername: oldValue
   bei System.String.ReplaceInternal(String oldValue, String newValue)
   bei System.String.Replace(String oldValue, String newValue)
   bei LinqToDB.Linq.Builder.ExpressionTestGenerator.<>c.<GenerateSourceString>b__27_0(String current, KeyValuePair`2 item) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionTestGenerator.cs:Zeile 928.
   bei System.Linq.Enumerable.Aggregate[TSource,TAccumulate](IEnumerable`1 source, TAccumulate seed, Func`3 func)
   bei LinqToDB.Linq.Builder.ExpressionTestGenerator.GenerateSourceString(Expression expr) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionTestGenerator.cs:Zeile 899.
   bei LinqToDB.Linq.Builder.ExpressionTestGenerator.GenerateSource(Expression expr) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionTestGenerator.cs:Zeile 865.
```

So if i use the original query, leave the "auv.status.in" part in and just remove the "loadwith" part, this Query is generated:

```c#
--  SqlServer.2012
DECLARE @beginningOfNextYear DateTime2
SET     @beginningOfNextYear = '2021-01-01T00:00:00'
DECLARE @thisYear Int -- Int32
SET     @thisYear = 2020

SELECT
	[auv].[CURRENCY24],
...
	[auv].[CURRENCY12]
FROM
	[ADDITIONAL] [auv]
		INNER JOIN [SUBTABLE03] [tp] ON [auv].[ID] = [tp].[SUPERID]
WHERE
	[auv].[DATE6] IS NOT NULL AND
	[auv].[DATE8] > @beginningOfNextYear AND
	[auv].[TEXT3] IN (N'Vertrag', N'Vertragsänderung') AND
	[tp].[DATE2] IS NOT NULL AND
	DatePart(year, [tp].[DATE2]) <= @thisYear
```

So he correctly generates the where TEXT3 IN ... part. And the ExpressionTest.0.cs Class this Time also worked.

The Navigation Property i used in LoadWith is defined as this:
```c#
[LinqToDB.Mapping.Association(ThisKey = nameof(AngebotsUndVertragsdaten.Id), OtherKey = nameof(Teilprodukte.SuperId), CanBeNull = false)]
public IEnumerable<Teilprodukte> Ref_Teilprodukte { get; set; }	
```

Made a short test with linq2db version: 3.0.1, but the Exception remains.

### Environment details
linq2db version: 3.0.0
Database Server: SqlServer
Operating system: Windows 10
.NET Framework: 4.5.2

**Comment by sdanyliv** [comment]
Thanks for reporting will try to reproduce.

**Comment by sdanyliv** [comment]
Fix is ready and will be available in the next release.

**Comment by BenKmann** [comment]
Thanks a lot! I love this fast responsetimes <3
Really appreciate the effort.
Should i close the Issue or should i wait for the fix and test again?

**Comment by sdanyliv** [comment]
It will be closed automatically after PR merge.

**Comment by BenKmann** [comment]
@sdanyliv So will this also fix, that my Navigationproperty "Ref_Teilprodukte" has every entity 2 times, when i query it with the query i used as an example in this issue?
![grafik](https://user-images.githubusercontent.com/12639595/89440863-92498700-d74c-11ea-855e-83b1288422c0.png)
Field Id you see is the Primarykey, so in the Database there are only two entries.

**Comment by sdanyliv** [comment]
How many records returned by this query?
```cs
var query = from auv in db.AngebotsUndVertragsdaten
join tp in db.Teilprodukte on auv.Id equals tp.SuperId
where auv.Vertragsbeginn.HasValue
where auv.Vertragsende > beginningOfNextYear
where auv.Status.In(Status.Vertrag, Status.Vertragsänderung)
where tp.Von.HasValue && tp.Von.Value.Year <= thisYear
select auv
```

**Comment by BenKmann** [comment]
This Query returns 16.238 (with and without the "LoadWith").

And i also just saw, it's not 2 times, but n-times.
So a auv record where this SQL-Query would return 5 tp-Childs

(dq-query: SELECT * FROM SUBTABLE03 WHERE SuperId = 100157 ) 100157 is auv-Id

then auv.Ref_Teilprodukte is filled with 25 Entities. So 5 rows 5 Times. 
6 childs = 36 Entities in auv.Ref_Teilprodukte. Super strange.

**Comment by BenKmann** [comment]
So i posted in the starting Post the Query Linq2Db generates.
It creates this query when i use **LoadWith**.

```sql
DECLARE @Vertragsende DateTime2
SET     @Vertragsende = '2021-01-01T00:00:00'
DECLARE @p1 Int -- Int32
SET     @p1 = 2020

SELECT
	[auv].[ID],
	[detail].[CURRENCY3],
	[detail].[CURRENCY2]
FROM
	[ADDITIONAL] [auv]
		INNER JOIN [SUBTABLE03] [tp] ON [auv].[ID] = [tp].[SUPERID]
		INNER JOIN [SUBTABLE03] [detail] ON [auv].[ID] = [detail].[SUPERID]
WHERE
	[auv].[DATE6] IS NOT NULL AND
	[auv].[DATE8] > @Vertragsende AND
	[tp].[DATE2] IS NOT NULL AND
	DatePart(year, [tp].[DATE2]) <= @p1
```

When i put this query in Sql Server Management Studio, he also multiplies it out.
If I remove the double Join on the same Sub-Table, i get the correct results.
So the problem is, that LoadWith Inner Joins on a table, i already "inner joined" on in my query.

**Comment by sdanyliv** [comment]
Will try to reproduce on my test. It should be only two queries.
If you put LoadWith exactly after db.AngebotsUndVertragsdaten you have also strange results?

**Comment by BenKmann** [comment]
Hi @sdanyliv ,

thanks. Maybe you can reproduce it, when you try the Unittest like this?
```c#
[Test]
public void TestLoadWithAndExtensions([IncludeDataSources(TestProvName.AllSQLite)] string context)
{
	var (masterRecords, detailRecords, subDetailRecords) = GenerateDataWithSubDetail();

	using (new AllowMultipleQuery())
	using (var db = GetDataContext(context))
	using (var master = db.CreateLocalTable(masterRecords))
	using (var detail = db.CreateLocalTable(detailRecords))
	using (var subDetail = db.CreateLocalTable(subDetailRecords))
	{
		var query = 
			from m in master
			join d in detail on m.Id1 equals d.MasterId
			where m.Id1.In(1, 2)
			select m;

		query = query.LoadWith(m => m.Details);
		var result = query.ToArray();		
	}
}
```

m.Details should have to many items.

**Comment by sdanyliv** [comment]
I see, you have produced duplicates of main records and `LoadWith` made Cartesian explosion on details.
Let me see how we can avoid this without performance penalty.
