### ISSUE TITLE
System.InvalidCastException: 'Specified cast is not valid.' after migrate to 3.x.x from 2.9.8

### ISSUE THREAD

**Issue by Nelo-cool** [linq2db/linq2db#2415]
Hello guys! 
I recently migrated to a new version linq2db. After that, I encountered the fact that the previously working code stopped executing correctly. With very strange exception 'Specified cast is not valid.' 
Please, help me:)
```
Exception message:
System.InvalidCastException: 'Specified cast is not valid.'
Stack trace:    
at LinqToDB.Linq.QueryRunner.SetParameters(Query query, Expression expression, IDataContext parametersContext, Object[] parameters, Int32 queryNumber)
   at LinqToDB.Linq.QueryRunnerBase.SetCommand(Boolean clearQueryHints)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass33_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Thisislogic.Gtrk.Manager.Commands.Impl.PageUpdateCommandHandler.UpdateObject(Int64 id, PageUpdateCommand command) in D:\Work\Thisislogic.Ivteleradio\Source-Common\Thisislogic.Gtrk.Manager\Commands\Impl\PageUpdateCommandHandler.cs:line 85
```

### Steps to reproduce
My entities:
```c#
 public abstract class EntityWithIdentity : Entity
    {
        [PrimaryKey, Identity]
        public override long Id { get; set; }
    }

    [Table(Name = "Object", IsColumnAttributeRequired = false)]
    public class ObjectEntity : EntityWithIdentity
    {
        public long ObjectTypeId;
        public long UserId;
        public bool Active;
        public int Order;
        public string Name;
        public DateTime CreationDate;
        public DateTime EditDate;
        public DateTime StartDate;
        public long? ParentId;
        public bool Deleted;

        [Association(ThisKey = nameof(ObjectTypeId), OtherKey = nameof(Id), CanBeNull = false)]
        public ObjectType ObjectType;

        [Association(ThisKey = nameof(ParentId), OtherKey = nameof(Id), CanBeNull = true)]
        public ObjectEntity Parent;
        [Association(ThisKey = nameof(UserId), OtherKey = nameof(Id), CanBeNull = false)]
        public User User;

        [Association(ThisKey = nameof(Id), OtherKey = nameof(Id), CanBeNull = false)]
        public Page Page;

        [Association(ThisKey = nameof(Id), OtherKey = nameof(Impl.ObjectFlag.ObjectId), CanBeNull = true)]
        public ObjectFlag ObjectFlag;

        [Association(ThisKey = nameof(Id), OtherKey = nameof(Impl.ObjectCategoryItem.ObjectId), CanBeNull = true)]
        public ObjectCategoryItem ObjectCategoryItem;

        [Association(ThisKey = nameof(Id), OtherKey = nameof(Id), CanBeNull = true)]
        public Video Video;

        [Association(ThisKey = nameof(Id), OtherKey = nameof(Id), CanBeNull = true)]
        public Audio Audio;

        [Association(ThisKey = nameof(Id), OtherKey = nameof(Impl.Image.PageId), CanBeNull = true)]
        public Image Image;
    }

And my simple query for update:

var query = _db.Object
                .Where(x => x.Id == id)
                .Set(x => x.UserId, user.UserId)
                .Set(x => x.Active, command.Object.Active)
                .Set(x => x.Order, command.Object.Order)
                .Set(x => x.Name, x => command.Object.Name)
                .Set(x => x.StartDate, command.Object.StartDate);

            if (command.ParentId != null)
            {
                query = query.Set(x => x.ParentId, command.ParentId);
            }

            query.Update(); <---- throw exception
```

### Environment details
linq2db version: *3.0.1*
Database Server: *MS SQL 2016*
Database Provider: *SqlServer*
Operating system: *Windows 10*
.NET Framework: *4.8*

**Comment by sdanyliv** [comment]
@Nelo-cool, could you please check latest build https://dev.azure.com/linq2db/linq2db/_packaging?_a=feed&feed=linq2db
I can not reproduce issue. 
Or specify command class, maybe something wrong with types.

**Comment by Nelo-cool** [comment]
Simple classes :( Later I will check on the last build and publish the result

` public abstract class PageCommonCommand : IBaseCommand
    {
        public ObjectDescriptor Object;
        public PageDescriptor Page;

        public VideoDescriptor Video;
        public AudioDescriptor Audio;

        public ObjectFlagDescriptor[] Flags;
        public ObjectCategoryItemDescriptor[] CategoryItems = { };
        public ObjectTagDescriptor[] Tags = { };
        public GalleryImageDescriptor[] Images = { };
    }

public class PageUpdateCommand : PageCommonCommand
    {
        public long Id;
        public long? ParentId;
    }

public class ObjectDescriptor
    {
        public string Name;
        public bool Active;
        public long Order;
        public DateTime StartDate;
    }
`

**Comment by sdanyliv** [comment]
Let me know how it works with current version. We have did a lot of fixes in that area.
Anyway you can try this workaround if we can not fix it until this Thurthday.
```cs

var query = _db.Object
                .Where(x => x.Id == id)
                .Set(x => x.UserId, x => user.UserId)
                .Set(x => x.Active, x => command.Object.Active)
                .Set(x => x.Order, x => command.Object.Order)
                .Set(x => x.Name, x => command.Object.Name)
                .Set(x => x.StartDate, x => command.Object.StartDate);

            if (command.ParentId != null)
            {
                query = query.Set(x => x.ParentId, x => command.ParentId);
            }
```

**Comment by MaceWindu** [comment]
This issue is already fixed in master and fix will be released on Thursday

**Comment by MaceWindu** [comment]
But in any case, I would recommed you to change your code - updating int column with long value will work only if value fits into int range

**Comment by Nelo-cool** [comment]
Oh, thanks! It is my trouble after convert project to new version. Should be int everywhere! Thanks!
