### ISSUE TITLE
LoadWith exception in WebApi Core 3.1 

### ISSUE THREAD

**Issue by RoyChase** [linq2db/linq2db#2442]
If I try to return an object with an association using LoadWith from an ApiController 3.1 I am getting the following exception

```
System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IDataContext context, IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.AsyncEnumeratorImpl`1.MoveNextAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, Object asyncEnumerable, Func`2 reader)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeFilterPipelineAsync()
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)
```
### Steps to reproduce
See test app: https://github.com/RoyChase/ApiTest

```c#
        [HttpGet]
        public ActionResult<IQueryable<Customer>> Get()
        {
            var data =_ctx.GetTable<Customer>().LoadWith(c => c.Emails);

            //var dummy = data.ToList();

            return Ok(data);
        }
```

If I uncomment ```var dummy = data.ToList();``` then the exception is not thrown and the method returns the correct data even though the return is over the original IQueryable and not the materialised list.

The same method works without problems on netcoreapp2.1.

I'm guessing that it isn't a Linq2Db issue as such but any help in diagnosing the issue would be great.

Thanks

### Environment details
linq2db version: 3.1.0
Database Server: doesn't matter
Database Provider: doesn't matter. Tried with SQL Server and SQLite
Operating system: Windows 10
.NET Framework: netcoreapp31.

**Comment by MaceWindu** [comment]
That's a bug in eager load support for IAsyncEnumerator<T>, will be fixed in next version
