### ISSUE TITLE
SelectMany with Take produced invalid SQL

### ISSUE THREAD

**Issue by voronov-maxim** [linq2db/linq2db#2470]
SelectMany with Take thrown exception
```
Exception message:
Microsoft.Data.SqlClient.SqlException: 'Не удалось привязать составной идентификатор "t1.Count_1".
Не удалось привязать составной идентификатор "t1.Id".
Не удалось привязать составной идентификатор "t1.OrderId".
Не удалось привязать составной идентификатор "t1.Price".
Не удалось привязать составной идентификатор "t1.Product".'
Stack trace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DbCommandProcessor.DbCommandProcessorExtensions.ExecuteReaderExt(IDbCommand cmd, CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__12`1.MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at OdataToEntity.Test.Linq2Db.Program.<Main>d__0.MoveNext() in D:\vorona\OdataToEntity\test\OdataToEntity.Test.Linq2Db\Program.cs:line 21
```

### Steps to reproduce
```c#
[Table(Schema = "dbo", Name = "Orders")]
public class Order
{
    [PrimaryKey, Identity] public int Id { get; set; }
    [Column, NotNull] public string Name { get; set; }

    [Association(ThisKey = "Id", OtherKey = "OrderId", CanBeNull = true, IsBackReference = true)]
    public IEnumerable<OrderItem> Items { get; set; }
}

[Table(Schema = "dbo", Name = "OrderItems")]
public class OrderItem
{
    [PrimaryKey, Identity] public int Id { get; set; }
    [Column, NotNull] public int OrderId { get; set; }
    [Column, NotNull] public string Product { get; set; }

    [Association(ThisKey = "OrderId", OtherKey = "Id", CanBeNull = false, KeyName = "FK_OrderItem_Order", BackReferenceName = "Items")]
    public Order Order { get; set; }
}

public class OdataToEntityDB : LinqToDB.Data.DataConnection
{
    public ITable<Order> Orders { get { return this.GetTable<Order>(); } }
    public ITable<OrderItem> OrderItems { get { return this.GetTable<OrderItem>(); } }

    public OdataToEntityDB()
        : base("Microsoft.Data.SqlClient", @"Server=.\sqlexpress;Initial Catalog=OdataToEntity;Trusted_Connection=Yes;")
    {
    }
}

static void Main()
{
    var context = new OdataToEntityDB();
    var result = context.Orders
        .GroupJoin(
            context.Orders.SelectMany(
                Order => context.OrderItems
                    .Where(OrderItem => Order.Id == OrderItem.OrderId)
                    .OrderBy(orderItem => orderItem.Id)
                    .Take(1)
                    ),
            Order => Order.Id,
            OrderItem => OrderItem.OrderId,
            (outer, inner) => new { outer, inner })
        .SelectMany(
            t => t.inner.DefaultIfEmpty(),
            (source, collection) => new { source.outer, collection })
        .ToArray();
}
```
Produce sql
```sql
(@take int)SELECT
	[t].[Id],
	[t].[Name],
	[t1].[Id],
	[t1].[OrderId],
	[t1].[Product]
FROM
	[dbo].[Orders] [t]
		LEFT JOIN (
			SELECT
				[t1].[OrderId] as [collection]
			FROM
				[dbo].[Orders] [cp]
					CROSS APPLY (
						SELECT TOP (@take)
							[OrderItem].[OrderId],
							[OrderItem].[Id],
							[OrderItem].[Product]
						FROM
							[dbo].[OrderItems] [OrderItem]
						WHERE
							[cp].[Id] = [OrderItem].[OrderId]
						ORDER BY
							[OrderItem].[Id]
					) [t1]
		) [t2] ON [t].[Id] = [t2].[collection]
```

Old version 2.9.8 produce valid sql.

### Environment details
linq2db version: 3.1.2
Database Server: SqlServer
Database Provider: Microsoft.Data.SqlClient
Operating system: Windows 10 Pro 2004
.NET Framework: .net 5.0 preview 8

**Comment by sdanyliv** [comment]
Please post valid SQL. Just for eye validation. I can not parse your LINQ query ;)

**Comment by voronov-maxim** [comment]
linq2db 2.9.8
```sql
SELECT
	[t].[Id],
	[t].[Name],
	[t2].[Id],
	[t2].[collection],
	[t2].[Product]
FROM
	[dbo].[Orders] [t]
		LEFT JOIN (
			SELECT
				[t1].[OrderId] as [collection],
				[t1].[Id],
				[t1].[Product]
			FROM
				[dbo].[Orders] [cp]
					CROSS APPLY (
						SELECT TOP (1)
							[OrderItem].[OrderId],
							[OrderItem].[Id],
							[OrderItem].[Product]
						FROM
							[dbo].[OrderItems] [OrderItem]
						WHERE
							[cp].[Id] = [OrderItem].[OrderId]
						ORDER BY
							[OrderItem].[Id]
					) [t1]
		) [t2] ON [t].[Id] = [t2].[collection]```

**Comment by sdanyliv** [comment]
Rewriting LINQ query for myself.
```cs
var query = 
    from order in context.Orders
    select new 
    {
        Order = order,
        OrderItem = context.OrderItems
                    .Where(orderItem => order.Id == orderItem.OrderId)
                    .OrderBy(orderItem => orderItem.Id)
                    .FirstOrDefault()
    };
```
