### ISSUE TITLE
Can't generate data context with t4 template. PostgreSQL + MySql

### ISSUE THREAD

**Issue by almika777** [linq2db/linq2db#2485]
First i added ```linq2db.postgresql (3.1.0)``` and generated the context with the t4 template and everything worked fine. after adding ```linq2db.mysql (3.1.0)``` and ```mysql.data (8.0.21)``` to the project, the same context stopped generating and falls off with an error in the ```GenerateModel()``` method in T4 template.

Stack trace:
```   
Microsoft.VisualStudio.TextTemplatingA5208046AF2043F523FADEBCEC39E89AD7C755BFB4575C9DACB89B9BC71CF16FD3DD7FEC14C137FA1F177710ACD95EE8B411A25F37E08636F44DA95190DC0880. GeneratedTextTransformation.TransformText() in C:\Project\statistics.tt:line 51
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.PerformTransformation()
```
![image](https://user-images.githubusercontent.com/47299790/93113149-433f2c00-f6d2-11ea-8c51-be2cc6426db0.png)

**Comment by sdanyliv** [comment]
Looks like a mix of templates. For PostgreSql there is its own template with proper includes. Just copy needed template for new model.

**Comment by almika777** [comment]
```
<#@ template language="C#" debug="True" hostSpecific="True"                            #>
<#@ output extension=".generated.cs"                                                   #>
<#@ include file="$(LinqToDBT4PostgreSQLTemplatesDirectory)LinqToDB.PostgreSQL.Tools.ttinclude" #>
<#@ include file="$(LinqToDBT4PostgreSQLTemplatesDirectory)PluralizationService.ttinclude"      #>
<# //@ include file="$(ProjectDir)LinqToDB.Templates\LinqToDB.PostgreSQL.Tools.ttinclude" #>
<# //@ include file="$(ProjectDir)LinqToDB.Templates\PluralizationService.ttinclude"      #>
<#
	/*
		1. Create new *.tt file (e.g. MyDatabase.tt) in a folder where you would like to generate your data model
		   and copy content from this file to it. For example:

			MyProject
				DataModels
					MyDatabase.tt

		2. Modify the connection settings below to connect to your database.

		3. Add connection string to the web/app.config file:

			<connectionStrings>
				<add name="MyDatabase" connectionString="Server=MyServer;Port=5432;Database=MyDatabase;User Id=postgres;Password=TestPassword;Pooling=true;MinPoolSize=10;MaxPoolSize=100;Protocol=3;" providerName="PostgreSQL" />
			</connectionStrings>

		4. To access your database use the following code:

			using (var db = new MyDatabaseDB())
			{
				var q =
					from c in db.Customers
					select c;

				foreach (var c in q)
					Console.WriteLine(c.ContactName);
			}

		5. See more at https://linq2db.github.io/articles/T4.html

		IMPORTANT: if running .tt file gives you error like this:
		"error : Failed to resolve include text for file: C:\...\$(LinqToDBT4<SOME_DB>TemplatesDirectory)LinqToDB.<DB_NAME>.Tools.ttinclude"
		check tt file properties.
		Custom tool must be set to TextTemplatingFileGenerator, not TextTemplatingFilePreprocessor or any other value.
	*/

	NamespaceName = "Namespace";
	DataContextName = "Db";
	GenerateConstructors = false;
	GenerateDataTypes = true;
	GenerateLengthProperty = false;
	GeneratePrecisionProperty = false;
	GenerateScaleProperty = false;
	GenerateBackReferences = false;

	LoadPostgreSQLMetadata("localhost", "5432", "dbName", "postgres", "password");

	GenerateModel();
#>
```
It's my PostgreSQL template. 
I copied it from ```Linq2db.Templates``` and changed the line with ```LoadPostgreSQLMetadata``` method parameters.

**Comment by MaceWindu** [comment]
`linq2db.<DBNAME>` nuget packages doesn't support multiple packages in same project. If you need to use T4 templates with multiple different databases, you should use `linq2db.t4models` package instead

**Comment by almika777** [comment]
Thanks. U helped me a lot. U are was right

**Comment by MaceWindu** [comment]
problem here is that we use tools location msbuild property with same name for all packages, so when multiple packages installed, property reference tools folder for last installed package. In theory we can refactor it to use unique names.

**Comment by MaceWindu** [comment]
That's quite strange that this "issue" existed for a long time, but this week we had 3 reports already.
In that case I will assign it to next release: we will try to fix it or update nugets to generate build error if multiple incompatible nugets installed.
