### ISSUE TITLE
Associations with Concat/Union or other Set operations are not supported after migrate to 3.x.x from 2.9.8

### ISSUE THREAD

**Issue by Nelo-cool** [linq2db/linq2db#2503]
Hello guys! Thanks for your work!

After that, I encountered the fact that the previously working code stopped executing correctly. In the code is executed Union operator with slightly complex queries than usual. A few joins (left and inner) with using Association attribute ([Association(ThisKey = nameof(Id), OtherKey = nameof(ObjectId), CanBeNull = true)]) with parameters - time interval and other simple params.

Please, help me:)
```
Exception message: Associations with Concat/Union or other Set operations are not supported.
Stack trace:
 at LinqToDB.Linq.Builder.SetOperationBuilder.SetOperationContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SetOperationBuilder.cs:line 404
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SelectContext.cs:line 173
   at LinqToDB.Linq.Builder.PassThroughContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\PassThroughContext.cs:line 38
   at LinqToDB.Linq.Builder.SetOperationBuilder.SetOperationContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SetOperationBuilder.cs:line 408
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 183
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass79_0.<BuildExpression>b__0(Expression expr) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 52
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in D:\a\1\s\Source\LinqToDB\Expressions\Extensions.cs:line 1371
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 52
   at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 422
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 60
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 373
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass79_0.<BuildExpression>b__0(Expression expr) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 52
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in D:\a\1\s\Source\LinqToDB\Expressions\Extensions.cs:line 1371
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias) in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 52
   at LinqToDB.Linq.Builder.SetOperationBuilder.SetOperationContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SetOperationBuilder.cs:line 368
   at LinqToDB.Linq.Builder.SetOperationBuilder.SetOperationContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter) in D:\a\1\s\Source\LinqToDB\Linq\Builder\SetOperationBuilder.cs:line 276
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in D:\a\1\s\Source\LinqToDB\Linq\Builder\ExpressionBuilder.cs:line 173
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in D:\a\1\s\Source\LinqToDB\Linq\Query.cs:line 532
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in D:\a\1\s\Source\LinqToDB\Linq\Query.cs:line 494
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in D:\a\1\s\Source\LinqToDB\Linq\ExpressionQuery.cs:line 75
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in D:\a\1\s\Source\LinqToDB\Linq\ExpressionQuery.cs:line 304
   at System.Linq.SystemCore_EnumerableDebugView`1.get_Items()
```
### Steps to reproduce

```c#
var  resultQuery = popularsQuery.Union(query)
                    .OrderByDescending(x => x.IsPopular)
                    .ThenByDescending(x => x.NumberOfViews);
```

### Environment details
linq2db version: 3.1.3
Database Server: MS SQL 2016
Database Provider: SqlServer
Operating system: Windows 10
.NET Framework: 4.8

**Comment by sdanyliv** [comment]
In which version it works?

**Comment by Nelo-cool** [comment]
Maybe 2.9.8, but I'm not sure, I'll recheck

**Comment by Firebie** [comment]
Is this related to https://github.com/linq2db/linq2db/issues/2461 ?

**Comment by Nelo-cool** [comment]
Maybe, very similar to, I will tell you later today

**Comment by Nelo-cool** [comment]
Oh. This is related to https://github.com/linq2db/linq2db/issues/2461.  After i rewrote code to manual joins everything started working. Any hope to see an implementation using [Association] in future?

**Comment by sdanyliv** [comment]
Yes, I have plans for that. Association were completely rewritten in 3.0 but Concat/Union marked as not supported.

**Comment by Nelo-cool** [comment]
Thanks! Maybe is there anything I can do for you?

**Comment by sdanyliv** [comment]
Not sure, we have to extract association functionality to base class. Too complicated thing.

**Comment by Nelo-cool** [comment]
Okay, listen, we'll get out of your way :)))

**Comment by sdanyliv** [comment]
Associations refactoring took one month of my free time, but now they handles any query as association.

@Nelo-cool, actually you can help if you pickup some "non complex" issue ;) 
For example https://github.com/linq2db/linq2db/issues/1591
