### ISSUE TITLE
Transaction got promoted into Distributed Transaction and failed.

### ISSUE THREAD

**Issue by sydwebdesign** [linq2db/linq2db#2507]
We are using Linq2DB in our .NET Core 3.1 application with these settings:

- AllowMultipleQuery = true, so as to use LoadWith()
- Use `AddLinqToDbContext()` to set up IoC. The lifetime of the DataConnection is by-default per scope.
- We create a root TransactionScope before instantiating a DataConnection object. The inner code also uses TransactionScope to form a nested TransactionScope hierarchy.

The code randomly threw an exception:

```
Exception message:This platform does not support distributed transactions.
Stack trace:  at System.Transactions.Distributed.DistributedTransactionManager.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)
 at System.Transactions.TransactionInterop.GetDistributedTransactionFromTransmitterPropagationToken(Byte[] propagationToken)
 at System.Transactions.TransactionStatePSPEOperation.PSPEPromote(InternalTransaction tx)
 at System.Transactions.TransactionStateDelegatedBase.EnterState(InternalTransaction tx)
 at System.Transactions.EnlistableStates.Promote(InternalTransaction tx)
 at System.Transactions.Transaction.Promote()
 at System.Transactions.TransactionInterop.ConvertToDistributedTransaction(Transaction transaction)
 at System.Transactions.TransactionInterop.GetExportCookie(Transaction transaction, Byte[] whereabouts)
 at Microsoft.Data.SqlClient.SqlInternalConnection.GetTransactionCookie(Transaction transaction, Byte[] whereAbouts)
 at Microsoft.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
 at Microsoft.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)
 at Microsoft.Data.SqlClient.SqlInternalConnectionTds.Activate(Transaction transaction)
 at Microsoft.Data.ProviderBase.DbConnectionInternal.ActivateConnection(Transaction transaction)
 at Microsoft.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
 at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
 at Microsoft.Data.ProviderBase.DbConnectionPool.WaitForPendingOpen()
--- End of stack trace from previous location where exception was thrown ---
 at LinqToDB.Data.DataConnection.EnsureConnectionAsync(CancellationToken cancellationToken)
```

A separate exception log shows where the procedure breaks:

```
The operation is not valid for the state of the transaction.
at System.Transactions.TransactionState.EnlistPromotableSinglePhase(InternalTransaction tx, IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Transaction atomicTransaction, Guid promoterType)\n at System.Transactions.Transaction.EnlistPromotableSinglePhase(IPromotableSinglePhaseNotification promotableSinglePhaseNotification, Guid promoterType)
 at System.Transactions.Transaction.EnlistPromotableSinglePhase(IPromotableSinglePhaseNotification promotableSinglePhaseNotification)
 at Microsoft.Data.SqlClient.SqlInternalConnection.EnlistNonNull(Transaction tx)
 at Microsoft.Data.SqlClient.SqlInternalConnection.Enlist(Transaction tx)
 at Microsoft.Data.SqlClient.SqlInternalConnectionTds.Activate(Transaction transaction)
 at Microsoft.Data.ProviderBase.DbConnectionInternal.ActivateConnection(Transaction transaction)
 at Microsoft.Data.ProviderBase.DbConnectionPool.PrepareConnection(DbConnection owningObject, DbConnectionInternal obj, Transaction transaction)
 at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, UInt32 waitForMultipleObjectsTimeout, Boolean allowCreate, Boolean onlyOneCheckConnection, DbConnectionOptions userOptions, DbConnectionInternal& connection)
 at Microsoft.Data.ProviderBase.DbConnectionPool.TryGetConnection(DbConnection owningObject, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal& connection)
 at Microsoft.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
 at Microsoft.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
 at Microsoft.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
 at Microsoft.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry, SqlConnectionOverrides overrides)
 at Microsoft.Data.SqlClient.SqlConnection.Open(SqlConnectionOverrides overrides)
 at Microsoft.Data.SqlClient.SqlConnection.Open()
 at LinqToDB.Async.AsyncDbConnection.Open()
 at LinqToDB.Data.DataConnection.EnsureConnection()
 at LinqToDB.Data.DataConnection.get_Connection()
 at LinqToDB.Data.DataConnection.CreateCommand()
 at LinqToDB.Data.DataConnection.get_Command()
 at LinqToDB.Data.DataConnection.QueryRunner.Dispose()
 at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, Func`5 skipAction, Func`5 takeAction, CancellationToken cancellationToken)
 at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass4_0`1.<<GetFirstOrDefaultElement>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
 at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
 at Order.API.Services.PatientService.Get(String id, CancellationToken token) in /src/Order.API/Services/PatientService.cs:line 72
 at Order.API.QueryHandlers.PostProcedureHandler.Handle(PostProcedure request, CancellationToken cancellationToken) in /src/Order.API/QueryHandlers/PostProcedureHandler.cs:line 48
 at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestExceptionActionProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestPostProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at MediatR.Pipeline.RequestPreProcessorBehavior`2.Handle(TRequest request, CancellationToken cancellationToken, RequestHandlerDelegate`1 next)
 at Order.API.Controllers.ProcedureController.Post(PostProcedureRequest request) in /src/Order.API/Controllers/ProcedureController.cs:line 33
 at lambda_method(Closure , Object )
 at Microsoft.Extensions.Internal.ObjectMethodExecutorAwaitable.Awaiter.GetResult()
 at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
 at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
 at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
 at Order.API.Middlewares.BasicAuthMiddleware.Invoke(HttpContext context) in /src/Order.API/Middlewares/BasicAuthMiddleware.cs:line 43
 at Order.API.Middlewares.LogRequestMiddleware.InvokeAsync(HttpContext context) in /src/Order.API/Middlewares/LogRequestMiddleware.cs:line 36
 at Microsoft.AspNetCore.Server.Kestrel.Core.Internal.Http.HttpProtocol.ProcessRequests[TContext](IHttpApplication`1 application)
```

### Steps to reproduce
This is the hard part, we haven't been able to reliably reproduce it. We didn't expect in such a setting, the code would promote to use a Distributed Transaction:

- Root TransactionScope
    - DataConnection
        - PatientService.Get()
        - Inner TransactionScope
        - Inner TransactionScope

As per the second exception log, the code flow breaks at the first query made to the DB (`ProcedureHandler.Handle()` -> `PatientService.Get()`) as a simple Get query *without* using `LoadWith()`.

I have also tried to reproduce the problem by deliberately setting the DataConnection lifetime to Transient. The code flow did throw the same two exceptions on the second query (passed the first query). This is understandable as two DataConnection objects were instantiated. However, it doesn't explain why the first query would result in the exceptions. 

I see two previous relevant issues:
1. https://github.com/linq2db/linq2db/issues/2471 This solves TransactionScope and LoadWith() issue. However, I see the changes include `EnsureConnection` which exists in the exception callstack.
2. https://github.com/linq2db/linq2db/issues/962 This issue describes very similar situation where a TransactionScope was promoted into Distributed Transaction.

Would you please shed some light on this issue? Could the change in fixing 2471 (adding EnsureConnection) have any chance to create a new DataConnection, and resulted in Distributed Transaction?

### Environment details
linq2db version: 3.1.3
Database Server: SQL Server 2017 container
Database Provider: Microsoft.Data.SqlClient
Operating system: ASP.NET Core 3.1 container (where the exception was emitted from)
.NET Framework: .NET Core 3.1

**Comment by sdanyliv** [comment]
@linq2db/developers, can someone handle this?

**Comment by MaceWindu** [comment]
As I understand, issue here is that transaction is promoted to distributed, when it shouldn't? As .net core [doesn't support](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Transactions.Local/src/System/Transactions/DistributedTransaction.cs#L8) distributed transactions.

From stack I see that it happens here, because two connections created inside of one transaction scope.
I will try to analyze stack traces to understand why it could happen, but let's first exclude obvious case when linq2db would create new connection. We create new (cloned) connection when there is client-side `GroupBy` materialization, which will happen only if you allowed it by disabling groupby-guard [LinqToDB.Common.Configuration.Linq.GuardGrouping](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Common/Configuration.cs#L159).

**Comment by MaceWindu** [comment]
Second stack fails in data connection trace logging code. I see following points:
- disable data connection tracing could probably be a workaround
- we shouldn't create connection object if it doesn't exists for logging purposes
- still need to figure out why connection is missing at that point

**Comment by MaceWindu** [comment]
@sydwebdesign,

could you change data connection tracing from Info/Verbose to warning to avoid exception from traces? Looks like it hides actual error you have.

**Comment by MaceWindu** [comment]
`DataConnection.TraceSwitch.Level = TraceLevel.Warning`

**Comment by sydwebdesign** [comment]
Thank you, @MaceWindu for your reply. Really appreciated your time looking into this. Hopefully we can find out why. Just to clarify:

> As I understand, issue here is that transaction is promoted to distributed, when it shouldn't? As .net core [doesn't support](https://github.com/dotnet/runtime/blob/master/src/libraries/System.Transactions.Local/src/System/Transactions/DistributedTransaction.cs#L8) distributed transactions.
> 
> From stack I see that it happens here, because two connections created inside of one transaction scope.
> I will try to analyze stack traces to understand why it could happen, but let's first exclude obvious case when linq2db would create new connection. We create new (cloned) connection when there is client-side `GroupBy` materialization, which will happen only if you allowed it by disabling groupby-guard [LinqToDB.Common.Configuration.Linq.GuardGrouping](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Common/Configuration.cs#L159).

I was troubleshooting the issue by altering the lifetime of DataConnection IoC from Scoped to Trascient. It's designed to use the Scoped lifetime so as to achieve a single DataConnection instance per API call. The stack of the DataConnection and TransactionScope can be described as:

- Root TransactionScope
    - DataConnection
        - PatientService.Get()
        - Inner TransactionScope
        - Inner TransactionScope

I suppose in that setting, .NET Core shouldn't incur a Distributed Transaction but attach the only DataConnection to the root TransactionScope. The thing that can't be explained is that the first-ever DB query: `PatientService.Get()` (a simple `FirstOrDefaultAsync()` query on a table) got promoted into Distributed Transaction. It behaved like there was another DataConnection object registered under the root TransactionScope. The code snippet that went up to the PatientService.Get() was:

Controller
```
[HttpPost]
public async Task<long> Post(PostProcedureRequest request)
{
    using var transactionScope = TransactionScopeHelper.CreateReadCommit();
    var result = await _mediator.Send(_autoMapper.Map<PostProcedure>(request));
    transactionScope.Complete();
    return result;
}
```

MediatR Handler
```
public async Task<long> Handle(PostProcedure request, CancellationToken cancellationToken)
{
    // some logging code
    var patient = await _patientService.Get(request.Patient.PatientID, cancellationToken);
   // Other code
}
```

PatientService
```
public async Task<Patient> Get(string id, CancellationToken token = default)
{
     var patient = await _ordersConnection.Patients.FirstOrDefaultAsync(p => p.Id == id, token);
      return patient;
}
```

DataConnection IoC registration
```
services.AddLinqToDbContext<OrdersConnection>((provider, options) =>
{
    var builder = new SqlConnectionStringBuilder
    {
        DataSource = Configuration["DB:DataSource"],
        InitialCatalog = Configuration["DB:InitialCatalog"],
        UserID = Configuration["DB:UserId"],
        Password = Configuration["DB:Password"]
    };

    options
        .UseConnectionString(SqlServerProviderAdapter.MicrosoftClientNamespace, builder.ConnectionString)
        .UseMappingSchema(OrdersConnection.GenerateMappings())
        .UseDefaultLogging(provider);
    // OrdersConnection is set to Scope lifetime for having one instance per API call.
});
LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
```

The hard part is that this error only occurred once in a remote environment (it hasn't gone into production, so the volume is low, so as the chance to hit the exception). I'll try to tweak the DataConnection trace level to see if I can find anything useful for troubleshooting.

Thanks again.

**Comment by MaceWindu** [comment]
@sydwebdesign, I've fixed logging for next release to not create new connection, this will solve unexpected distributed transaction creation from logger, so next time this happens - you will get real exception. I will close this issue for now. Feel free to reopen if you will have more details on underlying issue.
