### ISSUE TITLE
PostgresSQL. Delete with Take

### ISSUE THREAD

**Issue by MeNoln** [linq2db/linq2db#2549]
### Stack trace:
```
18:38:34|Error|ServersWorker|42601: ошибка синтаксиса (примерное положение: "LIMIT") Npgsql.PostgresException (0x80004005): 42601: ошибка синтаксиса (примерное положение: "LIMIT")
at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken)
at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken)
at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
at LinqToDB.LinqExtensions.DeleteAsync[T](IQueryable`1 source, CancellationToken token)
at Services.Services.Servers.ServerDeletion.DeleteMt5Deals(Int32 serverId) in C:\Services\Servers\ServerDeletion.cs:line 97
at Services.Services.Servers.ServerDeletion.DeleteMt5(Server mt5Server) in C:\Services\Servers\ServerDeletion.cs:line 36
at Services.Services.Servers.ServerDeletion.DeleteServer(Server server) in C:\Services\Servers\ServerDeletion.cs:line 29
at Core.Workers.ServersWorker.ExecuteAsync(CancellationToken stoppingToken) in C:\Services\Servers\ServerDeletion.cs:line 41
Exception data:
Severity: ОШИБКА
SqlState: 42601
MessageText: ошибка синтаксиса (примерное положение: "LIMIT")
Position: 63
File: scan.l
Line: 1149
Routine: scanner_yyerror
```

### Steps to reproduce
This query causes error above:
```
deleted = await _context.Deals
                    .Where(w => w.ServerId == serverId)
                    .Take(_chunkSize)
                    .DeleteAsync();
```
Generated SQL:
```
DECLARE @serverId Integer -- Int32
SET @serverId = 1
DECLARE @take Integer -- Int32
SET @take = 10000

DELETE FROM
"public".deals w
WHERE
w.server_id = :serverId
LIMIT :take
```

Without Take() it works fine.

### Environment details
linq2db installed packages:
```
<PackageReference Include="linq2db" Version="3.1.0" />
<PackageReference Include="linq2db.AspNet" Version="3.1.0" />
<PackageReference Include="linq2db.t4models" Version="3.1.0" />
```
Database Provider: PostgreSQL 12
Operating system: Win10
.NET Framework: netcoreapp3.1

**Comment by MaceWindu** [comment]
Are there any reason why you apply Take to query in first place?

**Comment by MeNoln** [comment]
No, i just need to delete data by chunk.

Replaced Take such like this:
```
deleted = await _context.Deals
                    .Take(_chunkSize)
                    .Where(w => w.ServerId == serverId)
                    .DeleteAsync();
```
SQL:
```
DECLARE @take Integer -- Int32
SET     @take = 10000
DECLARE @serverId Integer -- Int32
SET     @serverId = 1

DELETE FROM
        (
                SELECT
                        t1.server_id
                FROM
                        "public".deals t1
                LIMIT :take
        ) w
WHERE
        w.server_id = :serverId
```
And still an error:
```
18:54:45|Error|ServersWorker|42601: ошибка синтаксиса (примерное положение: "(") Npgsql.PostgresException (0x80004005): 42601: ошибка синтаксиса (примерное положение: "(")
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at LinqToDB.LinqExtensions.DeleteAsync[T](IQueryable`1 source, CancellationToken token)
   at BBI.Services.Services.Servers.ServerDeletion.DeleteMt5Deals(Int32 serverId) in C:\work\brokerbusinessintelligence\BBI.Services\Services\Servers\ServerDeletion.cs:line 97
   at BBI.Services.Services.Servers.ServerDeletion.DeleteMt5(Server mt5Server) in C:\work\brokerbusinessintelligence\BBI.Services\Services\Servers\ServerDeletion.cs:line 36
   at BBI.Services.Services.Servers.ServerDeletion.DeleteServer(Server server) in C:\work\brokerbusinessintelligence\BBI.Services\Services\Servers\ServerDeletion.cs:line 29
   at BBI.Core.Workers.ServersWorker.ExecuteAsync(CancellationToken stoppingToken) in C:\work\brokerbusinessintelligence\BBI.Core\Workers\ServersWorker.cs:line 41
  Exception data:
    Severity: ОШИБКА
    SqlState: 42601
    MessageText: ошибка синтаксиса (примерное положение: "(")
    Position: 15
    File: scan.l
    Line: 1149
    Routine: scanner_yyerror

```

**Comment by MaceWindu** [comment]
you should be able to delete it using filter by top 10 ids (if you have unique single-column id in this table)
```
_context.Deals
                    .Where(_ => _context.Deals
                                          .Take(_chunkSize)
                                          .Select(w => w.Id).Contains(_.Id))
                    .DeleteAsync();
```

**Comment by MeNoln** [comment]
> you should be able to delete it using filter by top 10 ids (if you have unique single-column id in this table)
> 
> ```
> _context.Deals
>                     .Where(_ => _context.Deals
>                                           .Take(_chunkSize)
>                                           .Select(w => w.Id).Contains(_.Id))
>                     .DeleteAsync();
> ```

Worked for me. Thanks!
How I would able to know if you will support just Delete with Take clause?
Or its imposiible? =(

**Comment by viceroypenguin** [comment]
@MaceWindu (@sdanyliv) The original code works correctly on the SQL Server side. It translates to the sql below (used a table I had laying around). We translate the select to an inner query and then execute the delete on that. I'll do some research to see what the equiv PS code looks like.

```sql
DELETE [t1]
FROM
	(
		SELECT TOP (@take)
			*
		FROM
			[dbo].[Security] [s]
		WHERE
			[s].[Name] <> N''asdf''
	) [t1]
```

**Comment by viceroypenguin** [comment]
@MeNoln You might also try the following:
```csharp
deleted = await _context.Deals
                    .Take(_chunkSize)
                    .Where(w => w.ServerId == serverId)
                    .AsCte()
                    .DeleteAsync();
```

Looks like PostgreSQL does support deleting from a CTE, at least according to docs. This might result in a simpler plan for the optimizer.

**Comment by MeNoln** [comment]
> @MeNoln You might also try the following:
> 
> ```cs
> deleted = await _context.Deals
>                     .Take(_chunkSize)
>                     .Where(w => w.ServerId == serverId)
>                     .AsCte()
>                     .DeleteAsync();
> ```
> 
> Looks like PostgreSQL does support deleting from a CTE, at least according to docs. This might result in a simpler plan for the optimizer.

```
19:20:27|Error|ServersWorker|42P01: отношение "CTE_1" не существует Npgsql.PostgresException (0x80004005): 42P01: отношение "CTE_1" не существует
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlConnector.<>c__DisplayClass160_0.<<DoReadMessage>g__ReadMessageLong|0>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming)
   at Npgsql.NpgsqlCommand.ExecuteReaderAsync(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at LinqToDB.LinqExtensions.DeleteAsync[T](IQueryable`1 source, CancellationToken token)
   at BBI.Services.Services.Servers.ServerDeletion.DeleteMt5Deals(Int32 serverId) in C:\work\brokerbusinessintelligence\BBI.Services\Services\Servers\ServerDeletion.cs:line 105
   at BBI.Services.Services.Servers.ServerDeletion.DeleteMt5(Server mt5Server) in C:\work\brokerbusinessintelligence\BBI.Services\Services\Servers\ServerDeletion.cs:line 35
   at BBI.Services.Services.Servers.ServerDeletion.DeleteServer(Server server) in C:\work\brokerbusinessintelligence\BBI.Services\Services\Servers\ServerDeletion.cs:line 28
   at BBI.Core.Workers.ServersWorker.ExecuteAsync(CancellationToken stoppingToken) in C:\work\brokerbusinessintelligence\BBI.Core\Workers\ServersWorker.cs:line 41
  Exception data:
    Severity: ОШИБКА
    SqlState: 42P01
    MessageText: отношение "CTE_1" не существует
    Position: 200
    File: d:\pginstaller_12.auto\postgres.windows-x64\src\backend\parser\parse_relation.c
    Line: 1194
    Routine: parserOpenTable
```

**Comment by viceroypenguin** [comment]
@MeNoln Ah. Sorry! Good times trying to read docs and interpret what dbs will do.

**Comment by sdanyliv** [comment]
Looks like it is "easy" to transform https://stackoverflow.com/questions/5170546/how-do-i-delete-a-fixed-number-of-rows-with-sorting-in-postgresql

**Comment by szguoxz** [comment]
After two years, still not fixed? I thought it's an easy fix.
YEs, I can write delete(x=>idquery.take(100).contains(x.id)), but it's much more elegant to write query.take(100).delete(). besides it worked on SQL server. :-)
Any plan to update the postgresql driver?
I found a lot linqtodb syntax does not work on postgresql. Upinsert won't work either. Seems postgresql for linqtodb is not quite ready?

Calvin
