### ISSUE TITLE
Connection pooling / concurrency issue "already in use" on MySQL adapter

### ISSUE THREAD

**Issue by AdamFrisby** [linq2db/linq2db#2567]
Hi there - 

I'm seeing some intermittent errors in our logs complaining about connections being in use. I'm assuming this should be solved through built-in pooling/connection management.

```
2020-10-21 03:45:18,033 ERROR Exception fired when (doing something) -> System.AggregateException: One or more errors occurred. (This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse)
 ---> System.InvalidOperationException: This MySqlConnection is already in use. See https://fl.vu/mysql-conn-reuse
   at MySqlConnector.Core.ServerSession.StartQuerying(ICancellableCommand command) in /_/src/MySqlConnector/Core/ServerSession.cs:line 244
   at MySqlConnector.Core.CommandExecutor.ExecuteReaderAsync(IReadOnlyList`1 commands, ICommandPayloadCreator payloadCreator, CommandBehavior behavior, IOBehavior ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 57
   at MySqlConnector.MySqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlCommand.cs:line 302
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, Func`5 skipAction, Func`5 takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at OurCode(...)

```

### Steps to reproduce

Occurring during this line;

```c#
return await RSDB.TableName.Where(t => t.X == X).ToListAsync();
```

Which occurs during an async call.

Connection is declared as:

```c#
                var builder = new LinqToDbConnectionOptionsBuilder();
                builder.UseMySql(_config.MySQLConnectionString);
                
                RSDB = new CustomDatabaseClass(builder.Build());
```

And:

```c#
    class CustomDatabaseClass : DataConnection
    {
        public CustomDatabaseClass(LinqToDbConnectionOptions build) : base(build)
        {

        }

        public ITable<X> TableName => GetTable<XType>();
    }
```

### Environment details
linq2db version: 3.1.4
Database Server: MySQL
Database Provider: linq2db.MySqlConnector / MySqlConnector
Operating system: Ubuntu LTS
.NET Framework: .NET Core 3.1

**Comment by sdanyliv** [comment]
Looks like you have not disposed your connection.
https://linq2db.github.io/articles/general/Managing-data-connection.html

**Comment by AdamFrisby** [comment]
Thanks, knew it must be something stupid.
