### ISSUE TITLE
SqlServer metadata timeout 

### ISSUE THREAD

**Issue by Alvic** [linq2db/linq2db#257]
В большой базе данных (1000+таблиц, 32000+ полей) при попытке генерации схемы с помощью t4 template происходит таймаут.

```
Timeout expired.  The timeout period elapsed prior to completion of the operation or the server is not responding. ---> System.ComponentModel.Win32Exception (0x80004005): Время ожидания операции истекло
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TrySetMetaData(_SqlMetaDataSet metaData, Boolean moreInfo)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.CommandInfo.<Query>d__5`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LinqToDB.DataProvider.SqlServer.SqlServerSchemaProvider.GetForeignKeys(DataConnection dataConnection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
...
```

Ошибка происходит при выполнении запроса получения связей таблиц.
Запрос выполняется за 33 секунды - стандартного таймаута 30 секунд не хватает.

Также профайлер SQL Server показал, что долго выполняется запрос:

```sql
SELECT
	TABLE_CATALOG + '.' + TABLE_SCHEMA + '.' + TABLE_NAME as TableID,
	COLUMN_NAME                                           as Name,
	CASE WHEN IS_NULLABLE = 'YES' THEN 1 ELSE 0 END       as IsNullable,
	ORDINAL_POSITION                                      as Ordinal,
	c.DATA_TYPE                                           as DataType,
	CHARACTER_MAXIMUM_LENGTH                              as Length,
	ISNULL(NUMERIC_PRECISION, DATETIME_PRECISION)         as [Precision],
	NUMERIC_SCALE                                         as Scale,
	ISNULL(CONVERT(varchar(8000), x.Value), '')           as [Description],
	COLUMNPROPERTY(object_id('[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']'), COLUMN_NAME, 'IsIdentity') as IsIdentity,
	CASE WHEN c.DATA_TYPE = 'timestamp' THEN 1 ELSE 0 END as SkipOnInsert,
	CASE WHEN c.DATA_TYPE = 'timestamp' THEN 1 ELSE 0 END as SkipOnUpdate
FROM
	INFORMATION_SCHEMA.COLUMNS c
	LEFT JOIN
		sys.extended_properties x
	ON
		OBJECT_ID('[' + TABLE_CATALOG + '].[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']') = x.major_id AND
		ORDINAL_POSITION = x.minor_id AND
		x.name = 'MS_Description'
```

Выполняется порядка 50 секунд.
Если в данном запросе поменять OBJECT_ID('[' + TABLE_CATALOG + '].[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']') на OBJECT_ID('[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']'), то он выполняется за 1 секунду.
Аналогично во всех остальных запросах метаданных - исключение TABLE_CATALOG из аргумента функции OBJECT_ID существенно ускорит запросы.

**Comment by Alvic** [comment]
Если поменять запрос 
SELECT
	rc.CONSTRAINT_NAME                                             as Name,
	fk.TABLE_CATALOG + '.' + fk.TABLE_SCHEMA + '.' + fk.TABLE_NAME as ThisTableID,
	fk.COLUMN_NAME                                                 as ThisColumn,
	pk.TABLE_CATALOG + '.' + pk.TABLE_SCHEMA + '.' + pk.TABLE_NAME as OtherTableID,
	pk.COLUMN_NAME                                                 as OtherColumn,
	pk.ORDINAL_POSITION                                            as Ordinal
FROM
	INFORMATION_SCHEMA.REFERENTIAL_CONSTRAINTS rc
	JOIN
		INFORMATION_SCHEMA.KEY_COLUMN_USAGE fk
	ON
		--fk.CONSTRAINT_CATALOG = rc.CONSTRAINT_CATALOG AND
		fk.CONSTRAINT_SCHEMA  = rc.CONSTRAINT_SCHEMA  AND
		fk.CONSTRAINT_NAME    = rc.CONSTRAINT_NAME
	JOIN
		INFORMATION_SCHEMA.KEY_COLUMN_USAGE pk
	ON
		--pk.CONSTRAINT_CATALOG = rc.UNIQUE_CONSTRAINT_CATALOG AND
		pk.CONSTRAINT_SCHEMA  = rc.UNIQUE_CONSTRAINT_SCHEMA  AND
		pk.CONSTRAINT_NAME    = rc.UNIQUE_CONSTRAINT_NAME
WHERE
	fk.ORDINAL_POSITION = pk.ORDINAL_POSITION
ORDER BY
	ThisTableID,
	Ordinal

на

SELECT fk.name CONSTRAINT_NAME, 
	DB_NAME() + '.' + SCHEMA_NAME(po.schema_id) + '.' + po.name as ThisTableID,
	pc.name as ThisColumn,
	DB_NAME() + '.' + SCHEMA_NAME(fo.schema_id) + '.' + fo.name as OtherTableID,
	fc.name as OtherColumn,
	fkc.constraint_column_id as Ordinal
FROM sys.foreign_keys fk
	inner join sys.foreign_key_columns fkc ON fk.object_id = fkc.constraint_object_id
	inner join sys.columns pc on fkc.parent_column_id = pc.column_id and fkc.parent_object_id = pc.object_id
	inner join sys.objects po on fk.parent_object_id = po.object_id
	inner join sys.columns fc on fkc.referenced_column_id = fc.column_id and fkc.referenced_object_id = fc.object_id
	inner join sys.objects fo on fk.referenced_object_id = fo.object_id
ORDER BY
	ThisTableID,
	Ordinal

то время выполнения на этой же БД изменится с 33 секунд на 1.
