### ISSUE TITLE
Using T4 Generated DataContext with .Net Core Dependency injection

### ISSUE THREAD

**Issue by Runaho** [linq2db/linq2db#2629]
Hello, i look the article for [Configuring LINQ To DB for ASP.Net Core](https://linq2db.github.io/articles/get-started/asp-dotnet-core/index.html#add-table-property-to-the-data-connection) and it's actually work.

But when i create generated context with t4.
Context Constructor dosn't have  (LinqToDbConnectionOptions<Class> options) : base(options).
I can add of course but i don't want to add because i can update the database and re-generate to datacontext later.

**Can i add diffrently to scope or can i fix this missing constructor error ?**

![lq1](https://user-images.githubusercontent.com/16222645/99246044-b28de500-2815-11eb-9448-eddccf7d9ffd.png)

### Codes

```c#
Startup.cs

        public void ConfigureServices(IServiceCollection services)
        {
            services.AddRazorPages();

            services.AddLinqToDbContext<NorthwindDB>((provider, options) =>
            {
                options
                    .UseSqlServer(Configuration.GetConnectionString("Default"))
                    .UseDefaultLogging(provider);
            });


  public void Configure(IApplicationBuilder app, IWebHostEnvironment env)
        {
            app.UseHttpsRedirection();
            app.UseStaticFiles();

            app.UseRouting();

            app.UseAuthorization();

            app.UseEndpoints(endpoints =>
            {
                endpoints.MapRazorPages();
            });

            using var scope = app.ApplicationServices.CreateScope();
            var dataConnection = scope.ServiceProvider.GetService<NorthwindDB>();
        }


```

### Environment details
linq2db version: 3.1.6
Database Server: MSSQL Local
Operating system: Win 10
.NET Framework: Core 3.1

```
Exception message: System.ArgumentException: 'Missing constructor accepting 'LinqToDbContextOptions' on type NorthwindDB'
Stack trace:    at LinqToDB.AspNet.ServiceConfigurationExtensions.CheckContextConstructor[TContext]()
   at LinqToDB.AspNet.ServiceConfigurationExtensions.AddLinqToDbContext[TContext,TContextImplementation](IServiceCollection serviceCollection, Action`2 configure, ServiceLifetime lifetime)
   at LinqToDB.AspNet.ServiceConfigurationExtensions.AddLinqToDbContext[TContext](IServiceCollection serviceCollection, Action`2 configure, ServiceLifetime lifetime)
   at LQTODBCORE.Startup.ConfigureServices(IServiceCollection services) in C:\Users\LookusGunes\source\repos\LQTODBCORE\LQTODBCORE\Startup.cs:line 32
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor, Boolean wrapExceptions)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.InvokeCore(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass9_0.<Invoke>g__Startup|0(IServiceCollection serviceCollection)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.Invoke(Object instance, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.ConfigureServicesBuilder.<>c__DisplayClass8_0.<Build>b__0(IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.UseStartup(Type startupType, HostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass12_0.<UseStartup>b__0(HostBuilderContext context, IServiceCollection services)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at LQTODBCORE.Program.Main(String[] args) in \LQTODBCORE\Program.cs:line 16
```

**Comment by MaceWindu** [comment]
T4 templates generate context as partial class for this reason: to allow you extend it with additional members.

But I think it makes sense to generate this constructor by default.

**Comment by Runaho** [comment]
Thank you for the answer, as I understand it, I have no choice but to wait for the new version right now.

> T4 templates generate context as partial class for this reason: to allow you extend it with additional members.
> 
> But I think it makes sense to generate this constructor by default.

**Comment by MaceWindu** [comment]
No, you just need to add additional file with code like that:
```cs
partial class <YOUR_CONTEXT_CLASS_NAME_HERE>
{
    public <CLASS_NAME> (LinqToDbConnectionOptions options) : base(options) {}
}
```

https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods

**Comment by Runaho** [comment]
Yes it's work thanks a lot 👍🏻 

> No, you just need to add additional file with code like that:
> 
> ```cs
> partial class <YOUR_CONTEXT_CLASS_NAME_HERE>
> {
>     public <YOUR_CONTEXT_CLASS_NAME_HERE> (LinqToDbConnectionOptions options) : base(options) {}
> }
> ```
> 
> replace `<YOUR_CONTEXT_CLASS_NAME_HERE>` with name of your data context class
> 
> https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/partial-classes-and-methods
