### ISSUE TITLE
Exception: There is already an open DataReader associated with this Command which must be closed first 

### ISSUE THREAD

**Issue by BenoitStutz** [linq2db/linq2db#2643]
.Net Version 4.6.1
Microsoft.Data.SqlClient 2.01
linq2db 3.1.6

**With Oracle:**
no Problem
**With SQL-Server:**
Exception: There is already an open DataReader associated with this Command which must be closed first.

**Code:**
```cs
using (DbContext dbContext = new DbContext(dbProvider))
{
  IEnumerable<string> list = dbContext.MENUS_LOG.Select(obj => obj.DATATYPE).Distinct();
   foreach(string strItem in list)
   {
      dbContext.MENUS_LOG.Where(objWhere => objWhere.DATATYPE == strItem)
                .Update(dbContext.MENUS_LOG, objWhere => new MENUS_LOG{ DATATYPE = strItem + "X"});
   }
}
```

### DataProvider:
**Oracle:**
```cs
m_IDataProvider = new LinqToDB.DataProvider.Oracle.OracleDataProvider(ProviderName.OracleManaged,
LinqToDB.DataProvider.Oracle.OracleVersion.v12);
```

**SQL-Server:**
```cs
m_IDataProvider = new LinqToDB.DataProvider.SqlServer.SqlServerDataProvider(
ProviderName.SqlServer,
LinqToDB.DataProvider.SqlServer.SqlServerVersion.v2017,
LinqToDB.DataProvider.SqlServer.SqlServerProvider.MicrosoftDataSqlClient);
```

### ConnectionString:
**Oracle:**
```cs
@"USER ID=UserDummy;CONNECTION TIMEOUT=60;PASSWORD=XXXXXX;DATA SOURCE=PKSABNAHME12;STATEMENT CACHE SIZE=0;CONNECTION LIFETIME=0;INCR POOL SIZE=1;STATEMENT CACHE PURGE=True";
```

**SQL-Server:**
```cs
@"Data Source=MSTEST17\MSTEST17;Initial Catalog=DUMMYDB;Integrated Security=True;Connect Timeout=60;Multiple Active Result Sets=True;Multi Subnet Failover=True;";
```

**Exception:**
```
System.InvalidOperationException
HResult=0x80131509
Message=There is already an open DataReader associated with this Command which must be closed first.
Source=Microsoft.Data.SqlClient
StackTrace:
at Microsoft.Data.SqlClient.SqlInternalConnectionTds.ValidateConnectionForExecute(SqlCommand command)
at Microsoft.Data.SqlClient.SqlConnection.ValidateConnectionForExecute(String method, SqlCommand command)
at Microsoft.Data.SqlClient.SqlCommand.ValidateCommand(String method, Boolean async)
at Microsoft.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry) at Microsoft.Data.SqlClient.SqlCommand.ExecuteNonQuery() at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command) at LinqToDB.Data.DataConnection.ExecuteNonQuery() at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryImpl(DataConnection dataConnection, PreparedQuery preparedQuery) at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery() at LinqToDB.DataContext.QueryRunner.ExecuteNonQuery() at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles) at LinqToDB.Linq.QueryRunner.<>c__DisplayClass32_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles) at LinqToDB.Linq.ExpressionQuery1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
at LinqToDB.LinqExtensions.Update[TSource,TTarget](IQueryable1 source, ITable1 target, Expression`1 setter)
```

**Comment by MaceWindu** [comment]
This is valid error. You cannot issue another query over connection, while previous one is still running.

You can fix it by fetching all data from first query using something like ToList or ToArray
```cs
foreach(string strItem in list.ToList())
```

**Comment by BenoitStutz** [comment]
Hi, 
I now this Solution, but why does it work on Oracle?

**Comment by MaceWindu** [comment]
This is provider-specific behavior. Looks like Oralce provider supports multiple queries over single connection.
Actually this also should work for sql server with MARS enabled for connection, but we need to tweak linq2db a bit for it to work.

@sdanyliv what do you think about allowing this scenario for MARS-enabled connections? We just need to discard old command if MARS enabled.

**Comment by BenoitStutz** [comment]
@sdanyliv what do you think about allowing this scenario for MARS-enabled connections? We just need to discard old command if MARS enabled.  => YES

**Comment by MaceWindu** [comment]
#2728

**Comment by ali-anapalar** [comment]
you are a perfect detail i was about to go crazy thank you
