### ISSUE TITLE
SQL Server - Collation conflict while generating data access classes

### ISSUE THREAD

**Issue by JechoJekov** [linq2db/linq2db#2663]
In cases when the collation of the catalog (`CATALOG_COLLATION` option of `CREATE DATABASE`) is different than the default collation of the database, the collation of the database name (catalog) is different than the collation of the names of the schema, tables, etc. The name of the database use the default database collation while the names of the objects in the database use the collation specified by `CATALOG_COLLATION`.

One reason for having different collations is to use a case-sensitive collation by default for the data and case-insensitive collation for the names of the database objects. For some unfathomable reason the collation is different for the database's name which means that it can be case-sensitive if the default collation is case-sensitive.

linq2db uses the following query to load the schema:

```SQL
SELECT
	TABLE_CATALOG + '.' + TABLE_SCHEMA + '.' + TABLE_NAME                          as TableID,
	TABLE_CATALOG                                                                  as CatalogName,
	TABLE_SCHEMA                                                                   as SchemaName,
	TABLE_NAME                                                                     as TableName,
	CASE WHEN TABLE_TYPE = 'VIEW' THEN 1 ELSE 0 END                                as IsView,
	ISNULL(CONVERT(varchar(8000), x.Value), '')                                    as Description,
	CASE WHEN TABLE_SCHEMA = 'dbo' THEN 1 ELSE 0 END                               as IsDefaultSchema
FROM
	INFORMATION_SCHEMA.TABLES s
	LEFT JOIN
		sys.tables t
	ON
		OBJECT_ID('[' + TABLE_CATALOG + '].[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']') = t.object_id
	LEFT JOIN
		sys.extended_properties x
	ON
		OBJECT_ID('[' + TABLE_CATALOG + '].[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']') = x.major_id AND
		x.minor_id = 0 AND 
		x.name = 'MS_Description'
WHERE
	t.object_id IS NULL OR
	t.is_ms_shipped <> 1 AND
	(
		SELECT
			major_id
		FROM
			sys.extended_properties
		WHERE
			major_id = t.object_id AND
			minor_id = 0           AND
			class    = 1           AND
			name     = N'microsoft_database_tools_support'
	) IS NULL
```

The only issue is `TABLE_CATALOG + '.' + TABLE_SCHEMA + '.' + TABLE_NAME                          as TableID` in the select list. For some reason concatenation in the where/ join clauses like `'[' + TABLE_CATALOG + '].[' + TABLE_SCHEMA + '].[' + TABLE_NAME + ']'` does not causes issues but if the same code is used in the select clause it fails as well.

```
Exception message: Running transformation: System.Data.SqlClient.SqlException (0x80131904): Cannot resolve collation conflict between "SQL_Latin1_General_CP1_CI_AS" and "Latin1_General_CS_AS" in add operator occurring in SELECT statement column 1.
Stack trace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.CommandInfo.Query[T]()
   at LinqToDB.DataProvider.SqlServer.SqlServerSchemaProvider.GetTables(DataConnection dataConnection, GetSchemaOptions options)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplating1E213238080D15AECAEB979979AF0A58078ABF80A66E492B230C73F49679FA23D127852169293D2E887909E4C7666554B2F6DD61704CB5887B9791CE9DF8712F.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection)
   at Microsoft.VisualStudio.TextTemplating1E213238080D15AECAEB979979AF0A58078ABF80A66E492B230C73F49679FA23D127852169293D2E887909E4C7666554B2F6DD61704CB5887B9791CE9DF8712F.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection)
   at Microsoft.VisualStudio.TextTemplating1E213238080D15AECAEB979979AF0A58078ABF80A66E492B230C73F49679FA23D127852169293D2E887909E4C7666554B2F6DD61704CB5887B9791CE9DF8712F.GeneratedTextTransformation.LoadSqlServerMetadata(String connectionString, SqlServerVersion version, SqlServerProvider provider)
   at Microsoft.VisualStudio.TextTemplating1E213238080D15AECAEB979979AF0A58078ABF80A66E492B230C73F49679FA23D127852169293D2E887909E4C7666554B2F6DD61704CB5887B9791CE9DF8712F.GeneratedTextTransformation.TransformText()

```

### Steps to reproduce

Create a new database and attempt to generate data model types.

```SQL
CREATE DATABASE [TEST]
CONTAINMENT = NONE
ON PRIMARY 
(NAME = N'TEST', FILENAME = N'...' , SIZE = 1024KB , MAXSIZE = UNLIMITED, FILEGROWTH = 1024KB)
LOG ON (NAME = N'TEST_log', FILENAME = N'...' , SIZE = 1024KB , MAXSIZE = 2048GB , FILEGROWTH = 10%)
COLLATE Latin1_General_CS_AS
WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS
GO

...
```

### Environment details
linq2db version: 3.1.6
Database Server: SQL Server 2019
Database Provider: Microsoft.Data.SqlClient
Operating system: Windows Server 2019
.NET Framework: .NET Core 3.1

**Comment by MaceWindu** [comment]
Looks like we already have fix (#1733) but apply it only to azure databases. We should do same for all sql server databases
