### ISSUE TITLE
SQLite.Ms wants to use System.Data.Sqlite in Release mode

### ISSUE THREAD

**Issue by Daveismus** [linq2db/linq2db#2680]
I use linq2db and linq2db.SQLite.MS. Compiling to Debug mode does not produce any Error.
But on doing this in Release mode, the first time it tries to create a DataConnection it shuts down with the Error below.

```
Exception message: 
System.InvalidOperationException
  HResult=0x80131509
  Nachricht = Cannot load assembly System.Data.SQLite
  Quelle = <Die Ausnahmequelle kann nicht ausgewertet werden.>
  Stapelüberwachung:
<Die Ausnahmestapelüberwachung kann nicht ausgewertet werden.>

Stack trace:
   at LinqToDB.DataProvider.SQLite.SQLiteProviderAdapter.CreateAdapter(String assemblyName, String clientNamespace, String prefix) in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteProviderAdapter.cs:line 52
   at LinqToDB.DataProvider.SQLite.SQLiteProviderAdapter.GetInstance(String name) in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteProviderAdapter.cs:line 78
   at LinqToDB.DataProvider.SQLite.SQLiteDataProvider..ctor(String name, MappingSchema mappingSchema) in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteDataProvider.cs:line 32
   at LinqToDB.DataProvider.SQLite.SQLiteDataProvider..ctor(String name) in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteDataProvider.cs:line 27
   at LinqToDB.DataProvider.SQLite.SQLiteTools.<>c.<.cctor>b__21_0() in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteTools.cs:line 17
   at System.Func`1.Invoke()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Lazy.cs:line 324
```

### Steps to reproduce
I use the code below to build my LinqToDbConnectionOptions. Nothing else has been used.

```c#
LinqToDB.Common.Configuration.Linq.AllowMultipleQuery = true;
            var connectionString = @"Data Source=internal.db";

            // create options builder
            var builder = new LinqToDbConnectionOptionsBuilder();

            // configure connection string
            builder.UseSQLite(connectionString);

            return builder.Build();
```

### Environment details
linq2db version: *3.1.6*
Database Server: *?*
Database Provider: *SQlite MS*
Operating system: *Windows*
.NET Framework: *.Net Standard 2.0*

**Comment by MaceWindu** [comment]
Looking at provider detection code, linq2db cannot detect which provider to use and defaults to `System.Data.Sqlite`. I will see if we can improve detection.
You can explicitly specify provider by replacing
```cs
builder.UseSQLite(connectionString);
```
with
```cs
builder.UseConnectionString(LinqToDB.ProviderName.SQLiteMS, connectionString);
```

**Comment by Daveismus** [comment]
Thanks, this fixes this, but another Error arrived:

Again only in Release mode. The First Linq Query (see below) raises the following exception.

```
Exception message: 
GetRuntimeInterfaceMap() is not supported on this runtime. | System.PlatformNotSupportedException


Stack trace:
at System.Reflection.Runtime.TypeInfos.RuntimeTypeInfo.GetInterfaceMap(Type interfaceType) in f:\\dd\\ndp\\fxcore\\CoreRT\\src\\System.Private.Reflection.Core\\src\\System\\Reflection\\Runtime\\TypeInfos\\RuntimeTypeInfo.cs:line 198\r\n   at LinqToDB.Reflection.TypeAccessor`1.<>c__DisplayClass0_0.<.cctor>b__3(Type ti) in D:\\a\\1\\s\\Source\\LinqToDB\\Reflection\\TypeAccessorT.cs:line 51\r\n   at Internal.Runtime.Augments.RuntimeAugments.CallDescrWorker(IntPtr callDescr) in f:\\dd\\ndp\\fxcore\\CoreRT\\src\\System.Private.CoreLib\\src\\Internal\\Runtime\\Augments\\RuntimeAugments.cs:line 969\r\n   at Internal.Runtime.TypeLoader.CallConverterThunk.InvokeTarget(Void* allocatedStackBuffer, CallConversionParameters& conversionParams)\r\n   at Internal.Runtime.Augments.RuntimeAugments.RawCalliHelper.Call[T](IntPtr pfn, Void* arg1, T& arg2)\r\n   at Internal.Runtime.Augments.RuntimeAugments.RunFunctionWithConservativelyReportedBufferInternal[T](Int32 cbBuffer, IntPtr pfnTargetToInvoke, T& context, ConservativelyReportedRegionDesc& regionDesc)\r\n   at Internal.Runtime.Augments.RuntimeAugments.RunFunctionWithConservativelyReportedBuffer[T](Int32 cbBuffer, IntPtr pfnTargetToInvoke, T& context)\r\n   at Internal.Runtime.TypeLoader.CallConverterThunk.CallConversionThunk(IntPtr callerTransitionBlockParam, IntPtr callConversionId)\r\n   at System.Linq.Enumerable.SelectManySingleSelectorIterator`2.MoveNext()\r\n   at System.Collections.Generic.List`1.AddEnumerable(IEnumerable`1 enumerable) in f:\\dd\\ndp\\fxcore\\CoreRT\\src\\System.Private.CoreLib\\shared\\System\\Collections\\Generic\\List.cs:line 1101\r\n   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)\r\n   at LinqToDB.Reflection.TypeAccessor`1..cctor() in D:\\a\\1\\s\\Source\\LinqToDB\\Reflection\\TypeAccessorT.cs:line 51\r\n   at System.Runtime.CompilerServices.ClassConstructorRunner.EnsureClassConstructorRun(StaticClassConstructionContext* pContext) in f:\\dd\\ndp\\fxcore\\CoreRT\\src\\System.Private.CoreLib\\src\\System\\Runtime\\CompilerServices\\ClassConstructorRunner.cs:line 92
   at LinqToDB.DataProvider.SQLite.SQLiteTools.<>c.<.cctor>b__21_0() in D:\a\1\s\Source\LinqToDB\DataProvider\SQLite\SQLiteTools.cs:line 17
   at System.Func`1.Invoke()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode) in f:\dd\ndp\fxcore\CoreRT\src\System.Private.CoreLib\shared\System\Lazy.cs:line 324
```

### Steps to reproduce
I had an simple query like the query below

```c#
var query = from k in db.Kunde
                            where i <= k.KundenId
                            where k.KundenId <= j
                            select k;
```

**Comment by MaceWindu** [comment]
Which framework you actually use? `netstandard2.0` is TFM and I see `Type.GetInterfaceMap` in list of supported APIs: https://raw.githubusercontent.com/dotnet/standard/master/docs/versions/netstandard2.0_ref.md

**Comment by MaceWindu** [comment]
I suspect you use UWP https://github.com/dotnet/efcore/issues/22159

**Comment by MaceWindu** [comment]
I don't currently see `GetRuntimeInterfaceMap` or `GetInterfaceMap` in provider code, so it is possible call from `linq2db` itself, which means we need to fix it on our side...

**Comment by Daveismus** [comment]
Yes I am using UWP

**Comment by MaceWindu** [comment]
#2819 will add more `Use<DB>` extensions, specifically `UseSQLiteMicrosoft` to help with wrong provider autodetection.

Looking into UWP issue.

**Comment by MaceWindu** [comment]
Which version  of UWP your project target? It should be at least 10.0.16299 (starting from this version UWP supports netstandard2.0).

I've used https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer to check which APIs are missing and see that this method supported starting from UWP 10.1. What is UWP 10.1 is another question (even msft employees don't know it: https://stackoverflow.com/questions/55670965/is-newtonsoft-not-supported-for-uwp-10-1#comment98064169_55670965).

**Comment by Daveismus** [comment]
I am targeting 10.0.18362.0 as minimum Version.

**Comment by MaceWindu** [comment]
That's sucks. I will try to get rid of this method, but I have no idea how to ensure that we don't have other APIs, missing from UWP as analyzer tool lies...

**Comment by MaceWindu** [comment]
Ok, current plan:
- check if it is easy to implement replacement for this method
- otherwise: replace this method with no-op implementation if it throws PNSE exception. this means no interface mappings for UWP

PS: spent some time reasearching this and actually I'm a amazed by number of tools Microsoft introduced to solve this issuse (detect unsupported API) and abandoned all of them (actually none of them work)

Some links:
- https://github.com/dotnet/corert/pull/8144 : PR that adds  GetInterfaceMap implementation to corert (to unknown version...)
- https://docs.microsoft.com/en-us/dotnet/standard/analyzers/portability-analyzer, https://github.com/Microsoft/dotnet-apiport : analyzer that is useless here as it doesn't take into account PNSE implementations (despite project description advertise it will solve this issue) and don't report proper UWP version
- https://docs.microsoft.com/en-us/windows/communitytoolkit/platform-specific/platformspecificanalyzer another analyzer that is abandoned and doesn't actually work (wasn't able to get any life signs from it)
- https://github.com/ljw1004/platform-specific-analyzer another abandoned project
-

**Comment by MaceWindu** [comment]
BTW, exception generated only from `corert` runtime (`Compile with .NET Native tool chain` option enabled for project).
