### ISSUE TITLE
There seems problems about tt script generate MySQL model

### ISSUE THREAD

**Issue by psliurt** [linq2db/linq2db#270]
I've installed MySQL 5.6 server on my Windows 7 OS.
I use Visual Studio 2010 to develop software and download the linq2db from NuGet.

After I Installed the "LINQ to DB" , "LINQ to DB T4 Models" and "LINQ to MySql" , I copy the "CopyMe.MySql.tt.txt" to the Models folder(I develop an  ASP.Net MVC project). Then I modify the file name to "CopyMe.MySql.tt" and modify the LoadMySqlMetadata method with correct data like below.

LoadMySqlMetadata("localhost", "world", "root", "mypassword");

the "world" database is default generated by MySQL installer.

After I modify the LoadMySqlMetadata Method and saved the .tt script file.

It generate some error like below.

---

錯誤  1   正在執行轉換: System.InvalidOperationException: 序列未包含項目
   於 System.Linq.Enumerable.Max(IEnumerable`1 source)
   於 System.Linq.Enumerable.Max[TSource](IEnumerable`1 source, Func`2 selector)
   於 Microsoft.VisualStudio.TextTemplating77DC7F2B06966E27F1DD4AC0DBECEEC6.GeneratedTextTransformation.GenerateTypesFromMetadata() 於 f:\VSProj\Linq2dbDemo\Linq2dbDemo\LinqToDB.Templates\LinqToDB.ttinclude: 行 205
   於 Microsoft.VisualStudio.TextTemplating77DC7F2B06966E27F1DD4AC0DBECEEC6.GeneratedTextTransformation.<>c__DisplayClass1.<TransformText>b__0() 於 f:\VSProj\Linq2dbDemo\Linq2dbDemo\LinqToDB.Templates\DataModel.ttinclude: 行 11
   於 Microsoft.VisualStudio.TextTemplating77DC7F2B06966E27F1DD4AC0DBECEEC6.GeneratedTextTransformation.GenerateModel() 於 f:\VSProj\Linq2dbDemo\Linq2dbDemo\LinqToDB.Templates\T4Model.ttinclude: 行 16
   於 Microsoft.VisualStudio.TextTemplating77DC7F2B06966E27F1DD4AC0DBECEEC6.GeneratedTextTransformation.TransformText() 於 f:\VSProj\Linq2dbDemo\Linq2dbDemo\Models\CopyMe.MySql.tt: 行 42
   於 Microsoft.VisualStudio.TextTemplating.TransformationRunner.RunTransformation(TemplateProcessingSession session, String source, ITextTemplatingEngineHost host, String& result)       1   1   

---

If I change the parameter of  LoadMySqlMetadata Method like below

LoadMySqlMetadata("localhost", "sakila", "root", "mypassword");

the error message would be different like below

---

錯誤  1   正在執行轉換: System.Data.SqlTypes.SqlNullValueException: 資料為 Null。無法在值為 Null 的情況下呼叫這個方法或屬性。
   於 MySql.Data.MySqlClient.MySqlDataReader.GetFieldValue(Int32 index, Boolean checkNull)
   於 MySql.Data.MySqlClient.MySqlDataReader.GetString(Int32 i)
   於 MySql.Data.MySqlClient.MySqlDataReader.GetString(String column)
   於 MySql.Data.MySqlClient.SchemaProvider.GetIndexColumns(String[] restrictions)
   於 MySql.Data.MySqlClient.SchemaProvider.GetSchemaInternal(String collection, String[] restrictions)
   於 MySql.Data.MySqlClient.ISSchemaProvider.GetSchemaInternal(String collection, String[] restrictions)
   於 MySql.Data.MySqlClient.SchemaProvider.GetSchema(String collection, String[] restrictions)
   於 MySql.Data.MySqlClient.MySqlConnection.GetSchema(String collectionName, String[] restrictionValues)
   於 MySql.Data.MySqlClient.MySqlConnection.GetSchema(String collectionName)
   於 LinqToDB.DataProvider.MySql.MySqlSchemaProvider.GetPrimaryKeys(DataConnection dataConnection)
   於 LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   於 Microsoft.VisualStudio.TextTemplatingD168C78C55D712AF43FE7C599FEF2E64.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) 於 f:\VSProj\Linq2dbDemo\Linq2dbDemo\LinqToDB.Templates\DataModel.ttinclude: 行 56
   於 Microsoft.VisualStudio.TextTemplatingD168C78C55D712AF43FE7C599FEF2E64.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) 於 f:\VSProj\Linq2dbDemo\Linq2dbDemo\LinqToDB.Templates\DataModel.ttinclude: 行 284
   於 Microsoft.VisualStudio.TextTemplatingD168C78C55D712AF43FE7C599FEF2E64.GeneratedTextTransformation.LoadMySqlMetadata(String server, String database, String uid, String password) 於 f:\VSProj\Linq2dbDemo\Linq2dbDemo\LinqToDB.Templates\LinqToDB.MySql.ttinclude: 行 28
   於 Microsoft.VisualStudio.TextTemplatingD168C78C55D712AF43FE7C599FEF2E64.GeneratedTextTransformation.TransformText() 於 f:\VSProj\Linq2dbDemo\Linq2dbDemo\Models\CopyMe.MySql.tt: 行 42
   於 Microsoft.VisualStudio.TextTemplating.TransformationRunner.RunTransformation(TemplateProcessingSession session, String source, ITextTemplatingEngineHost host, String& result)       1   1   

---

**Comment by victordeanda** [comment]
how did you solve this issue, im having the exact same problem

**Comment by victor84** [comment]
Set the schema that you want to import.
GetSchemaOptions.IncludedSchemas = new[] { "need_schema" };

**Comment by sdanyliv** [comment]
@psliurt, it is still needs our help?

**Comment by psliurt** [comment]
it solved, thanks

**Comment by shubham6396** [comment]
I am having the same problem.
can you please help me with this?
would be great help to me

**Comment by shubham6396** [comment]
> Set the schema that you want to import.
> GetSchemaOptions.IncludedSchemas = new[] { "need_schema" };

where to do this?

**Comment by MaceWindu** [comment]
You should put it into your tt file before `LoadMetadata` call

**Comment by shubham6396** [comment]
NamespaceName = "DataModels";
	GetSchemaOptions.IncludedSchemas = new[] { "smartstudentanalysis" };
	LoadMySqlMetadata(@"localhost", "smartstudentanalysis", "root", "111");
	

Like this?

**Comment by MaceWindu** [comment]
right

**Comment by shubham6396** [comment]
> right

still giving same error

**Comment by sdanyliv** [comment]
@shubham6396, please post full error message.

**Comment by shubham6396** [comment]
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: MySql.Data.MySqlClient.MySqlException (0x80004005): Unknown table 'parameters' in information_schema
   at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.CommandInfo.Query[T](Func`2 objectReader)
   at LinqToDB.DataProvider.MySql.MySqlSchemaProvider.GetProcedureParameters(DataConnection dataConnection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplating1BC58585BC1ACF67091107438DF30E84F8DD5ECD10940D4941388C2FBE2A31015BBFB44C981DAA107D7A6EC446CE21565069CE275A2B32106D29636E84BF2DE1.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in C:\Users\dell\source\repos\linq2db\packages\linq2db.MySql.2.5.3\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude:line 103
   at Microsoft.VisualStudio.TextTemplating1BC58585BC1ACF67091107438DF30E84F8DD5ECD10940D4941388C2FBE2A31015BBFB44C981DAA107D7A6EC446CE21565069CE275A2B32106D29636E84BF2DE1.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in C:\Users\dell\source\repos\linq2db\packages\linq2db.MySql.2.5.3\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude:line 415
   at Microsoft.VisualStudio.TextTemplating1BC58585BC1ACF67091107438DF30E84F8DD5ECD10940D4941388C2FBE2A31015BBFB44C981DAA107D7A6EC446CE21565069CE275A2B32106D29636E84BF2DE1.GeneratedTextTransformation.LoadMySqlMetadata(String server, String database, String uid, String password, Int32 port) in C:\Users\dell\source\repos\linq2db\packages\linq2db.MySql.2.5.3\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.MySql.ttinclude:line 28
   at Microsoft.VisualStudio.TextTemplating1BC58585BC1ACF67091107438DF30E84F8DD5ECD10940D4941388C2FBE2A31015BBFB44C981DAA107D7A6EC446CE21565069CE275A2B32106D29636E84BF2DE1.GeneratedTextTransformation.TransformText() in C:\Users\dell\source\repos\linq2db\linq2db\DataModels\smartstudentanalysis.tt:line 41	Miscellaneous Files	C:\Users\dell\source\repos\linq2db\packages\linq2db.MySql.2.5.3\build\..\contentFiles\any\any\LinqToDB.Templates\DataModel.ttinclude	103	


> @shubham6396, please post full error message.

**Comment by MaceWindu** [comment]
Can you create new issue with more details: linq2db version, mysql version, do you have `INFORMATION_SCHEMA.PARAMETERS` table in your database or not?
As I pointed out on SO, you can disable procedures load to workaround this issue

**Comment by sdanyliv** [comment]
@shubham6396, `parameters` table exists in MySQL 5.5 or newer.
I suggest to disable procedures generation
```cs
NamespaceName = "DataModels";
GetSchemaOptions.IncludedSchemas = new[] { "smartstudentanalysis" };
GetSchemaOptions.GetProcedures = false;
LoadMySqlMetadata(@"localhost", "smartstudentanalysis", "root", "111");
```

**Comment by shubham6396** [comment]
> GetSchemaOptions.IncludedSchemas = new[] { "smartstudentanalysis" }; GetSchemaOptions.GetProcedures = false;

if i do this tables are not auto generated

**Comment by shubham6396** [comment]
> Can you create new issue with more details: linq2db version, mysql version, do you have `INFORMATION_SCHEMA.PARAMETERS` table in your database or not?
> As I pointed out on SO, you can disable procedures load to workaround this issue

MySQL server 5.5
Linq2db-2.5.4
and i do not have information_schema.parameters but this table is auto generated and i want to skip this
while going through scehmas

**Comment by MaceWindu** [comment]
Once more:
you get this error during load of procedures schema due to missing information_schema.parameters view, which was added in MySQL 5.5.3. If you have lower version, you just need to disable procedures load using
```cs
GetSchemaOptions.GetProcedures = false;
```
If you don't see any tables after that, it means that your schema filter is not correct (`GetSchemaOptions.IncludedSchemas`) - remove it and then add proper filter later if it generates tables from unwanted schemas.
