### ISSUE TITLE
Question: Conversion of property for queryable

### ISSUE THREAD

**Issue by caliskanersin** [linq2db/linq2db#2712]
Hi , I keep pk at  db as Guid. However for UI I convert them to string . If i read records from db it works but if I send results as queryble  it does not works. I use odata for returning IQueryble.  In nibernate I can map one column to one guid property and one formula mapping (insert:false update:false) and I can manage entity filtering and sorting actions. 
How I can do that with linq2db. Calculated expression not works I tried.

```
Exception message:
Stack trace:

LinqToDB.Linq.LinqException: Expression 'o.IdHexString' is not a Field.
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.SelectContext.ConvertExpressions(Expression expression, ConvertFlags flags, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.SelectContext.ConvertMember(MemberInfo member, Expression expression, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.<>c__DisplayClass42_0.<ConvertToSql>b__3(KeyValuePair`2 m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.SelectManyIterator[TSource,TCollection,TResult](IEnumerable`1 source, Func`2 collectionSelector, Func`3 resultSelector)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass79_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass79_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.GetAsyncEnumerator(CancellationToken cancellationToken)
   at Microsoft.AspNetCore.Mvc.Infrastructure.AsyncEnumerableReader.ReadInternal[T](Object value)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ObjectResultExecutor.ExecuteAsyncEnumerable(ActionContext context, ObjectResult result, Object asyncEnumerable, Func`2 reader)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.InvokeResultFilters()
```

### Steps to reproduce
 
```c#

public class Operation
{
[PrimaryKey]
[Column(Name = "OPERATIONID")]
public Guid OperationId { get; set; }

[SkipValuesOnInsert(true)]
[SkipValuesOnUpdate(true)]
public string IdHexString
{
	get
	{
		return BitConverter.ToString(OperationId.ToByteArray()).Replace("-", string.Empty);
	}
}
}		
       //it works conversion is ok
	var results= snpDb
				.GetTable<Operation>()
				.ToArray();
	
	//it thows exception when client request
          return snpDb
				.GetTable<Operation>()
				.Select(o => new OperationInfo()
				{
					JobId = o.JobId,
					OperationId = o.OperationId,
					Name = o.Name,
					Description = o.Description,
					CompletedDate = o.CompleteDate,
					StartDate = o.StartDate,
					CreatedBy = o.CreatedBy,
					FailMessage = o.FailMessage,
					Progress = o.Progress,
					Status = o.Status,
					OperationIdHex = o.IdHexString
				})
				.AsQueryable();
		}

```

### Environment details
linq2db version: 3.2.1
Database Server: oracle
Database Provider: Oracle.ManagedDataAccess.Core" Version="2.19.100
Operating system: windows 10 x64
.NET Framework:  .net core 3.1.404

**Comment by sdanyliv** [comment]
Which type has `OperationId` in your database?

**Comment by caliskanersin** [comment]
OperationId  db type is DbType.Guid

**Comment by sdanyliv** [comment]
I'm asking about database name, oracle's name, not linq2db and CLR types. Also do you need filtering, sorting using IdHexString?

**Comment by caliskanersin** [comment]
oracle version Oracle Database 19c Enterprise Edition Release 19.0. Also I can use PostgreSQL 9.4.24 (Greenplum Database 6.10.1)

**Comment by sdanyliv** [comment]
Well, find time to look into database and check which column type has Guid. I assume it is `raw(16)`
Create extension class
```cs
public static class MyExtensions
{
	[Sql.Function("RAWTOHEX")]
	public static string ToHexString(this Guid guid)
	{
		return BitConverter.ToString(data).Replace("-", string.Empty);
	}
}
```
Then just use in your query:
```cs
return snpDb
	.GetTable<Operation>()
	.Select(o => new OperationInfo()
	{
		JobId = o.JobId,
		OperationId = o.OperationId,
		Name = o.Name,
		Description = o.Description,
		CompletedDate = o.CompleteDate,
		StartDate = o.StartDate,
		CreatedBy = o.CreatedBy,
		FailMessage = o.FailMessage,
		Progress = o.Progress,
		Status = o.Status,
		OperationIdHex = o.OperationId.ToHexString()
	});
```
It is much flexible than use property, but this also ca be solved:
```cs
public class Operation
{
	[PrimaryKey]
	[Column(Name = "OPERATIONID")]
	public Guid OperationId { get; set; }

	[ExpressionMethod(name(IdHexStringImpl))]
	public string IdHexString  => OperationId.ToHexString();

	static Expression<Func<Operation, string>> IdHexStringImpl()
		=> o => o.ToHexString();
}
```

**Comment by caliskanersin** [comment]
Thank you i will check it that way

**Comment by caliskanersin** [comment]
In postgresql  db data is "uuid" is there any function for it

**Comment by sdanyliv** [comment]
You have to update extension method:
```cs
public static class MyExtensions
{
	[ExpressionMethod(ProviderName.PostgreSQL, nameof(ToHexStringImpl))]
	[Sql.Function(ProviderName.Oracle, "RAWTOHEX")]
	public static string ToHexString(this Guid guid)
	{
		return BitConverter.ToString(guid.ToByteArray()).Replace("-", string.Empty);
	}

	static Expression<Func<Guid, string>> ToHexStringImpl()
	{
		return guid => Sql.ConvertTo<string>.From(guid).Replace("-", string.Empty);
	}
}
```

**Comment by caliskanersin** [comment]
thanks
