### ISSUE TITLE
Postgres T4 fail to run with Npgsql doesn't implement DisposeAync

### ISSUE THREAD

**Issue by sgwong** [linq2db/linq2db#2730]
### Environment details
linq2db version: 3.2.1
Database Server:  postgres
Database Provider: npgsql
Operating system: win64
.NET Framework: 4.7.2

The error only happened when I try to use T4 to generate code. If I run linq2db with postgres, it can run without issues. If I revert to older version which with the npgsql not implementing the DisposeAsync, it also can run without issues. I had tried to add
<#@ assembly name="$(LinqToDBT4PostgreSQLToolsDirectory)Microsoft.Bcl.AsyncInterfaces.dll" #>
and copy the dll to the tool directory but it still show the same error.

Error trace:
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.TypeLoadException: Method 'DisposeAsync' in type 'Npgsql.NpgsqlBinaryImporter' from assembly 'Npgsql, Version=4.1.7.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7' does not have an implementation.
   at System.Reflection.RuntimeAssembly.GetType(RuntimeAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at System.Reflection.Assembly.GetType(String name, Boolean throwOnError)
   at LinqToDB.DataProvider.PostgreSQL.NpgsqlProviderAdapter.GetInstance()
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider..ctor(String name, PostgreSQLVersion version)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.<>c.<.cctor>b__19_0()
   at System.Lazy`1.CreateValue()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.get_Value()
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.GetDataProvider(PostgreSQLVersion version)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.CreateDataConnection(String connectionString, PostgreSQLVersion version)
   at Microsoft.VisualStudio.TextTemplating2069EE733B0BAE88671472CEEF9D31FABF9E2AE14871C1BF1562B05B555C03E18FAC63908CACFBF94E418480AFF08B82C38DF65AB14A0D673FFE15A7556E7070.GeneratedTextTransformation.GetPostgreSQLConnection(String connectionString) in C:\Users\sgwon\source\repos\WpfApp2\packages\linq2db.PostgreSQL.3.2.1\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude:line 130
   at Microsoft.VisualStudio.TextTemplating2069EE733B0BAE88671472CEEF9D31FABF9E2AE14871C1BF1562B05B555C03E18FAC63908CACFBF94E418480AFF08B82C38DF65AB14A0D673FFE15A7556E7070.GeneratedTextTransformation.GetPostgreSQLConnection(String server, String port, String database, String uid, String password) in C:\Users\sgwon\source\repos\WpfApp2\packages\linq2db.PostgreSQL.3.2.1\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude:line 135
   at Microsoft.VisualStudio.TextTemplating2069EE733B0BAE88671472CEEF9D31FABF9E2AE14871C1BF1562B05B555C03E18FAC63908CACFBF94E418480AFF08B82C38DF65AB14A0D673FFE15A7556E7070.GeneratedTextTransformation.LoadPostgreSQLMetadata(String server, String port, String database, String uid, String password) in C:\Users\sgwon\source\repos\WpfApp2\packages\linq2db.PostgreSQL.3.2.1\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude:line 146
   at Microsoft.VisualStudio.TextTemplating2069EE733B0BAE88671472CEEF9D31FABF9E2AE14871C1BF1562B05B555C03E18FAC63908CACFBF94E418480AFF08B82C38DF65AB14A0D673FFE15A7556E7070.GeneratedTextTransformation.TransformText() in C:\Users\sgwon\source\repos\WpfApp2\Entity\PostgreSQL.tt:line 49	Miscellaneous Files	C:\Users\sgwon\source\repos\WpfApp2\packages\linq2db.PostgreSQL.3.2.1\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude	130

**Comment by MaceWindu** [comment]
Thanks. That's really strange error, will check what's wrong here.

**Comment by MaceWindu** [comment]
Problem is in VisualStudio. Looks like now it loads own copies of System.Threading.Tasks.Extensions.dll, Microsoft.Bcl.AsyncInterfaces.dll and we have two different copies of assembly, loaded in memory. We should load them only when it is not loaded already (to support older VS versions)
