### ISSUE TITLE
"x.MyProperty is not a Field" exception on update

### ISSUE THREAD

**Issue by ImoutoChan** [linq2db/linq2db#2735]
I'm trying to set up a simple model with a simple update method.

I call it like this: _context.Table.Set(x => x.MyProperty, false).UpdateAsync();

But I always get an error that "x.MyProperty is not a field" even before SQL request is sent.

```
Exception message:
x.MyProperty is not a Field

Stack trace:

   at LinqToDB.Linq.Builder.TableBuilder.TableContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.UpdateBuilder.ParseSet(ExpressionBuilder builder, LambdaExpression extract, MethodCallExpression updateMethod, Int32 valueIndex, IBuildContext select, List`1 items)
   at LinqToDB.Linq.Builder.UpdateBuilder.Set.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at LinqToDB.LinqExtensions.UpdateAsync[T](IUpdatable`1 source, CancellationToken token)
```

### Steps to reproduce
https://github.com/linq2db/linq2db/blob/b9cd78fd23fe6a4b25efdc3c4c7ec4870970e6c7/Source/LinqToDB/Linq/Builder/TableBuilder.TableContext.cs#L1322

I traced the problem back to this line, Fields collection is empty in my case, no matter how many properties I add to my model. So, what is the problem? 

Everything works fine if I just use raw SQL like this `_context.ExecuteAsync($"UPDATE Table SET MyProperty = 1")`.
I also tried with simple string property and got the same exception.

### Environment details
linq2db version: "linq2db.AspNet" Version="3.1.3"
Database Server: MS SQL
Database Provider: "System.Data.SqlClient" Version="4.8.2"
Operating system: windows 10
.NET Framework: net5.0

**Comment by sdanyliv** [comment]
Probably you have not set `[Column]` attribute for this property.

**Comment by sdanyliv** [comment]
Or you can set `[Table(IsColumnAttributeRequired = false)]` for whole entity.

**Comment by ImoutoChan** [comment]
Is it necessary in the new version? I used linq2db before and only remember to set it up only for specifying a different name.

**Comment by sdanyliv** [comment]
As I know this behaviour was not changed.
