### ISSUE TITLE
LoadWith with custom load query does not work if out of line

### ISSUE THREAD

**Issue by tolfino** [linq2db/linq2db#2755]
When the second argument of LoadWith is called using a custom query method, it doesn't work. However, substituting it with the body of that custom query method does work just fine.

```
Exception message: LinqToDB.Linq.LinqException: Sequence 'u' cannot be converted to SQL.
Stack trace:
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertSequence(BuildInfo buildInfo, ParameterExpression param, Boolean throwExceptionIfCantConvert)
   at LinqToDB.Linq.Builder.SelectBuilder.Convert(ExpressionBuilder builder, MethodCallExpression originalMethodCall, BuildInfo buildInfo, ParameterExpression param)
   at LinqToDB.Linq.Builder.MethodCallBuilder.Convert(ExpressionBuilder builder, BuildInfo buildInfo, ParameterExpression param)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertSequence(BuildInfo buildInfo, ParameterExpression param, Boolean throwExceptionIfCantConvert)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressionTree(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpressionImpl(Expression expr, HashSet`1 currentParameters)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass45_0.<OptimizeExpression>b__0(Expression e)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpression(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpressionImpl(Expression expr, HashSet`1 currentParameters)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass45_0.<OptimizeExpression>b__0(Expression e)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpression(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpressionImpl(Expression expr, HashSet`1 currentParameters)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass45_0.<OptimizeExpression>b__0(Expression e)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpression(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpressionImpl(Expression expr, HashSet`1 currentParameters)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass45_0.<OptimizeExpression>b__0(Expression e)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpression(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressionTree(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder..ctor(Query query, IDataContext dataContext, Expression expression, ParameterExpression[] compiledParameters)
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

#### Mapping classes and extensions

```c#
public partial class User
{
    [Column("id"),              PrimaryKey,  NotNull] public long           Id            { get; set; } // bigint
    [Column("created_at"),                   NotNull] public DateTimeOffset CreatedAt     { get; set; } // timestamp (6) with time zone
    [Column("name"),                         NotNull] public string         Name          { get; set; } // USER-DEFINED
}

public partial class User
{
    [NotMapped]
    public bool IsFollowing { get; set; }
}

public static class UserExtensions {
    public static IQueryable<User> WithIsFollowing(this IQueryable<User> users,
        IQueryable<Follow> follows,
        long? myUserId) {
        return users.Select(u => new User {
            Id = u.Id,
            CreatedAt = u.CreatedAt,
            Name = u.Name,
            IsFollowing = follows.Any(f =>
                f.FollowerUserId == myUserId && f.FollowedUserId == u.Id)
        });
    }
}
```

#### DOESN'T work
```c#
db.Posts.LoadWith(p => p.User, u => u.WithIsFollowing(db.Follows))
```

#### DOES work
If the body if WithIsFollowing is inlined directly into LoadWith, the query works fine.

```c#
db.Posts.LoadWith(p => p.User, u => u.Select(u => new User {
    Id = u.Id,
    CreatedAt = u.CreatedAt,
    Name = u.Name,
    IsFollowing = follows.Any(f =>
        f.FollowerUserId == myUserId && f.FollowedUserId == u.Id)
}))
```

### Additional notes

This seems to fail with any implementation of `WithIsFollowing` that modifies the query, e.g. `return users.Take(1)`. However, `return users` will work fine.

### Environment details
linq2db version: 3.2.2
Database Server: Postgres
Database Provider: Npgsql
Operating system: Windows 10
.NET Framework: .NET Core 5

**Comment by tolfino** [comment]
I see the issue now: my extension method doesn't match any of the predefined names supported by the builder: LinqToDB.Expressions.InternalExtensions is only able to see the direct method name being called and can't inspect the method body.

I don't know much about C# and Linq: is there a way to force the inlining of the method call?

**Comment by tolfino** [comment]
Never mind: turns out I was selecting from the table after a `Select`. Oops!
