### ISSUE TITLE
Expression translation fails with "cannot be converted to SQL"

### ISSUE THREAD

**Issue by uladz-zubrycki** [linq2db/linq2db#2900]
Expression cannot be converted to sql. Fails with exception

`'new <>f__AnonymousType1``1(Value = ToNotNull(aa.Value))' cannot be converted to SQL.`
```
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.SelectContext.ConvertExpressions(Expression expression, ConvertFlags flags, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.<>c__DisplayClass49_1.<ConvertToIndexInternal>b__3(KeyValuePair`2 m)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Enumerable.<SelectManyIterator>d__23`3.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryContext(IBuildContext context, MethodCallExpression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryExpression(IBuildContext context, MethodCallExpression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass79_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass79_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Repro.Program.Main(String[] args) in D:\dev\Repro\Program.cs:line 22
```

### Steps to reproduce

Model and select expression are created from the existing ones by removing irrelevant details and changing names, so could look stupid.

Data connection type is
```c#
public class DbContext : DataConnection
{
	public DbContext(LinqToDbConnectionOptions options) : base(options: options) { }
	public ITable<Request> Requests => GetTable<Request>();
}
```

Model is
```c#
[Table]
public class Request
{
	[PrimaryKey, Identity, Column]
	public int Id { get; set; }

	[Association(ThisKey = nameof(Id), OtherKey = nameof(Metric.RequestId))]
	public virtual ICollection<Metric> Metrics { get; set; }
}


[Table]
public class Metric
{
	[PrimaryKey, Identity, Column]
	public int Id { get; set; }

	[Column]
	public int RequestId { get; set; }

	[Column]
	public double? Value { get; set; }
}
```

Failing query is
```c#
var connectionString = "Data Source=.;Initial Catalog=Repro;Integrated Security=True; MultipleActiveResultSets=True";

var builder = new LinqToDbConnectionOptionsBuilder();
builder.UseSqlServer(connectionString);

var dbContext = new DbContext(builder.Build());

var failing = dbContext.Requests
	.Select(a => new
	{
		Metrics = a.Metrics
			.Select(aa => new
			{
				Value = aa.Value.HasValue 
					? new { Value = aa.Value.Value }
					: null,
			})
			.FirstOrDefault()
	})
	.ToArray();
```

It works if I remove `FirstOrDefault`, or if there is no ternary operator with `null` in the else branch, or if there is no `Select` nesting, i.e same expression applied on the `Metrics` table level directly. Like this
```c#
dbContext.Metrics
	.Select(aa => new
	{
		Value = aa.Value.HasValue
			? new { Value = aa.Value.Value }
			: null,
	})
	.FirstOrDefault();
```

But none of these options is acceptable for my scenario unfortunately.

Here is a solution to reproduce this issue:
[Repro.zip](https://github.com/linq2db/linq2db/files/6156088/Repro.zip)

### Environment details
linq2db version: 3.2.3
Database Server: MS SQL Server 14.0.1000
Database Provider: Default Sql Server provider, which is "SqlServer", I believe
Operating system: Windows 10.0.18363
.NET Framework: 4.8

**Comment by MaceWindu** [comment]
Fixed long time ago in v4.0.0
