### ISSUE TITLE
Unable to cast object of type 'Npgsql.NpgsqlConnection' to type 'Npgsql.NpgsqlTransaction'.

### ISSUE THREAD

**Issue by HypeillingerChillinger** [linq2db/linq2db#2901]
An exception is thrown on ```BeginTransactionAsync```

```
Exception message:
Stack trace:

"Unable to cast object of type 'Npgsql.NpgsqlConnection' to type 'Npgsql.NpgsqlTransaction'."

{System.InvalidCastException: Unable to cast object of type 'Npgsql.NpgsqlConnection' to type 'Npgsql.NpgsqlTransaction'.
   at lambda_method383(Closure , IDbConnection )
   at LinqToDB.Async.ReflectedAsyncDbTransaction.DisposeAsync()
   at LinqToDB.Data.DataConnection.BeginTransactionAsync(CancellationToken cancellationToken)
   at Accounting.Services.FileService.DeleteTempFilesExcept(Int64 userId, String exceptCustomIdentifier, IAccountingContext context) in /home/heidewitzka/WorkingDirectories/accounting/Backend/Services/Accounting/Accounting.Services/Services/File/FileService.cs:line 130}

```

### Steps to reproduce

```c#

  <ItemGroup>
    <PackageReference Include="linq2db" Version="3.2.3" />
    <PackageReference Include="linq2db.PostgreSQL" Version="3.2.3" />
  </ItemGroup>

public class AccountingContext : DataConnection,
        IAccountingContext,
        ICloneable,
        IDataContext,
        IEntityServices,
        IDisposable
    {
        public AccountingContext(string providerName, string connectionstring, MappingSchema mappingSchema)
        : base(providerName, connectionstring, mappingSchema)
        { }
}

    public class AccountingLinqToDbSettings : ILinqToDBSettings
    {
        protected string ConnectionString { get; set; }
        public AccountingLinqToDbSettings(string connectionString)
        {
            ConnectionString = connectionString;
        }

        public IEnumerable<IDataProviderSettings> DataProviders => Enumerable.Empty<IDataProviderSettings>();

        public string DefaultConfiguration => ProviderName.PostgreSQL;
        public string DefaultDataProvider => ProviderName.PostgreSQL;

        public IEnumerable<IConnectionStringSettings> ConnectionStrings
        {
            get
            {
                yield return
                new ConnectionStringSettings
                {
                    Name = ProviderName.PostgreSQL,
                    ProviderName = ProviderName.PostgreSQL,
                    ConnectionString = ConnectionString
                };
            }
        }
    }

AccountingContext.DefaultSettings = new AccountingLinqToDbSettings("Connection String");


var dataConnection = (DataConnection)context;

try
{
    using (var transaction = await dataConnection.BeginTransactionAsync())
     {
     }
 }
catch (Exception ex)
{
}
```

### Environment details
linq2db version: 3.2.3
Database Server: Postgres
Database Provider: *?*
Operating system: *?*
.NET Framework: Core 5

**Comment by MaceWindu** [comment]
Amazing... why it wasn't discovered before...

**Comment by HypeillingerChillinger** [comment]
Yes amazing - may be not too many use the async flavour of BeginTransaction. When do you plan to publish a new version?

**Comment by MaceWindu** [comment]
next thursday
