### ISSUE TITLE
Query with StringAggregate fails when used in Merge

### ISSUE THREAD

**Issue by RandScullard** [linq2db/linq2db#2918]
This is my model (abbreviated):
```
   public class PatentAssessment
   {
      [Key]
      public int PatentId { get; set; }
      public List<PatentAssessmentTechnicalReviewer> TechnicalReviewers { get; set; }
      public string TechnicalReviewersText { get; set; }
   }

   public class PatentAssessmentTechnicalReviewer
   {
      [ForeignKey("PatentAssessment")]
      public int PatentId { get; set; }
      public PatentAssessment PatentAssessment { get; set; }
      public int UserId { get; set; }
      public User User { get; set; }
   }

   public class User
   {
      [Key]
      public int Id { get; set; }
      [Required]
      [StringLength(300)]
      public string DisplayName { get; set; }
   }

```
When a user's DisplayName changes, I want to run the following Merge to update the TechnicalReviewersText field in each PatentAssessment where that user is assigned as a technical reviewer. (The TechnicalReviewersText field is a semicolon-delimited string with the DisplayNames of the users who are technical reviewers.)
```
   var qry =
      from pa in _dbContext.PatentAssessments
      where _dbContext.PatentAssessmentTechnicalReviewers
               .Any(patr => patr.UserId == userId && patr.PatentId == pa.PatentId)
      select new PatentAssessment
      {
         PatentId = pa.PatentId,
         TechnicalReviewersText =
            _dbContext.PatentAssessmentTechnicalReviewers.Include(patr => patr.User)
               .Where(patr => patr.PatentId == pa.PatentId)
               .StringAggregate("; ", patr => patr.User.DisplayName)
               .OrderBy(patr => patr.User.DisplayName)
               .ToValue()
      };

   var list = await qry.ToListAsyncLinqToDB();

   await _dbContext.PatentAssessments.ToLinqToDBTable()
      .Merge()
      .Using(qry)
      .OnTargetKey()
      .UpdateWhenMatched((target, source) => new PatentAssessment
      {
         TechnicalReviewersText = source.TechnicalReviewersText
      })
      .MergeAsync();
```
When I run this code, the statement that calls ToListAsyncLinqToDB works fine. (This statement is just test code that I added to test out the query by itself.) However, the Merge statement throws this exception:
```
LinqToDB.LinqToDBException: Member 'User' not found in type 'PatentAssessment'.
   at LinqToDB.Linq.Builder.SelectContext.GetProjectedExpression(MemberInfo memberInfo, Boolean throwOnError)
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T](Expression expression, MemberExpression levelExpression, Int32 level, Func`6 action)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToExtensionSql(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass129_0.<ConvertExtensionToSql>b__0(Expression e, ColumnDescriptor descriptor)
   at LinqToDB.Sql.ExtensionAttribute.BuildExtensionParam(IDataContext dataContext, SelectQuery query, MemberInfo member, Expression[] arguments, ConvertHelper convertHelper)
   at LinqToDB.Sql.ExtensionAttribute.BuildFunctionsChain(IDataContext dataContext, SelectQuery query, Expression expr, ConvertHelper convertHelper)
   at LinqToDB.Sql.ExtensionAttribute.GetExpression(IDataContext dataContext, SelectQuery query, Expression expression, Func`3 converter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExtensionToSql(IBuildContext context, ExpressionAttribute attr, MethodCallExpression mc)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.SelectContext.ConvertExpressions(Expression expression, ConvertFlags flags, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.MergeSourceQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSqlExpression(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.UpdateBuilder.<BuildSetterWithContext>g__BuildSetter|5_0(MemberExpression memberExpression, Expression expression, <>c__DisplayClass5_0& )
   at LinqToDB.Linq.Builder.UpdateBuilder.<BuildSetterWithContext>g__BuildMemberInit|5_2(MemberInitExpression expression, Expression path, <>c__DisplayClass5_0& )
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildSetterWithContext(ExpressionBuilder builder, BuildInfo buildInfo, LambdaExpression setter, IBuildContext into, List`1 items, IBuildContext[] sequences)
   at LinqToDB.Linq.Builder.MergeBuilder.UpdateWhenMatched.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MergeBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Patents.UserService.<AzureSync>b__13_0(IDbContextTransaction trans) in C:\RDS\intelliv8\patents\Services\UserService.cs:line 268
   at Patents.PatentsDbContext.<>c__DisplayClass51_0`1.<<BeginTransactionAsync>b__0>d.MoveNext() in C:\RDS\intelliv8\patents\Data\PatentsDbContext.cs:line 97
--- End of stack trace from previous location ---
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.Storage.ExecutionStrategy.ExecuteImplementationAsync[TState,TResult](Func`4 operation, Func`4 verifySucceeded, TState state, CancellationToken cancellationToken)
   at Patents.UserService.AzureSync() in C:\RDS\intelliv8\patents\Services\UserService.cs:line 182
   at Patents.UserController.AzureSync() in C:\RDS\intelliv8\patents\Controllers\UserController.cs:line 119
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.TaskOfIActionResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at Patents.CurrentUserMiddleware.InvokeAsync(HttpContext httpContext, PatentsDbContext dbContext, UserService userService) in C:\RDS\intelliv8\patents\Infrastructure\CurrentUserMiddleware.cs:line 38
   at Microsoft.AspNetCore.Authorization.Policy.AuthorizationMiddlewareResultHandler.HandleAsync(RequestDelegate next, HttpContext context, AuthorizationPolicy policy, PolicyAuthorizationResult authorizeResult)
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
```
I don't know why it would be looking for member 'User' in type 'PatentAssessment' - it seems like a bug in the code that generates the Merge query. I think it has something to do with StringAggregate because if I comment out the StringAggregate part of the query, the Merge works fine.

**Comment by MaceWindu** [comment]
Was fixed in 3.5.2
