### ISSUE TITLE
Question about Linq deferred execution

### ISSUE THREAD

**Issue by giuliohome** [linq2db/linq2db#294]
Assume I write an initial select as IQueryable.
Then - before fetching the data from the db - I build a new linq IEnumerable by adding a where condition and then I get the ToList() from that.
I would expect that the actual SQL to fetch data from the db should contain the newly added where, taking advantage from the deferred execution's behavior.
 Is it correct? I'm afraid it isn't.
 Why don't I see that where condition from the last executed SQL?
Because unfortunately - I think that, even though linq is deferring the execution, the sql is generated always from the original IQueryable... but if I try to put a trival function in the original where clause,
the ExpressionBuilder.ConvertToSq fails to converted it to SQL

**Comment by giuliohome** [comment]
Of course the example in the readme under the paragraph "composing queries" does work and the final sql is composed in fact, but it is really too simple: not even a join in the initial query, 2 "where conditions" on the only, same db table...

**Comment by MaceWindu** [comment]
It sounds like an error I do from time to time:

```
var query = db.Table.Where(some_condition);
if (needsExtraCondition)
{
    query.Where();
    // Bah, forgot to assign new expression to query variable
    // must be:
    //
    // query = query.Where();
}
return query.ToList();
```

I hope you mean IQueryable in this statement "I build a new linq IEnumerable by adding a where condition ", because you cannot do it with IEnumerable

**Comment by giuliohome** [comment]
Lol :-) no, no I did not forget it. It is


var myNewIEnumerable = query.Where(something);
var myRetList = myNewIEnumerable.ToList();
var theSql = db.Last Query; //not optimized! :-(
// where clause missing
// obviously it is done "in memory"
 // better new query = from .. query where...
// but limited SQL builder possibilities
return myRetList;


Sorry for brevity, I'm writing from my mobile.

**Comment by MaceWindu** [comment]
It is not clear what type 'query' variable has. If it is IEnumerable instead of IQueryable then linq2db can do nothing about it - to change query you must work with IQuerable objects.

Just to check that we understant each other:
- IEnumerable uses linq methods, defined in Enumerable class. Those methods that IEnumerable and perform actions over in-memory collection
- IQuerable uses linq methods, defined in Queryable class. Those methods take IQueryable which is in short - link to provider and expression AST. Those methods ask provider to modify AST and return modified IQueryable instance or to execute it by converting AST to provider-specific functionality (SQL query against database in linq2db case, but there are other providers like LINQ to XML).

So, if you work with IEnumerable object, you call Where from Enumerable class that don't know anything about linq2db and even if your code 'query' is an IQueryable, downcasted to IEnumerable, Enumerable.Where will load query results to memory and apply filtering in-memory.
```
var query = db.Table;
IEnumerable enumerableQuery = query;
var results1 = query
    .Where()  // Queryable.Where updates AST
    .ToList(); // Queryable.ToList() executes SQL and puts them to list
var results1 = query
    .Where()  // Enumerable.Where loads data from database and filter results in memory
    .ToList(); // Enumerable.ToList() puts results to list
```

**Comment by giuliohome** [comment]
sorry, it is Queryable. I don't see what mean byt "updates AST".
Could you put a db.LastQuery after results1 and comment it? Please, confirm if you actually find the where clause in the executed sql.
(Should I blame the db provider if there is no where clause?)
Thank you very much!

**Comment by MaceWindu** [comment]
Hmm, then I need to see query. It looks like it contains something that prevents linq2db from pure server-side execution. E.g. call to function without Sql.Expression attribute.

**Comment by giuliohome** [comment]
Yep... maybe you're  right again ..
Here is my code:
```c#
internal static IEnumerable<ExtendedItem> LoadTois(string context, 
                                                  Func<ExtendedItem,bool> variableCond,
                                                  ILog log)
{
	try
	{
		using (var db = new MyContext(context))
		{
				var query = 
				from i in db.TabA						
					
				join sc in db.TabB
					on i.keyA_num equals sc.keyA_num						
				
				join c in db.TabC
					on sc.keyC_num equals c.keyC_num
				
				select ExtendedItem.Build(i,sc,c);
				
				
			return query.Where(FixedCond).Where(variableCond) .ToList();
		}
		
	}
	catch (Exception exc)
	{
		log.write(exc.Message);
		log.write(exc.StackTrace);
		return Enumerable.Empty<ExtendedItem>();
	}
}
```
I will double check.

**Comment by MaceWindu** [comment]
Func<ExtendedItem,bool> variableCond
it must be
Expression<Func<ExtendedItem,bool>> variableCond

**Comment by giuliohome** [comment]
you are a regular genius :-) 
Will try soon! 
Thanks in advance!!!

**Comment by giuliohome** [comment]
But, unfortunately, that change results in:
```c#
The method or operation is not implemented.
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T](Expression expression, Int32 level, Func`4 action, Func`1 defaultAction) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:line 912
   at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:line 644
   at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag) in i:\linq2db\Source\Linq\Builder\SelectContext.cs:line 607
   at LinqToDB.Linq.Builder.ExpressionContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag) in i:\linq2db\Source\Linq\Builder\ExpressionContext.cs:line 90
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass70.<CheckSubQueryForWhere>b__6f(Expression expr) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 88
   at LinqToDB.Expressions.Extensions.Visit(Expression expr, Func`2 func) in i:\linq2db\Source\Expressions\Extensions.cs:line 206
   at LinqToDB.Expressions.Extensions.Visit[T](IEnumerable`1 source, Func`2 func) in i:\linq2db\Source\Expressions\Extensions.cs:line 201
   at LinqToDB.Expressions.Extensions.Visit(Expression expr, Func`2 func) in i:\linq2db\Source\Expressions\Extensions.cs:line 262
   at LinqToDB.Linq.Builder.ExpressionBuilder.CheckSubQueryForWhere(IBuildContext context, Expression expression, Boolean& makeHaving) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 59
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 31
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in i:\linq2db\Source\Linq\Builder\WhereBuilder.cs:line 18
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in i:\linq2db\Source\Linq\Builder\MethodCallBuilder.cs:line 22
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 177
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in i:\linq2db\Source\Linq\Builder\WhereBuilder.cs:line 18
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in i:\linq2db\Source\Linq\Builder\MethodCallBuilder.cs:line 22
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 177
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in i:\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 148
   at LinqToDB.Linq.Query`1.GetQuery(IDataContextInfo dataContextInfo, Expression expr) in i:\linq2db\Source\Linq\Query.cs:line 165
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression expression, Boolean cache) in i:\linq2db\Source\Linq\ExpressionQuery.cs:line 89
   at LinqToDB.Linq.ExpressionQuery`1.Execute(IDataContextInfo dataContextInfo, Expression expression) in i:\linq2db\Source\Linq\ExpressionQuery.cs:line 76
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in i:\linq2db\Source\Linq\ExpressionQuery.cs:line 156
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by MaceWindu** [comment]
Looks like you hit limitation of current LINQ to SQL converter in linq2db. I recommend you to fill an issue with full linq expression or add it here and try tro rewrite your query.
Maybe my comments here will help you to identify problem: #266 #269 (I also had that exception there)

**Comment by giuliohome** [comment]
I suspect that the complexity stems from the fact that I want to apply
```c#
Expression<Func<TabA,bool>> variableTabCCond
```
but I am using a more indirect approach with
```c#
Expression<Func<ExtendedItem,bool>> variableCond
```
Well, I mean: in the query above, at the beginning, I could have written
```c#
                  var query = 
                from i in db.TabA                       

                join sc in db.TabB
                    on i.keyA_num equals sc.keyA_num                        

                join c in db.TabC
                    on sc.keyC_num equals c.keyC_num

                 where c.MyDate.Date == DateTime.Now.Date // for example

                select ExtendedItem.Build(i,sc,c);
```


Is there a way to appy that 

```c#
Expression<Func<TabA,bool>> variableTabCCond
```
to an
```c#
IQueryable<ExtendedItem> query
```
?

**Comment by MaceWindu** [comment]
Aha, right.
I'm 99% sure that your error is due to ExtendedItem.Build call placed before Where. linq2db cannot process predicates with complex sources for predicate parameter (and it's valid behavior usually). In your case predicate's parameter (TabA) cames from method call. linq2db knows nothing what this call do (or just have limited support) and it just throw exception here.

You are right, that you must put Where before Select if it will not affect query logic. It could be tricky.

You need to split your linq like that:
```
var query = 
                from i in db.TabA                       

                join sc in db.TabB
                    on i.keyA_num equals sc.keyA_num                        

                join c in db.TabC
                    on sc.keyC_num equals c.keyC_num;

                 query = query.Where(variableTabCCond).Select((i,sc,c) => ExtendedItem.Build(i,sc,c));
```
But code like that will not build, because compiler will not like LINQ statement without select. Also Where/Select methods' do not have such signatures.
Simplest solution for your case (inner join on TabC) is:
```
var tabCQuery = db.TabC.Where(variableTabCCond);
 var query = 
                from i in db.TabA                       

                join sc in db.TabB
                    on i.keyA_num equals sc.keyA_num                        

                join c in tabCQuery // here
                    on sc.keyC_num equals c.keyC_num

                select ExtendedItem.Build(i,sc,c);
```
More complex one will be to rewrite your query to be built using Queryable methods and Expression directly and plug your conditing where you need it. This is what compiler do internally when it see linq statements. But it's hell.

**Comment by giuliohome** [comment]
IT WORKS LIKE A CHARM :-) 

THANK YOU !!!

**Comment by MaceWindu** [comment]
Glad to hear :)
BTW, if you allways add this condition, you can put 
```
db.TabC.Where(variableTabCCond)
```
directly into linq statement, no need for extra var

**Comment by giuliohome** [comment]
Done!
It is working with 2 Where conds, one in db.TabC and the other in db.TabA
When I call the method 
```c#
var items = MyFramework.DB.LoadItems(
	"MyContext",  _ => true,
	MyFramework.DB.DateCond(new DateTime(2015,11,9),new DateTime(2015,11,9)),
	log)
```
one of the 2 parameters (for example TabC ) can be assigned _ => true when it is not relevant and the other a method like 
```c#
internal static Expression<Func<TabA,bool>> DateCond (DateTime fromDate, DateTime toDate) {
			return t => t.MyDate >= fromDate && t.MyDate <= toDate;
		}
```
Query SQL as expected.
