### ISSUE TITLE
PostgreSQL Test Error when get Hours on TimeSpan

### ISSUE THREAD

**Issue by sasukevita** [linq2db/linq2db#2950]
model
```c#
	[Table(Schema="Member", Name="Table")]
	public partial class Table
	{
		[PrimaryKey, NotNull    ] public int       Id   { get; set; } // integer
		[Column,        Nullable] public DateTime? Date { get; set; } // date
		[Column,        Nullable] public TimeSpan? Time { get; set; } // time without time zone
	}
```
test
```c#
var query = (from x in db.Table
                         select new
                         {
                             Output = x.Time.Value.Hours,
                         });
            query.ToArray();
```
Error: LinqToDB.Common.LinqToDBConvertException: 'Cannot convert value '12:34:56' to type 'System.Int32''
### Environment details
linq2db version: 3.3.0
Database: PostgreSQL 12.1
.NET Framework: 4.7.2

**Comment by jogibear9988** [comment]
We need a TmepSpan Part Builder like the DatePart Builder:

https://github.com/linq2db/linq2db/blob/054da1e089c396fa594a4975bf6e3d95c7b6e654/Source/LinqToDB/Sql/Sql.DateTime.cs#L401

and then the Expressions for all parts like here:

https://github.com/linq2db/linq2db/blob/8246efebdfbd3a7e5ab838b5425dce80a9147da0/Source/LinqToDB/Linq/Expressions.cs#L588

**Comment by coder2213** [comment]
@jogibear9988  @MaceWindu 
Interested to contribute to this issue.
I am trying to find a way to test this on my local.

I tried searching for creating a nuget locally and then attaching the nuget to the project and test it out.
So far my search didn't yield any results.
I searched through the documentation and couldn't find anything on this.
Can you please guide me on this?

**Comment by MaceWindu** [comment]
To build nuget locally, use `NuGet\PackLocal.cmd`, but I'm not sure why you need to use nuget for testing.

**Comment by coder2213** [comment]
Is there any easy way to test without building nuget?
How can I use the linq2db assembly in another project?

**Comment by sdanyliv** [comment]
Just add `linq2db.csproj` to solution and add project dependecy. Also we have `linq2db.playground.slnf` and you can add new test by copying TestTemplate.cs

**Comment by coder2213** [comment]
@sdanyliv @MaceWindu 

I have created a console app in .NET CORE and added this project as reference.

Main method where I am creating connection as per code given in gitpage.
 ```
static void Main(string[] args)
        {
            // create options builder
            var builder = new LinqToDbConnectionOptionsBuilder();

            // configure connection string
            builder.UsePostgreSQL("Server=PostgreSQL 12;Port=5432;Database=postgres;User Id=postgres;Password=abcd;Pooling=true;MinPoolSize=10;MaxPoolSize=100;");

            // pass configured options to data connection constructor
            using (var dc = new DataConnection(builder.Build()))
            {

            }            
        }
```

Error I am getting

```
System.InvalidOperationException
  HResult=0x80131509
  Message=Cannot load assembly Npgsql
  Source=linq2db
  StackTrace:
   at LinqToDB.DataProvider.PostgreSQL.NpgsqlProviderAdapter.GetInstance() in C:\CodeContribute\linq2db\Source\LinqToDB\DataProvider\PostgreSQL\NpgsqlProviderAdapter.cs:line 165
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider..ctor(String name, PostgreSQLVersion version) in C:\CodeContribute\linq2db\Source\LinqToDB\DataProvider\PostgreSQL\PostgreSQLDataProvider.cs:line 22
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.<>c.<.cctor>b__19_0() in C:\CodeContribute\linq2db\Source\LinqToDB\DataProvider\PostgreSQL\PostgreSQLTools.cs:line 18
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Lazy`1.CreateValue()
   at System.Lazy`1.get_Value()

  This exception was originally thrown at this call stack:
    LinqToDB.DataProvider.PostgreSQL.NpgsqlProviderAdapter.GetInstance() in NpgsqlProviderAdapter.cs
    LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider.PostgreSQLDataProvider(string, LinqToDB.DataProvider.PostgreSQL.PostgreSQLVersion) in PostgreSQLDataProvider.cs
    LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools..cctor.AnonymousMethod__19_0() in PostgreSQLTools.cs
    System.Lazy<T>.ViaFactory(System.Threading.LazyThreadSafetyMode)
    System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
    System.Lazy<T>.CreateValue()
    System.Lazy<T>.Value.get()
```

I debugged it and found that assembly is getting as null in NpgsqlProviderAdapter.cs file

```
public static NpgsqlProviderAdapter GetInstance()
		{
			if (_instance == null)
				lock (_syncRoot)
					if (_instance == null)
					{
						var assembly = Tools.TryLoadAssembly(AssemblyName, null);
						if (assembly == null)
							throw new InvalidOperationException($"Cannot load assembly {AssemblyName}");
```

Appreciate any help in fixing this.

**Comment by MaceWindu** [comment]
Looks like you didn't added rerefence to Npgsql nuget

**Comment by coder2213** [comment]
@MaceWindu 
I am able to run the code after adding Npgsql nuget.

I am somewhat confused the solution proposed by @jogibear9988 
I understood that we need to add similar code for TimeParts as well.
But I am not sure if I should add another class or can I do it in sql.DateTime class or any other existing class?

Also, any reference to the internal working of the code would be helpful.
I checked Contributing.md page and couldn't find any.
I am having hard time debugging through full code and trying to make sense.
Thanks.
