### ISSUE TITLE
PostrgreSql error when InsertWithOutputAsync

### ISSUE THREAD

**Issue by riberk** [linq2db/linq2db#2958]
Returning clause is empty in result sql query

```
Exception message: 42601: syntax error at end of input
Stack trace:
at Npgsql.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|194_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken token)
```

### Steps to reproduce
It's need postgres on `localhost:5432` with created database `l2db_tests`.

Test framework: xunit

```c#
public class Test
{
    private readonly ITestOutputHelper _console;

    public Test(ITestOutputHelper console)
    {
        _console = console;
    }

    [Fact]
    public async Task InsertWithOutputError()
    {
        DataConnection.TurnTraceSwitchOn();
        DataConnection.WriteTraceLine = (message, displayName, lvl) =>
        {
            _console.WriteLine($"{lvl}|{displayName}|{message}");
        };

        var connectionString = "Host=localhost;Port=5432;Username=postgres;Password=postgres;Database=l2db_tests;Include Error Detail=true";
        var connectionOptions = new LinqToDbConnectionOptionsBuilder()
            .UsePostgreSQL(connectionString)
            .Build<Con>();
        await using var con = new Con(connectionOptions);
        await using var tmpTable = con.CreateTempTable<Entity>("entities");
        await con.InsertAsync(new Entity()
        {
            Id = "id",
            Name = "name"
        }, "entities");

        var inserted = await tmpTable.InsertWithOutputAsync(tmpTable, e => new Entity
        {
            Id = e.Name,
            Name = e.Id
        }, e => e.Id);

        Assert.Equal("name", Assert.Single(inserted));
        Assert.Collection(tmpTable.OrderBy(x => x.Id).ToArray(),
            e => Assert.Equal("id", e.Id),
            e => Assert.Equal("name", e.Id));
    }

    public class Con : DataConnection
    {
        public Con(LinqToDbConnectionOptions<Con> options) : base(options)
        {
        }

        public ITable<Entity> Entities => GetTable<Entity>();
    }

    public class Entity
    {
        [PrimaryKey, Column("id")]
        public string Id { get; set; }

        [Column("name")]
        public string Name { get; set; }
    }
}
```

In logs you can see sql query with empty `returning` clause

```
...
Info|DataConnection|BeforeExecute
--  PostgreSQL.9.5 PostgreSQL (asynchronously)

INSERT INTO entities
(
	id,
	name
)
SELECT
	t1.name,
	t1.id
FROM
	entities t1
RETURNING

Error|DataConnection|Error
Exception: Npgsql.PostgresException
...
```

### Environment details
linq2db version: 3.3.0
Database Server: PostgreSQL 11.7 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
Operating system: ubuntu 20.04
.NET Framework: NET 5.0.5

**Comment by TheAsda** [comment]
Yeap, having the same issue. Looks like wrong `RETURNING` statement is generated
```
INSERT INTO "public"."group"
 	(
 		name,
 		"path"
 	)
 	VALUES
 	(
 		$1,
 		$2
 	)
 	RETURNING
```

Even specifying output expression does not add returning fields

**Comment by MaceWindu** [comment]
#3328 PR fix fix
