### ISSUE TITLE
Optimizer can't find IsDistinctFrom

### ISSUE THREAD

**Issue by jods4** [linq2db/linq2db#3000]
I'm trying to use the new (unreleased) `IsDistinctFrom` in my project, using this nightly build:
https://dev.azure.com/linq2db/linq2db/_packaging?_a=package&feed=linq2db&view=overview&package=linq2db&version=3.3.1-rc.5876&protocolType=NuGet

In a very large and complex query, it raises the following error:
```
Exception message:
Method not found: 'Boolean LinqToDB.Sql.IsDistinctFrom(!!0, !!0)'.

Stack trace:
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at LinqToDB.Expressions.InternalExtensions.EvaluateExpression(Expression expr) in /_/Source/LinqToDB/Expressions/InternalExtensions.cs:line 1381
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.ConvertMethodExpression(Type type, MemberInfo mi, String& alias) in /_/Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs:line 683
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertMethodExpression(Type type, MemberInfo mi, String& alias) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs:line 520
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpressionImpl(Expression expr, HashSet`1 currentParameters) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs:line 485
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass46_0.<OptimizeExpression>b__0(Expression e) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs:line 385
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1372
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1422
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1467
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1422
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1622
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpression(Expression expression) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs:line 385
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpressionImpl(Expression expr, HashSet`1 currentParameters) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs:line 492
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass46_0.<OptimizeExpression>b__0(Expression e) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs:line 385
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1372
   at LinqToDB.Expressions.Extensions.<>c__DisplayClass36_0.<Transform>g__Modify|1(MemberBinding b) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1522
   at LinqToDB.Expressions.Extensions.Transform2[T](ICollection`1 source, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1338
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1568
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1486
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1451
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1354
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1458
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1354
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1458
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1354
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1458
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1354
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1458
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1354
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in /_/Source/LinqToDB/Expressions/Extensions.cs:line 1458
   at LinqToDB.Linq.Builder.ExpressionBuilder.OptimizeExpression(Expression expression) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs:line 385
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressionTree(Expression expression) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs:line 310
   at LinqToDB.Linq.Builder.ExpressionBuilder..ctor(Query query, IDataContext dataContext, Expression expression, ParameterExpression[] compiledParameters) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs:line 134
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in /_/Source/LinqToDB/Linq/Query.cs:line 540
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in /_/Source/LinqToDB/Linq/Query.cs:line 502
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in /_/Source/LinqToDB/Linq/ExpressionQuery.cs:line 75
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in /_/Source/LinqToDB/Linq/ExpressionQuery.cs:line 270
   at LinqToDB.MultiInsertExtensions.InsertFirst[TSource](IMultiInsertElse`1 insert) in /_/Source/LinqToDB/LinqExtensions.MultiInsert.cs:line 240
```

This is surprising to me for 2 reasons:
1. The expressions that call `IsDistinctFrom` are based on two DB fields, there's no way they can be evaluated in C# so I'm surprised LinqToDb seems to try?
2. Why would the `IsDistinctFrom` method not be found... we have tests for all .net types.

I'm assuming there's a bug in the optimizer, do you have any idea what it might be? 
Anything I could do to help identify it?
This is a _very large_ query that's composed dynamically from several parts, creating a small repro won't be easy.

**Comment by sdanyliv** [comment]
@jods4, I need sample. O piece of your code.

**Comment by jods4** [comment]
@sdanyliv I can't reproduce this bug anymore, so I'm gonna close this because it's not actionnable. 
The error is super-weird and there must be a bug somewhere but I have no idea how to demonstrate it anymore.

This is part of a mega-query that was based on generics, interfaces, inheritance, insert all, expressions methods and its complexity is through the roof, the resulting SQL spans multiple pages.
We have refactored that beast many times while working on it and currently it runs without error so I'm unable to say what triggered this.

Good thing it works now, I suppose 🤷‍♂️
