### ISSUE TITLE
[PostgreSQL] Define `ulong->decimal` mapping for parameters

### ISSUE THREAD

**Issue by Kaoticz** [linq2db/linq2db#3013]
LinqToDB queries are not working when they need to instantiate entities with unsigned properties. Consider the following entity:
```cs
public class UserEntity
{
    [Key]
    public int Id { get; set; }
    public ulong UserId { get; set; } // <---- unique property
    public string Username { get; set; }
    public string Discriminator { get; set; }
}
```
Running a query like this:
```cs
var dbEntry = db.Users
    .Where(x => x.UserId == userId)
    .DeleteWithOutput()
    .FirstOrDefault();
```
Or a query like this
```cs
var table = db.GetTable<UserEntity>();
table.InsertOrUpdate(
    () => new UserEntity()
    { 
        Id = 1,
        UserId = contextId,
        Username = username,
        Discriminator = discriminator
    },
    y => new UserEntity()
    {
        Username = username,
        Discriminator = discriminator
    }
);
```
Causes an exception to be thrown:
```
System.InvalidCastException: Can't write CLR type System.UInt64 with handler type NumericHandler
   at lambda_method107(Closure , NpgsqlTypeHandler , Object , NpgsqlLengthCache& , NpgsqlParameter )
   at Npgsql.TypeHandling.NpgsqlSimpleTypeHandler`1.ValidateObjectAndGetLength(Object value, NpgsqlLengthCache& lengthCache, NpgsqlParameter parameter)
   at Npgsql.NpgsqlParameter.ValidateAndGetLength()
   at Npgsql.NpgsqlCommand.ValidateParameters(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken token)
   at [Business Logic]
```

In my experiments, this only happens when the property is assigned to another variable. Assigning it to a constant literal (ie. `UserId = 1234UL`) or omitting it causes the methods to work flawlessly. `BulkCopy()` and `BulkCopyAsync()` also seem to work fine regardless of what I do.

Some advice would be appreciated.

Relevant Nuget Packages:
LinqToDb.EntityFrameworkCore: v5.2.1
Npgsql: v5.0.5
Npgsql.EntityFrameworkCore.PostgreSQL: v5.0.6

**Comment by Kaoticz** [comment]
Hey, that worked. Thanks!
