### ISSUE TITLE
Duplicate ExtensionAttributes for DateAdd on SQL Server

### ISSUE THREAD

**Issue by roflmuffin** [linq2db/linq2db#3045]
I am currently experiencing an exception (see below) with regard to the "DateAdd" function on SQL Server 2019. It seems that the source of this error is that the Expression resolves down to DateAdd but there are two instances of the ExtensionAttribute for SQL found for DateAdd.

The two that I can see that are being loaded are https://github.com/linq2db/linq2db/blob/5dec345f6d597310c808d369f68fb88322c80f92/Source/LinqToDB/Sql/Sql.DateTime.cs#L736

and 

https://github.com/linq2db/linq2db/blob/cb072819428998b2db81763af47f262227699a33/Source/LinqToDB/Linq/Expressions.cs#L1713

When I set a breakpoint into the `MappingSchema.GetAttributes<T>` it appears to be returning two duplicate attributes for the DateAdd method.

```
Exception message: Multiple root sequences found for expression 'DateAdd(Day, Convert(-1), Convert(ros.EndDate))'
Stack trace: System.InvalidOperationException: Multiple root sequences found for expression 'DateAdd(Day, Convert(-1), Convert(ros.EndDate))'
   at LinqToDB.Sql.ExtensionAttribute.GetExpression(IDataContext dataContext, SelectQuery query, Expression expression, Func`3 converter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExtensionToSql(IBuildContext context, ExpressionAttribute attr, MethodCallExpression mc)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToExtensionSql(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass147_0.<ConvertExtensionToSql>b__0(Expression e, ColumnDescriptor descriptor)
   at LinqToDB.Sql.ExpressionAttribute.<>c__DisplayClass67_0.<PrepareArguments>b__0(String v, String d)
   at LinqToDB.Sql.ExpressionAttribute.<>c__DisplayClass64_0.<ResolveExpressionValues>b__0(Match match)
   at System.Text.RegularExpressions.RegexReplacement.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at LinqToDB.Sql.ExpressionAttribute.ResolveExpressionValues(String expression, Func`3 valueProvider)
   at LinqToDB.Sql.ExpressionAttribute.PrepareArguments(String expressionStr, Int32[] argIndices, Boolean addDefault, List`1 knownExpressions, List`1 genericTypes, Func`3 converter)
   at LinqToDB.Sql.ExpressionAttribute.GetExpression(IDataContext dataContext, SelectQuery query, Expression expression, Func`3 converter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExtensionToSql(IBuildContext context, ExpressionAttribute attr, MethodCallExpression mc)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToExtensionSql(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass147_0.<ConvertExtensionToSql>b__0(Expression e, ColumnDescriptor descriptor)
   at LinqToDB.Sql.ExpressionAttribute.PrepareArguments(String expressionStr, Int32[] argIndices, Boolean addDefault, List`1 knownExpressions, List`1 genericTypes, Func`3 converter)
   at LinqToDB.Sql.FunctionAttribute.GetExpression(IDataContext dataContext, SelectQuery query, Expression expression, Func`3 converter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExtensionToSql(IBuildContext context, ExpressionAttribute attr, MethodCallExpression mc)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.CountBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
```

### Steps to reproduce

This is included in a complex project that is being migrated from Linq-To-SQL so it would be a bit hard to provide code samples for the issue. The example linq that generates the issue:

```c#
from ros in db.RoomOutOfServices
                     where ros.EndDate.AddDays(-1).Date >= startDate
```

### Environment details
linq2db version: 3.4.0.0
Database Server: SQL Server 2019
Database Provider: SQL Server
Operating system: Windows
.NET Framework: 4.7.2

**Comment by sdanyliv** [comment]
I cannot reproduce. Do you have some custom extensions?

**Comment by roflmuffin** [comment]
Hey Svyatoslav, thanks for the update. Based on your comment I did some further digging on my end and it appears that it was indeed user error. I was accidentally adding an extra AttributeReader to the mapping schema which was duplicating the SQL extension attributes.
