### ISSUE TITLE
Unable to cast object of type 'LinqToDB.Data.DataConnection' to type 'DataProvider'

### ISSUE THREAD

**Issue by croban** [linq2db/linq2db#3049]
I have updated from application from 3.2.3 to 3.4

For this Delete statement
```c#
AsQueryable().Delete(f => f.Id == entity.Id && DB.User.Categories.ContainsKey(f.CategoryId));
```

I get this exception 

```
Exception message: Unable to cast object of type 'LinqToDB.Data.DataConnection' to type 'Nesto.DataProvider'.
Stack trace:
System.InvalidCastException : Unable to cast object of type 'LinqToDB.Data.DataConnection' to type 'Nesto.DataProvider'.
   at lambda_method495(Closure , Expression , IDataContext , Object[] )
   at LinqToDB.Linq.QueryRunner.SetParameters(Query query, Expression expression, IDataContext parametersContext, Object[] parameters, Int32 queryNumber, SqlParameterValues parameterValues)
   at LinqToDB.Linq.QueryRunnerBase.SetCommand(Boolean clearQueryHints)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()
   at LinqToDB.DataContext.QueryRunner.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass31_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at LinqToDB.LinqExtensions.Delete[T](IQueryable`1 source, Expression`1 predicate)
   at Nesto.ApplicationRepository.__a$_around_Delete_100664428_o(OpenIddictApplication entity) in C:\Git\Nesto\Repository\ApplicationRepository.cs:line 223
```

### Environment details
linq2db version: 3.4
Database Server: Microsoft Sql Server
Database Provider: MSSQL
Operating system: Windows
.NET Framework: .net core 5

**Comment by sdanyliv** [comment]
@croban, I need more details. Just stack trace will not help.

**Comment by sdanyliv** [comment]
Probably you have used QueryFilter or something else dynamic. And we failed to build parameter expression.

**Comment by croban** [comment]
Hi @sdanyliv 

I have something like this: 

```c#

internal partial class AdminContext : DataContext
{
        public AdminContext(string connectionString) : base(new SqlServerDataProvider("SqlServer", SqlServerVersion.v2017), connectionString)
        {

        }

	public ITable<OpenIddictApplication>   OpenIddictApplications   { get { return this.GetTable<OpenIddictApplication>(); } }
		
        private Dictionary<string, object> _nesto;
        public Dictionary<string, object> Nesto
        {
            get
            {
                if (_nesto == null)
                    _nesto = new Dictionary<string, object>() {{"key", "value"}};
                return _nesto;
            }
        }
}
```

This will throw exception from above

```c#
var db = new AdminContext("...");
db.OpenIddictApplications.Delete(f => f.Id == id && db.Nesto.ContainsKey(f.CategoryId));
```

It seems that properties inside DataContext cause this exception.
If I change the statement to this, everything works.

```c#
var db = new AdminContext("...");
var keys = db.Nesto.Keys.ToList();
db.OpenIddictApplications.Delete(f => f.Id == id && keys.Contains(f.CategoryId));
```
