### ISSUE TITLE
Getting Error while mapping custom type object with byte array

### ISSUE THREAD

**Issue by VarunSaiTeja** [linq2db/linq2db#3067]
I am facing an issue while doing type conversion between a custom POCO and byte[].
I am using SQLite Db. And it had a table Patches with columns ('Serial' text, 'Snapshot' integer, 'Data' blob).

My POCO Classes
```
    [Table("Patches")]
    public class PatchInfo
    {
        [Column]
        public long Snapshot { get; set; }

        [Column]
        public string Serial { get; set; }

        [Column]
        public PatchData Data { get; set; }
    }

    public class PatchData
    {
       //Various Properties will be there
    }
```

Code for custom mapping
```
    static void ConfigureMapping()
    {
        MappingSchema.Default
           .SetConverter<byte[], PatchData>(v => Utils.Deserialize<PatchData>(v));

        MappingSchema.Default
           .SetConverter<PatchData, byte[]>(v => Utils.Serialize(v));
    }
```

Code of Utils
```
    using System.IO;
    using ProtoBuf;
    public static class Utils
    {
        public static byte[] Serialize<T>(T record) where T : class
        {
            using var stream = new MemoryStream();
            Serializer.Serialize(stream, record);
            return stream.ToArray();
        }

        public static T Deserialize<T>(byte[] data) where T : class
        {
            using var stream = new MemoryStream(data);
            return Serializer.Deserialize<T>(stream);
        }
    }
```

```
Exception message: An unhandled exception of type 'System.InvalidOperationException' occurred in System.Private.CoreLib.dll: 'No mapping exists from object type FileHub.Core.Entities.PatchData to a known managed provider native type.

Stack trace:
at Microsoft.Data.Sqlite.SqliteValueBinder.Bind()
   at Microsoft.Data.Sqlite.SqliteParameter.Bind(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteParameterCollection.Bind(sqlite3_stmt stmt)
   at Microsoft.Data.Sqlite.SqliteCommand.<GetStatements>d__54.MoveNext()
   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteReader()
   at Microsoft.Data.Sqlite.SqliteCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
```

Steps to reproduce
```
  void Main()
  {
      PatchInfo patchInfo = new PatchInfo
      {
          Snapshot = DateTimeOffset.UtcNow.AsUnix(),
          Serial = Serial,
          Data = new PatchData
      };
      
      await DbContext.InsertAsync(patchInfo);
  }
```

### Environment details
linq2db version: 3.4.0
Database Server: Sqlite
Database Provider: Microsoft.Data.Sqlite
Operating system: Windows 10
.NET version: 5

**Comment by sdanyliv** [comment]
You have to add conversion to `DataParameter`
```cs
static void ConfigureMapping()
{
    MappingSchema.Default
        .SetConverter<byte[], PatchData>(v => Utils.Deserialize<PatchData>(v));

    MappingSchema.Default
        .SetConverter<PatchData, DataParameter>(v => new DataParameter(null, Utils.Serialize(v)));
}
```
