### ISSUE TITLE
Does linq2db support C# 9 records?

### ISSUE THREAD

**Issue by Ilchert** [linq2db/linq2db#3082]
Hello, does linq2db support C# 9 records?

I am trying to map simple record but get exception `Type 'RecordType' does not have a default constructor`.
Are there any workarounds for records?

Thanks, Ilya.

Example code 

```C#
record Rec(int Id);

[Fact]
public async Task RecordsTest()
{
    var cs = _options.Value.ConnectionString;
    var ms = new MappingSchema();
    ms.GetFluentMappingBuilder().Entity<Rec>()
        .HasTableName("Table")
        .HasSchemaName("dbo")
        .Property(p => p.Id).IsPrimaryKey().HasColumnName("Id").IsIdentity();

    await using var dc = new DataConnection(SqlServerProviderAdapter.MicrosoftProviderFactoryName, cs, ms);
    var data = await dc.GetTable<Rec>().ToArrayAsync();
}
```

Exception stack trace 

```
System.ArgumentException
Type 'Rec' does not have a default constructor (Parameter 'type')
   at System.Linq.Expressions.Expression.New(Type type)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildDefaultConstructor(EntityDescriptor entityDescriptor, Type objectType, Tuple`2[] index)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildTableExpression(Boolean buildBlock, Type objectType, Tuple`2[] index)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery(Type tableType, TableContext tableContext, ParameterExpression parentObject)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken token)
```

**Comment by sdanyliv** [comment]
Provide us with small reproducible sample. And we will check what to do.

**Comment by MaceWindu** [comment]
@sdanyliv,  probably time to generalize code we use for fsharp records...

**Comment by MaceWindu** [comment]
Checked quickly and compared to F#, C# records doesn't have metadata we can use to recognize them. Basically we need to support non-default constructor here

**Comment by Ilchert** [comment]
> Provide us with small reproducible sample. And we will check what to do.
@sdanyliv I updated the question.
