### ISSUE TITLE
Collection was modified on ApplyQueryHints (PostgreSQL)

### ISSUE THREAD

**Issue by ademchenko** [linq2db/linq2db#3137]
There's already an issue #2784 which is, I assume, very similar to the one I'm facing but #2784 is closed by the author without any solution.
I have prepared a test without any ASP.NET core DI facilities so it's 100% clear that the data connections are used per thread, but anyway, the exception is thrown.

```
 public class Linq2DbTests
    {
        [SetUp]
        public void SetupDatabaseConnection()
        {
            var configuration =
                new ConfigurationBuilder()
                    .SetBasePath(TestContext.CurrentContext.TestDirectory)
                    .AddJsonFile("appsettings.json")
                    .Build();

            const string connectionName = "ServerDbConnection";
            var connectionString = configuration.GetConnectionString(connectionName);
            DataConnection.DefaultSettings = new LinqToDbSettings(connectionName, ProviderName.PostgreSQL, connectionString);
        }

        [Repeat(100)]
        [Test]
        public async Task ParallelQueries()
        {
            const int degreeOfParallelism = 10;

            var parallelBetTasks = new Task[degreeOfParallelism];

            for (int i = 0; i < degreeOfParallelism; ++i)
            {
                parallelBetTasks[i] = DoDbCommand();
            }

            await Task.WhenAll(parallelBetTasks);
        }

        private async Task DoDbCommand()
        {
            //EntitiesDataConnection is autogenerated class derived from LinqToDB.Data.DataConnection
            // <auto-generated>
            //    This code was generated by T4Model template for T4 (https://github.com/linq2db/linq2db).
            //    With additional support for multiple files.
            //    Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
            // </auto-generated>
            var entitiesDataConnection = new EntitiesDataConnection();
            entitiesDataConnection.NextQueryHints.Add("FOR NO KEY UPDATE");
            TestContext.WriteLine(entitiesDataConnection.NextQueryHints.Count.ToString(CultureInfo.InvariantCulture));

            var user = await entitiesDataConnection.Users.Where(u => u.Id == 11).SingleOrDefaultAsync();
        }
    }
```

"User" is just a class mapped from the corresponding table with T4 template.
The linq2db version I'm facing the issue is **3.4.2**. I have a number of multithreading tests in my project similar to the above one and I think I didn't face such an issue with 2.xx.yy linq2db versions. 

Exception:
```

System.InvalidOperationException : Collection was modified; enumeration operation may not execute.
   at System.Collections.Generic.List`1.Enumerator.MoveNextRare()
   at LinqToDB.SqlProvider.BasicSqlBuilder.ApplyQueryHints(String sqlText, List`1 queryHints)
   at LinqToDB.Data.DataConnection.InitCommand(CommandType commandType, String sql, DataParameter[] parameters, List`1 queryHints, Boolean withParameters)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass6_0`1.<<GetSingleOrDefaultElement>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at My.Tests.Linq2DbTests.DoDbCommand()
```

**Comment by MaceWindu** [comment]
Looking at code can confirm it looks suspicious. Looks like reusable `PreparedQuery.QueryHints` list is cleared by `InitCommand`

**Comment by ademchenko** [comment]
@MaceWindu, this is really a blocker bug, because it disables concurrent use of a library.

**Comment by MaceWindu** [comment]
Next release will be around 12 aug. If you need it earlier - I can fix it and make available through preview build on azure artifacts

**Comment by ademchenko** [comment]
> Next release will be around 12 aug. If you need it earlier - I can fix it and make available through preview build on azure artifacts

I think it's OK to wait till 12 Aug, thanks a lot in advance!
