### ISSUE TITLE
Multiple Levels of Abstract Inheritance Results in Failed Reads

### ISSUE THREAD

**Issue by theodinspire** [linq2db/linq2db#3184]
While refactoring our project to use polymorphism, we have found that Linq2DB's inheritance mapping falls apart when the tree of abstract classes becomes three deep. The mapping works fine if there is a base abstract class and a single layer of derived types.

### tl;dr:
When mapping to a class tree with two or more levels of abstract classes:
* Reads and Inserts made from concrete classes behave as expected
* Reads using base types fail
* Inserts of collections of base types fail
* [A project illustrating the errors](https://github.com/theodinspire/DoubleInheritance)

#### Reads
Reads from the table do map correctly when using any terminal concrete instances as in either `connection.GetTable<Bicycle>()` or `connection.GetTable<Lorry>()` from the example provided below. But with any of the abstract parent types, exceptions will be thrown on an attempt to read the objects from the database.

When reading from the table using the base abstract type, *e.g.* `connection.GetTable<Vehicle>`, the following exception is thrown:
```
System.InvalidOperationException : Instances of abstract classes cannot be created.
   at System.Runtime.CompilerServices.RuntimeHelpers._CompileMethod(IRuntimeMethodInfo method)
   at System.Reflection.Emit.DynamicMethod.CreateDelegate(Type delegateType, Object target)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda, DebugInfoGenerator debugInfoGenerator)
   at System.Linq.Expressions.Expression`1.Compile()
   at LinqToDB.Common.Compilation.CompileExpression[TDelegate](Expression`1 expression)
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IDataContext context, IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__11`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Tests.VehicleTests.CanReadBicycleFromListOfVehicles() in C:\Users\Cormack\code\theodinspire\DoubleInheritance\Tests\VehicleTests.cs:line 117
```

When reading from the table using the derived abstract type, *e.g.* `connection.GetTable<Automobile>`, the following is thrown:
```
System.ArgumentException : 'CargoCapacity' is not a member of type 'DoubleInheritance.Locomotion.Automobile'
   at System.Linq.Expressions.Expression.ValidateMemberInitArgs(Type type, ReadOnlyCollection`1 bindings)
   at System.Linq.Expressions.Expression.MemberInit(NewExpression newExpression, IEnumerable`1 bindings)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildDefaultConstructor(EntityDescriptor entityDescriptor, Type objectType, Tuple`2[] index)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildTableExpression(Boolean buildBlock, Type objectType, Tuple`2[] index)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery(Type tableType, TableContext tableContext, ParameterExpression parentObject)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Tests.VehicleTests.CanReadCarFromAutomobiles() in C:\Users\Cormack\code\theodinspire\DoubleInheritance\Tests\VehicleTests.cs:line 91
```

#### Inserts
Insertions into the database behave similarly. Inserting single objects is successful, even if cast as a base type, as is inserting collections of concrete objects (*e.g.* `List<Bicycle>`).

However when inserting collections typed for the abstract classes, whether or not the objects in the collection share the same type, the insert fails. The following is the exception thrown when inserting a list containing a bicycle and a lorry:
```
System.InvalidCastException : Unable to cast object of type 'DoubleInheritance.Locomotion.Bicycle' to type 'DoubleInheritance.Locomotion.Automobile'.
   at lambda_method(Closure , Object )
   at LinqToDB.DataProvider.BulkCopyReader.GetValue(Int32 ordinal)
   at System.Data.SqlClient.SqlBulkCopy.GetValueFromSourceRow(Int32 destRowIndex, Boolean& isSqlType, Boolean& isDataFeed, Boolean& isNull)
   at System.Data.SqlClient.SqlBulkCopy.ReadWriteColumnValueAsync(Int32 col)
   at System.Data.SqlClient.SqlBulkCopy.CopyColumnsAsync(Int32 col, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyRowsAsync(Int32 rowsSoFar, Int32 totalRows, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsyncContinued(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.CopyBatchesAsync(BulkCopySimpleResultSet internalResults, String updateBulkCommandText, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestContinuedAsync(BulkCopySimpleResultSet internalResults, CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalRestAsync(CancellationToken cts, TaskCompletionSource`1 source)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServerInternalAsync(CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteRowSourceToServerAsync(Int32 columnCount, CancellationToken ctoken)
   at System.Data.SqlClient.SqlBulkCopy.WriteToServer(IDataReader reader)
   at LinqToDB.DataProvider.SqlServer.SqlServerBulkCopy.<>c__DisplayClass10_1`1.<ProviderSpecificCopyInternal>b__3()
   at LinqToDB.DataProvider.BasicBulkCopy.TraceAction(DataConnection dataConnection, Func`1 commandText, Func`1 action)
   at LinqToDB.DataProvider.SqlServer.SqlServerBulkCopy.ProviderSpecificCopyInternal[T](ProviderConnections providerConnections, ITable`1 table, BulkCopyOptions options, Func`2 createDataReader)
   at LinqToDB.DataProvider.SqlServer.SqlServerBulkCopy.ProviderSpecificCopy[T](ITable`1 table, BulkCopyOptions options, IEnumerable`1 source)
   at LinqToDB.DataProvider.BasicBulkCopy.BulkCopy[T](BulkCopyType bulkCopyType, ITable`1 table, BulkCopyOptions options, IEnumerable`1 source)
   at Tests.VehicleTests.CanInsertMixedVehicleCollection() in C:\Users\Cormack\code\theodinspire\DoubleInheritance\Tests\VehicleTests.cs:line 203
```

### Steps to reproduce
I have [built a project](https://github.com/theodinspire/DoubleInheritance) with tests illustrating the points I have made above. Below are the type declarations compiled for easy reference

```c#
[Table("Vehicle", Schema = "DoubleInheritance")]
[InheritanceMapping(Code = VehicleType.Bicycle, Type = typeof(Bicycle))]
[InheritanceMapping(Code = VehicleType.Automobile, Type = typeof(Automobile))]
public abstract class Vehicle
{
	[Identity]
	public int Id { get; set; }

	[Column(IsDiscriminator = true)]
	public virtual VehicleType Type { get; set; }
}

public class Bicycle : Vehicle
{
	[Column]
	public override VehicleType Type => VehicleType.Bicycle;

	[Column]
	public BicycleType BicycleType { get; set; }
}

[InheritanceMapping(Code = AutomobileType.Lorry, Type = typeof(Lorry))]
[InheritanceMapping(Code = AutomobileType.Car, Type = typeof(Car))]
public abstract class Automobile : Vehicle
{
	[Column]
	public override VehicleType Type => VehicleType.Automobile;

	[Column(IsDiscriminator = true)]
	public virtual AutomobileType AutomobileType { get; set; }
}

public class Lorry : Automobile
{
	[Column]
	public override AutomobileType AutomobileType => AutomobileType.Lorry;

	[Column]
	public double CargoCapacity { get; set; }
}

public class Car : Automobile
{
	[Column]
	public override AutomobileType AutomobileType => AutomobileType.Car;

	[Column]
	public int MaxOccupancy { get; set; }
}

public enum VehicleType
{
	Bicycle,
	Automobile,
}

public enum AutomobileType
{
	Lorry,
	Car,
}

public enum BicycleType
{
	Standard,
	Recumbent,
	Cargo,
	Tandem,
}
```

Here are some of the failing queries:
```c#
// Read
var vehicles = this.connection.GetTable<Vehicle>().ToList();
var automobiles = this.connection.GetTable<Automobile>().ToList();

// Bulk Insert
var list = new List<Vehicle> { bicycle, lorry };
var count = this.connection.BulkCopy(list).RowsCopied;
```

### Environment details
* linq2db version: 3.4.2
* Database Server: Microsoft SQL Server 2016 (SP1) (KB3182545) - 13.0.4001.0 (X64), Express Edition
* Database Provider: SqlServerVersion.v2016
* Operating system: Windows 10
* .NET Framework: v4.6.2

**Comment by theodinspire** [comment]
Thank you for updating the functionality to be able to insert mixed collections of objects.

However, the primary reason that I had opened this issue is that reading mixed collections is failing.

**Comment by sdanyliv** [comment]
My fault. Will fix that for the next release (
