### ISSUE TITLE
Update : System.InvalidCastException : Unable to cast object of type 'Column' to type 'LinqToDB.SqlQuery.SqlField'

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#319]
System.InvalidCastException : Unable to cast object of type 'Column' to type 'LinqToDB.SqlQuery.SqlField'.

```
at LinqToDB.Linq.Builder.UpdateBuilder.BuildSetter(ExpressionBuilder builder, IBuildContext into, List`1 items, IBuildContext ctx, MemberInitExpression expression, Expression path) in c:\GitHub\linq2db\Source\Linq\Builder\UpdateBuilder.cs:line 221
at LinqToDB.Linq.Builder.UpdateBuilder.BuildSetter(ExpressionBuilder builder, BuildInfo buildInfo, LambdaExpression setter, IBuildContext into, List`1 items, IBuildContext sequence) in c:\GitHub\linq2db\Source\Linq\Builder\UpdateBuilder.cs:line 158
at LinqToDB.Linq.Builder.UpdateBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in c:\GitHub\linq2db\Source\Linq\Builder\UpdateBuilder.cs:line 36
at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in c:\GitHub\linq2db\Source\Linq\Builder\MethodCallBuilder.cs:line 22
at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in c:\GitHub\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 177
at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in c:\GitHub\linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 148
at LinqToDB.Linq.Query`1.GetQuery(IDataContextInfo dataContextInfo, Expression expr) in c:\GitHub\linq2db\Source\Linq\Query.cs:line 165
at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression expression, Boolean cache) in c:\GitHub\linq2db\Source\Linq\ExpressionQuery.cs:line 84
at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in c:\GitHub\linq2db\Source\Linq\ExpressionQuery.cs:line 142
at LinqToDB.LinqExtensions.Update[T](IQueryable`1 source, Expression`1 setter) in c:\GitHub\linq2db\Source\LinqExtensions.cs:line 225
```

I will create pull request with test and fix a bit later.

**Comment by MaceWindu** [comment]
Closing as fix was merged long time ago
