### ISSUE TITLE
Syntax error in query with OVER and CONTAINS

### ISSUE THREAD

**Issue by coudy** [linq2db/linq2db#3198]
```
System.Data.SqlClient.SqlException (0x80131904): Incorrect syntax near '*'.
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite, String method)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

### Steps to reproduce

Set up tables in SQL Server:
```
CREATE TABLE Foo (a int);
CREATE TABLE Bar (b int);
```

Run template.

```c#
var q =
    from foo in Database.Foos
    from bar in Database.Bars.Where(bar => bar.B == foo.A)
    where Sql.Ext.SqlServer().Contains("'bar'", bar)
    select Sql.Ext.Max(bar.B).Over().PartitionBy(bar != null ? 1 : 0).ToValue();
var res = q.ToArray();
```

Last line throws above exception. `q.ToString()` clearly shows the syntax error in the `PARTITION BY` clause:

```
--  SqlServer.2017
SELECT
	MAX([bar_1].[b]) OVER(PARTITION BY IIF([bar_1].* IS NOT NULL, 1, 0))
FROM
	[dbo].[Foo] [foo_1]
		INNER JOIN [dbo].[Bar] [bar_1] ON ([bar_1].[b] = [foo_1].[a] OR [bar_1].[b] IS NULL AND [foo_1].[a] IS NULL)
WHERE
	CONTAINS(([bar_1].*), N'''bar''')
```

### Environment details
linq2db version: 3.4.3
Database Server: SQL Server 2019
Database Provider: System.Data.SqlClient
Operating system: Windows Server 2019
.NET 5

**Comment by sdanyliv** [comment]
Use the following workaround: 
```cs
Sql.Ext.Max(bar.B).Over().PartitionBy(Sql.ToNullable(bar.Id) != null ? 1 : 0).ToValue()
```
