### ISSUE TITLE
PostgreSQL Test System.NullReferenceException when select with subquery + multiple left join with View contain null value (worked before 3.4.4-rc.6409)

### ISSUE THREAD

**Issue by sasukevita** [linq2db/linq2db#3217]
<details>
<summary>Views</summary>

```SQL
CREATE OR REPLACE VIEW "Member"."V_TableContainValue"
AS SELECT 1 AS "Id",
    'a'::text AS "Val1",
    'b'::text AS "Val2",
    'c'::text AS "Val3";

CREATE OR REPLACE VIEW "Member"."V_TableContainNullValue"
AS SELECT 1 AS "Id",
    'a'::text AS "Val1",
    NULL::text AS "Val2",
    'c'::text AS "Val3";
```

</details>

<details>
<summary>Model</summary>

```C#
[Table(Schema="Member", Name="Table")]
	public partial class Table
	{
		[PrimaryKey, NotNull] public int      Id   { get; set; } // integer
		[Column,     NotNull] public DateTime Date { get; set; } // date
		[Column,     NotNull] public TimeSpan Time { get; set; } // time without time zone

		#region Associations

		/// <summary>
		/// FK_Table2_Table_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ParentId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Table2> Table2 { get; set; }

		#endregion
	}

	[Table(Schema="Member", Name="Table2")]
	public partial class Table2
	{
		[PrimaryKey(1), NotNull    ] public int   Id       { get; set; } // integer
		[PrimaryKey(2), NotNull    ] public int   ParentId { get; set; } // integer
		[Column,           Nullable] public bool? IsTrue   { get; set; } // boolean

		#region Associations

		/// <summary>
		/// FK_Table2_Table
		/// </summary>
		[Association(ThisKey="ParentId", OtherKey="Id", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_Table2_Table", BackReferenceName="Table2")]
		public Table Table { get; set; }

		/// <summary>
		/// FK_Table3_Table2_BackReference
		/// </summary>
		[Association(ThisKey="Id, ParentId", OtherKey="Id, ParentId", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Table3> Table3 { get; set; }

		#endregion
	}

	[Table(Schema="Member", Name="Table3")]
	public partial class Table3
	{
		[Column, NotNull    ] public int   Id       { get; set; } // integer
		[Column, NotNull    ] public int   ParentId { get; set; } // integer
		[Column, NotNull    ] public int   SubId    { get; set; } // integer
		[Column,    Nullable] public bool? IsTrue   { get; set; } // boolean

		#region Associations

		/// <summary>
		/// FK_Table3_Table2
		/// </summary>
		[Association(ThisKey="Id, ParentId", OtherKey="Id, ParentId", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="FK_Table3_Table2", BackReferenceName="Table3")]
		public Table2 Table2 { get; set; }

		#endregion
	}


	[Table(Schema="Member", Name="V_TableContainNullValue", IsView=true)]
	public partial class V_TableContainNullValue
	{
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public int?   Id   { get; set; } // integer
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val1 { get; set; } // text
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val2 { get; set; } // text
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val3 { get; set; } // text
	}

	[Table(Schema="Member", Name="V_TableContainValue", IsView=true)]
	public partial class V_TableContainValue
	{
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public int?   Id   { get; set; } // integer
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val1 { get; set; } // text
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val2 { get; set; } // text
		[Column(SkipOnInsert=true, SkipOnUpdate=true), Nullable] public string Val3 { get; set; } // text
	}
```
</details>

Sample Condition must contain:
- LEFT JOIN other Table
- LEFT JOIN View that contain null value (V_TableContainNullValue)
- SubQuery with Data

Problem:
```C#
            db.Table3.Delete();
            db.Table2.Delete();
            db.Table.Delete();

            db.Insert(new Table { Id = 1, Date = DateTime.Today, Time = TimeSpan.FromSeconds(0) });
            db.Insert(new Table2 { Id = 1, ParentId = 1 });
            db.Insert(new Table3 { Id = 1, ParentId = 1, SubId = 1 });

            var query = (from x in db.Table2
                         join y1 in db.Table on x.ParentId equals y1.Id into a1
                         from z1 in a1.DefaultIfEmpty()
                         join y2 in db.V_TableContainNullValue on x.ParentId equals y2.Id into a2
                         from z2 in a2.DefaultIfEmpty()
                         select new
                         {
                             TId = z1 != null ? (int?)z1.Id : null,
                             Val1 = z2 != null ? z2.Val1 : null,
                             SubArrays = (from d in x.Table3
                                          select new
                                          {
                                              SubId = d.SubId,
                                          })
                         });
            query.ToArray(); //Error: System.NullReferenceException
```

last tested on linq2db 3.4.2 - 3.4.4-rc.6408 still works

error System.NullReferenceException when linq2db 3.4.4-rc.6409 - 3.4.4-rc.6421

### Environment details
linq2db version: 3.4.4-rc.6421
Database: PostgreSQL 12.1
.NET Framework: 4.7.2

**Comment by sdanyliv** [comment]
Could you please add call stack?

**Comment by sasukevita** [comment]
```
Exception thrown: 'System.NullReferenceException' in linq2db.dll
Object reference not set to an instance of an object.

System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>PGTest.exe</AppDomain><Exception><ExceptionType>System.NullReferenceException, mscorlib, Version=4.0.0.0, Culture=neutral, PublicKeyToken=b77a5c561934e089</ExceptionType><Message>Object reference not set to an instance of an object.</Message><StackTrace>   at lambda_method(Closure , String )
   at LinqToDB.Common.Internal.MTuple`6.GetHashCode() in /_/Source/LinqToDB/Common/Internal/MutableTuple.generated.cs:line 242
   at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at LinqToDB.Linq.Builder.EagerLoading.EagerLoadingContext`2.Add(TKey key, T item) in /_/Source/LinqToDB/Linq/Builder/EagerLoading.cs:line 48
   at LinqToDB.Linq.Builder.EagerLoading.&amp;lt;&amp;gt;c__DisplayClass43_0`2.&amp;lt;RegisterPreambles&amp;gt;b__0(IDataContext dc, Expression expr, Object[] ps) in /_/Source/LinqToDB/Linq/Builder/EagerLoading.cs:line 1543
   at LinqToDB.Linq.Builder.ExpressionBuilder.&amp;lt;&amp;gt;c__DisplayClass212_0`1.&amp;lt;RegisterPreamble&amp;gt;b__0(IDataContext dc, Expression e, Object[] ps) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs:line 3463
   at LinqToDB.Linq.Query.InitPreambles(IDataContext dc, Expression rootExpression, Object[] ps) in /_/Source/LinqToDB/Linq/Query.cs:line 209
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable&amp;lt;T&amp;gt;.GetEnumerator() in /_/Source/LinqToDB/Linq/ExpressionQuery.cs:line 308
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PGTest.Sample.TestBug.Run21(PayrollBozzMemberEntities db) in D:\Project\C#\PGTest\Sample\TestBug.cs:line 803
   at PGTest.Program.Main() in D:\Project\C#\PGTest\Program.cs:line 14</StackTrace><ExceptionString>System.NullReferenceException: Object reference not set to an instance of an object.
   at lambda_method(Closure , String )
   at LinqToDB.Common.Internal.MTuple`6.GetHashCode() in /_/Source/LinqToDB/Common/Internal/MutableTuple.generated.cs:line 242
   at System.Collections.Generic.ObjectEqualityComparer`1.GetHashCode(T obj)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at LinqToDB.Linq.Builder.EagerLoading.EagerLoadingContext`2.Add(TKey key, T item) in /_/Source/LinqToDB/Linq/Builder/EagerLoading.cs:line 48
   at LinqToDB.Linq.Builder.EagerLoading.&amp;lt;&amp;gt;c__DisplayClass43_0`2.&amp;lt;RegisterPreambles&amp;gt;b__0(IDataContext dc, Expression expr, Object[] ps) in /_/Source/LinqToDB/Linq/Builder/EagerLoading.cs:line 1543
   at LinqToDB.Linq.Builder.ExpressionBuilder.&amp;lt;&amp;gt;c__DisplayClass212_0`1.&amp;lt;RegisterPreamble&amp;gt;b__0(IDataContext dc, Expression e, Object[] ps) in /_/Source/LinqToDB/Linq/Builder/ExpressionBuilder.SqlBuilder.cs:line 3463
   at LinqToDB.Linq.Query.InitPreambles(IDataContext dc, Expression rootExpression, Object[] ps) in /_/Source/LinqToDB/Linq/Query.cs:line 209
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable&amp;lt;T&amp;gt;.GetEnumerator() in /_/Source/LinqToDB/Linq/ExpressionQuery.cs:line 308
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PGTest.Sample.TestBug.Run21(MemberEntities db) in D:\Project\C#\PGTest\Sample\TestBug.cs:line 803
   at PGTest.Program.Main() in D:\Project\C#\PGTest\Program.cs:line 14</ExceptionString></Exception></TraceRecord>
An unhandled exception of type 'System.NullReferenceException' occurred in linq2db.dll
```

**Comment by sdanyliv** [comment]
Got it, yes it's new, will fix that ASAP
