### ISSUE TITLE
System.ArgumentException: An item with the same key has already been added from ExpressionTreeOptimizationContext

### ISSUE THREAD

**Issue by tralalablblbl** [linq2db/linq2db#3242]
ArgumentException sometimes happens in a multithreading system

```
Exception message:
System.ArgumentException: An item with the same key has already been added.
Stack trace: 
at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.IsServerSideOnly(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.CanBeCompiledFind(CanBeCompiledContext context, Expression ex)
   at LinqToDB.Expressions.FindVisitor`1.Find(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.CanBeCompiled(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.RegisterParameter(Expression expression)
   at LinqToDB.Linq.Builder.EagerLoading.<>c.<PrepareParameters>b__41_0(ValueTuple`4 context, Expression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(LambdaExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(UnaryExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Linq.Builder.EagerLoading.PrepareParameters(Expression expr, ExpressionBuilder builder, ParameterContainer& container, Expression& correctedExpression)
   at LinqToDB.Linq.Builder.EagerLoading.<>c__DisplayClass43_0`2.<<RegisterPreambles>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass212_0`1.<<RegisterPreamble>b__1>d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at LinqToDB.Linq.Query.<InitPreamblesAsync>d__34.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.Linq.ExpressionQuery`1.<LinqToDB-Async-IQueryProviderAsync-ExecuteAsync>d__15`1.MoveNext()
```

### Steps to reproduce
Nothing special. The problem that simple Dictionary was used for caching 

https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Builder/ExpressionTreeOptimizationContext.cs
```c#
Dictionary<Expression, bool> _isServerSideOnlyCache = new ();
```
Possible solutions:
Replace Dictionary<Expression, bool> with ConcurenceDictionary<Expression, bool> or use Set instead of Add in 361 line
```c#
_isServerSideOnlyCache[expr] = result;
```

### Environment details
linq2db version: *3.4.3*
Database Server: *Azure ms sql*
Database Provider: *SqlServer*
Operating system: *Windows*
.NET Framework: *4.8*

**Comment by sdanyliv** [comment]
Well, it can happen if you use `DbConnection` in wrong way, `DbConnection` is not thread safe itself, and if you are trying to execute queries using the same `DbConnection` via threads, any UB exceptions may occur.
