### ISSUE TITLE
Postgre Test Problem Call Function Need Cast C# short to smallint when require smallint param

### ISSUE THREAD

**Issue by sasukevita** [linq2db/linq2db#3298]
<details>
<summary>DDL</summary>

```sql
CREATE OR REPLACE FUNCTION "Member"."fnTest2"(input1 integer, input2 smallint)
 RETURNS smallint
 LANGUAGE sql
AS $function$
   SELECT input2; 
$function$
;
```
</details>

<details>
<summary>Model</summary>

```C#
[Sql.Function(Name="\"Member\".\"fnTest2\"", ServerSideOnly=true)]
		public static short? fnTest2(int? input1, short? input2)
		{
			throw new InvalidOperationException();
		}
```
</details>

execute:
```C#
            var query = db.SelectQuery(() => SqlFunctions.fnTest2(1, 2));
            query.ToArray();//Npgsql.PostgresException: '42883: function Member.fnTest2(integer, integer) does not exist'
```

error detail:
```
Exception thrown: 'Npgsql.PostgresException' in mscorlib.dll
System.Transactions Critical: 0 : <TraceRecord xmlns="http://schemas.microsoft.com/2004/10/E2ETraceEvent/TraceRecord" Severity="Critical"><TraceIdentifier>http://msdn.microsoft.com/TraceCodes/System/ActivityTracing/2004/07/Reliability/Exception/Unhandled</TraceIdentifier><Description>Unhandled exception</Description><AppDomain>PGTest.exe</AppDomain><Exception><ExceptionType>Npgsql.PostgresException, Npgsql, Version=4.1.8.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7</ExceptionType><Message>42883: function Member.fnTest2(integer, integer) does not exist</Message><StackTrace>   at Npgsql.NpgsqlConnector.&amp;lt;&amp;gt;c__DisplayClass160_0.&amp;lt;&amp;lt;DoReadMessage&amp;gt;g__ReadMessageLong|0&amp;gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.&amp;lt;&amp;gt;c__DisplayClass160_0.&amp;lt;&amp;lt;DoReadMessage&amp;gt;g__ReadMessageLong|0&amp;gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlDataReader.&amp;lt;NextResult&amp;gt;d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.&amp;lt;ExecuteReaderAsync&amp;gt;d__102.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior) in /_/Source/LinqToDB/Data/DataConnection.cs:line 1400
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in /_/Source/LinqToDB/Data/DataConnection.cs:line 1410
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader() in /_/Source/LinqToDB/Data/DataConnection.QueryRunner.cs:line 497
   at LinqToDB.Linq.QueryRunner.&amp;lt;ExecuteQuery&amp;gt;d__11`1.MoveNext() in /_/Source/LinqToDB/Linq/QueryRunner.cs:line 380
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PGTest.Sample.TestBug.Run26(TestMemberEntities db) in D:\Project\C#\PGTest\Sample\TestBug.cs:line 942
   at PGTest.Program.Main() in D:\Project\C#\PGTest\Program.cs:line 14</StackTrace><ExceptionString>Npgsql.PostgresException (0x80004005): 42883: function Member.fnTest2(integer, integer) does not exist
   at Npgsql.NpgsqlConnector.&amp;lt;&amp;gt;c__DisplayClass160_0.&amp;lt;&amp;lt;DoReadMessage&amp;gt;g__ReadMessageLong|0&amp;gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlConnector.&amp;lt;&amp;gt;c__DisplayClass160_0.&amp;lt;&amp;lt;DoReadMessage&amp;gt;g__ReadMessageLong|0&amp;gt;d.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Npgsql.NpgsqlDataReader.&amp;lt;NextResult&amp;gt;d__44.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.&amp;lt;ExecuteReaderAsync&amp;gt;d__102.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(IDbCommand command, CommandBehavior commandBehavior) in /_/Source/LinqToDB/Data/DataConnection.cs:line 1400
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in /_/Source/LinqToDB/Data/DataConnection.cs:line 1410
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader() in /_/Source/LinqToDB/Data/DataConnection.QueryRunner.cs:line 497
   at LinqToDB.Linq.QueryRunner.&amp;lt;ExecuteQuery&amp;gt;d__11`1.MoveNext() in /_/Source/LinqToDB/Linq/QueryRunner.cs:line 380
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at PGTest.Sample.TestBug.Run26(TestMemberEntities db) in D:\Project\C#\PGTest\Sample\TestBug.cs:line 942
   at PGTest.Program.Main() in D:\Project\C#\PGTest\Program.cs:line 14
  Exception data:
    Severity: ERROR
    SqlState: 42883
    MessageText: function Member.fnTest2(integer, integer) does not exist
    Hint: No function matches the given name and argument types. You might need to add explicit type casts.
    Position: 10
    File: d:\pginstaller_12.auto\postgres.windows-x64\src\backend\parser\parse_func.c
    Line: 631
    Routine: ParseFuncOrColumn</ExceptionString><DataItems><Data><Key>Severity</Key><Value>ERROR</Value></Data><Data><Key>InvariantSeverity</Key><Value>ERROR</Value></Data><Data><Key>SqlState</Key><Value>42883</Value></Data><Data><Key>MessageText</Key><Value>function Member.fnTest2(integer, integer) does not exist</Value></Data><Data><Key>Hint</Key><Value>No function matches the given name and argument types. You might need to add explicit type casts.</Value></Data><Data><Key>Position</Key><Value>10</Value></Data><Data><Key>File</Key><Value>d:\pginstaller_12.auto\postgres.windows-x64\src\backend\parser\parse_func.c</Value></Data><Data><Key>Line</Key><Value>631</Value></Data><Data><Key>Routine</Key><Value>ParseFuncOrColumn</Value></Data></DataItems></Exception></TraceRecord>
An unhandled exception of type 'Npgsql.PostgresException' occurred in mscorlib.dll
42883: function Member.fnTest2(integer, integer) does not exist
```

query generated was
```sql
SELECT
	"Member"."fnTest2"(1, 2)
```

instead
```sql
SELECT
	"Member"."fnTest2"(1, 2::smallint)
```

### Environment details
linq2db version: 3.5.2-rc.6775
Database: PostgreSQL 12.1
.NET Framework: 4.7.2

**Comment by MaceWindu** [comment]
That's quite hard to decide how to fix it and postgresql [documentation](https://www.postgresql.org/docs/current/typeconv.html) doesn't help much here...
I think for now I will just add type hint (::smallint) to literals of `short` type.

**Comment by sasukevita** [comment]
its not just smallint, other type data may need cast too

ex: 
DLL
```sql
CREATE OR REPLACE FUNCTION "Member"."fnTest3"(input_var date)
 RETURNS integer
 LANGUAGE sql
AS $function$ 
   SELECT 1;
$function$
;
```
Model
```C#
		[Sql.Function(Name="\"Member\".\"fnTest3\"", ServerSideOnly=true)]
		public static int? fnTest3(DateTime? input_var)
		{
			throw new InvalidOperationException();
		}
```
Test
```C#
            var query = db.SelectQuery(() => SqlFunctions.fnTest3(DateTime.Now));
            query.ToArray();//Npgsql.PostgresException: '42883: function Member.fnTest3(timestamp without time zone) does not exist'
```


temp solution add new function
```sql
CREATE OR REPLACE FUNCTION "Member"."fnTest3"(input_var timestamp)
 RETURNS integer
 LANGUAGE sql
AS $function$ 
   SELECT "Member"."fnTest3"(input_var::date);
$function$
;
```

**Comment by sasukevita** [comment]
> 
> 
> That's quite hard to decide how to fix it and postgresql [documentation](https://www.postgresql.org/docs/current/typeconv.html) doesn't help much here... I think for now I will just add type hint (::smallint) to literals of `short` type.


how about add some attributes original info type in T4 generated model, so we can know what to cast when call the function

C# DateTime type in postgre can be "date" "timestamp" "timestamp with time zone" "timestamp without time zone" etc
