### ISSUE TITLE
bulk inserts on local sqlite db

### ISSUE THREAD

**Issue by giuliohome** [linq2db/linq2db#330]
I'm trying to insert some hundreds rows in a local db: it appears extremely slow:
more than 4 minutes for less than 600 recs with an overall db size of only 300 KB.

Sometimes I also see a contraint failure
```c#
UNIQUE constraint failed: cargo.request_key, cargo.request_row
   at System.Data.SQLite.SQLite3.Reset(SQLiteStatement stmt)
   at System.Data.SQLite.SQLite3.Step(SQLiteStatement stmt)
   at System.Data.SQLite.SQLiteDataReader.NextResult()
   at System.Data.SQLite.SQLiteDataReader..ctor(SQLiteCommand cmd, CommandBehavior behave)
   at System.Data.SQLite.SQLiteCommand.ExecuteReader(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery(CommandBehavior behavior)
   at System.Data.SQLite.SQLiteCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery() in i:\linq2db\Source\Data\DataConnection.cs:line 578
   at LinqToDB.Data.CommandInfo.Execute() in i:\linq2db\Source\Data\CommandInfo.cs:line 284
   at LinqToDB.DataProvider.MultipleRowsHelper`1.Execute() in i:\linq2db\Source\DataProvider\MultipleRowsHelper.cs:line 85
   at LinqToDB.DataProvider.BasicBulkCopy.MultipleRowsCopy1[T](MultipleRowsHelper`1 helper, DataConnection dataConnection, BulkCopyOptions options, IEnumerable`1 source) in i:\linq2db\Source\DataProvider\BasicBulkCopy.cs:line 246
   at LinqToDB.DataProvider.BasicBulkCopy.MultipleRowsCopy1[T](DataConnection dataConnection, BulkCopyOptions options, Boolean enforceKeepIdentity, IEnumerable`1 source) in i:\linq2db\Source\DataProvider\BasicBulkCopy.cs:line 200
   at LinqToDB.DataProvider.SQLite.SQLiteBulkCopy.MultipleRowsCopy[T](DataConnection dataConnection, BulkCopyOptions options, IEnumerable`1 source) in i:\linq2db\Source\DataProvider\SQLite\SQLiteBulkCopy.cs:line 13
   at LinqToDB.DataProvider.BasicBulkCopy.BulkCopy[T](BulkCopyType bulkCopyType, DataConnection dataConnection, BulkCopyOptions options, IEnumerable`1 source) in i:\linq2db\Source\DataProvider\BasicBulkCopy.cs:line 21
   at LinqToDB.DataProvider.SQLite.SQLiteDataProvider.BulkCopy[T](DataConnection dataConnection, BulkCopyOptions options, IEnumerable`1 source) in i:\linq2db\Source\DataProvider\SQLite\SQLiteDataProvider.cs:line 119
   at LinqToDB.Data.DataConnectionExtensions.BulkCopy[T](DataConnection dataConnection, IEnumerable`1 source) in i:\linq2db\Source\Data\DataConnectionExtensions.cs:line 214
```

but that's very strange, in fact I've double checked the contraints in the code:

```c#
using (var db = new MyContext<MyModel>())
{
	var bulk_list = resItems.ToList();
	var rows = bulk_list.Select(s => s.RequestRow).ToList();
	bool check_distinct = rows.Count == rows.Distinct().Count();
	if (!check_distinct) {
		MyService.SrvLog(sel.User,"distinct check failed: " +rows.Distinct().Count().ToString() +" vs " + rows.Count.ToString());
	}
	db.BulkCopy(bulk_list);
}
```

**Comment by giuliohome** [comment]
From a more accurate performance test, it appears that most of the time is consumed by the Linq logic before the BulkCopy and that the BulkCopy itself is quick enough. So I'm closing the issue for the moment.
