### ISSUE TITLE
Rare NullReferenceException in expression building

### ISSUE THREAD

**Issue by FlipSs** [linq2db/linq2db#3312]
Hello.
After upgrading to 3.4.4 (error also appears in 3.5.1) from 3.2.3 a very rare NullReferenceException began to appear on simple queries.
It mostly appears in a project that runs very often - about every 2 minutes (some tasks). At this run frequency the error repeats constantly ~ 3 times per day. Also I once caught this exception in tests in another project with a different query and database.
I think it has something to do with initialization (sometimes things go wrong, for example, due to concurrency), because I have never seen this error in heavily loaded web services yet, only in frequently performed tasks.
Tried to reproduce issue in tests but no success.

```
Exception message: Object reference not set to an instance of an object.
Stack trace in tasks (repeated): at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Mapping.MappingSchema.ReduceDefaultValue(Expression expr)
   at LinqToDB.Mapping.MappingSchema.GetConvertExpression(DbDataType from, DbDataType to, Boolean checkNull, Boolean createDefault)
   at LinqToDB.Mapping.MappingSchema.GetConvertExpression(Type from, Type to, Boolean checkNull, Boolean createDefault)
   at LinqToDB.Mapping.ColumnDescriptor.ApplyConversions(MappingSchema mappingSchema, Expression getterExpr, DbDataType dbDataType, IValueConverter valueConverter, Boolean includingEnum)
   at LinqToDB.Mapping.ColumnDescriptor.ApplyConversions(Expression getterExpr, DbDataType dbDataType, Boolean includingEnum)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildConstant(Expression expr, ColumnDescriptor columnDescriptor)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSqlExpression(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.UpdateBuilder.<BuildSetterWithContext>g__BuildSetter|9_0(MemberExpression memberExpression, Expression expression, <>c__DisplayClass9_0& )
   at LinqToDB.Linq.Builder.UpdateBuilder.<BuildSetterWithContext>g__BuildMemberInit|9_2(MemberInitExpression expression, Expression path, <>c__DisplayClass9_0& )
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildSetterWithContext(ExpressionBuilder builder, BuildInfo buildInfo, LambdaExpression setter, IBuildContext into, List`1 items, IBuildContext[] sequences)
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildSetter(ExpressionBuilder builder, BuildInfo buildInfo, LambdaExpression setter, IBuildContext into, List`1 items, IBuildContext sequence)
   at LinqToDB.Linq.Builder.InsertBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at LinqToDB.LinqExtensions.InsertAsync[T](ITable`1 target, Expression`1 setter, CancellationToken token)
   
Stack trace in tests (failed only once by now):
at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Mapping.MappingSchema.ReduceDefaultValue(Expression expr)
   at LinqToDB.Mapping.MappingSchema.GetConvertExpression(DbDataType from, DbDataType to, Boolean checkNull, Boolean createDefault)
   at LinqToDB.Mapping.MappingSchema.GetConvertExpression(Type from, Type to, Boolean checkNull, Boolean createDefault)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.CanBeConstantFind(Expression ex)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.<>c.<CanBeConstant>b__37_0(ExpressionTreeOptimizationContext ctx, Expression e)
   at LinqToDB.Expressions.FindVisitor`1.Find(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.CanBeConstant(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CanBeConstant(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressionTransformer(Expression e)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<ConvertExpression>b__136_0(ExpressionBuilder ctx, Expression e)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpression(Expression expression)
   at LinqToDB.Linq.Builder.MergeBuilder.InsertWhenNotMatched.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MergeBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
```

### Steps to reproduce

```c#
[Table("ProcessingJobs")]
	public class ProcessingJob
	{
		[Column]
		[PrimaryKey]
		public string FileName { get; set; }

		[Column]
		public string HostName { get; set; }

		[Column]
		public string TypeName { get; set; }

		[Column]
		public DateTime? StartedOn { get; set; }


		[Column]
		public DateTime? FinishedOn { get; set; }
		[Column]
		public ProcessedFileStatus Status { get; set; }
	}

	public enum ProcessedFileStatus
	{
		Started, Finished
	}

	public class MyDataConnection : DataConnection
	{

		static MyDataConnection()
		{
			Configuration.ContinueOnCapturedContext = false;
			Configuration.OptimizeForSequentialAccess = true;
		}

		public MyDataConnection(string connectionString) : base(ProviderName.SqlServer, connectionString)
		{
		}

		protected override Task<DbDataReader> ExecuteReaderAsync(IDbCommand command, CommandBehavior commandBehavior, CancellationToken cancellationToken)
		{
			return base.ExecuteReaderAsync(command, commandBehavior | CommandBehavior.SequentialAccess, cancellationToken);
		}
	}

	public class Test
	{
		// code that fails in tasks
		public async Task Tasks()
		{
			var fileName = "somename";
			var typeName = "somename";

			using (var connection = new MyDataConnection("connectionstring"))
			{
				// fail here
				await connection.GetTable<ProcessingJob>().InsertAsync(() => new ProcessingJob()
				{
					FileName = fileName,
					FinishedOn = null,
					HostName = Environment.MachineName,
					StartedOn = DateTime.Now,
					Status = ProcessedFileStatus.Started,
					TypeName = typeName
				}).ConfigureAwait(false);
			}
		}

		// code that failed once in tests (code is more complex there, and I don't known which table it was, but it is close to this one)
		public async Task Tests()
		{
			using (var connection = new MyDataConnection("connectionstring"))
			{
				var data = new SomeTable
				{
					UpdatedOn = DateTime.Now,
					Version = 0
				};

				var query = connection.GetTable<SomeTable>().Merge()
					.Using(new[] { data })
					.OnTargetKey()
					.InsertWhenNotMatched();

				// fail here
				await query.MergeAsync().ConfigureAwait(false);
			}
		}
	}

	[Table("SomeTable")]
	public class SomeTable
	{
		[PrimaryKey]
		public Guid UserId { get; set; }

		[Column]
		public byte[] Data { get; set; }

		[Column]
		public DateTime? UpdatedOn { get; set; }

		[Column]
		public int Version { get; set; }
	}
```

### Environment details
linq2db version: 3.5.1
Database Server: Sql Server 2017
.NET Framework: net5.0

**Comment by MaceWindu** [comment]
Also observed this error this week once

**Comment by MaceWindu** [comment]
Reproduced in test

**Comment by FlipSs** [comment]
Did you find out why the error occurs?
Can this error affect anything without throwing an error?

**Comment by MaceWindu** [comment]
It's race condition when multiple threads that use same mapping schema.
There is no bad side-effects except this exception which is quite rare.
Still I'm a bit amused that such thing is possible

**Comment by FlipSs** [comment]
Okay, thanks for the quick investigation :)
