### ISSUE TITLE
Postgres Bulk insert Problem with new Npgsql

### ISSUE THREAD

**Issue by jogibear9988** [linq2db/linq2db#3342]
New NpgSQL checks if underlying Column is "timestamp without timezone" or "timestamp with timezone".
You only now can insert a UTC DateTime to a "Timestamp with timezone". I now switched my columns to "timestamp with timezone", but BulkCopy still fails:

       System.InvalidCastException: 'Cannot write DateTime with Kind=UTC to PostgreSQL type 'timestamp without time zone', consider using 'timestamp with time zone'. Note that it's not possible to mix DateTimes with different Kinds in an array/range. See the Npgsql.EnableLegacyTimestampBehavior AppContext switch to enable legacy behavior.'

Is this a Npgsql error I need to report there, or do we maybe not have the column informations correct on bulk insert?
Do I need to provide the postgres type on BulkInsert?

![image](https://user-images.githubusercontent.com/364896/141596706-e73ef32d-64e3-490e-8672-c27165e51a93.png)

**Comment by jogibear9988** [comment]
see this call in the stacktrace:

the type in linq2db is timestamp and not timestamptz
![image](https://user-images.githubusercontent.com/364896/141596744-9cf9aeed-f8b3-4521-aa6a-451d021738ad.png)

**Comment by jogibear9988** [comment]
ftry to fixe it like this:

            mb.Entity<TagsArchiveDTO>()
                .HasTableName(tablePrefix + "VISU_TagsArchive")
                .Ignore(e => e.MccEntityState)
                .Ignore(e => e.StrippedDownDTO)
                .Property(e => e.Id).IsPrimaryKey()
                .Property(e => e.TagId)
                .Property(e => e.TagValue).HasDataType(LinqToDB.DataType.Decimal)
                .Property(e => e.ModifiedTimeStamp);


            mb.Entity<TagsArchiveDTO>(ProviderName.PostgreSQL)
             .Property(e => e.ModifiedTimeStamp).HasDbType("timestamptz");
             
 see #3130 

but it did not work

**Comment by jogibear9988** [comment]
this works...

            mb.Entity<TagsArchiveDTO>()
                .HasTableName(tablePrefix + "VISU_TagsArchive")
                .Ignore(e => e.MccEntityState)
                .Ignore(e => e.StrippedDownDTO)
                .Property(e => e.Id).IsPrimaryKey()
                .Property(e => e.TagId)
                .Property(e => e.TagValue).HasDataType(LinqToDB.DataType.Decimal)
                .Property(e => e.ModifiedTimeStamp)
                .HasAttribute(new ColumnAttribute() { Configuration = ProviderName.PostgreSQL, DbType = "timestamptz" });

**Comment by jogibear9988** [comment]
@MaceWindu 
can i change default, so postgres always maps to "timestamptz" ?

**Comment by jogibear9988** [comment]
cause I have all columns like so, if not I need to change all mappings.

**Comment by jogibear9988** [comment]
see also:

https://github.com/npgsql/doc/pull/116/files#diff-b69d89926b0fade3dcdf89f0e45dbfd01aeb483dad11dd1e618f6fec7f1f0592R35

* DateTime properties now map to `timestamptz` by default, instead of to `timestamp`; although storing UTC timestamps is the recommended pattern, this will cause the first migration to change your column type.
*

**Comment by MaceWindu** [comment]
I'm working on required changes to make migration seamless.
Could you create test that shows code, that worked before and now is broken without changes?

**Comment by jogibear9988** [comment]
don't think we have an error about this.
but the mapping error

        mb.Entity<TagsArchiveDTO>(ProviderName.PostgreSQL)
         .Property(e => e.ModifiedTimeStamp).HasDbType("timestamptz");

does still exist.

and can I change columntype for all postgres datetime types?

**Comment by MaceWindu** [comment]
We already have issue for fluent mapping with configuration name #3136

**Comment by MaceWindu** [comment]
```cs
ms.AddScalarType(typeof(DateTime),  your type here);
ms.AddScalarType(typeof(DateTime?),  your type here);
```

**Comment by jogibear9988** [comment]
ahh sorry thought you closed #3130 cause it was fixed

**Comment by jogibear9988** [comment]
> ```cs
> ms.AddScalarType(typeof(DateTime),  your type here);
> ```

how should I use it?
I can only select a DataType, but I need to set that for
DataType.DateTime on postgre we should use "timestamptz"

**Comment by jogibear9988** [comment]
for addscalartype we have no overload wich can use a string

**Comment by MaceWindu** [comment]
use
```cs
public void AddScalarType(Type type, SqlDataType dataType)
```

but `DataType.DateTimeOffset` should be enough

**Comment by jogibear9988** [comment]
and SqlDataType also has DataType in it's constructors and no DbType string property

**Comment by MaceWindu** [comment]
it has

**Comment by jogibear9988** [comment]
you're right....
but vs didn't suggest me....
soooorrryy

**Comment by jogibear9988** [comment]
Should I leave this open? Do you think we need to do something about npgsql default changed?
Could you update linq2db npgsql package, so we see if smth. is broken?

**Comment by jogibear9988** [comment]
my issue at npgsql: https://github.com/npgsql/npgsql/issues/4133

**Comment by MaceWindu** [comment]
I didn't found anything wrong with current defaults. Only issue I found is that we need to set `timestamp` type for `DateTime.DateTime` and `DateTime.DateTime2` parameters or npgsql will try to use `timestamptz` and fail

**Comment by jogibear9988** [comment]
I've now switched everything to timestamptz in my database, and on bulk insert linq2db picks timestamp, so it fails.
So there seems to be an inconsitency.
If you use DateTime.utc without timestamptz Type in postgres, npgsql will fail in new version

**Comment by jogibear9988** [comment]
@MaceWindu 

if I add:

            this.MappingSchema.AddScalarType(typeof(DateTime), "timestamptz");
            this.MappingSchema.AddScalarType(typeof(DateTime?), "timestamptz");
            this.MappingSchema.AddScalarType(typeof(DateTimeOffset), "timestamptz");
            this.MappingSchema.AddScalarType(typeof(DateTimeOffset?), "timestamptz");

I get this exception:

	   at System.Linq.Expressions.Expression.Constant(Object value, Type type)
	   at LinqToDB.Expressions.ConvertFromDataReaderExpression.GetColumnReader(IDataContext dataContext, MappingSchema mappingSchema, IDataReader dataReader, Type type, IValueConverter converter, Int32 idx, Expression dataReaderExpr, Boolean forceNullCheck)
	   at LinqToDB.Expressions.ConvertFromDataReaderExpression.Reduce(IDataContext dataContext, IDataReader dataReader, Expression dataReaderParam)
	   at LinqToDB.Linq.QueryRunner.Mapper`1.<>c.<TransformMapperExpression>b__5_1(TransformMapperExpressionContext context, Expression e)
	   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
	   at LinqToDB.Expressions.TransformVisitor`1.Modify(MemberBinding b)
	   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source, Func`2 func)
	   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MemberInitExpression e)
	   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
	   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
	   at LinqToDB.Expressions.TransformVisitor`1.TransformX(MethodCallExpression e)
	   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
	   at LinqToDB.Expressions.TransformVisitor`1.TransformX(UnaryExpression e)
	   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
	   at LinqToDB.Expressions.TransformVisitor`1.TransformX(BinaryExpression e)
	   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
	   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
	   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
	   at LinqToDB.Expressions.TransformVisitor`1.TransformX(LambdaExpression e)
	   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
	   at LinqToDB.Expressions.Extensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
	   at LinqToDB.Linq.QueryRunner.Mapper`1.TransformMapperExpression(IDataContext context, IDataReader dataReader, Type dataReaderType, Boolean slowMode)
	   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IDataContext context, IQueryRunner queryRunner, IDataReader dataReader)
	   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__11`1.MoveNext()
	   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
	   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
	   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass4_0`1.<GetFirstOrDefaultElement>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
	   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
	   at System.Linq.Queryable.FirstOrDefault[TSource](IQueryable`1 source, Expression`1 predicate)
	   at MCC.Common.CommonServiceImpl.Default.ImportDefaultMessages.CheckForTranslatedMessage(CommonDL commonDl) in D:\csharp\git\mcc5ordner2\MCC.V1.0\2Services\ServiceInfrastructure\MCC.Common.CommonServiceImpl\Default\ImportDefaultMessages.cs:line 133
	   at MCC.Common.CommonServiceImpl.Default.ImportDefaultMessages.Import(CommonDL commonDl) in D:\csharp\git\mcc5ordner2\MCC.V1.0\2Services\ServiceInfrastructure\MCC.Common.CommonServiceImpl\Default\ImportDefaultMessages.cs:line 65
	   at MCC.Common.CommonServiceImpl.Default.ImportDefault.<>c__DisplayClass0_0.<Import>b__3() in D:\csharp\git\mcc5ordner2\MCC.V1.0\2Services\ServiceInfrastructure\MCC.Common.CommonServiceImpl\Default\ImportDefault.cs:line 60
	   at System.Threading.Tasks.Task.InnerInvoke()
	   at System.Threading.Tasks.Task.<>c.<.cctor>b__271_0(Object obj)
	   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
	--- End of stack trace from previous location ---
	   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
	   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
	   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)

**Comment by MaceWindu** [comment]
I still need a test that demonstrates your issue. I've migrated our tests to npgsql 6 and didn't found any serious issue yet #3343

**Comment by jogibear9988** [comment]
The problem on our system is, we only use UTC Time at the database, and I've converted all database datetimes to "timestamptz".

But why does 

        this.MappingSchema.AddScalarType(typeof(DateTime), "timestamptz");
        this.MappingSchema.AddScalarType(typeof(DateTime?), "timestamptz");
        this.MappingSchema.AddScalarType(typeof(DateTimeOffset), "timestamptz");
        this.MappingSchema.AddScalarType(typeof(DateTimeOffset?), "timestamptz");

not work?

in postgres Mapping schema we have following code:

			SetValueToSqlConverter(typeof(DateTime), (sb,dt,v) => BuildDateTime(sb, dt, (DateTime)v));


and

		static void BuildDateTime(StringBuilder stringBuilder, SqlDataType dt, DateTime value)
		{
			string dbType;
			string format;

			if (value.Millisecond == 0)
			{
				if (value.Hour == 0 && value.Minute == 0 && value.Second == 0)
				{
					format = DATE_FORMAT;
					dbType = dt.Type.DbType ?? "date";
				}
				else
				{
					format = TIMESTAMP0_FORMAT;
					dbType = dt.Type.DbType ?? "timestamp";
				}
			}
			else
			{
				format = TIMESTAMP3_FORMAT;
				dbType = dt.Type.DbType ?? "timestamp";
			}

			stringBuilder.AppendFormat(CultureInfo.InvariantCulture, format, value, dbType);
		}

**Comment by jogibear9988** [comment]
I don't know how in our case to create a custom postgres database with "timestamptz" column.
But try to bulk insert into a Postgre DB a UTCTime with a "timestamptz" column.
For this you need to change the dbtype to "timestamp".

But I want to set it for all mapped columns, and not for each one individual

**Comment by MaceWindu** [comment]
1. You don't need to change DTO mapping as it is already mapped to tstz type
```cs
    this.MappingSchema.AddScalarType(typeof(DateTimeOffset), "timestamptz");
    this.MappingSchema.AddScalarType(typeof(DateTimeOffset?), "timestamptz");
```
2. there is no AddScalarType that takes dbtype directly, you actually call `AddScalarType(Type type, object? defaultValue, DataType dataType = DataType.Undefined)` method here. Proper call is:
```cs
   this.MappingSchema.AddScalarType(typeof(DateTime), new SqlDataType(DataType.DateTimeOffset, typeof(DateTime), "timestamptz"));
   this.MappingSchema.AddScalarType(typeof(DateTime?), new SqlDataType(DataType.DateTimeOffset, typeof(DateTime), "timestamptz"));
```

but I'm not sure why you need to use dbtype. This should be enough for you:
```cs
    this.MappingSchema.AddScalarType(typeof(DateTimeOffset), DataType.DateTimeOffset);
    this.MappingSchema.AddScalarType(typeof(DateTimeOffset?), DataType.DateTimeOffset);

```

**Comment by jogibear9988** [comment]
so I've created a test.

Fails on my system if I use npgsql > 6

Also tried your fix, still fails...

https://github.com/linq2db/linq2db/pull/3349

**Comment by roji** [comment]
@MaceWindu let me know if you need any help/guidance from the Npgsql side (or see any issue there). @vonzshik you may be interested in this too.

> I didn't found anything wrong with current defaults. Only issue I found is that we need to set timestamp type for DateTime.DateTime and DateTime.DateTime2 parameters or npgsql will try to use timestamptz and fail

Note that we've changed DbType.DateTime to now map to timestamptz, not timestamp (this is a breaking change, [see the release notes](https://www.npgsql.org/doc/release-notes/6.0.html#major-changes-to-timestamp-mapping)).. DbType.DateTime2 continues to map to timestamp as before.

But all in all, my recommendation would be to not set DbType by default (in general), but rather to let Npgsql decide on the correct PostgreSQL type based on the given parameter value. This way the right type can also be chosen based on DateTime.Kind (timestamptz for UTC, timestamp for non-UTC).

**Comment by jogibear9988** [comment]
@roji does the gues als work for BulkInsert?

**Comment by MaceWindu** [comment]
@roji , thanks, we are fine here. By `DateTime`/`DateTime2` I mean members of linq2db-specifc [DataType types enum](https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataType.cs). We shouldn't break mappings for existing applications, so some minor tweaks were needed (all tests pass again).

**Comment by roji** [comment]
@MaceWindu good to know.

One thing I'm wondering about - I'm assuming LinqToDB.DataType is somewhat similar to System.Data's DbType, i.e. a database-agnostic abstraction over database types. If that's so, then note that Npgsql itself did do a breaking change in how DbType values are interpreted. Of course you have your own breaking changes policy etc., but I think some breakage around the timestamp handling is expected (and even necessary).
