### ISSUE TITLE
Union of entity with complex type throws exception 

### ISSUE THREAD

**Issue by zbrkic** [linq2db/linq2db#3346]
Hi,

Union of entity with complex type throws exception.
The same exception is thrown when _Concat_ is used.

```
Exception message:
Sequence contains no matching element
Stack trace:
   at System.Linq.Enumerable.First[TSource](IEnumerable`1 source, Func`2 predicate)
   at LinqToDB.Linq.Builder.SetOperationBuilder.SetOperationContext.Init()
   at LinqToDB.Linq.Builder.SetOperationBuilder.SetOperationContext..ctor(SubQueryContext sequence1, SubQueryContext sequence2, MethodCallExpression methodCall)
   at LinqToDB.Linq.Builder.SetOperationBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.CountBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
```

### Steps to reproduce

```c#
using LinqToDB;
using LinqToDB.Mapping;
using System.Linq;

namespace Linq2dbTest
{
    public class UnionTest
    {
        public void Test()
        {
            var builder = MappingSchema.Default.GetFluentMappingBuilder();

            builder.Entity<ComplexPerson>()
                .Property(e => e.Name.FirstName).HasColumnName("FirstName")
                .Property(e => e.Name.LastName).HasColumnName("LastName");

            using (var db = new Db())
            {
                var personQuery1 = from x in db.Person
                                   where x.Id < 10
                                   select x;

                var personQuery2 = from x in db.Person
                                   where x.Id < 20
                                   select x;

                var unionQuery = personQuery1.Union(personQuery2);

                // System.InvalidOperationException
                // Sequence contains no matching element
                var count = unionQuery.Count();  // or Any() or ToList() etc.
            }
        }

        public class Db : LinqToDB.Data.DataConnection
        {
            public Db() : base(ProviderName.SqlServer2017, "data source=localhost;initial catalog=xxx;integrated security=True;MultipleActiveResultSets=True") { }
            public ITable<ComplexPerson> Person => GetTable<ComplexPerson>();
        }

        public class ComplexPerson
        {
            public int Id { get; set; }
            public FullName Name { get; set; }
        }

        public class FullName
        {
            public string FirstName { get; set; }
            public string LastName { get; set; }
        }
    }
}
```

### Environment details
linq2db version: *3.5.2*
Database Server: *SQL Server 2019*
Database Provider: *SQL*
Operating system: *W10*
.NET Framework: *4.8*

**Comment by sdanyliv** [comment]
@zbrkic, just notice for your production. Do not use  `MappingSchema.Default` for defining mapping. It is global configuration and should be done ONCE per application.

`DataConnection` has `AddMppingSchema` and constructor which accepts mapping schema.

**Comment by zbrkic** [comment]
Thanks @sdanyliv. It is done once per application (using singleton schema provider), but  `MappingSchema.Default` is used. Should `new MappingSchema()` be used instead? In that case, what to do with configuration provided by DefaultMappingSchema (AddScalarType calls in constructor, etc.)? Is that needed?

**Comment by sdanyliv** [comment]
If you are doing it once, it is ok.
