### ISSUE TITLE
LinqToDB.Linq.LinqException "Invalid expression"

### ISSUE THREAD

**Issue by KeterSCP** [linq2db/linq2db#3356]
```
Exception message: 
Invalid expression x.Table1Item.Name
Stack trace:
   at LinqToDB.Linq.Builder.SelectContext.GetMemberExpression(Expression newExpression, Expression expression, Int32 level)
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T,TContext](TContext context, Expression expression, MemberExpression levelExpression, Int32 level, Func`7 action)
   at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag)
   at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<CheckSubQueryForWhere>b__123_0(CheckSubQueryForWhereContext context, Expression expr)
   at LinqToDB.Expressions.VisitFuncVisitor`1.Visit(Expression expr)
   at LinqToDB.Expressions.VisitFuncVisitor`1.Visit(Expression expr)
   at LinqToDB.Expressions.Extensions.Visit[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CheckSubQueryForWhere(IBuildContext context, Expression expression, Boolean& makeHaving)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.CountBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.<LinqToDB-Async-IQueryProviderAsync-ExecuteAsync>d__15`1.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
```

### Steps to reproduce
Consider having 2 tables: `Table1` and `Table2` with relationship one-to-many. Models generated by T4 template look like this
```c#
	[Table(Schema="public", Name="table1")]
	public partial class Table1
	{
		[Column("id",   DataType=LinqToDB.DataType.Int32, Precision=32, Scale=0), PrimaryKey, Identity] public int    Id   { get; set; } // integer
		[Column("name", DataType=LinqToDB.DataType.Text),                         NotNull             ] public string Name { get; set; } // text

		#region Associations

		/// <summary>
		/// fk_table1_id_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="Table1Id", CanBeNull=true, Relationship=LinqToDB.Mapping.Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Table2> Fkids { get; set; }

		#endregion
	}

	[Table(Schema="public", Name="table2")]
	public partial class Table2
	{
		[Column("id",        DataType=LinqToDB.DataType.Int32, Precision=32, Scale=0), PrimaryKey, Identity] public int Id       { get; set; } // integer
		[Column("table1_id", DataType=LinqToDB.DataType.Int32, Precision=32, Scale=0), NotNull             ] public int Table1Id { get; set; } // integer

		#region Associations

		/// <summary>
		/// fk_table1_id
		/// </summary>
		[Association(ThisKey="Table1Id", OtherKey="Id", CanBeNull=false, Relationship=LinqToDB.Mapping.Relationship.ManyToOne, KeyName="fk_table1_id", BackReferenceName="Fkids")]
		public Table1 Table1 { get; set; }

		#endregion
	}
```

Then I have 2 dto classes:

```c#
    public class Table2Item
    {
        public Table1Item Table1Item { get; }

        public Table2Item(Table1Item table1Item)
        {
            Table1Item = table1Item;
        }
    }

    public class Table1Item
    {
        public string Name { get; }

        public Table1Item(string name)
        {
            Name = name;
        }
    }
```

And following code throws an exception "Invalid expression x.Table1Item.Name"

```c#
        public async Task<int> TestCount()
        {
            await using var db = new HSDB();

            var query = db.Table2
                .LoadWith(x => x.Table1)
                .Select(x => new Table2Item(new Table1Item(x.Table1.Name)))
                .Where(x => x.Table1Item.Name == "123");

            var count = await query.CountAsync();

            return count;


        }   
```

But if I change models to accept data via `set` or `init` like this:

```c#
    public class Table2Item
    {
        public Table1Item Table1Item { get; set; }
    }

    public class Table1Item
    {
        public string Name { get; set; }
    }
```

And select them using object initializer, everything works fine:

```c#
        public async Task<int> TestCount()
        {
            await using var db = new HSDB();

            var query = db.Table2
                .LoadWith(x => x.Table1)
                .Select(x => new Table2Item
                {
                    Table1Item = new Table1Item
                    {
                        Name = x.Table1.Name
                    }
                })
                .Where(x => x.Table1Item.Name == "123");

            var count = await query.CountAsync();

            return count;
        }   
```

### Environment details
linq2db version: 3.6.0
Database Server: PostgreSQL
Database Provider: Npgsql
Operating system: WIN10
.NET Framework: .NET5

**Comment by sdanyliv** [comment]
It is as designed. We cannot tack property `Table1Item` because translator cannot see body of your constructor.
Maybe [this answer](https://stackoverflow.com/questions/63727166/linq2db-filter-by-nested-property-field) will be helpful for you

**Comment by KeterSCP** [comment]
Oh, I see now. The link was very helpful
