### ISSUE TITLE
Filter on selection with null check on FK property throws NullReferenceException

### ISSUE THREAD

**Issue by zbrkic** [linq2db/linq2db#3371]
Hi,

Filtering selection with null check on FK propery throws NullReferenceException. If selection uses navigation property for null check exception is not thrown.

Method RemoveNullPropagation makes the difference:

```c#
else if (IsNullConstant(conditional.IfTrue)
	&& ((nullRight && !MappingSchema.IsScalarType(binary.Left.Type)) ||
		(nullLeft  && !MappingSchema.IsScalarType(binary.Right.Type))))
{
	return GetRemoveNullPropagationTransformer().Transform(conditional.IfFalse);
}

```

In case of FK property (scalar type) null propagation removal is not not called.

Exception message:

`Object reference not set to an instance of an object.`

Stack trace:
```
at LinqToDB.Linq.Builder.SelectContext.<>c.<ConvertToIndexInternal>b__49_2(ValueTuple`4 context, Int32 n, IBuildContext ctx, Expression ex, Int32 l, Expression _)
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T,TContext](TContext context, Expression expression, MemberExpression levelExpression, Int32 level, Func`7 action)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Linq2dbTest.FilterTest.Test() in C:\Users\zbrkic\source\repos\Linq2dbTest\FilterTest.cs:line 51
```

### Steps to reproduce

```c#

using LinqToDB;
using LinqToDB.Mapping;
using System.Linq;

namespace Linq2dbTest
{
    public class FilterTest
    {
        public void Test()
        {
            var builder = MappingSchema.Default.GetFluentMappingBuilder();

            builder.Entity<Employee>()
                 .Association(x => x.PayRate, x => x.PayRateId, x => x.Id);

            builder.Entity<PayRate>();

            using (var db = new Db())
            {
                var queryNavProp = db.Employees
                    .Select(x => new
                    {
                        x.Id,
                        PayRate = x.PayRate == null // nav property
                        ? null
                        : new
                        {
                            x.Id,
                            x.PayRate.Name,
                        }
                    })
                    .Where(item => item.PayRate.Name.Equals("test"));

                var good = queryNavProp.ToList();

                var queryFK = db.Employees
                    .Select(x => new 
                    {
                        x.Id, 
                        PayRate = x.PayRateId == null // FK property
                        ? null
                        : new 
                        {
                            x.Id,
                            x.PayRate.Name,
                        }
                    })
                    .Where(item => item.PayRate.Name.Equals("test"));

                var bad = queryFK.ToList(); // System.NullReferenceException
            }
        }

        public class Db : LinqToDB.Data.DataConnection
        {
            public Db() : base(ProviderName.SqlServer2017, "data source=localhost;initial catalog=xxx;integrated security=True;MultipleActiveResultSets=True") { }
            public ITable<Employee> Employees => GetTable<Employee>();
        }

        public class Employee
        {
            public int Id { get; set; }
            public PayRate PayRate { get; private set; }
            public int? PayRateId { get; private set; }
        }

        public class PayRate
        {
            public int Id { get; set; }
            public string Name { get; set; }
        }
    }
}

```

### Environment details
linq2db version: *3.5.2*
Database Server: *SQL Server 2019*
Database Provider: *SQL*
Operating system: *W10*
.NET Framework: *4.8*

**Comment by zbrkic** [comment]
Do you know any workaround? We have only FK property without navigation property, and cannot add navigation property.

**Comment by sdanyliv** [comment]
Not sure, this is very special case which I'm working right now. Unfortunately it is very cardinal parsing refactoring for 4.0.
Anyway try to use instead of `Equals` just `==`
```cs
.Where(item => item.PayRate.Name == "test")
```

**Comment by zbrkic** [comment]
The same exception is thrown when ```==``` is used.
