### ISSUE TITLE
LinqToDB.Common.LinqToDBConvertException: Cannot convert value '1/25/1980 12:00:00 AM: System.DateTime' to type 'System.DateOnly'

### ISSUE THREAD

**Issue by cspwizard** [linq2db/linq2db#3382]
Not sure if .net 6.0 is completely supported at this point, but I've and issue with DateOnly fields. Query fails on materialization

```
Exception message: Cannot convert value '1/25/1980 12:00:00 AM: System.DateTime' to type 'System.DateOnly'

Stack trace:
LinqToDB.Common.LinqToDBConvertException: Cannot convert value '1/25/1980 12:00:00 AM: System.DateTime' to type 'System.DateOnly'
 ---> System.InvalidCastException: Invalid cast from 'System.DateTime' to 'System.DateOnly'.
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.DateTime.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at LinqToDB.Common.ConvertBuilder.ConvertDefault(Object value, Type conversionType)
   --- End of inner exception stack trace ---
   at LinqToDB.Common.ConvertBuilder.ConvertDefault(Object value, Type conversionType)
   at lambda_method1066(Closure , IDataReader )
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader)
   at lambda_method1059(Closure , IQueryRunner , IDataReader )
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IDataContext context, IQueryRunner queryRunner, IDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Vtbf.Contractors.Application.CQRS.ContractorsLegal.ContractorLegalQueryByFilter.Handler.SelectWithSearchQueryAsync(ContractorLegalQueryByFilter request, CancellationToken cancellationToken) in /home/konstantin/sources/....cs:line 82
```

### Steps to reproduce

Fails on materialization

### Environment details
linq2db version: *3.6*
Database Server: *Postgres 14*
Database Provider: *Npgsql.EntityFrameworkCore.PostgreSQL 6.0.1*
Operating system: *Ubuntu 21.10*
.NET Framework: *.net 6.0*

**Comment by MaceWindu** [comment]
You just need to define `DateTime => DateOnly` conversion in your mapping schema.
```cs
// e.g. to Default schema
MappingSchema.Default.SetConverter<DateTime, DateOnly>(dt => DateOnly.FromDateTime(dt));
```

but yes, we need to embedd those conversions into linq2db at some point.

**Comment by viceroypenguin** [comment]
Fixed by #3502

**Comment by SteveDunn** [comment]
> You just need to define `DateTime => DateOnly` conversion in your mapping schema.
> 
> ```cs
> // e.g. to Default schema
> MappingSchema.Default.SetConverter<DateTime, DateOnly>(dt => DateOnly.FromDateTime(dt));
> ```
> 
> but yes, we need to embedd those conversions into linq2db at some point.

Hi - thank you for that information! Using 4.4, I don't seem to need that for `DateTime => DateOnly`, but I *do* need it for `DateTime => TimeOnly`.  @viceroypenguin - any ideas on this one? I'm adding support for DateOnly/TimeOnly into Vogen (https://github.com/SteveDunn/Vogen/issues/310)

**Comment by viceroypenguin** [comment]
@SteveDunn I haven't implemented `TimeOnly` yet - haven't found a use for it yet. If you need it, I'll put something together soon.

**Comment by SteveDunn** [comment]
Thank you. The workaround works well enough for what Vogen requires. I just merged the PR

https://github.com/SteveDunn/Vogen/pull/320/files#diff-3242da43965b9d1428085c7058b25a8260d0e7fdb2da6c82a376a3ef953c10cc

**Comment by viceroypenguin** [comment]
Thanks @SteveDunn!
