### ISSUE TITLE
How properly use hstore

### ISSUE THREAD

**Issue by pavelvondrasek** [linq2db/linq2db#3385]
Hi,

I'm using latest linq2db and have entity:

```cs
[Table("product_categories", Schema = "plm")]
public class Category : IEntity<int?>
{
    [PrimaryKey]
    [Identity]
    [Column("id")]
    public int? Id { get; set; }

    [Column("title", DbType = "public.hstore")]
    public Dictionary<string, string> Title { get; set; } = new();

    [Column("description", DbType = "public.hstore")]
    public Dictionary<string, string> Description { get; set; } = new();
}
```

I'm trying new data:
```cs
            db.CreateTable<Category>();

            db.Insert(new Category
            {
                Title = new Dictionary<string, string>
                {
                    { "en", "MTB FULL-SUSPENSION" }
                }
            });

            db.Insert(new Category
            {
                Title = new Dictionary<string, string>
                {
                    { "en", "MTB HARDTAIL" }
                }
            });
```

(Note: I'm re-creating table because this code is from database fixture in test project)

I get error:
System.NotSupportedException
IEnumerable parameters are not supported, pass an array or List instead
   at Npgsql.TypeMapping.ConnectorTypeMapper.ResolveByClrType(Type type)
   at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlParameterCollection.ValidateAndBind(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass31_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.Insert`1.Query(IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String serverName, String databaseName, String schemaName, TableOptions tableOptions)
   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String databaseName, String schemaName, String serverName, TableOptions tableOptions)
   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, String serverName, TableOptions tableOptions)
   at Tests.ApiTestFixture.<>c.<ConfigureWebHost>b__0_0(IServiceCollection services) in /Users/pavel/RiderProjects/BikeFun.PLM/Tests/ApiTestFixture.cs:line 62
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass10_0.<ConfigureServices>b__0(WebHostBuilderContext context, IServiceCollection services)
   at Microsoft.AspNetCore.Hosting.GenericWebHostBuilder.<>c__DisplayClass11_0.<ConfigureServices>b__0(HostBuilderContext context, IServiceCollection builder)
   at Microsoft.Extensions.Hosting.HostBuilder.CreateServiceProvider()
   at Microsoft.Extensions.Hosting.HostBuilder.Build()
   at Microsoft.AspNetCore.Builder.WebApplicationBuilder.Build()
   at Program.<Main>$(String[] args) in /Users/pavel/RiderProjects/BikeFun.PLM/Backend/Program.cs:line 50
--- End of stack trace from previous location ---
   at Microsoft.Extensions.Hosting.HostFactoryResolver.HostingListener.CreateHost()
   at Microsoft.Extensions.Hosting.HostFactoryResolver.<>c__DisplayClass8_0.<ResolveHostFactory>b__0(String[] args)
   at Microsoft.AspNetCore.Mvc.Testing.DeferredHostBuilder.Build()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateHost(IHostBuilder builder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.ConfigureHostBuilder(IHostBuilder hostBuilder)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.EnsureServer()
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateDefaultClient(Uri baseAddress, DelegatingHandler[] handlers)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient(WebApplicationFactoryClientOptions options)
   at Microsoft.AspNetCore.Mvc.Testing.WebApplicationFactory`1.CreateClient()
   at Tests.Endpoints.GetCategoriesTests..ctor(ApiTestFixture fixture) in /Users/pavel/RiderProjects/BikeFun.PLM/Tests/Endpoints/GetCategoriesTests.cs:line 15

And this is from console:
      BeforeExecute
      --  PostgreSQL.9.5 PostgreSQL
      DECLARE @Title Hstore -- Object
      SET     @Title = System.Collections.Generic.Dictionary`2[System.String,System.String]
      DECLARE @Description Hstore -- Object
      SET     @Description = System.Collections.Generic.Dictionary`2[System.String,System.String]
      
      INSERT INTO plm.product_categories
      (
      	title,
      	description
      )
      VALUES
      (
      	:Title,
      	:Description
      )

**Comment by MaceWindu** [comment]
```cs
[Column("description", DbType = "public.hstore")]
```

try
```cs
[Column("description", DbType = "hstore")]
```
or
```cs
[Column("description", DataType = DataType.Dictionary)]
```

**Comment by pavelvondrasek** [comment]
I'm so sorry I'm very busy now. Problem was caused by recreating database for tests and hstore extension was changed every time.
