### ISSUE TITLE
CompareTo cannot be converted to SQL for Guid

### ISSUE THREAD

**Issue by riberk** [linq2db/linq2db#3394]
I am trying to use `int CompareTo(Guid value)` method (because Guid does not overload compare operators), but it is not working.

```
Exception message: 'x.Id.CompareTo(value(Tests.Test+<>c__DisplayClass2_0).id)' cannot be converted to SQL.
Stack trace:

   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Tests.Test.CompareTo() in Test.cs:line 40
   at Tests.Test.CompareTo() in Test.cs:line 40
   at Tests.Test.CompareTo() in Test.cs:line 40
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_1.<<InvokeTestMethodAsync>b__1>d.MoveNext() in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\Runners\TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in C:\Dev\xunit\xunit\src\xunit.execution\Sdk\Frameworks\ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in C:\Dev\xunit\xunit\src\xunit.core\Sdk\ExceptionAggregator.cs:line 90

```

### Steps to reproduce
It's need postgres on localhost:5432 with created database l2db_tests.

```c#
using System;
using System.Linq;
using System.Threading.Tasks;
using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;
using Xunit;
using Xunit.Abstractions;

namespace Tests;

public class Test
{
    private readonly ITestOutputHelper _console;

    public Test(ITestOutputHelper console)
    {
        _console = console;
    }

    [Fact]
    public async Task CompareTo()
    {
        DataConnection.TurnTraceSwitchOn();
        DataConnection.WriteTraceLine = (message, displayName, lvl) =>
        {
            _console.WriteLine($"{lvl}|{displayName}|{message}");
        };

        var connectionString = "Host=localhost;Port=5432;Username=postgres;Password=postgres;Database=l2db_tests;Include Error Detail=true";
        var connectionOptions = new LinqToDbConnectionOptionsBuilder()
            .UsePostgreSQL(connectionString)
            .Build<Con>();
        await using var con = new Con(connectionOptions);
        await using var tmpTable = con.CreateTempTable<Entity>("entities");

        var id = Guid.NewGuid();
        var res = await tmpTable.Where(x => x.Id.CompareTo(id) > 0).ToListAsync();
    }

    public class Con : DataConnection
    {
        public Con(LinqToDbConnectionOptions<Con> options) : base(options)
        {
        }

        public ITable<Entity> Entities => GetTable<Entity>();
    }

    public class Entity
    {
        [PrimaryKey, Column("id")]
        public Guid Id { get; set; }
    }
}

```

### Environment details
linq2db version: 3.6.0 and 4.0.0-preview.10
Database Server: PostgreSQL 11.7 on x86_64-pc-linux-musl, compiled by gcc (Alpine 9.2.0) 9.2.0, 64-bit
Operating system: ubuntu 20.04
.NET Framework: 6.0.0

**Comment by MaceWindu** [comment]
`CompareTo` mapping defined only for string. If you want to use this method for other types, you need to define mapping using `Expressions.MapMember` method

**Comment by riberk** [comment]
I wrote this code and it works, but "magic method" `ConvertToCaseCompareTo` is strange
```csharp
    static Test()
    {
        LinqToDB.Linq.Expressions.MapMember((Guid left, Guid right) => left.CompareTo(right), (left, right) => ConvertToCaseCompareTo(left, right));
    }

    [Sql.Function]
    public static int ConvertToCaseCompareTo<T>(T left, T right)
        where T : IComparable<T> => throw new NotSupportedException();
```

This is similar with code for strings from https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Expressions.cs#L548

And it converts to ISqlExpression https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/SqlProvider/BasicSqlOptimizer.cs#L930

Is it safe to rely on this kind of code? Or magic constant `ConvertToCaseCompareTo` may be changed in later versions?

**Comment by MaceWindu** [comment]
Well, I would not recommend to rely on current implementation internals (`ConvertToCaseCompareTo`) as it could change without any prior notice.

I recommend to define conversion explicitly. E.g.
```cs
LinqToDB.Linq.Expressions.MapMember((Guid left, Guid right) => left > right ? 1 : (left == right ? 0 : -1));
```

**Comment by riberk** [comment]
`Guid` does not define comparison operators. 

I try this code
```csharp
LinqToDB.Linq.Expressions.MapMember((Guid left, Guid right) => left.CompareTo(right) > 0, (left, right) => SqlGt(left, right));

[Sql.Expression("({0} > {1})")]
public static bool SqlGt<T>(T left, T right) where T : IComparable<T> => left.CompareTo(right) > 0;
```

but it didn`t work with exception
```
System.InvalidCastException
Unable to cast object of type 'System.Linq.Expressions.LogicalBinaryExpression' to type 'System.Linq.Expressions.NewExpression'.
   at LinqToDB.Expressions.MemberHelper.GetMemberInfo(Expression expr)
   at LinqToDB.Expressions.MemberHelper.GetMemberInfo(LambdaExpression func)
   at LinqToDB.Linq.Expressions.MapMember[T1,T2,TR](Expression`1 memberInfo, Expression`1 expression)
   at Tests.Test..cctor() in Test.cs:line 28
```

I tried using `MapBinary`, but it didn't work too

```csharp
LinqToDB.Linq.Expressions.MapBinary((Guid left, Guid right) => left.CompareTo(right) > 0, (left, right) => SqlGt(left, right));

[Sql.Expression("({0} > {1})")]
public static bool SqlGt<T>(T left, T right) where T : IComparable<T> => left.CompareTo(right) > 0;
```
```
LinqToDB.Linq.LinqException
'x.Id.CompareTo(value(Tests.Test+<>c__DisplayClass5_0).id)' cannot be converted to SQL.
```

What am I doing wrong?

**Comment by MaceWindu** [comment]
First lambda parameter identify member you want to map.
When you set it to `(Guid left, Guid right) => left.CompareTo(right) > 0` you map `operator >`, not `CompareTo`

Proper way should be
```cs
LinqToDB.Linq.Expressions.MapMember((Guid left, Guid right) => left.CompareTo(right), (left, right) => SqlCompare(left, right));

[Sql.Expression("HERE YOUR COMPARISON SQL")]
public static int SqlCompare<T>(T left, T right) where T : IComparable<T> => left.CompareTo(right);
```

**Comment by riberk** [comment]
I want SQL to be generated when using СompareTo, similar to the one I would write with my hands, that is `a.CompareTo(b) > 0 ---> a > b`,
and I absolutely do not understand how to achieve this. If I use my own sql for `CompareTo`, as in the last example, it  degenerates into
`(case when a > b then 1 when a = b then 0 else -1) > 0` , as it happens for strings.
But for strings, not SQL is generated directly, but SqlExpression, which then, apparently, is optimized and turns into `a > b`

Is there any way to do this using CompareTo? I understand that I can just replace the `CompareTo... > 0` call to call a method marked up by Sql.Function attribute, but I'm writing code that should work for both Ef and LinqToDb, so this option doesn't suit me

**Comment by HypeillingerChillinger** [comment]
This is what I did. Don't know if it is as intended by Linq2Db but it works:

```c#
[Sql.Expression("case when {0} > {1} then 1 when {0} = {1} then 0 else -1 end", ServerSideOnly = true)]
public static int GuidCompareTo<T>(this T left, T right)
        where T : IComparable<T>
{
      return left.CompareTo(right);
}
```

```Sql
SELECT 
x.id, 
case when x.id > :guid then 1 when x.id = :guid then 0 else -1 end FROM tschemadefault.bla x ORDER BY x.id"
```
