### ISSUE TITLE
RetryingDataConnection Problem: Connection already open

### ISSUE THREAD

**Issue by streamzyuk** [linq2db/linq2db#3431]
I am trying to implement retry logic for Aws Aurora Mysql.

In Linq2db there  is retyrpolicy already implemented  except there is no way  to pass retrypolicy to DataContext.
So I have extended the DataContext as follows.

 public class RetryingDataContext : DataContext
    {
        protected IRetryPolicy _retryPolicy;
        public RetryingDataContext(IDataProvider dataProvider, string connectionString,IRetryPolicy retryPolicy):base(dataProvider,connectionString)
        {
            _retryPolicy = retryPolicy;
        }

        protected override DataConnection CreateDataConnection()
        {
            return ConnectionString != null
                ? new DataConnection(DataProvider, ConnectionString) { RetryPolicy =_retryPolicy}
                : new DataConnection(ConfigurationString) { RetryPolicy = _retryPolicy};
        }
       
    }

This way I can use retrypolicy for linq expressions. It works as expected but with one problem.

When can not connnect to mysql (I manually stop/restart mysql server) at first retry I get "connection already open" error.

I adjusted the connect time out to different values  as I beleive mysql connector api tries to connect until end of timeout and it is successfull before retrypolicy retries.

Is it a bug? I  checked the source code but I couldnt find a solution.

Did anyone mannged to handle this.

Thanks

**Comment by MaceWindu** [comment]
We should add retry policy to `LinqToDbConnectionOptions`

**Comment by sdanyliv** [comment]
@streamzyuk, try to use global configuration:
```cs
Configuration.RetryPolicy.Factory = dc => new MyRetryPolicy();
```

**Comment by MaceWindu** [comment]
`connection already open` not related to timeouts, it means `Open()` method called on connection twice. I don't know how your retry policy implementation looks, maybe there is something wrong with it

**Comment by streamzyuk** [comment]
Here is my RetryPoliicy


  public class MySqlRetryPolicy : RetryPolicyBase
    {
        


        /// <summary>
        ///   Creates a new instance of <see cref="MySqlRetryPolicy" />.
        /// </summary>
        /// <remarks>
        ///     The default retry limit is 5, which means that the total amount of time spent before failing is 26 seconds plus the random factor.
        /// </remarks>
        public MySqlRetryPolicy()
            : this(Configuration.RetryPolicy.DefaultMaxRetryCount)
        { }

        /// <summary>
        ///     Creates a new instance of <see cref="MySqlRetryPolicy" />.
        /// </summary>
        /// <param name="maxRetryCount"> The maximum number of retry attempts. </param>
        public MySqlRetryPolicy(int maxRetryCount)
            : this(maxRetryCount, Configuration.RetryPolicy.DefaultMaxDelay)
        { }

        /// <summary>
        ///     Creates a new instance of <see cref="MySqlRetryPolicy" />.
        /// </summary>
        /// <param name="maxRetryCount">The maximum number of retry attempts.</param>
        /// <param name="maxRetryDelay">The maximum delay in milliseconds between retries.</param>
        /// <param name="errorNumbersToAdd">Additional SQL error numbers that should be considered transient.</param>
        public MySqlRetryPolicy(
            int maxRetryCount,
            TimeSpan maxRetryDelay)
            : base(maxRetryCount, maxRetryDelay)
        {
            
        }

        protected override bool ShouldRetryOn(Exception exception)
        {

            var mySqlException = exception as MySqlException;

            if (mySqlException == null)
                return false;

            if (mySqlException.IsTransient)
                return true;
            if (exception is TimeoutException)
                return true;

            switch (mySqlException.Number)
            {
                case ((int)MySqlErrorCode.None):
                case ((int)MySqlErrorCode.UnableToConnectToHost):
                case ((int)MySqlErrorCode.AbortingConnection):
                case ((int)MySqlErrorCode.ServerShutdown):
                    return true;
                default:
                    return false;
            };

        }

        private static int ExponentialBase = 2;
        private static double RandomFactor = 1.1;
        private static TimeSpan Coefficient  = TimeSpan.FromSeconds(2);//min 4 sn   
        protected override TimeSpan? GetNextDelay(Exception lastException)
        {
            var currentRetryCount = ExceptionsEncountered.Count - 1;

            if (currentRetryCount < MaxRetryCount)
            {
                var delta =
                    (Math.Pow(ExponentialBase, currentRetryCount) -1 )*
                    (1.0 + Random.NextDouble() * (RandomFactor - 1.0));

                var delay = Math.Min(
                    Coefficient.TotalMilliseconds * delta,
                    MaxRetryDelay.TotalMilliseconds);

                return TimeSpan.FromMilliseconds(delay);
            }

            return null;
        }



    }

**Comment by MaceWindu** [comment]
could you provide stack for error?

**Comment by streamzyuk** [comment]
> could you provide stack for error?

System.InvalidOperationException: The connection is already open.
   at MySql.Data.MySqlClient.Interceptors.ExceptionInterceptor.Throw(Exception exception)
   at MySql.Data.MySqlClient.MySqlConnection.Throw(Exception ex)
   at MySql.Data.MySqlClient.MySqlConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at LinqToDB.Data.RetryPolicy.RetryingDbConnection.<OpenAsync>b__21_0(CancellationToken ct)
   at LinqToDB.Data.RetryPolicy.RetryPolicyBase.<>c__DisplayClass21_0.<<ExecuteAsync>b__0>d.MoveNext()
--- End of stack trace from previous location ---
   at LinqToDB.Data.RetryPolicy.RetryPolicyBase.ExecuteImplementationAsync[TResult](Func`2 operation, CancellationToken cancellationToken)
   at LinqToDB.Data.RetryPolicy.RetryPolicyBase.ExecuteAsync(Func`2 operation, CancellationToken cancellationToken)
   at LinqToDB.Data.RetryPolicy.RetryingDbConnection.OpenAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.EnsureConnectionAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass4_0`1.<<GetFirstOrDefaultElement>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Nop.Services.Media.PictureService.GetPictureBinaryByPictureIdAsync(Int32 pictureId) in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Libraries\Nop.Services\Media\PictureService.cs:line 995
   at Nop.Services.Media.PictureService.LoadPictureBinaryAsync(Picture picture, Boolean fromDb) in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Libraries\Nop.Services\Media\PictureService.cs:line 256
   at Nop.Services.Media.PictureService.LoadPictureBinaryAsync(Picture picture) in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Libraries\Nop.Services\Media\PictureService.cs:line 454
   at Nop.Services.Media.PictureService.GetPictureUrlAsync(Picture picture, Int32 targetSize, Boolean showDefaultPicture, String storeLocation, PictureType defaultPictureType) in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Libraries\Nop.Services\Media\PictureService.cs:line 573
   at Nop.Web.Factories.ShoppingCartModelFactory.<>c__DisplayClass59_0.<<PrepareCartItemPictureModelAsync>b__0>d.MoveNext() in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Presentation\Nop.Web\Factories\ShoppingCartModelFactory.cs:line 1454
--- End of stack trace from previous location ---
   at Nop.Core.Caching.DistributedCacheManager.GetAsync[T](CacheKey key, Func`1 acquire) in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Libraries\Nop.Core\Caching\DistributedCacheManager.cs:line 162
   at Nop.Web.Factories.ShoppingCartModelFactory.PrepareCartItemPictureModelAsync(ShoppingCartItem sci, Int32 pictureSize, Boolean showDefaultPicture, String productName) in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Presentation\Nop.Web\Factories\ShoppingCartModelFactory.cs:line 1447
   at Nop.Web.Factories.ShoppingCartModelFactory.PrepareMiniShoppingCartModelAsync() in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Presentation\Nop.Web\Factories\ShoppingCartModelFactory.cs:line 1074
   at Nop.Web.Components.FlyoutShoppingCartViewComponent.InvokeAsync() in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Presentation\Nop.Web\Components\FlyoutShoppingCart.cs:line 34
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsyncCore(ObjectMethodExecutor executor, ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentInvoker.InvokeAsync(ViewComponentContext context)
   at Microsoft.AspNetCore.Mvc.ViewComponents.DefaultViewComponentHelper.InvokeCoreAsync(ViewComponentDescriptor descriptor, Object arguments)
   at AspNetCore.Views_Shared__Header.ExecuteAsync() in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Presentation\Nop.Web\Views\Shared\_Header.cshtml:line 12
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.RenderPartialCoreAsync(String partialViewName, Object model, ViewDataDictionary viewData, TextWriter writer)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.HtmlHelper.PartialAsync(String partialViewName, Object model, ViewDataDictionary viewData)
   at AspNetCore.Views_Shared__Root.ExecuteAsync() in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Presentation\Nop.Web\Views\Shared\_Root.cshtml:line 10
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageCoreAsync(IRazorPage page, ViewContext context)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderPageAsync(IRazorPage page, ViewContext context, Boolean invokeViewStarts)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderLayoutAsync(ViewContext context, ViewBufferTextWriter bodyWriter)
   at Microsoft.AspNetCore.Mvc.Razor.RazorView.RenderAsync(ViewContext context)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ViewContext viewContext, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewExecutor.ExecuteAsync(ActionContext actionContext, IView view, ViewDataDictionary viewData, ITempDataDictionary tempData, String contentType, Nullable`1 statusCode)
   at Microsoft.AspNetCore.Mvc.ViewFeatures.ViewResultExecutor.ExecuteAsync(ActionContext context, ViewResult result)
   at Microsoft.AspNetCore.Mvc.ViewResult.ExecuteResultAsync(ActionContext context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResultFilterAsync>g__Awaited|29_0[TFilter,TFilterAsync](ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResultExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.ResultNext[TFilter,TFilterAsync](State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeResultFilters>g__Awaited|27_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|24_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|19_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at WebMarkupMin.AspNetCore5.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
   at WebMarkupMin.AspNetCore5.WebMarkupMinMiddleware.ProcessAsync(HttpContext context, Boolean useMinification, Boolean useCompression)
   at WebMarkupMin.AspNetCore5.WebMarkupMinMiddlewareBase.Invoke(HttpContext context)
   at StackExchange.Profiling.MiniProfilerMiddleware.Invoke(HttpContext context) in C:\projects\dotnet\src\MiniProfiler.AspNetCore\MiniProfilerMiddleware.cs:line 104
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Nop.Services.Authentication.AuthenticationMiddleware.InvokeAsync(HttpContext context) in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Libraries\Nop.Services\Authentication\AuthenticationMiddleware.cs:line 94
   at NWebsec.AspNetCore.Middleware.Middleware.CspMiddleware.Invoke(HttpContext context)
   at Nop.Web.Framework.Infrastructure.Extensions.ApplicationBuilderExtensions.<>c.<<UseSecurityHeaders>b__13_3>d.MoveNext() in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Presentation\Nop.Web.Framework\Infrastructure\Extensions\ApplicationBuilderExtensions.cs:line 404
--- End of stack trace from previous location ---
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at NWebsec.AspNetCore.Middleware.Middleware.MiddlewareBase.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Session.SessionMiddleware.Invoke(HttpContext context)
   at Nop.Services.Installation.InstallUrlMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Libraries\Nop.Services\Installation\InstallUrlMiddleware.cs:line 52
   at Nop.Services.Common.KeepAliveMiddleware.InvokeAsync(HttpContext context, IWebHelper webHelper) in C:\Streamzy\StreamzyNopCommerce_4.40.3\src\Libraries\Nop.Services\Common\KeepAliveMiddleware.cs:line 49
   at Microsoft.AspNetCore.ResponseCompression.ResponseCompressionMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.StatusCodePagesMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.HandleException(HttpContext context, ExceptionDispatchInfo edi)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)
   at Microsoft.AspNetCore.Diagnostics.ExceptionHandlerMiddleware.<Invoke>g__Awaited|6_0(ExceptionHandlerMiddleware middleware, HttpContext context, Task task)

**Comment by streamzyuk** [comment]
> @streamzyuk, try to use global configuration:
> 
> ```cs
> LinqToDB.Common.Configuration.RetryPolicy.Factory = dc => new MyRetryPolicy();
> ```

Can you give an example where I should put this. Is it in configure services

**Comment by MaceWindu** [comment]
Try following steps before we will look into it. I see some layers that would be nice to disable/replace first to ensure they are not causing this issue:
- miniprofiler
- try to switch to `MySqlConnector` provider from `MySql.Data` (just replace nuget dependencies - it should be enough)

**Comment by streamzyuk** [comment]
> Hm, checked `RetryingDbConnection` implementation - we actually don't check/close connection before Open/OpenAsync call. Anyway, I would recommend to switch to `MySqlConnector` as you use async and `MySql.Data` does sync-over-async

Thank you.
I am using nopcommerce. I am not sure why they choosed Mysql.Data. Is there any functionality missing in MySqlConnector over MySql.Data.

Can I workaround this bug before new release without recompiling. Also checking if connnection open then opening the connection will not if exception happens after the check. Then retrying will has to check if the connection open before retrying.

So we need a way to check in retrypolicy if the operation if open and then if its still open supperss the exception

**Comment by MaceWindu** [comment]
As far as I know, last missing feature was big decimals support, which was added in recent releases. But I doubt Nop use them anyway. MySqlConnector supperior to MySql.Data in all aspects except maybe lack of `developed by Oracle` badge, which is quite dubious advantage taking into account quality of its code

**Comment by streamzyuk** [comment]
> Regarding workaround. I'm looking at retry policy code and cannot see how issue could be workarounded here as we don't expose connection to user

MaceWindu,
Thank you for your advise on using MySqlConnector. I replaced MySqlData with MySqlConnector. (I  will ask nop team if it has any side effects that I am not aware  of). It works like a charm. And its lightning fast. I am surprised. After connector, it tried everything to get the same exception but I couldn't. I check the source code of MySqlConnector but couldn't see any specific handling on Connection Already Open. I think they handle the connnection issues better than MySql.Data. Whats more their transient error settings include connnection issues which  is a plus.

I will let you know if I get the same error again.

**Comment by streamzyuk** [comment]
> ```cs
> Common.Configuration.RetryPolicy.Factory = dc => new MyRetryPolicy();
> ```

Thank you I figured it out. So I put the above code in Configure services. So globally app wise it started using my retrypolicy in DataContext and DataConnection calls. 
So no need to create a custom RetryingDataContext
Thanks for the info.

 public void Configure(IApplicationBuilder application)
        {
         
           LinqToDB.Common.Configuration.RetryPolicy.Factory = dc => new Nop.Data.DataProviders.LinqToDB.MySqlRetryPolicy(5, System.TimeSpan.FromSeconds(30));
         
        }
