### ISSUE TITLE
DeleteWithOutput for Azure SQL (SqlServer.2017) generates unsupported query

### ISSUE THREAD

**Issue by BobBoba** [linq2db/linq2db#3445]
Hi guys, I found a little problem (which I can bypass).

I have quite trivial code:
```C#
using var scope     = _serviceProvider.CreateScope();
var       dbContext = scope.ServiceProvider.GetRequiredService<MyDbContext>().CreateLinqToDbConnection();
var deleted = await dbContext.GetTable<CachedResult>()
                             .Where(r => r.Expired < DateTime.UtcNow)
                             .DeleteWithOutputAsync(stoppingToken);
```

It seems that it generates SQL query, which is not supported in Azure SQL:
```
--  SqlServer.2017 (asynchronously)
DECLARE @UtcNow DateTime2
SET     @UtcNow = '2022-02-28T15:42:39.9584090'

DELETE [r]
OUTPUT
        *
FROM
        [mytable].[CachedResults] [r]
WHERE
        [r].[Expired] < @UtcNow
16:55:19.818 759860 ERR #  7  LinqToDB.Data.DataConnection:() :: Error
Exception: Microsoft.Data.SqlClient.SqlException
Message  : Incorrect syntax near '*'.
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__188_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
```

I think a star (*) needs to be prefixed with `deleted.` to have a query like:
```SQL
DELETE [r]
OUTPUT
        deleted.*
FROM
        [mytable].[CachedResults] [r]
WHERE
        [r].[Expired] < @UtcNow
```

https://docs.microsoft.com/en-us/sql/t-sql/queries/output-clause-transact-sql?view=azuresqldb-current

I will be much appreciated to any comments. 

### Environment details
linq2db version: 3.6.0
Database Server: Azure SQL (SqlServer.2017)
Database Provider: linq2db.EntityFrameworkCore v6.6.1
Operating system: WIN10
.NET: v6.0

**Comment by MaceWindu** [comment]
@igor-tkachev, there shouldn't be any `*` in select list:
 - it is not compatible with remote context
 - it could return unmapped columns

**Comment by igor-tkachev** [comment]
Can you please show the structure of the CachedResult class?

**Comment by MaceWindu** [comment]
This is what I get for following table definition:
```cs
[Table]
    public class TestTable
    {
        [Column(DataType = DataType.DateTime2)] public DateTime Expired { get; set; }
        [Column] public int ExtraColumn { get; set; }
    }
```
on linq2db 3.6.0 (without linq2db.EntityFrameworkCore  involved, will try to add ef.core)
```sql
DELETE [r]
OUTPUT
	[DELETED].[Expired],
	[DELETED].[ExtraColumn]
FROM
	[#TestTable] [r]
WHERE
	[r].[Expired] < @UtcNow
```

**Comment by MaceWindu** [comment]
Tried same query with `linq2db.EntityFrameworkCore` and got same correct query.

**Comment by MaceWindu** [comment]
Closing for now. Will reopen if you still have an issue with it.
