### ISSUE TITLE
PostGreSql, npgSql 3.0.5

### ISSUE THREAD

**Issue by SteliosKornelakis** [linq2db/linq2db#345]
While opening the dataconnection it throws : 

"Keyword not supported: protocol
Parameter name: keyword".

This occurs with "npgSql 3.0.5", 2.2.7 is working proprly.

`   at Npgsql.NpgsqlConnectionStringBuilder.GetProperty(String keyword)
   at Npgsql.NpgsqlConnectionStringBuilder.set_Item(String keyword, Object value)
   at System.Data.Common.DbConnectionStringBuilder.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnectionStringBuilder..ctor(String connectionString)
   at Npgsql.NpgsqlConnection.set_ConnectionString(String value)
   at Npgsql.NpgsqlConnection..ctor(String connectionString)
   at lambda_method(Closure , String )
   at LinqToDB.DataProvider.DynamicDataProviderBase.CreateConnectionInternal(String connectionString) in i:\linq2db\Source\DataProvider\DynamicDataProviderBase.cs:line 69
   at LinqToDB.DataProvider.DataProviderBase.CreateConnection(String connectionString) in i:\linq2db\Source\DataProvider\DataProviderBase.cs:line 74
   at LinqToDB.Data.DataConnection.get_Connection() in i:\linq2db\Source\Data\DataConnection.cs:line 482
   at LinqToDB.Data.DataConnection.CreateCommand() in i:\linq2db\Source\Data\DataConnection.cs:line 556
   at LinqToDB.Data.DataConnection.get_Command() in i:\linq2db\Source\Data\DataConnection.cs:line 550
   at LinqToDB.DataProvider.DataProviderBase.InitCommand(DataConnection dataConnection, CommandType commandType, String commandText, DataParameter[] parameters) in i:\linq2db\Source\DataProvider\DataProviderBase.cs:line 88
   at LinqToDB.Data.DataConnection.InitCommand(CommandType commandType, String sql, DataParameter[] parameters, List`1 queryHints) in i:\linq2db\Source\Data\DataConnection.cs:line 533
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.ExecuteReader(Object query) in i:\linq2db\Source\Data\DataConnection.Linq.cs:line 261
   at LinqToDB.Linq.Query`1.<RunQuery>d__11.MoveNext() in i:\linq2db\Source\Linq\Query.cs:line 371
   at LinqToDB.Linq.Query`1.<Map>d__6a.MoveNext() in i:\linq2db\Source\Linq\Query.cs:line 1177
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at ConsoleApplication1.Program.Main(String[] args) in C:\Development\TestDBGre\ConsoleApplication1\ConsoleApplication1\Program.cs:line 26`

**Comment by SteliosKornelakis** [comment]
Removing Protocol=3 from the connection string seems to solve the issue.
