### ISSUE TITLE
ExpressionMethod with count on another table

### ISSUE THREAD

**Issue by primozcerar** [linq2db/linq2db#3467]
### Discussed in https://github.com/linq2db/linq2db/discussions/3466

<div type='discussions-op-text'>

<sup>Originally posted by **primozcerar** March 15, 2022</sup>
I'm getting an ArgumentOutOfRangeException with this expression method:

```cs
private static Expression<Func<E_MAILER_MESSAGE_LIST, DataConnection, int>> AttachmentCountExpression()
{
	return (m, dc) => dc.GetTable<E_MAILER_ATACHMENT>().Where(a => a.ID == m.ID).Count();
}
```

This is the call stack:
```
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.SZArrayHelper.get_Item[T](Int32 index)
   at LinqToDB.Linq.Builder.ExpressionBuilder.IsGroupJoinSource(IBuildContext context, MethodCallExpression call)
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass78_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildCalculatedColumns(EntityDescriptor entityDescriptor, Expression expr)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildTableExpression(Boolean buildBlock, Type objectType, Int32[] index)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery(Type tableType, TableContext tableContext, ParameterExpression parentObject)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.IEnumerable.GetEnumerator()
```   
I can't currently provide a sample project to demonstrate this as this is part of large web project and it would require me to create a new project with embedded DB. If you can not replicate it please let me know and I will try to make it.

Using Linq2DB 2.9.3 netstandard 2.0
</div>

**Comment by primozcerar** [comment]
After updating to 2.9.8 it is working. Sorry for the inconvenience.
