### ISSUE TITLE
MySql + Identity: Type DateTimeOffset incorrectly treated as Blob

### ISSUE THREAD

**Issue by GiovanniCmpaner** [linq2db/linq2db#3469]
When using `linq2db.MySql` with `linq2db.Identity` and calling `await _userManager.AccessFailedAsync(user)`, a exception is thrown.

<details>
  <summary>Exception message</summary>

```
MySql.Data.MySqlClient.MySqlException
  HResult=0x80004005
  Message=Incorrect datetime value: '3/15/2022 11:18:22 AM +00:00' for column 'LockoutEnd' at row 1
  Source=MySql.Data
```

</details>

<details>
  <summary>Stack trace</summary>

```
at MySql.Data.MySqlClient.MySqlStream.ReadPacket()
   at MySql.Data.MySqlClient.NativeDriver.GetResult(Int32& affectedRow, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.GetResult(Int32 statementId, Int32& affectedRows, Int64& insertedId)
   at MySql.Data.MySqlClient.Driver.NextResult(Int32 statementId, Boolean force)
   at MySql.Data.MySqlClient.MySqlDataReader.NextResult()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(CommandBehavior behavior)
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
   at MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
   at LinqToDB.Data.DbCommandProcessor.DbCommandProcessorExtensions.ExecuteNonQueryExt(IDbCommand cmd)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass31_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at LinqToDB.LinqExtensions.Update[T](IUpdatable`1 source)
   at LinqToDB.Identity.Extensions.UpdateConcurrent[T,TKey](IDataContext dc, T obj)
   at LinqToDB.Identity.UserStore`7.<>c__DisplayClass50_0.<UpdateAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LinqToDB.Identity.UserStore`7.<UpdateAsync>d__50.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at LinqToDB.Identity.UserStore`7.<UpdateAsync>d__49.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Identity.UserManager`1.<UpdateUserAsync>d__173.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Microsoft.AspNetCore.Identity.UserManager`1.<AccessFailedAsync>d__141.MoveNext()
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Server.AuthenticateController.<Login>d__4.MoveNext() in C:\Users\Giovanni\source\repos\TesteServer\Server\AuthenticateController.cs:line 43

  This exception was originally thrown at this call stack:
    MySql.Data.MySqlClient.MySqlStream.ReadPacket()
    MySql.Data.MySqlClient.NativeDriver.GetResult(ref int, ref long)
    MySql.Data.MySqlClient.Driver.GetResult(int, ref int, ref long)
    MySql.Data.MySqlClient.Driver.NextResult(int, bool)
    MySql.Data.MySqlClient.MySqlDataReader.NextResult()
    MySql.Data.MySqlClient.MySqlCommand.ExecuteReader(System.Data.CommandBehavior)
    MySql.Data.MySqlClient.MySqlCommand.ExecuteReader()
    MySql.Data.MySqlClient.MySqlCommand.ExecuteNonQuery()
    LinqToDB.Data.DbCommandProcessor.DbCommandProcessorExtensions.ExecuteNonQueryExt(System.Data.IDbCommand)
    LinqToDB.Data.DataConnection.ExecuteNonQuery(System.Data.IDbCommand)
    ...
    [Call Stack Truncated]
```

</details>

With `DataConnection.TurnTraceSwitchOn()`, the generated command is the following.

<details>
  <summary>SQL Command</summary>

```sql
DECLARE @ConcurrencyStamp VarChar(36) -- String
SET     @ConcurrencyStamp = 'ab450a1b-3e82-47b3-8597-1838fcd3abe1'
DECLARE @AccessFailedCount Int32
SET     @AccessFailedCount = 0
DECLARE @LockoutEnabled UByte -- Boolean
SET     @LockoutEnabled = 1
DECLARE @LockoutEnd Blob -- DateTimeOffset
SET     @LockoutEnd = '2022-03-15T11:18:22.3349759+00:00'
DECLARE @TwoFactorEnabled UByte -- Boolean
SET     @TwoFactorEnabled = 0
DECLARE @PhoneNumberConfirmed UByte -- Boolean
SET     @PhoneNumberConfirmed = 0
DECLARE @PhoneNumber VarChar -- String
SET     @PhoneNumber = NULL
DECLARE @SecurityStamp VarChar(32) -- String
SET     @SecurityStamp = 'YFTZADARNBVACKGXBHHLNNIG6T5AYEV3'
DECLARE @PasswordHash VarChar(84) -- String
SET     @PasswordHash = 'AQAAAAEAACcQAAAAEENQ1TxRpV2JAhqjGz4N+crL/CXJxZlXKF9xL9rzrhbg9/AQGhQInrIAEydQr6vTjA=='
DECLARE @EmailConfirmed UByte -- Boolean
SET     @EmailConfirmed = 1
DECLARE @NormalizedEmail VarChar(18) -- String
SET     @NormalizedEmail = 'TESTE@TESTE.COM.BR'
DECLARE @Email VarChar(18) -- String
SET     @Email = 'teste@teste.com.br'
DECLARE @NormalizedUserName VarChar(5) -- String
SET     @NormalizedUserName = 'TESTE'
DECLARE @UserName VarChar(5) -- String
SET     @UserName = 'teste'
DECLARE @Id VarChar(36) -- String
SET     @Id = '5471ea64-ac98-4968-9527-f7d1a132ce6e'
DECLARE @ConcurrencyStamp_1 VarChar(36) -- String
SET     @ConcurrencyStamp_1 = 'bc6f4d96-1fcb-49a4-b315-fc985cc8ed44'

UPDATE
        `IdentityUser` `_`
SET
        `_`.`ConcurrencyStamp` = @ConcurrencyStamp,
        `_`.`AccessFailedCount` = @AccessFailedCount,
        `_`.`LockoutEnabled` = @LockoutEnabled,
        `_`.`LockoutEnd` = @LockoutEnd,
        `_`.`TwoFactorEnabled` = @TwoFactorEnabled,
        `_`.`PhoneNumberConfirmed` = @PhoneNumberConfirmed,
        `_`.`PhoneNumber` = @PhoneNumber,
        `_`.`SecurityStamp` = @SecurityStamp,
        `_`.`PasswordHash` = @PasswordHash,
        `_`.`EmailConfirmed` = @EmailConfirmed,
        `_`.`NormalizedEmail` = @NormalizedEmail,
        `_`.`Email` = @Email,
        `_`.`NormalizedUserName` = @NormalizedUserName,
        `_`.`UserName` = @UserName
WHERE
        `_`.`Id` = @Id AND `_`.`ConcurrencyStamp` = @ConcurrencyStamp_1
```

</details>

As you can see `LockoutEnd` is being incorrectly treated as `Blob`.
I've tried modifying the `MappingSchema`, without success.
How can I solve this problem?

### Steps to reproduce

<details>
  <summary>Program.cs</summary>

```c#
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.DataProvider.MySql;
using LinqToDB.Identity;
using LinqToDB.Mapping;
using LinqToDB.SqlQuery;
using Microsoft.AspNetCore.Authentication.JwtBearer;
using Microsoft.AspNetCore.Identity;
using Microsoft.IdentityModel.Tokens;
using Server.Models;
using System.Globalization;
using System.Text;

CultureInfo.CurrentCulture = new CultureInfo("en-US");
CultureInfo.DefaultThreadCurrentCulture = new CultureInfo("en-US");

var builder = WebApplication.CreateBuilder(args);

var teste = new SqlDataType(DataType.DateTimeOffset, typeof(DateTimeOffset));

LinqToDB.DataProvider.MySql.MySqlMappingSchema.Default.SetDataType(typeof(DateTimeOffset), teste);
LinqToDB.DataProvider.MySql.MySqlMappingSchema.MySqlOfficialMappingSchema.Default.SetDataType(typeof(DateTimeOffset), teste);
LinqToDB.DataProvider.MySql.MySqlMappingSchema.MySqlConnectorMappingSchema.Default.SetDataType(typeof(DateTimeOffset), teste);

DataConnection.AddConfiguration("Default", builder.Configuration["Data:ConnectionString"], new MySqlDataProvider("Default"));
DataConnection.DefaultConfiguration = "Default";
DataConnection.TurnTraceSwitchOn();
DataConnection.WriteTraceLine = (message, displayName, level) => { Console.WriteLine($"{message} {displayName}"); };

builder.Services.AddControllers();
builder.Services.AddIdentity<LinqToDB.Identity.IdentityUser, LinqToDB.Identity.IdentityRole>(options =>
{
    options.User.RequireUniqueEmail = true;
    options.SignIn.RequireConfirmedEmail = true;
})
.AddLinqToDBStores(new DefaultConnectionFactory())
.AddDefaultTokenProviders();

builder.Services.AddAuthentication(options =>
{
    options.DefaultAuthenticateScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultChallengeScheme = JwtBearerDefaults.AuthenticationScheme;
    options.DefaultScheme = JwtBearerDefaults.AuthenticationScheme;
})
.AddJwtBearer(options =>
{
    options.RequireHttpsMetadata = true;
    options.SaveToken = true;
    options.TokenValidationParameters = new TokenValidationParameters
    {
        ValidateIssuer = true,
        ValidIssuer = builder.Configuration["Jwt:ValidIssuer"],

        ValidateAudience = true,
        ValidAudience = builder.Configuration["Jwt:ValidAudience"],

        ValidateIssuerSigningKey = true,
        IssuerSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(builder.Configuration["Jwt:Secret"]))
    };
});

var app = builder.Build();

app.UseStaticFiles();
app.UseHttpsRedirection();
app.UseAuthentication();
app.UseAuthorization();
app.MapControllers();

using (var db = new AppDataConnection())
{
    await db.CreateTableAsync<LinqToDB.Identity.IdentityUser>(tableOptions: TableOptions.CreateIfNotExists);
    await db.CreateTableAsync<LinqToDB.Identity.IdentityRole>(tableOptions: TableOptions.CreateIfNotExists);
    await db.CreateTableAsync<LinqToDB.Identity.IdentityUserClaim<string>>(tableOptions: TableOptions.CreateIfNotExists);
    await db.CreateTableAsync<LinqToDB.Identity.IdentityRoleClaim<string>>(tableOptions: TableOptions.CreateIfNotExists);
    await db.CreateTableAsync<LinqToDB.Identity.IdentityUserLogin<string>>(tableOptions: TableOptions.CreateIfNotExists);
    await db.CreateTableAsync<LinqToDB.Identity.IdentityUserRole<string>>(tableOptions: TableOptions.CreateIfNotExists);
    await db.CreateTableAsync<LinqToDB.Identity.IdentityUserToken<string>>(tableOptions: TableOptions.CreateIfNotExists);
}

app.Run();
```

</details>

<details>
  <summary>appsettings.json</summary>

```json
{
  "Logging": {
    "LogLevel": {
      "Default": "Information",
      "Microsoft.AspNetCore": "Warning"
    }
  },
  "AllowedHosts": "localhost",
  "Data": {
    "ConnectionString": "Server=localhost;Database=teste;User=teste;Password=teste;"
  },
  "Jwt": {
    "Secret": "Yh2k7QSu4l8CZg5p6X3Pna9L0Miy4D3Bvt0JVr87UcOj69Kqw5R2Nmf4FWs03Hdz",
    "ValidIssuer": "JWTAuthenticationServer",
    "ValidAudience": "JWTServicePostmanClient"
  }
}

```

</details>

<details>
  <summary>AuthenticateController.cs</summary>

```c#
using Microsoft.AspNetCore.Authorization;
using Microsoft.AspNetCore.Identity;
using Microsoft.AspNetCore.Mvc;
using Microsoft.IdentityModel.Tokens;
using Server.Models;
using System.IdentityModel.Tokens.Jwt;
using System.Security.Claims;
using System.Text;

namespace Server
{
    [Route("api/[controller]")]
    [ApiController]
    public class AuthenticateController : ControllerBase
    {
        private readonly UserManager<LinqToDB.Identity.IdentityUser> _userManager;
        private readonly RoleManager<LinqToDB.Identity.IdentityRole> _roleManager;
        private readonly IConfiguration _configuration;

        public AuthenticateController(
            UserManager<LinqToDB.Identity.IdentityUser> userManager,
            RoleManager<LinqToDB.Identity.IdentityRole> roleManager,
            IConfiguration configuration)
        {
            _userManager = userManager;
            _roleManager = roleManager;
            _configuration = configuration;
        }

        [HttpPost]
        [Route("login")]
        public async Task<IActionResult> Login([FromBody] LoginModel model)
        {
            var user = await _userManager.FindByNameAsync(model.Username);
            if(user == null)
            {
                return Unauthorized("User or password mismatch");
            }

            var match = await _userManager.CheckPasswordAsync(user, model.Password);
            if(!match)
            {
                await _userManager.AccessFailedAsync(user);
                return Unauthorized("User or password mismatch");
            }

            var confirmed = await _userManager.IsEmailConfirmedAsync(user);
            if (!confirmed)
            {
                return Unauthorized("Email not confirmed");
            }

            var lockedOut = await _userManager.IsLockedOutAsync(user);
            if (lockedOut)
            {
                return Unauthorized("User locked out");
            }

            await _userManager.ResetAccessFailedCountAsync(user);

            var authClaims = new List<Claim>
            {
                new Claim(ClaimTypes.Name, user.UserName),
                new Claim(ClaimTypes.NameIdentifier, user.Id),
                new Claim(JwtRegisteredClaimNames.Jti, Guid.NewGuid().ToString()),
            };

            var userRoles = await _userManager.GetRolesAsync(user);
            foreach (var userRole in userRoles)
            {
                authClaims.Add(new Claim(ClaimTypes.Role, userRole));
            }

            var token = GetToken(authClaims);

            return Ok(new
            {
                token = new JwtSecurityTokenHandler().WriteToken(token),
                expiration = token.ValidTo
            });
        }

        [HttpPost]
        [Route("register")]
        public async Task<IActionResult> Register([FromBody] RegisterModel model)
        {
            var userExists = await _userManager.FindByNameAsync(model.Username);
            if (userExists != null)
                return BadRequest("User already exists!");

            LinqToDB.Identity.IdentityUser user = new()
            {
                Email = model.Email,
                SecurityStamp = Guid.NewGuid().ToString(),
                UserName = model.Username,
                EmailConfirmed = false
            };

            var result = await _userManager.CreateAsync(user, model.Password);
            if (!result.Succeeded)
                return StatusCode(StatusCodes.Status500InternalServerError, "User creation failed! Please check user details and try again.");

            return Ok("User created successfully!");
        }

        [HttpPost]
        [Route("register-admin")]
        public async Task<IActionResult> RegisterAdmin([FromBody] RegisterModel model)
        {
            var userExists = await _userManager.FindByNameAsync(model.Username);
            if (userExists != null)
                return BadRequest("User already exists!");

            LinqToDB.Identity.IdentityUser user = new()
            {
                Email = model.Email,
                SecurityStamp = Guid.NewGuid().ToString(),
                UserName = model.Username
            };
            var result = await _userManager.CreateAsync(user, model.Password);
            if (!result.Succeeded)
                return StatusCode(StatusCodes.Status500InternalServerError, "User creation failed! Please check user details and try again.");

            if (!await _roleManager.RoleExistsAsync(UserRoles.Admin))
                await _roleManager.CreateAsync(new LinqToDB.Identity.IdentityRole(UserRoles.Admin));

            if (!await _roleManager.RoleExistsAsync(UserRoles.User))
                await _roleManager.CreateAsync(new LinqToDB.Identity.IdentityRole(UserRoles.User));

            await _userManager.AddToRoleAsync(user, UserRoles.Admin);
            await _userManager.AddToRoleAsync(user, UserRoles.User);

            return Ok("User created successfully!");
        }

        [HttpGet]
        [Route("teste")]
        [Authorize]
        public async Task<IActionResult> Teste()
        {
            var user = await _userManager.GetUserAsync(HttpContext.User);
            return Ok("Teste");
        }

        private JwtSecurityToken GetToken(List<Claim> authClaims)
        {
            var authSigningKey = new SymmetricSecurityKey(Encoding.UTF8.GetBytes(_configuration["JWT:Secret"]));

            var token = new JwtSecurityToken(
                issuer: _configuration["JWT:ValidIssuer"],
                audience: _configuration["JWT:ValidAudience"],
                expires: DateTime.Now.AddHours(3),
                claims: authClaims,
                signingCredentials: new SigningCredentials(authSigningKey, SecurityAlgorithms.HmacSha256)
            );

            return token;
        }
    }
}
```

</details>

<details>
  <summary>AppDataConnection.cs</summary>

```c#
using LinqToDB.Data;
using LinqToDB.Identity;
using LinqToDB.Mapping;

namespace Server.Models
{
    public class AppDataConnection : IdentityDataConnection<IdentityUser>
    {
    }
}
```

</details>

<details>
  <summary>LoginModel.cs</summary>

```c#
using System.ComponentModel.DataAnnotations;

namespace Server.Models
{
    public class LoginModel
    {
        [Required(ErrorMessage = "User Name is required")]
        public string? Username { get; set; }

        [Required(ErrorMessage = "Password is required")]
        public string? Password { get; set; }
    }
}
```

</details>

<details>
  <summary>RegisterModel.cs</summary>

```c#
using System.ComponentModel.DataAnnotations;

namespace Server.Models
{
    public class RegisterModel
    {
        [Required(ErrorMessage = "User Name is required")]
        public string? Username { get; set; }

        [EmailAddress]
        [Required(ErrorMessage = "Email is required")]
        public string? Email { get; set; }

        [Required(ErrorMessage = "Password is required")]
        public string? Password { get; set; }
    }
}
```

</details>

<details>
  <summary>UserRoles.cs</summary>

```c#
namespace Server.Models
{
    public static class UserRoles
    {
        public const string Admin = "Admin";
        public const string User = "User";
    }
}
```

</details>

### Environment details
linq2db version: 3.6.0
linq2db.Identity version: 3.3.0
Database Server: MySQL 8
Database Provider: MySQL
Operating system: Windows 11
.NET Framework: .NET 6

**Comment by GiovanniCmpaner** [comment]
Adding the `linq2db.MySqlConnector` package and changing from:
`DataConnection.AddConfiguration("Default", builder.Configuration["Data:ConnectionString"], new MySqlDataProvider("Default"));`
to:
`DataConnection.AddOrSetConfiguration("Default", builder.Configuration["Data:ConnectionString"], LinqToDB.ProviderName.MySqlConnector);`
the new generated command is:

<details>
    <summary>SQL Command</summary>

```sql
DECLARE @ConcurrencyStamp VarChar(36) -- String
SET     @ConcurrencyStamp = '89b97df9-c0d1-4232-99bb-9cbca91dc9b1'
DECLARE @AccessFailedCount Int32
SET     @AccessFailedCount = 3
DECLARE @LockoutEnabled Bool -- Boolean
SET     @LockoutEnabled = 1
DECLARE @LockoutEnd Datetime -- DateTimeOffset
SET     @LockoutEnd = NULL
DECLARE @TwoFactorEnabled Bool -- Boolean
SET     @TwoFactorEnabled = 0
DECLARE @PhoneNumberConfirmed Bool -- Boolean
SET     @PhoneNumberConfirmed = 0
DECLARE @PhoneNumber VarChar -- String
SET     @PhoneNumber = NULL
DECLARE @SecurityStamp VarChar(32) -- String
SET     @SecurityStamp = 'BGHUMAZKPXGA4YBUH26REIFO54JP35YC'
DECLARE @PasswordHash VarChar(84) -- String
SET     @PasswordHash = 'AQAAAAEAACcQAAAAEA5xpgBZBi/5B3UtboEl+suZsPkPsIOBifdnEbWh5zFf3N7RnO+MbksX2HPvENy46w=='
DECLARE @EmailConfirmed Bool -- Boolean
SET     @EmailConfirmed = 0
DECLARE @NormalizedEmail VarChar(18) -- String
SET     @NormalizedEmail = 'TESTE@TESTE.COM.BR'
DECLARE @Email VarChar(18) -- String
SET     @Email = 'teste@teste.com.br'
DECLARE @NormalizedUserName VarChar(5) -- String
SET     @NormalizedUserName = 'TESTE'
DECLARE @UserName VarChar(5) -- String
SET     @UserName = 'teste'
DECLARE @Id VarChar(36) -- String
SET     @Id = 'f916555b-85df-4c86-b037-d578cef53754'
DECLARE @ConcurrencyStamp_1 VarChar(36) -- String
SET     @ConcurrencyStamp_1 = '01b7b12f-1f49-4466-9e9e-b0dd2e98b153'

UPDATE
        `IdentityUser` `_`
SET
        `_`.`ConcurrencyStamp` = @ConcurrencyStamp,
        `_`.`AccessFailedCount` = @AccessFailedCount,
        `_`.`LockoutEnabled` = @LockoutEnabled,
        `_`.`LockoutEnd` = @LockoutEnd,
        `_`.`TwoFactorEnabled` = @TwoFactorEnabled,
        `_`.`PhoneNumberConfirmed` = @PhoneNumberConfirmed,
        `_`.`PhoneNumber` = @PhoneNumber,
        `_`.`SecurityStamp` = @SecurityStamp,
        `_`.`PasswordHash` = @PasswordHash,
        `_`.`EmailConfirmed` = @EmailConfirmed,
        `_`.`NormalizedEmail` = @NormalizedEmail,
        `_`.`Email` = @Email,
        `_`.`NormalizedUserName` = @NormalizedUserName,
        `_`.`UserName` = @UserName
WHERE
        `_`.`Id` = @Id AND `_`.`ConcurrencyStamp` = @ConcurrencyStamp_1
```

</details>

and the problem is solved.
Thanks!
