### ISSUE TITLE
ExpressionMethod with count on another table in linq2db v3.6

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3472]
### Discussed in https://github.com/linq2db/linq2db/discussions/3471

<div type='discussions-op-text'>

<sup>Originally posted by **primozcerar** March 16, 2022</sup>
After updating my project from 2.9.8 to 3.6.0 this has stopped working again with a different error. I am not sure if this problem existed already in 3.0.0 since I upgraded from 2.9.8.

```cs
private static Expression<Func<E_MAILER_MESSAGE_LIST, DataConnection, int>> AttachmentCountExpression()
{
    return (m, dc) => dc.GetTable<E_MAILER_ATACHMENT_BASE>().Where(a => a.ID == m.ID).Count();
}
```

The error I get is:
`LinqToDB.Linq.LinqException: ''Convert(dctx).GetTable().Where(a => (a.ID == VascoWebLib.Core.Entity.E_MAILER_MESSAGE_LIST.ID)).Count()' cannot be converted to SQL.'
`
and the call stack:

```
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSql(IBuildContext context, Expression expression, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__90_0(ValueTuple`4 context, Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildCalculatedColumns(EntityDescriptor entityDescriptor, Expression expr)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildTableExpression(Boolean buildBlock, Type objectType, Tuple`2[] index)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery(Type tableType, TableContext tableContext, ParameterExpression parentObject)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.IEnumerable.GetEnumerator()
```

Do I need to do something different in 3.0 or is this a bug?</div>

**Comment by MaceWindu** [comment]
For now I see two items that could differ between test and your setup:
- `IDataContext` vs `DataConnection` parameter
- `IsColumn=true` in test and ? in your mappings

**Comment by primozcerar** [comment]
Mapping:
```cs
[ExpressionMethod(nameof(AttachmentCountExpression), IsColumn = true), NotNull, DisplayName("Št. priponk")] 
public int AttCount { get; set; }
```
I tested 3.0.1 and it works there. I will try with 3.6.0 and IDataContext as parameter. The query is just a db.GetTable<T>() with OrderBy

**Comment by primozcerar** [comment]
@MaceWindu  Changing the input parameter from DataConnection to IDataContext fixes the issue. Thank you very much.
