### ISSUE TITLE
Sql.Row doesn't work with server-side functions

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3491]
Sorry to bother, but this is not supported yet:
```c#
await Events.Where(x => x.Id == key)
            .Set(d => Sql.Row(d.Title, d.SearchVector),
                t => (from x in Events
                    where t.Id == x.Id
                    select Sql.Row(t.Title, EF
                        .Functions
                        .ToTsVector("test")
                    )).Single())
            .UpdateAsync();
```

model:
```c#
public class Event
{
    [LinqToDB.Mapping.PrimaryKey] public Guid Id { get; set; }
    public string Title { get; set; } = "";
    public NpgsqlTsVector? SearchVector { get; set; } = null;
}
```

```c#
System.InvalidOperationException: The 'ToTsVector' method is not supported because the query has switched to client-evaluation. This usually happens when the arguments to the method cannot be translated to server. Rewrite the query to avoid client evaluation of arguments so that method can be translated to server.
         at Microsoft.EntityFrameworkCore.NpgsqlFullTextSearchDbFunctionsExtensions.ToTsVector(DbFunctions _, String document)
         at lambda_method215(Closure , Expression , IDataContext , Object[] )
         at LinqToDB.Linq.QueryRunner.SetParameters(Query query, Expression expression, IDataContext parametersContext, Object[] parameters, Int32 queryNumber, SqlParameterValues parameterValues)
         at LinqToDB.Linq.QueryRunnerBase.SetCommand(Boolean forGetSqlText)
         at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken)
         at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
         at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
         at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
         at LinqToDB.LinqExtensions.UpdateAsync[T](IUpdatable`1 source, CancellationToken token)
```

_Originally posted by @sep2 in https://github.com/linq2db/linq2db/issues/3321#issuecomment-1092875003_

**Comment by MaceWindu** [comment]
@sdanyliv I see EF.Core on top of stack. COuld it be EF.Core or EF.Core integration issue?

**Comment by MaceWindu** [comment]
@sep2 any reason to use ROW syntax for this query?

**Comment by sep2** [comment]
@MaceWindu That maybe the cause! I use the functions from https://www.npgsql.org/efcore/mapping/full-text-search.html#operation-translation, did not notice the EF namespace, hoping it would just work (but it didn't).

I also tried the following with no luck.
```C#
await Events.Where(x => x.Id == key)
            .Set(d => d.SearchVector,
                t => (from x in Events
                    where t.Id == x.Id
                    select EF
                        .Functions
                        .ToTsVector("test")
                    ).Single())
            .UpdateAsync();
```

Could you point me how to do server-side functions correctly?

**Comment by MaceWindu** [comment]
If I correctly understand it, you want to update SearchVector column for record with Id=key?

```cs
// variant 1: using Set
await Event
    .Where(x => x.Id == key)
    .Set(x => x.SearchVector, x => EF.Functions.ToTsVector("test") })
    .UpdateAsync();

// variant 2 : using init expression
await Event
    .Where(x => x.Id == key)
    .Update(x => new Event(){ SearchVector EF.Functions.ToTsVector("test") })
    .UpdateAsync();
```


also there are multiple ways to describe UPDATE FROM queries [here](https://github.com/linq2db/linq2db/blob/master/Tests/Linq/Update/InsertIntoTests.cs), but your query doesn't look like one of those.

**Comment by sep2** [comment]
I tried these approaches also:
```c#
    public async Task<int> UpdateEventSearchIndex(Guid key)
    {
        return await Events
            .Where(x => x.Id == key)
            .UpdateAsync(x => new Event { SearchVector = EF.Functions.ToTsVector("test") });
    }
    
    public async Task<int> UpdateEventSearchIndex2(Guid key)
    {
        return await Events
            .Where(x => x.Id == key)
            .Set(x => x.SearchVector, x => EF.Functions.ToTsVector("test"))
            .UpdateAsync();
    }
```

The error is same:
```C#
      System.InvalidOperationException: The 'ToTsVector' method is not supported because the query has switched to client-evaluation. This usually happens when the arguments to the method cannot be translated to server. Rewrite the query to avoid client evaluation of arguments so that method can be translated to server.
         at Microsoft.EntityFrameworkCore.NpgsqlFullTextSearchDbFunctionsExtensions.ToTsVector(DbFunctions _, String document)
         at lambda_method207(Closure , Expression , IDataContext , Object[] )
         at LinqToDB.Linq.QueryRunner.SetParameters(Query query, Expression expression, IDataContext parametersContext, Object[] parameters, Int32 queryNumber, SqlParameterValues parameterValues)
         at LinqToDB.Linq.QueryRunnerBase.SetCommand(Boolean forGetSqlText)
         at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken)
         at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
         at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
         at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
         at LinqToDB.LinqExtensions.UpdateAsync[T](IQueryable`1 source, Expression`1 setter, CancellationToken token)
```

**Comment by MaceWindu** [comment]
I see, I don't know wether we support EF.Core extensions (@sdanyliv will know it better), but for `to_tsquery` function you can just define and use linq2db extension:

```cs
// not sure which type you use for SearchVector, so set return type to string
[Sql.Function("to_tsquery", ServerSideOnly=true)]
public static string ToTsQuery(string query) => throw new InvalidOperationException();
```

**Comment by sep2** [comment]
@MaceWindu It worked! Do you have an example on how to do an operator mapping like this `tsquery1 || tsquery2`?

**Comment by sep2** [comment]
Thank you! This should worth a chapter in the documentation.

Final question, when I try to do something like this:

```c#
[Sql.Function("setweight", ServerSideOnly=true)]
public static NpgsqlTsVector SetWeight(NpgsqlTsVector vector, NpgsqlTsVector.Lexeme.Weight weight) => throw new InvalidOperationException();
```

and use:
```c#
Linq2DbExt.SetWeight(Linq2DbExt.ToTsVector("test"), NpgsqlTsVector.Lexeme.Weight.A)
```

This could not work because `NpgsqlTsVector.Lexeme.Weight.A` is a number enum, but `setweight` requires a single char as input. The workaround is

```c#
[Sql.Function("setweight", ServerSideOnly=true)]
public static NpgsqlTsVector SetWeight(NpgsqlTsVector vector, char weight) => throw new InvalidOperationException();
```

and use:
```c#
Linq2DbExt.SetWeight(Linq2DbExt.ToTsVector("test"), 'A')
```

but it is not optimal, do you have any suggestion on that?

**Comment by sep2** [comment]
never mind, I resolved this by defining a custom weight enum using char as the representation.

**Comment by jods4** [comment]
Just to spell it out clearly in case anyone else has similar issues:

Simple expressions can be evaluated anywhere, but some expressions can only be evaluated server-side (i.e. SQL) and some can only be evaluated client-side (i.e. .NET).

`Sql.Row` is an example of a server-side feature that linq2db can only translate to SQL and never evaluates in C#, esp. in the UPDATE case here. 

When linq2db doesn't know how to translate a complex function to SQL, such as `ToTsVector` here, it just evaluates it in .NET.

But obviously you can't mix-and-match both worlds. Putting .net code inside SQL is not possible, so nesting `ToTsVector` inside `Row` can't be executed by linq2db. As @MaceWindu pointed out the solution is to teach linq2db how to translate the client-side code into SQL, e.g. with a custom `[Expression]` function.

Happy to see people other than me having uses for `Sql.Row` just one day after release :)

**Comment by MaceWindu** [comment]
Closing as it looks like incorrect use of EF.Core functions with linq2db context.
To handle such functions, `Linq To DB` context should be created using integration API.
Following code works fine:

```cs
// create linq2db context from efcore context
// this way we will be aware of ef.core mappings
using var db = ctx.CreateLinqToDBContext();

db
		.Event
		.Where(x => x.Id == 1)
		.Set(
			d => Sql.Row(d.Title, d.SearchVector),
			t => (from x in db.Event
				  where t.Id == x.Id
				  select Sql.Row(t.Title, EF.Functions.ToTsVector("test")))
				  .Single())
	.Update();
```

This one will fail:

```cs
// linq2db knows nothing about efcore by default
using var db = new DataConnection(...);

db
		.Event
		.Where(x => x.Id == 1)
		.Set(
			d => Sql.Row(d.Title, d.SearchVector),
			t => (from x in db.Event
				  where t.Id == x.Id
				  select Sql.Row(t.Title, EF.Functions.ToTsVector("test")))
				  .Single())
	.Update();
```
