### ISSUE TITLE
Invalid SQL generated when using Value on nullable property in JOIN statement

### ISSUE THREAD

**Issue by Feroks** [linq2db/linq2db#3506]
Invalid SQL is generated when `.Value` is used on nullable property in JOIN statement.

```
Exception message: Incorrect syntax near '*'.
Stack trace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in C:\Users\extern_mpo\source\repos\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 1419
   at LinqToDB.Data.DataConnection.ExecuteDataReader(CommandBehavior commandBehavior) in C:\Users\extern_mpo\source\repos\linq2db\Source\LinqToDB\Data\DataConnection.cs:line 1459
```

### Steps to reproduce
I do not know when it got broken, but it used to work on 3.1.6.

```c#
var cats = new[]
{
	new { OwnerId = (int?)1 }
};

var owners = new[]
{
	new { Id = 1 }
};

using (var db = GetDataContext(context))
{
	var catsTable = db.CreateTempTable(cats, tableName: "#catsTable"); 
	var ownerTable = db.CreateTempTable(owners, tableName: "#ownersTable");

	var result = catsTable
		.InnerJoin(
			ownerTable,
			(cat, owner) =>
				cat.OwnerId.HasValue
				&&
				// Using .Value generates invalid SQL
				cat.OwnerId.Value == owner.Id,
			(cat, owner) => cat)
		.Count();

	Assert.AreEqual(1, result);
}
```

```sql
SELECT
	Count(*)
FROM
	[#catsTable] [cat]
		INNER JOIN [#ownersTable] [owner_1] ON [cat].[OwnerId] IS NOT NULL AND [cat].* = [owner_1].[Id]
```

### Environment details
linq2db version: 3.7.0
Database Server: SQL Server
Database Provider: SQL Server 2012
Operating system: Windows 10
.NET Framework: 4.8

**Comment by MaceWindu** [comment]
Thanks, fix will be available in next release
