### ISSUE TITLE
Linq to Access, only 25 times, must throw exception.

### ISSUE THREAD

**Issue by animitta** [linq2db/linq2db#3608]
```csharp
public async Task<PageData<PlanEvaluation>> GetPlanEvaluationAsync()
{
    var connectionString = @"Driver={Microsoft Access Driver (*.mdb, *.accdb)};DBQ=" + $"{path};PWD={password}";
    using context = new DataContext(ProviderName.AccessOdbc, connectionString);
    var table = context.GetTable<PlanEvaluation>();
    var total = await table.CountAsync();
    var items = await table.OrderByDescending(item => item.Id).Skip(0).Take(30).ToListAsync();
    return new PageData<PlanEvaluation>(total, items);
}
```
```log
[Error] [Ibms.Collector.ControlExecutor] 数据库访问失败:"ERROR [08004] [Microsoft][ODBC Microsoft Access Driver] 客户端的工作过多。\r\nERROR [IM006] [Microsoft][ODBC 驱动程序管理器] 驱动程序的 SQLSetConnectAttr 失败"
System.Data.Odbc.OdbcException (0x80131937): ERROR [08004] [Microsoft][ODBC Microsoft Access Driver] 客户端的工作过多。
ERROR [IM006] [Microsoft][ODBC 驱动程序管理器] 驱动程序的 SQLSetConnectAttr 失败
   at System.Data.Odbc.OdbcConnectionHandle..ctor(OdbcConnection connection, OdbcConnectionString constr, OdbcEnvironmentHandle environmentHandle)
   at System.Data.Odbc.OdbcConnectionOpen..ctor(OdbcConnection outerConnection, OdbcConnectionString connectionOptions)
   at System.Data.Odbc.OdbcConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.Odbc.OdbcConnection.Open()
   at System.Data.Common.DbConnection.OpenAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.EnsureConnectionAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
  ```

**Comment by viceroypenguin** [comment]
Based on the error message, it sounds like you have too many connections open. For this particular unit of work, I would suggest using the `DataConnection` instead of the `DataContext`, and I would make sure you don't have too many threads attempting to access the file at the same time.

**Comment by animitta** [comment]
@viceroypenguin I call it almost every 10 minutes, I want to close the connection completely after call this method, until I call the method again. Or disable internal connection pooling?

**Comment by viceroypenguin** [comment]
In this context, the `DataContext` may actually be creating problems, because it is trying to create a separate connection for each query. Give `LinqToDB.Data.DataConnection` a try, if you don't mind? The API surface should be very similar between the two, but the behavior should work better for you.

**Comment by animitta** [comment]
@viceroypenguin  Ok, I'll give it a try.

**Comment by animitta** [comment]
@viceroypenguin Many thingks! Everything is working fine now.

**Comment by viceroypenguin** [comment]
How many functions do you have that access this database file? This could be a timing/multithreading issue, maybe?

**Comment by sdanyliv** [comment]
Show your code which executes `GetPlanEvaluationAsync`.

**Comment by animitta** [comment]
Could it be a Access DB file or ODBC problem? which is a database file provided by a third party.the operating system currently testing is the newest Windows 11 Professional.

**Comment by animitta** [comment]
@sdanyliv [Test Repository](https://github.com/animitta/AccessTester)

**Comment by animitta** [comment]
This problem is reproducible! I provided the original code and Access database file in before Repository.

**Comment by viceroypenguin** [comment]
Thank you @animitta  - we'll take a look!

**Comment by sdanyliv** [comment]
Very nice and reproducible sample. We have to look at this closer! On my Windows 11 workstation it crashes after 300 iterations.

**Comment by animitta** [comment]
@viceroypenguin The crash times is uncertain, with my surface laptop 3 is about 70, my desktop 200-300. All OS are Windows 11.

**Comment by viceroypenguin** [comment]
I'm on a Surface Book 3, with W11 as well. Version 22H2 (10.0.22621.1).  Since @sdanyliv  can repro, I'll let him investigate further.

**Comment by sdanyliv** [comment]
@animitta, well, there is problem with Access ODBC provider. Install latest version https://www.microsoft.com/en-us/download/details.aspx?id=13255 
Select x64 package.

**Comment by animitta** [comment]
@sdanyliv Ok, it's working fine now. Let me close this issue.
