### ISSUE TITLE
[Scaffold] Scaffold is not working for Oracle

### ISSUE THREAD

**Issue by berataydin** [linq2db/linq2db#3610]
Postgre and SQLServer scaffold is working pretty fine in our situation but Oracle give an exception below. I think it's because of that line show on the ss, I don't know  <19c versions but there is no such a 'PL/SQL%' line in that table contrary it's written exact version of the DB like Oracle 19c... bla bla with some minor version.

![MicrosoftTeams-image](https://user-images.githubusercontent.com/16878621/173399678-0bd0a9f2-9e8b-4bb2-8604-4f62409d61e9.png)

Exception message:
Stack trace:
dotnet : Unhandled exception: Object reference not set to an instance of an object.
At line:1 char:1
+ dotnet linq2db scaffold -i .\OracleAnkaDB.json
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...e of an object.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at LinqToDB.DataProvider.Oracle.OracleSchemaProvider.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at LinqToDB.Schema.LegacySchemaProvider..ctor(DataConnection connection, SchemaOptions options, ILanguageProvider languageProvider)
   at LinqToDB.CommandLine.ScaffoldCommand.Scaffold(ScaffoldOptions settings, ScaffoldInterceptors interceptors, String provider, String providerLocation, String connectionString, String additionalConnectionString, String output, Boolean overwrite)
   at LinqToDB.CommandLine.ScaffoldCommand.Execute(CliController controller, String[] rawArgs, Dictionary`2 options, IReadOnlyCollection`1 unknownArgs)
   at LinqToDB.CommandLine.CliController.Execute(String[] args)
   at LinqToDB.Tools.Program.Main(String[] args)

### Steps to reproduce
dotnet linq2db scaffold -i .\SomeOracleConfig.json

### Environment details
linq2db version: 4.0.1
Database Server: Oracle 19c
Database Provider: ODP.NET Managed
Operating system: Win11
.NET Framework: .NET 6.0

**Comment by MaceWindu** [comment]
As part of #3598
