### ISSUE TITLE
dotnet linq2db help scaffold throws exception, unable to see command list

### ISSUE THREAD

**Issue by alminol** [linq2db/linq2db#3612]
This seems weird, but "dotnet linq2db help scaffold" command throws exception in PM, so I'm unable to see the list of available commands :) Am I missing something here or is this a bug? Updated linq2db to 4.0.1 and CLI tool installed. 

VS2022 17.2.3 and .NET 5, ASP.NET REST API project

Here's the PM output:

```
PM> dotnet linq2db help scaffold
dotnet linq2db - Linq To DB command-line utilities. Version: 4.0.1.0

Usage:
        dotnet linq2db scaffold <options>

Options:

=== General : basic options

   -i, --import                              : path to JSON file with scaffold options
         type: string (optional)
         json: not allowed

dotnet : Unhandled exception: The handle is invalid.
At line:1 char:1
+ dotnet linq2db help scaffold
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep...dle is invalid.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at System.ConsolePal.GetBufferInfo(Boolean throwOnNoConsole, Boolean& succeeded)
   at LinqToDB.CommandLine.HelpCommand.WriteOptionHelp(CliCommand command, Int32 maxOptionNameWidth, String indent, OptionCategory category, CliOption option)
   at LinqToDB.CommandLine.HelpCommand.PrintCommandHelp(CliCommand command, IReadOnlyCollection`1 unknownArgs)
   at LinqToDB.CommandLine.HelpCommand.Execute(CliController controller, String[] rawArgs, Dictionary`2 options, IReadOnlyCollection`1 unknownArgs)
   at LinqToDB.CommandLine.CliController.Execute(String[] args)
   at LinqToDB.Tools.Program.Main(String[] args)
```

### Environment details
linq2db version: 4.0.1
Database Server: PostgreSQL
Operating system: Windows 10 Pro, Visual Studio 2022 17.2.3
.NET Framework: .NET 5

**Comment by MaceWindu** [comment]
https://github.com/dotnet/sdk/issues/5929

**Comment by alminol** [comment]
> Attaching output as workaround: [scaffold_help.txt](https://github.com/linq2db/linq2db/files/8908241/scaffold_help.txt)

I suggest that this help output should be put on the documentation page, it's handy to have it in browser while defining.

**Comment by MaceWindu** [comment]
Added link to help to https://linq2db.github.io/articles/CLI.html#use (`dotnet linq2db help scaffold` description)
