### ISSUE TITLE
Access and VS2022

### ISSUE THREAD

**Issue by AndreasWaning** [linq2db/linq2db#3626]
Hello,
I often used MS Access for my Parameterdatas.

Now since VS2022 (64bit) I can not use Access anymore.

Is there a easy solution for this problem ?

**Comment by MaceWindu** [comment]
There is not enough information to address it:
- what kind of issue you have
- how it related to VS 2022 and linq2db

Only idea I have is that you use T4 templates for Access and by default they configured to use Jet provider which is x86-only and VS2022 runs T4 in x64 process now.

In that case you have two options:
- specify connection string for x64  OleDb or ODBC provider (must be installed). Check this message for more details https://github.com/linq2db/linq2db/discussions/3345#discussioncomment-1636510
- switch from T4 templates to new scaffolding utility. Recommended, as it supports new scaffold mode for Access with two connection strings (OleDb + ODBC). This allows us to get proper database model for scaffolding as both OleDb and ODBC return incomplete database schema. In new "two-connections" mode we merge schema information from both providers to fill missing gaps.

**Comment by AndreasWaning** [comment]
Hello Mark,
Tanks, that is excatly what I need. I will check it tomorrow Tnaks Andreas

**Comment by AndreasWaning** [comment]
If I try it for Access I get this error:

> dotnet linq2db scaffold -o c:\Test -p Access -c "Provider=Microsoft.Jet.OLEDB.4.0;Data Source=C:\\AWData\\Dropbox\\AW\\AW65\\.NetCore\\GM-Arbeitsordner\\Datenbank\\GutachterDBV80.mdb;Locale Identifier=1033;Jet OLEDB:Engine Type=5;Persist Security Info=True;"
WARNING: it is recommended to use '--additional-connection <secondary_connection>' option with Access for better results
Unhandled exception: The 'Microsoft.Jet.OLEDB.4.0' provider is not registered on the local machine.
   at System.Data.OleDb.OleDbServicesWrapper.GetDataSource(OleDbConnectionString constr, DataSourceWrapper& datasrcWrapper)
   at System.Data.OleDb.OleDbConnectionInternal..ctor(OleDbConnectionString constr, OleDbConnection connection)
   at System.Data.OleDb.OleDbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningObject)
   at System.Data.ProviderBase.DbConnectionFactory.CreateConnection(DbConnectionOptions options, DbConnectionPoolKey poolKey, Object poolGroupProviderInfo, DbConnectionPool pool, DbConnection owningConnection, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.CreateNonPooledConnection(DbConnection owningConnection, DbConnectionPoolGroup poolGroup, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionClosed.TryOpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.ProviderBase.DbConnectionInternal.OpenConnection(DbConnection outerConnection, DbConnectionFactory connectionFactory)
   at System.Data.OleDb.OleDbConnection.Open()
   at LinqToDB.Async.AsyncDbConnection.Open()
   at LinqToDB.Data.DataConnection.EnsureConnection(Boolean connect)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at LinqToDB.Schema.LegacySchemaProvider..ctor(DataConnection connection, SchemaOptions options, ILanguageProvider languageProvider)
   at LinqToDB.CommandLine.ScaffoldCommand.Scaffold(ScaffoldOptions settings, ScaffoldInterceptors interceptors, String provider, String providerLocation, String connectionString, String additionalConnectionString, String output, Boolean overwrite)
   at LinqToDB.CommandLine.ScaffoldCommand.Execute(CliController controller, String[] rawArgs, Dictionary`2 options, IReadOnlyCollection`1 unknownArgs)
   at LinqToDB.CommandLine.CliController.Execute(String[] args)
   at LinqToDB.Tools.Program.Main(String[] args)
PS C:\>

**Comment by MaceWindu** [comment]
Regarding SQL Server instance failure - try to remove extra slash in instance name from connection string: `WANING_P3541\HMA`

**Comment by AndreasWaning** [comment]
Thank you very much.
That works fine.
Thank you for the Linq2db tool. It is really a great tool.

I have one question more:
At the moment he creates for each table one file.
Is it possible to set all classes in one file ? (As he did before ?

Thanks Andreas

Li

**Comment by MaceWindu** [comment]
Sure, use `--single-file true` option

https://linq2db.github.io/articles/CLI.html

https://linq2db.github.io/articles/cli-help.txt

**Comment by AndreasWaning** [comment]
Now I am happy. Thanks
