### ISSUE TITLE
An item with the same key has already been added (4.1.1)

### ISSUE THREAD

**Issue by timbze** [linq2db/linq2db#3668]
I think this is a regression, or I have bad code. I believe #3639 is my culprit.

My code works in 4.1.0 (also worked in 3.x), but is not working in 4.1.1

My code is quite complex, the issue seems to come in a `where` which follows a `union all`. I can share it privately if needed.

```
Message=An item with the same key has already been added. Key: value(my.namespace+<>c__DisplayClass13_0).fromDate, EventId=100, EventName=ExceptionRenderingComponent|WARN|Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer.HandleException|Microsoft.AspNetCore.Components.Server.Circuits.RemoteRenderer|Unhandled exception rendering component: An item with the same key has already been added. Key: value(my.namespace+<>c__DisplayClass13_0).fromDate System.ArgumentException: An item with the same key has already been added. Key: value(my.namespace+<>c__DisplayClass13_0).fromDate
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at LinqToDB.Linq.Builder.GroupByBuilder.GroupByContext.GroupByHelper`3.GetGrouping(GroupByContext context)
   at LinqToDB.Linq.Builder.GroupByBuilder.GroupByContext.BuildGrouping()
   at LinqToDB.Linq.Builder.GroupByBuilder.GroupByContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__93_0(ValueTuple`4 context, Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__93_0(ValueTuple`4 context, Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.PassThroughContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__93_0(ValueTuple`4 context, Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.PassThroughContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.PassThroughContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.<>c.<BuildExpression>b__40_0(ValueTuple`4 context, IBuildContext ctx, Expression ex, Int32 l)
   at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T,TContext](TContext context, Expression expression, Int32 level, Func`5 action, Func`2 defaultAction, Boolean throwOnError)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__93_0(ValueTuple`4 context, Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
...
```

### Environment details
linq2db version: *4.1.1*
Database Server: *Ubuntu 22.04* (irrelevant to this bug)
Database Provider: *PostgreSQL* (irrelevant to this bug)
Operating system: *Ubuntu 22.04* (irrelevant to this bug)
.NET Framework: *.NET 6.0*

**Comment by sdanyliv** [comment]
Yes, it may cause such exception. Will prepare fix.
