### ISSUE TITLE
F# Some in Where/Join Causes Exception

### ISSUE THREAD

**Issue by devinlyons** [linq2db/linq2db#3670]
Using `Some` to wrap a column in the where clause of a query in F# results in an exception.
Here is an example query:

``` fsharp
query {
    for p in db.Person do
    where (Some p.FirstName = Some "John")
    select p
  }
```

The example may seem bogus but it makes a lot more since when you need to join tables where the foreign key could be null.

``` fsharp
query {
     for c in db.Company do
     join p in db.Person
         on (Some c.Id = p.EmployerId)
     select c
  }
```

I get this exception:

```
Exception message: LinqToDB.Linq.LinqException: ''Some p.FirstName' cannot be converted to SQL.'
Stack trace:
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at Microsoft.FSharp.Collections.SeqModule.Iterate[T](FSharpFunc`2 action, IEnumerable`1 source)
```

### Steps to reproduce

```fsharp
open System
open LinqToDB.Data

type Person = 
  {
    Id : int
    EmployerId : int option
  }

type Company = 
  {
    Id : int
  } 

[<EntryPoint>]
let main argv =
  use db = new DataConnection("")
  query {
     for c in db.GetTable<Company>() do
     join p in db.GetTable<Person>()
         on (Some c.Id = p.EmployerId)
     select c
  } |> Seq.toList
```

### Environment details
linq2db version: *4.0.1*
Database Server: *iSeries DB2*
Database Provider: *Linq2Db4iSeries*
Operating system: *Windows 10*
.NET Framework: *6.0*

**Comment by MaceWindu** [comment]
Didn't looked into it but from error it looks like another case where F# compiler use custom `FSharpExpr` objects in `Expression` tree. Such expressions cannot be processed as we don't have access to full expression. Instead of it we have `FSharpExpr` which is black box for us. When I checked last time there were no `Reduce` method for it to convert it to `Expression` tree and in no way we will write our own translatior for it.

**Comment by MaceWindu** [comment]
Anyway. We plan to look at various F#-related issues after we will finish with linq parser rewrite - maybe we will be able to do something here.

**Comment by devinlyons** [comment]
Is this what you need: [QuotationToExpression](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-linq-runtimehelpers-leafexpressionconverter.html#QuotationToExpression)? There's a typed version of this function too: [QuotationToLambdaExpression](https://fsharp.github.io/fsharp-core-docs/reference/fsharp-linq-runtimehelpers-leafexpressionconverter.html#QuotationToLambdaExpression).

**Comment by devinlyons** [comment]
I've been debugging this in LinqToDB and I don't see a reference to a FSharpExpr. The builder seems to interpret this as a method call, not some unknown expression. Is it possible that the expression parser just needs to know that `Some value` should be interpreted as `value` in SQL?

**Comment by MaceWindu** [comment]
Ah, in that case it should be simple - you need to register custom translator using `Expressions.MapMember` method.

Regarding `QuotationToExpression` - I don't remember all details, but it wasn't working well with external variables or lambda parameters (don't remember now). Code [here](https://github.com/dotnet/fsharp/issues/2758#issuecomment-731588622) tries to fix it, but as it is said here - it's solution for specific case as cannot be used as general solution for cases with arbitrary types

**Comment by devinlyons** [comment]
I think I got it working. For anyone who wants to do the same thing, here is the solutions I came up with:

```csharp
    public class FSharpSomeInfoProvider<T> : IGenericInfoProvider
    {
        [Sql.Expression("{0}", Precedence = Precedence.Primary)]
        public static FSharpOption<T> Some(T val) => FSharpOption<T>.Some(val);

        public void SetInfo(MappingSchema mappingSchema)
        {
            Expressions.MapMember((T val) => FSharpOption<T>.Some(val), (T val) => Some(val));
        }
    }
```

Then you just need to register the provider somewhere in your application using `Expressions.SetGenericInfoProvider(typeof(FSharpSomeInfoProvider<>));`.

**Comment by MaceWindu** [comment]
For some time already I have an idea to introduce additional package for F# with various additional F#-specific mappings.

Currently we have some stuff implemented in linq2db, but it requires reflection and type checks by type name which is far from optimal and not needed for most of users.

**Comment by devinlyons** [comment]
I don't know if it will help, but here is my implementation of an F# provider that wraps the DB2iSeriesProvider. it could be abstracted to wrap any provider though. I'm not sure the implementation is very efficient though. If you have any suggestions, that would be helpful.

```csharp
using LinqToDB;
using LinqToDB.Common;
using LinqToDB.Data;
using LinqToDB.DataProvider.DB2iSeries;
using LinqToDB.Linq;
using LinqToDB.SqlQuery;
using Microsoft.FSharp.Core;
using System;
using System.Data.Common;
using System.Data.Linq;
using System.Xml;
using System.Xml.Linq;

namespace FSharp.LinqToDb
{
    public class FSharpDB2iSeriesDataProvider : DB2iSeriesDataProvider
    {
        public FSharpDB2iSeriesDataProvider() 
            : base(DB2iSeriesProviderOptions.Defaults.Instance)
        {
            this.Initialize();
        }

        public FSharpDB2iSeriesDataProvider(DB2iSeriesProviderOptions providerOptions) 
            : base(providerOptions)
        {
            this.Initialize();
        }

        public FSharpDB2iSeriesDataProvider(DB2iSeriesProviderType providerType, DB2iSeriesVersion version)
            : base(new DB2iSeriesProviderOptions(DB2iSeriesProviderName.GetProviderName(version, providerType, new DB2iSeriesMappingOptions(DB2iSeriesMappingOptions.Default.MapGuidAsString)), providerType, version))
        {
            this.Initialize();
        }

        public FSharpDB2iSeriesDataProvider(DB2iSeriesProviderType providerType, DB2iSeriesVersion version, DB2iSeriesMappingOptions mappingOptions) 
            : base(new DB2iSeriesProviderOptions(DB2iSeriesProviderName.GetProviderName(version, providerType, mappingOptions), providerType, version))
        {
            this.Initialize();
        }

        public FSharpDB2iSeriesDataProvider(string name, DB2iSeriesProviderType providerType, DB2iSeriesVersion version) 
            : base(new DB2iSeriesProviderOptions(name, providerType, version))
        {
            this.Initialize();
        }

        private void Initialize()
        {
            Expressions.SetGenericInfoProvider(typeof(FSharpSomeInfoProvider<>));
            this.SetDefaultScalarTypes();
            this.SetDefaultConvertExpressions();
            this.SetDefaultValueToSqlConversions();
        }

        private void SetDefaultScalarTypes()
        {
            this.MappingSchema.AddScalarType(typeof(FSharpOption<char>), new SqlDataType(DataType.NChar, typeof(char?), 1));
            this.MappingSchema.AddScalarType(typeof(FSharpOption<string>), DataType.NVarChar);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<decimal>), DataType.Decimal);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<DateTime>), DataType.DateTime2);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<DateTimeOffset>), DataType.DateTimeOffset);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<TimeSpan>), DataType.Time);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<byte[]>), DataType.VarBinary);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<Binary>), DataType.VarBinary);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<Guid>), DataType.Guid);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<object>), DataType.Variant);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<XmlDocument>), DataType.Xml);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<XDocument>), DataType.Xml);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<bool>), DataType.Boolean);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<sbyte>), DataType.SByte);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<short>), DataType.Int16);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<int>), DataType.Int32);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<long>), DataType.Int64);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<byte>), DataType.Byte);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<ushort>), DataType.UInt16);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<uint>), DataType.UInt32);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<ulong>), DataType.UInt64);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<float>), DataType.Single);
            this.MappingSchema.AddScalarType(typeof(FSharpOption<double>), DataType.Double);
        }

        private void SetDefaultConvertExpressions()
        {
            this.SetFSharpOptionConversionExpression<char>();
            this.SetFSharpOptionConversionExpression<string>();
            this.SetFSharpOptionConversionExpression<decimal>();
            this.SetFSharpOptionConversionExpression<DateTime>();
            this.SetFSharpOptionConversionExpression<DateTimeOffset>();
            this.SetFSharpOptionConversionExpression<TimeSpan>();
            this.SetFSharpOptionConversionExpression<byte[]>();
            this.SetFSharpOptionConversionExpression<Binary>();
            this.SetFSharpOptionConversionExpression<Guid>();
            this.SetFSharpOptionConversionExpression<object>();
            this.SetFSharpOptionConversionExpression<XmlDocument>();
            this.SetFSharpOptionConversionExpression<XDocument>();
            this.SetFSharpOptionConversionExpression<bool>();
            this.SetFSharpOptionConversionExpression<sbyte>();
            this.SetFSharpOptionConversionExpression<short>();
            this.SetFSharpOptionConversionExpression<int>();
            this.SetFSharpOptionConversionExpression<long>();
            this.SetFSharpOptionConversionExpression<byte>();
            this.SetFSharpOptionConversionExpression<ushort>();
            this.SetFSharpOptionConversionExpression<uint>();
            this.SetFSharpOptionConversionExpression<ulong>();
            this.SetFSharpOptionConversionExpression<float>();
            this.SetFSharpOptionConversionExpression<double>();
        }

        private void SetFSharpOptionConversionExpression<T>()
        {
            this.MappingSchema.SetConvertExpression<FSharpOption<T>, T?>(x => x.IsSome() ? x.Value : default(T));
        }

        private void SetDefaultValueToSqlConversions()
        {
            this.SetFSharpOptionValueToSqlConverter<char>();
            this.SetFSharpOptionValueToSqlConverter<string>();
            this.SetFSharpOptionValueToSqlConverter<decimal>();
            this.SetFSharpOptionValueToSqlConverter<DateTime>();
            this.SetFSharpOptionValueToSqlConverter<DateTimeOffset>();
            this.SetFSharpOptionValueToSqlConverter<TimeSpan>();
            this.SetFSharpOptionValueToSqlConverter<byte[]>();
            this.SetFSharpOptionValueToSqlConverter<Binary>();
            this.SetFSharpOptionValueToSqlConverter<Guid>();
            this.SetFSharpOptionValueToSqlConverter<object>();
            this.SetFSharpOptionValueToSqlConverter<XmlDocument>();
            this.SetFSharpOptionValueToSqlConverter<XDocument>();
            this.SetFSharpOptionValueToSqlConverter<bool>();
            this.SetFSharpOptionValueToSqlConverter<sbyte>();
            this.SetFSharpOptionValueToSqlConverter<short>();
            this.SetFSharpOptionValueToSqlConverter<int>();
            this.SetFSharpOptionValueToSqlConverter<long>();
            this.SetFSharpOptionValueToSqlConverter<byte>();
            this.SetFSharpOptionValueToSqlConverter<ushort>();
            this.SetFSharpOptionValueToSqlConverter<uint>();
            this.SetFSharpOptionValueToSqlConverter<ulong>();
            this.SetFSharpOptionValueToSqlConverter<float>();
            this.SetFSharpOptionValueToSqlConverter<double>();
        }

        private void SetFSharpOptionValueToSqlConverter<T>()
        {
            this.MappingSchema.SetValueToSqlConverter(typeof(FSharpOption<T>), (sb, dt, v) =>
            {
                var x = v as FSharpOption<T>;

                if (x != null && x.IsSome())
                {
                    this.MappingSchema.ValueToSqlConverter.Convert(sb, x.Value);
                }
                else
                {
                    this.MappingSchema.ValueToSqlConverter.Convert(sb, null);
                }
            });
        }

        public override void SetParameter(DataConnection dataConnection, DbParameter parameter, string name, DbDataType dataType, object value)
        {
            object? v = value;
            var t = v.GetType();
            if (t.IsGenericType && t.GetGenericTypeDefinition() == typeof(FSharpOption<>))
            {
                var m = t.GetMethod("get_IsSome");
                var isSomeObj = m?.Invoke(null, new object[] { v });
                var isSome = isSomeObj as bool?;

                if (isSome.GetValueOrDefault())
                {
                    var p = t.GetProperty("Value");
                    v = p?.GetValue(v);
                }
                else
                {
                    v = null;
                }
            }

            base.SetParameter(dataConnection, parameter, name, dataType, v);
        }
    }
}

```

**Comment by devinlyons** [comment]
Of course, this isn't quite working. I have an enum and entity like this:

```csharp
public enum MyEnum {
    [MapValue("Foo")] Foo,
    [MapValue("Bar")] Bar
}

public class MyEntity {
    public int Id { get; set; }
    public FSharpOption<MyEnum> Baz { get; set; }
}
```

I get an error when I query `MyEntity` because it can't convert the string from the database into `FSharpOption<MyEnum>`. Is there a place to specify a generic converter that would produce `FSharpOption<T where T : Enum>`s?

Here's the query:

```fsharp
[<EntryPoint>]
let main argv =
  use db = new DataConnection("")
  query {
     for e in db.GetTable<MyEntity>() do
     select e
  } |> Seq.toList
```

Here's the error:

``Cannot convert value '2: System.String' to type 'Microsoft.FSharp.Core.FSharpOption`1[[MyEnum, ...]]'``

And the stack trace:

```
   at LinqToDB.Common.ConvertBuilder.ConvertDefault(Object value, Type conversionType)
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(DbDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__11`1.MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
   at Program.main(String[] argv)
```

Here's the inner exception:

``Invalid cast from 'System.String' to 'Microsoft.FSharp.Core.FSharpOption`1[[MyEnum, ...]]'.``

And the stack trace:

```
   at System.Convert.DefaultToType(IConvertible value, Type targetType, IFormatProvider provider)
   at System.String.System.IConvertible.ToType(Type type, IFormatProvider provider)
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at LinqToDB.Common.ConvertBuilder.ConvertDefault(Object value, Type conversionType)
```

**Comment by devinlyons** [comment]
I tried working with value converters but they don't seem to work with wrapper types like `FSharpOption`. Do you have any suggestions on how to solve this?

**Comment by MaceWindu** [comment]
Well, open generic support is not here yet. [This comment](https://github.com/linq2db/linq2db/issues/195#issuecomment-739967734) suggests to use custom metadata provider that will return column value converter for columns with wrapper type.

Value converters : https://github.com/linq2db/linq2db/wiki/Release-Notes-3.0.0#value-converters-2273

**Comment by devinlyons** [comment]
Here is my value converter so far. Unfortunately, whenever the `FromProviderExpression` runs, I get an `ArgumentException`. Do you see any reason that would happen?

The Exception: `System.ArgumentException: 'Argument type cannot be System.Void. (Parameter 'type')'`

The Stacktrace:
```
   at System.Linq.Expressions.Expression.Validate(Type type, Boolean allowByRef)
   at LinqToDB.Common.ConvertBuilder.GetConverter(MappingSchema mappingSchema, Type from, Type to)
   at LinqToDB.Common.ConvertInfo.Create(MappingSchema mappingSchema, DbDataType from, DbDataType to)
   at LinqToDB.Mapping.MappingSchema.GetConverter(DbDataType from, DbDataType to, Boolean create)
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ConvertExpressionToType(Expression current, Type toType, MappingSchema mappingSchema)
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.GetColumnReader(IDataContext dataContext, MappingSchema mappingSchema, DbDataReader dataReader, Type type, IValueConverter converter, Int32 idx, Expression dataReaderExpr, Boolean forceNullCheck)
   at LinqToDB.Linq.QueryRunner.Mapper`1.<>c.<TransformMapperExpression>b__7_1(TransformMapperExpressionContext context, Expression e)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Modify(MemberBinding b)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source, Func`2 func)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Linq.QueryRunner.Mapper`1.TransformMapperExpression(IDataContext context, DbDataReader dataReader, Type dataReaderType, Boolean slowMode)
   at LinqToDB.Linq.QueryRunner.Mapper`1.GetMapperInfo(IDataContext context, IQueryRunner queryRunner, DbDataReader dataReader)
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__11`1.MoveNext()
   at Microsoft.FSharp.Collections.SeqModule.ToList[T](IEnumerable`1 source)
```

The Converter:

```csharp

    public class FSharpOptionConverter<T> : IValueConverter where T : struct, Enum
    {
        public FSharpOptionConverter()
            : base()
        {
            var valueType = typeof(T);
            var optionType = typeof(FSharpOption<T>);
            var providerType = ConvertBuilder.GetDefaultMappingFromEnumType(MappingSchema.Default, valueType) ?? typeof(int);
            var (to, _, _) = ConvertBuilder.GetConverter(MappingSchema.Default, valueType, providerType);
            var (from, _, _) = ConvertBuilder.GetConverter(MappingSchema.Default, providerType, valueType);

            this.HandlesNulls = false;
            this.ToProviderExpression = this.BuildToExpression(optionType, to);
            this.FromProviderExpression = this.BuildFromExpression(optionType, providerType, from);
        }

        private LambdaExpression BuildToExpression(Type optionType, LambdaExpression toExp)
        {
            var isNone = optionType.GetMethod(nameof(FSharpOption<T>.get_IsNone))!;
            var value = optionType.GetProperty(nameof(FSharpOption<T>.Value))!;

            var param = Expression.Parameter(optionType, "v");
            var test = Expression.Call(null, isNone, param);
            var nullExp = Expression.Constant(null);
            var valueProp = Expression.Property(param, value);
            var convertInv = Expression.Invoke(toExp, valueProp);
            var body = Expression.IfThenElse(test, nullExp, convertInv);
            return Expression.Lambda(body, param);
        }

        private LambdaExpression BuildFromExpression(Type optionType, Type providerType, LambdaExpression fromExp)
        {
            var some = optionType.GetMethod(nameof(FSharpOption<T>.Some))!;
            var none = optionType.GetProperty(nameof(FSharpOption<T>.None))!;

            var param = Expression.Parameter(providerType, "p");
            var test = Expression.Equal(param, Expression.Constant(null));
            var noneExp = Expression.Property(null, none);
            var convertInv = Expression.Invoke(fromExp, param);
            var someCall = Expression.Call(null, some, convertInv);
            var body = Expression.IfThenElse(test, noneExp, someCall);
            return Expression.Lambda(body, param);
        }

        public bool HandlesNulls { get; init; }

        public LambdaExpression FromProviderExpression { get; init; }

        public LambdaExpression ToProviderExpression { get; init; }
    }
```

**Comment by sdanyliv** [comment]
`Expression.IfThenElse(test, noneExp, someCall)`. Both variants should return same type.

**Comment by devinlyons** [comment]
They do have the same type. Both are `FSharpOption<MyEnum>`. I can see that at runtime: `noneExp.Type.Equals(someCall.Type)` is true.

**Comment by sdanyliv** [comment]
This one `var nullExp = Expression.Constant(null);` has void type.

**Comment by devinlyons** [comment]
I think I got it working. I put the code in a gist in case anybody is doing something similar. I can't promise it's the most efficient way to do it but it seems to work: https://gist.github.com/devinlyons/f74b4958d42c9377a187d5fcfca16a8e.
