### ISSUE TITLE
[Scaffold] Investigate why `exclude-schemas` option breaks Access scaffold

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3709]
Hi, I am trying to generate a scaffold from a older MS Access database. For this, I've created the following JSON configuration file:

```{
  "general": {
    "provider": "Access",
    "connection": "Driver={Microsoft Access Driver (*.mdb, *.accdb)};Dbq=C:\\Users\\kai\\Documents\\T2000_b\\IKS-DB.mdb;Persist Security Info=False;",
    "additional-connection": "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\\Users\\kai\\Documents\\T2000_b\\IKS-DB.mdb;Persist Security Info=False",
    "output": "C:\\Users\\kai\\RiderProjects\\DBAccess\\DBAccess\\",
    "overwrite": true
  },
    "schema" : {
      "include-tables": [{"name":  "HOSTS"},{"name": "FNT-All"}],
      "exclude-schemas": ["Check","Server","installiert","nicht abgebaut","nicht in FNT"]
    },
  "code": {
    "single-file": true
  }
}
```
and I'm invoking it with
```
C:\Users\kai> dotnet-linq2db.exe scaffold -p Access -c "Driver={Microsoft Access Driver (*.mdb, *.accdb)};Dbq=C:\Users\kai\Documents\T2000_b\IKS-DB.mdb;Persist Security Info=False;" --additional-connection "Provider=Microsoft.ACE.OLEDB.12.0;Data Source=C:\Users\kai\Documents\T2000_b\IKS-DB.mdb;Persist Security Info=False" -i C:\Users\kai\RiderProjects\DBAccess\DBAccess\table.json
```

It fails with the following error message:
```
Unhandled exception: ColumnType not provided by schema for table Check, Server, installiert, nicht abgebaut, nicht in FNT
   at LinqToDB.Schema.LegacySchemaProvider.ParseColumn(SqlObjectName tableName, ColumnSchema column)
   at LinqToDB.Schema.LegacySchemaProvider.ParseTable(TableSchema table, SchemaObjects loadedObjects)
   at LinqToDB.Schema.LegacySchemaProvider.ParseSchema(DatabaseSchema schema, SchemaObjects loadedObjects)
   at LinqToDB.Schema.LegacySchemaProvider..ctor(DataConnection connection, SchemaOptions options, ILanguageProvider languageProvider)
   at LinqToDB.CommandLine.ScaffoldCommand.Scaffold(ScaffoldOptions settings, ScaffoldInterceptors interceptors, String provider, String providerLocation, String connectionString, String additionalConnectionString, String output, Boolean overwrite)
   at LinqToDB.CommandLine.ScaffoldCommand.Execute(CliController controller, String[] rawArgs, Dictionary`2 options, IReadOnlyCollection`1 unknownArgs)
   at LinqToDB.CommandLine.CliController.Execute(String[] args)
   at LinqToDB.Tools.Program.Main(String[] args)
```
which is interesting, because I've checked the schemas are not used in the tables. Furthermore I'm using the Linq2DB for LINQPad 7 (v.4.1.1.0) and created a connection to the database. Here it works without a problem. I hope you can help me.

Thanks in advance,

Kai

_Originally posted by @Delta-VII in https://github.com/linq2db/linq2db/discussions/3706_

**Comment by MaceWindu** [comment]
Issue is not relates to schema filtering. For some reason Access ODBC provider behavior changed and now it reports columns of decimal type but doesn't report decimal type types schema.
