### ISSUE TITLE
Merge when entity has QueryFilter:System.NotImplementedException: Currently, only CTEs are supported as the target of a merge. You can fix by calling .AsCte() before calling .Merge()

### ISSUE THREAD

**Issue by darkflame0** [linq2db/linq2db#3729]
```cs
            db.GetFluentMappingBuilder().Entity<Test>().HasQueryFilter((a, b) => a.Where(a => a.Id != 0));
            db.CreateTable<Test>(tableOptions: TableOptions.CreateIfNotExists);
            await db.GetTable<Test>()
                .Merge()
                .Using(Enumerable.Repeat(new Test(), 1))
                .OnTargetKey()
                .InsertWhenNotMatched()
                .MergeAsync();

        [Table(IsColumnAttributeRequired = false)]
        public class Test
        {
            [Identity]
            [PrimaryKey]
            public int Id { get; set; }
        }
```

```
System.NotImplementedException: Currently, only CTEs are supported as the target of a merge. You can fix by calling .AsCte() before calling .Merge()
   at LinqToDB.Linq.Builder.MergeBuilder.Merge.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MergeBuilder.Using.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MergeBuilder.On.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MergeBuilder.InsertWhenNotMatched.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MergeBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
```

**Comment by MaceWindu** [comment]
Interesting. Looks like a bug, we shouldn't apply filter to target tables.

**Comment by MaceWindu** [comment]
As workaround add call to `IgnoreFilters`:

```cs
await db.GetTable<Test>().IgnoreFilters()
                .Merge()
                .Using(Enumerable.Repeat(new Test(), 1))
                .OnTargetKey()
                .InsertWhenNotMatched()
                .MergeAsync();
```
