### ISSUE TITLE
Could not load type 'NpgsqlTypes.NpgsqlDate' in .NET 7.0 preview 7

### ISSUE THREAD

**Issue by timbze** [linq2db/linq2db#3734]
### Describe your issue

It seems like LinqToDB is not working in .NET 7 at all. Here's a very simple repro in a .NET console project.

```csharp
using LinqToDB.Configuration;
using LinqToDB.Data;

var linqToDbBuilder = new LinqToDBConnectionOptionsBuilder();
linqToDbBuilder.UsePostgreSQL("Server=localhost;Port=5432;Database=db;User Id=postgres; Password=thepassword;");

var context = new DbContext(new LinqToDBConnectionOptions(linqToDbBuilder));
Console.WriteLine("Hello, World!");

public class DbContext : DataConnection
{
    public DbContext(LinqToDBConnectionOptions options) : base(options) {}
}
```

```
Exception message: Could not load type 'NpgsqlTypes.NpgsqlDate' from assembly 'Npgsql, Version=7.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
Stack trace:
Unhandled exception. System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.TypeLoadException: Could not load type 'NpgsqlTypes.NpgsqlDate' from assembly 'Npgsql, Version=7.0.0.0, Culture=neutral, PublicKeyToken=5d8b90d52f46fda7'.
   at System.Reflection.RuntimeAssembly.GetType(QCallAssembly assembly, String name, Boolean throwOnError, Boolean ignoreCase, ObjectHandleOnStack type, ObjectHandleOnStack keepAlive, ObjectHandleOnStack assemblyLoadContext)
   at System.Reflection.RuntimeAssembly.GetType(String name, Boolean throwOnError, Boolean ignoreCase)
   at LinqToDB.DataProvider.PostgreSQL.NpgsqlProviderAdapter.GetInstance()
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLMappingSchema.PostgreSQL92MappingSchema..ctor()
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider.GetMappingSchema(PostgreSQLVersion version)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider..ctor(String name, PostgreSQLVersion version)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider92..ctor()
   at System.RuntimeType.CreateInstanceOfT()
   --- End of inner exception stack trace ---
   at System.RuntimeType.CreateInstanceOfT()
   at System.Activator.CreateInstance[T]()
   at LinqToDB.Data.DataConnection.<>c__112`1.<CreateDataProvider>b__112_0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.ExecutionAndPublication(LazyHelper executionAndPublication, Boolean useDefaultConstructor)
   at System.Lazy`1.CreateValue()
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.ProviderDetector(IConnectionStringSettings css, String connectionString)
   at LinqToDB.Data.DataConnection.ConfigurationInfo.<>c__DisplayClass12_0.<GetDataProvider>b__0(Func`3 d)
   at System.Linq.Enumerable.SelectListIterator`2.MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Func`2 predicate, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source, Func`2 predicate)
   at LinqToDB.Data.DataConnection.ConfigurationInfo.GetDataProvider(IConnectionStringSettings css, String connectionString)
   at LinqToDB.Data.DataConnection.GetDataProvider(String providerName, String connectionString)
   at LinqToDB.Data.DataConnection..ctor(LinqToDBConnectionOptions options)
   at DbContext..ctor(LinqToDBConnectionOptions options) in /home/timmy/Repos/Tmp/LinqToDB_NET7/Program.cs:line 14
   at Program.<Main>$(String[] args) in /home/timmy/Repos/Tmp/LinqToDB_NET7/Program.cs:line 9
```

### Environment details

`Linq To DB` version: *4.1.1*

Database (with version): *PostgreSQL 14*

Operating system: *Ubuntu 22.04*

.NET Version: *7.0 preview 7*

**Comment by sdanyliv** [comment]
@MaceWindu, I think we already have fix for this in master branch. Please confirm.

**Comment by timbze** [comment]
@sdanyliv I found the nuget packages on Azure artifacts and tried the latest, and it works. Thanks

**Comment by MaceWindu** [comment]
Yep, duplicate of #3667

**Comment by timbze** [comment]
@MaceWindu we both closed as completed 👏🏽 😄 

Thanks for this great library
