### ISSUE TITLE
Invalid default column type for Timespan on Oracle

### ISSUE THREAD

**Issue by Jubast** [linq2db/linq2db#3736]
### Invalid default column type for Timespan property on Oracle

```
Exception message: ORA-00902: invalid datatype
Stack trace:  at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, OracleLogicalTransaction& oracleLogicalTransaction, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at System.Data.Common.DbCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryDataAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryDataAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.CreateTable`1.QueryAsync(IDataContext dataContext, String tableName, String serverName, String databaseName, String schemaName, String statementHeader, String statementFooter, DefaultNullable defaultNullable, TableOptions tableOptions, CancellationToken token)
```

### Steps to reproduce

```cs
[Serializable]
public class TypesTestTable
{
    public bool BoolValue { get; set; }
    public bool? NullableBoolValue { get; set; }
    public char CharValue { get; set; }
    public string StringValue { get; set; }
    public decimal DecimalValue { get; set; }
    public decimal? NullableDecimalValue { get; set; }
    public Guid GuidValue { get; set; }
    public int IntValue { get; set; }
    public int? NullableIntValue { get; set; }
    public DateTime DateTimeValue { get; set; }
    public DateTime? NullableDateTimeValue { get; set; }
    public DateTimeOffset DateTimeOffsetValue { get; set; }
    public DateTimeOffset? NullableDateTimeOffsetValue { get; set; }
    public TimeSpan TimeSpanValue { get; set; }
    public TimeSpan? NullableTimeSpanValue { get; set; }
}

var builder = new LinqToDBConnectionOptionsBuilder();
OracleTools.DontEscapeLowercaseIdentifiers = true;
builder.UseOracle("Data Source=(DESCRIPTION=(ADDRESS_LIST=(ADDRESS=(PROTOCOL=TCP)(HOST=localhost)(PORT=1521)))(CONNECT_DATA=(SERVICE_NAME=XEPDB1)));User Id=username;Password=password;");
var options = builder.Build();

var dataConnection = new DataConnection(options);
await dataConnection.CreateTableAsync<TypesTestTable>();
```

Created SQL clause (LastQuery Property from DataConenction)
```sql
CREATE TABLE TypesTestTable
(
	BoolValue                   Char(1)                  NOT NULL,
	NullableBoolValue           Char(1)                      NULL,
	CharValue                   NChar(1)                 NOT NULL,
	StringValue                 VarChar(255)                 NULL,
	DecimalValue                Decimal                  NOT NULL,
	NullableDecimalValue        Decimal                      NULL,
	GuidValue                   Raw(16)                  NOT NULL,
	IntValue                    Int                      NOT NULL,
	NullableIntValue            Int                          NULL,
	DateTimeValue               timestamp                NOT NULL,
	NullableDateTimeValue       timestamp                    NULL,
	DateTimeOffsetValue         timestamp with time zone NOT NULL,
	NullableDateTimeOffsetValue timestamp with time zone     NULL,
	TimeSpanValue               Time                     NOT NULL,
	NullableTimeSpanValue       Time                         NULL
)
```

If I remove Timespan properties the CreateTable suceeds.
It appears that the `Time` column type doesn't exist for Oracle.

### Environment details

`Linq To DB` version: *4.1.0*
Database (with version): *Oracle Database 21c Express Edition Release 21.0.0.0.0 - Production - Version 21.3.0.0.0*
ADO.NET Provider (with version): *Oracle.ManagedDataAccess.Core 2.19.110*
LinqToDB AutoPicked Provider: LinqToDB.DataProvider.Oracle.OracleDataProviderManaged12
Operating system: *Windows 10*
.NET Version: *6.0*

**Comment by MaceWindu** [comment]
There is no default mapping to TimeSpan for Oracle. Which type you expected here?

**Comment by Jubast** [comment]
I would expect that the defaults would work out of the box for any kind of provider.

Maybe the default could be a `string` representation of the timespan or a `int` in milliseconds. But I didn't really brainstorm those two options, so I don't know which approach would be better.

**Comment by MaceWindu** [comment]
Usually we don't provide mappings for types, not supported by database, except cases when such mappings are widespread (e.g. 'Y'/`N` `char(1)` for booleans).

You can specify desired mapping in mapping schema, check this example https://github.com/linq2db/linq2db/issues/2560#issuecomment-720017161

**Comment by Jubast** [comment]
I understand. Wouldn't it be better to throw an exception that there is no default mapping for the type? Getting an error from the database that an invalid datatype was was specified is a weird way to find out that a type is not supported by default.

Thank you for your time to answer my issue :)
Thank you for the example 👍

**Comment by MaceWindu** [comment]
I would agree that we should throw exceptions for such cases. We have plans to revamp type mappings configuration and probably then we change it.
