### ISSUE TITLE
[Investigate] InvalidOperationException from predicate parser

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#3743]
@MaceWindu thank you for the quick response. When you say `linq` syntax, do you mean query expression syntax?

We have a case where (1) we are using the standard linq methods (no query syntax) and (2) the fields in the anonymous records are alphabetical.

![image](https://user-images.githubusercontent.com/370746/186879668-3246f852-4070-44a5-9e20-a53d4880d706.png)

We are getting the following error:

![image](https://user-images.githubusercontent.com/370746/186879806-e32fe2d9-173f-44f9-a8e3-fc6e9a104523.png)

Stack trace:

```
>    at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToExtensionSql(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor)
   at LinqToDB.EntityFrameworkCore.Internal.EFCoreExpressionAttribute.<>c__1`1.<GetExpression>b__1_1(ValueTuple`4 ctx, String v, String d)
   at LinqToDB.Sql.ExpressionAttribute.<>c__DisplayClass68_0`1.<ResolveExpressionValues>b__0(Match match)
   at System.Text.RegularExpressions.Regex.<>c.<Replace>b__84_0(ValueTuple`5& state, Match match)
   at System.Text.RegularExpressions.RegexRunner.Scan[TState](Regex regex, String text, Int32 textstart, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run[TState](String input, Int32 startat, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject)
   at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at LinqToDB.Sql.ExpressionAttribute.ResolveExpressionValues[TContext](TContext context, String expression, Func`4 valueProvider)
   at LinqToDB.EntityFrameworkCore.Internal.EFCoreExpressionAttribute.GetExpression[TContext](TContext context, IDataContext dataContext, SelectQuery query, Expression expression, Func`4 converter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToExtensionSql(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor)
   at LinqToDB.EntityFrameworkCore.Internal.EFCoreExpressionAttribute.<>c__1`1.<GetExpression>b__1_1(ValueTuple`4 ctx, String v, String d)
   at LinqToDB.Sql.ExpressionAttribute.<>c__DisplayClass68_0`1.<ResolveExpressionValues>b__0(Match match)
   at System.Text.RegularExpressions.Regex.<>c.<Replace>b__84_0(ValueTuple`5& state, Match match)
   at System.Text.RegularExpressions.RegexRunner.Scan[TState](Regex regex, String text, Int32 textstart, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject, TimeSpan timeout)
   at System.Text.RegularExpressions.Regex.Run[TState](String input, Int32 startat, TState& state, MatchCallback`1 callback, Boolean reuseMatchObject)
   at System.Text.RegularExpressions.Regex.Replace(MatchEvaluator evaluator, Regex regex, String input, Int32 count, Int32 startat)
   at System.Text.RegularExpressions.Regex.Replace(String input, MatchEvaluator evaluator)
   at LinqToDB.Sql.ExpressionAttribute.ResolveExpressionValues[TContext](TContext context, String expression, Func`4 valueProvider)
   at LinqToDB.EntityFrameworkCore.Internal.EFCoreExpressionAttribute.GetExpression[TContext](TContext context, IDataContext dataContext, SelectQuery query, Expression expression, Func`4 converter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.SuggestColumnDescriptor(IBuildContext context, Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.AllJoinsLinqBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.get_SqlText()
   at Database.RepositoryExtra.getAdiLinqQuery(AdiId id) in C:\Work\Clients\Asbest Consulting\asbest-consulting\app\serverTests\RepositoryExtra.fs:line 51
   at Program.serverTests@21-1.Invoke(Unit unitVar) in C:\Work\Clients\Asbest Consulting\asbest-consulting\app\serverTests\Program.fs:line 21
   at Expecto.Impl.execTestAsync@569-1.Invoke(Unit unitVar)
   at Microsoft.FSharp.Control.AsyncPrimitives.CallThenInvoke[T,TResult](AsyncActivation`1 ctxt, TResult result1, FSharpFunc`2 part2)
   at Microsoft.FSharp.Control.Trampoline.Execute(FSharpFunc`2 firstAction)
```
   
Note that we are using linq2db together with EF Core (https://github.com/linq2db/linq2db.EntityFrameworkCore).

_Originally posted by @jannesiera in https://github.com/linq2db/linq2db/issues/1813#issuecomment-1228304979_

**Comment by Mrjuanblack** [comment]
Hello, I'm working with @jannesiera
I'll follow up with an example project I did to showcase the error.

The models we have:
```fsharp
[<CLIMutable>]
type CompanyInformation = {
    [<Key>]
    [<ForeignKey "Company">]
    [<DatabaseGenerated(DatabaseGeneratedOption.Identity)>]
    Id: int
    Name : string
    TypeOfCorporation : string
    PhoneNumber : string
    Email : string
}

[<CLIMutable>]
type Company = {
    [<Key>]
    [<DatabaseGenerated(DatabaseGeneratedOption.Identity)>]
    Id : int
    VatNumber : string
    BankAccount : string
    TermOfPayment : int
    VatLiable : bool
    // Address
    Street : string
    Number : string
    PostalCode : string
    City : string

    IsSoleProprietor : bool
    IsCorporation : bool
}

[<CLIMutable>]
type Person = {
    [<Key>]
    [<DatabaseGenerated(DatabaseGeneratedOption.Identity)>]
    Id : int
    LastName : string
    FirstName : string
    Email : string
    PhoneNumber : string
    // Address
    Street : string
    Number : string
    Postcode : string
    City : string

    [<ForeignKey "Company">]
    CompanyId : int
}
```

Repository methods (for testing we only wanted to check the SQL being generated):
```fsharp
type Repository(context : AppDbContext) =

    member _.getPersonTuple(id : int) =
        let q =
            context
                .Person
                .Where(fun p -> p.Id = id)
                .Join(
                    context.Companies,
                    (fun p -> p.Id),
                    (fun c -> c.Id),
                    (fun p c ->
                        (p, c)) )
                .LeftJoin(
                    context.CompaniesInformation,
                    (fun (p, c) cInfo -> c.Id = cInfo.Id),
                    (fun (p, c) cInfo ->
                        (p, c, cInfo)
                    ))
        q.ToLinqToDB().ToString()

    member _.getPersonRecord(id : int) =
        let q =
            context
                .Person
                .Where(fun p -> p.Id = id)
                .Join(
                    context.Companies,
                    (fun p -> p.Id),
                    (fun c -> c.Id),
                    (fun p c ->
                        {|
                            Person = p
                            Company = c
                        |}) )
                .LeftJoin(
                    context.CompaniesInformation,
                    (fun partialPerson cInfo -> partialPerson.Company.Id = cInfo.Id),
                    (fun partialPerson cInfo ->
                        {|
                            Person = partialPerson.Person
                            Company = partialPerson.Company
                            CompanyInformation = cInfo
                        |}) )
        q.ToLinqToDB().ToString()
```
Main program file:
```fsharp
[<EntryPoint>]
let main argv =
    let dbContext = TestDbContextFactory().CreateDbContext()
    //let query = Database.Repository(dbContext).getPersonTuple( 1 ) // Nested expression error
    let query = Database.Repository(dbContext).getPersonRecord( 1 ) // Operation is not valid error
    printfn "%s" query
    0
```
Basically, each `Person` has information in the `Company` table, but not all companies have extra information in the `CompanyInformation` table.
The `getPersonRecord` method was the first one we tried to use, but we kept getting the error that is being shown in the first comment. Then we tried to use only tuples as we saw other people having problems with anonymous records #3699. We got an error similar to #3699 where we were getting nested expressions:

```
Unhandled exception. LinqToDB.Linq.LinqException: 'p => c => (c.Id == cInfo.Id).Invoke(tupledArg.Item2).Invoke(tupledArg.Item1)' cannot be converted to SQL.
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.AllJoinsLinqBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.get_SqlText()
   at LinqToDB.Linq.ExpressionQueryImpl`1.ToString()
   at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.ToString()
   at Database.Repository.getPersonTuple(Int32 id) in D:\someFolder\sampleProject\sampleProject\Repository.fs:line 30
   at Program.main(String[] argv) in D:\someFolder\sampleProject\sampleProject\Program.fs:line 6
```

**TargetFramework :** net6.0
**Referenced Packages:**
```xml
<PackageReference Include="EntityFrameworkCore.FSharp" Version="6.0.7" />
<PackageReference Include="linq2db" Version="4.1.1" />
<PackageReference Include="linq2db.EntityFrameworkCore" Version="6.8.0" />
<PackageReference Include="Npgsql.EntityFrameworkCore.PostgreSQL" Version="6.0.6" />
```

**Comment by MaceWindu** [comment]
Looked into it. Actually it is F#-related issues.

To fix first query use anonymous records instead of tuples:
```f#
member _.getPersonTuple(id : int) =
        let q =
            context
                .Person
                .Where(fun p -> p.Id = id)
                .Join(
                    context.Companies,
                    (fun p -> p.Id),
                    (fun c -> c.Id),
                    (fun p c ->
                        {|
                        p = p
                        c = c
                        |}) )
                .LeftJoin(
                    context.CompaniesInformation,
                    (fun x cInfo -> x.c.Id = cInfo.Id),
                    (fun x cInfo ->
                        (x.p, x.c, cInfo)
                    ))
        q.ToLinqToDB().ToString()
```

Second query works for me, which means something is missing from your example (e.g. you didn't provided context class)

**Comment by Mrjuanblack** [comment]
Here's the context:
```fsharp
type AppDbContext(options: DbContextOptions<AppDbContext>) =
    inherit DbContext(options)

    [<DefaultValue>] val mutable companiesInformation : DbSet<CompanyInformation>
    member this.CompaniesInformation
        with get() = this.companiesInformation
        and set v = this.companiesInformation <- v

    [<DefaultValue>] val mutable companies : DbSet<Company>
    member this.Companies
        with get() = this.companies
        and set v = this.companies <- v

    [<DefaultValue>] val mutable person : DbSet<Person>
    member this.Person
        with get() = this.person
        and set v = this.person <- v

    override _.OnModelCreating builder =
        builder.RegisterOptionTypes() // enables option values for all entities
    
type TestDbContextFactory() =
    member this.CreateDbContext() =
        let options = new DbContextOptionsBuilder<AppDbContext>()
        options.UseNpgsql("connectionStringHere").UseFSharpTypes() |> ignore
        new AppDbContext(options.Options)
```
And a link to [the sample project](https://github.com/Mrjuanblack/testProject).

**Comment by MaceWindu** [comment]
We need to look into it, but looks like error is caused by use of `UseFSharpTypes` method. Without it linq2db cas parse query.

**Comment by Mrjuanblack** [comment]
Thanks for the response!
Do you know any workaround for using FSharpTypes?
What would be needed to fix that?
Having access to `Option` types would be really great. We could even use Linq2Db as the context directly if it means we can use them.

**Comment by MaceWindu** [comment]
I think have potential fix for this issue to `linq2db.EntityFrameworkCore`.

Still not clear why  `UseFSharpTypes` triggers this issue

**Comment by MaceWindu** [comment]
I suspect there is a bug on this line https://github.com/efcore/EFCore.FSharp/blob/a43b78c7833f9e9e346c5ff79c855e68620047bf/src/EFCore.FSharp/Translations/SingleCaseUnionTranslation.fs#L12

instead of instance it should return null, but I'm not an expert in EF.Core

**Comment by MaceWindu** [comment]
@sdanyliv could you comment on this?

**Comment by jannesiera** [comment]
@MaceWindu thank you for your support on this. Fixing this would definitely help us, implementing option types directly in linq2db (https://github.com/linq2db/linq2db/issues/195) would be even better. If that was the case we could drop EFCore and FSharp.EFCore altogether.

In that case we would be happy to build and open source a tool for generating migrations for code-first development (currently supported by EFCore but not by linq2db).

**Comment by MaceWindu** [comment]
We will ship workaround in linq2db.EntityFrameworkCore (this or next week). Regarding better F# support in general - I plan to look at it, but it will not happen earlier than October

**Comment by MaceWindu** [comment]
linq2db.EntityFrameworkCore  with fix released
