### ISSUE TITLE
Doesn't create a temporary table with the Clickhouse.Client provider

### ISSUE THREAD

**Issue by VitaliyNec** [linq2db/linq2db#3778]
Unhandled exception. ClickHouse.Client.ClickHouseServerException (0x00000071): Code: 113, e.displayText() = DB::Exception: There is no session or session context has expired (version 21.8.14.5 (official build))

   at ClickHouse.Client.ADO.ClickHouseConnection.HandleError(HttpResponseMessage response, String query)
   at ClickHouse.Client.ADO.ClickHouseCommand.PostSqlQueryAsync(String sqlQuery, CancellationToken token)
   at ClickHouse.Client.ADO.ClickHouseCommand.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryDataAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryDataAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.CreateTable`1.QueryAsync(IDataContext dataContext, String tableName, String serverName, String databaseName, String schemaName, String statementHeader, String statementFooter, DefaultNullable defaultNullable, TableOptions tableOptions, Cancella
tionToken token)
   at LinqToDB.TempTable`1.CreateAsync(IDataContext db, String tableName, String databaseName, String schemaName, String serverName, TableOptions tableOptions, CancellationToken cancellationToken)
   at LinqToDB.TempTable`1.CreateAsync(IDataContext db, String tableName, IEnumerable`1 items, BulkCopyOptions options, String databaseName, String schemaName, String serverName, TableOptions tableOptions, CancellationToken cancellationToken)

**Comment by MaceWindu** [comment]
You need to enable sessions in connection string as temporary tables require session and HTTP client doesn't use sessions by default. https://github.com/DarkWanderer/ClickHouse.Client/wiki/Connection-string
