### ISSUE TITLE
Association between Guid and string:System.InvalidOperationException: No coercion operator is defined between types 'System.Guid' and 'System.String'.

### ISSUE THREAD

**Issue by darkflame0** [linq2db/linq2db#3791]
```cs
      System.InvalidOperationException: No coercion operator is defined between types 'System.Guid' and 'System.String'.
         at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
         at LinqToDB.Linq.Builder.ExpressionBuilder.Equal(MappingSchema mappingSchema, Expression left, Expression right)
         at LinqToDB.Linq.Builder.AssociationHelper.CreateAssociationQueryLambda(ExpressionBuilder builder, AccessorMember onMember, AssociationDescriptor association, Type parentOriginalType, Type parentType, Type objectType, Boolean inline, Boolean enforceDefault, List`1 loadWith, Boolean& isLeft)
         at LinqToDB.Linq.Builder.AssociationHelper.BuildAssociationInline(ExpressionBuilder builder, BuildInfo buildInfo, TableContext tableContext, AccessorMember onMember, AssociationDescriptor descriptor, Boolean inline, Boolean& isOuter)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.FindContextExpression(Expression expression, Int32 level, Boolean forceInner, Boolean throwExceptionForNull)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
         at LinqToDB.Linq.Builder.DefaultIfEmptyBuilder.DefaultIfEmptyContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
         at LinqToDB.Linq.Builder.AssociationContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
         at LinqToDB.Linq.Builder.SelectContext.IsExpressionInternal(Expression expression, Int32 level, RequestFor requestFlag)
         at LinqToDB.Linq.Builder.SelectContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
         at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
         at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
         at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__93_0(ValueTuple`4 context, Expression expr)
         at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
         at LinqToDB.Expressions.ExpressionExtensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
         at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
         at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
         at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
         at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__93_0(ValueTuple`4 context, Expression expr)
         at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
         at LinqToDB.Expressions.ExpressionExtensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
         at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
         at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
         at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
         at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
         at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
         at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
         at LinqToDB.Linq.ExpressionQuery`1.GetAsyncEnumerator(CancellationToken cancellationToken)
```
I have an Association between Guid and string.
I have already set the converter but not working
```cs
            Converter.SetConverter<Guid, string>(a => a.ToString());
            Converter.SetConverter<string, Guid>(a => Guid.Parse(a));
```

**Comment by MaceWindu** [comment]
It is not clear what are you trying to do without sample query/model.

**Comment by darkflame0** [comment]
```cs
        Converter.SetConverter<Guid, string>(a => a.ToString());
        Converter.SetConverter<string, Guid>(a => Guid.Parse(a));
        var table = await db.CreateTempTableAsync<Test>();
        await db.CreateTempTableAsync<TestGuid>();
        await table.LoadWith(a => a.Association).ToListAsync();

        [Table(IsColumnAttributeRequired = false)]
        public class Test
        {
            [Identity]
            [PrimaryKey]
            public int Id { get; set; }
            public string? OtherId { get; set; }
            [Association(ThisKey = nameof(OtherId), OtherKey = nameof(TestGuid.Id))]
            public TestGuid? Association { get; set; }
        }
        [Table(IsColumnAttributeRequired = false)]
        public class TestGuid
        {
            [PrimaryKey]
            public Guid Id { get; set; }
        }
```
I think the above code should work.

Maybe there is a bug in
https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs#L1568
?

**Comment by darkflame0** [comment]
@MaceWindu Any progress? or my bad?

**Comment by MaceWindu** [comment]
Looked into it. There is indeed bug in `https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Builder/ExpressionBuilder.cs#L1568` logic.
`CanConvertTo` use `TypeDescriptor` to find possible conversions but it is not used by `Expression.Convert`

As workaround you can specify predicate explicitly for association https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Mapping/AssociationAttribute.cs#L68

**Comment by aloksharma1** [comment]
@MaceWindu this issue is back in new preview version, i have a few queries like this

```
using LinqToDB;
using Microsoft.Extensions.DependencyInjection;
using Ultra.Abstractions.Processors;
using Ultra.Services.Accessibility;

namespace Ultra.BlogModule.Core.Services.Implementations.SearchProviders
{
    [SingletonService(typeof(ISearchProvider))]
    public class GetBlogSearchQuery : ISearchProvider
    {
        public string GroupName { get; set; } = "PageGroup";
        public string Name { get; set; } = "Blogs";
        public int Order { get; set; } = -999;
        public IServiceProvider ServiceProvider { get; set; }
        public GetBlogSearchQuery(IServiceProvider serviceProvider)
        {
            ServiceProvider = serviceProvider;
        }
        public dynamic? GetSearchQuery(string? SearchTerm)
        {
            using (var scope = ServiceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                if (SearchTerm.IsNullOrWhiteSpace())
                {
                    return default;
                }
                return GetSearchQuery(SearchTerm, scope);
            }
        }

        public dynamic? GetSearchQuery(string? SearchTerm = null, IServiceScope? serviceScope = null)
        {
            if (SearchTerm.IsNullOrWhiteSpace() || serviceScope == null)
            {
                return default;
            }
            var provider = serviceScope.ServiceProvider;
            var service = provider.GetRequiredService<IAccountService>();
            var repository = provider.GetRequiredService<IRepository<BlogPostInfo, UltraDbContext>>();
            var _imageRepository = provider.GetRequiredService<IRepository<Images, UltraDbContext>>();
            var _blogImagesRepository = provider.GetRequiredService<IRepository<BlogPostImages, UltraDbContext>>();
            var _blogAuthorRepository = provider.GetRequiredService<IRepository<BlogAuthor, UltraDbContext>>();
            var _blogCategoryRepository = provider.GetRequiredService<IRepository<BlogCategory, UltraDbContext>>();
            var _blogTypeRepository = provider.GetRequiredService<IRepository<BlogTypes, UltraDbContext>>();
            var _pageRepository = provider.GetRequiredService<IRepository<Pages, UltraDbContext>>();
            var query = repository.Query()!
                .Where(x => x.SiteId == service.GetSiteId()
                && x.IsActive == true
                && (x.RecordStatus == RecordStatus.Published || (x.RecordStatus == RecordStatus.ScheduledPublished && x.PublishDate <= DateTimeOffset.UtcNow))
                && x.SearchStatus != SearchStatus.NotSearchable);
            if (SearchTerm.IsNotNullOrWhiteSpace())
            {
                query = query.Where(x => x.PageName!.Contains(SearchTerm!) ||
                x.MainCategoryId == _blogCategoryRepository.Query()!.Where(b => b.CategoryName!.Contains(SearchTerm!) && b.IsActive == true && b.SiteId == x.SiteId && b.CategoryBlogTypeId == x.BlogPostTypeId).Select(b => b.Id).FirstOrDefault());
            }
            var result = query.Select(x => new SearchResults
            {
                DateCreated = x.DateCreated,
                Id = "" + x.Id,
                Slug = x.PageSlugUrl,
                Title = x.PageName,
                Summary = x.PageSummary,
                Images = null,                
                Videos = null,
                Files = null,
                Htmls = null,
                Links = null,
                Category = _blogCategoryRepository.Query()!.Where(b => b.Id == x.MainCategoryId).Select(b => b.CategoryName).FirstOrDefault(),
                CategoryTrail = x.CategoryParentTrail,
                Type = _blogTypeRepository.Query()!.Where(b => b.Id == x.BlogPostTypeId).Select(b => b.Name).FirstOrDefault(),
                AuthorName = _blogAuthorRepository.Query()!.Where(ba => ba.Id == x.AuthorId).Select(ba => ba.PenName).FirstOrDefault(),
                AuthorProfile = _pageRepository.Query()!.Where(pa => pa.RecordStatus == RecordStatus.Published && pa.IsActive == true && pa.Id == _blogAuthorRepository.Query()!.Where(ba => ba.Id == x.AuthorId).Select(ba => ba.BioPageId).FirstOrDefault()).Select(pa => pa.PageSlugUrl).FirstOrDefault(),
                DatePublished = x.PublishDate,
                ResultOrder = -999,
                ProviderTable = "Blogs"
            });
            //.Where(x => x.SiteId == service.GetSiteId()
            //&& x.IsActive == true && x.PageName.StartsWith(SearchTerm) && x.RecordStatus == RecordStatus.Published
            //&& x.SearchStatus != SearchStatus.DisabledSearchable)
            return result;
        }
    }
}
```

which i use to union and show end result for search purposes. the code was working fine on previous version but on 8.2.0-rc.13787 its back.

**Comment by MaceWindu** [comment]
Create new issue with reduced test code

**Comment by aloksharma1** [comment]
> Create new issue with reduced test code

ok will make sample repo and issue
