### ISSUE TITLE
Expressions.MapMember string.Split not work in Select

### ISSUE THREAD

**Issue by darkflame0** [linq2db/linq2db#3807]
```cs
    public static partial class SqlFnEx
    {
        [Sql.TableExpression("string_split({2},{3}) {1}")]
        public static IQueryable<ValueWrapper<string>> StringSplit(string str, char delimiter)
        {
            return (str?.Split(delimiter, StringSplitOptions.None) ?? Array.Empty<string>()).Select(a => new ValueWrapper<string>() { Value = a }).AsQueryable();
        }
    }
    public record ValueWrapper<T>
    {
        public static PropertyInfo PropertyInfo { get; } = typeof(ValueWrapper<T>).GetProperty("Value");
        public T Value { get; set; }
    }
    public class TestDto
    {
        public int Id { get; set; }
        public int Value { get; set; }
        public IEnumerable<string>? Array { get; set; }
    }

    [Table(IsColumnAttributeRequired = false)]
    public class Test
    {
        [Identity]
        [PrimaryKey]
        public int Id { get; set; }
        public int Value { get; set; }
        public string? ArrayString { get; set; }
        [Association(QueryExpressionMethod = nameof(ArrayExpression))]
        public IEnumerable<string> Array { get; set; }
        private static Expression<Func<Test, IDataContext, IQueryable<string>>> ArrayExpression()
        {
            return (e, dc) => e.ArrayString.Split(',', StringSplitOptions.None).AsQueryable();
        }
    }

            LinqToDB.Linq.Expressions.MapMember<string, char, StringSplitOptions, IEnumerable<string>>(
                (a, b, c) => a.Split(b, c),
                (a, b, c) => SqlFnEx.StringSplit(a, b).Select(a => a.Value)
                );
            await db.DropTableAsync<Test>(tableOptions: TableOptions.DropIfExists);
            var table = await db.CreateTableAsync<Test>(tableOptions: TableOptions.CreateIfNotExists);
//not work
            await table.Select(a => new TestDto
            {
                Id = a.Id,
                Array = a.ArrayString.Split(',', StringSplitOptions.None)
            })
            .ToListAsync();
//work
            await table.Select(a => new TestDto
            {
                Id = a.Id,
                Array = a.Array
            })
            .ToListAsync();
//work
            await table.Select(a => new TestDto
            {
                Id = a.Id,
                Array = SqlFnEx.StringSplit(a.ArrayString, ',').Select(a => a.Value)
            })
            .ToListAsync();

```
correct sql (Not exactly,relates to #3806)
```sql
      SELECT
        [key_data_result].[ArrayString],
        [detail].[Value]
      FROM
        (
                SELECT DISTINCT
                        [a].[ArrayString]
                FROM
                        [Test] [a]
        ) [key_data_result]
                CROSS APPLY string_split([key_data_result].[ArrayString],N',') [detail]

      SELECT
        [a].[Id],
        [a].[ArrayString]
      FROM
        [Test] [a]
```
Incorrect sql (eval on client side)
```sql
      SELECT
        [a].[Id],
        [a].[ArrayString]
      FROM
        [Test] [a]
```

**Comment by MaceWindu** [comment]
linq2db prefers to move final calculations to client when possible. For extensions it is possible to override this behavior using `PreferServerSide`/`ServerSideOnly` flags, but `MapMember` doesn't have such functionality.

You can force server-side evaluation by wrapping member access with `Sql.AsSql(...)` method

**Comment by darkflame0** [comment]
```cs
await table.Select(a => new TestDto
            {
                Id = a.Id,
                Array = Sql.AsSql(a.ArrayString.Split(',', StringSplitOptions.None))
            })
            .ToListAsync();
```
```sql
      SELECT
        [a_1].[Id],
        (
                SELECT
                        [a].[Value]
                FROM
                        string_split([a_1].[ArrayString],N',') [a]
        )
      FROM
        [Test] [a_1]
```
```
Subquery returned more than 1 value. This is not permitted when the subquery follows =, !=, <, <= , >, >= or when the subquery is used as an expression.
```

**Comment by MaceWindu** [comment]
@sdanyliv, any idea?

**Comment by darkflame0** [comment]
```cs
            var table = await db.CreateTableAsync<Test>(tableOptions: TableOptions.CreateIfNotExists);
            await table.Select(a => new TestDto
            {
                Id = a.Id,
                Array = a.ArrayString.Split(',', StringSplitOptions.None)
            })
                .Where(a => a.Array.Any(a => a == "123"))
            .ToListAsync();
```
```
     LinqToDB.Linq.LinqException: Expression 'a.ArrayString.Split(,, None)' (a.ArrayString) is not a table.
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.FindContextExpression(Expression expression, Int32 level, Boolean forceInner, Boolean throwExceptionForNull)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.GetContext(Expression expression, Int32 level, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.TableBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.AllAnyBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr)
         at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryContext(IBuildContext context, MethodCallExpression expr)
         at LinqToDB.Linq.Builder.ExpressionBuilder.SubQueryToSql(IBuildContext context, MethodCallExpression expression)
         at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
         at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
         at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
         at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
         at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
         at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
         at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
         at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
         at WorkerService1.Worker.ExecuteAsync(CancellationToken stoppingToken) in D:\Source\Repos\Linq2dbTest\WorkerService1\Worker.cs:line 31
         at Microsoft.Extensions.Hosting.Internal.Host.TryExecuteBackgroundServiceAsync(BackgroundService backgroundService)
```

**Comment by MaceWindu** [comment]
There is no need to use Expression.MapMember, following mappings will be enough:

```cs
static partial class SqlFnEx
{
        // no need for TableExpression
	[Sql.TableFunction("STRING_SPLIT")]
	public static IQueryable<StringValue> StringSplit(string? str, char delimiter)
	{
		return (str?.Split(delimiter, StringSplitOptions.None).Select(e => new StringValue() { Value = e }) ?? Array.Empty<StringValue>()).AsQueryable();
	}
}

class StringValue
{
	// function returns column, named "value"
	[Column("value")] public string Value { get; set; } = null!;
}

[Table]
sealed class Test
{
	[PrimaryKey] public int Id { get; set; }
	[Column] public string? ArrayString { get; set; }

	[Association(QueryExpressionMethod = nameof(ArrayExpression))]
	public IEnumerable<string> Array { get; set; } = null!;

	private static Expression<Func<Issue3807Table, IDataContext, IQueryable<string>>> ArrayExpression()
	{
		return (e, dc) => SqlFnEx.StringSplit(e.ArrayString, ',').Select(r => r.Value);
	}
}
```

Array filter doesn't work, because you are accessing not mapped property `TestDto.Array` instead of `Test.Array`.
You need to apply filter before projection. In v6 you will be able to use projection type if it's property has mapping (not working in v5)
