### ISSUE TITLE
Operation is not valid due to the current state of the object

### ISSUE THREAD

**Issue by darkflame0** [linq2db/linq2db#3809]
sorry,my english is poor,I don't know what title to use to describe this issue.
```cs
        await db.DropTableAsync<Test>(tableOptions: TableOptions.DropIfExists);
        await db.DropTableAsync<TestChild>(tableOptions: TableOptions.DropIfExists);
        await db.DropTableAsync<TestItem>(tableOptions: TableOptions.DropIfExists);
        var table = await db.CreateTableAsync<Test>(tableOptions: TableOptions.CreateIfNotExists);
        await db.CreateTableAsync<TestChild>(tableOptions: TableOptions.CreateIfNotExists);
        await db.CreateTableAsync<TestItem>(tableOptions: TableOptions.CreateIfNotExists);
        await table.Select(a => new TestDto
        {
            Id = a.Id,
            Child =
            a.Child == null ? null : //if comment this line,sql successfully generated but final result is not I expected
            new TestChildDto()
            {
                Id = a.Child.Id,
                Items = a.Child.Items.Select(a => new TestItemDto()
                {
                    Id = a.Id,
                    Value = a.Value
                })
            }
        }
        )
        .Where(a => a.Child == null || a.Child.Items.Any())
        .ToListAsync();


        public class TestDto
        {
            public int Id { get; set; }
            public int Value { get; set; }
            public TestChildDto? Child { get; set; }
        }
        public class TestChildDto
        {
            public int Id { get; set; }
            public IEnumerable<TestItemDto> Items { get; set; }
        }

        [Table(IsColumnAttributeRequired = false)]
        public class TestItemDto
        {
            public int Id { get; set; }
            public int Value { get; set; }
        }

        [Table(IsColumnAttributeRequired = false)]
        public class Test
        {
            [Identity]
            [PrimaryKey]
            public int Id { get; set; }
            public int Value { get; set; }
            [Association(ThisKey = nameof(Id), OtherKey = nameof(TestChild.TestId))]

            public TestChild? Child { get; set; }
        }
        public class TestChild
        {
            [Identity]
            [PrimaryKey]
            public int Id { get; set; }
            public int TestId { get; set; }
            [Association(ThisKey = nameof(TestId), OtherKey = nameof(TestItem.AssociationKey))]
            public IEnumerable<TestItem> Items { get; set; }
        }

        [Table(IsColumnAttributeRequired = false)]
        public class TestItem
        {
            [Identity]
            [PrimaryKey]
            public int Id { get; set; }
            public int Value { get; set; }
            public int? AssociationKey { get; set; }
        }
```
```cs
      System.InvalidOperationException: Operation is not valid due to the current state of the object.
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.GetContext(Expression expression, Int32 level, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.SelectContext.GetContext(Expression expression, Int32 level, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.TableBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.AllAnyBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr)
         at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryContext(IBuildContext context, MethodCallExpression expr)
         at LinqToDB.Linq.Builder.ExpressionBuilder.SubQueryToSql(IBuildContext context, MethodCallExpression expression)
         at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
         at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
         at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
         at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
         at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
         at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
         at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
         at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
         at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
```

I use OData with DTO,so I can‘t code following
```cs
await table.Where(a => a.Child == null || a.Child.Items.Any()).Select(a => new TestDto
            {
                Id = a.Id,
                Child =
                a.Child == null ? null :
                new TestChildDto()
                {
                    Id = a.Child.Id,
                    Value = a.Child.Value,
                    Items = a.Child.Items.Select(a => new TestItemDto()
                    {
                        Id = a.Id,
                        Value = a.Value
                    })
                }
            }
            )
            .ToListAsync();

```

**Comment by darkflame0** [comment]
```cs
            await table.Select(a => new TestDto
            {
                Id = a.Id,
                Child =
                a.Child == null ? null :
                new TestChildDto()
                {
                    Id = a.Child.Id,
                    Value = a.Child.Value,
                    //Items = a.Child.Items.Select(a => new TestItemDto()
                    //{
                    //    Id = a.Id,
                    //    Value = a.Value
                    //})
                }
            }
            )
            .Where(a => a.Child != null)
            .ToListAsync();
```
if not include items,The correct sql is generated.
```sql
      SELECT
        [a].[Id],
        [a_Child].[Id],
        [a_Child].[Value]
      FROM
        [Test] [a]
                LEFT JOIN [TestChild] [a_Child] ON [a].[Id] = [a_Child].[TestId]
      WHERE
        ([a_Child].[Id] IS NOT NULL OR [a_Child].[Value] IS NOT NULL)
```


```cs
            await table.Select(a => new TestDto
            {
                Id = a.Id,
                Child =
                a.Child == null ? null :
                new TestChildDto()
                {
                    Id = a.Child.Id,
                    Value = a.Child.Value,
                    Items = a.Child.Items.Select(a => new TestItemDto()
                    {
                        Id = a.Id,
                        Value = a.Value
                    })
                }
            }
            )
            .Where(a => a.Child != null && a.Child.Value != 0)
            .ToListAsync();
```
otherwise, "a.Child != null" is ignored and not filtered on client side
```sql
      SELECT
        [key_data_result].[Id],
        [detail].[Id],
        [detail].[Value]
      FROM
        (
                SELECT DISTINCT
                        [a_Child].[Id]
                FROM
                        [Test] [a]
                                LEFT JOIN [TestChild] [a_Child] ON [a].[Id] = [a_Child].[TestId]
        ) [key_data_result]
                INNER JOIN [TestItem] [detail] ON [key_data_result].[Id] = [detail].[AssociationKey]

      SELECT
        [a].[Id],
        [a_Child].[Id],
        [a_Child].[Value]
      FROM
        [Test] [a]
                LEFT JOIN [TestChild] [a_Child] ON [a].[Id] = [a_Child].[TestId]
```

**Comment by darkflame0** [comment]
if not include items,The correct sql is generated.
```cs
            await table.Select(a => new TestDto
            {
                Id = a.Id,
                Child =
                a.Child == null ? null :
                new TestChildDto()
                {
                    Id = a.Child.Id,
                    Value = a.Child.Value,
                    //Items = a.Child.Items.Select(a => new TestItemDto()
                    //{
                    //    Id = a.Id,
                    //    Value = a.Value
                    //})
                }
            }
            )
            .Where(a => a.Child != null)
            .ToListAsync();
```
```sql
      SELECT
        [a].[Id],
        [a_Child].[Id],
        [a_Child].[Value]
      FROM
        [Test] [a]
                LEFT JOIN [TestChild] [a_Child] ON [a].[Id] = [a_Child].[TestId]
      WHERE
        ([a_Child].[Id] IS NOT NULL OR [a_Child].[Value] IS NOT NULL)
```

otherwise, "a.Child != null" is ignored and not filtered on client side
```cs
            await table.Select(a => new TestDto
            {
                Id = a.Id,
                Child =
                a.Child == null ? null :
                new TestChildDto()
                {
                    Id = a.Child.Id,
                    Value = a.Child.Value,
                    Items = a.Child.Items.Select(a => new TestItemDto()
                    {
                        Id = a.Id,
                        Value = a.Value
                    })
                }
            }
            )
            .Where(a => a.Child != null)
            .ToListAsync();
```
```sql
      SELECT
        [key_data_result].[Id],
        [detail].[Id],
        [detail].[Value]
      FROM
        (
                SELECT DISTINCT
                        [a_Child].[Id]
                FROM
                        [Test] [a]
                                LEFT JOIN [TestChild] [a_Child] ON [a].[Id] = [a_Child].[TestId]
        ) [key_data_result]
                INNER JOIN [TestItem] [detail] ON [key_data_result].[Id] = [detail].[AssociationKey]

      SELECT
        [a].[Id],
        [a_Child].[Id],
        [a_Child].[Value]
      FROM
        [Test] [a]
                LEFT JOIN [TestChild] [a_Child] ON [a].[Id] = [a_Child].[TestId]
```
