### ISSUE TITLE
Global `SetConverter` for struct does not work for Insert

### ISSUE THREAD

**Issue by timbze** [linq2db/linq2db#3815]
### Describe your issue

Using the global `SetConverter` for struct does not work for the Insert extension. Here's a minimal repro in .NET 7 RC2 and Linq2Db 4.3.0 :

```csharp
using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

var linqToDbBuilder = new LinqToDBConnectionOptionsBuilder();
linqToDbBuilder.UsePostgreSQL("Server=localhost;Port=5432;Database=pgtest;User Id=postgres; Password=password;");
MappingSchema.Default.SetConverter<DataId,string>(d => d.Value);
MappingSchema.Default.SetConverter<string,DataId>(s => DataId.From(s));

var context = new DbContext(new LinqToDBConnectionOptions(linqToDbBuilder));

// read data works
var poco = context.GetPoco.First(i => i.TheDataId.Equals("something else"));
Console.WriteLine($"The DataId is {poco.TheDataId.Value}");

// insert does NOT work
context.Insert(new Poco {TheDataId = DataId.From("something else2")});
// crash

public sealed class DbContext : DataConnection
{
    public DbContext(LinqToDBConnectionOptions options) : base(options) {}
    public ITable<Poco> GetPoco => this.GetTable<Poco>();
}

public record Poco
{
    public DataId TheDataId { get; set; }
}

public readonly struct DataId
{
    public string Value { get; init; }
    public static DataId From(string value) => new() {Value = value};
}
```

**Exception**:
```
**Exception message**: Unhandled exception. System.NotSupportedException: The CLR type DataId isn't natively supported by Npgsql or your PostgreSQL. To use it with a PostgreSQL composite you need to specify DataTypeName or to map it, please refer to the documentation.
**Stack trace**:
   at Npgsql.TypeMapping.ConnectorTypeMapper.ResolveByClrType(Type type)
   at Npgsql.NpgsqlParameter.ResolveHandler(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlParameter.Bind(ConnectorTypeMapper typeMapper)
   at Npgsql.NpgsqlParameterCollection.ProcessParameters(ConnectorTypeMapper typeMapper, Boolean validateValues)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery(DbCommand command)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryImpl(DataConnection dataConnection, ExecutionPreparedQuery executionQuery)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQuery()
   at LinqToDB.Linq.QueryRunner.NonQueryQuery(Query query, IDataContext dataContext, Expression expr, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass31_0.<SetNonQueryQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.Insert`1.Query(IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String serverName, String databaseName, String schemaName, TableOptions tableOptions)
   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, InsertColumnFilter`1 columnFilter, String tableName, String databaseName, String schemaName, String serverName, TableOptions tableOptions)
   at LinqToDB.DataExtensions.Insert[T](IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, String serverName, TableOptions tableOptions)
   at Program.<Main>$(String[] args) in /home/timmy/Repos/Tmp/LinqToDB_NET7_Repro/LinqToDB_NET7_Repro/Program.cs:line 15
```

### Environment details

`Linq To DB` version: *4.3.0*

Database (with version): *PostgreSQL 14*

Operating system: *Ubuntu 22.04*

.NET Version: *7.0 RC2*

**Comment by jogibear9988** [comment]
You need 3 converters:

Sample:

            mappingSchema.SetConverter<List<string>, string>((obj) => obj == null ? null : StringSerializer.JsonNetSerialize(obj, false));
            mappingSchema.SetConverter<List<string>, DataParameter>((obj) => obj == null ? new DataParameter { DataType = DataType.VarChar, Value = DBNull.Value } : new DataParameter { Value = StringSerializer.JsonNetSerialize(obj, false) });
            mappingSchema.SetConverter<string, List<string>>((txt) => txt == null ? null : StringSerializer.JsonNetDeSerialize<List<string>>(txt));

**Comment by timbze** [comment]
> You need 3 converters

I don't understand. How would that look with my struct?

BTW, this ValueConverter works (I filed this issue because I would like a solution that I don't need to add an attribute to every property that uses the type):
```csharp
[Column]
[ValueConverter(ConverterType = typeof(DataId.LinqToDbValueConverter))]
public DataId TheDataId { get; set; }

public class LinqToDbValueConverter : LinqToDB.Common.ValueConverter<DataId, string>
{
    public LinqToDbValueConverter()
        : base(
              v => v.Value,
              p => DataId.From(p),
              handlesNulls: false)
    { }
}
```

**Comment by viceroypenguin** [comment]
note the `SetConverter<DataId, DataParameter>()` call

```csharp
using LinqToDB;
using LinqToDB.Configuration;
using LinqToDB.Data;
using LinqToDB.Mapping;

var ms = new MappingSchema();
ms.SetConverter<DataId, string>(d => d.Value);
ms.SetConverter<DataId, DataParameter>(d => new DataParameter { DataType = DataType.VarChar, Value = d.Value, });
ms.SetConverter<string, DataId>(s => DataId.From(s));

var linqToDbBuilder = new LinqToDBConnectionOptionsBuilder();
linqToDbBuilder
		.UsePostgreSQL("Server=172.16.31.6;Port=5432;Database=pgtest;User Id=postgres; Password=Pazzword_11;")
		.UseMappingSchema(ms);
var context = new DbContext(new LinqToDBConnectionOptions(linqToDbBuilder));

// read data works
var poco = context.GetPoco.First(i => i.TheDataId.Equals("something else"));
Console.WriteLine($"The DataId is {poco.TheDataId.Value}");

// insert does work now
context.Insert(new Poco { TheDataId = DataId.From("something else2") });

public sealed class DbContext : DataConnection
{
	public DbContext(LinqToDBConnectionOptions options) : base(options) { }
	public ITable<Poco> GetPoco => this.GetTable<Poco>();
}

public record Poco
{
	public DataId TheDataId { get; set; }
}

public readonly struct DataId
{
	public string Value { get; init; }
	public static DataId From(string value) => new() { Value = value };
}
```

**Comment by timbze** [comment]
> note the `SetConverter<DataId, DataParameter>()` call

Oh, I got it now, and it works! Thank you!
