### ISSUE TITLE
Clickhouse. Translation exception throws if DistinctBy is used.

### ISSUE THREAD

**Issue by MaxLevs** [linq2db/linq2db#3816]
### Describe your issue

I use linq2db to select data from clickhouse tables.
I was tring to use distinctby method to get unique rows.

E.X. `conn.GetTable<StatisticTableRow>().DistinctBy(x => x.CallUUID).Select(x => x.CallUUID);`
But this line throws exception

```
LinqToDB.Linq.LinqException: Sequence 'value(LinqToDB.Data.DataConnection).GetTable().DistinctBy(x => x.CallUUID)' cannot be converted to SQL.
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertSequence(BuildInfo buildInfo, ParameterExpression param, Boolean throwExceptionIfCantConvert)
   at LinqToDB.Linq.Builder.SelectBuilder.Convert(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo, ParameterExpression param)
   at LinqToDB.Linq.Builder.MethodCallBuilder.Convert(ExpressionBuilder builder, BuildInfo buildInfo, ParameterExpression param)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertSequence(BuildInfo buildInfo, ParameterExpression param, Boolean throwExceptionIfCantConvert)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressionTree(Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder..ctor(Query query, ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expression, ParameterExpression[] compiledParameters)
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at POMCampaignCallManager.Logic.Repositories.ClickHouse.CallStatisticsRepository.GetOperatorCallsForDay(Int32 operatorId, DateTime fromDate, CancellationToken cancellationToken) in C:\Users\mliven\source\POM_Repos\Pom-Service-CallManager\POMCampaignCallManager.Logic\Repositories\ClickHouse\CallStatisticsRepository.cs:line 41
   at POMCampaignCallManager.Program.RunTestAsync(IHost app) in C:\Users\mliven\source\POM_Repos\Pom-Service-CallManager\POMCampaignCallManager\Program.cs:line 75
   at System.Threading.Tasks.Task.<>c.<ThrowAsync>b__128_1(Object state)
   at System.Threading.QueueUserWorkItemCallbackDefaultContext.Execute()
   at System.Threading.ThreadPoolWorkQueue.Dispatch()
   at System.Threading.PortableThreadPool.WorkerThread.WorkerThreadStart()
   at System.Threading.Thread.StartCallback()
```

### Steps to reproduce

1. Create table in clickhouse.
2. Try to get unique value with .DistinctBy() method by some column.
3. Use select to get specific columns from db.

### Environment details

`Linq To DB` version: *4.3.0*

Database (with version): *ClickHouse 22.1.3.7*
ADO.NET Provider (with version): *Clickhouse.Client 6.1.0*

Operating system: *Windows 10*

.NET Version: *6.0.0*

**Comment by MaceWindu** [comment]
`DistinctBy` (and other new `*By` operations) not supported yet https://github.com/linq2db/linq2db/issues/2977
