### ISSUE TITLE
How to make grouping with value from ExtendedProperties?

### ISSUE THREAD

**Issue by VitaliyNec** [linq2db/linq2db#3859]
.NET 7
ProviderName: ClickHouse.Client
```cs
var ms = MappingSchema.Default;
var fm = ms.GetFluentMappingBuilder();
fm.Entity<MyClass>().DynamicColumnsStore(x => new ColumnAttribute("All", "All"));

var result = db.MyClass()
    .Select(x => new
    {
        Value1 = x.ExtendedProperties["All"],
        Value2 = x.SomeField
    })
    .ToArray();

// OK!
```
```cs
var result = db.MyClass()
    .Select(x => new
    {
        Value1 = x.ExtendedProperties["All"],
        Value2 = x.SomeField
    })
    .GroupBy(x => x.Value1,
        (g, e) => new
        {
            Value1 = g,
            Value2 = e.Count()
        })
    .ToArray();

//Fail!
```
```
LinqToDB.Linq.LinqException: 'x.ExtendedProperties.get_Item("All")' cannot be converted to SQL.
at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag, ColumnDescriptor columnDescriptor)
at LinqToDB.Linq.Builder.SelectContext.ConvertExpressions(Expression expression, ConvertFlags flags, ColumnDescriptor columnDescriptor)
at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags)
at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
at LinqToDB.Linq.Builder.SelectContext.<>c.<ConvertToSql>b__42_0(ValueTuple`3 context, IBuildContext ctx, Expression ex, Int32 l)
at LinqToDB.Linq.Builder.SelectContext.ProcessScalar[T,TContext](TContext context, Expression expression, Int32 level, Func`5 action, Func`2 defaultAction, Boolean throwOnError)
at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
at LinqToDB.Linq.Builder.GroupByBuilder.KeyContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag, ColumnDescriptor columnDescriptor)
at LinqToDB.Linq.Builder.GroupByBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
at LinqToDB.Linq.Builder.SelectBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
at ClickHouseTest.ClickHouseQueryExecutor.Execute() in D:\repos\s1mpl\ClickHouseTest\ClickHouseTest\ClickHouseQueryExecutor.cs:line 39
at Program.<Main>$(String[] args) in D:\repos\s1mpl\ClickHouseTest\ClickHouseTest\Program.cs:line 11
at Program.<Main>(String[] args)
```

**Comment by sdanyliv** [comment]
Have you tried `Value1 = Sql.Property<string>(x, "All")` ?

**Comment by VitaliyNec** [comment]
"All" is an extra column in the model that is not present in the database table so you get the error 'No column 'x.All' in table 'x'. "All"

**Comment by MaceWindu** [comment]
It doesn't make sense to me. First example works because access to `ExtendedProperties` moved to client mapper. Second example cannot do it and cannot convert it to sql as All property is not defined.
You can add `.AsEnumerable()` before `GroupBy` to make it work on client too if this is what you want to achieve
