### ISSUE TITLE
linq2db.cli: "T4 compilation failed"

### ISSUE THREAD

**Issue by zh4ui** [linq2db/linq2db#3896]
### Describe your issue

When executing a command like `dotnet linq2db scaffold -i config.json` (config.json has a tt template specified), the following error was encountered:

```
T4 compilation failed:
        error CS0009: Metadata file 'C:\Program Files\dotnet\shared\Microsoft.NETCore.App\7.0.1\System.IO.Compression.Native.dll' could not be opened -- PE image doesn't contain managed metadata.
Unhandled exception: Object reference not set to an instance of an object.
   at LinqToDB.CommandLine.ScaffoldCommand.CompileTemplateAndLoadAssembly(String templateCode, IReadOnlyCollection`1 references, IReadOnlyCollection`1 imports)
   at LinqToDB.CommandLine.ScaffoldCommand.LoadInterceptorsFromT4(String t4templatePath, ScaffoldOptions options)
   at LinqToDB.CommandLine.ScaffoldCommand.LoadInterceptors(String interceptorsPath, ScaffoldOptions options)
   at LinqToDB.CommandLine.ScaffoldCommand.Execute(CliController controller, String[] rawArgs, Dictionary`2 options, IReadOnlyCollection`1 unknownArgs)
   at LinqToDB.CommandLine.CliController.Execute(String[] args)
   at LinqToDB.Tools.Program.Main(String[] args)
```

### Steps to reproduce

`dotnet tool install  -g linq2db.cli`

Tested with linq2db.cli version 4.4 or 4.3, the same problem occured.

`dotnet --list-runtimes` shows

```
Microsoft.AspNetCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.NETCore.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.NETCore.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.NETCore.App]
Microsoft.WindowsDesktop.App 6.0.12 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
Microsoft.WindowsDesktop.App 7.0.1 [C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App]
```

### Environment details

`Linq To DB` version: *?*

Database (with version): *?* (e.g. SQL Server 2019)

ADO.NET Provider (with version): *?* (e.g. Microsoft.Data.SqlClient 4.1.0)

Operating system: *?*

.NET Version: *?*

**Comment by MaceWindu** [comment]
Could you provide your template?

**Comment by zh4ui** [comment]
Might not be a problem of the template. 
I haven't changed the template. Previously it was working fine.
But after I upgrade to .NET 7 and have some servicing updates on .NET6, it fails to work with .NET 7 and .NET 6.
