### ISSUE TITLE
"The method or operation is not implemented." with such a design "== null ? null :"

### ISSUE THREAD

**Issue by KohanovFedor** [linq2db/linq2db#3901]
### Describe your issue

I am creating a DTO class using the Master.Tool library. This is the auto-generation of the code. In the resulting code there are constructions of the type "Value = p7.Value == null ? null : new ReferenceDto()". At this point LinqToDB gets the error: "The method or operation is not implemented". If you remove the NULL check, then everything works fine. I also noticed that this error appears in nested classes. I.e., when requesting an Image, it will work well. If you request Citizenship, there will be an error. The request is made via Graph using the HotChocolate library.

```
Exception message: The method or operation is not implemented.
Stack trace: "   at LinqToDB.Linq.Builder.EagerLoading.GenerateDetailsExpression(IBuildContext context, MappingSchema mappingSchema, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetMultipleQueryExpression(IBuildContext context, MappingSchema mappingSchema, Expression expression, HashSet`1 parameters, Boolean& isLazy)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildMultipleQuery(IBuildContext context, Expression expression, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__94_0(ValueTuple`4 context, Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__94_0(ValueTuple`4 context, Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__94_0(ValueTuple`4 context, Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.IEnumerable.GetEnumerator()
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.<>c__DisplayClass58_0.<ExecuteResolverPipelineAsync>b__0()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__272_0(Object obj)
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.ExecuteResolverPipelineAsync(CancellationToken cancellationToken)
   at HotChocolate.Execution.Processing.Tasks.ResolverTask.TryExecuteAsync(CancellationToken cancellationToken)"
```

```c#
[UseProjection]
public IQueryable<StaffEmployeeDto> GetEmployees(
            [Service] AppDataConnection connection,
            [Service] StaffEmployeeMapper staffEmployeeMapper)
            => connection.Entities<StaffEmployee>().Select(staffEmployeeMapper.StaffEmployeeProjection);
```

### Environment details

`Linq To DB` version: *4.4.0*

Database (with version): *PostgreSQL 14*

Provider (with version): *Npgsql 7.0.1*

Operating system: *MS Windows 10*

.NET Version: *NET 6*
[Error in Linq2db.zip](https://github.com/linq2db/linq2db/files/10380233/Error.in.Linq2db.zip)

**Comment by MaceWindu** [comment]
Could be another case of #3148 where library use Default expression.

**Comment by MaceWindu** [comment]
It's not `DefaultExpression` but still something in expression generated in a way we don't expect. To proceed with this issue we will need sample code, that reproduce this issue.

**Comment by MaceWindu** [comment]
We cannot proceed with this issue without additional details on which query fails and how to setup it.
