### ISSUE TITLE
How to append `FOR UPDATE/SHARE` hint to the end of SQL with mysql

### ISSUE THREAD

**Issue by n0099** [linq2db/linq2db#3905]
### Describe your issue

I've discovered https://github.com/linq2db/linq2db/issues/1276 and https://github.com/linq2db/linq2db/pull/3297, the latter pr introduced a way to add comment based query hints and prepend/append some texts into SQL

### Steps to reproduce

Providing
```c#
db.Set<SomeEntity>.QueryHint("FOR UPDATE").ToLinqToDB().ToList();
```
will execute the following SQL:
```sql
SELECT /*+ FOR UPDATE */
	`t1`.`someField`
FROM
	`SomeEntity` `t1`
```
it's expected since query hints is just comments.
But what I want is [`SELECT ... FOR UPDATE` syntax](https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html), so I tried
```c#
db.Set<SomeEntity>.AsPostgreSQL().ForUpdateHint().ToLinqToDB().ToList();
```
it will just throw an exception:
```log
System.ArgumentException: 'must be reducible node'
   at System.Linq.Expressions.Expression.ReduceAndCheck()
   at System.Linq.Expressions.Expression.ReduceExtensions()
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExtensionExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.Add(Expression expression)
   at System.Linq.Expressions.Compiler.StackSpiller.ChildRewriter.AddArguments(IArgumentProvider expressions)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteMethodCallExpression(Expression expr, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpression(Expression node, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.RewriteExpressionFreeTemps(Expression expression, Stack stack)
   at System.Linq.Expressions.Compiler.StackSpiller.Rewrite[T](Expression`1 lambda)
   at System.Linq.Expressions.Expression`1.Accept(StackSpiller spiller)
   at System.Linq.Expressions.Compiler.LambdaCompiler.Compile(LambdaExpression lambda)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.EvaluateExpression(Expression expr)
   at System.Linq.Enumerable.SelectIListIterator`2.ToArray()
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.<>c__DisplayClass39_0.<TransformExpression>g__LocalTransform|0(Expression e)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.ExpressionExtensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.TransformExpression(Expression expression, IDataContext dc, DbContext ctx, IModel model)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.TransformExpression(Expression expression, IDataContext dc, DbContext ctx, IModel model)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsDataConnection.ProcessExpression(Expression expression)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```
and I can't do
```c#
db.Set<SomeEntity>.AsMySql().ForUpdateHint().ToLinqToDB().ToList();
```
since`'IMySqlSpecificQueryable<SomeEntity>' does not contain a definition for 'ForUpdateHint'`

Did I miss something?

### Environment details

`Linq To DB` version: linq2db 4.4.0 linq2db.EntityFrameworkCore 6.11.0

Database (with version): MySQL 8.0.31

ADO.NET Provider (with version): MySqlConnector 2.2.2

Operating system: Windows 8.1

.NET Version: 6.0

**Comment by MaceWindu** [comment]
@igor-tkachev, looks like we miss API for those hints https://dev.mysql.com/doc/refman/8.0/en/innodb-locking-reads.html

**Comment by n0099** [comment]
MariaDB supports the [legacy syntax](https://mariadb.com/kb/en/lock-in-share-mode/) of `FOR SHARE` and [`FOR UPDATE`](https://mariadb.com/kb/en/for-update/)
