### ISSUE TITLE
Asp.Net DI using `NpgsqlDataSourceBuilder` and `.UseConnectionFactory` is not working

### ISSUE THREAD

**Issue by timbze** [linq2db/linq2db#3915]
### Describe your issue

I'm trying to set up my .NET 7.0 project with Linq2db 5.0.0 preview 1 but it's not working.

It crashes with: `Connection string is not provided.`

When I uncomment the `.UsePostgreSQL` line then it works, but NodaTime does not work so it's obvious that it is not using the connection factory from the data source builder that I tried setting up.

What am I doing wrong?

```csharp
var dsBuilder = new NpgsqlDataSourceBuilder(connectionString);
dsBuilder.UseNodaTime();
var ds = dsBuilder.Build();

var ms = new MappingSchema();
ms.AddMetadataReader(new SnakeCaseNamingConventionMetadataReader());

services.AddLinqToDBContext<IDbContext, DbContext>((serviceProvider, opt) =>
{
    return opt
        .UseConnectionFactory(PostgreSQLTools.GetDataProvider(), ds.CreateConnection)
        // .UsePostgreSQL(connectionString)
        .UseMappingSchema(ms)
        .UseDefaultLogging(serviceProvider);
});
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Stack trace:
Unhandled exception. System.InvalidOperationException: Connection string is not provided.
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLProviderDetector.<GetDataProvider>g__AutoDetectProvider|7_0(<>c__DisplayClass7_0&)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLProviderDetector.GetDataProvider(Provider provider, PostgreSQLVersion version, String connectionString)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.GetDataProvider(PostgreSQLVersion version, String connectionString)
   at Infra.Database.ConfigureServices.<>c__DisplayClass0_0.<AddDatabaseServices>b__0(IServiceProvider serviceProvider, DataOptions opt) in /home/timmy/Repos/App/src/Infra.Database/ConfigureServices.cs:line 38
   at LinqToDB.AspNet.ServiceConfigurationExtensions.<>c__DisplayClass2_0`2.<AddLinqToDBContext>b__1(IServiceProvider provider)
```

### Environment details

`Linq To DB` version: *5.0.0 preview 1*

Database (with version): *PostgreSQL 14.5*

Operating system: *Ubuntu 22.04*

.NET Version: *7.0*

**Comment by timbze** [comment]
Oh, that makes sense. What you suggested works, and it actually also works to set the provider and then the connection string is not needed.

Thank you!
