### ISSUE TITLE
Error in sql generation

### ISSUE THREAD

**Issue by nikitam** [linq2db/linq2db#3926]
**Problem descr**
The problem root is: when I add in LoadWith attributes any attribute from Where clause LoadWith does'nt work correctly.

**Steps to reproduce**
For internal purposes I have inheritance in domain objects:
```c#
public abstract class BaseDataObject
{
	public abstract bool IsNew { get; }
}

public abstract class GuidDataObject: BaseDataObject
{
	public Guid Id { get; internal set; }

	protected GuidDataObject()
	{
		Id = Guid.Empty;
	}

	public override bool IsNew => Id == Guid.Empty;
}

public class CALL_META : GuidDataObject
{
    // a lot of simple scalar attributes

    public CALL_RECORD? CallRecord { get; set; }
    public CALL_TRANSCRIPTION? CallTranscription { get; set; }

    public Guid? DialogCategoryId { get; set; }
    public DIALOG_CATEGORY DialogCategory { get; set; }
}

public class DIALOG_CATEGORY: GuidDataObject
{
    public string Category { get; set; }

    public Guid CategoryGroupId { get; set; }

    public CATEGORY_GROUP CategoryGroup { get; set; }
}

public class CATEGORY_GROUP: GuidDataObject
{
    public string GroupIcon { get; set; }

    public string TelegramBotName { get; set; }

    public List<DIALOG_CATEGORY> Categories { get; set; }
}
```

Also I have fluent mappings:
```c#
private static EntityMappingBuilder<T> MapDataObject<T>(FluentMappingBuilder builder, string tableName)
	where T : GuidDataObject
{
	return builder.Entity<T>()
		.HasTableName(tableName)
		.HasPrimaryKey(x => x.Id)
		.Ignore(x => x.IsNew);
}

private static MappingSchema GetShema()
{
	var result = new MappingSchema();
	var builder = new FluentMappingBuilder(result);

	// other entities

	MapDataObject<CATEGORY_GROUP>(builder, "t_category_groups")
		.Property(x => x.Id).HasColumnName("Id").HasDataType(DataType.Guid)
		.Property(x => x.TelegramBotName).HasColumnName("TelegramBotName")
		.Property(x => x.GroupIcon).HasColumnName("GroupIcon")
		.Association(x => x.Categories, x => x.Id, x => x.CategoryGroupId);

	MapDataObject<DIALOG_CATEGORY>(builder, "t_dialog_categories")
		.Property(x => x.Id).HasColumnName("Id").HasDataType(DataType.Guid)
		.Property(x => x.Category).HasColumnName("Category")
		.Property(x => x.CategoryGroupId).HasColumnName("CategoryGroupId").HasDataType(DataType.Guid)
		.Association(x => x.CategoryGroup, x => x.CategoryGroupId, x => x.Id);

	MapDataObject<CALL_META>(builder, "t_call_metas")
		.Property(x => x.Id).HasColumnName("Id").HasDataType(LinqToDB.DataType.Guid)
		// a lot of simple scalar fields
		.Association(x => x.CallRecord, x => x.Id, x => x.Id)
		.Association(x => x.CallTranscription, x => x.Id, x => x.Id)
		.Association(x => x.DialogCategory, x => x.DialogCategoryId, x => x.Id);
	return result;
}
```
Query:
```c#
var dataConnection = ExecutionContext.As<DataConnection>();
var calls = await dataConnection.GetTable<CALL_META>()
	.Where(x => x.ProfileId == query.ProfileId && x.StartDateUtc >= from 
	                                           && x.DialogCategory != null 
	                                           && x.DialogCategory.CategoryGroup.TelegramBotName == query.Category
	                                           && x.Decision == DecisionOption.Bot)
	.LoadWith(x => x.DialogCategory.CategoryGroup)
	.LoadWith(x => x.CallTranscription)
	.LoadWith(x => x.CallRecord)
	.OrderByDescending(x => x.StartDateUtc).Take(query.Count).ToListAsync();
```
So we can see that **Where clause contains conditions on the same attributes in LoadWith clause**

After query I have checked "LastQuery" DataConnection property:
```sql
SELECT
	x."Id",
        ... // a lot of scalar attrs
	"a_DialogCategory"."Id",
	"a_DialogCategory"."CategoryGroupId",
	"a_DialogCategory"."Category",
	"a_CallTranscription"."Id",
	"a_CallTranscription"."CreateDateUtc",
	"a_CallTranscription"."Summary",
	"a_CallTranscription"."Text",
	"a_CallRecord"."Id",
	"a_CallRecord"."UpdateDateUtc",
	"a_CallRecord"."CreateDateUtc",
	"a_CallRecord"."IsListened",
	"a_CallRecord"."AudioMetaLink",
	"a_CallRecord"."FileSize",
	"a_CallRecord"."FileLink",
	"a_CallRecord"."FileName"
FROM
	t_call_metas x
		LEFT JOIN t_dialog_categories "a_DialogCategory" ON x."DialogCategoryId" = "a_DialogCategory"."Id"
		LEFT JOIN t_category_groups "a_CategoryGroup" ON "a_DialogCategory"."CategoryGroupId" = "a_CategoryGroup"."Id"
		LEFT JOIN t_call_transcriptions "a_CallTranscription" ON x."Id" = "a_CallTranscription"."Id"
		LEFT JOIN t_call_records "a_CallRecord" ON x."Id" = "a_CallRecord"."Id"
WHERE
	x."ProfileId" = :ProfileId AND
	x."StartDateUtc" >= :from_1 AND
	"a_DialogCategory"."Id" IS NOT NULL AND
	"a_CategoryGroup"."TelegramBotName" = :Category AND
	x."Decision" = 6
ORDER BY
	x."StartDateUtc" DESC
LIMIT :take
```
there is no "a_CategoryGroup" table in SELECT clause. If I change query like this **Where clause does'nt contain conditions on the same attributes in LoadWith clause**: 
```c#
var calls = await dataConnection.GetTable<CALL_META>()
	.Where(x => x.ProfileId == query.ProfileId && x.StartDateUtc >= from 
	                                           // && x.DialogCategory != null 
	                                           // && x.DialogCategory.CategoryGroup.TelegramBotName == query.Category
	                                           && x.Decision == DecisionOption.Bot)
	.LoadWith(x => x.DialogCategory.CategoryGroup)
	.LoadWith(x => x.CallTranscription)
	.LoadWith(x => x.CallRecord)
	.OrderByDescending(x => x.StartDateUtc).Take(query.Count).ToListAsync();
```
I got correct sql
```sql
SELECT
	x."Id",
        ... // a lot of scalar attrs
	"a_DialogCategory"."Id",
	"a_DialogCategory"."CategoryGroupId",
	"a_DialogCategory"."Category",
        // now we have a_CategoryGroup
	"a_CategoryGroup"."Id",
	"a_CategoryGroup"."TelegramBotName",
	"a_CategoryGroup"."GroupIcon",
	"a_CallTranscription"."Id",
	"a_CallTranscription"."CreateDateUtc",
	"a_CallTranscription"."Summary",
	"a_CallTranscription"."Text",
	"a_CallRecord"."Id",
	"a_CallRecord"."UpdateDateUtc",
	"a_CallRecord"."CreateDateUtc",
	"a_CallRecord"."IsListened",
	"a_CallRecord"."AudioMetaLink",
	"a_CallRecord"."FileSize",
	"a_CallRecord"."FileLink",
	"a_CallRecord"."FileName"
FROM
	t_call_metas x
		LEFT JOIN t_dialog_categories "a_DialogCategory" ON x."DialogCategoryId" = "a_DialogCategory"."Id"
		LEFT JOIN t_category_groups "a_CategoryGroup" ON "a_DialogCategory"."CategoryGroupId" = "a_CategoryGroup"."Id"
		LEFT JOIN t_call_transcriptions "a_CallTranscription" ON x."Id" = "a_CallTranscription"."Id"
		LEFT JOIN t_call_records "a_CallRecord" ON x."Id" = "a_CallRecord"."Id"
WHERE
	x."ProfileId" = :ProfileId AND x."StartDateUtc" >= :from_1 AND
	x."Decision" = 6
ORDER BY
	x."StartDateUtc" DESC
LIMIT :take

```
What am I doing wrong?

### Environment details

`Linq To DB` version: *4.4.0*

Database: *Postgresql 14* 

ADO.NET Provider (with version): *Npgsql 7.0.1*

Operating system: *Windows 10 / Debian*

.NET Version: 7.0.101
C:\Users\...>dotnet --list-sdks
6.0.403 [C:\Program Files\dotnet\sdk]
7.0.101 [C:\Program Files\dotnet\sdk]

**Comment by sdanyliv** [comment]
Thanks for reporting, will fix that for the upcoming release.

**Comment by nikitam** [comment]
I have updated to new version 5.0.0, but now I receiveng an exception:
```
Exception message:
Expression 'x.DialogCategory' is not a Field.
Stack trace:
LinqToDB.Linq.LinqException: Expression 'x.DialogCategory' is not a Field.
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.LoadWithBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.LoadWithBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.LoadWithBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.OrderByBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.TakeSkipBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
```

domain objects and mappings are the same like in previous example.  What am I doing wrong?

**Comment by MaceWindu** [comment]
- have you done required changes to fluent mappings configuration for version 5.0.0?
- if yes, could you check it with 5.1.0 preview?

**Comment by nikitam** [comment]
Yes, I forgot call .Build() on FluentMappingBuilder, now it works fine, thank you for your help!
