### ISSUE TITLE
Exception thrown: Expression 'display.PageNumber' is not a Field using Value on Insertable

### ISSUE THREAD

**Issue by DDSGooch** [linq2db/linq2db#3927]
### Using the Value method when doing an Insert throws 'Expression is not a Field exception'

When using the Value method when doing an Insert, the following exception is thrown if the value parameter is not an Expression.
This seems wrong as there are two overloads on this method, once which takes a Value:
```c#
		public static ISelectInsertable<TSource,TTarget> Value<TSource,TTarget,TValue>(
			                this ISelectInsertable<TSource,TTarget> source,
			[InstantHandle] Expression<Func<TTarget,TValue>>        field,
			TValue                                                  value)
```
and one which takes an expression:
```c#
		public static ISelectInsertable<TSource,TTarget> Value<TSource,TTarget,TValue>(
			                this ISelectInsertable<TSource,TTarget> source,
			[InstantHandle] Expression<Func<TTarget,TValue>>        field,
			[InstantHandle] Expression<Func<TSource,TValue>>        value)
```
I would expect both to work. If the first method doesn't work, why does it exist? This turned out to be quite a serious problem as the code compiled but failed at runtime.

```
Exception message:
LinqToDB.Linq.LinqException: Expression 'display.PageNumber' is not a Field.

Stack trace:
at LinqToDB.Linq.Builder.TableBuilder.TableContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.UpdateBuilder.ParseSet(ExpressionBuilder builder, LambdaExpression extract, MethodCallExpression updateMethod, Int32 valueIndex, IBuildContext select, List`1 items)
   at LinqToDB.Linq.Builder.InsertBuilder.Value.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.InsertBuilder.Value.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.InsertBuilder.Value.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.InsertBuilder.Value.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.InsertBuilder.Value.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.InsertBuilder.Value.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.InsertBuilder.Value.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.InsertBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.<LinqToDB-Async-IQueryProviderAsync-ExecuteAsync>d__15`1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at LinqToDB.LinqExtensions.<InsertAsync>d__92`2.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Service.Commands.DisplayUpdateCommand.<DisplayInsertCommand>d__9.MoveNext()
```

### Steps to reproduce

```c#

var serialNumber = "12345678901";
var pageNum = 9;
await _dbConnection.Displays
                .Where(display => display.SerialNumber == serialNumber)
                .Into(_dbConnection.Displays)
                .Value(display => display.PageNumber, pageNumber)
                .InsertAsync();
```

**Model**
```c#

[Table(Schema="dbo", Name="Display")]
public partial class Display
{
	[Column(DataType=LinqToDB.DataType.Char,   Length=11),   PrimaryKey, NotNull ] public string  SerialNumber    { get; set; } // char(11)
	[Column(DataType=LinqToDB.DataType.Int32),   NotNull ] public int            PageNumber                          { get; set; } // int
}
```

### Environment details

`Linq To DB` version: *4.1.1*

Database (with version): *SQL Server 2016*

ADO.NET Provider (with version): *Microsoft.Data.SqlClient 4.1.0*

Operating system: *Windows Server 2019*

.NET Version: *.Net Framework 4.7.2*

**Comment by sdanyliv** [comment]
Does second overload works? I mean overload which expects  Expression as value.

**Comment by DDSGooch** [comment]
@sdanyliv, yes the second overload works, which is the workaround I'm now using. My concern is that I, or somebody else uses the other overload without realising that it won't work and it's only when the code is actually run, that it will be discovered. Thanks.

**Comment by sdanyliv** [comment]
If it is not critical now, we have did a lot of refactoring for version 6, which will handle this limitation.

**Comment by DDSGooch** [comment]
Thanks, yes that's fine. I assume you mean version 5, as that is in the preview stage or are you already working on version 6?

**Comment by sdanyliv** [comment]
Version 5 have a lot of improvements but version 6 will have redesigned LINQ translator. Almost done but for release it is about several months. In short, if it is not critical we can spend efforts on version 6.

**Comment by DDSGooch** [comment]
Thanks for your quick and helpful replies, I look forward to trying out the new version and keep up the good work. It's a great package and so much preferable to using Entity Framework.

**Comment by MaceWindu** [comment]
Looks like some important details missing as it is not reproduced on both  4.1.1 and versions

**Comment by MaceWindu** [comment]
Closing as no additional details provided and probably not an issue anymore as it is reported for old parser
