### ISSUE TITLE
Mapping to DateOnly[] column type doesn't work

### ISSUE THREAD

**Issue by VitaliyNec** [linq2db/linq2db#3929]
.Net 7
PostgreSQL 14.0 on x86_64-pc-linux-musl, compiled by gcc (Alpine 10.3.1_git20210424) 10.3.1 20210424, 64-bit

```cs
[Column] public DateOnly Date { get; set; }
```

 Work!

```cs
[Column] public DateOnly[] Dates { get; set; }
```

```
Cannot convert value 'System.DateTime[]: System.DateTime[]' to type 'System.DateOnly[]'

at LinqToDB.Common.ConvertBuilder.ConvertDefault(Object value, Type conversionType)
   at lambda_method158(Closure, DbDataReader)
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(DbDataReader dataReader)
   at lambda_method137(Closure, IQueryRunner, DbDataReader)
   at LinqToDB.Linq.QueryRunner.Mapper`1.ReMapOnException(IDataContext context, IQueryRunner queryRunner, DbDataReader dataReader, ReaderMapperInfo& mapperInfo, Exception ex)
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
```

**Comment by MaceWindu** [comment]
Related to #1660

You can define required conversion in mapping schema as workaround

**Comment by MaceWindu** [comment]
Let's keep it open till we not improve built-in mappings
