### ISSUE TITLE
Linq2db doesn't support read numeric into BigInteger

### ISSUE THREAD

**Issue by twilightrus** [linq2db/linq2db#4006]
### Describe your issue
While reading entity with BigInteger property (dbtype - numeric(78,0)) - linq2db throws exception

```
Exception message: System.OverflowException: Numeric value does not fit in a System.Decimal
Stack trace: System.OverflowException: Numeric value does not fit in a System.Decimal
   at Npgsql.Internal.TypeHandlers.NumericHandlers.NumericHandler.Read(NpgsqlReadBuffer buf, Int32 len, Boolean async, FieldDescription fieldDescription)
   at Npgsql.NpgsqlDataReader.GetFieldValue[T](Int32 ordinal)
   at Npgsql.NpgsqlDataReader.GetDecimal(Int32 ordinal)
   at lambda_method56(Closure, IQueryRunner, DbDataReader)
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IDataContext context, IQueryRunner queryRunner, DbDataReader dataReader, ReaderMapperInfo& mapperInfo)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass4_0`1.<<GetFirstOrDefaultElement>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at Domain.Services.FundsTransferService.TransferAsync(String senderAddress, String recipientAddress, BigInteger amount) in 
```

### Steps to reproduce

```c#
var transfer = await connection.Transfers.FirstOrDefaultAsync();

builder.Entity<Transfer>()
            .HasPrimaryKey(x => x.Id)
            .Property(x => x.Amount).HasPrecision(78).HasScale(0);
```

### Environment details

`Linq To DB` version: 5.0.0

Database (with version): Postgres

**Comment by MaceWindu** [comment]
Related npgsql issue https://github.com/npgsql/npgsql/issues/448#issuecomment-850652579

Looks like we should add explicit mappings for https://github.com/npgsql/npgsql/issues/3665 using `GetFieldValue<BigInteger>`

You could be able to workaround it by subclassing provider https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs#L17

and adding required data reader mappings
```cs
SetProviderField<DbDataReader, BigInteger, BigInteger>((DbDataReader rd, int idx) => rd.GetFieldValue<BigInteger>(idx));

```

**Comment by twilightrus** [comment]
> Related npgsql issue [npgsql/npgsql#448 (comment)](https://github.com/npgsql/npgsql/issues/448#issuecomment-850652579)
> 
> Looks like we should add explicit mappings for [npgsql/npgsql#3665](https://github.com/npgsql/npgsql/issues/3665) using `GetFieldValue<BigInteger>`
> 
> You could be able to workaround it by subclassing provider https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/PostgreSQL/PostgreSQLDataProvider.cs#L17
> 
> and adding required data reader mappings
> 
> ```cs
> SetProviderField<DbDataReader, BigInteger, BigInteger>((DbDataReader rd, int idx) => rd.GetFieldValue<BigInteger>(idx));
> ```

i want to bypass it

i write this code:
```
       var dataProvider = new PostgreSQLCustomDataProvider(PostgreSQLVersion.v95);
        DataConnection.AddDataProvider(dataProvider);
        
        services.AddLinqToDBContext<DbConnection>((provider, options) => options
            .UseConnectionString(connectionString)
            .UseDataProvider(dataProvider)
            .UseMappingSchema(builder.MappingSchema)
            .UseDefaultLogging(provider));
```

```
using System.Data.Common;
using System.Numerics;
using LinqToDB;
using LinqToDB.DataProvider.PostgreSQL;

namespace Infrastructure;

public class PostgreSQLCustomDataProvider : PostgreSQLDataProvider
{
    public PostgreSQLCustomDataProvider(PostgreSQLVersion version) : this(ProviderName.PostgreSQL95, version)
    {
    }

    public PostgreSQLCustomDataProvider(string name, PostgreSQLVersion version) : base(name, version)
    {
        SetProviderField<DbDataReader, BigInteger, BigInteger>((DbDataReader rd, int idx) => rd.GetFieldValue<BigInteger>(idx));
    }
}
```

but it doesn't work (Numeric value does not fit in a System.Decimal)

**Comment by MaceWindu** [comment]
Will check
