### ISSUE TITLE
Updating to 1.5 got Akka.Logger.NLog.NLogLogger error

### ISSUE THREAD

**Issue by JTrotta** [linq2db/linq2db#4013]
### Describe your issue
Upgrading to 1.5 it seems that there are some issues with Akka.Logger.NLog 1.4.10

```
Exception message:
[ERROR]Method not found: 'Void Akka.Event.ILoggingAdapter.Info(System.String, System.Object[])'.
Cause: System.MissingMethodException: Method not found: 'Void Akka.Event.ILoggingAdapter.Info(System.String, System.Object[])'.
   at Akka.Logger.NLog.NLogLogger.<.ctor>b__2_4(InitializeLogger m)
   at lambda_method79(Closure, Object, Action`1, Action`1, Action`1, Action`1, Action`1)
   at Akka.Tools.MatchHandler.PartialHandlerArgumentsCapture`6.Handle(T value)
   at Akka.Actor.ReceiveActor.ExecutePartialMessageHandler(Object message, PartialAction`1 partialAction)
   at Akka.Actor.ReceiveActor.OnReceive(Object message)
   at Akka.Actor.UntypedActor.Receive(Object message)
   at Akka.Actor.ActorBase.AroundReceive(Receive receive, Object message)
   at Akka.Actor.ActorCell.ReceiveMessage(Object message)
   at Akka.Actor.ActorCell.Invoke(Envelope envelope)
```

### Steps to reproduce

Upgrade a project using Akka.Logger.NLog to 1.5 

### Environment details

`Linq To DB` version: *1.5*

Database (with version): *SQLLite* 

Operating system: *Windows/Linux*

.NET Version: *7.0*

**Comment by jogibear9988** [comment]
@JTrotta you're sure you are in the correct repo? This is about linq2db, your issue is about akka

**Comment by JTrotta** [comment]
> @JTrotta you're sure you are in the correct repo? This is about linq2db, your issue is about akka

Oppppsssssss
