### ISSUE TITLE
Expression 'c.Id' is not a Field.' for derived DBO with separate base assembly

### ISSUE THREAD

**Issue by Redart98** [linq2db/linq2db#4031]
### Describe your issue

I have a group of tables with similar data structure. DBOs for them are placed in a shared assembly. To write single method that modifies any of that tables, I've created an interface, then derived class from both DBO and that interface, then made a generic that modifies data through that interface. If DBO, interface and derived class are placed in the same assembly, everything works ok. If they are located in different assemblies, exception is thrown when trying to build update query string.

```
Unhandled exception. LinqToDB.Linq.LinqException: Expression 'c.Id' is not a Field.
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.UpdateBuilder.Set.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at LinqToDB.LinqExtensions.Update[T](IUpdatable`1 source)
   at Bad.Program.Confirm[T](Int32 id) in D:\TestCase\Bad\Program.cs:line 20
   at Bad.Program.Main(String[] args) in D:\TestCase\Bad\Program.cs:line 14
```

### Steps to reproduce

Here is sample solution
https://disk.yandex.ru/d/D7MlU_8FHMbaIw

Project Good contains DBO class 
```c#
    [Table("Test")]
    class MyItem
    {
        [Column]
        [PrimaryKey]
        public int Id { get; set; }

        [Column]
        public bool Ok { get; set; }
    }
```

interface 
```c#
    interface IConfirmable
    {
        int Id { get; set; }
        bool Ok { get; set; }
    }
```

and derived class 
```c#
    class MyItemConfirmable : MyItem, IConfirmable
    {
    }
```

Also here is generic function 

```c#
        static void Main(string[] args)
        {
            DataConnection.AddOrSetConfiguration("default", "Server=.;Database=Ts1;Trusted_Connection=True;encrypt=false", "SqlServer");
            Confirm<MyItemConfirmable>(5);

        }
        static void Confirm<T>(int id) where T : class, IConfirmable
        {
            using var db = new DataConnection("default");
            db.GetTable<T>().Where(c => c.Id == id).
                Set(c => c.Ok, true)
                .Update();
            Console.WriteLine(db.LastQuery);
        }
```
Everything works as expected.

Now, project Bad contains derved MyItemConfirmable only and links to project Shared, containing MyItem, IConfirmable. When invoking Update in generic function here, exception is thrown.

### Environment details

`Linq To DB` version: 5.0.0

Database (with version): SQL Server 2017

ADO.NET Provider (with version): SqlServer

Operating system: Windows 10

.NET Version: .Net 5

**Comment by MaceWindu** [comment]
BTW, could you retest it with 5.1.0 preview (or wait for release later today)?

**Comment by Redart98** [comment]
5.1.0 gives the same error.

**Comment by MaceWindu** [comment]
That's interesting one. `Type.GetInterfaceMap` behaves differently for types in different assemblies (same behavior for both .net framework and .net core runtimes).

Investigating...

**Comment by Redart98** [comment]
Already done that, thank you. Waiting for fix.
