### ISSUE TITLE
T4 System.InvalidOperationException: Connection string is not provided

### ISSUE THREAD

**Issue by ndc** [linq2db/linq2db#4037]
### Steps to reproduce

1. Create a new dotnet 4.8 project.
2. Add nuget for linq2db.SqlServer.
3. Copy the CopyMe.SqlServer.tt.txt.
4. Add connection string to a localdb database.
5. Save.

Expected: the T4 generates the classes.
Actual: T4 emits an error: System.InvalidOperationException: Connection string is not provided.

Here is the stack trace:

```
System.InvalidOperationException: Connection string is not provided.
   at LinqToDB.DataProvider.ProviderDetectorBase`3.DetectServerVersion(ConnectionOptions options, TProvider provider)
   at LinqToDB.DataProvider.SqlServer.SqlServerProviderDetector.GetDataProvider(ConnectionOptions options, SqlServerProvider provider, SqlServerVersion version)
   at LinqToDB.DataProvider.SqlServer.SqlServerTools.CreateDataConnection(String connectionString, SqlServerVersion version, SqlServerProvider provider)
   at Microsoft.VisualStudio.TextTemplating65CAAFC4BCDC3DF47CB95842CD60EFBBCEA4545F114119F9AC113DB385B160158487441DB670D487A91465DE96F0B21DD2BB190C94796DAD94213D4DC4EEDF7A.GeneratedTextTransformation.GetSqlServerConnection(String connectionString, SqlServerVersion version, SqlServerProvider provider) in D:\PROJECTS\vssolutions\T4Error\packages\linq2db.SqlServer.5.1.0\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.SqlServer.ttinclude:line 66
   at Microsoft.VisualStudio.TextTemplating65CAAFC4BCDC3DF47CB95842CD60EFBBCEA4545F114119F9AC113DB385B160158487441DB670D487A91465DE96F0B21DD2BB190C94796DAD94213D4DC4EEDF7A.GeneratedTextTransformation.LoadSqlServerMetadata(String connectionString, SqlServerVersion version, SqlServerProvider provider) in D:\PROJECTS\vssolutions\T4Error\packages\linq2db.SqlServer.5.1.0\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.SqlServer.ttinclude:line 89
   at Microsoft.VisualStudio.TextTemplating65CAAFC4BCDC3DF47CB95842CD60EFBBCEA4545F114119F9AC113DB385B160158487441DB670D487A91465DE96F0B21DD2BB190C94796DAD94213D4DC4EEDF7A.GeneratedTextTransformation.TransformText() in D:\PROJECTS\vssolutions\T4Error\T4Error\CopyMe.SqlServer.tt:line 121		D:\PROJECTS\vssolutions\T4Error\packages\linq2db.SqlServer.5.1.0\build\..\contentFiles\any\any\LinqToDB.Templates\LinqToDB.SqlServer.ttinclude	66	
```

I have attached the project to reproduce the issue:
[T4Error.zip](https://github.com/linq2db/linq2db/files/11011191/T4Error.zip)

### Environment details

`Linq To DB` version: *5.1.0*

Database (with version): *localdb Microsoft SQL Server 2019 (RTM-CU12) (KB5004524) - 15.0.4153.1 (X64)* (e.g. SQL Server 2019)

ADO.NET Provider (with version): *System.Data.SqlClient 4.8.1* (e.g. Microsoft.Data.SqlClient 4.1.0)

Operating system: *Windows 10*

.NET Version: *4.8.1*

**Comment by igor-tkachev** [comment]
Add the following parameter to the LoadSqlServerMetadata method for now

```c#
LoadSqlServerMetadata(@"...", SqlServerVersion.v2019);
```
