### ISSUE TITLE
linq2db jsonb postgres support

### ISSUE THREAD

**Issue by twilightrus** [linq2db/linq2db#4044]
can I search on jsonb field using linq? when I tried this I got an exception about the impossibility of converting

**Comment by igor-tkachev** [comment]
Can you please provide an example of what you are trying to do?

**Comment by twilightrus** [comment]
> Can you please provide an example of what you are trying to do?

I have this mapping:

```
public void Configure(EntityMappingBuilder<Sending> builder)
    {
        builder.HasTableName("Sendings");
        builder.HasPrimaryKey(x => x.Id);
        builder.Property(x => x.ConcurrencyToken).HasAttribute(new OptimisticLockPropertyAttribute(VersionBehavior.Auto));
        builder.Property(x => x.Params).HasDbType("jsonb").HasConversionFunc(JsonConvert.SerializeObject, y => JsonConvert.DeserializeObject<SendingParams>(y)!);
}
```

I call the .Build(), mapping works on standard queries.
I want to filter `Sending` by `Params` fields:

```
table.Where(x => x.Params.FromAddress == 'test').ToListAsync()
```

throws an exception. Can linq2db map this query to ->> operators for postgres?

**Comment by LaXiS96** [comment]
This would be a great feature, with two main points: mapping POCOs (like EFCore7's `ToJson` owned entities) and mapping JSON DOM types (`System.Text.Json`'s `JsonDocument`/`JsonNode` and Newtonsoft's `JToken`).
The former is supported by the [Npgsql.EFCore provider](https://www.npgsql.org/efcore/mapping/json.html), the latter is supported only partially AFAIK, but plain Npgsql can already do that.

PostgreSQL has [many powerful functions and operators](https://www.postgresql.org/docs/current/functions-json.html) to query and process JSON data stored in `json` and `jsonb` columns, it would be awesome if linq2db could translate property accesses to the correct JSON operators, while leaving specific functions to extension methods like EFCore's `EF.Functions`.

**Comment by AudriusButkevicius** [comment]
Am I wrong, or even IUpdatable does not work with jsonb?

i.e, I have a column that stores a jsonb object, doing 
```
ctx.DbSet.Set(o => o.JsonBField, instanceOfJsonSerializableObject).Update()
```
does not seem to work.

**Comment by MaceWindu** [comment]
Have you annotated your column with `DataType.Jsonb`? `Column(DataType=DataType.Jsonb)`

**Comment by AudriusButkevicius** [comment]
Just tried it now, still happens.

**Comment by AudriusButkevicius** [comment]
Actually, I think it's even worse, I can't seem to be able to use `Set().Update()` on entities that have a Jsonb (EF .ToJson()) column.


Not sure where the "select include expression" comes from, my query is fairly simple:

```
        var count = await dbCtx.Orders
            .AsSingleQuery()
            .Where(o => o.Id == request.OrderId&& o.GameAccountId == request.AccountId&& o.Courier == null)
            .Set(o => o.Courier, courier)
            .Set(o => o.Locked, true)
            .Set(o => o.ShippingTime, SystemClock.Instance.GetCurrentInstant())
            .UpdateAsync()
            .ConfigureAwait(false);
```

Error in details

<details>

```
System.AggregateException: One or more errors occurred. (The LINQ expression 'DbSet<Order>()
    .Where(c => (ulong)c.Id == __request_OrderId_0 && (ulong)c.AccountId == __request_AccountId_1 && c.Courier == null)
    .Select(c => IncludeExpression(
        EntityExpression:
        c,
        NavigationExpression:
        IncludeExpression(
            EntityExpression:
            EF.Property<OrderPreview>(c, "Preview"),
            NavigationExpression:
            MaterializeCollectionNavigation(
                Navigation: OrderPreview.Equipment,
                subquery: EF.Property<List<Equipment>>(EF.Property<OrderPreview>(c, "Preview"), "Equipment")
                    .AsQueryable()), Equipment)
        , Preview)
    )
    .Set(
        extract: o => o.Courier,
        value: __p_2)
    .Set(
        extract: o => o.Locked,
        value: __p_3)
    .Set(
        extract: o => o.ShippingTime,
        value: __p_4)
    .Update()' could not be translated. Either rewrite the query in a form that can be translated, or switch to client evaluation explicitly by inserting a call to 'AsEnumerable', 'AsAsyncEnumerable', 'ToList', or 'ToListAsync'. See https://go.microsoft.com/fwlink/?linkid=2101038 for more information.)
   
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.VisitMethodCall(MethodCallExpression methodCallExpression)
   at Microsoft.EntityFrameworkCore.Query.QueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.RelationalQueryableMethodTranslatingExpressionVisitor.Translate(Expression expression)
   at Microsoft.EntityFrameworkCore.Query.QueryCompilationContext.CreateQueryExecutor[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Storage.Database.CompileQuery[TResult](Expression query, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.CompileQueryCore[TResult](IDatabase database, Expression query, IModel model, Boolean async)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.<>c__DisplayClass9_0`1.<Execute>b__0()
   at Microsoft.EntityFrameworkCore.Query.Internal.CompiledQueryCache.GetOrAddQuery[TResult](Object cacheKey, Func`1 compiler)
   at Microsoft.EntityFrameworkCore.Query.Internal.QueryCompiler.Execute[TResult](Expression query)
   at Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider.Execute[TResult](Expression expression)
   at LinqKit.Core.ExpandableQueryProvider`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at LinqToDB.LinqExtensions.<>c__DisplayClass36_0`1.<UpdateAsync>b__0()
```

</details>
