### ISSUE TITLE
PostgreSQLTools: Connection string is not provided

### ISSUE THREAD

**Issue by sergiocardenasm** [linq2db/linq2db#4045]
### Describe your issue

InvalidOperationException: Connection string is not provided.

   at LinqToDB.DataProvider.ProviderDetectorBase`3.DetectServerVersion(ConnectionOptions options, TProvider provider)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLProviderDetector.GetDataProvider(ConnectionOptions options, Provider provider, PostgreSQLVersion version)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.GetDataProvider(PostgreSQLVersion version, String connectionString)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLTools.CreateDataConnection(String connectionString, PostgreSQLVersion version)

### Steps to reproduce

```c#
PostgreSQLTools.CreateDataConnection("Database=[...]");
```

The bug is here:

```c#
public static partial class PostgreSQLTools
{
   [...]

		public static IDataProvider GetDataProvider(PostgreSQLVersion version = PostgreSQLVersion.AutoDetect, string? connectionString = null)
		{
			return ProviderDetector.GetDataProvider(new ConnectionOptions(connectionString), default, version);
		}

		public static DataConnection CreateDataConnection(string connectionString, PostgreSQLVersion version = PostgreSQLVersion.AutoDetect)
		{
			return new DataConnection(GetDataProvider(version), connectionString);
		}
}
```

CreateDataConnection is calling GetDataProvider without my connectionString, so the default value is null

### Environment details

`Linq To DB` version: 5.1.0

Database (with version): PostgreSql 13.9

Operating system: Windows 10

.NET Version: 7

**Comment by igor-tkachev** [comment]
Duplicate #4037. Already fixed. 
You should specify PostgreSQLVersion for now.

**Comment by sergiocardenasm** [comment]
It is not fixed. Please, review my suggestion.
The issue persists in 5.1.1

**Comment by MaceWindu** [comment]
@igor-tkachev, for context - I've noticed it before here #4002 - a lot of Tools classes doesn't pass `connectionString` to `GetDataProvider`
