### ISSUE TITLE
Error on untyped enum values in Postgres

### ISSUE THREAD

**Issue by ademchenko** [linq2db/linq2db#4046]
### Describe your issue

I'm actually not sure if I have to post the bug here or to npgsql, but the issue is quite severe for us, so, if you think it's not possible to make anything with that issue on the side of linq2db, please, let me know in order to recreate the issues on the npgsql side.

Suppose we have a database with the table:

```sql
create table person
(
    name     text    not null,
    category integer not null
);
```

and the corresponding generated class: 
```c#
[Table("person", Schema = "public")]
	public partial class Person
	{
		[Column("name"    , CanBeNull = false)] public string Name     { get; set; } = null!; // text
		[Column("category"                   )] public int    Category { get; set; } // integer
	}
```

Let the category be logically the enum but not having the mapping in the database to the custom enum type (it's quite common case).

In the described case it's convenient to convert the category to C# enum:
```c#
  public enum PersonCategory
    {
        Friends = 1,
        Relatives = 2
    }
```
like 
```c#
db.People.Select(p => new { p.Name, Category = (PersonCategory)p.Category })
```

And after that, let's suppose we have some third-party lib that applies filters to our IQueryables (exactly our production case). Usually, such libs produce the code with untyped enums. Let's model that situation in the following test:
```c#
[Test]
        public async Task FilterWithEnumAsObjectTest_Fail()
        {
            var db = new EntitiesDataConnection();

           //The enum is untyped
            object categoryParam = PersonCategory.Friends;

            var result = await db.People
                .Select(p => new { p.Name, Category = (PersonCategory)p.Category })
                .Where(p => p.Category.Equals(categoryParam))
                .CountAsync();
        }
```
That test will fail with the exception:
```
System.ArgumentException : A PostgreSQL type with the name 'person_category' was not found in the database
   at Npgsql.Internal.NpgsqlDatabaseInfo.GetPostgresTypeByName(String pgName)
   at Npgsql.TypeMapping.TypeMapper.ResolveByClrType(Type type)
   at Npgsql.NpgsqlParameter.ResolveHandler(TypeMapper typeMapper)
   at Npgsql.NpgsqlParameterCollection.ProcessParameters(TypeMapper typeMapper, Boolean validateValues, CommandType commandType)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteElementAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteElementAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at GtG.Core.Tests.Test.FilterWithEnumAsObjectTest_Fail() in C:\Sources\B2B\bgs-platform\BigGameSolutions.Tests\BetWinRefundGenericTests.cs:line 49
   at NUnit.Framework.Internal.TaskAwaitAdapter.GenericAdapter`1.GetResult()
   at NUnit.Framework.Internal.AsyncToSyncAdapter.Await(Func`1 invoke)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.RunTestMethod(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.TestMethodCommand.Execute(TestExecutionContext context)
   at NUnit.Framework.Internal.Commands.BeforeAndAfterTestCommand.<>c__DisplayClass1_0.<Execute>b__0()
   at NUnit.Framework.Internal.Commands.DelegatingTestCommand.RunTestMethodInThreadAbortSafeZone(TestExecutionContext context, Action action)
```
And the generated SQL script is obviously not correct (AFAIK there's just no syntax allowing to define the type "Enum" of the variable): 
```
BeforeExecute
-- GtG.Core.Db PostgreSQL.9.5 PostgreSQL (asynchronously)
DECLARE @categoryParam Enum -- Object
SET     @categoryParam = 1

SELECT
	Count(*)
FROM
	"public".person p
WHERE
	p.category = :categoryParam
```

Of course, there's a "kind of" a workaround - just to use the strongly typed enums, but, as I told before, that's not the case when the code is applied by some third-party library which intentionally uses untyped objects in order to cover all possible cases.
```c#
         [Test]
        public async Task FilterWithEnumStronglyTypedTest_Success()
        {
            var db = new EntitiesDataConnection();

            PersonCategory categoryParam = PersonCategory.Friends;

            var result = await db.People
                .Select(p => new { p.Name, Category = (PersonCategory)p.Category })
                .Where(p => p.Category.Equals(categoryParam))
                .CountAsync();
        }
```

`Linq To DB` version: *4.x, 5.x*

Database (with version): *Postgres 14.x*

ADO.NET Provider (with version): *Npgsql 7.x* 

Is it possible to fix that somehow on the side of linq2db?

**Comment by igor-tkachev** [comment]
Can you define the Category field as enum?

```c#
[Table("person", Schema = "public")]
public partial class Person
{
	[Column("name"    , CanBeNull = false)] public string         Name     { get; set; } = null!; // text
	[Column("category"                   )] public PersonCategory Category { get; set; } // integer
}
```

**Comment by ademchenko** [comment]
@igor-tkachev , I understand, that's a workaround, but in my case it's not possible to change the generated entities.

**Comment by igor-tkachev** [comment]
Is it technically or bureaucratically impossible?

**Comment by igor-tkachev** [comment]
The following code works:

```c##
[Test]
public void ObjectParamTest([IncludeDataSources(TestProvName.AllPostgreSQL)] string context)
{
	var ms = new MappingSchema();

	ms.SetConverter<object?,object?>(o => o is PersonCategory pc ? (int)pc : o);

	using var db = GetDataConnection(context, o => o.UseMappingSchema(ms));

	object categoryParam = PersonCategory.Friends;

	_ = db.GetTable<Person>()
		.Select(p => new { p.Name, Category = (PersonCategory)p.ID })
		.Where(p => p.Category.Equals(categoryParam))
		.Count();
}
```

The only problem is object is too generic type and this conversion can override some other conversions.

**Comment by ademchenko** [comment]
@igor-tkachev , first of all, thank you for the provided workaround. 
But, yes, that's quite inconvenient to define the mapping in such a manner not only because the object is too generic but also because there's a plenty of such cases in our system.

But, please, could you say what is the root of the issue?
For example, if I do the same with an integer it works perfectly:
```
[Test]
        public async Task FilterWithEnumAsObjectTest_SuccessWithInt()
        {
            var db = new EntitiesDataConnection();

            object categoryParam = 1;

            var result = await db.People
                .Select(p => new
                {
                    p.Name,
                    p.Category
                })
                .Where(p => p.Category.Equals(categoryParam))
                .CountAsync();
        }
```
But we know that enums are "more or less" integer types. So, is it an issue on the side of npgsql and, therefore, shall I create an issue on their repository? Or is it something wrong with the default mappings of linq2db?

**Comment by igor-tkachev** [comment]
We have different mappings for different providers for known types. Object is too generic and we just pass it directly to provider. If the object wraps up an integer or any other known type, provider takes it without problem. If this is any unknown type, it throws an exception.

The regular linq2db way to solve this situation is to create a mapping extension 
```c#
SetConverter[Expression]<YurType,DataParameter>(...)
```
but it did not work. I already fixed it, but not committed yet.

If you have a lot of cases like this one, you can use the following conversion:

```c#
ms.SetConverter<object?,object?>(o => o is Enum e ? Convert.ChangeType(e, Enum.GetUnderlyingType(e.GetType())) : o);
```
It converts any enum value to its underlying type.

**Comment by ademchenko** [comment]
@igor-tkachev , any news with SetConverter[Expression]?

**Comment by ademchenko** [comment]
@igor-tkachev , if SetConverter is used in that way for object, is there a chance that some built-in or generated (by scaffolding tool) converters will be redefined? So, are we safe here?

**Comment by igor-tkachev** [comment]
I cannot guarantee this for your code. We have a test for this converter, and about a million other tests work just fine.
