### ISSUE TITLE
Create an association without having the foreign key mapped as property

### ISSUE THREAD

**Issue by akamud** [linq2db/linq2db#4051]
### Describe your issue

I would like to map an association omitting the Foreign Key id as a mapped property. I'm trying hide it because my code doesn't need the Foreign Key explicitly, I can use the navigation property (`Conta`) to read everything I need. It's something like the concept of [Shadow Properties](https://learn.microsoft.com/en-us/ef/core/modeling/shadow-properties#foreign-key-shadow-properties) in EF Core.

```
Exception message: Association key 'ContaId' not found for type 'DistributedTransactions.Movimentacao.
Stack trace:
LinqToDB.Linq.LinqException: Association key 'ContaId' not found for type 'DistributedTransactions.Movimentacao.
         at LinqToDB.Linq.Builder.AssociationHelper.CreateAssociationQueryLambda(ExpressionBuilder builder, AccessorMember onMember, AssociationDescriptor association, Type parentOriginalType, Type parentType, Type objectType, Boolean inline, Boolean enforceDefault, List`1 loadWith, Boolean& isLeft)
         at LinqToDB.Linq.Builder.AssociationHelper.BuildAssociationInline(ExpressionBuilder builder, BuildInfo buildInfo, TableContext tableContext, AccessorMember onMember, AssociationDescriptor descriptor, Boolean inline, Boolean& isOuter)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.FindContextExpression(Expression expression, Int32 level, Boolean forceInner, Boolean throwExceptionForNull)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildExpression(Expression expression, Int32 level, ParameterExpression parentObject, Boolean enforceServerSide)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.SetLoadWithBindings(Type objectType, ParameterExpression parentObject, List`1 exprs)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildDefaultConstructor(EntityDescriptor entityDescriptor, Type objectType, Tuple`2[] index)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildTableExpression(Boolean buildBlock, Type objectType, Tuple`2[] index)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery(Type tableType, TableContext tableContext, ParameterExpression parentObject)
         at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
         at LinqToDB.Linq.Builder.PassThroughContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
         at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
         at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
         at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
         at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
         at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
         at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
         at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
         at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
         at TestEFCoreLinq2Db.Controllers.WeatherForecastController.Get() in /Users/mahmoud/Projects/TestEFCoreLinq2Db/TestEFCoreLinq2Db/Controllers/WeatherForecastController.cs:line 25
         at lambda_method2(Closure , Object , Object[] )
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.SyncObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeActionMethodAsync()
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeNextActionFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()
      --- End of stack trace from previous location ---
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Awaited|17_0(ResourceInvoker invoker, Task task, IDisposable scope)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
         at Swashbuckle.AspNetCore.SwaggerUI.SwaggerUIMiddleware.Invoke(HttpContext httpContext)
         at Swashbuckle.AspNetCore.Swagger.SwaggerMiddleware.Invoke(HttpContext httpContext, ISwaggerProvider swaggerProvider)
         at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)

```

### Steps to reproduce

```c#
public class Movimentacao
{
    public Movimentacao() { }

    public Guid Id { get; set; }

    [Association(ThisKey = "ContaId", OtherKey = "Id")]
    public Conta Conta { get; init; }
    // public Guid ContaId { get; init; } -- If I uncomment this, it works, but I don't want to map this property because I don't use it in my Code.
    public decimal Valor { get; init; }
}

public class Conta
{
    public Guid Id { get; set; }
    public string Nome { get; set; }
    public decimal Saldo { get; set; }
}
```

I'm trying to build a simple `db.Movimentacoes.LoadWith(x => x.Conta).ToList()` query.

Is this possible?

### Environment details

`Linq To DB` version: 5.1.0

Database (with version): SQL Server 2019

ADO.NET Provider (with version): Microsoft.Data.SqlClient 5.0.1

Operating system: macOS 12.6.1

.NET Version: 6.0

**Comment by sdanyliv** [comment]
You can try `QueryExpressionMethod`
```cs
public class Movimentacao
{
    public Movimentacao() { }

    public Guid Id { get; set; }

    [Association(QueryExpressionMethod = nameof(ContaImpl)]
    public Conta Conta { get; init; }

    public decimal Valor { get; init; }

    private static Expression<Func<Movimentacao, IDataContext, IQueryable<Conta>>> ContaImpl()   
    {
        return (m, db) => db.GetTable<Conta>().Where(c => c.Id == Sql.Property<int>(m, "ContaId"));
    }
}
```
