### ISSUE TITLE
`System.ArgumentOutOfRangeException` when using `LoadWith`

### ISSUE THREAD

**Issue by viceroypenguin** [linq2db/linq2db#4060]
If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message:
System.ArgumentOutOfRangeException; Index was out of range. Must be non-negative and less than the size of the collection

Stack trace:
   at System.ThrowHelper.ThrowArgumentOutOfRange_IndexMustBeLessException()
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at LinqToDB.SqlProvider.BasicSqlOptimizer.<>c.<FixSetOperationNulls>b__7_0(IQueryElement e)
   at LinqToDB.SqlQuery.QueryParentVisitor`1.Visit(IQueryElement element)
   at LinqToDB.SqlQuery.QueryParentVisitor`1.Visit(IQueryElement element)
   at LinqToDB.SqlQuery.QueryVisitorExtensions.VisitParentFirst(IQueryElement element, Func`2 action)
   at LinqToDB.SqlProvider.BasicSqlOptimizer.FixSetOperationNulls(SqlStatement statement)
   at LinqToDB.SqlProvider.BasicSqlOptimizer.Finalize(MappingSchema mappingSchema, SqlStatement statement, DataOptions dataOptions)
   at LinqToDB.Linq.QueryRunner.FinalizeQuery(Query query)
   at LinqToDB.Linq.QueryRunner.GetExecuteQuery[T](Query query, Func`8 queryFunc)
   at LinqToDB.Linq.QueryRunner.SetRunQuery[T](Query`1 query, Expression`1 expression)
   at LinqToDB.Linq.QueryRunner.SetRunQuery[T](Query`1 query, Expression`1 expression)
   at LinqToDB.Linq.Builder.SetOperationBuilder.SetOperationContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.PassThroughContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at LinqToDB.LinqExtensions.LoadWithQueryable`2.GetEnumerator()
   at System.Linq.Enumerable.<TakeWhileIterator>d__277`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at LinqToDB.AsyncExtensions.<>c__DisplayClass8_0`1.<ToListAsync>b__0()
```

### Steps to reproduce

Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
var _context = new DbContext();
var forms = await _context.Forms
	.Where(f => f.FormId == 2)
	.Concat(_context.Forms.Where(f => f.FormId == 3))
	.LoadWith(f => f.CreatedUser)
	.ToListAsync();

public partial class DbContext : DataConnection
{
	public DbContext()
		: base(
			connectionString: "<>",
			dataProvider: SqlServerTools.GetDataProvider(
				SqlServerVersion.v2019,
				SqlServerProvider.MicrosoftDataSqlClient))
	{

	}

	public ITable<Form> Forms => this.GetTable<Form>();
	public ITable<User> Users => this.GetTable<User>();
}

[Table("Form")]
public class Form
{
	[Column("FormId", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int FormId { get; set; } // int
	[Column("Name", CanBeNull = false)] public string Name { get; set; } = null!; // nvarchar(200)
	[Column("CreatedDateTime")] public DateTimeOffset CreatedDateTime { get; set; } // datetimeoffset(7)
	[Column("CreatedUserId")] public int CreatedUserId { get; set; } // int

	#region Associations
	/// <summary>
	/// FK_Form_User
	/// </summary>
	[Association(CanBeNull = false, ThisKey = nameof(CreatedUserId), OtherKey = nameof(User.UserId))]
	public User CreatedUser { get; set; } = null!;
	#endregion
}

[Table("User")]
public class User
{
	[Column("UserId", IsPrimaryKey = true, IsIdentity = true, SkipOnInsert = true, SkipOnUpdate = true)] public int UserId { get; set; } // int
	[Column("Name", CanBeNull = false)] public string Name { get; set; } = null!; // nvarchar(200)

	#region Associations
	/// <summary>
	/// FK_Form_User backreference
	/// </summary>
	[Association(ThisKey = nameof(UserId), OtherKey = nameof(Form.CreatedUserId))]
	public IEnumerable<Form> Forms { get; set; } = null!;
	#endregion
}
```

### Environment details

`Linq To DB` version: 5.1.1

Database (with version): SQL Server 2019

ADO.NET Provider (with version): Microsoft.Data.SqlClient 5.1.1

Operating system: Windows

.NET Version: 7.0

**Comment by MaceWindu** [comment]
I've added it to v6 as SET queries with eager load doesn't work in current parser and we don't plan to implement it in it. New parser already should handle it AFAIK

**Comment by TopDZL** [comment]
I've got the similar exception. It looks like LoadWith must not be used after Where and other LinqToDb methods.
