### ISSUE TITLE
SQL error when calling Count on a query with Join and OrderBy

### ISSUE THREAD

**Issue by sksk571** [linq2db/linq2db#4074]
### Describe your issue

When query contains Join and OrderBy in one of the joined tables, then calling Count on such query generates error `Column X is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.`

```
Exception message:
Column X is invalid in the ORDER BY clause because it is not contained in either an aggregate function or the GROUP BY clause.
Stack trace:
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteDataReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.ExecuteElement[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.QueryRunner.<>c__DisplayClass26_0`1.<SetRunQuery>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
```

### Steps to reproduce

```c#
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.Mapping;

var db = new DataConnection(LinqToDB.ProviderName.SqlServer2019,
  @"Server=.\;Database=Test;Trusted_Connection=True;Enlist=False;TrustServerCertificate=True");

var q1 = db.GetTable<UserAccount>().OrderBy(u => u.Email);
var q2 = db.GetTable<UserAccount>();
var q = q2.Join(q1, u2 => u2.Email, u1 => u1.Email, (u2, u1) => new { u2, u1 });

Console.WriteLine(q.Count());


[Table(Name = "[dbo].[UserAccounts]")]
public class UserAccount
{
    [PrimaryKey, Identity]
    public int ID { get; set; }

    [Column]
    public string Email { get; set; } = string.Empty;
}
```

### Environment details

`Linq To DB` version: 5.1.1

Database (with version): SQL Server 2019

ADO.NET Provider (with version): Microsoft.Data.SqlClient 4.1.0

Operating system: Windows 10

.NET Version: .NET7

**Comment by MaceWindu** [comment]
Could you add generated sql?

**Comment by Luizalvess** [comment]
I have a similar problem, every time I create the class VS informs me that it already exists and tells me to replace it and it gives me an error.
