### ISSUE TITLE
F# insert/update api methods with lambdas not working.

### ISSUE THREAD

**Issue by FaultyBill** [linq2db/linq2db#4132]
### Describe your issue

Looks like few linq2db methods that uses func expression parameters does not work in F#. Tested insert and update methods. Results described below.

Stacktrace:

```
LinqToDB.Linq.LinqException: 'new TestType(0, 1, "freshly inserted")' cannot be converted to SQL.
   at LinqToDB.Linq.Builder.ExpressionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildSetterWithContext(ExpressionBuilder builder, BuildInfo buildInfo, LambdaExpression setter, IBuildContext into, List`1 items, IBuildContext[] sequences)
   at LinqToDB.Linq.Builder.UpdateBuilder.BuildSetter(ExpressionBuilder builder, BuildInfo buildInfo, LambdaExpression setter, IBuildContext into, List`1 items, IBuildContext sequence)
   at LinqToDB.Linq.Builder.InsertBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at LinqToDB.LinqExtensions.Insert[T](ITable`1 target, Expression`1 setter)
   at <StartupCode$ReproLinq2dbFsharp>.$Program.main@() in 
```

### Steps to reproduce

```F#
open LinqToDB
open LinqToDB.Mapping

[<Table("TestTable")>]
    //keep messages which correspondent's message not yet was added to db.
type TestType =
    { [<Column("id"); PrimaryKey; Identity>]
      Id: int
      [<Column("number")>]
      Number: int
      [<Column("text")>]
      Text: string }
    
let test =
    use db = new LinqToDB.Data.DataConnection(DataOptions().UseSQLite(@"Data Source=.\demo_base.sqlite;Version=3;"))
    let table = db.CreateTable<TestType>()    
    //spawn LinqToDB.Linq.LinqException: 'new TestType(0, 1, "freshly inserted")' cannot be converted to SQL.
    table.Insert(fun() ->{TestType.Id = 0; Number = 1; Text = "freshly inserted"}) |> ignore    
    //LinqToDB.Linq.LinqException: 'Text => new TestType(row.Id, row.Number, Text).Invoke("updated recently")' cannot be converted to SQL
    table.Update((fun row -> row.Number = 1), (fun row -> {row with Text = "updated recently"})) |> ignore
   
   
test
```

### Environment details

`Linq To DB` version: 5.2.1

Database (with version): SQLite 3

Operating system: win 10
.NET Version: 7.0

**Comment by MaceWindu** [comment]
Thanks for report. I would recommend to use simplier APIs from F#. We have plans to improve handling of F#-generated expressions, but it's not something that will happen soon

**Comment by FaultyBill** [comment]
@MaceWindu there is possibility to filter&update in single request without expressions?
As far as I see, in f#'s linq2db we cannot use "Where + Set" combo as "Where" is not applicable. (?)

**Comment by MaceWindu** [comment]
```fs
table.Where(fun r -> r.Id = 1).Set((fun r -> r.Value), "new text").Update() |> ignore
```

**Comment by MaceWindu** [comment]
You could also try to use `Microsoft.FSharp.Linq.RuntimeHelpers.LeafExpressionConverter.QuotationToExpression` APIs to convert F#-generated expressions to expressions, understandable by outside world :) , but it's not something I tested.
