### ISSUE TITLE
Linq2DB & Azure SQL Edge

### ISSUE THREAD

**Issue by canine-afficionado** [linq2db/linq2db#4195]
Hello, first time user trying out linq2db. Looks fantastic.

I tried using the donet linq2db cli tool (5.2.2.0) to scaffold my database which is an Azure SQL Edge Database (so I can run SQL Server on Linux ARM).

However it appears that CLR features are needed to scaffold and Azure SQL Edge [does not support the CLR](https://learn.microsoft.com/en-us/azure/azure-sql-edge/features).

It is possible to scaffold without using the CLR features?

Thanks.

**Comment by MaceWindu** [comment]
What do you mean by "CLR features needed"? linq2db knows nothing (and don't need to know) about SQL Server CLR support.

**Comment by canine-afficionado** [comment]
Thanks @MaceWindu I thought it was weird that CLR support would be needed for introspecting a database but this was the exception that was raised when I tried scaffolding:

```
>dotnet linq2db scaffold -p SQLServer -c "Server=server;Database=db;User Id=user;Password=password;TrustServerCertificate=True"
Unhandled exception: Common Language Runtime(CLR) is not enabled on this instance.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryHasMoreRows(Boolean& moreRows)
   at Microsoft.Data.SqlClient.SqlDataReader.TryReadInternal(Boolean setTimeout, Boolean& more)
   at Microsoft.Data.SqlClient.SqlDataReader.Read()
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.addUDTsToDataTypesTable(DataTable dataTypesTable, SqlConnection connection, String ServerVersion)
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.GetDataTypesTable(SqlConnection connection)
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.PrepareCollection(String collectionName, String[] restrictions, DbConnection connection)
   at Microsoft.Data.ProviderBase.DbMetaDataFactory.GetSchema(DbConnection connection, String collectionName, String[] restrictions)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.GetSchema(DbConnectionFactory factory, DbConnectionPoolGroup poolGroup, DbConnection outerConnection, String collectionName, String[] restrictions)
   at Microsoft.Data.SqlClient.SqlConnection.GetSchema(String collectionName, String[] restrictionValues)
   at Microsoft.Data.SqlClient.SqlConnection.GetSchema(String collectionName)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetDataTypes(DataConnection dataConnection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at LinqToDB.Schema.LegacySchemaProvider..ctor(DataConnection connection, SchemaOptions options, ILanguageProvider languageProvider)
   at LinqToDB.CommandLine.ScaffoldCommand.Scaffold(ScaffoldOptions settings, ScaffoldInterceptors interceptors, String provider, String providerLocation, String connectionString, String additionalConnectionString, String output, Boolean overwrite)
   at LinqToDB.CommandLine.ScaffoldCommand.Execute(CliController controller, String[] rawArgs, Dictionary`2 options, IReadOnlyCollection`1 unknownArgs)
   at LinqToDB.CommandLine.CliController.Execute(String[] args)
   at LinqToDB.Tools.Program.Main(String[] args)

```

**Comment by MaceWindu** [comment]
That's interesting. Investigating..

**Comment by MaceWindu** [comment]
We load list of database types using Sqlclient's GetSchema API and it executes following SQL, which is not compatible with your server https://github.com/dotnet/SqlClient/blob/3cb9730a848c919c765036d48cb79440030f3df5/src/Microsoft.Data.SqlClient/src/Microsoft/Data/SqlClient/SqlMetadataFactory.cs#L28

It raises some questions. If SqlClient officially supports `Azure SQL Edge`, than it's bug in SqlClient. I will rise issue on their side as I cannot find any official information on support.

In any case, we probably should fix it on our side by using raw SQL instead of GetSchema API. We already have plans to get rid of GetSchema calls as it's awfully bad and inconsistent API.

**Comment by MaceWindu** [comment]
Filled https://github.com/dotnet/SqlClient/issues/2086 to track it on Sqlclient side

**Comment by canine-afficionado** [comment]
Interesting & thanks for your prompt diagnosis. I did wonder if it might be something to do with SqlClient as I did some research and discovered that the [CLR is required for certain types](https://dba.stackexchange.com/questions/213328/experiencing-clr-error-on-sql-azure-db?rq=1). I wondered if the SqlClient had accounted for this with SQL Edge. 

Re the GetSchema API - I know that most Java Database Tools use SQL rather than the JDBC introspection calls for the same reason (inconsistent results) although that is across different databases.

Let's home Microsoft fix it ASAP - I'll keep an eye on the issue.

**Comment by kaspars-ozols** [comment]
It looks like the underlying issue with SqlClient has now been resolved.

**Comment by MaceWindu** [comment]
Consolidated from duplicate #4536 — same root cause and fix. The underlying task tracked here is to **stop using SqlClient's `GetSchema` API in the schema provider** (the `addUDTsToDataTypesTable` / `GetDataTypes` path), replacing it with raw SQL, which fixes scaffolding against trimmed MSSQL-derivative cloud DBs that lack CLR / assembly support.

### From #4536 (by @Hoodah, 2024) — Microsoft Fabric Data Warehouse

`dotnet linq2db scaffold -p SqlServer` against a `*.datawarehouse.fabric.microsoft.com` connection fails with `FUNCTION 'ASSEMBLYPROPERTY' is not supported.` — the **identical** `GetSchema` data-types path as the Azure SQL Edge failure above:

```
Unhandled exception: FUNCTION 'ASSEMBLYPROPERTY' is not supported.
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.addUDTsToDataTypesTable(...)
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.GetDataTypesTable(SqlConnection connection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetDataTypes(DataConnection dataConnection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at LinqToDB.Schema.LegacySchemaProvider..ctor(...)
   at LinqToDB.CommandLine.ScaffoldCommand.Scaffold(...)
```

A separate SqlClient issue was filed for Fabric DW. The Azure SQL Edge case (this issue) was tracked at dotnet/SqlClient#2086, but the durable fix is removing the `GetSchema` dependency on our side so any trimmed MSSQL variant scaffolds.
