### ISSUE TITLE
Null reference error on type conversion in Select

### ISSUE THREAD

**Issue by sksk571** [linq2db/linq2db#4198]
### Describe your issue

Null reference error happens when type converted to itself in a Select statement and Where is applied. The type cast is not needed in this case, but can be easily overlooked and cause the issue that's hard to diagnose.

```
Exception message: Object reference not set to an instance of an object.
Stack trace:
   at LinqToDB.Linq.Builder.SelectContext.<>c.<ConvertToIndexInternal>b__49_2(ValueTuple`4 context, Int32 n, IBuildContext ctx, Expression ex, Int32 l, Expression _)
   at LinqToDB.Linq.Builder.SelectContext.ProcessMemberAccess[T,TContext](TContext context, Expression expression, MemberExpression levelExpression, Int32 level, Func`7 action)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertCompare(IBuildContext context, ExpressionType nodeType, Expression left, Expression right)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.CountBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Program.<Main>$(String[] args) in :line 16
```

### Steps to reproduce

```c#
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.Mapping;

var db = new DataConnection(LinqToDB.ProviderName.SqlServer2019,
  @"Server=.\;Database=Test;Trusted_Connection=True;");

var q = db.GetTable<UserAccount>().Select(a => new 
{
    Account = (UserAccount)a
}).Where(cwa => cwa.Account.ID == 1);

var r = q.Count();

[Table(Name = "[dbo].[UserAccounts]")]
public class UserAccount
{
    [Column]
    public int ID { get; set; }
}
```

### Environment details

`Linq To DB` version: 5.2.2

Database (with version): SQL Server 2019

ADO.NET Provider (with version): Microsoft.Data.SqlClient 4.1.0

Operating system: Windows 11

.NET Version: .NET7

**Comment by MaceWindu** [comment]
Fixed in `6.0.0-preview.1`
