### ISSUE TITLE
Object refrence error when used dataContext.BulkCopyAsync in Oracle

### ISSUE THREAD

**Issue by vishal0909** [linq2db/linq2db#4216]
Hello 

I have to get records and copy into tables. I am using stored procedure for SQL server. But right now sql server stored procudure is not working, so I created method into C#. 
Method is working quite good for SQL server, but I am getting an error for Oracle.

`
System.NullReferenceException: 'Object reference not set to an instance of an object.'
`

```
var query = from a in _companyUserRepository.Table
                        where a.CompanyID == comapnyID
                        && a.IsCompanyOwner
                        select a.UserID;
            var userID = await query.FirstOrDefaultAsync();

            ///Finance Account Insert
            var finaceAccounts = await (
                        from a in _financeAccountRepository.Table
                        where a.CompanyID == defaulCompanyID
                        && a.IsActive && !a.IsDeleted
                        select new FinanceAccount
                        {
                            CompanyID = comapnyID,
                            Code = a.Code,
                            Name = a.Name,
                            Name_EN = a.Name_EN,
                            Description = a.Description,
                            Description_EN = a.Description,
                            IsActive = a.IsActive,
                            IsDeleted = a.IsDeleted,
                            IsBankAccount = a.IsBankAccount,
                            CreatedUserID = a.CreatedUserID,
                            CreatedDate = a.CreatedDate,
                            ModifiedUserID = a.ModifiedUserID,
                            ModifiedDate = a.ModifiedDate
                        }
                    ).ToListAsync();
            await _financeAccountRepository.InsertAsync(finaceAccounts);

```
```
public virtual async Task InsertAsync(IList<TEntity> entities)
        {
            if (entities == null)
                throw new ArgumentNullException(nameof(entities));

            using var transaction = new TransactionScope(TransactionScopeAsyncFlowOption.Enabled);
            await _dataProvider.BulkInsertEntitiesAsync(entities);
            transaction.Complete();
        }
```

I have to getting error from below statement

`
await _dataProvider.BulkInsertEntitiesAsync(entities);
`

Can you please someone help to do figure out this.

**Comment by sdanyliv** [comment]
Not sure, that latest version has fix. Looks like function `RetrieveIdentity` has issue. But not updating several years can be issue also.

**Comment by vishal0909** [comment]
Can you please confirm, which version has resolved this issue. Becauase there is lot's of changes. So I have to do carefull about it.

**Comment by vishal0909** [comment]
I upgrade linq2db. I removed System.Data.Oracle client object.
I added below nuget package, but result is same.
https://www.nuget.org/packages/dotNetCore.Data.OracleClient

<img width="621" alt="image" src="https://github.com/linq2db/linq2db/assets/16779274/81f8b0e4-278e-45db-ad05-6fbbf01bebec">

 ```
 at System.Data.OracleClient.OracleDataReader.GetOracleNumber(Int32 i)
   at System.Data.OracleClient.OracleDataReader.GetOracleValue(Int32 i)
   at System.Data.OracleClient.OracleDataReader.GetProviderSpecificFieldType(Int32 i)
   at LinqToDB.DataProvider.DataProviderBase.GetReaderExpression(DbDataReader reader, Int32 idx, Expression readerExpression, Type toType)
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.GetReaderExpression(DbDataReader reader, Int32 idx, Expression readerExpression, Type toType)
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.GetColumnReader(IDataContext dataContext, MappingSchema mappingSchema, DbDataReader dataReader, Type type, IValueConverter converter, Int32 idx, Expression dataReaderExpr, Boolean forceNullCheck)
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.Reduce(IDataContext dataContext, DbDataReader dataReader)
   at LinqToDB.Data.CommandInfo.<>c__87`1.<GetObjectReader>b__87_2(DataConnection dc, DbDataReader dr, Type type, Int32 idx, Expression dataReaderExpr, IValueConverter conv)
   at LinqToDB.Data.CommandInfo.CreateObjectReader[T](DataConnection dataConnection, DbDataReader dataReader, Func`7 getMemberExpression)
   at LinqToDB.Data.CommandInfo.<>c__87`1.<GetObjectReader>b__87_0(ICacheEntry`2 e, ValueTuple`2 context)
   at LinqToDB.Common.Internal.Cache.CacheExtensions.GetOrCreate[TItem,TKey,TContext](IMemoryCache`2 cache, TKey key, TContext context, Func`3 factory)
   at LinqToDB.Data.CommandInfo.GetObjectReader[T](DataConnection dataConnection, DbDataReader dataReader, String sql, String additionalKey)
   at LinqToDB.Data.CommandInfo.Execute[T]()
   at LinqToDB.Data.DataConnectionExtensions.Execute[T](DataConnection connection, String sql)
   at LinqToDB.Tools.DataExtensions.GetDefaultIdentityImpl[T](DataConnection context, IList`1 sourceList, EntityDescriptor entityDescriptor, ColumnDescriptor column, ISqlBuilder sqlBuilder)
   at LinqToDB.Tools.DataExtensions.RetrieveIdentity[T](IEnumerable`1 source, DataConnection context, Boolean useSequenceName, Boolean useIdentity)
   at Plan.FixedAssets.Core.DataProviders.BaseDataProvider.<BulkInsertEntitiesAsync>d__16`1.MoveNext() in D:\Application\ArtSolutions\PLAN 2.0\Fixed Assets\Plan.FixedAssets.Core\DataProviders\BaseDataProvider.cs:line 255

```

I have to create connetion string, so I have to used this one.

```
public string BuildConnectionString(IConnectionStringInfo connectionString)
        {
            var builder = new OracleConnectionStringBuilder
            {
                DataSource = connectionString.ServerName,
                PersistSecurityInfo = false,
                IntegratedSecurity = connectionString.IntegratedSecurity
            };

            if (!connectionString.IntegratedSecurity)
            {
                builder.UserID = connectionString.Username;
                builder.Password = connectionString.Password;
            }

            return builder.ConnectionString;
        }

        protected override DbConnection GetInternalDbConnection(string connectionString)
        {
            if (string.IsNullOrEmpty(connectionString))
                throw new ArgumentException(nameof(connectionString));

            return new OracleConnection(connectionString);
        }
```

**Comment by viceroypenguin** [comment]
> Make sure you use managed Oracle provider https://www.nuget.org/packages/Oracle.ManagedDataAccess (netfx) or https://www.nuget.org/packages/Oracle.ManagedDataAccess.Core (netcore)

As stated, these are the only Oracle supported by linq2db. Please try one of these, depending on which version of .net you're using.

**Comment by MaceWindu** [comment]
We also support ODP.NET and DevArt providers for Oracle, but yes, I would recommend to use official managed providers from Oracle  I linked above.

dotNetCore.Data.OracleClient is just a clone of System,Data.OracleClient from Mono and also not supported.

**Comment by MaceWindu** [comment]
unsupported provider
