### ISSUE TITLE
Exception thrown when InnerJoin applied over arrays, prepared with AsQueryable

### ISSUE THREAD

**Issue by Shiko1st** [linq2db/linq2db#4240]
Testing with in-memory queryables is very useful for lightweight unit tests. Let's take a look at the following test class with xUnit framework (there is no difference what test framework is used or even a totally clean app):
```csharp
public class JoinTestsClass
{
    public class Entity
    {
        public int Id { get; set; }
    }

    public class JoinResult
    {
        public Entity A { get; set; }
        public Entity B { get; set; }
    }
    
    public static readonly IQueryable<Entity> QueryA = new[] { new Entity { Id = 1 } }.AsQueryable();
    public static readonly IQueryable<Entity> QueryB = new[] { new Entity { Id = 1 } }.AsQueryable();

    [Fact]
    public void TestJoin()
    {
        var result = QueryA
            .InnerJoin(
                QueryB,
                static (eA, eB) => eA.Id == eB.Id,
                static (eA, eB) => new JoinResult { A = eA, B = eB })
            .ToArray();
    }

    [Fact]
    public async Task TestJoinAsync()
    {
        var result = await QueryA
            .InnerJoin(
                QueryB,
                static (eA, eB) => eA.Id == eB.Id,
                static (eA, eB) => new JoinResult { A = eA, B = eB })
            .ToArrayAsyncLinqToDB();
    }
}
```

Execution of the `TestJoin` test produces the following exception:
```
System.InvalidOperationException
There is no method 'Join' on type 'LinqToDB.LinqExtensions' that matches the specified arguments
   at System.Linq.EnumerableRewriter.FindMethod(Type type, String name, ReadOnlyCollection`1 args, Type[] typeArgs)
   at System.Linq.EnumerableRewriter.VisitMethodCall(MethodCallExpression m)
   at System.Linq.EnumerableQuery`1.GetEnumerator()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at Xxx.UnitTests.Join.JoinTestsClass.TestJoin() in JoinTestsClass.cs:line 25
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodInvoker.Invoke(Object obj, IntPtr* args, BindingFlags invokeAttr)
```

Execution of the `TestJoinAsync` test produces the following exception:
```
System.ArgumentException
Field '_queryCompiler' defined on type 'Microsoft.EntityFrameworkCore.Query.Internal.EntityQueryProvider' is not a field on the target object which is of type 'System.Linq.EnumerableQuery`1[Xxx.UnitTests.Join.JoinTestsClass+JoinResult]'.
   at System.Reflection.RtFieldInfo.GetValue(Object obj)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.GetCurrentContext(IQueryable query)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.ToLinqToDB[T](IQueryable`1 query)
   at LinqToDB.EntityFrameworkCore.LinqToDBForEFExtensions.ToArrayAsyncLinqToDB[TSource](IQueryable`1 source, CancellationToken token)
   at Xxx.UnitTests.Join.JoinTestsClass.TestJoinAsync() in JoinTestsClass.cs:line 36
   at Xunit.Sdk.TestInvoker`1.<>c__DisplayClass48_0.<<InvokeTestMethodAsync>b__1>d.MoveNext() in /_/src/xunit.execution/Sdk/Frameworks/Runners/TestInvoker.cs:line 264
--- End of stack trace from previous location ---
   at Xunit.Sdk.ExecutionTimer.AggregateAsync(Func`1 asyncAction) in /_/src/xunit.execution/Sdk/Frameworks/ExecutionTimer.cs:line 48
   at Xunit.Sdk.ExceptionAggregator.RunAsync(Func`1 code) in /_/src/xunit.core/Sdk/ExceptionAggregator.cs:line 90
```
### Environment details

`Linq To DB` version: 5.2.2
`Linq To DB Entity Framework Core` version: 7.5.0
Database (with version): no database
.NET Version: 7

**Comment by viceroypenguin** [comment]
On the sync version, even though `.InnerJoin()` is used, because the underlying context is an enumerable, there's place for l2db to get involved in the query. `InnerJoin` (along with most methods on l2db) assumes that the underlying `IQueryable` is coming from l2db in some form; whether it's an l2db Table or an EFC Set with a `ToLinqToDBTable()` on it. This is because we don't execute queries on random `IQueryable`, we have to know how to query the source, and to do that, we have to know what the source is.

The async version is essentially the same thing, just with a different path to failure. 

l2db doesn't support running queries on plain enumerables, and most of the methods in l2db do not have in-memory equivalents available in the code. It is primarily and foremost a SQL translator, working against an engine that we can send SQL to.

**Comment by sdanyliv** [comment]
`QueryA` and `QueryB` is not started from linq2db `IQueryable` implementation.
What you can do is to call linq2db `AsQueryable(db)` method:
```cs
    public static readonly IQueryable<Entity> QueryA(IDataContext db) => new[] { new Entity { Id = 1 } }.AsQueryable(db);
    public static readonly IQueryable<Entity> QueryB(IDataContext db) => new[] { new Entity { Id = 1 } }.AsQueryable(db);
```
Anyway better to show real EF Core query and what you are trying to achieve.

**Comment by Shiko1st** [comment]
> Anyway better to show real EF Core query and what you are trying to achieve.

There is no real EF Core queries and I want to achive exactly what I described — to unit-test some pieces of code that may use or may not use linq2db routines without any real database and mappings, over some static predefined data.

Therefore there is no any real database or database context available and I prefer to have no one.

**Comment by viceroypenguin** [comment]
That won't be possible with a majority of l2db methods, as they are "server-side only"; this means that they do not have in-memory implementations, they are merely placeholders for the translation engine to write SQL. As such, l2db requires a connection to a SQL engine of some kind in order to interpret the sql and execute the query. 

You will need to either unit-test against a db engine (recommended) or move queries to a repository interface and mock that.
