### ISSUE TITLE
Unexpected SQL Generation with GroupBy

### ISSUE THREAD

**Issue by boginw** [linq2db/linq2db#4256]
### Describe your issue

It seems that linq2db doesn't handle the grouping of projections correctly when the projection includes instantiating a class. 

Consider the following (minimized) example:

```csharp
var headers =
    context.GetTable<NavPurchInvHeader>()
        .Select(it => new TestHeader
        {
            IsActive = true, // <-- notable
            Other = Convert.ToBoolean(it.PortfolioCustomer)
        })
        .GroupBy(it => it)
        .Select(it => it.Key);
```

The above example produces the following (SQL Server) SQL:

```sql
SELECT
    [t1].[c1],
    [t1].[Other]
FROM
    (
        SELECT
            Convert(Bit, [it].[Portfolio Customer]) as [Other],
            1 as [IsActive],
            1 as [c1]
        FROM
            [Purch_ Inv_ Header] [it]
    ) [t1]
GROUP BY
    [t1].[Other],
    [t1].[IsActive]
```

The SQL produced includes two copies of the `IsActive` field, but one is being selected and the other is being grouped by, which results in an error:

```
Column 't1.c1' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
```

I think it has something to do with the projection to a class, as when removing `TestHeader` and simply mapping to an anonymous object then `IsActive` is grouped by and selected correctly.

<details>
<summary>Full Stacktrace</summary>

```
Unhandled exception. System.Data.SqlClient.SqlException (0x80131904): Column 't1.c1' is invalid in the select list because it is not contained in either an aggregate function or the GROUP BY clause.
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken token)
   at linq2db_mssql_group_by_bug.Program.Main() in /home/bogi/projects/linq2db-mssql-group-by-bug/linq2db-mssql-group-by-bug/Program.cs:line 43
   at linq2db_mssql_group_by_bug.Program.Main() in /home/bogi/projects/linq2db-mssql-group-by-bug/linq2db-mssql-group-by-bug/Program.cs:line 43
   at linq2db_mssql_group_by_bug.Program.<Main>()

```
</details>

### Steps to reproduce

Repo with reproducible bug: [Program.cs](https://github.com/boginw/linq2db_mssql_group_by_bug/blob/main/linq2db-mssql-group-by-bug/Program.cs)

### Environment details

`Linq To DB` version: *5.2.1*

Database (with version): *SQL Server 2017*

ADO.NET Provider (with version): *System.Data.SqlClient 4.8.5*

Operating system: *Ubuntu*

.NET Version: *7.0*

**Comment by igor-tkachev** [comment]
Cant reproduce. This test 

```c#
[Test]
public void GroupByTypeTest([DataSources] string context)
{
	using var db = GetDataContext(context);

	AssertQuery(
		db.Types
			.Select(it => new
			{
				IsActive = true,
				Other    = Convert.ToBoolean(it.SmallIntValue)
			})
			.GroupBy(it => it)
			.Select(it => it.Key));
}
```

generates the following SQL

```sql
SELECT
	[t1].[IsActive],
	[t1].[Other]
FROM
	(
		SELECT
			1 as [IsActive],
			Convert(Bit, [it].[SmallIntValue]) as [Other]
		FROM
			[LinqDataTypes] [it]
	) [t1]
GROUP BY
	[t1].[IsActive],
	[t1].[Other]
```

**Comment by boginw** [comment]
Hi @igor-tkachev and thanks for taking the time to look at this. The key difference I found, is whether or not you're using a class or an anonymous object in the projection. I also found it to work perfectly when not using a class, but if you try to modify your example to something like the following, it should break:

```csharp
class GroupByTypeTestClass {
        public required bool IsActive { get; set; }
        public required bool Other { get; set; }
}

[Test]
public void GroupByTypeTest([DataSources] string context)
{
	using var db = GetDataContext(context);

	AssertQuery(
		db.Types
			.Select(it => new GroupByTypeTestClass
			{
				IsActive = true,
				Other    = Convert.ToBoolean(it.SmallIntValue)
			})
			.GroupBy(it => it)
			.Select(it => it.Key));
}
```

That is, at least, the thing I did in my [reproducibility repo](https://github.com/boginw/linq2db_mssql_group_by_bug/blob/main/linq2db-mssql-group-by-bug/Program.cs).

**Comment by MaceWindu** [comment]
Looking into it. Issue caused by IsActive property being nullable in your repro
