### ISSUE TITLE
Instance property or field with name DebugView not found on type System.Linq.Expressions.Expression

### ISSUE THREAD

**Issue by DoubleDBE** [linq2db/linq2db#4263]
When we compile our .NET MAUI application for Android in Release mode, we get the following exception when creating an instance of our database class.

It doesn't matter when tested in an emulator or on an actual device. Same outcome.

In Debug mode everything works fine.

```
System.InvalidOperationException: Instance property or field with name DebugView not found on type System.Linq.Expressions.Expression
   at LinqToDB.Expressions.ExpressionHelper.PropertyOrField(Expression obj, String name)
   at LinqToDB.Expressions.ExpressionExtensions.GetDebugView(Expression expression)
   at LinqToDB.Common.Internal.IdentifierBuilder.GetObjectID(Expression ex)
   at LinqToDB.Mapping.AssociationAttribute.GetObjectID()
   at LinqToDB.Metadata.FluentMetadataReader.CalculateObjectID()
   at LinqToDB.Metadata.FluentMetadataReader..ctor(IReadOnlyDictionary`2 typeAttributes, IReadOnlyDictionary`2 memberAttributes, IReadOnlyList`1 orderedMembers)
   at LinqToDB.Mapping.FluentMappingBuilder.Build()
```
### Steps to reproduce

The issue seems to be coming from the `FluentMappingBuilder`, especially when using an `Expression` and calling `.Association(...)`.

When those are removed, it works, but then of course `.LoadWith(...)` doesn't work. So that's not an option.

[A repro project can be found here.](https://github.com/DoubleDBE/Linq2dbMauiCrash)

Files of interest:

- Database2.cs
- MainPage.xaml.cs

When you want to compile the project in Release mode, you should use the following command:

`dotnet publish -f:net7.0-android -c:Release`

### Environment details

`Linq To DB` version: *5.2.2, also tried 5.3.0*

Database (with version): *SQLite*

ADO.NET Provider (with version): *Microsoft.Data.Sqlite 7.0.10*

Operating system: *Android*

.NET Version: *.NET 7.0-android*

**Comment by DoubleDBE** [comment]
For anyone experiencing the same issue, I finally solved it on my own by adding the following to my csproj:

I'm not going to close this issue because IMO this needs to be addressed.

```
<ItemGroup>
	<TrimmerRootAssembly Include="System.Linq.Expressions" RootMode="entrypoint" />
</ItemGroup>
```

**Comment by DoubleDBE** [comment]
Hi there,

I just tried the preview version and all seems to be working fine now, awesome!
