### ISSUE TITLE
An exception is thrown when Update<BaseEntity> is called with InheritanceMapping definition

### ISSUE THREAD

**Issue by FilipCalek** [linq2db/linq2db#4280]
Hi,

when I define this simple model:

```
[InheritanceMapping(Code = "DISPLAY", Type = typeof(DisplayDevice))]
[InheritanceMapping(Code = "TV", Type = typeof(TvDevice))]
[Table("Device")]
public abstract class DeviceBase
{
    [Column]
    [PrimaryKey]
    public int Id { get; set; }
    
    [Column]
    public string? SerialNumber { get; set; }
    
    [Column(IsDiscriminator = true)]
    public abstract string DeviceType { get; set; }
}

public class DisplayDevice : DeviceBase
{
    public override string DeviceType { get; set; } = "DISPLAY";
}

public class TvDevice : DeviceBase
{
    public override string DeviceType { get; set; } = "TV";
    
    [Column]
    public string? Location { get; set; }
}
```

... and I call Insert / Update methods like this:

```
var displayDevice = new DisplayDevice { Id = 1, SerialNumber = "Disp00001" };
var tvDevice = new TvDevice { Id = 2, SerialNumber = "TV00001", Location = "Something" };

using (var db = new Linq2dbDataManager())
{
    db.Insert<DeviceBase>(tvDevice);
    db.Insert<DeviceBase>(displayDevice);
    
    db.Update<DeviceBase>(tvDevice);
    db.Update<DeviceBase>(displayDevice);
}
```

... the last update fails with exception:

```
System.ArgumentException: Property 'System.String Location' is not defined for type 'LinqTestNet6.Entities.DisplayDevice' (Parameter 'property')
   at System.Linq.Expressions.Expression.Property(Expression expression, PropertyInfo property)
   at System.Linq.Expressions.Expression.MakeMemberAccess(Expression expression, MemberInfo member)
   at LinqToDB.Expressions.TransformVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.ExpressionExtensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Expressions.ExpressionExtensions.GetBody(LambdaExpression lambda, Expression exprToReplaceParameter)
   at LinqToDB.Expressions.InternalExtensions.ApplyLambdaToExpression(LambdaExpression convertLambda, Expression expression)
   at LinqToDB.Linq.QueryRunner.GetParameter(Type type, IDataContext dataContext, SqlField field)
   at LinqToDB.Linq.QueryRunner.Update`1.CreateQuery(IDataContext dataContext, EntityDescriptor descriptor, T obj, UpdateColumnFilter`1 columnFilter, String tableName, String serverName, String databaseName, String schemaName, TableOptions tableOptions, Type type)
   at LinqToDB.Linq.QueryRunner.Update`1.<>c.<Query>b__2_0(ICacheEntry`2 entry, ValueTuple`8 key, ValueTuple`3 context)
   at LinqToDB.Common.Internal.Cache.CacheExtensions.GetOrCreate[TItem,TKey,TDerivedKey,TContext](IMemoryCache`2 cache, TDerivedKey key, TContext context, Func`4 factory)
   at LinqToDB.Linq.QueryRunner.Update`1.Query(IDataContext dataContext, T obj, UpdateColumnFilter`1 columnFilter, String tableName, String serverName, String databaseName, String schemaName, TableOptions tableOptions)
   at LinqToDB.DataExtensions.Update[T](IDataContext dataContext, T obj, UpdateColumnFilter`1 columnFilter, String tableName, String databaseName, String schemaName, String serverName, TableOptions tableOptions)
   at LinqToDB.DataExtensions.Update[T](IDataContext dataContext, T obj, String tableName, String databaseName, String schemaName, String serverName, TableOptions tableOptions)
   at Program.<Main>$(String[] args) in C:\Pool\Tests\ConsoleTest\LinqTestNet6\Program.cs:line 48
```

There is no issue when I call the Update method with child generic types or without them like this:

```
db.Update<DisplayDevice>(displayDevice);
db.Update(displayDevice);
```

Since Insert method seems to work correctly I tried to compare it to Update method in linq2db project and I found this small difference in the class _QueryRunner_:

**Insert**

_QueryRunner.Insert<T>.CreateQuery_

```
var sqlTable = new SqlTable(descriptor);
```

**Update**

_QueryRunner.Update<T>.CreateQuery_

```
var sqlTable = SqlTable.Create<T>(dataContext);
```

So I replaced that static "SqlTable.Create" with "new SqlTable(descriptor)" and it began to work.

The question is. Can it be fixed that way? Does this modification cause any other problems?

### Environment details

`Linq To DB` version: *5.2.2*

Database (with version): *SQL Server 2016*

Operating system: *Win 10*

.NET Version: *NET 6*

**Comment by MaceWindu** [comment]
You fix should be correct. Looks like we forgot this change in #1070
