### ISSUE TITLE
Invoking lambda with Contains() causes exception

### ISSUE THREAD

**Issue by ossaltu** [linq2db/linq2db#429]
I wrote some code which combines several lambdas into one and then use combined lambda in .Where(). Everything works fine, except the case when I use Contains() in lambda. Here is the example:

```
ParameterExpression lambdaParameter = Expression.Parameter(typeof(Workflow), "t");
Expression<Func<Workflow, bool>> filterExpression = w => model.StatusFilter.Contains(w.Status);
Expression<Func<Workflow, bool>> lambda = Expression.Lambda<Func<Workflow, bool>>(Expression.Invoke(filterExpression, lambdaParameter), lambdaParameter);
var result = _db.Workflows.Where(lambda).ToList();
```

Upon execution, I get the "Cannot be converted to SQL" exception.
If I use expression that does not use .Contains(), no exception is thrown, e.g: 

`
Expression<Func<Workflow, bool>> filterExpression = w => w.Status == WorkflowStatuses.Completed;
`

Passing expression directly to .Where() also works fine:

`
var result = _db.Workflows.Where(w => model.StatusFilter.Contains(w.Status)).ToList();
`

Might this be a bug, or am I missing something?

**Comment by mdvtj** [comment]
It seems the handmade lambda expression (first code block) results in a different expression tree than the one created by the compiler (third code block).

Btw, should the third code block look like this?

    var result = _db.Workflows.Where(w => model.StatusFilter.Contains(w.Status)).ToList();

Of what type is `model.StatusFilter`? Could you please provide the full exception message?

**Comment by ossaltu** [comment]
Yes, third code block should be
```
var result = _db.Workflows.Where(w => model.StatusFilter.Contains(w.Status)).ToList();
```
Corrected it in original post.

Type of StatusFilter:
```
IEnumerable<WorkflowStatuses> StatusFilter
```

Full exception text:

```
Sequence 'value(Controllers.WorkflowController+<>c__DisplayClass10_0).model.StatusFilter' cannot be converted to SQL.
```

Stack trace:
```
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ContainsBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.SubQueryToSql(IBuildContext context, MethodCallExpression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.GetQuery(IDataContextInfo dataContextInfo, Expression expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.Execute(IDataContextInfo dataContextInfo, Expression expression)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Controllers.WorkflowController.Index(WorkflowListViewModel model) in D:\Projects\Controllers\WorkflowController.cs:line 49
   at lambda_method(Closure , Object , Object[] )
   at Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.<InvokeActionFilterAsync>d__28.MoveNext()
```

**Comment by mdvtj** [comment]
I vaguely remember that having `Expression.Invoke` in the expression tree is something that may not always work as expected when linq2db tries to analyze the expression tree.

Instead you may want to try replacing it with `Expression.Call` of the `Contains` method.

Example:

```
var lambdaParameter = Expression.Parameter(typeof(Workflow), "t");
var containsMethod = MemberHelper.MethodOf(() => Enumerable.Contains<WorkflowStatuses>(null, null));
var predicate = Expression.Lambda<Func<Workflow, bool>>(
        Expression.Call(
            containsMethod, Expression.Constant(model.StatusFilter),
            Expression.PropertyOrField(lambaParameter, "Status"))
        , lambaParameter);
```

**Comment by ossaltu** [comment]
Found a faster workaround. Instead of `IEnumerable<WorkflowStatuses> StatusFilter` used `ICollection<WorkflowStatuses> StatusFilter`

**Comment by jogibear9988** [comment]
@sdanyliv is this a bug, or wrong use?

**Comment by ili** [comment]
Hard to say... we'll need some time to investigate it. 
In any way, now we should recommend to use `ICollection<T>` types for `Contains` predicates.

**Comment by sdanyliv** [comment]
Closing for now. Looks like it is wrong Expression tree usage.
Will reopen if needed.
