### ISSUE TITLE
Getting ArgumentException with Linq2db 5.3.1 and Npgsql 7.0.6

### ISSUE THREAD

**Issue by vonzshik** [linq2db/linq2db#4313]
### Describe your issue

It seems like `npgsqlInetType.GetConstructor` for `netmaskType = typeof(byte)` returns a constructor with the second argument's type being `int`, which leads to linq2db casting an `int` to `byte`.

![image](https://github.com/linq2db/linq2db/assets/14861420/15ca33f4-aa57-4126-a77a-21583512ad90)

```
Exception message: System.ArgumentException : Expression of type 'System.Byte' cannot be used for constructor parameter of type 'System.Int32' (Parameter 'arguments[1]')

Stack trace:

at System.Dynamic.Utils.ExpressionUtils.ValidateOneArgument(MethodBase method, ExpressionType nodeKind, Expression arguments, ParameterInfo pi, String methodParamName, String argumentParamName, Int32 index)
   at System.Dynamic.Utils.ExpressionUtils.ValidateArgumentTypes(MethodBase method, ExpressionType nodeKind, ReadOnlyCollection`1& arguments, String methodParamName)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, IEnumerable`1 arguments)
   at System.Linq.Expressions.Expression.New(ConstructorInfo constructor, Expression[] arguments)
   at LinqToDB.DataProvider.PostgreSQL.NpgsqlProviderAdapter.GetInstance()
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLMappingSchema.PostgreSQL92MappingSchema..ctor()
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider.GetMappingSchema(PostgreSQLVersion version)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider..ctor(String name, PostgreSQLVersion version)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider92..ctor()

```

### Steps to reproduce

```c#
var db = new DataConnection(new DataOptions()
                .UsePostgreSQL(ConnectionString));
```

### Environment details

`Linq To DB` version: 5.3.1

Database (with version): Postgresql 15

ADO.NET Provider (with version): Npgsql 7.0.6

Operating system: Windows 10

.NET Version: .NET 6.0.23

**Comment by vonzshik** [comment]
Passing `BindingFlags.ExactBinding` to `npgsqlInetType.GetConstructor` call seems to fix the issue.
