### ISSUE TITLE
ArgumentException at GroupJoin

### ISSUE THREAD

**Issue by XeniaLan** [linq2db/linq2db#434]
I have the following lambda expression that I am using to query a database, but it keeps throwing the error:
`System.ArgumentException: An item with the same key has already been added `

```cs
private IEnumerable<object> GetList(string input) {
        var result =
            db.Users.GroupJoin(db.Users_Roles, re => re.Id, ri => ri.UserId, (re, ri) => new
            {
                Name = re.Name,
                Roles = ri.ToList().Select(p => p.Name)
            }).Where(p => p.Name.ToLower().Contains(input.ToLower())).ToList();
}

```
```
StackTrace:
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at LinqToDB.Linq.Builder.JoinBuilder.GroupJoinContext.GroupJoinHelper`2.GetGroupJoin(GroupJoinContext context) at i:\linq2db\Source\Linq\Builder\JoinBuilder.cs:line 321
   at LinqToDB.Linq.Builder.JoinBuilder.GroupJoinContext.BuildExpression(Expression expression, Int32 level) at i:\linq2db\Source\Linq\Builder\JoinBuilder.cs:line 415
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass57.<BuildExpression>b__55(Expression expr) at i:\linq2db\Source\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 151
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) at i:\linq2db\Source\Expressions\Extensions.cs:line 1212
```
  Error getting a combination of: GroupJoin, Contains, Declare a string variable

  Сould you please assist? Thanks!

**Comment by sdanyliv** [comment]
First that i see which type objects you are expected?
IOW what you trying to achieve by this statement?

**Comment by XeniaLan** [comment]
I want to get a list of objects containing fields from the table and a list of objects from another table (Many-to-one) GroupJoin means

**Comment by sdanyliv** [comment]
List of Users, with filled Roles?
If yes, you cannot do this with linq2db in that way.
First you have to select from table Users, put it to the dictionary.
Then you need to select from table User_Roles (and filter by username - means join to Users)
Then fill Roles list on the client using dictionary.

**Comment by XeniaLan** [comment]
Thanks. But  I'd like to use GroupJoin. 

Why next code works without error ArgumentException
 ```
  var result =
            db.Users.GroupJoin(db.Users_Roles, re => re.Id, ri => ri.UserId, (re, ri) => new
            {
                Name = re.Name,
                Roles = ri.ToList().Select(p => p.Name)
            }).Where(p => p.Name.ToLower().Contains("world".ToLower())).ToList()

```

difference: `Contains("world".ToLower()) `and `Contains(input.ToLower())`

**Comment by sdanyliv** [comment]
Could you please post here which SQL is generated?

**Comment by XeniaLan** [comment]
If use code  `Contains(input.ToLower()) ` then  I get ArgumentException (at class GroupJoinHelper , line:
```

 var parameters = context.Builder.CurrentSqlParameters
						.Select((p,i) => new { p, i })
						.ToDictionary(_ => _.p.Expression, _ => _.i)  
```
) 
and query does't generated

If  use code `Contains("world".ToLower())` then 
	1 query : 
	SELECT
	re."Name",
	re."Id"
	FROM
		"Users" re
	WHERE
		Lower(re."Name") LIKE '%world%'

	[2-n] queries:
		
		DECLARE @p1 Uuid -- Guid
		SET   @p1 = '782fb44e-1190-4ecb-a98b-7fc4090a994b'

			SELECT
				t1."Name"
			FROM
				system."Users_Roles" t1
			WHERE
				t1."UserId" = :p1

**Comment by sdanyliv** [comment]
It is related to more sophisticated algorithm with. Currently no supported but in our mind. It should be expanded by two queries and mapped on client side. We will investigate this in the future.

**Comment by MaceWindu** [comment]
Already fixed
