### ISSUE TITLE
SqlGeography mapping error

### ISSUE THREAD

**Issue by MoeHamdan** [linq2db/linq2db#4342]
I have a GEOGRAPHY column type in my table, and when there is a value in that column, linq2db is failing.

Exception message:LinqToDBConvertException exception occurred
LinqToDB.Common.LinqToDBConvertException: Mapping of column 'GeoPosition' value failed, see inner exception for details
 ---> System.InvalidCastException: Unable to cast object of type 'Microsoft.SqlServer.Types.SqlGeography' to type 'Microsoft.Data.SqlClient.Server.IBinarySerialize'.

Stack trace:
` at Microsoft.Data.SqlClient.Server.BinarySerializeSerializer.Deserialize(Stream s)
   at Microsoft.Data.SqlClient.Server.SerializationHelperSql9.Deserialize(Stream s, Type resultType)
   at Microsoft.Data.SqlClient.SqlConnection.GetUdtValue(Object value, SqlMetaDataPriv metaData, Boolean returnDBNull)
   at Microsoft.Data.SqlClient.SqlDataReader.GetValueFromSqlBufferInternal(SqlBuffer data, _SqlMetaData metaData)
   at Microsoft.Data.SqlClient.SqlDataReader.GetValueInternal(Int32 i)
   at Microsoft.Data.SqlClient.SqlDataReader.GetValue(Int32 i)
   at lambda_method465(Closure, DbDataReader)
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(DbDataReader dataReader)
   --- End of inner exception stack trace ---
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(DbDataReader dataReader)
   at lambda_method434(Closure, IQueryRunner, DbDataReader)
   at LinqToDB.Linq.QueryRunner.Mapper`1.Map(IDataContext context, IQueryRunner queryRunner, DbDataReader dataReader, ReaderMapperInfo& mapperInfo)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass5_0`1.<<GetFirstOrDefaultElement>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken)`

### Steps to reproduce

Create a table with a column of type geography
insert a record
generate the model
using c# write query to retrieve that record.

### Environment details

`Linq To DB` version: 5.2.2

Database (with version): SQL Server 16.0.1105.1

Operating system: Debain 11
.NET Version: 7

**Comment by MoeHamdan** [comment]
I did not have Microsoft.Data.SqlClient added to my nuget packages. I had to manually install latest Microsoft.Data.SqlClient after that the issue is gone.
