### ISSUE TITLE
Incorrectly generated query when const is a part of grouping: 42P10: ORDER BY position 0 is not in select list

### ISSUE THREAD

**Issue by ademchenko** [linq2db/linq2db#4349]
### In Postgres

Suppose we have the following table:
```sql
CREATE TABLE foos
(
    b INTEGER NOT NULL 
);
```

The generated code would be:
```c#
	[Table("foos")]
	public partial class Foo
	{
		[Column("b")] public int B { get; set; } // integer
	}
```
Then, suppose we make the following (obviously correct) query:
```c#
  [Test]
    public async Task Issue4349ReproducingTest()
    {
        await using DataConnection dc = new DataConnection(ProviderName.PostgreSQL, _connectionString);

        var queryable = dc.GetTable<Foo>().Select(f1 => new { A = 0, f1.B })
            .GroupBy(r => new { r.A, r.B })
            .Select(g => new
            {
                A = g.Key.A == 0 ? 0 : 1,
                g.Key.B
            }).OrderBy(i => i.A);

        await queryable.ToListAsync();

        TestContext.WriteLine(dc.LastQuery);
    }
```
CUR:
Exception:
```c#
Npgsql.PostgresException : 42P10: ORDER BY position 0 is not in select list

POSITION: 65
Data:
  Severity: ERROR
  InvariantSeverity: ERROR
  SqlState: 42P10
  MessageText: ORDER BY position 0 is not in select list
  Position: 65
  File: parse_clause.c
  Line: 2034
  Routine: findTargetlistEntrySQL92
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|233_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at NpgsqlIssue4349Reproduction.NpgsqlIssue4349Tests.Issue4349ReproducingTest() in 
```

If we look at the generated script we can see that the generated query is incorrect - it tries to order by constant directly (without using its name), and it is treated as a positioning argument by Postgres:
```sql
--  PostgreSQL.9.5 PostgreSQL
SELECT
	0,
	f1.b
FROM
	foos f1
GROUP BY
	f1.b
ORDER BY
	0

```

### Environment details

`Linq To DB` version: *5.3.2*

Database (with version): *Postgres 14.1*

ADO.NET Provider (with version): *npgsql 7.0.6*

The reproducing solution is attached here:
[Linq2dbIssue4349Reproduction.zip](https://github.com/linq2db/linq2db/files/13624206/Linq2dbIssue4349Reproduction.zip)

**Comment by ademchenko** [comment]
@sdanyliv, @MaceWindu, any progress on that query-generating issue?

**Comment by igor-tkachev** [comment]
https://github.com/linq2db/linq2db/pull/4252

**Comment by viceroypenguin** [comment]
@igor-tkachev I don't think this has anything to do with 4252. This is about a bug in the generation, such that it is generating a constant column of `0` and then attempting to order by _that_ column. The original linq does not reference a constant number, which is what you're attempting to address in 4252.

**Comment by ademchenko** [comment]
@sdanyliv, @MaceWindu,  @viceroypenguin, any news on that issue? Thanks in advance!

**Comment by MaceWindu** [comment]
@sdanyliv it is still broken in v6

**Comment by MaceWindu** [comment]
This is fixed in preview-2 in form of removing sort over constant field. You can test it using builds from Azure artifacts. If it is not what you expected - you need to provide better test case

**Comment by ademchenko** [comment]
@MaceWindu , but in the task I described the root cause of the issue - the generator uses constant directly which is wrong:
```
--  PostgreSQL.9.5 PostgreSQL
SELECT
	0,
	f1.b
FROM
	foos f1
GROUP BY
	f1.b
ORDER BY
	0
```
So, instead of that, the query should be like that:
```
--  PostgreSQL.9.5 PostgreSQL
SELECT
	0 as someConst,
	f1.b
FROM
	foos f1
GROUP BY
	f1.b
ORDER BY
	someConst
```
That would be a more proper fix in my opinion.

**Comment by MaceWindu** [comment]
Sort by constant is `no-op` so we optimize it out
