### ISSUE TITLE
MySql's BulkCopy doesn't support custom GuidFormat

### ISSUE THREAD

**Issue by QianMoXi** [linq2db/linq2db#4354]
### Describe your issue

When GuidFormat = MySqlGuidFormat.Binary16 is set, data cannot be written using bulk copy

```
Exception message:
MySqlConnector.MySqlException:"Data too long for column 'ID' at row 1"
Stack trace:
   at MySqlConnector.Core.ServerSession.<ReceiveReplyAsync>d__107.MoveNext() in /_/src/MySqlConnector/Core/ServerSession.cs:line 936
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at System.Runtime.CompilerServices.ConfiguredValueTaskAwaitable`1.ConfiguredValueTaskAwaiter.GetResult()
   at MySqlConnector.Core.ResultSet.<ReadResultSetHeaderAsync>d__2.MoveNext() in /_/src/MySqlConnector/Core/ResultSet.cs:line 37
   at MySqlConnector.MySqlDataReader.ActivateResultSet(CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlDataReader.cs:line 130
   at MySqlConnector.MySqlDataReader.<InitAsync>d__111.MoveNext() in /_/src/MySqlConnector/MySqlDataReader.cs:line 483
   at MySqlConnector.Core.CommandExecutor.<ExecuteReaderAsync>d__0.MoveNext() in /_/src/MySqlConnector/Core/CommandExecutor.cs:line 56
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at MySqlConnector.MySqlCommand.<ExecuteNonQueryAsync>d__78.MoveNext() in /_/src/MySqlConnector/MySqlCommand.cs:line 309
   at LinqToDB.Data.DataConnection.<ExecuteNonQueryAsync>d__10.MoveNext()
   at LinqToDB.Data.DataConnection.<ExecuteNonQueryDataAsync>d__11.MoveNext()
   at LinqToDB.Data.DataConnection.<ExecuteNonQueryDataAsync>d__11.MoveNext()
   at LinqToDB.Data.CommandInfo.<ExecuteAsync>d__55.MoveNext()
   at LinqToDB.DataProvider.MultipleRowsHelper.<ExecuteAsync>d__30.MoveNext()
   at LinqToDB.DataProvider.BasicBulkCopy.<MultipleRowsCopyHelperAsync>d__28.MoveNext()
   at Program.<<Main>$>d__0.MoveNext()
   at Program.<Main>(String[] args)
```

### Steps to reproduce

DDL:
``` sql
CREATE TABLE `Test` (
  `ID` binary(16) NOT NULL,
  `Name` varchar(20) CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci NOT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
```

c# code:
```c#

[Table(Name = "test")]
public class Test
{
    [Column]
    public Guid Id { get; set; }

    [Column]
    public required string Name { get; set; }
}

var connectionString = new MySqlConnectionStringBuilder()
{
    Server     = "",
    UserID     = "root",
    Password   = "",
    Database   = "",
    GuidFormat = MySqlGuidFormat.Binary16 //BulkCopy is affected here
}.ConnectionString;

using var connection = MySqlTools.CreateDataConnection(connectionString);

await connection.InsertAsync(new Test()
{
    Id   = Guid.NewGuid(),
    Name = "null"
});

//insert is normal
await connection.InsertAsync(new Test()
{
    Id   = Guid.NewGuid(),
    Name = "null"
});

//throw MySqlConnector.MySqlException: "Data too long for column 'ID' at row 1"
await connection.BulkCopyAsync(new List<Test>()
{
    new ()
    {
        Id   = Guid.NewGuid(),
        Name = "null"
    }
});

```

### Environment details

`Linq To DB` version: 5.3.2

Database (with version): mysql 8.1.0

ADO.NET Provider (with version): MySqlConnector 2.3.1

Operating system: windows 11 23H2

.NET Version: .net 8

**Comment by ShivamKr7250** [comment]
Assign me this. i would like to resolve this issue

**Comment by MaceWindu** [comment]
Done. Good luck 👍

**Comment by MaceWindu** [comment]
I will check it and probably add some notes how to approach this task a bit later today

**Comment by MaceWindu** [comment]
Ok, checked this issue:
- as label says we already have tests for this issue, but they are not merged yet. You need to cherry-pick test code from this file https://github.com/linq2db/linq2db/pull/4569/files#diff-dd31e31992efad5b60db6ec6087df1325c1cb7edf1359f736f0e16a5444fcedd (`using` + whole `#region issue 4354` region)
- as fix it probably will be enough (at least you should start from it) to add missing literals generation formats to this place https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/DataProvider/MySql/MySqlMappingSchema.cs#L16-L26 - you need to generate binary or string literal in expected format based on data type parameter (DataType + Length properties)

**Comment by ShivamKr7250** [comment]
Okay I will try my best to fix this issue
