### ISSUE TITLE
CTE with custom mapping class not working

### ISSUE THREAD

**Issue by timbze** [linq2db/linq2db#4366]
### Describe your issue

Here's a full repro project. https://github.com/timbze/linq2db-cte-repro

Here's the details based on my current project:

I have these 2 queries, one works and one does not:
#### Does not work
 (the resulting SQL has the UNION ALL one level too deep):
```c#
internal sealed class ProductLabelMappingDto
{
    public ProductLabelDto Label { get; set; }
    public string? FullName { get; set; }
}

var cte = await _context.GetCte<ProductLabelMappingDto>(labels =>
    (from l in _context.ProductLabel
        where l.ParentLabelId == null
        select new ProductLabelMappingDto
        {
            Label = l,
            FullName = l.Name,
        })
    .Concat(
        from pl in _context.ProductLabel
        from recur in labels.InnerJoin(ll => ll.Label.Id == pl.ParentLabelId)
        select new ProductLabelMappingDto
        {
            Label = pl,
            FullName = recur.FullName + " > " + pl.Name,
        }
    )
).ToListAsync();
```

The resulting SQL
```sql
WITH RECURSIVE labels
(
	"Label", -- NOTE should not be here
	"FullName",
	"Id",
	"FullName_1",
	"ShortCode",
	"Description",
	"ParentLabelId"
)
AS
(
	SELECT
		t1."Label_FullName",
		t1."FullName_1",
		t1."Id",
		t1."FullName",
		t1."ShortCode",
		t1."Description",
		t1."ParentLabelId"
	FROM
		(
			SELECT
				l.id as "Id",
				l.name as "FullName",
				l.short_code as "ShortCode",
				l.description as "Description",
				l.parent_label_id as "ParentLabelId",
				l.full_name as "Label_FullName",
				l.name as "FullName_1"
			FROM
				product_label l
			WHERE
				l.parent_label_id IS NULL
			UNION ALL
			SELECT
				pl.id as "Id",
				pl.name as "FullName",
				pl.short_code as "ShortCode",
				pl.description as "Description",
				pl.parent_label_id as "ParentLabelId",
				pl.full_name as "Label_FullName",
				ll."FullName" || ' > ' || pl.name as "FullName_1"
			FROM
				product_label pl
					INNER JOIN labels ll ON (ll."Label" = pl.parent_label_id OR ll."Label" IS NULL AND pl.parent_label_id IS NULL)
		) t1
)
SELECT
	t2."Id",
	t2."FullName_1",
	t2."ShortCode",
	t2."Description",
	t2."ParentLabelId",
	t2."Label",
	t2."FullName"
FROM
	labels t2
```

#### This does work
```c#
var cte = await _context.GetCte<ProductLabelDto>(labels =>
    (from l in _context.ProductLabel
        where l.ParentLabelId == null
        select new ProductLabelDto
        {
            Id = l.Id,
            Name = l.Name,
            FullName = l.Name,
            ShortCode = l.ShortCode,
            Description = l.Description,
            ParentLabelId = l.ParentLabelId,
        })
    .Concat(
        from pl in _context.ProductLabel
        from recur in labels.InnerJoin(ll => ll.Label.Id == pl.ParentLabelId)
        select new ProductLabelDto
        {
            Id = l.Id,
            Name = l.Name,
            ShortCode = l.ShortCode,
            Description = l.Description,
            ParentLabelId = l.ParentLabelId,
            FullName = recur.FullName + " > " + pl.Name,
        }
    )
).ToListAsync();
```

Resulting SQL (works)
```sql
WITH RECURSIVE labels
(
	"Id",
	"Name",
	"ShortCode",
	"Description",
	"ParentLabelId",
	"FullName"
)
AS
(
	SELECT
		l.id,
		l.name,
		l.short_code,
		l.description,
		l.parent_label_id,
		l.name
	FROM
		product_label l
	WHERE
		l.parent_label_id IS NULL
	UNION ALL
	SELECT
		pl.id,
		pl.name,
		pl.short_code,
		pl.description,
		pl.parent_label_id,
		ll."FullName" || ' > ' || pl.name
	FROM
		product_label pl
			INNER JOIN labels ll ON ll."Id" = pl.parent_label_id
)
SELECT
	"dtoProductLabelDto"."Id",
	"dtoProductLabelDto"."Name",
	"dtoProductLabelDto"."ShortCode",
	"dtoProductLabelDto"."Description",
	"dtoProductLabelDto"."ParentLabelId",
	"dtoProductLabelDto"."FullName"
FROM
	labels "dtoProductLabelDto"
```

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
Exception message: 42P19: recursive query "labels" does not have the form non-recursive-term UNION [ALL] recursive-term
Stack trace:
at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
at Npgsql.NpgsqlCommand.ExecuteDbDataReaderAsync(CommandBehavior behavior, CancellationToken cancellationToken)
at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
at LinqToDB.Linq.QueryRunner.ExecuteQueryAsync[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber, Func`2 func, TakeSkipDelegate skipAction, TakeSkipDelegate takeAction, CancellationToken cancellationToken)
at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
```

### Environment details

`Linq To DB` version: *5.3.2*

Database (with version): *PostgreSQL 15*

ADO.NET Provider (with version): *default?*

Operating system: *Ubuntu 22.04*

.NET Version: *8.0*

**Comment by MaceWindu** [comment]
Your second query gives me query parsing error, in 5.3.2/5.4.1. Anyways it is fixed in `6.0.0-preview.1`
