### ISSUE TITLE
Upgrading to 5.4 breaks window query

### ISSUE THREAD

**Issue by dagdynamik** [linq2db/linq2db#4440]
### Describe your issue
upgrading from 5.3.2 to 5.4.0 breaks this query 
    public async Task<List<InstrumentViewModel>?> GetInstrumentsAsync(DateTime aggUntilDate, int? companyIdentityId = null, bool showAll = false, int? instrumentId = null)
        {
            var dateModified = aggUntilDate.Date.AddDays(1);
            var reportingCurrencyId = 1;
            var transactionsAggregateQuery = _reportingContext.InstrumentTransactions.AsNoTracking()
                .Where(t => t.Retracted == null && t.Instrument!.Customer!.IdentityId == companyIdentityId && t.TransactionDate < dateModified)
                .WhereIf(instrumentId.HasValue, t => t.Instrument.InstrumentId == instrumentId)
                .Select(t => new
                {
                    t.TransactionDate,
                    Id = t.InstrumentId,
                    SumOfCostPriceOnOwnedSecurities = Sql.Ext.Sum(InstrumentTransactionsFilterLists.StockCostPriceList.Contains(t.ActionType ?? 0) ? t.Amount : 0)
                        .Over().PartitionBy(t.InstrumentId).OrderBy(t.TransactionDate).ToValue(),
                    SumOfCostPriceOnOwnedSecuritiesInCurrency = Sql.Ext.Sum(InstrumentTransactionsFilterLists.StockCostPriceList.Contains(t.ActionType ?? 0) ? t.CurrencyAmount : 0)
                        .Over().PartitionBy(t.InstrumentId).OrderBy(t.TransactionDate).ToValue(),
                    Quantity = Sql.Ext.Sum(InstrumentTransactionsFilterLists.InstrumentQuantityList.Contains(t.ActionType ?? 0) ? t.Quantity : 0)
                        .Over().PartitionBy(t.InstrumentId).OrderBy(t.TransactionDate).ToValue(),
                    LoanQty = Sql.Ext.Sum(InstrumentTransactionsFilterLists.InstrumentLoanQuantityList.Contains(t.ActionType ?? 0) && t.DueDate >= dateModified ? t.Quantity : 0)
                        .Over().PartitionBy(t.InstrumentId).OrderBy(t.TransactionDate).ToValue(),
                    AmountSold = Sql.Ext.Sum(InstrumentTransactionsFilterLists.SummableActionTypesSales.Contains(t.ActionType ?? 0) ? t.Amount : 0)
                        .Over().PartitionBy(t.InstrumentId).OrderBy(t.TransactionDate).ToValue(),
                    AmountCostReduction = Sql.Ext.Sum(InstrumentTransactionsFilterLists.SummableActionTypesCostReduction.Contains(t.ActionType ?? 0) ? t.Amount : 0)
                        .Over().PartitionBy(t.InstrumentId).OrderBy(t.TransactionDate).ToValue(),
                    Interest = Sql.Ext.Sum(InstrumentTransactionsFilterLists.SummableInterestsType.Contains(t.ActionType ?? 0) ? t.Interests : 0)
                        .Over().PartitionBy(t.InstrumentId).OrderBy(t.TransactionDate).ToValue(),
                    Dividend = Sql.Ext.Sum(InstrumentTransactionsFilterLists.SummableDividend.Contains(t.ActionType ?? 0) ? t.Amount : 0)
                        .Over().PartitionBy(t.InstrumentId).OrderBy(t.TransactionDate).ToValue(),
                    RowNumber = Sql.Ext.RowNumber().Over().PartitionBy(t.InstrumentId).OrderByDesc(t.TransactionDate).ToValue()
                });

            var transactionsAggregateCte = transactionsAggregateQuery.AsCte("transactionsAggregateCte");
            var result = from t in transactionsAggregateCte
                join i in _reportingContext.Instruments on t.Id equals i.Id
                join ai in _reportingContext.AvailableInstruments.AsNoTracking() on i.AvailableInstrumentId equals ai.Id
                join ic in _reportingContext.InstrumentCurrencies.AsNoTracking() on ai.CurrencyCode equals ic.CurrencyCode
                join cm in _reportingContext.CurrencyMappings.AsNoTracking() on ic.Id equals cm.InstrumentCurrencyId
                join ip in _reportingContext.ImportedPrices.AsNoTracking() on i.AvailableInstrumentId equals ip.AvailableInstrumentId into ipgrp
                join ip in _reportingContext.ImportedPrices.AsNoTracking() on cm.AvailableInstrumentFxPairId equals ip.AvailableInstrumentId into curgrp
                join mpf in _reportingContext.InstrumentPrices.AsNoTracking() on i.Id equals mpf.InstrumentId into mpfgrp
                join mpf in _reportingContext.InstrumentTaxValues.AsNoTracking() on i.Id equals mpf.InstrumentId into taxgrp
                where cm.ReportingCurrencyId == reportingCurrencyId && t.RowNumber == 1 && !(t.Quantity == 0 && !showAll)
                //orderby t.TransactionDate descending
                select new
                {
                    DivideByFactor = t.RowNumber,
                    t.Quantity,
                    AvailableInstrument = ai,
                    Instrument = i,
                    InstrumentCurrency = ic,
                    t.Interest,
                    t.Dividend,
                    t.SumOfCostPriceOnOwnedSecurities,
                    t.SumOfCostPriceOnOwnedSecuritiesInCurrency,
                    t.LoanQty,
                    t.AmountSold,
                    t.AmountCostReduction,
                    Dimension1 = "",
                    Dimension2 = "",
                    Dimension3 = "",
                    Dimension4 = "",
                    Dimension5 = "",
                    Dimension6 = "",
                    Dimension10 = "",
                    Dimension11 = "",
                    Dimension12 = "",
                    Dimension13 = "",
                    Dimension14 = "",
                    Dimension20 = "",
                    Dimension21 = "",
                    cm.CurrencyMultiplier,
                    LastManualPrice =
                        mpfgrp.OrderByDescending(x => x.FromDate)
                            .Where(manualPrice => manualPrice.FromDate < dateModified)
                            .Select(x => new
                            {
                                x.FromDate, x.ToDate, x.SellPrice, x.InstrumentCurrencyId,
                                ManualPriceCurrency = x.InstrumentCurrency.CurrencyMapping.AvailableInstrumentFxPair.ImportedPrices
                                    .OrderByDescending(y => y.Date)
                                    // .()
                                    .FirstOrDefault(y => y.Date < dateModified),
                                ManualCurrencyMultiplier = x.InstrumentCurrency.CurrencyMapping.CurrencyMultiplier,
                                ManualCurrencyCode = x.InstrumentCurrency.CurrencyCode,
                            }).FirstOrDefault(),
                    LastTaxValue =
                        taxgrp.OrderByDescending(x => x.FromDate)
                            .Where(taxValue => taxValue.FromDate < dateModified)
                            .Select(x => new { x.FromDate, x.TaxValue }).FirstOrDefault() ?? null,
                    LastImportedPrice =
                        ipgrp.OrderByDescending(x => x.Date)
                            .Where(x => x.Date < dateModified)
                            .Select(x => new { x.Date, x.SellPrice }).FirstOrDefault() ?? null,
                    LastImportedCurrency =
                        curgrp.OrderByDescending(x => x.Date)
                            .Where(x => x.Date < dateModified)
                            .Select(x => new { x.Date, x.SellPrice }).FirstOrDefault() ?? null
                };

            var queryResult = await result.ToListAsyncLinqToDB();
            
If you have a question, first try to check our [documentation](https://linq2db.github.io/), especially [FAQ](https://linq2db.github.io/articles/FAQ.html) and search in [issues](https://github.com/linq2db/linq2db/issues) and [discussions](https://github.com/linq2db/linq2db/discussions) - maybe your question already answered there.

If you still have questions or want to start general discussion, please create new topic in [discussions](https://github.com/linq2db/linq2db/discussions).

If you are seeing an exception, include the full exceptions details (message and stack trace).

```
fail: Dynamik.Shared.Api.Middleware.ErrorHandlingMiddleware[0]
      => SpanId:d250369a643dc2e0, TraceId:8fd5c20adc26b091a47cd7615b4ea664 => ConnectionId:0HN1RSBA8RC2I => RequestPath:/companies/538/GlReports/Balance/2024-03-04 RequestId:0HN1RSBA8RC2I:00000002
      Unexpected Api error
      System.MissingMethodException: Method not found: 'Void LinqToDB.Mapping.MappingSchema.SetConvertExpression(System.Type, System.Type, System.Linq.Expressions.LambdaExpression, Boolean)'.
         at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.<>c__DisplayClass14_0.<DefineConvertors>g__MapEFCoreType|1(Type modelType)
         at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.CreateMappingSchema(IModel model, IMetadataReader metadataReader, IValueConverterSelector convertorSelector, DataOptions dataOptions)
         at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.<>c__DisplayClass17_0.<GetMappingSchema>b__0(ICacheEntry e)
         at Microsoft.Extensions.Caching.Memory.CacheExtensions.GetOrCreate[TItem](IMemoryCache cache, Object key, Func`2 factory)
         at LinqToDB.EntityFrameworkCore.LinqToDBForEFToolsImplDefault.GetMappingSchema(IModel model, IMetadataReader metadataReader, IValueConverterSelector convertorSelector, DataOptions dataOptions)
         at LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.CreateLinqToDBContext(DbContext context, IDbContextTransaction transaction)
         at LinqToDB.EntityFrameworkCore.LinqToDBForEFTools.<>c__DisplayClass18_0.<InitializeInternal>b__1(IQueryable queryable)
         at LinqToDB.LinqExtensions.AsCte[TSource](IQueryable`1 source, String name)
         at Dynamik.Reporting.Services.WindowQuerys.PortfolioWindowQueryBuilders.GetInstrumentsAsync(DateTime aggUntilDate, Nullable`1 companyIdentityId, Boolean showAll, Nullable`1 instrumentId) in /Src/Services/Reporting/Dynamik.Reporting.Services/WindowQuerys/PortfolioWindowQueryBuilders.cs:line 63
         at Dynamik.Reporting.Services.WindowQuerys.PortfolioWindowQueryBuilders.<>c__DisplayClass5_0.<<GetInstrumentsCachedAsync>b__0>d.MoveNext() in /Src/Services/Reporting/Dynamik.Reporting.Services/WindowQuerys/PortfolioWindowQueryBuilders.cs:line 53
      --- End of stack trace from previous location ---
         at LazyCache.CachingService.<>c__DisplayClass28_1`1.<<GetOrAddAsync>b__1>d.MoveNext()
      --- End of stack trace from previous location ---
         at LazyCache.CachingService.GetOrAddAsync[T](String key, Func`2 addItemFactory, MemoryCacheEntryOptions policy)
         at Dynamik.Reporting.Services.WindowQuerys.PortfolioWindowQueryBuilders.GetInstrumentsCachedAsync(Int32 companyIdentityId, OverviewRequest request) in /Src/Services/Reporting/Dynamik.Reporting.Services/WindowQuerys/PortfolioWindowQueryBuilders.cs:line 50
         at Dynamik.Reporting.Services.AccountTransactionService.GetTotalPortfolioValueYearToDateAsyncWithLongTerm(Nullable`1 companyIdentityId, Boolean longTerm, Nullable`1 dateUb, Nullable`1 dateIb) in /Src/Services/Reporting/Dynamik.Reporting.Services/AccountTransactionService.cs:line 448
         at Dynamik.Reporting.Services.AccountTransactionService.GetBalanceReport(Int32 companyIdentityId, DateTime toDate) in /Src/Services/Reporting/Dynamik.Reporting.Services/AccountTransactionService.cs:line 56
         at Dynamik.Reporting.Api.Controllers.GlReportsController.Balance(Int32 companyIdentityId, DateTime toDate) in /Src/Services/Reporting/Dynamik.Reporting.Api/Controllers/GlReportsController.cs:line 26
         at lambda_method285(Closure, Object)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(ActionContext actionContext, IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Logged|12_1(ControllerActionInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeInnerFilterAsync>g__Awaited|13_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
         at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|7_0(Endpoint endpoint, Task requestTask, ILogger logger)
         at Dynamik.Shared.Api.Middleware.ErrorHandlingMiddleware.Invoke(HttpContext context) in /Src/Services/Shared/Dynamik.Shared.Api/Middleware/ErrorHandlingMiddleware.cs:line 25
{"exception":"System.MissingMethodException","error":"Method not found: \u0027Void LinqToDB.Mapping.MappingSchema.SetConvertExpression(System.Type, System.Type, System.Linq.Expressions.LambdaExpression, Boolean)\u0027.","errorDetail":null}
info: Microsoft.AspNetCore.Hosting.Diagnostics[2]
```

`Linq To DB` version: *?*

Database (with version): postgress 15

**Comment by MaceWindu** [comment]
Yep, need to update linq2db.EntityFrameworkCore to support 5.4.0. Will try to release it today.
Close as https://github.com/linq2db/linq2db.EntityFrameworkCore/issues/378 duplicate
