### ISSUE TITLE
Connection pool depletion when using new DataContext(...), together with LoadWith and FirstOrDefault (or SingleOrDefault)

### ISSUE THREAD

**Issue by dotarj** [linq2db/linq2db#4457]
### Describe your issue

We use Linq to DB (latest version, 5.4.0) from our ASP.NET (Core) application(s) to execute queries against MariaDB (10.4.* and 10.11.*) instances. We recently started to get exceptions related connection pool depletion. After some investigation it seems that the combination of using `new DataContext(...)`, together with `LoadWith` and `FirstOrDefault` (or `SingleOrDefault`) in same the query connections are not correctly closed/disposed, thus not returned to the connection pool. Connections will remain open in the Sleep state (see screenshot), even when the configured Connection Idle Timeout is expired.

My feeling is that this is related to Linq To DB executing a second query for the `LoadWith` on a second connection which is not correctly closed/disposed in this specific scenario. Could that be the case?

![image](https://github.com/linq2db/linq2db/assets/452825/c10e61a0-3495-48dd-aeef-b1669706b486)

```
Exception message: Connect Timeout expired. All pooled connections are in use.
Stack trace:
   at MySqlConnector.MySqlConnection.CreateSessionAsync(ConnectionPool pool, Int64 startingTimestamp, Activity activity, Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 946
   at MySqlConnector.MySqlConnection.OpenAsync(Nullable`1 ioBehavior, CancellationToken cancellationToken) in /_/src/MySqlConnector/MySqlConnection.cs:line 419
   at MySqlConnector.MySqlConnection.Open() in /_/src/MySqlConnector/MySqlConnection.cs:line 381
   at LinqToDB.Async.AsyncDbConnection.Open()
   at LinqToDB.Data.DataConnection.EnsureConnection(Boolean connect)
   at LinqToDB.Linq.ExpressionQuery`1.StartLoadTransaction(Query query)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Program.<Main>$(String[] args) in C:\git_repos\LinqToDbConnectionIssue\LinqToDbConnectionIssue\Program.cs:line 29
```

### Steps to reproduce

We have created a GitHub repository to easily reproduce this issue: https://github.com/eLabNext/LinqToDbConnectionIssue.

After cloning the GitHub repository run `docker compose up`, which will start a MariaDB (10.11) Docker image and create a database with the necessary tables and columns. Then the project can be started using a debug session in the IDE or started using `dotnet run --project LinqToDbConnectionIssue/LinqToDbConnectionIssue.csproj`.

I'll copy the code from the GitHub repository here for reference:

```c#
using LinqToDB;
using LinqToDB.DataProvider.MySql;
using LinqToDB.Mapping;

var connectionString = "Server=127.0.0.1; Port=13306; User ID=foobar; Password=foobar; Database=foobar; Pooling=true; Connection Idle Timeout=10";

// Set maxExecutionCount to 20 (a low number) and leave the application running to see that connections are not
// correctly returned to the connection pool. When using the command `SHOW PROCESSLIST;` MariaDB will show the open
// connections, which all will be in Sleep state and will not be terminated when the configured Connection Idle Timeout
// expires.
const int maxExecutionCount = int.MaxValue;
var currentExecutionCount = 0;

while (true)
{
    if (currentExecutionCount == maxExecutionCount)
    {
        break;
    }
    
    Console.WriteLine($"{DateTime.Now:O}: Executing query.");

    // For both MySqlConnector and MySql.Official the connection pool will be depleted. Due to differences in
    // connection pooling logic, MySql.Official will take longer to break compared to MySqlConnector.
    var dataContext = new DataContext(MySqlTools.GetDataProvider("MySqlConnector"), connectionString);
    // var dataContext = new DataContext(MySqlTools.GetDataProvider("MySql.Official"), connectionString);

    // The combination of using DataContext, LoadWith and FirstOrDefault (or SingleOrDefault) will quickly deplete the connection pool.
    var result = dataContext.GetTable<Foo>()
        .LoadWith(foo => foo.Bars)
        .FirstOrDefault();

    // By using FirstOrDefault without LoadWith the connection pool will not deplete.
    // var result = dataContext.GetTable<Foo>()
    //     .FirstOrDefault();

    // By using ToList with LoadWith the connection pool will not deplete.
    // var result = dataContext.GetTable<Foo>()
    //     .LoadWith(foo => foo.Bars)
    //     .Take(1)
    //     .ToList()[0];

    currentExecutionCount++;

    Thread.Sleep(10);
}

Console.WriteLine("Press any key to exit...");
Console.ReadKey();

[Table("Foo")]
public class Foo
{
    [Column]
    public string Id { get; set; }

    [Association(ThisKey = nameof(Id), OtherKey = nameof(Bar.FooId))]
    public List<Bar> Bars { get; set; }
}

[Table("Bar")]
public class Bar
{
    [Column]
    public string Id { get; set; }

    [Column]
    public string FooId { get; set; }
}
```

### Environment details

`Linq To DB` version: 5.4.0

Database (with version): MariaDB 10.4.* and MariaDB 10.11.*

ADO.NET Provider (with version): Both MySqlConnector 2.3.5 (latest) and MySql.Official 8.3.0 (MySql.Data, latest)

Operating system: Windows / Linux

.NET Version: .NET 4.6.2 / .NET 8.0

**Comment by MaceWindu** [comment]
Do you dispose your context? I don't see Dispose call for DataContext instance in your code.

**Comment by MaceWindu** [comment]
Also we don't use secondary connection for LoadWith queries anymore, only for client-side GroupBy queries (this will also gone in upcoming v6 release)

**Comment by dotarj** [comment]
Hi @MaceWindu, thanks for your quick response! We do not dispose the `DataContext`, which seems to be the right way to use `DataContext` as described in the documentation: "Using the DataContext class opens and closes an actual connection for each query!" https://linq2db.github.io/articles/general/Managing-data-connection.html#done-right.

`IDisposable.Dispose` is implemented explicitly on `DataContext`. Casting `dataContext` to `IDisposable` and calling `Dispose` does solve the problem (`((IDisposable)dataContext).Dispose();`), but that is not what the documentation states and also difficult to fix in our (big) code base.

**Comment by dotarj** [comment]
After debugging a little bit more, it looks like the method `DataContext.ReleaseQuery()` does not dispose the `_dataConnection` because the field `LockDbManagerCounter` is 1 and not 0. When not using the `LoadWith` in the example application the field `LockDbManagerCounter` is 0 and the connection will be disposed after the query is completed.

**Comment by dotarj** [comment]
`DataContext.ReleaseQuery()` is called once in this scenario and before `DataContextTransaction.Dispose()`. `DataContextTransaction.Dispose()` will `LockDbManagerCounter--` back to 0, but since `DataContext.ReleaseQuery()` is already called and will not be called again, the underlying connection will not get disposed (because `LockDbManagerCounter` was 1 when it was called).

When I replace `.FirstOrDefault()` with `.Take(1).ToList()[0]` in the example application, `DataContext.ReleaseQuery()` will get called a second time, the second time after `DataContextTransaction.Dispose()` is called and so `LockDbManagerCounter` will be 0 and the underlying connection will be closed.

**Comment by dotarj** [comment]
Oh, `DataContext.ReleaseQuery()` is also called twice (not once) in the `.FirstOrDefault()` scenario, but before `DataContextTransaction.Dispose()` so `LockDbManagerCounter` will be 1.
