### ISSUE TITLE
BulkCopy failure on CLOB

### ISSUE THREAD

**Issue by panthernet** [linq2db/linq2db#4461]
### Describe your issue
DB: Oracle12.1c
LINQ2DB: 3.4.3

When trying to copy a lot of entries using the `db.BulkCopy` it fails with an exception.
Column is defined like this
`[Column("PROJECT_IDS", DbType = "CLOB", Length = 40000)] public string ProjectIdsString { get; set; }`
I've tried to play with Length = 0-4000 but it fails anyway.

Need help figuring out on how I can bypass it.

```
ORA-01704: string literal too long

   at OracleInternal.ServiceObjects.OracleConnectionImpl.VerifyExecution(Int32& cursorId, Boolean bThrowArrayBindRelatedErrors, SqlStatementType sqlStatementType, Int32 arrayBindCount, OracleException& exceptionForArrayBindDML, Boolean& hasMoreRowsInDB, Boolean bFirstIterationDone)
   at OracleInternal.ServiceObjects.OracleCommandImpl.ExecuteNonQuery(String commandText, OracleParameterCollection paramColl, CommandType commandType, OracleConnectionImpl connectionImpl, Int32 longFetchSize, Int64 clientInitialLOBFS, OracleDependencyImpl orclDependencyImpl, Int64[]& scnFromExecution, OracleParameterCollection& bindByPositionParamColl, Boolean& bBindParamPresent, OracleException& exceptionForArrayBindDML, OracleConnection connection, Boolean isFromEF)
   at Oracle.ManagedDataAccess.Client.OracleCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery(IDbCommand command)
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Data.CommandInfo.Execute()
   at LinqToDB.DataProvider.MultipleRowsHelper.Execute()
   at LinqToDB.DataProvider.BasicBulkCopy.MultipleRowsCopyHelper(MultipleRowsHelper helper, IEnumerable source, String from, Action`1 prepFunction, Action`3 addFunction, Action`1 finishFunction, Int32 maxParameters, Int32 maxSqlLength)
   at LinqToDB.DataProvider.Oracle.OracleBulkCopy.OracleMultipleRowsCopy1(MultipleRowsHelper helper, IEnumerable source)
   at LinqToDB.DataProvider.Oracle.OracleBulkCopy.MultipleRowsCopy[T](ITable`1 table, BulkCopyOptions options, IEnumerable`1 source)
   at LinqToDB.DataProvider.BasicBulkCopy.BulkCopy[T](BulkCopyType bulkCopyType, ITable`1 table, BulkCopyOptions options, IEnumerable`1 source)
```

**Comment by panthernet** [comment]
Got it working right away :)
You have to set correct column attributes:
```
[Column("PROJECT_IDS", DbType = "CLOB", DataType = DataType.Text)] public string ProjectIdsString { get; set; }
```
