### ISSUE TITLE
Task-spawning code refactoring

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#4475]
We should review/fix/simplify places where we create and run Tasks, e.g. 

https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/AsyncExtensions.cs#L30-L68

this leads to exceptions like:
```
Message: 'Start may not be called on a task that has completed.',
    Stack: '   at System.Threading.Tasks.Task.Start(TaskScheduler scheduler)
   at LinqToDB.AsyncExtensions.GetTask[T](Func`1 func, CancellationToken token)
   at LinqToDB.AsyncExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken token)
```

https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/LinqExtensions.cs#L732-L735

this is not necessary, as we should always work with `IQueryProviderAsync`

**Comment by MaceWindu** [comment]
> I believe your exception arises when calling Start() on a task that was created with a cancellation token that is already cancelled when you call Start().

yes, and while it is completely valid scenario, it adds one to much useless exception to ignore when we already have Task/Operation cancelled duo...

> ... ContinueOnCapturedContext ...

it was added in times when we had little idea about this stuff to just please everyone :). Probably it's a good idea to get rid of it in v6 finally

**Comment by MaceWindu** [comment]
All sub-tasks are done
