### ISSUE TITLE
SQL-Server GroupBy-Query with nullable String-Key fails to create working SQL when used in an IN-Query instead of old EXISTS-Behaviour

### ISSUE THREAD

**Issue by BenKmann** [linq2db/linq2db#4513]
### Describe your issue

My GroupBy Clause worked in Version 5.3.2 of linq2db but stopped working after i updated to 5.4.1. So it is a recent change in Linq2db afaik.

So SQL-Server throws the following Exception:
```
Exception message:
Stack trace:
System.Data.SqlClient.SqlException
Each GROUP BY expression must contain at least one column that is not an outer reference.
StackTrace:
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteDataReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__12`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at MyCode.FilterAdressenDefinitelyChangedNavKontakte()
```

### Steps to reproduce
My Code:
```c#
using var db = _addInContext.GetCobraDbContext();
var innerGroupByQuery= from adr in db.Adressen
							   join navKontakt in db.NAVKontakte on adr.NAVKontaktnummer equals navKontakt.NAVKontaktnummer --both are nullable string.
							   where adr.NAVKontaktnummer != null
							   group adr by adr.NAVKontaktnummer
							   into grp
							   where grp.Count() == 1
							   select grp.Key;

return (from adr in db.Adressen
		join navKontakt in db.NAVKontakte on adr.NAVKontaktnummer equals navKontakt.NAVKontaktnummer
		where adr.NAVKontaktnummer.In(innerGroupByQuery)
		select adr).ToList();
```

The first innerGroupByQuery alone works, but not in the Big Query.

The SQL Generated is:
```sql
SELECT
	[adr].*
FROM
	[ADDRESSES] [adr]
		INNER JOIN [FREE08] [navKontakt] ON ([adr].[CUSTOMERNUMBER6] = [navKontakt].[TEXT1] OR [adr].[CUSTOMERNUMBER6] IS NULL AND [navKontakt].[TEXT1] IS NULL)
WHERE
	([adr].[CUSTOMERNUMBER6] IS NULL AND 1 IN ( -- <-- this whole in is not neccessary or broken
		SELECT
			1
		FROM
			[ADDRESSES] [adr_1]
				INNER JOIN [FREE08] [navKontakt_1] ON 1 = [navKontakt_1].[TEXT1]
		GROUP BY
			1 -- <-- this will not work
		HAVING
			Count(*) = 1
	) OR [adr].[CUSTOMERNUMBER6] IS NOT NULL AND [adr].[CUSTOMERNUMBER6] IN (
		SELECT
			[adr_1].[CUSTOMERNUMBER6]
		FROM
			[ADDRESSES] [adr_1]
				INNER JOIN [FREE08] [navKontakt_1] ON ([adr_1].[CUSTOMERNUMBER6] = [navKontakt_1].[TEXT1] OR [adr_1].[CUSTOMERNUMBER6] IS NULL AND [navKontakt_1].[TEXT1] IS NULL)
		WHERE
			[adr_1].[CUSTOMERNUMBER6] IS NOT NULL
		GROUP BY
			[adr_1].[CUSTOMERNUMBER6]
		HAVING
			Count(*) = 1
	))
```

The GroupBy 1 is Failing with the Exception provided above.

When i change only my groupby Line in my Query and write 
```c#
group adr by adr.NAVKontaktnummer ?? string.Empty
```
then the Query is working and the following SQL is generated:

```sql
DataConnection: BeforeExecute
--  SqlServer.2014
-- Works with String.Empty
SELECT
	[adr].* -- shortened Select.
FROM
	[ADDRESSES] [adr]
		INNER JOIN [FREE08] [navKontakt] ON ([adr].[CUSTOMERNUMBER6] = [navKontakt].[TEXT1] OR [adr].[CUSTOMERNUMBER6] IS NULL AND [navKontakt].[TEXT1] IS NULL)
WHERE
	[adr].[CUSTOMERNUMBER6] IN (
		SELECT
			[t1].[Key_1]
		FROM
			(
				SELECT
					Coalesce([selectParam].[CUSTOMERNUMBER6], N'') as [Key_1]
				FROM
					[ADDRESSES] [selectParam]
						INNER JOIN [FREE08] [navKontakt_1] ON ([selectParam].[CUSTOMERNUMBER6] = [navKontakt_1].[TEXT1] OR [selectParam].[CUSTOMERNUMBER6] IS NULL AND [navKontakt_1].[TEXT1] IS NULL)
				WHERE
					[selectParam].[CUSTOMERNUMBER6] IS NOT NULL
			) [t1]
		GROUP BY
			[t1].[Key_1]
		HAVING
			Count(*) = 1
	)
```

With linq2db 5.3.2 and the old Query without the == string.Empty it produced the following Query:
This Query uses Exists instead of In.
```sql
FROM
	[ADDRESSES] [adr]
		INNER JOIN [FREE08] [navKontakt] ON ([adr].[CUSTOMERNUMBER6] = [navKontakt].[TEXT1] OR [adr].[CUSTOMERNUMBER6] IS NULL AND [navKontakt].[TEXT1] IS NULL)
WHERE
	EXISTS( -- <-- the old behaviour
		SELECT
			[adr_1].[CUSTOMERNUMBER6]
		FROM
			[ADDRESSES] [adr_1]
				INNER JOIN [FREE08] [navKontakt_1] ON ([adr_1].[CUSTOMERNUMBER6] = [navKontakt_1].[TEXT1] OR [adr_1].[CUSTOMERNUMBER6] IS NULL AND [navKontakt_1].[TEXT1] IS NULL)
		WHERE
			[adr_1].[CUSTOMERNUMBER6] IS NOT NULL AND ([adr_1].[CUSTOMERNUMBER6] = [adr].[CUSTOMERNUMBER6] OR [adr_1].[CUSTOMERNUMBER6] IS NULL AND [adr].[CUSTOMERNUMBER6] IS NULL)
		GROUP BY
			[adr_1].[CUSTOMERNUMBER6]
		HAVING
			Count(*) = 1
	)
```

Do you need further information, or is this enough for you to fix the problem?
If you need ExpressionTest-Files or something, just say it :)

### Environment details

Database (with version): SQL Server 2019

ADO.NET Provider (with version): System.Data.SqlClient (default for .net Framework 4.7.2)

Operating system: Win11

.NET Version: Framework 4.7.2

**Comment by sdanyliv** [comment]
It is know regression, fixed in upcoming version 6. Use `PreferExistsForScalar` while configring `DataOptions`.
```cs
var options = new DataOptions()
    .UseSqlServer(...)
    .WithOptions<LinqOptions>(lo => lo.WithPreferExistsForScalar(true));

using var dc = new DataConnection(options);
```

**Comment by BenKmann** [comment]
Thanks a lot! Love Linq2DB 👍 . Keep up the great work!!
