### ISSUE TITLE
Cannot scaffold Microsoft Fabric Datawarehouse database

### ISSUE THREAD

**Issue by Hoodah** [linq2db/linq2db#4536]
I am trying to use the cli tool to generate a database model for a database in Microsoft's Fabric ecosystem. I assume this is some derivative of an Azure SQL database. However it seems to have some limited functionality which is stopping linq2db in its tracks. Specifically the FUNCTION 'ASSEMBLYPROPERTY' is not supported.

```
Exception message: dotnet : Unhandled exception: FUNCTION 'ASSEMBLYPROPERTY' is not supported.
Stack trace: 

```
dotnet : Unhandled exception: FUNCTION 'ASSEMBLYPROPERTY' is not supported.
At line:1 char:1
+ dotnet linq2db scaffold -p SqlServer -c "Data Source=lpo3n5rp6anejgna ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (Unhandled excep... not supported.:String) [], RemoteException
    + FullyQualifiedErrorId : NativeCommandError
 
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, 
TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean 
forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& 
task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 
timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader()
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.addUDTsToDataTypesTable(DataTable dataTypesTable, SqlConnection connection, String ServerVersion)
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.GetDataTypesTable(SqlConnection connection)
   at Microsoft.Data.SqlClient.SqlMetaDataFactory.PrepareCollection(String collectionName, String[] restrictions, DbConnection connection)
   at Microsoft.Data.ProviderBase.DbMetaDataFactory.GetSchema(DbConnection connection, String collectionName, String[] restrictions)
   at Microsoft.Data.ProviderBase.DbConnectionInternal.GetSchema(DbConnectionFactory factory, DbConnectionPoolGroup poolGroup, DbConnection outerConnection, String 
collectionName, String[] restrictions)
   at Microsoft.Data.SqlClient.SqlConnection.GetSchema(String collectionName, String[] restrictionValues)
   at Microsoft.Data.SqlClient.SqlConnection.GetSchema(String collectionName)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetDataTypes(DataConnection dataConnection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at LinqToDB.Schema.LegacySchemaProvider..ctor(DataConnection connection, SchemaOptions options, ILanguageProvider languageProvider)
   at LinqToDB.CommandLine.ScaffoldCommand.Scaffold(ScaffoldOptions settings, ScaffoldInterceptors interceptors, String provider, String providerLocation, String 
connectionString, String additionalConnectionString, String output, Boolean overwrite)
   at LinqToDB.CommandLine.ScaffoldCommand.Execute(CliController controller, String[] rawArgs, Dictionary`2 options, IReadOnlyCollection`1 unknownArgs)
   at LinqToDB.CommandLine.CliController.Execute(String[] args)
   at LinqToDB.Tools.Program.Main(String[] args)
```

```

### Steps to reproduce
from the package manager console in Visual Studio run the following command against a fabric connectionstring
dotnet linq2db scaffold -p SqlServer -c "Data Source=yourfabricserverhere.datawarehouse.fabric.microsoft.com;Initial Catalog=yourdatabasehere;Authentication=Active Directory Interactive;"

### Environment details

`Linq To DB` version: 5.4.1

Database (with version): Microsoft fabric data warehouse

ADO.NET Provider (with version):  Microsoft.Data.SqlClient 5.2.1

Operating system: windows

.NET Version: 8.0

**Comment by MaceWindu** [comment]
Looks similar to https://github.com/linq2db/linq2db/issues/4195

Microsoft fixed it for Edge db here https://github.com/dotnet/SqlClient/issues/2086, but it looks like they need to do the same for Fabric DB. Could you please report another issue to SqlClient repo?

**Comment by MaceWindu** [comment]
I've created issue in SqlClient repo. Looks like we really need to get rid of GetSchema calls on our side. Microsoft spawns new DBs too fast 😄

**Comment by MaceWindu** [comment]
Closing as duplicate of #4195, which tracks the underlying task — removing the SqlClient `GetSchema` dependency in the schema provider so scaffolding works on trimmed MSSQL cloud DBs (Azure SQL Edge, Fabric DW). Details consolidated there. Any further info, please add to #4195.
