### ISSUE TITLE
PostgreSQL Json/JsonB columns are not mapped during merge operation

### ISSUE THREAD

**Issue by GlebGQ** [linq2db/linq2db#4556]
### Describe your issue

Executing merge with json or jsonb columns in postgresql is not possible

```
Unhandled exception. Npgsql.PostgresException (0x80004005): 42804: column "Payload" is of type jsonb but expression is of type text

POSITION: 226
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|234_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior, Boolean async, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteNonQuery(Boolean async, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryDataAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryDataAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.NonQueryQueryAsync(Query query, IDataContext dataContext, Expression expression, Object[] ps, Object[] preambles, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) 
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsync[TResult](Expression expression, CancellationToken cancellationToken) 
   at Program.<Main>$(String[] args) in C:\work\repos\ConsoleApp2\Program.cs:line 21
   at Program.<Main>(String[] args)
  Exception data:
    Severity: ERROR
    SqlState: 42804
    MessageText: column "Payload" is of type jsonb but expression is of type text
    Hint: You will need to rewrite or cast the expression.
    Position: 226
    File: parse_target.c
    Line: 587
    Routine: transformAssignedExpr


```

### Steps to reproduce

```c#
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.Mapping;
using System;
using LinqToDB.DataProvider.PostgreSQL;

var myObject = new MyClass
{
    Payload = "John",
    Headers = new Dictionary<string, string>
    {
        { "key1", "value1" },
    }
};

using (var db = new DataConnection(new DataOptions().UsePostgreSQL("connectionString")))
{
    await db.GetTable<MyClass>().Merge()
        .Using(new MyClass[] { myObject })
        .OnTargetKey()
        .InsertWhenNotMatched()
        .MergeAsync();
}
public class MyClass
{
    [PrimaryKey, Identity]
    public int Id { get; set; }

    [Column(DataType = DataType.BinaryJson, DbType = "jsonb", Name = "Payload")]
    public string Payload { get; set; }
    
    [Column(DataType = DataType.Json, DbType = "json", Name = "Headers")]
    public Dictionary<string, string> Headers { get; set; }
}
```

**Generated SQL**

``` sql
--  PostgreSQL.15 PostgreSQL (asynchronously)
DECLARE @value Json -- Object
SET     @value = System.Collections.Generic.Dictionary`2[System.String,System.String]

MERGE INTO "MyClass" "Target"
USING (VALUES
        (0,'John',:value)
) "Source"
(
        "Id",
        "Payload",
        "Headers"
)
ON ("Target"."Id" = "Source"."Id")

WHEN NOT MATCHED THEN
INSERT
(
        "Payload",
        "Headers"
)
VALUES
(
        "Source"."Payload",
        "Source"."Headers"
)

```

### Environment details

linq2db - 5.2.1

PostgreSQL - 15

Npgsql - 7.0.7

Operating system: windows 10 pro

.net 7.0

**Comment by lhotamir** [comment]
@MaceWindu  I have tried the 6.0.0-preview4 release in my project and I still experience the issue

**Comment by MaceWindu** [comment]
Create new issue with additional details

**Comment by picolino** [comment]
You can use temp table as a workaround on previous versions of linq2db. Temp table creation translates jsonb fields correctly:

```
await using var temp = await dataConnection.CreateTempTableAsync(
    source,
    BulkCopyOptions.Empty,
    Guid.NewGuid().ToString(),
    cancellationToken: ct
);

var q = table.Merge()
  .Using(temp)
  .OnTargetKey()
  .InsertWhenNotMatched();

await query.MergeAsync(token: ct);
```
