### ISSUE TITLE
Sequence cannot be converted to SQL

### ISSUE THREAD

**Issue by torgashov** [linq2db/linq2db#4570]
Hello!
Whe got exception in complex query.
To reproduce I shortened the request.

This example complete success:

```cs
var result = (from ua in ctx.UserInApps
              where ua.UserId == 55377
              && (true && true || true && false)
              && ctx.UserInApps.Any()
              select 1).AsSqlCe();
result.ToArray();
```

This example complete with exception:

```cs
var result = (from ua in ctx.UserInApps
                          where ua.UserId == 55377
                          && true && ( true || false)
                          && ctx.UserInApps.Any()
                          select 1).AsSqlCe();
result.ToArray();
```

```
LinqToDB.Linq.LinqException
  HResult=0x80131500
  Message=Sequence '[Microsoft.EntityFrameworkCore.Query.EntityQueryRootExpression]' cannot be converted to SQL.
  Source=linq2db
  StackTrace:
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.AllAnyBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryContext(IBuildContext context, MethodCallExpression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.SubQueryToSql(IBuildContext context, MethodCallExpression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertPredicate(IBuildContext context, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSearchCondition(IBuildContext context, Expression expression, List`1 conditions)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.SelectBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.QueryExtensionBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at LinqToDB.DataProvider.DatabaseSpecificQueryable`1.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Catalog.ProofOfConcept.Console.TestClass.Test(ICatalogUnitOfWorkFactory uowFactory) in D:\Dev\Catalog.ProofOfConcept.Console\TestClass.cs:line 115
   at Catalog.ProofOfConcept.Console.App.StartAsync(CancellationToken cancellationToken) in D:\Dev\Catalog.ProofOfConcept.Console\App.cs:line 24
   at Microsoft.Extensions.Hosting.Internal.Host.<<StartAsync>b__15_1>d.MoveNext()
```

**Comment by torgashov** [comment]
> Does it work with `.Any()` replaced with `.Count() > 0` ?

No it does not work. I have got same exception.

**Comment by torgashov** [comment]
First and second examples are equal. 
The first example is an expansion of the parentheses of the second example.

**Comment by sdanyliv** [comment]
Shortening may not help. It is some composition of many queries?

**Comment by torgashov** [comment]
For reproduce problem you can create any query for any model.
For example, you have model Users.
This query will throw exception:

var result = (from ua in ctx.Users
                          where ua.UserId == 55377
                          && true && ( true || false)
                          && ctx.User.Any()
                          select 1).AsSqlCe();
result.ToArray();

But this example will work fine:
var result = (from ua in ctx.Users
              where ua.UserId == 55377
              && (true && true || true && false)
              && ctx.Users.Any()
              select 1).AsSqlCe();
result.ToArray();

Bouth examples are equal.
This seems to be a visitor problem.

**Comment by sdanyliv** [comment]
Can you replace `AsSqlCe()` with `ToLinqToDB()`

**Comment by torgashov** [comment]
> No it does not work. I have got same exception.

No it does not work. I have got same exception.

**Comment by torgashov** [comment]
This example complete with exception too:

var result = (from ua in ctx.UserInApps.AsCte("UserInApps")
              where ua.UserId == userId 
              && ctx.RoleInRoles.Any()
              && ctx.RoleInRoles.Any()
              && ctx.RoleInRoles.Any()
              select 1).ToLinqToDB(); 
result.ToArray();

**Comment by sdanyliv** [comment]
> Have linqtodb some stricts or limits in conditions?

No, for some unknown reason library not transformed EF Core's Exprersssion to our representation.

As a workaround i can propose the following
```cs
using var db = ctx.CreateLinqToDBConnection();

var query = 
    from ua in ctx.UserInApps
    where ua.UserId == userId && db.GetTable<RoleInRole>().Any() && true && true
    select 1;

var result = query.ToLinqToDB().ToArray();
```

**Comment by torgashov** [comment]
> > Have linqtodb some stricts or limits in conditions?
> 
> No, for some unknown reason library not transformed EF Core's Exprersssion to our representation.
> 
> As a workaround i can propose the following
> 
> ```cs
> using var db = ctx.CreateLinqToDBConnection();
> 
> var query = 
>     from ua in ctx.UserInApps
>     where ua.UserId == userId && db.GetTable<RoleInRole>().Any() && true && true
>     select 1;
> 
> var result = query.ToLinqToDB().ToArray();
> ```

Thank you!
Is it possible fix problem in feature?

**Comment by torgashov** [comment]
> > Have linqtodb some stricts or limits in conditions?
> 
> No, for some unknown reason library not transformed EF Core's Exprersssion to our representation.
> 
> As a workaround i can propose the following
> 
> ```cs
> using var db = ctx.CreateLinqToDBConnection();
> 
> var query = 
>     from ua in ctx.UserInApps
>     where ua.UserId == userId && db.GetTable<RoleInRole>().Any() && true && true
>     select 1;
> 
> var result = query.ToLinqToDB().ToArray();
> ```

I checked complex query with multiple expressions (as functions) and it works fine if i change all model entities to GetTable construction.

Is this temprory problem? 
Can we use library with home to change constructions GetTable<> to models using?

**Comment by sdanyliv** [comment]
Yes, it is temporary problem.
