### ISSUE TITLE
Exception on loading child type association

### ISSUE THREAD

**Issue by dev-anton-ko** [linq2db/linq2db#4585]
Simple hierarchy with base class and one child with nested property.
Exception occurred:

```
LinqToDB.LinqToDBException : Member 'Ref(TableContext[ID:1](14)(T: 15)::SomeDerivedClass).Nested' is not an association.:
```

If `Nested` property moved to the base class - works as expected

### Steps to reproduce

Include a complete code listing (or project/solution) that we can run to reproduce the issue.

Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.

```c#
public class SomeBaseClass
{
	public int Id { get; set; }

	public string Data { get; set; } = null!;
	
	public HierachyType TypeId { get; set; }
}

public enum HierachyType
{
	Type1 = 0,
	Type2 = 1
}

public class SomeDerivedClass : SomeBaseClass
{
	public string? SomeField { get; set; }
	
	public int? NestedTypeId { get; set; }
	
	public NestedType? Nested { get; set; }
}

public class NestedType
{
	public int Id { get; set; }

	public string Code { get; set; } = null!;
}

[Test]
public void Test([DataSources] string context)
{
	using var db                   = GetDataContext(context, new MappingSchema());
	var       fluentMappingBuilder = new FluentMappingBuilder(db.MappingSchema);

	fluentMappingBuilder
		.Entity<NestedType>()
		.HasTableName(nameof(NestedType))
		.Property(x => x.Id)
		.Property(x => x.Code);
	
	fluentMappingBuilder
		.Entity<SomeBaseClass>()
		.HasTableName("SomeBaseClass")
		.Inheritance(x => x.TypeId, HierachyType.Type1, typeof(SomeDerivedClass))
		.Property(t => t.Data).HasColumnName("data")
		.Property(t => t.Id).IsPrimaryKey()
		.Property(t => t.TypeId).IsDiscriminator()
		.Build();
	
	fluentMappingBuilder.Entity<SomeDerivedClass>()
		.Property(x => x.SomeField)
		.Property(x => x.NestedTypeId)
		.Association(x => x.Nested, x => x.NestedTypeId, x => x!.Id);

	using var table = db.CreateLocalTable<SomeBaseClass>();
	using var table1 = db.CreateLocalTable<NestedType>();
	
	var list      = db.GetTable<SomeDerivedClass>()
		.LoadWith(x => x.Nested)
		.ToList();
}
```

### Environment details

`Linq To DB` version: *6.0.0 Preview 1*

Database (with version): *Reproduced on Tests*

Operating system: *Windows 11*

.NET Version: *.Net 8*

**Comment by aushev-vadim** [comment]
Hi! I guess I have a similar problem. 😢

I have following classes:
```csharp
public abstract class BaseEntity
{
    public Guid Id { get; set; }
    public DateTimeOffset CreatedDate { get; set; }
    public Guid CreatedBy { get; set; }
    public DateTimeOffset? UpdatedDate { get; set; }
    public Guid? UpdatedBy { get; set; }
    public virtual User? CreatedByUser { get; set; }
    public virtual User? UpdatedByUser { get; set; }
}

public class Address : BaseEntity
{
    public required string Settlement { get; set; }
    public required string Street { get; set; }
    public required string House { get; set; }
    public string? Flat { get; set; }
}

public class User
{
    public Guid Id { get; set; }
    public required string Name { get; set; }
    // Other properties have been removed for clarity.
}
```

Mapping builders:
```csharp
internal abstract class BaseEntityMappingBuilder<TEntity> : EntityMappingBuilder<TEntity>
    where TEntity : BaseEntity
{
    protected BaseEntityMappingBuilder(FluentMappingBuilder builder, string configuration, string schemaName)
        : base(builder, configuration)
    {
        this.GenerateTableName(schemaName); // Extension method for table name generation (snake case, pluralized)
        this.GenerateColumnNames(); // Extension method for column names generation (snake case)

        this.Property(entity => entity.Id).IsPrimaryKey();
        this.Association(entity => entity.CreatedByUser, entity => entity.CreatedBy, user => user!.Id);
        this.Association(entity => entity.UpdatedByUser, entity => entity.UpdatedBy, user => user!.Id, true);
    }
}

internal sealed class AddressMappingBuilder : BaseEntityMappingBuilder<Address>
{
   public AddressMappingBuilder(FluentMappingBuilder builder, string configuration)
        : base(builder, configuration, SchemaNames.Application)
    {
        this.Property(address => address.Settlement).IsNotNull().HasLength(128);
        this.Property(address => address.Street).IsNotNull().HasLength(256);
        this.Property(address => address.House).IsNotNull().HasLength(64);
        this.Property(address => address.Flat).HasLength(64);
    }
}

internal sealed class UserEntityMappingBuilder : EntityMappingBuilder<User>
{
    public UserEntityMappingBuilder(FluentMappingBuilder builder, string configuration)
        : base(builder, configuration)
    {
        this.GenerateTableName(SchemaNames.Security);
        this.GenerateColumnNames();

        this.Property(user => user.Id).IsPrimaryKey();
        this.Property(user => user.Name).IsNotNull().HasLength(256);
        // Other properties have been removed for clarity.
    }
}
```

Inheritance is only in C# code to reduce code duplication.

In database tables look like this:
```sql
CREATE TABLE application.addresses (
    id uuid NOT NULL,
    created_date timestamp NOT NULL,
    created_by uuid NOT NULL,
    updated_date timestamp NULL,
    updated_by uuid NULL,
    settlement varchar(128) NOT NULL,
    street varchar(256) NOT NULL,
    house varchar(64) NOT NULL,
    flat varchar(64) NULL,
    CONSTRAINT addresses_pk PRIMARY KEY (id)
);

CREATE TABLE "security".users (
    id uuid NOT NULL,
    "name" varchar(256) NOT NULL,
    -- Other columns have been removed for clarity.
    CONSTRAINT users_pk PRIMARY KEY (id)
);
```

### Reproduction Steps
```csharp
var addresses = db.GetTable<Address>()
    .LoadWith(a => a.CreatedByUser)
    .LoadWith(a => a.UpdatedByUser)
    .ToArray();
```

### Exception details
```
LinqToDB.LinqToDBException: Member 'Ref(TableContext(1)(T: 2)::Address).CreatedByUser' is not an association.
   at LinqToDB.Internal.Linq.Builder.LoadWithBuilder.GetAssociations(ExpressionBuilder builder, ILoadWithContext parentContext, Expression expression, Expression stopExpression) in /_/Source/LinqToDB/Internal/Linq/Builder/LoadWithBuilder.cs:line 258
   at LinqToDB.Internal.Linq.Builder.LoadWithBuilder.ExtractAssociations(ExpressionBuilder builder, ILoadWithContext parentContext, Expression expression, Expression stopExpression) in /_/Source/LinqToDB/Internal/Linq/Builder/LoadWithBuilder.cs:line 167
   at LinqToDB.Internal.Linq.Builder.LoadWithBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in /_/Source/LinqToDB/Internal/Linq/Builder/LoadWithBuilder.cs:line 79
   at LinqToDB.Internal.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in /_/Source/LinqToDB/Internal/Linq/Builder/MethodCallBuilder.cs:line 10
   at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.TryBuildSequence(BuildInfo buildInfo) in /_/Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.cs:line 358
   at LinqToDB.Internal.Linq.Builder.LoadWithBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in /_/Source/LinqToDB/Internal/Linq/Builder/LoadWithBuilder.cs:line 35
   at LinqToDB.Internal.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in /_/Source/LinqToDB/Internal/Linq/Builder/MethodCallBuilder.cs:line 10
   at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.TryBuildSequence(BuildInfo buildInfo) in /_/Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.cs:line 358
   at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in /_/Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.cs:line 373
   at LinqToDB.Internal.Linq.Builder.ExpressionBuilder.Build[T](IQueryExpressions& expressions) in /_/Source/LinqToDB/Internal/Linq/Builder/ExpressionBuilder.cs:line 128
   at LinqToDB.Internal.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, IQueryExpressions& expressions) in /_/Source/LinqToDB/Internal/Linq/Query{T}.cs:line 403
   at LinqToDB.Internal.Linq.Query`1.GetQuery(IDataContext dataContext, IQueryExpressions& expressions, Boolean& dependsOnParameters) in /_/Source/LinqToDB/Internal/Linq/Query{T}.cs:line 380
   at LinqToDB.Internal.Linq.ExpressionQuery`1.GetQuery(IQueryExpressions& expression, Boolean cache, Boolean& dependsOnParameters) in /_/Source/LinqToDB/Internal/Linq/ExpressionQuery.cs:line 91
   at LinqToDB.Internal.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in /_/Source/LinqToDB/Internal/Linq/ExpressionQuery.cs:line 357
   at LinqToDB.LinqExtensions.LoadWithQueryable`2.System.Collections.Generic.IEnumerable<TEntity>.GetEnumerator() in /_/Source/LinqToDB/LinqExtensions/LinqExtensions.LoadWith.cs:line 81
   at System.Linq.Enumerable.<ToArray>g__EnumerableToArray|314_0[TSource](IEnumerable`1 source)
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
```

### Regression?

In version 5.4.1.9 same code works as expected.

### Linq To DB version

6.0.0, 6.1.0

### .NET version

9.0.311

### Database

PostgreSQL 17.7

### Database provider

Npgsql 10.0.1

### Operating system

Windows 11

### Configuration

_No response_
