### ISSUE TITLE
StringAggregate on SelectMany throw exception cannot be convert to SQL

### ISSUE THREAD

**Issue by gatsuga** [linq2db/linq2db#4597]
Hello,

I'm trying to make stringJoin with StringAggregate function
It works fine with one table, but I can't get values in the linked table. It throws an exception.

```
ctx.GetTable<Source>()
             .Where(s => s.DeletedAt == null)                          
             .Where(s => s.Id == id)             
             .OrderBy(s => s.Level)
             .TakeLast(1)             
             .SelectMany(s => s.Linked
                .Where(l => l.DeletedAt == null))             
                .StringAggregate(", ", l => l.Code)
                .ToValue();
```

But for example this part of code works fine:

```
ctx.GetTable<Source>()
            .Where(s => s.DeletedAt == null) 
            .Where(r => r.Id > id)
            .StringAggregate(", ", r => r.Name)
            .ToValue();
```

How I can use string aggregation for more complicated queries?
```
Exception message: 'null.GetTable().Where(x => (Convert(x, ISoftDeletableEntity).DeletedAt == null)).Where(l => (l.Id == id)).OrderBy(l => l.Level).TakeLast(1).SelectMany(cp => cp.Linked.Where(ta => (ta.DeletedAt == null)), (s, c) => c).StringAggregate(", ", l => l.Code).ToValue()' cannot be converted to SQL.

Stack trace:

at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSqlExpression(IBuildContext context, Expression expression, ColumnDescriptor columnDescriptor, Boolean isPureExpression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSql(IBuildContext context, Expression expression, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__93_0(ValueTuple`4 context, Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.ExpressionExtensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CorrectConditional(IBuildContext context, Expression expr, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertAssignmentArgument(IBuildContext context, Expression expr, MemberInfo memberInfo, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<BuildExpression>b__93_0(ValueTuple`4 context, Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.ExpressionExtensions.Transform[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide, String alias)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide)
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.<GetForEachAsync>d__19.MoveNext()
   at LinqToDB.AsyncExtensions.<ToArrayAsync>d__9`1.MoveNext()

### Environment details

`Linq To DB` version: 5.4.0.0

Database (with version): PostgreSQL 16

Operating system: Windows 11

.NET Version: 8

**Comment by MaceWindu** [comment]
You should replace `SelectMany` with `Select`. `StringAggregate` converts list to string and then using `SelectMany` you convert it to `IEnumerable<char>`
