### ISSUE TITLE
Association key not found when using custom IMetadataReader

### ISSUE THREAD

**Issue by boginw** [linq2db/linq2db#4602]
### Describe your issue

I'm using a custom `IMetadataReader` and `DynamicColumnsStore` to add associations without the `Column`- and `Association`-attributes. Inserting, updating, deleting, and querying a single entity works fine, but if I involve the association, I the exception listed below. Is there something I'm missing?

Exception

```
/home/bogi/projects/linq2db-metadata-bug/bin/Debug/net8.0/linq2db-metadata-bug
Unhandled exception. LinqToDB.Linq.LinqException: Association key 'ParentId' not found for type 'ChildClass.
   at LinqToDB.Linq.Builder.AssociationHelper.CreateAssociationQueryLambda(ExpressionBuilder builder, AccessorMember onMember, AssociationDescriptor association, Type parentOriginalType, Type parentType, Type objectType, Boolean inline, Boolean enforceDefault, List`1 loadWith, Boolean& isLeft)
   at LinqToDB.Linq.Builder.AssociationHelper.BuildAssociationInline(ExpressionBuilder builder, BuildInfo buildInfo, TableContext tableContext, AccessorMember onMember, AssociationDescriptor descriptor, Boolean inline, Boolean& isOuter)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.FindContextExpression(Expression expression, Int32 level, Boolean forceInner, Boolean throwExceptionForNull)
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
   at LinqToDB.Linq.Builder.ExpressionContext.IsExpression(Expression expression, Int32 level, RequestFor requestFlag)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c.<CheckSubQueryForWhere>b__126_0(CheckSubQueryForWhereContext context, Expression expr)
   at LinqToDB.Expressions.VisitFuncVisitor`1.Visit(Expression expr)
   at LinqToDB.Expressions.VisitFuncVisitor`1.Visit(Expression expr)
   at LinqToDB.Expressions.ExpressionExtensions.Visit[TContext](Expression expr, TContext context, Func`3 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.CheckSubQueryForWhere(IBuildContext context, Expression expression, Boolean& makeHaving)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildWhere(IBuildContext parent, IBuildContext sequence, LambdaExpression condition, Boolean checkForSubQuery, Boolean enforceHaving)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToArrayAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Program.Main() in /home/bogi/projects/linq2db-metadata-bug/Program.cs:line 36
   at Program.Main() in /home/bogi/projects/linq2db-metadata-bug/Program.cs:line 36
   at Program.Main() in /home/bogi/projects/linq2db-metadata-bug/Program.cs:line 36
   at Program.<Main>()
```

### Steps to reproduce

 I've tried to create a minimal reproducible example where I use a `CustomMetadataReader` to add a new dynamic column to `ChildClass` along with an association attribute to that column.

<details>
  <summary>Example Code</summary>
  
  ```csharp
using System.Diagnostics;
using System.Reflection;
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.DataProvider.SQLite;
using LinqToDB.Mapping;
using LinqToDB.Metadata;
using Microsoft.Data.Sqlite;

public class Program
{
    public static async Task Main()
    {
        await using var connection = new SqliteConnection("Data Source=db;Mode=Memory");

        await connection.OpenAsync();

        var mappingSchema = new MappingSchema();
        mappingSchema.AddMetadataReader(new CustomMetadataReader());

        var options = new DataOptions()
            .UseMappingSchema(mappingSchema)
            .UseConnection(SQLiteTools.GetDataProvider(), connection);

        await using var db = new DataConnection(options);

        await db.CreateTableAsync<ChildClass>();
        await db.CreateTableAsync<ParentClass>();

        await CanInsertAndReadDynamicColumns(db); // Doesn't fail
        CanFindDynamicColumn(db); // Doesn't fail

        var query = db.GetTable<ChildClass>()
            .Where(it => it.Parent!.ParentProperty == 123);

        await query
            .ToArrayAsync(); // Fails: Association key 'ParentId' not found for type 'ChildClass.
    }

    private static void CanFindDynamicColumn(DataConnection db)
    {
        var assoc = db.MappingSchema.GetAttributes<AssociationAttribute>(
            typeof(ChildClass),
            typeof(ChildClass).GetProperty(nameof(ChildClass.Parent))!
        ).Single();

        var dynamicColumn = db.MappingSchema.GetDynamicColumns(typeof(ChildClass)).Single();

        Debug.Assert(dynamicColumn.Name == assoc.ThisKey);

        var col = db.MappingSchema.GetAttributes<ColumnAttribute>(
            typeof(ChildClass),
            dynamicColumn
        ).SingleOrDefault();

        Debug.Assert(col != null);
    }

    private static async Task CanInsertAndReadDynamicColumns(DataConnection db)
    {
        var before = new ChildClass
        {
            Id = "test",
            ExtendedProperties = new() { ["ParentId"] = "1234" },
        };

        await db.InsertAsync(before);

        var after = await db.GetTable<ChildClass>().SingleAsync();

        Debug.Assert(
            before.ExtendedProperties["ParentId"].Equals(after.ExtendedProperties["ParentId"])
        );
    }
}

[Table]
public class ParentClass
{
    [Column(IsPrimaryKey = true)]
    public required string Id { get; set; }

    [Column]
    public required int ParentProperty { get; set; }
}

[Table]
public class ChildClass
{
    [Column(IsPrimaryKey = true)]
    public required string Id { get; set; }

    public ParentClass? Parent { get; set; }

    [DynamicColumnsStore]
    public Dictionary<string, object> ExtendedProperties { get; set; } = new();
}

public class CustomMetadataReader : IMetadataReader
{
    public MappingAttribute[] GetAttributes(Type type) => [];

    public MappingAttribute[] GetAttributes(Type type, MemberInfo memberInfo)
    {
        if (memberInfo is DynamicColumnInfo)
            return [new ColumnAttribute(memberInfo.Name)];

        if (memberInfo.Name != nameof(ChildClass.Parent))
            return [];

        return [new AssociationAttribute { ThisKey = "ParentId", OtherKey = "Id" }];
    }

    public MemberInfo[] GetDynamicColumns(Type type)
    {
        if (type != typeof(ChildClass)) return [];

        return [new DynamicColumnInfo(type, typeof(string), "ParentId")];
    }

    public string GetObjectID() => $".{nameof(CustomMetadataReader)}.";
}

  ```
  
</details>

### Environment details

`Linq To DB` version: *5.4.1*

Database (with version): I've tried with both Postgres and Sqlite 5.4.1

ADO.NET Provider (with version):  *Microsoft.Data.Sqlite 8.0.7* 

Operating system: Both Windows and Linux

.NET Version: Both 7 and 8

**Comment by boginw** [comment]
I'm able to get it to work with the following code:

```csharp
private static void Fix(DataConnection db, params Type[] tables)
{
    foreach (Type table in tables)
    {
        var typeAccessor = TypeAccessor.GetAccessor(table);

        var dynamicColumns = db.MappingSchema.GetDynamicColumns(table)
            .Concat(table.GetProperties());

        foreach (MemberInfo col in dynamicColumns)
        {
            var existing = typeAccessor.Members.Find(it => it.MemberInfo == col);
            if (existing != null)
                typeAccessor.Members.Remove(existing);

            var accessor = new MemberAccessor(typeAccessor, col, null);
            typeAccessor.Members.Add(accessor);
        }
    }
}
```

However, after implementing it in our webserver, it begins to throw after 12 hours:

```
System.AggregateException: One or more errors occurred. (Exception has been thrown by the target of an invocation.)
 ---> System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation.
 ---> System.ArgumentException: An item with the same key has already been added. Key: PersonAdvisesCustomerAdvisorId
   at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at System.Collections.Generic.Dictionary`2.Add(TKey key, TValue value)
   at LinqToDB.Mapping.EntityDescriptor.Init(Action`2 onEntityDescriptorCreated)
   at LinqToDB.Mapping.MappingSchema.<>c.<GetEntityDescriptor>b__98_0(ICacheEntry`2 o, ValueTuple`2 context)
   at LinqToDB.Common.Internal.Cache.CacheExtensions.GetOrCreate[TItem,TKey,TContext](IMemoryCache`2 cache, TKey key, TContext context, Func`3 factory)
   at LinqToDB.Linq.Table`1..ctor(IDataContext dataContext)
   at LinqToDB.DataExtensions.GetTable[T](IDataContext dataContext)
   at InvokeStub_DataExtensions.GetTable(Object, Span`1)
   [project specific calls here]
```

**Comment by boginw** [comment]
There seems to be a discrepancy between how `AssociationHelper.cs` resolves members and how `EntityDescriptor.cs` does.

https://github.com/linq2db/linq2db/blob/89b1b78041d88cfe03829def11d9ff71870082de/Source/LinqToDB/Linq/Builder/AssociationHelper.cs#L105-L107

https://github.com/linq2db/linq2db/blob/89b1b78041d88cfe03829def11d9ff71870082de/Source/LinqToDB/Mapping/EntityDescriptor.cs#L204-L205

This seems to be what makes my previous `Fix` method work, since it appends the members to the `TypeAccessor`, but when the cache-entry is evicted it fails. I think `AssociationHelper.cs` needs to take dynamic-members into account and then we'll be good (I think).
