### ISSUE TITLE
linq2db.EntityFrameworkCore: Error when im using ThenInclude in recursive CTE

### ISSUE THREAD

**Issue by Rofliex** [linq2db/linq2db#4603]
### Describe your issue

I decided to look at working with recursive CTEs since they are missing in ef core. I made a simple hierarchical structure (details below). Everything works if I try to include nested entities at depth 1, but breaks if I add ThenInclude.

```
Exception message: LinqToDB.LinqToDBException: Member 'x.Users' is not an association.
Stack trace:
 at LinqToDB.Linq.Builder.LoadWithBuilder.GetAssociations(ExpressionBuilder builder, Expression expression, Expression stopExpression)+MoveNext()
   at LinqToDB.Linq.Builder.LoadWithBuilder.ExtractAssociations(ExpressionBuilder builder, Expression expression, Expression stopExpression)+MoveNext()
   at System.Collections.Generic.LargeArrayBuilder`1.AddRange(IEnumerable`1 items)
   at System.Collections.Generic.EnumerableHelpers.ToArray[T](IEnumerable`1 source)
   at System.Linq.Enumerable.ReverseIterator`1.ToArray()
   at LinqToDB.Linq.Builder.LoadWithBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.WhereBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.SelectBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.SetOperationBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.TableBuilder.<>c__DisplayClass11_0.<BuildCteContext>b__1(CteClause cteClause)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildCte(Expression cteExpression, Func`2 buildFunc)
   at LinqToDB.Linq.Builder.TableBuilder.BuildCteContext(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.TableBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
// calling .ToListAsyncLinqToDB() from my code
```

### Steps to reproduce

Models

```c#
[StronglyTypedId(Template.Guid, "guid-efcore")]
public partial struct DivisionId
{
}

public class Division
{
    public DivisionId Id { get; set; }
    public string Name { get; set; }
    public string? Description { get; set; }
    public DivisionId? ParentDivisionId { get; set; }
    public Division? ParentDivision { get; set; }
    public ICollection<StaffUnit> StaffUnits { get; set; }
    public ICollection<Division> ChildDivisions { get; set; }
}

[StronglyTypedId(Template.Guid, "guid-efcore")]
public partial struct StaffUnitId
{
}
public class StaffUnit
{
    public StaffUnitId Id { get; set; }
    public string Name { get; set; }
    public string? Description { get; set; }
    public DivisionId DivisionId { get; set; }
    public Division? Division { get; set; }
    public ICollection<User> Users { get; set; }
}
```

Ef configurations:
```c#
public class DivisionConfiguration : IEntityTypeConfiguration<Division>
{
    public void Configure(EntityTypeBuilder<Division> builder)
    {
        builder.HasKey(x => x.Id);

        builder.Property(x => x.Id)
            .HasConversion(new DivisionId.EfCoreValueConverter())
            .ValueGeneratedNever();

        builder.Property(x => x.Name).IsRequired().HasMaxLength(100);
        builder.Property(x => x.Description).HasMaxLength(500);

        builder
            .HasOne(x => x.ParentDivision)
            .WithMany(x => x.ChildDivisions)
            .HasForeignKey(x => x.ParentDivisionId);

        builder
            .HasMany(x => x.StaffUnits)
            .WithOne(x => x.Division)
            .HasForeignKey(x => x.DivisionId);
    }
}
public class StaffUnitConfiguration : IEntityTypeConfiguration<StaffUnit>
{
    public void Configure(EntityTypeBuilder<StaffUnit> builder)
    {
        builder.HasKey(x => x.Id);

        builder.Property(x => x.Id)
            .HasConversion(new StaffUnitId.EfCoreValueConverter())
            .ValueGeneratedNever();

        builder.Property(x => x.Name).IsRequired().HasMaxLength(100);
        builder.Property(x => x.Description).HasMaxLength(500);

        builder
            .HasMany(x => x.Users)
            .WithMany()
            //.UsingEntity<Dictionary<string, object>>(
            //    "UserStaffUnit",
            //    x => x.HasOne<User>().WithMany().HasForeignKey("UserId"),
            //    x => x.HasOne<StaffUnit>().WithMany().HasForeignKey("StaffUnitId")
            //);
        ;
    }
}
```

Example of work with CTE:
```c#
var linq2DbCtx = _db.CreateLinqToDBContext();
var divisionsCte = linq2DbCtx.GetCte<Division>(
    hierarchy =>
    {
        return 
        (_db.Divisions
            .Include(x=> x.StaffUnits)
            //.ThenInclude(x => x.Users)
            .Where(@t => @t.Id == new DivisionId(Guid.Parse("00000000-0000-0000-0000-000000000001")))
            .Select(@t => @t)).Concat
        (_db.Divisions
            .Join(
                hierarchy, 
                o => o.ParentDivisionId, 
                c => c.Id, 
                (d, c) => d)
        );
    }
);

var cteResult = await divisionsCte.ToListAsyncLinqToDB();
```
As i said - without `ThenInclude` all works. But if im wanna include some data from "joined" to cte data (example to StaffUnits) im getting error.
### Environment details

`Linq To DB` version: >=5.4.0
Operating system: windows 11(22h2)
Database (with version): Postgres 16.1
.NET Version:  .net8 (dotnet --version -> `8.0.300`)
Packages:
```xaml
<PackageVersion Include="Microsoft.EntityFrameworkCore" Version="8.0.4" />
<PackageVersion Include="linq2db.EntityFrameworkCore" Version="8.1.0" />
```

**Comment by sdanyliv** [comment]
`Include` in RecursiveCTE should not work, it is known limitation. Create intermediate class `DivisionCte` project all needed fields Then outside of CTE, join to this CTE and fill rest of the fields.

**Comment by MaceWindu** [comment]
There is not enough data to reproduce this issue:
- User class and it's mappings not provided
- Some unknown types and methods used

I don't observe any issues with simple model like that, so it could be an issue in your mappings of `Users`:
```cs
public class Parent
{
	public int Id { get; set; }
	public int? ParentId { get; set; }

	public ICollection<Child> Children { get; set; } = null!;
}

public class Child
{
	public int Id { get; set; }
	public int ParentId { get; set; }

	public Parent Parent { get; set; } = null!;
	public ICollection<GrandChild> GrandChildren { get; set; } = null!;
}

public class GrandChild
{
	public int Id { get; set; }
	public int ChildId { get; set; }

	public Child Child { get; set; } = null!;
}
```

**Comment by MaceWindu** [comment]
Closing as duplicate of #4012, which tracks the same limitation — eager-loading associations (`LoadWith`/`Include`/`ThenInclude`) into recursive-CTE results in linq2db.EntityFrameworkCore. The `ThenInclude` repro and the maintainer's known-limitation note have been consolidated there. Any further info, please add to #4012.
