### ISSUE TITLE
[BUG] Memory leak issue, when using linq2db efcore library 7.7.0

### ISSUE THREAD

**Issue by aloksharma1** [linq2db/linq2db#4639]
Hello Guys,

in the version 7.7.0 of [linq2db.EntityFrameworkCore](https://github.com/linq2db/linq2db.EntityFrameworkCore), main library version 5.4.0 with ef core 7.0.20. I am seeing a sudden surge and retention of objects in linq2db memory cache for much longer than required and it's not disposing correctly.

if I remove linq2db implementation from that part of code it stops leaking memory. I can confirm this issue was not present in my project with previous versions as its an existing project and we just did a library version update and nothing else. 
i did a memory diagnostic too and saw that each of the snapshot linq2db was holding big objects (14-16 mb per request).
its an mvc application, i cant share the code but i think if you can make a complex 3 level table and do merge/complex crud/union on it you will be able to see it.

@MaceWindu @sdanyliv

**Comment by aloksharma1** [comment]
@MaceWindu critical problem, i have updated my project to net 8 and for ef core and linq2db to this package config for net 8

```
<ItemGroup Condition="'$(TargetFramework)' == 'net8.0'">
	<PackageReference Include="linq2db.EntityFrameworkCore" Version="8.2.0-rc.13787" />
	<PackageReference Include="LinqKit.Microsoft.EntityFrameworkCore" Version="8.1.5" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.8">
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>
	<PackageReference Include="Microsoft.EntityFrameworkCore.DynamicLinq" Version="8.4.5" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Relational" Version="8.0.8" />
	<PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.8">
		<PrivateAssets>all</PrivateAssets>
	</PackageReference>
</ItemGroup>
```

now another kind of error issue i got in trying to access my already working code on net 7 version
```
[18:02:00 ERR] An error occurred during the normalization of blog posts.
System.MissingMethodException: Method not found: 'System.Nullable`1<Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier> Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier.Create(Microsoft.EntityFrameworkCore.Metadata.IReadOnlyEntityType, Microsoft.EntityFrameworkCore.Metadata.StoreObjectType)'.
   at LinqToDB.EntityFrameworkCore.EFCoreMetadataReader.GetStoreObjectIdentifier(IEntityType entityType)
   at LinqToDB.EntityFrameworkCore.EFCoreMetadataReader.GetAttributes(Type type, MemberInfo memberInfo)
   at LinqToDB.Metadata.MetadataReader.<.ctor>b__9_1(Type type, ICustomAttributeProvider source)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesTreeInternal(Key key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesInternal(CacheKey key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributes[T](Type sourceOwner, ICustomAttributeProvider source)
   at LinqToDB.Metadata.MetadataReader.GetAttributes[T](Type type, MemberInfo memberInfo)
   at LinqToDB.Mapping.MappingSchema.GetAllAttributes[T](Type type, MemberInfo memberInfo)
   at LinqToDB.Mapping.MappingSchema.<CreateAttributeCaches>b__52_0(Type sourceOwner, ICustomAttributeProvider source)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesTreeInternal(Key key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesInternal(CacheKey key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributes[T](Type sourceOwner, ICustomAttributeProvider source)
   at LinqToDB.Mapping.MappingSchema.GetAttribute[T](Type type, MemberInfo memberInfo)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.ConvertMethodExpression(Type type, MemberInfo mi, String& alias)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.ExposeExpressionTransformer(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.ExposeExpression(Expression expression)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsyncEnumerable[TResult](Expression expression, CancellationToken cancellationToken)
   at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.<GetAsyncEnumerator>g__EnumerateAsyncEnumerable|23_0(CancellationToken ct)+MoveNext()
   at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.<GetAsyncEnumerator>g__EnumerateAsyncEnumerable|23_0(CancellationToken ct)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Ultra.BlogModule.Core.Services.Tasks.ExistingBlogPostNormalizer.GetBlogPostDataAsync(IServiceProvider serviceProvider) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule.Core\Services\Tasks\ExistingBlogPostNormalizer.cs:line 298
   at Ultra.BlogModule.Core.Services.Tasks.ExistingBlogPostNormalizer.NormalizeOperation(IServiceScope scope) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule.Core\Services\Tasks\ExistingBlogPostNormalizer.cs:line 53
   at Ultra.BlogModule.Core.Services.Tasks.ExistingBlogPostNormalizer.ExecuteAsync(CancellationToken cancellationToken) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule.Core\Services\Tasks\ExistingBlogPostNormalizer.cs:line 36
[18:03:00 ERR] An error occurred during the normalization of blog posts.
System.MissingMethodException: Method not found: 'System.Nullable`1<Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier> Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier.Create(Microsoft.EntityFrameworkCore.Metadata.IReadOnlyEntityType, Microsoft.EntityFrameworkCore.Metadata.StoreObjectType)'.
   at LinqToDB.EntityFrameworkCore.EFCoreMetadataReader.GetStoreObjectIdentifier(IEntityType entityType)
   at LinqToDB.EntityFrameworkCore.EFCoreMetadataReader.GetAttributes(Type type, MemberInfo memberInfo)
   at LinqToDB.Metadata.MetadataReader.<.ctor>b__9_1(Type type, ICustomAttributeProvider source)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesTreeInternal(Key key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesInternal(CacheKey key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributes[T](Type sourceOwner, ICustomAttributeProvider source)
   at LinqToDB.Metadata.MetadataReader.GetAttributes[T](Type type, MemberInfo memberInfo)
   at LinqToDB.Mapping.MappingSchema.GetAllAttributes[T](Type type, MemberInfo memberInfo)
   at LinqToDB.Mapping.MappingSchema.<CreateAttributeCaches>b__52_0(Type sourceOwner, ICustomAttributeProvider source)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesTreeInternal(Key key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesInternal(CacheKey key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributes[T](Type sourceOwner, ICustomAttributeProvider source)
   at LinqToDB.Mapping.MappingSchema.GetAttribute[T](Type type, MemberInfo memberInfo)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.ConvertMethodExpression(Type type, MemberInfo mi, String& alias)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.ExposeExpressionTransformer(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.ExposeExpression(Expression expression)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsyncEnumerable[TResult](Expression expression, CancellationToken cancellationToken)
   at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.<GetAsyncEnumerator>g__EnumerateAsyncEnumerable|23_0(CancellationToken ct)+MoveNext()
   at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.<GetAsyncEnumerator>g__EnumerateAsyncEnumerable|23_0(CancellationToken ct)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Ultra.BlogModule.Core.Services.Tasks.ExistingBlogPostNormalizer.GetBlogPostDataAsync(IServiceProvider serviceProvider) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule.Core\Services\Tasks\ExistingBlogPostNormalizer.cs:line 298
   at Ultra.BlogModule.Core.Services.Tasks.ExistingBlogPostNormalizer.NormalizeOperation(IServiceScope scope) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule.Core\Services\Tasks\ExistingBlogPostNormalizer.cs:line 53
   at Ultra.BlogModule.Core.Services.Tasks.ExistingBlogPostNormalizer.ExecuteAsync(CancellationToken cancellationToken) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule.Core\Services\Tasks\ExistingBlogPostNormalizer.cs:line 36
[18:04:00 ERR] An error occurred during the normalization of blog posts.
System.MissingMethodException: Method not found: 'System.Nullable`1<Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier> Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier.Create(Microsoft.EntityFrameworkCore.Metadata.IReadOnlyEntityType, Microsoft.EntityFrameworkCore.Metadata.StoreObjectType)'.
   at LinqToDB.EntityFrameworkCore.EFCoreMetadataReader.GetStoreObjectIdentifier(IEntityType entityType)
   at LinqToDB.EntityFrameworkCore.EFCoreMetadataReader.GetAttributes(Type type, MemberInfo memberInfo)
   at LinqToDB.Metadata.MetadataReader.<.ctor>b__9_1(Type type, ICustomAttributeProvider source)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesTreeInternal(Key key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesInternal(CacheKey key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributes[T](Type sourceOwner, ICustomAttributeProvider source)
   at LinqToDB.Metadata.MetadataReader.GetAttributes[T](Type type, MemberInfo memberInfo)
   at LinqToDB.Mapping.MappingSchema.GetAllAttributes[T](Type type, MemberInfo memberInfo)
   at LinqToDB.Mapping.MappingSchema.<CreateAttributeCaches>b__52_0(Type sourceOwner, ICustomAttributeProvider source)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesTreeInternal(Key key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributesInternal(CacheKey key)
   at LinqToDB.Metadata.MappingAttributesCache.GetMappingAttributes[T](Type sourceOwner, ICustomAttributeProvider source)
   at LinqToDB.Mapping.MappingSchema.GetAttribute[T](Type type, MemberInfo memberInfo)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.ConvertMethodExpression(Type type, MemberInfo mi, String& alias)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.ExposeExpressionTransformer(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Linq.Builder.ExpressionTreeOptimizationContext.ExposeExpression(Expression expression)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.LinqToDB.Async.IQueryProviderAsync.ExecuteAsyncEnumerable[TResult](Expression expression, CancellationToken cancellationToken)
   at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.<GetAsyncEnumerator>g__EnumerateAsyncEnumerable|23_0(CancellationToken ct)+MoveNext()
   at LinqToDB.EntityFrameworkCore.Internal.LinqToDBForEFQueryProvider`1.<GetAsyncEnumerator>g__EnumerateAsyncEnumerable|23_0(CancellationToken ct)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at Microsoft.EntityFrameworkCore.EntityFrameworkQueryableExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
   at Ultra.BlogModule.Core.Services.Tasks.ExistingBlogPostNormalizer.GetBlogPostDataAsync(IServiceProvider serviceProvider) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule.Core\Services\Tasks\ExistingBlogPostNormalizer.cs:line 298
   at Ultra.BlogModule.Core.Services.Tasks.ExistingBlogPostNormalizer.NormalizeOperation(IServiceScope scope) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule.Core\Services\Tasks\ExistingBlogPostNormalizer.cs:line 53
   at Ultra.BlogModule.Core.Services.Tasks.ExistingBlogPostNormalizer.ExecuteAsync(CancellationToken cancellationToken) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule.Core\Services\Tasks\ExistingBlogPostNormalizer.cs:line 36

```
the issue is coming as `System.MissingMethodException`  as it cannot find **`Microsoft.EntityFrameworkCore.Metadata.StoreObjectIdentifier.Create`**

**Comment by MaceWindu** [comment]
Looks like you mixed different assembly versions

**Comment by aloksharma1** [comment]
@MaceWindu ok what is the correct version for ef core 8.0.8?

**Comment by MaceWindu** [comment]
You should check what your bin folder contains. I suspect there are some wrong assemblies copied due to incorrect dependencies

**Comment by aloksharma1** [comment]
ok i was able to run the project after cleaning the nuget cache and deleting bin/obj files. in preliminary tests linq2db seems stable with memory leaks just that query execution is feeling super slow. 
another thing i encountered with a complex query that was working before :

```
Microsoft.Data.SqlClient.SqlException (0x80131904): The column 'Id' was specified multiple times for 't5'.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at Microsoft.Data.SqlClient.SqlDataReader.get_MetaData()
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean isAsync, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry, String method)
   at Microsoft.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior)
   at Microsoft.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteDataReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.BasicResultEnumerable`1.GetEnumerator()+MoveNext()
   at LinqToDB.Linq.Builder.ExpressionBuilder.Preamble`2.Execute(IDataContext dataContext, Expression expression, Object[] parameters, Object[] preambles)
   at LinqToDB.Linq.Query.InitPreambles(IDataContext dc, Expression rootExpression, Object[] ps)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at X.PagedList.PagedListExtensions.ToPagedListAsync[T](IQueryable`1 superset, Int32 pageNumber, Int32 pageSize, Nullable`1 totalSetCount, CancellationToken cancellationToken)
   at X.PagedList.PagedListExtensions.ToPagedListAsync[T](IQueryable`1 superset, Int32 pageNumber, Int32 pageSize, Nullable`1 totalSetCount)
   at Ultra.BlogModule.Core.Services.Implementations.CoreServices.BlogService.GetBlogPostListByGroupAsync(String blogGroupBy, String blogType, Nullable`1 num, Nullable`1 size, Nullable`1 take, String orderBy, Nullable`1 selectFullInfo, Nullable`1 selectFeatured, Nullable`1 selectPopular) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule.Core\Services\Implementations\CoreServices\BlogService.cs:line 2442
   at Ultra.BlogModule.Components.BlogPostListGroupByTypes.InvokeAsync(String viewname, String viewtype, String blogGroupBy, String blogType, Nullable`1 num, Nullable`1 Size, Int32 take, String orderBy, Boolean selectFullInfo, Boolean selectFeatured, Boolean selectPopular) in E:\Dotnet\Web\MVC\UltraWeb\Net8\MVC\Ultra.BlogModule\Components\BlogPostListGroupByTypes.cs:line 19
```

i will continue to do more thorough tests for all our complex data structures in coming days.

do you want me to report my findings in separate threads or this single thread?

**Comment by MaceWindu** [comment]
> do you want me to report my findings in separate threads or this single thread?

Yes, fill separate issues

**Comment by aloksharma1** [comment]
hello, is there any progress on the leaking issue yet?

**Comment by MaceWindu** [comment]
First we need to identify "leak" source. For that I will probably need memory profiler report.

**Comment by aloksharma1** [comment]
i could have helped with if i had to look for some specific code, but even i dont know how to use memory profilers in-depth the only reason i was able to trace this issue was because your library was the only thing i updated in my deployed project.

**Comment by aloksharma1** [comment]
@MaceWindu hello, any idea how close you are to clear this issue.

**Comment by MaceWindu** [comment]
As I mentioned before - without repro code or memory profile information there is nothing we can do here.

**Comment by aloksharma1** [comment]
@MaceWindu ok then the only way to check it is when you release the next version of lib, please let me know when next preview version becomes available.

**Comment by MaceWindu** [comment]
You could try latest release from azure feed or wait for nuget release (planned next week)

**Comment by aloksharma1** [comment]
hello, is the new release ready? also will a perfview log help you, i can run a perfview analysis on live site with jmeter and give you the dump for it.

**Comment by aloksharma1** [comment]
k i will make a perfview log with rc lib then

**Comment by MaceWindu** [comment]
Also I don't see how jmeter could help here. What we need is a memory allocation profile to identity potential objects stuck in memory.

You could try to use trial version https://memprofiler.com/ to attach to your process in time when it has unusual memory consumption to take snapshot and analyse anomalies in it

**Comment by MaceWindu** [comment]
Stale
