### ISSUE TITLE
System.InvalidOperationException: No coercion operator is defined between types 'System.Guid' and 'System.String'.

### ISSUE THREAD

**Issue by aloksharma1** [linq2db/linq2db#4654]
this issue is back in new preview version, i have a few queries like this

```
using LinqToDB;
using Microsoft.Extensions.DependencyInjection;
using Ultra.Abstractions.Processors;
using Ultra.Services.Accessibility;

namespace Ultra.BlogModule.Core.Services.Implementations.SearchProviders
{
    [SingletonService(typeof(ISearchProvider))]
    public class GetBlogSearchQuery : ISearchProvider
    {
        public string GroupName { get; set; } = "PageGroup";
        public string Name { get; set; } = "Blogs";
        public int Order { get; set; } = -999;
        public IServiceProvider ServiceProvider { get; set; }
        public GetBlogSearchQuery(IServiceProvider serviceProvider)
        {
            ServiceProvider = serviceProvider;
        }
        public dynamic? GetSearchQuery(string? SearchTerm)
        {
            using (var scope = ServiceProvider.GetRequiredService<IServiceScopeFactory>().CreateScope())
            {
                if (SearchTerm.IsNullOrWhiteSpace())
                {
                    return default;
                }
                return GetSearchQuery(SearchTerm, scope);
            }
        }

        public dynamic? GetSearchQuery(string? SearchTerm = null, IServiceScope? serviceScope = null)
        {
            if (SearchTerm.IsNullOrWhiteSpace() || serviceScope == null)
            {
                return default;
            }
            var provider = serviceScope.ServiceProvider;
            var service = provider.GetRequiredService<IAccountService>();
            var repository = provider.GetRequiredService<IRepository<BlogPostInfo, UltraDbContext>>();
            var _imageRepository = provider.GetRequiredService<IRepository<Images, UltraDbContext>>();
            var _blogImagesRepository = provider.GetRequiredService<IRepository<BlogPostImages, UltraDbContext>>();
            var _blogAuthorRepository = provider.GetRequiredService<IRepository<BlogAuthor, UltraDbContext>>();
            var _blogCategoryRepository = provider.GetRequiredService<IRepository<BlogCategory, UltraDbContext>>();
            var _blogTypeRepository = provider.GetRequiredService<IRepository<BlogTypes, UltraDbContext>>();
            var _pageRepository = provider.GetRequiredService<IRepository<Pages, UltraDbContext>>();
            var query = repository.Query()!
                .Where(x => x.SiteId == service.GetSiteId()
                && x.IsActive == true
                && (x.RecordStatus == RecordStatus.Published || (x.RecordStatus == RecordStatus.ScheduledPublished && x.PublishDate <= DateTimeOffset.UtcNow))
                && x.SearchStatus != SearchStatus.NotSearchable);
            if (SearchTerm.IsNotNullOrWhiteSpace())
            {
                query = query.Where(x => x.PageName!.Contains(SearchTerm!) ||
                x.MainCategoryId == _blogCategoryRepository.Query()!.Where(b => b.CategoryName!.Contains(SearchTerm!) && b.IsActive == true && b.SiteId == x.SiteId && b.CategoryBlogTypeId == x.BlogPostTypeId).Select(b => b.Id).FirstOrDefault());
            }
            var result = query.Select(x => new SearchResults
            {
                DateCreated = x.DateCreated,
                Id = "" + x.Id, <-- problem here
                Slug = x.PageSlugUrl,
                Title = x.PageName,
                Summary = x.PageSummary,
                Images = null,                
                Videos = null,
                Files = null,
                Htmls = null,
                Links = null,
                Category = _blogCategoryRepository.Query()!.Where(b => b.Id == x.MainCategoryId).Select(b => b.CategoryName).FirstOrDefault(),
                CategoryTrail = x.CategoryParentTrail,
                Type = _blogTypeRepository.Query()!.Where(b => b.Id == x.BlogPostTypeId).Select(b => b.Name).FirstOrDefault(),
                AuthorName = _blogAuthorRepository.Query()!.Where(ba => ba.Id == x.AuthorId).Select(ba => ba.PenName).FirstOrDefault(),
                AuthorProfile = _pageRepository.Query()!.Where(pa => pa.RecordStatus == RecordStatus.Published && pa.IsActive == true && pa.Id == _blogAuthorRepository.Query()!.Where(ba => ba.Id == x.AuthorId).Select(ba => ba.BioPageId).FirstOrDefault()).Select(pa => pa.PageSlugUrl).FirstOrDefault(),
                DatePublished = x.PublishDate,
                ResultOrder = -999,
                ProviderTable = "Blogs"
            });
            //.Where(x => x.SiteId == service.GetSiteId()
            //&& x.IsActive == true && x.PageName.StartsWith(SearchTerm) && x.RecordStatus == RecordStatus.Published
            //&& x.SearchStatus != SearchStatus.DisabledSearchable)
            return result;
        }
    }
}
```
which i use to union and show end result for search purposes. the code was working fine on previous version but on 8.2.0-rc.13787 its back.

**error details: Id = "" + x.Id, <-- problem here**

```
System.InvalidOperationException: No coercion operator is defined between types 'System.Guid' and 'System.String'.
   at System.Linq.Expressions.Expression.GetUserDefinedCoercionOrThrow(ExpressionType coercionType, Expression expression, Type convertToType)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass140_0.<ToReadExpression>b__1(Expression e)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.TransformInfoVisitor`1.TransformMemberBinding(MemberBinding b)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform[T](IList`1 source, Func`2 func)
   at LinqToDB.Expressions.TransformInfoVisitor`1.Transform(Expression expr)
   at LinqToDB.Expressions.ExpressionExtensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.ExpressionBuilder.ToReadExpression(ExpressionGenerator expressionGenerator, NullabilityContext nullability, Expression expression)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildMapper[T](SelectQuery query, Expression expr)
   at LinqToDB.Linq.Builder.SelectContext.SetRunQuery[T](Query`1 query, Expression expr)
   at LinqToDB.Linq.Builder.SubQueryContext.SetRunQuery[T](Query`1 query, Expression expr)
   at LinqToDB.Linq.Builder.SubQueryContext.SetRunQuery[T](Query`1 query, Expression expr)
   at LinqToDB.Linq.Builder.SubQueryContext.SetRunQuery[T](Query`1 query, Expression expr)
   at LinqToDB.Linq.Builder.SubQueryContext.SetRunQuery[T](Query`1 query, Expression expr)
   at LinqToDB.Linq.Builder.SubQueryContext.SetRunQuery[T](Query`1 query, Expression expr)
   at LinqToDB.Linq.Builder.SubQueryContext.SetRunQuery[T](Query`1 query, Expression expr)
   at LinqToDB.Linq.Builder.SubQueryContext.SetRunQuery[T](Query`1 query, Expression expr)
   at LinqToDB.Linq.Builder.PassThroughContext.SetRunQuery[T](Query`1 query, Expression expr)
   at LinqToDB.Linq.Builder.PassThroughContext.SetRunQuery[T](Query`1 query, Expression expr)
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildQuery[T](Query`1 query, IBuildContext sequence, ParameterExpression queryParameter, List`1& preambles, Expression[] previousKeys)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(ExpressionTreeOptimizationContext optimizationContext, ParametersContext parametersContext, IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache, Boolean& dependsOnParameters)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at X.PagedList.PagedListExtensions.ToPagedListAsync[T](IQueryable`1 superset, Int32 pageNumber, Int32 pageSize, Nullable`1 totalSetCount, CancellationToken cancellationToken)
   at X.PagedList.PagedListExtensions.ToPagedListAsync[T](IQueryable`1 superset, Int32 pageNumber, Int32 pageSize, Nullable`1 totalSetCount)
   at Ultra.BasicSiteModules.Components.SimplePageSearchList.InvokeAsync(String viewname, String viewtype, String searchTerm, Nullable`1 num, Nullable`1 Size) in 
```

here is how i combine queries from different modules and materialize the result wherever i need it.

```
public IQueryable<SearchResults>? GetSearchResultQuery(string? searchTerm)
{
    _scope = _scopeFactory.CreateScope();
    //x.GroupName == "PageGroup" x.Name == "Blogs"
    var queries = _searchProviders.Where(x => x.GroupName == "PageGroup").Select(x => x.GetSearchQuery(searchTerm, serviceScope: _scope) as IQueryable<SearchResults>).Where(x => x != null).ToList();
    if (queries?.Count > 0)
    {
        var query = queries.Aggregate((current, next) => next != null ? current?.Union(next!) : current)!;
        return query;
    }
    return default;
}
```

working on the sample repo to make issue clearer with another problem similarly related with union queries.

.Net Version: 8
Ef Core: 8.0.8
Linq2db.EntityFrameworkCore : 8.2.0-rc.13787
linq2db 6.0.0-rc.13787

**Comment by aloksharma1** [comment]
@MaceWindu here is the repo for problem https://github.com/aloksharma1/Guid.UnionIssue.Linq2DB

if you use ""+Id you get error but Id.ToString() works but in practice both should be working.
