### ISSUE TITLE
BulkCopy with KeepIdentity doesn't update the identity sequence in PostgreSQL

### ISSUE THREAD

**Issue by exileDev** [linq2db/linq2db#4702]
### Describe your issue

I have built a console application with a simple entity using the T4 template. After bulk operation postgresql throws exception:

```
Exception message: Npgsql.PostgresException: '23505: duplicate key value violates unique constraint "testtable_pkey"
Stack trace:
   at Npgsql.Internal.NpgsqlConnector.<<ReadMessage>g__ReadMessageLong|234_0>d.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlDataReader.<<ReadMessage>g__ReadMessageSequential|44_0>d.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlDataReader.<NextResult>d__47.MoveNext()
   at Npgsql.NpgsqlDataReader.<NextResult>d__47.MoveNext()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__124.MoveNext()
   at Npgsql.NpgsqlCommand.<ExecuteReader>d__124.MoveNext()
   at System.Threading.Tasks.ValueTask`1.get_Result()
   at Npgsql.NpgsqlCommand.<ExecuteScalar>d__115.MoveNext()
   at LinqToDB.Data.DataConnection.<ExecuteScalarAsync>d__12.MoveNext()
   at LinqToDB.Data.DataConnection.<ExecuteScalarAsync>d__12.MoveNext()
   at LinqToDB.Data.DataConnection.<ExecuteScalarDataAsync>d__13.MoveNext()
   at LinqToDB.Data.DataConnection.<ExecuteScalarDataAsync>d__13.MoveNext()
   at LinqToDB.Data.DataConnection.QueryRunner.<ExecuteScalarAsync>d__43.MoveNext()
   at LinqToDB.Linq.QueryRunner.<ScalarQueryAsync>d__31.MoveNext()
   at LinqToDB.Linq.QueryRunner.<ScalarQueryAsync>d__31.MoveNext()
   at LinqToDB.Linq.QueryRunner.<ScalarQueryAsync>d__31.MoveNext()
   at LinqToDB.Linq.QueryRunner.InsertWithIdentity`1.<QueryAsync>d__2.MoveNext()
   at LinqToDB.Linq.QueryRunner.InsertWithIdentity`1.<QueryAsync>d__2.MoveNext()
   at LinqToDB.DataExtensions.<InsertWithInt32IdentityAsync>d__25`1.MoveNext()
   at ConsoleApp3.Program.<Main>d__0.MoveNext() in C:\Users\alexey\source\repos\ConsoleApp3\Class1.cs:line 23
```

DTO:

```c#
[Table(Schema="public", Name="testtable")]
public partial class Testtable
{
	[Column("id"),   PrimaryKey, Identity] public int    Id   { get; set; } // integer
	[Column("text"), Nullable            ] public string Text { get; set; } // text
}
```

Code to reproduce the issue:

```c#
            DataConnection.SetConnectionStrings(new MySettings().ConnectionStrings);
            using var db = new DataModels.MyDatabaseDB();

            List<Testtable> ttable = [
                new() { Text = "Text 1" },new() { Text = "Text 2" }, ...
            ];

            await db.Testtables.BulkCopyAsync(new BulkCopyOptions { KeepIdentity = true }, ttable.RetrieveIdentity(db));

            await db.InsertWithInt32IdentityAsync(new Testtable { Text = "text Insert 1" });
```

### Environment details

`Linq To DB` version: 5.4.1
Database (with version): PostgreSQL 12.4

**Comment by HypeillingerChillinger** [comment]
```KeepIdentity``` keeps the identity. If I understand your issue correctly you add two or more times the number zero. After the first insert the second throws since it is also zero.

https://linq2db.github.io/articles/sql/Bulk-Copy.html#options

**Comment by MaceWindu** [comment]
How id column configured in database?
