### ISSUE TITLE
Conversion of Custom Types to SQL does not work as expected for arithmetic operations

### ISSUE THREAD

**Issue by AidenFuller** [linq2db/linq2db#4712]
### Describe your issue

I'm seeing an exception in version 6.0.0-preview.1 which I have not been seeing in previous versions (specifically 5.4.1), and just want to make sure this is on the radar to be patched for the full release.

It appears as though the order of arithmetic operations is causing some grief when attempting to convert custom types to SQL.

#### My setup is as follows
I have a custom type to represent "Percent" values
```cs
public class Percent(decimal Value)
{
    public static implicit operator Percent(decimal value) => new(value);

    public static Percent operator +(Percent lhs, Percent rhs) => new(lhs.Value + rhs.Value);
    // other arithmetic overloads
}
```

I specify the underlying DB type in the MappingSchema creation as
```cs
fluentMappingBuilder.MappingSchema.SetDataType(typeof(Percent), new SqlDataType(DataType.Decimal, typeof(decimal), 18, 6));
```

This would be used in entities in the following way:
```cs
public class SampleEntity
{
    [PrimaryKey]
    public int SampleId { get; set; }
    
    [Column]
    public Percent SamplePercent { get; set; }
}
```

#### Actual issue given the above
When selecting a column directly, there is no issue or exception and the result is as I expect it to be.
The issue comes when I attempt to select a specific arithmetic operation. For example, if I run the following statement I get no error
```cs
await db.GetTable<SampleEntity>().Select(entity => new { entity.SampleId, CalculatedPercent = entity.SamplePercent + 1 }).ToListAsync();
```
But reversing the order of the `entity.SamplePercent + 1` as shown in the below statement somehow produces the below exception.
```cs
await db.GetTable<SampleEntity>().Select(entity => new { entity.SampleId, CalculatedPercent = 1 + entity.SamplePercent }).ToListAsync();
```
Exception:
```
System.InvalidCastException: Failed to convert parameter value from a Percent to a Decimal.
StackTrace: System.InvalidCastException: Failed to convert parameter value from a Percent to a Decimal.
 ---> System.InvalidCastException: Object must implement IConvertible.
   at System.Convert.ChangeType(Object value, Type conversionType, IFormatProvider provider)
   at System.Data.SqlClient.SqlParameter.CoerceValue(Object value, MetaType destinationType, Boolean& coercedToDataFeed, Boolean& typeChanged, Boolean allowStreaming)
   --- End of inner exception stack trace ---
   at System.Data.SqlClient.SqlCommand.<>c.<ExecuteDbDataReaderAsync>b__126_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReaderAsync(CancellationToken cancellationToken)
   at LinqToDB.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext()
   at LinqToDB.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext()
   at LinqToDB.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+MoveNext()
   at LinqToDB.Linq.QueryRunner.BasicResultEnumerable`1.GetAsyncEnumerable(CancellationToken cancellationToken)+System.Threading.Tasks.Sources.IValueTaskSource<System.Boolean>.GetResult()
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.Linq.ExpressionQuery`1.GetForEachAsync(Action`1 action, CancellationToken cancellationToken)
   at LinqToDB.AsyncExtensions.ToListAsync[TSource](IQueryable`1 source, CancellationToken token)
```

### Steps to reproduce

Full code to produce issue can be found here:

```cs
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.DataProvider.SqlServer;
using LinqToDB.Mapping;
using LinqToDB.SqlQuery;

namespace Linq2DbTest;

public class Program
{
    public static async Task Main()
    {
        var connectionString = "INSERT CONNECTION STRING";
        var options = new DataOptions().UseSqlServer(connectionString, SqlServerVersion.AutoDetect, SqlServerProvider.SystemDataSqlClient);

        var fluentMappingBuilder = new FluentMappingBuilder();
        fluentMappingBuilder.MappingSchema.SetDataType(typeof(Percent), new SqlDataType(DataType.Decimal, typeof(decimal), 18, 6));

        fluentMappingBuilder.MappingSchema.SetConverter<Percent, decimal>(c => c.Value);
        fluentMappingBuilder.MappingSchema.SetConverter<decimal, Percent>(c => new Percent(c));

        fluentMappingBuilder.Build();

        await using var db = new DataConnection(options.UseMappingSchema(fluentMappingBuilder.MappingSchema));

        await using var tempTable = await db.CreateTempTableAsync<SampleEntity>();

        var successfulQuery = await tempTable.Select(c => new { Test = c.SampleId, Calculation = c.SamplePercent + 1 }).ToListAsync();
        var problematicQuery = await tempTable.Select(c => new { Test = c.SampleId, Calculation = 1 + c.SamplePercent }).ToListAsync();
    }
}

[Table]
public class SampleEntity
{
    [PrimaryKey]
    public int SampleId { get; set; }
    [Column]
    public Percent SamplePercent { get; set; }
}

public record Percent(decimal Value)
{
    public static implicit operator Percent(decimal value) => new Percent(value);

    public static Percent operator +(Percent a, Percent b) => new Percent(a.Value + b.Value);
    // other operators
}
```

### Environment details

`Linq To DB` version: 6.0.0-preview.1

`linq2db.EntityFrameworkCore` version (if used): N/A

`Entity Framework Core` provider with version (if used): N/A

Database (with version): SQL Server 2019

ADO.NET Provider (with version): System.Data.SqlClient 4.1.0

Operating system: Windows 11

.NET Version: .NET 8 (8.0.401 specifically)

**Comment by MaceWindu** [comment]
`SetDataType` sets type information, but doesn't tell linq2db how to convert this custom type to database value (parameter or literal).

You need to set required conversions too.

```cs
// for conversion to query parameter
ms.SetConvertExpression<Percent,DataParameter>(...)
// for literal generation if you need it
ms.SetValueToSqlConverter(...)
```

**Comment by MaceWindu** [comment]
Ah, sorry. I see you mention it wasn't an issue in older versions. I will check wether we have a regression here

**Comment by AidenFuller** [comment]
Ah makes sense regarding the examples you provided. Based on that, would it be possible that the 5.4.1 version (and older I assume) was the one at fault here and I just happened to find a situation where it worked in my favour by coincidence?
