### ISSUE TITLE
class with explicit interface implementation not working

### ISSUE THREAD

**Issue by lytico** [linq2db/linq2db#4715]
### class with explicit interface implementation not working

I have a class Foo which implements an interface [explicit.](https://learn.microsoft.com/en-us/dotnet/csharp/programming-guide/interfaces/explicit-interface-implementation)

running a query, it gives the following error:

```
Exception message:

Npgsql.PostgresException: 42703: column t1.Limaki.Common.Trees.ITree<Example.Foo>.Roo does not exist

Stack trace:

   at Npgsql.Internal.NpgsqlConnector.ReadMessageLong(Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   at System.Runtime.CompilerServices.PoolingAsyncValueTaskMethodBuilder`1.StateMachineBox`1.System.Threading.Tasks.Sources.IValueTaskSource<TResult>.GetResult(Int16 token)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult(Boolean async, Boolean isConsuming, CancellationToken cancellationToken)
   at Npgsql.NpgsqlDataReader.NextResult()
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(Boolean async, CommandBehavior behavior, CancellationToken cancellationToken)
   at Npgsql.NpgsqlCommand.ExecuteReader(CommandBehavior behavior)
   at Npgsql.NpgsqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteDataReader(CommandBehavior commandBehavior)
   at LinqToDB.Data.DataConnection.ExecuteReader()
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.ExecuteQuery[T](Query query, IDataContext dataContext, Mapper`1 mapper, Expression expression, Object[] ps, Object[] preambles, Int32 queryNumber)+MoveNext()
   at System.Linq.Enumerable.TryGetFirst[TSource](IEnumerable`1 source, Boolean& found)
   at System.Linq.Enumerable.FirstOrDefault[TSource](IEnumerable`1 source)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.<>c__DisplayClass5_0`1.<GetFirstOrDefaultElement>b__0(IDataContext db, Expression expr, Object[] ps, Object[] preambles)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
   at Example.ExplicitInterfaceTests.TestFooTreeError() in *****/ExplicitInterfaceTests.cs:line 42
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Void** arguments, Signature sig, Boolean isConstructor)
   at System.Reflection.MethodBaseInvoker.InvokeWithNoArgs(Object obj, BindingFlags invokeAttr)
```

### Steps to reproduce

code to reproduce the issue:

```c#
using System;
using System.Linq;
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.Mapping;
using Xunit;

namespace Limaki.Common.Trees {

    public interface ITree<TItem> where TItem : ITree<TItem> {

        Guid RootId { get; }

    }

}

namespace Example {

    using Limaki.Common.Trees;

    public class Foo : ITree<Foo> {

        public Guid Id { get; set; }

        public Guid TopicId { get; set; }

        Guid ITree<Foo>.RootId => TopicId;

    }

    public class ExplicitInterfaceTests {

        [Fact]
        public void TestFooTreeError () {

            DataConnection connection = GetDataConnection (ProviderName.PostgreSQL95, "****");

            ITable<Foo> query = connection.GetTable<Foo> ();

            var y = query.FirstOrDefault ();

        }

        DataConnection GetDataConnection (string providerName, string connectionString) {
            var mappingSchema = new MappingSchema ();
            var builder = mappingSchema.GetFluentMappingBuilder ();

            builder
               .Entity<Foo> ()
               .HasTableName ("Foo")
               .Property (t => t.TopicId)
               .HasColumnName ("TopicId")
               .Property (t => t.Id)
               .HasColumnName ("Id")
               .IsPrimaryKey ();

            // this i tried to avoid the error, but no success:

            builder.Entity<ITree<Foo>> ()
               .Ignore (i => i.RootId)
               .Property (i => i.RootId)
               .IsNotColumn ()
                ;

            builder.Build ();

            var conn = new DataConnection (providerName, connectionString, mappingSchema);

            return conn;

        }

    }

}
```

```sql

--  PostgreSQL.9.5 PostgreSQL
SELECT
	t1."Id",
	t1."TopicId",
	t1."Limaki.Common.Trees.ITree<Example.Foo>.RootId"
FROM
	"Foo" t1

```

### Environment details

`Linq To DB` version: *5.4.1*

Database (with version): *PostgreSQL.9.5 PostgreSQL*

Operating system: *Ubuntu 24.04*

.NET Version: *8.0*

**Comment by igor-tkachev** [comment]
Fixed in `6.0.0-preview.1`

**Comment by MaceWindu** [comment]
If you cannot add attribute to property directly, you can use this as workaround:
```cs
...
.Entity<Foo>()
.HasAttribute(typeof(Foo).GetProperty("ITree<Foo>.RootId", BindingFlags.NonPublic | BindingFlags.Instance), new NotColumnAttribute())
...
```

**Comment by lytico** [comment]
thank you,
this workaround worked for me, but i had to use the full class/interface names with namespace:

```
.Entity<Foo>()
.HasAttribute(typeof(Foo)
.GetProperty(
"Limaki.Common.Trees.ITree<Example.Foo>"
, BindingFlags.NonPublic | BindingFlags.Instance), new NotColumnAttribute())

```

now i'm looking for a solution to get the explicit property by an expression to have it refactoring save,
something like:
```
        Expression<Func<Foo, Guid>> rootId =
            s => ((ITree<Foo>)s).RootId;
```
but i think, this is out of scope of this issue, and a general c#-memberinfo-expression problem.

**Comment by MaceWindu** [comment]
Let's keep it open. We need to decide what to do with it.

- at least we should leverage fluent mapping configuration
- also I see issue with v6, where we don't include such property in default select list when it is mapped

**Comment by MaceWindu** [comment]
Small update: this specific case will work in v6 as we will not select read-only property here anymore, but I would recommend to disable column in mapping explicitly to avoid it re-appear in more complex queries.
