### ISSUE TITLE
Scaffold generates a stored procedure call method with extra parameters

### ISSUE THREAD

**Issue by rkirill** [linq2db/linq2db#4718]
Scaffold adds stored procedure output parameters to the calling method.

### Steps to reproduce
Stored procedure
```sql
create procedure Proc1(p1 int)
returns (v1 int)
as
begin
 v1 = p1;
end
```
Command
```cmd
dotnet linq2db scaffold -p Firebird -c "<connectionstring>" --objects stored-procedure
```
Generated method

```c#
public static async Task<Proc1Results> Proc1Async(this Acrdb dataConnection, int? p1, int? v1, CancellationToken cancellationToken = default)
{
	var parameters = new []
	{
		new DataParameter("P1", p1, DataType.Int32)
		{
			Size = 4
		},
		new DataParameter("V1", null, DataType.Int32)
		{
			Direction = ParameterDirection.Output,
			Size = 4
		}
	};
	var result = await dataConnection.ExecuteProcAsync("PROC1", cancellationToken, parameters);
	return new Proc1Results()
	{
		Result = result,
		V1 = Converter.ChangeTypeTo<int?>(parameters[1].Value)
	};
}
```
Parameter v1 in Proc1Async is redundant.

### Environment details
linq2db.cli version:  5.4.1, 6.0.0-preview.1
Database (with version): Firebird 3.0 
Operating system: Windows 11
.NET Version: .NET 8

**Comment by SicJG** [comment]
There seems to be a related issue
I have a MsSql Server Database with following procedure:
```sql
create procedure dbo.TestOutputForLinqToDb
    @returnResult bit, 
    @data varchar(max) = null output
as begin
    set nocount on;  
    set xact_abort on;
	
    set @data = 'test';

    select @data as [Data]  
        where @returnResult = 1;
  
    return iif( @returnResult =  1, 0/*success*/, 1/*fail*/);  
end;
```
Scaffolding this procedure with `dotnet-linq2db scaffold -o PATH -p SqlServer -c CONNECTION_STRING --mssql-enable-return-value-parameter true --objects stored-procedure --include-stored-procedures TestOutputForLinqToDb` generates following 
functions:
 ```charp
public static int TestOutputForLinqToDb(this Maindb dataConnection, bool? returnResult, ref string? data, out int @return)
{
	var parameters = new []
	{
		new DataParameter("@returnResult", returnResult, DataType.Boolean),
		new DataParameter("@data", data, DataType.VarChar)
		{
			Direction = ParameterDirection.InputOutput,
			Size = -1
		},
		new DataParameter("@return", null, DataType.Int32)
		{
			Direction = ParameterDirection.Output,
			Size = 0,
			Precision = 0,
			Scale = 0
		}
	};
	var ret = dataConnection.ExecuteProc("[TestOutputForLinqToDb]", parameters);
	data = Converter.ChangeTypeTo<string?>(parameters[1].Value);
	@return = Converter.ChangeTypeTo<int>(parameters[2].Value);
	return ret;
}

public static async Task<TestOutputForLinqToDbResults> TestOutputForLinqToDbAsync(this Maindb dataConnection, bool? returnResult, string? data, int @return, CancellationToken cancellationToken = default)
{
	var parameters = new []
	{
		new DataParameter("@returnResult", returnResult, DataType.Boolean),
		new DataParameter("@data", data, DataType.VarChar)
		{
			Direction = ParameterDirection.InputOutput,
			Size = -1
		},
		new DataParameter("@return", null, DataType.Int32)
		{
			Direction = ParameterDirection.Output,
			Size = 0,
			Precision = 0,
			Scale = 0
		}
	};
	var result = await dataConnection.ExecuteProcAsync("[TestOutputForLinqToDb]", cancellationToken, parameters);
	return new TestOutputForLinqToDbResults()
	{
		Result = result,
		Data = Converter.ChangeTypeTo<string?>(parameters[1].Value),
		Return = Converter.ChangeTypeTo<int>(parameters[2].Value)
	};
}

public class TestOutputForLinqToDbResults
{
	public int     Result { get; set; }
	public string? Data   { get; set; }
	public int     Return { get; set; }
}
```
If i execute any of them, i will get runtime exception. Example of exception in case of execution of the 2nd:
```
Microsoft.Data.SqlClient.SqlException (0x80131904): Procedure or function TestOutputForLinqToDb has too many arguments specified.
   at Microsoft.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at Microsoft.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, SqlCommand command, Boolean callerHasConnectionLock, Boolean asyncClose)
   at Microsoft.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at Microsoft.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption, Boolean shouldCacheForAlwaysEncrypted)
   at Microsoft.Data.SqlClient.SqlCommand.CompleteAsyncExecuteReader(Boolean isInternal, Boolean forDescribeParameterEncryption)
   at Microsoft.Data.SqlClient.SqlCommand.InternalEndExecuteNonQuery(IAsyncResult asyncResult, Boolean isInternal, String endMethod)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryInternal(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.EndExecuteNonQueryAsync(IAsyncResult asyncResult)
   at Microsoft.Data.SqlClient.SqlCommand.<>c.<InternalExecuteNonQueryAsync>b__193_1(IAsyncResult asyncResult)
   at System.Threading.Tasks.TaskFactory`1.FromAsyncCoreLogic(IAsyncResult iar, Func`2 endFunction, Action`1 endAction, Task`1 promise, Boolean requiresSynchronization)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteNonQueryAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryDataAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteNonQueryDataAsync(CancellationToken cancellationToken)
   at LinqToDB.Data.CommandInfo.ExecuteAsync(CancellationToken cancellationToken)
```

The problem is with `@return` param's Direction. It should be `ParameterDirection.ReturnValue` instead of `ParameterDirection.Output`

### Environment details
linq2db.cli version: 5.4.1
Database (with version): MsSql Server 2022 (16.0.4195.2)
Operating system: Window 10
.NET Version: .NET 8
