### ISSUE TITLE
QueryMultipleAsync throws Exception, and seems to be broken entirely

### ISSUE THREAD

**Issue by Usaga** [linq2db/linq2db#4728]
### Describe your issue

`QueryMultipleAsync` throws Exception, and seems to be broken entirely.  `QueryMultiple` works fine.

```
Exception message: ''System.Threading.Tasks.Task' does not contain a definition for 'Result''

Stack trace:
Microsoft.CSharp.RuntimeBinder.RuntimeBinderException
  HResult=0x80131500
  Message='System.Threading.Tasks.Task' does not contain a definition for 'Result'
  Source=System.Linq.Expressions
  StackTrace:
   at System.Dynamic.UpdateDelegates.UpdateAndExecute1[T0,TRet](CallSite site, T0 arg0)
   at LinqToDB.Data.CommandInfo.<ReadMultipleResultSetsAsync>d__50`1.MoveNext()
   at LinqToDB.Data.CommandInfo.<QueryMultipleAsync>d__33`1.MoveNext()
   at LinqToDB.Data.CommandInfo.<QueryMultipleAsync>d__33`1.MoveNext()
   at LinqToDB.Data.CommandInfo.<QueryMultipleAsync>d__33`1.MoveNext()
   at Program.<<Main>$>d__0.MoveNext() in ...Program.cs:line 12
   at Program.<Main>(String[] args)
```

### Steps to reproduce

```c#
using LinqToDB;
using LinqToDB.Data;
using LinqToDB.DataProvider.SqlServer;
using LinqToDB.Mapping;

var context = new DataConnection(opt => opt
                .UseSqlServer(
                    "Data Source=localhost;Initial Catalog=master;User Id=sa;Password=!Qazxsw2",
                    SqlServerVersion.v2022,
                    SqlServerProvider.SystemDataSqlClient));

var dataset = await context.QueryMultipleAsync<MultipleResultDeletion>(
        "select 1, 1 from INFORMATION_SCHEMA.TABLES where 1 = 0;" +
        "select 1, 1, 1 from INFORMATION_SCHEMA.TABLES where 1 = 0;" +
        "select 1, 1 from INFORMATION_SCHEMA.TABLES where 1 = 0;");

internal sealed class ToDeleteId
{
    public int CaseLogId { get; set; }
    public string CaseNbr { get; set; }
}

internal sealed class NotDeletedId
{
    public int CaseLogId { get; set; }
    public string CaseNbr { get; set; }
    public int CrimeCodesId { get; set; }
}

internal sealed class DeletedId
{
    public int CaseLogId { get; set; }
    public string CaseNbr { get; set; }
}

internal sealed class MultipleResultDeletion
{
    [ResultSetIndex(0)] public ToDeleteId[] ToDeleteId { get; set; }
    [ResultSetIndex(1)] public NotDeletedId[] NotDeletedId { get; set; }
    [ResultSetIndex(2)] public DeletedId[] DeletedId { get; set; }
}

```

### Environment details

`Linq To DB` version: 5.4.1

Database (with version): SQL Server 2022

ADO.NET Provider: System.Data.SqlClient, 4.9.0

Operating system: Windows 10 and 11

.NET Version: 4.8.1, net8.0

**Comment by MaceWindu** [comment]
I would say error says lies, because object is `Task<T>` and has `Result` property. Anyway, we need to "fix" it
