### ISSUE TITLE
 the generated SQL is incorrect

### ISSUE THREAD

**Issue by AppChenX** [linq2db/linq2db#4751]
### Describe your issue

When using a subquery, if the parameter value is empty, the generated SQL is incorrect, resulting in an extra WHERE clause. Is this a bug?

log.

```
[2024-12-23 11:48:12:122 LinqToDB.Data.DataConnection [Information] BeforeExecute
--  Oracle.11.Managed Oracle11 (asynchronously)
DECLARE @take Int32
SET     @take = 200
DECLARE @skip Int32
SET     @skip = 0

SELECT
	t3.Id,
	t3.CarNo 
	t3.FirstVal,
	t3.TelNo,
	t3.RuleNo,
	t3.RuleName,
	t3.RuleType,
	t3.RuleVal,
	t3.RuleUnit  
FROM
	(
		SELECT
			t2.Id,
			t2.CarNo, 
			t2.FirstVal,
			t2.TelNo,
			t2.RuleNo,
			t2.RuleName,
			t2.RuleType,
			t2.RuleVal,
			t2.RuleUnit 
			ROWNUM as RN
		FROM
			(
				SELECT
					x_3.Id,
					x_3.CarNo, 
					x_3.FirstVal,
					x_3.TelNo,
					x_3.RuleNo,
					x_3.RuleName,
					x_3.RuleType,
					x_3.RuleVal,
					x_3.RuleUnit 
				FROM
					(
						SELECT
							t1.CAR_NO as CarNo, 
							x_2.FIRST_VAL as FirstVal,
							x.TEL_NO as TelNo,
							x.RULE_NO as RuleNo,
							x_1.RULE_NAME as RuleName,
							x_1.RULE_TYPE as RuleType,
							x_1.RULE_VAL as RuleVal,
							x_1.RULE_UNIT as RuleUnit 
							 
						FROM
							TDM100 t1
								LEFT JOIN TRP004 x ON x.CAR_NO = t1.CAR_NO
								LEFT JOIN TRP003 x_1 ON x_1.RULE_NO = x.RULE_NO
								LEFT JOIN TRP0041 x_2 ON x_2.CAR_NO = t1.CAR_NO
						ORDER BY
							t1.CAR_NO
					) x_3
				WHERE
					()
			) t2
		WHERE
			ROWNUM <= :take
	) t3
WHERE
	t3.RN > :skip
[2024-12-23 11:48:12:787 LinqToDB.Data.DataConnection [Error] Error
Exception: Oracle.ManagedDataAccess.Client.OracleException
Message  : ORA-00936: missing expression
https://docs.oracle.com/error-help/db/ora-00936/
   at Oracle.ManagedDataAccess.Client.OracleCommand.<>c.<ExecuteDbDataReaderAsync>b__218_0(Task`1 result)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.<>c.<.cctor>b__277_0(Object obj)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location ---
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location ---
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
   at LinqToDB.Data.DataConnection.ExecuteDataReaderAsync(CommandBehavior commandBehavior, CancellationToken cancellationToken)
```

### Steps to reproduce 

code sinpe

```c#
 .....
  var query = (from t1 in dbContext.GetTable<Tdm100>()
                from t2 in dbContext.GetTable<Trp004>().LeftJoin(x => x.CarNo == t1.CarNo)
                from t3 in dbContext.GetTable<Trp003>().LeftJoin(x => x.RuleNo == t2.RuleNo)
                from t4 in dbContext.GetTable<Trp0041>().LeftJoin(x => x.CarNo == t1.CarNo)
                 
                 orderby t1.CarNo
                select new Rp002_R_GetPageList_Dto
                {
                    Id=t1.Id,
                    CarNo = t1.CarNo, 
                    FirstVal = t4.FirstVal,
                    TelNo = t2.TelNo,
                    RuleNo = t2.RuleNo,
                    RuleName = t3.RuleName,
                    RuleType = t3.RuleType,
                    RuleVal = t3.RuleVal,
                    RuleUnit = t3.RuleUnit  
                });

             IQueryable<Rp002_R_GetPageList_Dto> query2;


             if (string.IsNullOrWhiteSpace(input.HasRule))
             {
                 query2= (from t in query.AsSubQuery() select t);
             }
             else
             {
                 if (input.HasRule == "Y")
                 {
                     query2= (from t in query.AsSubQuery() where t.RuleNo!=null select t);
                 }
                 else
                 {
                     query2= (from t in query.AsSubQuery() where t.RuleNo==null select t);
                 }
             }
             var query3= query2.Where(x=> x.CarNo.Contains(input.CarNo)&&x.CarBrand.Contains(input.CarBrand));
              ###query3 sql is not correct,because input.CarNo &&CarBrand is null
               
               
             
             var items = await query3.PageBy(input.SkipCount, input.MaxResultCount).ToListAsync();
             var totalCount = query3.LongCount();
```

### Environment details

`Linq To DB` version: 5.4.1  

ADO.NET Provider (with version): oracle.manageddataaccess.core.23.5.0 

.NET Version: .NET5.0

**Comment by MaceWindu** [comment]
`CarBrand` column is not defined in your projection

**Comment by MaceWindu** [comment]
In next release (v6) we are detecting such invalid query fragments and generate error:
```
LinqToDB.LinqToDBException : The LINQ expression 'x.CarBrand.Contains(<>c__DisplayClass58_0.carBrand)' could not be converted to SQL.
```

**Comment by MaceWindu** [comment]
You will need to provide complete reproducible example, as your code with missing parts restored works:

```sql
SELECT
	t3."Id",
	t3."CarNo",
	t3."CarSelf",
	t3."CarBrand",
	t3."RateWgt",
	t3."MastLeve",
	t3."ForkPole",
	t3."FirstVal",
	t3."TelNo",
	t3."RuleNo",
	t3."RuleName",
	t3."RuleType",
	t3."RuleVal",
	t3."RuleUnit",
	t3."RecCreator",
	t3."RecCreateTime",
	t3."RecRevisor",
	t3."RecReviseTime"
FROM
	(
		SELECT
			t2."Id",
			t2."CarNo",
			t2."CarSelf",
			t2."CarBrand",
			t2."RateWgt",
			t2."MastLeve",
			t2."ForkPole",
			t2."FirstVal",
			t2."TelNo",
			t2."RuleNo",
			t2."RuleName",
			t2."RuleType",
			t2."RuleVal",
			t2."RuleUnit",
			t2."RecCreator",
			t2."RecCreateTime",
			t2."RecRevisor",
			t2."RecReviseTime",
			ROWNUM as RN
		FROM
			(
				SELECT
					t."Id",
					t."CarNo",
					t."CarSelf",
					t."CarBrand",
					t."RateWgt",
					t."MastLeve",
					t."ForkPole",
					t."FirstVal",
					t."TelNo",
					t."RuleNo",
					t."RuleName",
					t."RuleType",
					t."RuleVal",
					t."RuleUnit",
					t."RecCreator",
					t."RecCreateTime",
					t."RecRevisor",
					t."RecReviseTime"
				FROM
					(
						SELECT
							x."RuleNo",
							t1."CarNo",
							t1."CarBrand",
							t1."Id",
							t1."CarSelf",
							t1."RateWgt",
							t1."MastLeve",
							t1."ForkPole",
							x_2."FirstVal",
							x."TelNo",
							x_1."RuleName",
							x_1."RuleType",
							x_1."RuleVal",
							x_1."RuleUnit",
							x."RecCreator",
							x."RecCreateTime",
							x."RecRevisor",
							x."RecReviseTime"
						FROM
							"Tdm100" t1
								LEFT JOIN "Trp004" x ON x."CarNo" = t1."CarNo"
								LEFT JOIN "Trp003" x_1 ON x_1."RuleNo" = x."RuleNo"
								LEFT JOIN "Trp0041" x_2 ON x_2."CarNo" = t1."CarNo"
						ORDER BY
							t1."CarNo"
					) t
				WHERE
					t."RuleNo" IS NOT NULL AND t."CarNo" LIKE :carNo ESCAPE '~' AND
					t."CarBrand" LIKE :carBrand ESCAPE '~'
			) t2
		WHERE
			ROWNUM <= :take
	) t3
WHERE
	t3.RN > :skip
````

**Comment by MaceWindu** [comment]
Thanks! Reproduced and can confirm it was already fixed in upcoming v6 release
