### ISSUE TITLE
ArgumentOutOfRangeException after using UNION

### ISSUE THREAD

**Issue by spencode** [linq2db/linq2db#508]
I use Firebird 2.5 database.

Table SomeXUserGroups:
```sql
CREATE TABLE SOME_X_USERGROUPS (
    USERGROUPID        INTEGER NOT NULL,
    SOMEID         VARCHAR(256) NOT NULL
);
```
USERGROUPID and SOMEID is foreign keys.

Table UserGroupMember:
```sql
CREATE TABLE USERGROUPMEMBERS (
    USERGROUPID  INTEGER NOT NULL,
    USERID       INTEGER NOT NULL
);
```
USERGROUPID and USERID is foreign keys.

Table SomeXUser:
```sql
CREATE TABLE SOME_X_USERS (
    USERID             INTEGER NOT NULL,
    SOMEID         VARCHAR(256) NOT NULL
);
```
USERID and SOMEID is foreign keys.

Parameter SomeNumber  for example = "333".

I have linq query like: 
```cs
var query = from u in (from rlsxuge in dataContext.GetEntityService<SomeXUserGroups>().List
                                join ugme in dataContext.GetEntityService<UserGroupMember>().List on
                                sxuge.UserGroupId equals ugme.UserGroupId
                                where sxuge.SomeId == SomeNumber
                                select ugme.UserId)
                            .Union(from sxue in dataContext.GetEntityService<SomeXUser>().List
                                where sxue.SomeId == SomeNumber
                                select sxue.UserId).ToList();
```

After executing code:

```
System.ArgumentOutOfRangeException: Index was out of range. Must be non-negative and less than the size of the collection.
Parameter name: index
   at System.ThrowHelper.ThrowArgumentOutOfRangeException(ExceptionArgument argument, ExceptionResource resource)
   at System.Collections.Generic.List`1.get_Item(Int32 index)
   at LinqToDB.SqlQuery.SelectQuery.<>c__DisplayClassf.<SetAliases>b__e(IQueryElement expr)
   at LinqToDB.SqlQuery.QueryVisitor.Visit2(IQueryElement element)
   at LinqToDB.SqlQuery.QueryVisitor.Visit2(IQueryElement element)
   at LinqToDB.SqlQuery.QueryVisitor.VisitAll(IQueryElement element, Action`1 action)
   at LinqToDB.SqlQuery.SelectQuery.SetAliases()
   at LinqToDB.SqlQuery.SelectQueryOptimizer.FinalizeAndValidate(Boolean isApplySupported, Boolean optimizeColumns)
   at LinqToDB.SqlProvider.BasicSqlOptimizer.Finalize(SelectQuery selectQuery)
   at LinqToDB.DataProvider.Firebird.FirebirdSqlOptimizer.Finalize(SelectQuery selectQuery)
   at LinqToDB.Linq.Query`1.FinalizeQuery()
   at LinqToDB.Linq.Query`1.GetQuery()
   at LinqToDB.Linq.Query`1.SetQuery(Expression`1 expression)
   at LinqToDB.Linq.Builder.ConcatUnionBuilder.UnionContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.GetQuery(IDataContextInfo dataContextInfo, Expression expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.Execute(IDataContextInfo dataContextInfo, Expression expression)
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
```

**Comment by ili** [comment]
Hello,

what hides under `GetEntityService<SomeXUserGroups>().List`

**Comment by spencode** [comment]
GetEntityService<T>().List
`public IQueryable<T> List
        {
            get { return _db.GetTable<T>(); }
        }`

**Comment by sdanyliv** [comment]
@spencode, maybe it is not related to this issue. It does mean that for every entity you have db connection? Or it is resolved by IoC container? 
Just for clarification, you HAVE TO dispose connections for returning them to the connection pool.
