### ISSUE TITLE
Linq2db, Firebird2.5.1, T4

### ISSUE THREAD

**Issue by jkarakiz** [linq2db/linq2db#518]
Hello Ilya,
thank you for your reply. I read issue#505 added assemblies for linq2db.dll and FirebirdSql.Data.FirebirdClient.dll on top of Copy.tt.txt as suggested.
Now code generation starts but I get the error:
```
Error	1	Running transformation: System.Collections.Generic.KeyNotFoundException: The given key was not present in the dictionary.
   at System.Collections.Generic.Dictionary`2.get_Item(TKey key)
   at Microsoft.VisualStudio.TextTemplating43803B678D5D0FDACFAFD976FE4545D2.GeneratedTextTransformation.<>c__DisplayClassba.<LoadServerMetadata>b__a0(ColumnSchema c) in c:\Users\Iakovos\Documents\Visual Studio 2010\Projects\Wpf\WpfRestaurant1\HospitalityModel_T4\LinqToDB.Templates\DataModel.ttinclude:line 142
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplating43803B678D5D0FDACFAFD976FE4545D2.GeneratedTextTransformation.<LoadServerMetadata>b__9f(<>f__AnonymousType4`2 <>h__TransparentIdentifier8b) in c:\Users\Iakovos\Documents\Visual Studio 2010\Projects\Wpf\WpfRestaurant1\HospitalityModel_T4\LinqToDB.Templates\DataModel.ttinclude:line 133
   at System.Linq.Enumerable.<>c__DisplayClass7_0`3.<CombineSelectors>b__0(TSource x)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplating43803B678D5D0FDACFAFD976FE4545D2.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in c:\Users\Iakovos\Documents\Visual Studio 2010\Projects\Wpf\WpfRestaurant1\HospitalityModel_T4\LinqToDB.Templates\DataModel.ttinclude:line 128
   at Microsoft.VisualStudio.TextTemplating43803B678D5D0FDACFAFD976FE4545D2.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in c:\Users\Iakovos\Documents\Visual Studio 2010\Projects\Wpf\WpfRestaurant1\HospitalityModel_T4\LinqToDB.Templates\DataModel.ttinclude:line 310
   at Microsoft.VisualStudio.TextTemplating43803B678D5D0FDACFAFD976FE4545D2.GeneratedTextTransformation.LoadFirebirdMetadata(String connectionString) in c:\Users\Iakovos\Documents\Visual Studio 2010\Projects\Wpf\WpfRestaurant1\HospitalityModel_T4\LinqToDB.Templates\LinqToDB.Firebird.ttinclude:line 57
   at Microsoft.VisualStudio.TextTemplating43803B678D5D0FDACFAFD976FE4545D2.GeneratedTextTransformation.TransformText() in c:\Users\Iakovos\Documents\Visual Studio 2010\Projects\Wpf\WpfRestaurant1\HospitalityModel_T4\Hospitality.tt.txt:line 46
   at Microsoft.VisualStudio.TextTemplating.TransformationRunner.RunTransformation(TemplateProcessingSession session, String source, ITextTemplatingEngineHost host, String& result)		1	1	
```
I read DataModel.ttinclude and the line 142 is

OtherColumns    = k.OtherColumns.Select(c => otherTable.Columns[c.ColumnName]).ToList(),

Tested with Firebird 2.5.1.26351, VS2010 (.NET40) and VS2015 (.NET452)
Strange is that VS2010 downloaded linq2db.1.7.5 but VS2015 downloaded linq2db.1.0.7.1 however both version stop at line 142

Is there anything I can do to fix this?
Thank you for your help

**Comment by ili** [comment]
Can you provide database creating script?

**Comment by jkarakiz** [comment]
Hi Ilya,
I have create a database from scratch, used VS2015, linq2db 1.7.5, linq2db.Firebird.1.0.7.5, added linq2db.dll and FirebirdSql.Data.FirebirdClient.dll manually and it generated model successfully. So it must have been something wrong with my database. I think you can close the issue.
Thank you for your help.

**Comment by ili** [comment]
Super, thanks!
