### ISSUE TITLE
Transformation Exception 'DateTime is not a member of type NpgsqlTypes.NpgsqlDateTime'

### ISSUE THREAD

**Issue by Kempe** [linq2db/linq2db#541]
Everytime when transforming PostgreSQL..tt I got an exception -see below- saying that DateTime is not a member of type NpgsqlTypes.NpgsqlDateTime. I'm using Postgres 9.6 (Database), npgsql.dll (v3.2.0) and linq2db (v1.7.5).
By the way, do I still need to add 

```
<#@ assembly name="$(SolutionDir)packages\linq2db.1.7.5\lib\net45\linq2db.dll"        #>
<#@ assembly name="$(SolutionDir)packages\Npgsql.3.2.0\lib\net451\Npgsql.dll"         #>
```
to the header of PostgreSQL.tt in order to successfully transform??? Version 1.7.3 is working without any 
problems.

Thanks in advance.

Cheers.

```
Severity	Code	Description	Project	File	Line	Suppression State
Error		Running transformation: System.ArgumentException: 'DateTime' is not a member of type 'NpgsqlTypes.NpgsqlDateTime'
   at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider.OnConnectionTypeCreated(Type connectionType) in c:\projects\linq2db\Source\DataProvider\PostgreSQL\PostgreSQLDataProvider.cs:line 166
   at LinqToDB.DataProvider.DynamicDataProviderBase.GetConnectionType() in c:\projects\linq2db\Source\DataProvider\DynamicDataProviderBase.cs:line 40
   at LinqToDB.DataProvider.DynamicDataProviderBase.CreateConnectionInternal(String connectionString) in c:\projects\linq2db\Source\DataProvider\DynamicDataProviderBase.cs:line 63
   at LinqToDB.DataProvider.DataProviderBase.CreateConnection(String connectionString) in c:\projects\linq2db\Source\DataProvider\DataProviderBase.cs:line 76
   at LinqToDB.Data.DataConnection.get_Connection() in c:\projects\linq2db\Source\Data\DataConnection.cs:line 520
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options) in c:\projects\linq2db\Source\SchemaProvider\SchemaProviderBase.cs:line 49
   at Microsoft.VisualStudio.TextTemplatingC4A9431148BBB115F7FB8192247A57F2BDFBEDB28815ECC4462D4D91C10D5DEE014A4AA4D0E0D1691F6567EED2BD8370B133C78A3DF343E490060B87D89747A4.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in F:\Temp\linq2dbTest\linq2dbTest\linq2dbTest\LinqToDB.Templates\DataModel.ttinclude:line 56
   at Microsoft.VisualStudio.TextTemplatingC4A9431148BBB115F7FB8192247A57F2BDFBEDB28815ECC4462D4D91C10D5DEE014A4AA4D0E0D1691F6567EED2BD8370B133C78A3DF343E490060B87D89747A4.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in F:\Temp\linq2dbTest\linq2dbTest\linq2dbTest\LinqToDB.Templates\DataModel.ttinclude:line 310
   at Microsoft.VisualStudio.TextTemplatingC4A9431148BBB115F7FB8192247A57F2BDFBEDB28815ECC4462D4D91C10D5DEE014A4AA4D0E0D1691F6567EED2BD8370B133C78A3DF343E490060B87D89747A4.GeneratedTextTransformation.LoadPostgreSQLMetadata(String connectionString) in F:\Temp\linq2dbTest\linq2dbTest\linq2dbTest\LinqToDB.Templates\LinqToDB.PostgreSQL.ttinclude:line 49
   at Microsoft.VisualStudio.TextTemplatingC4A9431148BBB115F7FB8192247A57F2BDFBEDB28815ECC4462D4D91C10D5DEE014A4AA4D0E0D1691F6567EED2BD8370B133C78A3DF343E490060B87D89747A4.GeneratedTextTransformation.TransformText() in F:\Temp\linq2dbTest\linq2dbTest\linq2dbTest\DBModel\Post.tt:line 42		c:\projects\linq2db\Source\DataProvider\PostgreSQL\PostgreSQLDataProvider.cs	166	
```

**Comment by ili** [comment]
1) we'll fix issue with assembly linking in next release.
2) DateTime issue occurs on any datetime field?

**Comment by Kempe** [comment]
Sorry, I can't tell you cause this exception appears right at the beginning of the transformation process and stops with only this information.

**Comment by sdanyliv** [comment]
@ili , 
In version Npgsql 3.2.0, they have changed in class NpgsqlDateTime property DateTime to function ToDateTime().
That's why it is failed.

**Comment by ili** [comment]
@sdanyliv thanks!

But now it is unclear what to do... either support only latest Npgsql or try to support both...

**Comment by sdanyliv** [comment]
I think, It's not time critical to support both variants.

**Comment by jogibear9988** [comment]
I think we should support both! maybe autodetect dll version or set a config

**Comment by sdanyliv** [comment]
@jogibear9988, we can easily check via reflection that property no more exits. It's not a problem.

**Comment by ili** [comment]
PR somebody? :))

**Comment by sdanyliv** [comment]
I'll prepare

**Comment by ili** [comment]
fixed, thanks to @sdanyliv :)
