### ISSUE TITLE
Error generating code with postgresql 9.3.1 and latest 1.7.5 version

### ISSUE THREAD

**Issue by brunommarques** [linq2db/linq2db#554]
Severity	Code	Description	Project	File	Line	Source	Suppression State
Error		Running transformation: System.ArgumentException: 'DateTime' is not a member of type 'NpgsqlTypes.NpgsqlDateTime'
   at System.Linq.Expressions.Expression.PropertyOrField(Expression expression, String propertyOrFieldName)
   at LinqToDB.DataProvider.PostgreSQL.PostgreSQLDataProvider.OnConnectionTypeCreated(Type connectionType)
   at LinqToDB.DataProvider.DynamicDataProviderBase.GetConnectionType()
   at LinqToDB.DataProvider.DynamicDataProviderBase.CreateConnectionInternal(String connectionString)
   at LinqToDB.DataProvider.DataProviderBase.CreateConnection(String connectionString)
   at LinqToDB.Data.DataConnection.get_Connection()
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplating943ACB2BAB3394CE97B705807B1617B2AC7BF6161A646F6078A1402A21CEDAABE1B11D4D00BA24A738D2F635AB0C9A2145C1D550D1369C819F29AAB60CAEBD25.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in C:\gitrepos\teste\ProcessCreator\EFDBAccess\LinqToDB.Templates\DataModel.ttinclude:line 56
   at

**Comment by sdanyliv** [comment]
Already fixed in #545

**Comment by brunommarques** [comment]
Great! would it be possible to release this fix in nuget pkg 1.7.6 please?

**Comment by ili** [comment]
We'll release after closing few open issues.
And you always can obtain latest build from MyGet https://github.com/linq2db/linq2db/blob/master/README.md#feeds

**Comment by jogibear9988** [comment]
Wouldn't it better to release mor often? I think fot example the multithread bug in mapping could happen at more users systems

**Comment by ili** [comment]
Yes, you are right
If #550 and #544 would not be closed this week, we'll release without em
