### ISSUE TITLE
MySql: SqlNullValueException Generating Models

### ISSUE THREAD

**Issue by Nesse** [linq2db/linq2db#558]
Generating my datamodels is firing an SqlNullValueException when getting my schema (magento). Does anyone know how to resolve this?

**CODE**:
```C#
    var connectionString = "Server=localhost;Port=3306;Database=magento;Uid=root;Pwd=1234;charset=utf8;ConvertZeroDatetime=True;AllowZeroDatetime=True;";

     // not working
    var sp = dataConnection.DataProvider.GetSchemaProvider();
    var db = sp.GetSchema(dataConnection);

    // working 
    var connection = new MySqlConnection(connectionString);
    var db2 = connection.GetSchema();

    // working - extra
    var command = connection.CreateCommand();
    command.CommandText = "SHOW TABLES;";

    var reader = command.ExecuteReader();

    while (reader.Read())
    {
        var row = "";
        for (var i = 0; i < reader.FieldCount; i++)
            row += reader.GetValue(i).ToString() + ", ";
        Console.WriteLine(row);
    }
    connection.Close();
```

**ERROR**:
`Running transformation: System.Data.SqlTypes.SqlNullValueException: Data is Null. This method or property cannot be called on Null values.
   at MySql.Data.MySqlClient.MySqlDataReader.GetFieldValue(Int32 index, Boolean checkNull)
   at MySql.Data.MySqlClient.MySqlDataReader.GetString(Int32 i)
   at MySql.Data.MySqlClient.MySqlDataReader.GetString(String column)
   at MySql.Data.MySqlClient.SchemaProvider.GetIndexColumns(String[] restrictions)
   at MySql.Data.MySqlClient.SchemaProvider.GetSchemaInternal(String collection, String[] restrictions)
   at MySql.Data.MySqlClient.ISSchemaProvider.GetSchemaInternal(String collection, String[] restrictions)
   at MySql.Data.MySqlClient.SchemaProvider.GetSchema(String collection, String[] restrictions)
   at MySql.Data.MySqlClient.MySqlConnection.GetSchema(String collectionName, String[] restrictionValues)
   at MySql.Data.MySqlClient.MySqlConnection.GetSchema(String collectionName)
   at LinqToDB.DataProvider.MySql.MySqlSchemaProvider.GetPrimaryKeys(DataConnection dataConnection)
   at LinqToDB.SchemaProvider.SchemaProviderBase.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplatingB41FF171F1D676BBB07B6DF817D0F73ED0CBC95FB4CC7ECDC5E60FA2EE25F117EC5BF9EE7E5389A250AC2F106B5484E253B1CA37CEE331162BC4836EB5843F12.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in C:\Users\Wesley.PACOLIBA\Documents\## Code\ERP\intershoe\TestMagento - LinqToDb\LinqToDB.Templates\DataModel.ttinclude:line 56
   at Microsoft.VisualStudio.TextTemplatingB41FF171F1D676BBB07B6DF817D0F73ED0CBC95FB4CC7ECDC5E60FA2EE25F117EC5BF9EE7E5389A250AC2F106B5484E253B1CA37CEE331162BC4836EB5843F12.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in C:\Users\Wesley.PACOLIBA\Documents\## Code\ERP\intershoe\TestMagento - LinqToDb\LinqToDB.Templates\DataModel.ttinclude:line 310
   at Microsoft.VisualStudio.TextTemplatingB41FF171F1D676BBB07B6DF817D0F73ED0CBC95FB4CC7ECDC5E60FA2EE25F117EC5BF9EE7E5389A250AC2F106B5484E253B1CA37CEE331162BC4836EB5843F12.GeneratedTextTransformation.LoadMySqlMetadata(String server, String database, String uid, String password, Int32 port) in C:\Users\Wesley.PACOLIBA\Documents\## Code\ERP\intershoe\TestMagento - LinqToDb\LinqToDB.Templates\LinqToDB.MySql.ttinclude:line 28
   at Microsoft.VisualStudio.TextTemplatingB41FF171F1D676BBB07B6DF817D0F73ED0CBC95FB4CC7ECDC5E60FA2EE25F117EC5BF9EE7E5389A250AC2F106B5484E253B1CA37CEE331162BC4836EB5843F12.GeneratedTextTransformation.TransformText() in C:\Users\Wesley.PACOLIBA\Documents\## Code\ERP\intershoe\TestMagento - LinqToDb\DataModels\Magento.tt:line 38	TestMagento - LinqToDb	C:\Users\Wesley.PACOLIBA\Documents\## Code\ERP\intershoe\TestMagento - LinqToDb\LinqToDB.Templates\DataModel.ttinclude	56	
`

**Comment by sdanyliv** [comment]
Try to replace your working code with
```cs
var db2 = connection.GetSchema("IndexColumns");
```
which is more closer to what linq2db do.

https://dev.mysql.com/doc/connector-net/en/connector-net-programming-getschema.html
Currently i don't know what happen. Have you upgraded you MySQL Connector?

**Comment by Nesse** [comment]
Hi @sdanyliv. Thx for your fast response.

I've used your piece of code and this is also firing an error. (Magento database)

**Error**:
`System.NullReferenceException was unhandled
  HResult=-2147467261
  Message=The object reference not set to an instance of an object.
  Source=MySql.Data
  StackTrace:
       bij MySql.Data.MySqlClient.MySqlConnection.GetSchema(String collectionName, String[] restrictionValues)
       bij MySql.Data.MySqlClient.MySqlConnection.GetSchema(String collectionName)
       bij TestMagento.Program.Main(String[] args) in C:\Users\Wesley.PACOLIBA\Documents\## Code\ERP\intershoe\TestMagento - LinqToDb\Program.cs:regel 74
       bij System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
       bij System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
       bij Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
       bij System.Threading.ThreadHelper.ThreadStart_Context(Object state)
       bij System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
       bij System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
       bij System.Threading.ThreadHelper.ThreadStart()
  InnerException: `

I'm using version 6.7.9 of MySql.Data.

**Comment by sdanyliv** [comment]
Which collection names returns this call?
```cs
var db2 = connection.GetSchema();
```

**Comment by Nesse** [comment]
Is this the info you are looking for?

MetaDataCollections:

- MetaDataCollections
- DataSourceInformation
- DataTypes
- Restrictions
- ReservedWords
- Databases
- Tables
- Columns
- Users
- Foreign Keys
- IndexColumns
- Indexes
- Foreign Key Columns
- UDF
- Views
- ViewColumns
- Procedure Parameters
- Procedures
- Triggers

**Comment by sdanyliv** [comment]
Yes, looks like this version of MySQL Connector have bug. Try to upgrade to 6.8.8 or downgrade and report problem to their repository.
Also, theoretically, it can be problem with permissions...

**Comment by Nesse** [comment]
I've tried to upgrade or downgrade without succes. Same error is accuring on both occasions. Is there a workarround to create the models?

**Comment by sdanyliv** [comment]
It's a known bug
https://bugs.mysql.com/bug.php?id=75301

> **How to repeat:**
> Define a full text search index on any table and then run the following code

**Comment by Nesse** [comment]
Thx @sdanyliv for the superb help. Is there a way to only generate specific tables and exclude the full index tables?

**Comment by sdanyliv** [comment]
Try to ensure that your indexes have all the following fields NOT NULL. I's decompiled source of problematic method.
```cs
foreach (MySqlSchemaRow row in (IEnumerable<MySqlSchemaRow>) this.GetTables(restrictions1).Rows)
      {
        using (MySqlDataReader reader = new MySqlCommand(string.Format("SHOW INDEX FROM `{0}`.`{1}`", row["TABLE_SCHEMA"], row["TABLE_NAME"]), this.connection).ExecuteReader())
        {
          while (reader.Read())
          {
            string str1 = SchemaProvider.GetString(reader, reader.GetOrdinal("KEY_NAME"));
            string str2 = SchemaProvider.GetString(reader, reader.GetOrdinal("COLUMN_NAME"));
            if (restrictions == null || (restrictions.Length < 4 || restrictions[3] == null || !(str1 != restrictions[3])) && (restrictions.Length < 5 || restrictions[4] == null || !(str2 != restrictions[4])))
            {
              MySqlSchemaRow mySqlSchemaRow = schemaCollection.AddRow();
              mySqlSchemaRow["INDEX_CATALOG"] = (object) null;
              mySqlSchemaRow["INDEX_SCHEMA"] = row["TABLE_SCHEMA"];
              mySqlSchemaRow["INDEX_NAME"] = (object) str1;
              mySqlSchemaRow["TABLE_NAME"] = (object) SchemaProvider.GetString(reader, reader.GetOrdinal("TABLE"));
              mySqlSchemaRow["COLUMN_NAME"] = (object) str2;
              mySqlSchemaRow["ORDINAL_POSITION"] = reader.GetValue(reader.GetOrdinal("SEQ_IN_INDEX"));
              mySqlSchemaRow["SORT_ORDER"] = (object) reader.GetString("COLLATION");
            }
          }
        }
```
For example and probably it's a problem:
```cs
reader.GetString("COLLATION")
```

**Comment by Nesse** [comment]
Thx @sdanyliv. This is a great help. The "_tmp" tables from magento are having **NULL** in the Collation column. They also have another **index_type** called HASH. Could I exclude them using restrictions?

**Comment by sdanyliv** [comment]
I don't see easy way.
Better if you set collation for indexes/tables and report problem to oracle.
Also you can compile MySql.Data from sources and resolve problem
https://dev.mysql.com/downloads/connector/net/

**Comment by Nesse** [comment]
Thx @sdanyliv. Great help, and superb component.
