### ISSUE TITLE
T4 models, and duplicate column names

### ISSUE THREAD

**Issue by ghost** [linq2db/linq2db#6]
When something procedure exist like this:

``` sql
create procedure x_duplicate_column_names
as
begin
select 123 as id, 456 as id
end
go
```

Then T4 generation fails with:

```
Error   3   Running transformation: System.ArgumentException: An item with the same key has already been added.
   at System.ThrowHelper.ThrowArgumentException(ExceptionResource resource)
   at System.Collections.Generic.Dictionary`2.Insert(TKey key, TValue value, Boolean add)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.Enumerable.ToDictionary[TSource,TKey,TElement](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector)
   at Microsoft.VisualStudio.TextTemplating7606E008372CBD07E42BCB71F2E0930EAFAD676B6CB295DF3B48E4D99343F06D2126B620E6CB982286C5F3122455E1AC418527400FAA7DA54956DE6360AB3E5C.GeneratedTextTransformation.<>c__DisplayClass46.<LoadServerMetadata>b__3d(ProcedureSchema p) in d:\prj\!temp\Linq2DbPlayground\Linq2DbPlayground\LinqToDB.Templates\DataModel.ttinclude:line 138
   at System.Linq.Enumerable.WhereSelectListIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.VisualStudio.TextTemplating7606E008372CBD07E42BCB71F2E0930EAFAD676B6CB295DF3B48E4D99343F06D2126B620E6CB982286C5F3122455E1AC418527400FAA7DA54956DE6360AB3E5C.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in d:\prj\!temp\Linq2DbPlayground\Linq2DbPlayground\LinqToDB.Templates\DataModel.ttinclude:line 137
   at Microsoft.VisualStudio.TextTemplating7606E008372CBD07E42BCB71F2E0930EAFAD676B6CB295DF3B48E4D99343F06D2126B620E6CB982286C5F3122455E1AC418527400FAA7DA54956DE6360AB3E5C.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in d:\prj\!temp\Linq2DbPlayground\Linq2DbPlayground\LinqToDB.Templates\DataModel.ttinclude:line 218
   at Microsoft.VisualStudio.TextTemplating7606E008372CBD07E42BCB71F2E0930EAFAD676B6CB295DF3B48E4D99343F06D2126B620E6CB982286C5F3122455E1AC418527400FAA7DA54956DE6360AB3E5C.GeneratedTextTransformation.TransformText() in d:\prj\!temp\Linq2DbPlayground\Linq2DbPlayground\DataContext.tt:line 45  d:\prj\!temp\Linq2DbPlayground\Linq2DbPlayground\LinqToDB.Templates\DataModel.ttinclude 138 1   Linq2DbPlayground
```

It is looks like happens near-by (procedures selection):

``` c#
                        Columns  = p.ResultTable.Columns.ToDictionary(
                            c => c.ColumnName,
                            c => new Column
                            {
```

**Comment by mberickson** [comment]
I ran into the same problem with a table, no idea why a column in this table was being reported twice even though it exist only once. To fix it I adjusted the code above to the following:

				Columns                 = t.Columns
                    // Remove duplicate column names.
                    .Select((c, idx) => new { ColumnIndex = idx, Column = c })
                    .GroupBy(cx => cx.Column.ColumnName)
                    .Select(cxg => cxg.Where(cxw => cxw.ColumnIndex == cxg.Min(cxm => cxm.ColumnIndex)).First())
                    .OrderBy(cx => cx.ColumnIndex)
                    .Select(cx => cx.Column)
					.ToDictionary(
						c => c.ColumnName,
						c => new Column
						{
