### ISSUE TITLE
Failures in recently added tests

### ISSUE THREAD

**Issue by MaceWindu** [linq2db/linq2db#674]
Some of recently added tests fails on some providers.
For cases 2 and 3 looks like you only need to exclude failed providers. For test 1 I'm not sure.

1. Linq.SqlExtensionTests.DatePartMillisecond.DB2
```
Test Name:	Linq.SqlExtensionTests.DatePartMillisecond.DB2
Test FullName:	Tests.Linq.SqlExtensionTests.DatePartMillisecond("DB2")
Test Source:	C:\GitHub\linq2db\Tests\Linq\Linq\SqlExtensionTests.cs : line 392
Test Outcome:	Failed
Test Duration:	0:00:01,435

Result StackTrace:	
at Tests.TestBase.AreEqual[T](IEnumerable`1 expected, IEnumerable`1 result) in C:\GitHub\linq2db\Tests\Linq\TestBase.cs:line 1045
at Tests.Linq.SqlExtensionTests.DatePartMillisecond(String context) in C:\GitHub\linq2db\Tests\Linq\Linq\SqlExtensionTests.cs:line 394
Result Message:	
Expect Expected
- 100 --- 100000
- 500 --- 500000
- 90 --- 90000
- 90 --- 90000
- 90 --- 90000
- 90 --- 90000
- 90 --- 90000
- 90 --- 90000
- 90 --- 90000
- 90 --- 90000
  0 --- 0
- 90 --- 90000

  Expected: 0
  But was:  3

```

2. Linq.SubQueryTests.Contains1 and Linq.SubQueryTests.Contains2
Those tests fail for DB2 and MariaDB configurations.
```
Test Name:	Linq.SubQueryTests.Contains1.DB2
Test FullName:	Tests.Linq.SubQueryTests.Contains1("DB2")
Test Source:	C:\GitHub\linq2db\Tests\Linq\Linq\SubQueryTests.cs : line 216
Test Outcome:	Failed
Test Duration:	0:00:00,125

Result StackTrace:	
at IBM.Data.DB2.DB2Command.ExecuteReaderObject(CommandBehavior behavior, String method, DB2CursorType reqCursorType, Boolean abortOnOptValueChg, Boolean skipDeleted, Boolean isResultSet, Int32 maxRows, Boolean skipInitialValidation)
   at IBM.Data.DB2.DB2Command.ExecuteReaderObject(CommandBehavior behavior, String method)
   at IBM.Data.DB2.DB2Command.ExecuteReader(CommandBehavior behavior)
   at IBM.Data.DB2.DB2Command.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in C:\GitHub\linq2db\Source\Data\DataConnection.cs:line 831
   at LinqToDB.Data.DataConnection.ExecuteReader() in C:\GitHub\linq2db\Source\Data\DataConnection.cs:line 776
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.ExecuteReader(Object query) in C:\GitHub\linq2db\Source\Data\DataConnection.Linq.cs:line 273
   at LinqToDB.Linq.Query`1.<RunQuery>d__23.MoveNext() in C:\GitHub\linq2db\Source\Linq\Query.cs:line 371
   at LinqToDB.Linq.Query`1.<Map>d__46.MoveNext() in C:\GitHub\linq2db\Source\Linq\Query.cs:line 1196
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Tests.TestBase.AreEqual[T](IEnumerable`1 expected, IEnumerable`1 result) in C:\GitHub\linq2db\Tests\Linq\TestBase.cs:line 1024
   at Tests.Linq.SubQueryTests.Contains1(String context) in C:\GitHub\linq2db\Tests\Linq\Linq\SubQueryTests.cs:line 218
Result Message:	IBM.Data.DB2.DB2Exception : ERROR [42704] [IBM][DB2/NT64] SQL0204N  "t1.ParentID" is an undefined name.
```

3. Following tests also fail for specified providers
- UserIssue269Tests.TestDistinctSkip : DB2, MariaDB, Sql2000
UserIssue269Tests.TestSkip : DB2, MariaDB, Sql2000
UserIssue269Tests.TestSkipDistinct : DB2, MariaDB, Sql2000
UserIssue269Tests.TestTake : DB2, MariaDB
```
Test Name:	UserIssue269Tests.TestDistinctSkip.DB2
Test FullName:	Tests.UserTests.Issue269Tests.TestDistinctSkip("DB2")
Test Source:	C:\GitHub\linq2db\Tests\Linq\UserTests\Issue269Tests.cs : line 101
Test Outcome:	Failed
Test Duration:	0:00:00,015

Result StackTrace:	
at IBM.Data.DB2.DB2Command.ExecuteReaderObject(CommandBehavior behavior, String method, DB2CursorType reqCursorType, Boolean abortOnOptValueChg, Boolean skipDeleted, Boolean isResultSet, Int32 maxRows, Boolean skipInitialValidation)
   at IBM.Data.DB2.DB2Command.ExecuteReaderObject(CommandBehavior behavior, String method)
   at IBM.Data.DB2.DB2Command.ExecuteReader(CommandBehavior behavior)
   at IBM.Data.DB2.DB2Command.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in C:\GitHub\linq2db\Source\Data\DataConnection.cs:line 831
   at LinqToDB.Data.DataConnection.ExecuteReader() in C:\GitHub\linq2db\Source\Data\DataConnection.cs:line 776
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.ExecuteReader(Object query) in C:\GitHub\linq2db\Source\Data\DataConnection.Linq.cs:line 273
   at LinqToDB.Linq.Query`1.<RunQuery>d__23.MoveNext() in C:\GitHub\linq2db\Source\Linq\Query.cs:line 371
   at LinqToDB.Linq.Query`1.<Map>d__46.MoveNext() in C:\GitHub\linq2db\Source\Linq\Query.cs:line 1196
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Tests.TestBase.AreEqual[T](IEnumerable`1 expected, IEnumerable`1 result) in C:\GitHub\linq2db\Tests\Linq\TestBase.cs:line 1024
   at Tests.UserTests.Issue269Tests.TestDistinctSkip(String context) in C:\GitHub\linq2db\Tests\Linq\UserTests\Issue269Tests.cs:line 122
Result Message:	IBM.Data.DB2.DB2Exception : ERROR [42704] [IBM][DB2/NT64] SQL0204N  "t1.PersonID" is an undefined name.
```

```
Test Name:	UserIssue269Tests.TestDistinctSkip.SqlServer.2000
Test FullName:	Tests.UserTests.Issue269Tests.TestDistinctSkip("SqlServer.2000")
Test Source:	C:\GitHub\linq2db\Tests\Linq\UserTests\Issue269Tests.cs : line 101
Test Outcome:	Failed
Test Duration:	0:00:00,041

Result StackTrace:	
at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSqlBuilder(SelectQuery selectQuery, Int32 indent, Boolean skipAlias) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 114
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildPhysicalTable(ISqlTableSource table, String alias) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 988
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildTableName(TableSource ts, Boolean buildName, Boolean buildAlias) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 1003
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildFromClause() in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 966
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSelectQuery() in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 197
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql() in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 157
   at LinqToDB.SqlProvider.BasicSqlBuilder.AlternativeBuildSql(Boolean implementOrderBy, Action buildSql) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 2315
   at LinqToDB.DataProvider.SqlServer.SqlServerSqlBuilder.BuildSql() in C:\GitHub\linq2db\Source\DataProvider\SqlServer\SqlServerSqlBuilder.cs:line 29
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql(Int32 commandNumber, SelectQuery selectQuery, StringBuilder sb, Int32 indent, Boolean skipAlias) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 81
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSqlBuilder(SelectQuery selectQuery, Int32 indent, Boolean skipAlias) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 119
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildExpression(ISqlExpression expr, Boolean buildTableName, Boolean checkParentheses, String alias, Boolean& addAlias, Boolean throwExceptionIfTableNotFound) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 1906
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildExpression(ISqlExpression expr, Boolean buildTableName, Boolean checkParentheses, Boolean throwExceptionIfTableNotFound) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 2015
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildFunction(String name, ISqlExpression[] exprs) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 2130
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildFunction(SqlFunction func) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 2116
   at LinqToDB.DataProvider.SqlServer.SqlServer2000SqlBuilder.BuildFunction(SqlFunction func) in C:\GitHub\linq2db\Source\DataProvider\SqlServer\SqlServer2000SqlBuilder.cs:line 75
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildExpression(ISqlExpression expr, Boolean buildTableName, Boolean checkParentheses, String alias, Boolean& addAlias, Boolean throwExceptionIfTableNotFound) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 1961
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildExpression(Int32 parentPrecedence, ISqlExpression expr, String alias, Boolean& addAlias) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 2002
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildExpression(Int32 precedence, ISqlExpression expr) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 2021
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildPredicate(ISqlPredicate predicate) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 1466
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildPredicate(Int32 parentPrecedence, Int32 precedence, ISqlPredicate predicate) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 1776
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSearchCondition(SearchCondition condition) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 1354
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSearchCondition(Int32 parentPrecedence, SearchCondition condition) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 1365
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildWhereSearchCondition(SearchCondition condition) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 1322
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildWhereClause() in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 1122
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSelectQuery() in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 198
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql() in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 157
   at LinqToDB.SqlProvider.BasicSqlBuilder.AlternativeBuildSql(Boolean implementOrderBy, Action buildSql) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 2315
   at LinqToDB.DataProvider.SqlServer.SqlServerSqlBuilder.BuildSql() in C:\GitHub\linq2db\Source\DataProvider\SqlServer\SqlServerSqlBuilder.cs:line 29
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql(Int32 commandNumber, SelectQuery selectQuery, StringBuilder sb, Int32 indent, Boolean skipAlias) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 81
   at LinqToDB.SqlProvider.BasicSqlBuilder.BuildSql(Int32 commandNumber, SelectQuery selectQuery, StringBuilder sb) in C:\GitHub\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 69
   at LinqToDB.Data.DataConnection.GetCommand(IQueryContext query) in C:\GitHub\linq2db\Source\Data\DataConnection.Linq.cs:line 82
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.SetQuery(IQueryContext queryContext) in C:\GitHub\linq2db\Source\Data\DataConnection.Linq.cs:line 360
   at LinqToDB.Linq.Query`1.SetCommand(IDataContext dataContext, Expression expr, Object[] parameters, Int32 idx, Boolean clearQueryHints) in C:\GitHub\linq2db\Source\Linq\Query.cs:line 402
   at LinqToDB.Linq.Query`1.<RunQuery>d__23.MoveNext() in C:\GitHub\linq2db\Source\Linq\Query.cs:line 369
   at LinqToDB.Linq.Query`1.<Map>d__46.MoveNext() in C:\GitHub\linq2db\Source\Linq\Query.cs:line 1196
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Tests.TestBase.AreEqual[T](IEnumerable`1 expected, IEnumerable`1 result) in C:\GitHub\linq2db\Tests\Linq\TestBase.cs:line 1024
   at Tests.UserTests.Issue269Tests.TestDistinctSkip(String context) in C:\GitHub\linq2db\Tests\Linq\UserTests\Issue269Tests.cs:line 122
Result Message:	LinqToDB.SqlQuery.SqlException : Skip for subqueries is not supported by the 'SqlServer.2000' provider.


```

**Comment by sdanyliv** [comment]
@MaceWindu, @ili already prepared fixes in #670

**Comment by MaceWindu** [comment]
Hmm, yeah, looks like some of those issues handled there

**Comment by ili** [comment]
I did... waiting for review to merge :)

**Comment by ili** [comment]
Will exclude tests for mentioned databases

**Comment by ili** [comment]
@MaceWindu do you need `DBHost` virtual machine image?

**Comment by MaceWindu** [comment]
Is it an image with test databases?

I've already installed almost everything except:
- SAP HANA - need to try their VM image once more
- Informix - installed, but needs configuration
- DB2 z/OS, DB2 iSeries of course
- SQLiteMs - didn't tried .net core yet
- oracle native client from repository doesn't work with latest oracle XE
- azure and separate instances for each sql server version - have access but don't have time to setup it for now
- Firebird 3 - I will need it for Merge testing, but it doesn't work alongside with v2.5

So in general my answer is no, I could manage without this image. But it will be nice to provide something like that (if there is no licensing issues there) or instructions/scripts to setup environment for new developers.

**Comment by ili** [comment]
Yes this is VMWare image with most of supported databases

**Comment by ili** [comment]
PR merged, test now should success
