### ISSUE TITLE
DataConnection.execute<string> with comment causes NullPointerException

### ISSUE THREAD

**Issue by krenaud** [linq2db/linq2db#71]
Scenario:

Run the following test against linq2db commit d9f697717651825a5ebf4dc4fe7de97dc9307e22

```
[Test, IncludeDataContextSource(ProviderName.SQLite)]
public void TestExecuteString_WithComment_DoesNotThrow(string context)
{
	Assert.DoesNotThrow(() =>
	{
	    using (var conn = new DataConnection(context))
	    {
	        conn.Execute<string>("-- CREATE UNIQUE INDEX IdxUnitCounters ON UnitCounters (UnitId)");
	    }
	});
}
```

Expected result:
Statement to be executed without anything affected, no exceptions thrown and null returned.

Actual result:
Null pointer exception caused in DataConnectionExtensions.cs

```
Object reference not set to an instance of an object.
   at System.Data.SQLite.SQLiteDataReader.Read()
   at LinqToDB.Data.DataConnectionExtensions.ExecuteScalar[T](DataConnection connection, String sql) in c:\Users\khr\Documents\Sandbox\linq2db\Source\Data\DataConnectionExtensions.cs:line 240
   at LinqToDB.Data.DataConnectionExtensions.Execute[T](DataConnection connection, String sql) in c:\Users\khr\Documents\Sandbox\linq2db\Source\Data\DataConnectionExtensions.cs:line 204
   at Tests.DataProvider.SQLiteTest.<>c__DisplayClass1.<TestComment>b__0() in c:\Users\khr\Documents\Sandbox\linq2db\Tests\Linq\DataProvider\CommentTest.cs:line 31
```

I am having troubles debugging Linq2Db since I'm missing Db2 DLLs and some other stuff so I can't give more precise info than this.

**Comment by igor-tkachev** [comment]
As you can see this exception occurs inside SQLite.SQLiteDataReader.Read method. You should report this bug to SQLite team.
