### ISSUE TITLE
Nullable association

### ISSUE THREAD

**Issue by dzyranov** [linq2db/linq2db#714]
Throw exception : Specified cast is not valid.

```
Exception message:
Stack trace:
   at LinqToDB.DataProvider.DataProviderBase.IsDBNullAllowed(IDataReader reader, Int32 idx) in c:\projects\linq2db\Source\DataProvider\DataProviderBase.cs:line 237
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.IsDBNullAllowed(IDataReader reader, Int32 idx) in c:\projects\linq2db\Source\Data\DataConnection.Linq.cs:line 353
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.GetColumnReader(IDataContext dataContext, MappingSchema mappingSchema, IDataReader dataReader, Type type, Int32 idx, Expression dataReaderExpr) in c:\projects\linq2db\Source\Expressions\ConvertFromDataReaderExpression.cs:line 109
   at LinqToDB.Linq.Query`1.<>c__DisplayClass67.<Map>b__65(Expression e) in c:\projects\linq2db\Source\Linq\Query.cs:line 1193
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in c:\projects\linq2db\Source\Expressions\Extensions.cs:line 968
   at LinqToDB.Expressions.Extensions.<>c__DisplayClass3d.<Transform>b__34(MemberBinding b) in c:\projects\linq2db\Source\Expressions\Extensions.cs:line 1123
   at LinqToDB.Expressions.Extensions.Transform[T](ICollection`1 source, Func`2 func) in c:\projects\linq2db\Source\Expressions\Extensions.cs:line 938
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in c:\projects\linq2db\Source\Expressions\Extensions.cs:line 1157
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in c:\projects\linq2db\Source\Expressions\Extensions.cs:line 1067
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in c:\projects\linq2db\Source\Expressions\Extensions.cs:line 1015
   at LinqToDB.Expressions.Extensions.Transform[T](ICollection`1 source, Func`2 func) in c:\projects\linq2db\Source\Expressions\Extensions.cs:line 954
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in c:\projects\linq2db\Source\Expressions\Extensions.cs:line 1196
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in c:\projects\linq2db\Source\Expressions\Extensions.cs:line 1085
   at LinqToDB.Linq.Query`1.<Map>d__69.MoveNext() in c:\projects\linq2db\Source\Linq\Query.cs:line 1190
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Test1945.API.Data.CBltoolkitTest.TestNullAssociation() in E:\Projects\Server1945\Test1945\API\Data\CBltoolkitTest.cs:line 271
```

### Steps to reproduce

```c#
public class CEnhancementFire
 {
        [Identity]
        [PrimaryKey]
        [XmlAttribute]
        [Column("ID")]
        public long Id { get; set; }

        [Column("ID_FIRE")]
        public long? FireId { get; set; }

        [Association(ThisKey = "FireId", OtherKey = "Id")]
        public CEnhancementFire Short { get; set; }
}

var list = db
                   .GetTable<CEnhancementFire>()
                   .Select(p => new CEnhancementFire
                   {
                                Id = p.Id,
                                Short = p.Short
                   }).ToList();
```

### Environment details
linq2db version: *1.8.2*  
Database Server: *E.g. PostgreSQL 9.2*  
Database Provider: *E.g. Npgsql 3.2.3*  
Operating system: *E.g. Windows 7*  
Framework version: *.NET Framework 4.6.1*

**Comment by MaceWindu** [comment]
Could you try to downgrade to Npgsql 3.1.8 temporary and report wether it helped or not?

**Comment by dzyranov** [comment]
Work with Npgsql 3.1.8

**Comment by ili** [comment]
Looks like this fails: `(bool)st.Rows[idx]["AllowDBNull"]` not `bool` value in this column...

@dzyranov not clear Npgsql version you are using.

**Comment by dzyranov** [comment]
@ili https://github.com/npgsql/npgsql/releases/tag/v3.2.3

**Comment by ili** [comment]
That's new in 3.2.3, only i'v updated from 3.2.2 and getting huge number of errors....
Now "AllowDBNull" column can contain null value

**Comment by sdanyliv** [comment]
Fix i obvious, if it is null - we have to perform null check in reader expresson.

**Comment by ili** [comment]
Yes, now i'm looking also for #715
