### ISSUE TITLE
Count() > 0 always returns InvalidCastException 'Specified cast is not valid' for Postgres

### ISSUE THREAD

**Issue by Kempe** [linq2db/linq2db#752]
Hello,
since linq2db.dll v1.8.2 any query in form of:
bool bDataExist = objDB.t_currency.Where(y=>y.rank >= 10).Count() > 0;
returns InvalidCastException 'Specified cast is not vaild'.

Sample Table Declaration:
```sql
CREATE TABLE public.t_currency
(
  currency_id integer NOT NULL DEFAULT nextval('t_currency_currency_id_seq'::regclass),
  currency_name character varying(3) NOT NULL,
  rank integer NOT NULL DEFAULT 999
)
WITH (
  OIDS=FALSE
);
```
No matter what was specified in the Where() clause... the result is always 'Specified cast is not valid'...

Any help appreciated...
Thanks in advance.

```
Stacktrace:
   at LinqToDB.DataProvider.DataProviderBase.IsDBNullAllowed(IDataReader reader, Int32 idx) in c:\projects\linq2db\Source\DataProvider\DataProviderBase.cs:line 237
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.IsDBNullAllowed(IDataReader reader, Int32 idx) in c:\projects\linq2db\Source\Data\DataConnection.Linq.cs:line 353
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.GetColumnReader(IDataContext dataContext, MappingSchema mappingSchema, IDataReader dataReader, Type type, Int32 idx, Expression dataReaderExpr) in c:\projects\linq2db\Source\Expressions\ConvertFromDataReaderExpression.cs:line 109
   at LinqToDB.Expressions.ConvertFromDataReaderExpression.ColumnReader.GetValue(IDataReader dataReader) in c:\projects\linq2db\Source\Expressions\ConvertFromDataReaderExpression.cs:line 147
   at lambda_method(Closure , QueryContext , IDataContext , IDataReader , Expression , Object[] )
   at LinqToDB.Linq.Query`1.RunQuery[TE](QueryContext ctx, IDataContextInfo dataContextInfo, Expression expr, Object[] parameters, Func`6 mapper) in c:\projects\linq2db\Source\Linq\Query.cs:line 1083
   at LinqToDB.Linq.Query`1.<>c__DisplayClass4f.<SetElementQuery>b__4e(QueryContext ctx, IDataContextInfo db, Expression expr, Object[] ps) in c:\projects\linq2db\Source\Linq\Query.cs:line 1063
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression) in c:\projects\linq2db\Source\Linq\ExpressionQuery.cs:line 142
   at System.Linq.Queryable.Count[TSource](IQueryable`1 source)
   at WL.DB.Debug.Program.CurrencyQueryTest() in F:\WL\DB\WL.DB.Debug\Program.cs:line 56
   at WL.DB.Debug.Program.Main(String[] args) in F:\WL\DB\WL.DB.Debug\Program.cs:line 18
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()
```

### Environment details

linq2db version: 1.8.2  
Database Server: PostgreSQL 9.6.  
Database Provider: Npgsql 3.2.4.1  
Operating system: Windows 10
Framework version: .NET Framework 4.6.1

**Comment by dolifer** [comment]
seems like this commit fixes this https://github.com/linq2db/linq2db/commit/d1782b1d7586e39cc795587b382d0423445f897b

you can check latest unstable nuget from https://www.myget.org/feed/linq2db/package/nuget/linq2db

**Comment by Kempe** [comment]
Yes, this fixed my problem! Thanks for your help.
