### ISSUE TITLE
PostgreSQL CreateTable with DateTimeOffset gives an error

### ISSUE THREAD

**Issue by hahn-kev** [linq2db/linq2db#794]
I'm trying to Create a table on a PostgreSQL database, my class has a DateTimeOffset field like so:
```
public class ClassWDateTimeOffset
{
    public DateTimeOffset SomeDateWithTimeZone { get; set; }
}
```

However, when I look at the SQL used to create the table, this is generated:
```
CREATE TABLE "ClassWDateTimeOffset"
(
	"SomeDateWithTimeZone" DateTimeOffset NOT NULL
)
```
In case you're not aware, there's no DateTimeOffset type in PostgreSQL lol. As such the following exception gets thrown
```
Exception: Npgsql.PostgresException
Message  : 42704: type "datetimeoffset" does not exist
Stack trace:
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.ValidateEnd(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter`1.GetResult()
   at Npgsql.NpgsqlCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.LinqToDB.IDataContext.ExecuteNonQuery(Object query)
   at LinqToDB.Linq.Query`1.NonQueryQuery(IDataContext dataContext, Expression expr, Object[] parameters)
   at LinqToDB.Linq.Query`1.<SetNonQueryQuery>b__15_0(QueryContext ctx, IDataContext db, Expression expr, Object[] ps)
   at LinqToDB.Linq.Query`1.CreateTable(IDataContext dataContext, String tableName, String databaseName, String schemaName, String statementHeader, String statementFooter, Defaul
Nullable defaulNullable)
   at LinqToDB.DataExtensions.CreateTable[T](IDataContext dataContext, String tableName, String databaseName, String schemaName, String statementHeader, String statementFooter, D
efaulNullable defaulNullable)

```

### Steps to reproduce
Using the above class `ClassWDateTimeOffset` just run the following

```c#
var db = new DataConnection();
db.CreateTable<ClassWDateTimeOffset>();
```

From what I've found [here ](http://www.npgsql.org/doc/types/datetime.html) we should be using timestamptz as the column type. In order to work around this issue I've extended the standard Postgre data provider and the sql builder to fix this issue myself, but it would be great if we could fix it for the future. If it's agreed that this is the right way to fix the issue than I can submit a pull request.

### Environment details
linq2db version: *1.8.3*  
Database Server: *E.g. PostgreSQL 9.5.2*  
Database Provider: *E.g. Npgsql 3.2.5*  
Operating system: *E.g. Windows 10*  
Framework version: *.NET Core 1.0.4*

**Comment by igor-tkachev** [comment]
What ProgressSQL type you expect?

**Comment by hahn-kev** [comment]
I'd expect `timestamptz` or `timestamp with time zone`

**Comment by igor-tkachev** [comment]
I found this table http://www.npgsql.org/doc/types/datetime.html

**Comment by hahn-kev** [comment]
Yeah, I linked to that in my first post, that's how I picked that datatype.

**Comment by hahn-kev** [comment]
Looks like @jogibear9988 just approved my pull request. Thanks!
