### ISSUE TITLE
Merge fails if strings are used (Firebird)

### ISSUE THREAD

**Issue by Franki1986** [linq2db/linq2db#851]
DB: Firebird 2.1.3 (dialect 1, charset ISO8859_1)
Linq2Db: 1.9.0

I am using a simple InsertWhenNotMatched Merge. Everything works fine if I merge tables where no strings are used (in firebird I use VARCHARs).

For every VARCHAR a sql statement is created with "CAST(_utf8 x'47D' AS VARCHAR(2))" 
where the number after the 'x' changes and the size of VARCHAR also... 
The weired thing is I have no VARCHARs with this size.

```
[Table("CUSTOMER")]
	public partial class Customer
	{
		[Column("ID"),                        PrimaryKey,  NotNull] public int    Id { get; set; } 
		[Column(),                                     NotNull] public string Name { get; set; } 
		[Column(),                                     NotNull] public string FirstName { get; set; } 
		[Column(),                           Nullable         ] public string Company { get; set; } 
		[Column(),                                     NotNull] public string ZipCode { get; set; }
		[Column(),                                     NotNull] public string Town { get; set; } 
	}
var multiCust = new List<Customer>()
         {
            new Customer() {Id = 405, Name = "Max", FirstName = "Mad", Town = "stut", ZipCode = "55845", Company = "My"}
         };
        try
         {
            using (var dbContext = new MyDb())
            {
               dbContext.GetTable<Customer>().Merge()
                        .Using(multiCust)
                        .OnTargetKey()
                        .InsertWhenNotMatched()
                        .Merge();
            }
         }
         catch (Exception e)
         {
            Console.WriteLine(e);            
         }
```

I get following in the log file:

_MERGE INTO CUSTOMER Target
USING
(
	SELECT 405, CAST(_utf8 x'4D6178' AS VARCHAR(3)), CAST(_utf8 x'4D6164' AS VARCHAR(3)), CAST(_utf8 x'4D79' AS VARCHAR(2)), CAST(_utf8 x'3535383435' AS VARCHAR(5)), CAST(_utf8 x'73747574' AS VARCHAR(4)) FROM rdb$database
) Source (c0, c1, c2, c3, c4, c5)
ON (Target.ID = Source.c0)

WHEN NOT MATCHED THEN
INSERT
(
	ID,
	Name,
	FirstName,
	Company,
	ZipCode,
	Town
)
VALUES
(
	Source.c0,
	Source.c1,
	Source.c2,
	Source.c3,
	Source.c4,
	Source.c5
)
:    DataConnection

Exception: FirebirdSql.Data.FirebirdClient.FbException
Message  : Dynamic SQL Error
SQL error code = -104
Token unknown - line 4, column 25
x
   at FirebirdSql.Data.FirebirdClient.FbCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery() in c:\projects\linq2db\Source\Data\DataConnection.cs:line 945

Exception: FirebirdSql.Data.Common.IscException
Message  : Dynamic SQL Error
SQL error code = -104
Token unknown - line 4, column 25
x_

**Comment by Franki1986** [comment]
Same thing here for InsertOrUpdate

**Comment by MaceWindu** [comment]
Could you override value to sql converter for string and char types in your schema as a temporary workaround?

Looks like FB 2.1 doesn't support such literals yet.

**Comment by Franki1986** [comment]
Yes, sure. But could you post some example code for me, or where to put it in?

**Comment by MaceWindu** [comment]
I cannot say right now about string literal length limitations - Firebird documentation don't have such information.
As for max count of merged items: yes, if you merge them from client (not from query), we need to generate union with select for each record and Firebird have troubles with such big queries. For 2.5 (and I suspect for 2.1 you use) it is around 100 records. Firebird 3 supports more records.

**Comment by Franki1986** [comment]
I appreciate your answer, thanks! But for these scenarios it would be very helpful to make the query builder public.. For a list with 10000 records I could create very simple a  batch script like this:

`UPDATE OR INSERT INTO CUSTOMER(ID, NAME, FIRST_NAME, TOWN) VALUES (1, 'Hanks', 'Tom', 'Berlin') MATCHING(ID);
`
Matching could use the PRIMARY_KEY fields and that's it...
I think it is the fastest way. By the way how would I execute such a script with link2DB?

**Comment by sdanyliv** [comment]
db.Execute?

**Comment by Franki1986** [comment]
:-) Yeah ok this one I know, but I would like to build my Inserts and append a matching and a prefix Update OR..
So that the normally generated string like : 
`INSERT INTO CUSTOMER(ID, NAME, FIRST_NAME, TOWN) VALUES (1, 'Hanks', 'Tom', 'Berlin') `

that is created by Linq2Db I can append prefix and the merge after:

`UPDATE OR INSERT INTO CUSTOMER(ID, NAME, FIRST_NAME, TOWN) VALUES (1, 'Hanks', 'Tom', 'Berlin') MATCHING(ID);`

**UPDATE OR**    ...  **MATCHING(ID)**

**Comment by sdanyliv** [comment]
@Franki1986, have you tested performance of Merge vs Big SQL approach? It is worth time to create alternative solution?

**Comment by Franki1986** [comment]
Even with 10000 Records? I mean so that I will loop 100 * 100 records. .. 
But you are right, no issue without test.. I will report

**Comment by Franki1986** [comment]
Because the disussion started here, but I don't want to overload tis bug issue I posted another 'discussion' issue.
