### ISSUE TITLE
MS SQL stored procedure call fails if procedure contains XML output parameter.

### ISSUE THREAD

**Issue by pmatrosov** [linq2db/linq2db#859]
MS SQL stored procedure call fails if procedure contains XML output parameter.

```
Exception message: Implicit conversion from data type xml to nvarchar(max) is not allowed. Use the CONVERT function to run this query.
Stack trace: 
   at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.InternalExecuteNonQuery(TaskCompletionSource`1 completion, String methodName, Boolean sendToPipe, Int32 timeout, Boolean asyncWrite)
   at System.Data.SqlClient.SqlCommand.ExecuteNonQuery()
   at LinqToDB.Data.DataConnection.ExecuteNonQuery() in C:\Projects\Linq2DB\Data\DataConnection.cs:line 945

```

I guess this is because class SqlServerDataProvider did not contains appropriate mapping for DataType.Xml in SetParameterType method.
Workaround: I can resolve this problem if I add line to switch block of mentioned method:

```c#
case DataType.Xml : ((SqlParameter)parameter).SqlDbType = SqlDbType.Xml; break;
```

### Steps to reproduce

Stored procedure source code

```sql
CREATE PROCEDURE [dbo].[Test]
@param1 xml,
@param2 XML OUTPUT
AS
SET @param2 = @param1
RETURN 0
```

Call block generated by T4 code

```c#
		public static void Test(this DataConnection dataConnection, string @param1, out string @param2)
		{
			dataConnection.ExecuteProc("dbo.Test",
				new DataParameter("@param1", @param1, DataType.Xml),
				new DataParameter("@param2", null, DataType.Xml) {Direction = ParameterDirection.InputOutput, Size = -1});

			@param2 = Converter.ChangeTypeTo<string>(((IDbDataParameter) dataConnection.Command.Parameters["@param2"]).Value);
		}
```

### Environment details
linq2db version: *1.9.0*  
Database Server: *MSSQL 2014*  
Database Provider: *SQL Native*  
Operating system: *Windows 7*  
Framework version: *.NET Framework 4.6.1*

**Comment by sdanyliv** [comment]
Fixed in https://github.com/linq2db/linq2db/commit/6a14279c57fed69e9ff073e5cb5c010333b46c41
