### ISSUE TITLE
Association as extension method

### ISSUE THREAD

**Issue by genusP** [linq2db/linq2db#865]
```C#
[Test, DataContextSource] 
public void ExtensionTest2(string context) 
{ 
	using (var db = GetDataContext(context)) 
	{ 
		AreEqual( 
		   Child.Select(_ => _.Parent.Value1), 
		db.Child.Select(_ => _.Parent().Value1)); 
	} 
} 
```
Throw exception:
```
LinqToDB.Linq.LinqException: '_.Parent().Value1' cannot be converted to SQL.
   at LinqToDB.Linq.Builder.TableBuilder.TableContext.BuildExpression(Expression expression, Int32 level, ParameterExpression parentObject)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level)
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass72_0.<BuildExpression>b__0(Expression expr)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func)
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func)
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level)
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.FirstSingleBuilder.FirstSingleContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter)
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]()
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr)
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr)
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache)
   at LinqToDB.Linq.ExpressionQuery`1.System.Linq.IQueryProvider.Execute[TResult](Expression expression)
......
   }
```

### Environment details
linq2db version: *1.9.0*  
Operating system: *Windows 10*  
Framework version: *.NET Core 2*

**Comment by sdanyliv** [comment]
@genusP, please post method body also.

**Comment by genusP** [comment]
https://github.com/linq2db/linq2db/blob/c392b47e52b0acb43dae6fdd9d1a1b6633069613/Tests/Linq/Linq/AssociationTests.cs#L749

**Comment by genusP** [comment]
In my query
```C#
var query = from t in taskStore.GetByKey(taskId)
                        select new Tuple<Task, Request>(t, t.Request().CreatorId);
var (task, creatorId) = query.Single();


 [Association(ThisKey = nameof(Task.TargetId), OtherKey = nameof(Models.Request.Id))]
        public static Request Request(this Task task)
        {
            throw new NotSupportedException("Cal this function only LINQ expressions");
        }
```
Without CreatorId, work correctly.

**Comment by genusP** [comment]
Any plan to fix this issue?

**Comment by sdanyliv** [comment]
Missed this one.

**Comment by sdanyliv** [comment]
I need your model (Task, Request). Our tests work properly.

**Comment by genusP** [comment]
```C#
[Table(Schema="awt", Name="Tasks")]
	public partial class Task : ITargetAware
	{
		[PrimaryKey, Identity   ] public int       Id          { get; set; } // Int
		[Column,     NotNull    ] public DateTime  DateBegin   { get; set; } // DateTime
		[Column,        Nullable] public DateTime? DateEnd     { get; set; } // DateTime
		[Column,     NotNull    ] public Guid      DirectionId { get; set; } // UniqueIdentifier
		[Column,        Nullable] public int?      StageId     { get; set; } // Int
		[Column,     NotNull    ] public string    Text        { get; set; } // varchar(1000)
		[Column,     NotNull    ] public string    TargetName  { get; set; } // nvarchar(128)
		[Column,     NotNull    ] public int       TargetId    { get; set; } // Int
		[Column,        Nullable] public int?      ParentId    { get; set; } // Int

		#region Associations

		/// <summary>
		/// FK_Tasks_Tasks_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="ParentId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Task> ChildTasks { get; set; }

		/// <summary>
		/// FK_Tasks_Tasks
		/// </summary>
		[Association(ThisKey="ParentId", OtherKey="Id", CanBeNull=true, Relationship=Relationship.ManyToOne, KeyName="FK_Tasks_Tasks", BackReferenceName="ChildTasks")]
		public Task ParentTask { get; set; }

		/// <summary>
		/// FK_WorkReports_Tasks_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="TaskId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<WorkReport> WorkReports { get; set; }

		#endregion
	}
```

```c#
[Table(Schema="bda", Name="Requests")]
	public partial class Request
	{
		[PrimaryKey,                Identity   ] public int      Id               { get; set; } // Int
		[Column(SkipOnUpdate=true), NotNull    ] public DateTime CreateDate       { get; set; } // DateTime
		[Column,                    NotNull    ] public int      CreatorId        { get; set; } // Int
		[Column,                    NotNull    ] public DateTime DateEndByCreator { get; set; } // DateTime
		[Column,                       Nullable] public string   Note             { get; set; } // varchar(1000)
		[Column,                    NotNull    ] public int      FirmId           { get; set; } // Int
		[Column,                    NotNull    ] public int      PriorityId       { get; set; } // Int
		[Column,                    NotNull    ] public int      CategoryId       { get; set; } // Int

		#region Associations

		/// <summary>
		/// FK_Attachments_Requests_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RequestId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Attachment> Attachments { get; set; }

		/// <summary>
		/// FK_Comments_Requests_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RequestId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Comment> Comments { get; set; }

		/// <summary>
		/// FK_Requests_FirmInfo
		/// </summary>
		[Association(ThisKey="FirmId", OtherKey="Id", CanBeNull=false, Relationship=Relationship.ManyToOne, KeyName="FK_Requests_FirmInfo", BackReferenceName="Requests")]
		public FirmInfo FirmInfo { get; set; }

		/// <summary>
		/// FK_RequestDocumentTypes_Requests_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RequestId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<RequestDocumentType> RequestDocumentTypes { get; set; }

		/// <summary>
		/// FK_RequestStages_Requests_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RequestId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<RequestStage> RequestStages { get; set; }

		/// <summary>
		/// FK_RequestSystems_Requests_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RequestId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<RequestSystem> RequestSystems { get; set; }

		/// <summary>
		/// FK_Subscribers_Requests_BackReference
		/// </summary>
		[Association(ThisKey="Id", OtherKey="RequestId", CanBeNull=true, Relationship=Relationship.OneToMany, IsBackReference=true)]
		public IEnumerable<Subscriber> Subscribers { get; set; }

		#endregion
	}
```

```C#
public partial class Request
    {
        public const string RequestTargetName = "bda.Requests";
        
        [Association(ThisKey = nameof(Id), OtherKey = nameof(Task.TargetId), ExpressionPredicate = nameof(ByTargetNameExpr))]
        public IEnumerable<Task> Tasks { get; set; }

        [Association(ThisKey =nameof(Id), OtherKey =nameof(Assignment.TargetId), ExpressionPredicate =nameof(ByTargetNameExpr))]
        public IEnumerable<Assignment> Assignments { get; set; }

        private static Expression<Func<Request, ITargetAware, bool>> ByTargetNameExpr()
            => (r,a) => a.TargetName == RequestTargetName;

        [Association(ThisKey =nameof(CreatorId), OtherKey =nameof(Employee.Id))]
        public Employee Creator { get; set; }

        [Association(ThisKey = nameof(Id), OtherKey = nameof(Assignment.TargetId), ExpressionPredicate = nameof(CurrentAssignmentExpr))]
        public IEnumerable<Assignment> CurrentAssignments { get; set; }

        private static Expression<Func<Request, Assignment, bool>> CurrentAssignmentExpr()
            => (r, a) => a.TargetName == RequestTargetName && (a.DateRevoke == null || a.DateRevoke>SqlServer.GetDate());

        
    }
```

**Comment by sdanyliv** [comment]
Strange it works on my side on .NET Framework 4.5, i have no chances now to test it in .NET Core.
One question: `taskStore.GetByKey(taskId)` returns `IQueryable<Task>` ?

**Comment by sdanyliv** [comment]
Also, please check last myGet release, maybe it is already fixed.

https://www.myget.org/feed/linq2db/package/nuget/linq2db

**Comment by genusP** [comment]
I check in linq2db.Core 1.9.1-rc1617. Its work fine. Thanks.
