### ISSUE TITLE
%1 is not a valid Win32 application

### ISSUE THREAD

**Issue by rahuljain257** [linq2db/linq2db#901]
Hello Admin,

I was trying to execute the tt file but I stumble upon this error can you please suggest some solution related to this 
```
Error	1	Running transformation: System.TypeInitializationException: The type initializer for 'Sap.Data.Hana.HanaConnection' threw an exception. ---> System.Exception: %1 is not a valid Win32 application
   at Sap.Data.Hana.HanaUnmanagedDll.LoadDll(String dllPath)
   at Sap.Data.Hana.HanaUnmanagedDll..ctor()
   at Sap.Data.Hana.HanaUnmanagedDll.get_Instance()
   at Sap.Data.Hana.HanaConnection..cctor()
   --- End of inner exception stack trace ---
   at Sap.Data.Hana.HanaConnection..ctor(String connectionString)
   at lambda_method(Closure , String )
   at LinqToDB.DataProvider.DynamicDataProviderBase.CreateConnectionInternal(String connectionString)
   at LinqToDB.DataProvider.DataProviderBase.CreateConnection(String connectionString)
   at LinqToDB.Data.DataConnection.get_Connection()
   at LinqToDB.Data.DataConnection.CreateCommand()
   at LinqToDB.Data.DataConnection.get_Command()
   at LinqToDB.DataProvider.DataProviderBase.InitCommand(DataConnection dataConnection, CommandType commandType, String commandText, DataParameter[] parameters)
   at LinqToDB.Data.DataConnection.InitCommand(CommandType commandType, String sql, DataParameter[] parameters, List`1 queryHints)
   at LinqToDB.Data.CommandInfo.Execute[T]()
   at LinqToDB.DataProvider.SapHana.SapHanaSchemaProvider.GetSchema(DataConnection dataConnection, GetSchemaOptions options)
   at Microsoft.VisualStudio.TextTemplating32E517318540B6669328A5E947670297288845A71B74E8F68AD7A5937B09B955876E5C8AC4111EA67165A8F43DA0571EB3574CFB915FC790D8A9356E18A93B6C.GeneratedTextTransformation.LoadServerMetadata(DataConnection dataConnection) in c:\Projects\Rahul_Test\LinqToHana\Testing\LinqToDB.Templates\DataModel.ttinclude:line 91
   at Microsoft.VisualStudio.TextTemplating32E517318540B6669328A5E947670297288845A71B74E8F68AD7A5937B09B955876E5C8AC4111EA67165A8F43DA0571EB3574CFB915FC790D8A9356E18A93B6C.GeneratedTextTransformation.LoadMetadata(DataConnection dataConnection) in c:\Projects\Rahul_Test\LinqToHana\Testing\LinqToDB.Templates\DataModel.ttinclude:line 361
   at Microsoft.VisualStudio.TextTemplating32E517318540B6669328A5E947670297288845A71B74E8F68AD7A5937B09B955876E5C8AC4111EA67165A8F43DA0571EB3574CFB915FC790D8A9356E18A93B6C.GeneratedTextTransformation.LoadSapHanaMetadata(String connectionString) in c:\Projects\Rahul_Test\LinqToHana\Testing\LinqToDB.Templates\LinqToDB.SapHana.ttinclude:line 101
   at Microsoft.VisualStudio.TextTemplating32E517318540B6669328A5E947670297288845A71B74E8F68AD7A5937B09B955876E5C8AC4111EA67165A8F43DA0571EB3574CFB915FC790D8A9356E18A93B6C.GeneratedTextTransformation.TransformText() in c:\Projects\Rahul_Test\LinqToHana\Testing\DataModels\CopyMe.SapHana.tt:line 43	c:\Projects\Rahul_Test\LinqToHana\Testing\LinqToDB.Templates\DataModel.ttinclude	91	1	Testing

```

**Comment by sdanyliv** [comment]
Looks like it is a problem with Sap Hana libraries. 
Can you try to create in test application, add reference to library Sap.Data.Hana and create  Sap.Data.Hana.HanaConnection?

**Comment by MaceWindu** [comment]
Well, HANA provider tries to load unmanaged provider dlls "libSQLDBCHDB.dll" and "libADONETHDB.dll" internally and something goes wrong.
I would recommend you:
- check with process monitor wether it can find them (https://docs.microsoft.com/en-us/sysinternals/downloads/procmon ) or you need to edit your environment variables
- check that your process architecture matches arch for those dlls

**Comment by MaceWindu** [comment]
Closing answered/non-actionable issues. Feel free to reopen/continue discussion if it wasn't anwsered.
