### ISSUE TITLE
GroupBy.OrderBy.First

### ISSUE THREAD

**Issue by n9** [linq2db/linq2db#911]
Not sure whether it is exactly same as: https://github.com/linq2db/linq2db/issues/672

```
Exception message: 
LinqToDB.LinqToDBException : '_.ParentID' cannot be converted to SQL.
Stack trace:
at LinqToDB.Linq.Builder.SelectContext.GetMemberExpression(MemberInfo member, Boolean add, Type type, Expression sourceExpression) in linq2db\Source\Linq\Builder\SelectContext.cs:line 1165
   at LinqToDB.Linq.Builder.SelectContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in linq2db\Source\Linq\Builder\SelectContext.cs:line 345
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndexInternal(Expression expression, Int32 level, ConvertFlags flags) in linq2db\Source\Linq\Builder\SelectContext.cs:line 563
   at LinqToDB.Linq.Builder.SelectContext.ConvertToIndex(Expression expression, Int32 level, ConvertFlags flags) in linq2db\Source\Linq\Builder\SelectContext.cs:line 435
   at LinqToDB.Linq.Builder.SubQueryContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in linq2db\Source\Linq\Builder\SubQueryContext.cs:line 98
   at LinqToDB.Linq.Builder.ExpressionContext.ConvertToSql(Expression expression, Int32 level, ConvertFlags flags) in linq2db\Source\Linq\Builder\ExpressionContext.cs:line 57
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertToSql(IBuildContext context, Expression expression, Boolean unwrap) in linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 840
   at LinqToDB.Linq.Builder.ExpressionBuilder.ConvertExpressions(IBuildContext context, Expression expression, ConvertFlags queryConvertFlag) in linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 636
   at LinqToDB.Linq.Builder.OrderByBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in linq2db\Source\Linq\Builder\OrderByBuilder.cs:line 49
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in linq2db\Source\Linq\Builder\MethodCallBuilder.cs:line 22
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 184
   at LinqToDB.Linq.Builder.FirstSingleBuilder.BuildMethodCall(ExpressionBuilder builder, MethodCallExpression methodCall, BuildInfo buildInfo) in linq2db\Source\Linq\Builder\FirstSingleBuilder.cs:line 25
   at LinqToDB.Linq.Builder.MethodCallBuilder.BuildSequence(ExpressionBuilder builder, BuildInfo buildInfo) in linq2db\Source\Linq\Builder\MethodCallBuilder.cs:line 22
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildSequence(BuildInfo buildInfo) in linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 184
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQuery(IBuildContext context, MethodCallExpression expr) in linq2db\Source\Linq\Builder\ExpressionBuilder.SqlBuilder.cs:line 238
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryContext(IBuildContext context, MethodCallExpression expr) in linq2db\Source\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 289
   at LinqToDB.Linq.Builder.ExpressionBuilder.GetSubQueryExpression(IBuildContext context, MethodCallExpression expr, Boolean enforceServerSide) in linq2db\Source\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 300
   at LinqToDB.Linq.Builder.ExpressionBuilder.TransformExpression(IBuildContext context, Expression expr, Boolean enforceServerSide) in linq2db\Source\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 233
   at LinqToDB.Linq.Builder.ExpressionBuilder.<>c__DisplayClass72_0.<BuildExpression>b__0(Expression expr) in linq2db\Source\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 25
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in linq2db\Source\Expressions\Extensions.cs:line 1349
   at LinqToDB.Expressions.Extensions.Transform2[T](IEnumerable`1 source, Func`2 func) in linq2db\Source\Expressions\Extensions.cs:line 1333
   at LinqToDB.Expressions.Extensions.Transform(Expression expr, Func`2 func) in linq2db\Source\Expressions\Extensions.cs:line 1545
   at LinqToDB.Linq.Builder.ExpressionBuilder.BuildExpression(IBuildContext context, Expression expression, Boolean enforceServerSide) in linq2db\Source\Linq\Builder\ExpressionBuilder.QueryBuilder.cs:line 25
   at LinqToDB.Linq.Builder.SelectContext.BuildExpression(Expression expression, Int32 level, Boolean enforceServerSide) in linq2db\Source\Linq\Builder\SelectContext.cs:line 115
   at LinqToDB.Linq.Builder.SelectContext.BuildQuery[T](Query`1 query, ParameterExpression queryParameter) in linq2db\Source\Linq\Builder\SelectContext.cs:line 65
   at LinqToDB.Linq.Builder.ExpressionBuilder.Build[T]() in linq2db\Source\Linq\Builder\ExpressionBuilder.cs:line 168
   at LinqToDB.Linq.Query`1.CreateQuery(IDataContext dataContext, Expression expr) in linq2db\Source\Linq\Query.cs:line 295
   at LinqToDB.Linq.Query`1.GetQuery(IDataContext dataContext, Expression& expr) in linq2db\Source\Linq\Query.cs:line 244
   at LinqToDB.Linq.ExpressionQuery`1.GetQuery(Expression& expression, Boolean cache) in linq2db\Source\Linq\ExpressionQuery.cs:line 84
   at LinqToDB.Linq.ExpressionQuery`1.System.Collections.Generic.IEnumerable<T>.GetEnumerator() in linq2db\Source\Linq\ExpressionQuery.cs:line 186
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
```

### Steps to reproduce

```c#
[Test, DataContextSource]
public void Test(string context)
{
	using (var db = GetDataContext(context))
	{
		var query = db.Child
			.GroupBy(p => p.ParentID % 2 == 0)
			.Select(g => new
			{
				g.Key,
				X = g.OrderBy(_ => _.ParentID).First()
			});

		var array = query.ToArray();
	}
}
```

### Environment details
linq2db version: *https://github.com/linq2db/linq2db/commit/2d5a97375e414f7358089ea2d9addfabac898ff8*
Database Server: *DataContextSourceAttribute* 
Database Provider: *DataContextSourceAttribute* 
Operating system: *Windows*
Framework version: *.NET Framework 4.7.0*

**Comment by sdanyliv** [comment]
It's not convertible to SQL, you have to use Window Functions here.
IOW, you are trying to select whole record after grouping which is not valid.

**Comment by sdanyliv** [comment]
Sample query is here:
```cs
var query =
	from c in
		from cs in db.Child
		select new
		{
			RowNumber = Sql.Ext.RowNumber().Over().PartitionBy(cs.ParentID % 2 == 0).OrderBy(cs.ParentID).ToValue(),
			Child = cs
		}
	where c.RowNumber == 1
	select new
	{
		Key = c.Child.ParentID % 2 == 0,
		c.Child
	};
```
Currently we do not have plans to do such transformations automatically. It is not trivial to detect such requests.

**Comment by n9** [comment]
Ok, thanks.
