### ISSUE TITLE
Is there a way to parameterize Contains query?

### ISSUE THREAD

**Issue by arwyl** [linq2db/linq2db#973]
Currently linq query with Contains method generates sql operator "in" with inlined parameters.

For example:

```
[Test]
		public void __Linq2Db_InlineParameters_For_Contains()
		{
			var ids = new int[] { 1, 2, 3 };

			using (var db = GetConnection())
			{
				var query = db.Users.Where(x => ids.Contains(x.Id));

				Console.WriteLine(query);
			}
		}
```

generates:

```
SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[IsActive],
	[t1].[AppointmentId]
FROM
	[Users] [t1]
WHERE
	[t1].[Id] IN (1, 2, 3)
```

Is there a way to generate something like [t1].[Id] IN (@p0, @p1, @p2)?

### Environment details
linq2db version: 1.10.1
Database Server: SqlServer 2016 
Database Provider: SqlServer.2012
Operating system: Windows 10
Framework version: .NET Framework 4.6.2

**Comment by sdanyliv** [comment]
Please explain when it can be useful?

**Comment by arwyl** [comment]
As our DBA says: for sql query caching

[Usefull link](https://www.brentozar.com/blitzcache/multiple-plans/)

Queries have been found with multiple execution plans. This can be caused by multiple things, but the two primary causes are a lack of parameterization or improper parameterization.

When queries aren’t parameterized, SQL Server will end up creating a separate plan for each set of literal values. This can cause significant plan cache bloat and lead to memory problems over time.

Even when queries are parameterized, SQL Server may create multiple execution plans for the same query. SQL Server will create a separate execution plan for different variations of parameter length

**Comment by LbISS** [comment]
Moreover, each new set of parameters in case of lack of parameterization causes SQL Server to generate separate query plan on each query. It costs about 50-200ms depending on query difficulty.

**Comment by n9** [comment]
So, it is (only) useful when the number of parameters is same?

**Comment by arwyl** [comment]
Basically, yes
But in our case we talk about the difference between 10 and 1000+ cached plans

**Comment by sdanyliv** [comment]
In your situation it is easy to write SqlExtension.
```cs
public static class MySqlExtensions
{
	[Sql.Extension("{field} IN ({values, ', '})", IsPredicate = true)]
	public static bool In<T>(this Sql.ISqlExtension ext, [ExprParameter] T field, [ExprParameter] params T[] values)
	{
		throw new NotImplementedException();
	}
}
```
```cs
using (var db = GetDataContext(context))
{
	var param = 4;
	var resultQuery =
		from o in db.Parent
		where Sql.Ext.In(o.ParentID, 1, 2, 3, param)
		select o;
	var str = resultQuery.ToString();
}
```
```sql
DECLARE @param  -- Int32
SET     @param = 4

SELECT
	[t1].[ParentID],
	[t1].[Value1]
FROM
	[Parent] [t1]
WHERE
	[t1].[ParentID] IN (1, 2, 3, @param)
```

**Comment by arwyl** [comment]
I tried passing int[] as a parameter in In<T> method, but got an exception 

```
System.ArgumentException : No mapping exists from object type System.Int32[] to a known managed provider native type.

Result StackTrace:	
at System.Data.SqlClient.MetaType.GetMetaTypeFromValue(Type dataType, Object value, Boolean inferLen, Boolean streamAllowed)
   at System.Data.SqlClient.SqlParameter.GetMetaTypeOnly()
   at System.Data.SqlClient.SqlParameter.get_SqlDbType()
   at LinqToDB.DataProvider.SqlServer.SqlServerSqlBuilder.GetProviderTypeName(IDbDataParameter parameter) in c:\projects\linq2db\Source\DataProvider\SqlServer\SqlServerSqlBuilder.cs:line 329
   at LinqToDB.SqlProvider.BasicSqlBuilder.PrintParameterType(StringBuilder sb, IDbDataParameter parameter) in c:\projects\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 2815
   at LinqToDB.SqlProvider.BasicSqlBuilder.PrintParameters(StringBuilder sb, IDbDataParameter[] parameters) in c:\projects\linq2db\Source\SqlProvider\BasicSqlBuilder.cs:line 2893
   at LinqToDB.Data.TraceInfo.get_SqlText() in c:\projects\linq2db\Source\Data\TraceInfo.cs:line 57
   at Valhalla.Core.UnitTests.Domain.Linq2DbTests.<>c.<__Linq2Db_Test>b__20_0(TraceInfo x) in C:\Valhalla\Valhalla.Core\Valhalla.Core\Valhalla.Core.UnitTests\Domain\Linq2DbTests.cs:line 810
   at Valhalla.Core.CoreUtils.Linq2DBUtils.<>c__DisplayClass0_0.<SwitchTraceOn>b__0(TraceInfo trace) in C:\Valhalla\Valhalla.Core\Valhalla.Core\Valhalla.Core\CoreUtils\Linq2DBUtils.cs:line 24
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in c:\projects\linq2db\Source\Data\DataConnection.cs:line 1122
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader() in c:\projects\linq2db\Source\Data\DataConnection.QueryRunner.cs:line 428
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__2b`1.MoveNext() in c:\projects\linq2db\Source\Linq\QueryRunner.cs:line 327
```

**Comment by sdanyliv** [comment]
Passing int array will not work because we expect Expressions and array constant is not convertible to SQL for now. It is also doable using SqlExtension but it needs extra coding of Builder Class, samples are here: https://github.com/linq2db/linq2db/blob/3fe20761f008a6dd9de77fcc5c2e3fe61c6fc1d7/Source/LinqToDB/Sql/Sql.Analytic.cs#L51
Please ensure from start that you have performance issues. Only then we can think about optimizations and workarounds. Nowadays SQL optimizators are smart enough.

**Comment by arwyl** [comment]
Can you give an example how to add named parameters to resulting query in Sql.IExtensionCallBuilder Build?

**Comment by sdanyliv** [comment]
`builder.AddXXX`

**Comment by arwyl** [comment]
I tried to use .AddParameter
```
class MyItemBuilder : Sql.IExtensionCallBuilder
	{
		public void Build(Sql.ISqExtensionBuilder builder)
		{
			var values = builder.GetValue<System.Collections.IEnumerable>("values");

			List<string> pars = new List<string>();

			int i = 0;

			foreach (var value in values)
			{
				pars.Add($"@p{i}");
				builder.AddParameter($"@p{i}", value.ToString());
				i++;
			}

			builder.AddExpression("generatedExpr", string.Join(", ", pars));
		}
	}

	public static class MySqlExtensions
	{
		[Sql.Extension("{field} IN ({generatedExpr})", IsPredicate = true, BuilderType = typeof(MyItemBuilder))]
		public static bool In<T>(this Sql.ISqlExtension ext, [ExprParameter] T field, [ExprParameter] params T[] values)
		{
			throw new NotImplementedException();
		}
	}
```

The sql was correct:

```
SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[IsActive],
	[t1].[AppointmentId]
FROM
	[Users] [t1]
WHERE
	[t1].[Id] IN (@p0, @p1, @p2)
```

but no parameters existed:
```

Result StackTrace:	
at System.Data.SqlClient.SqlConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.SqlInternalConnection.OnError(SqlException exception, Boolean breakConnection, Action`1 wrapCloseInAction)
   at System.Data.SqlClient.TdsParser.ThrowExceptionAndWarning(TdsParserStateObject stateObj, Boolean callerHasConnectionLock, Boolean asyncClose)
   at System.Data.SqlClient.TdsParser.TryRun(RunBehavior runBehavior, SqlCommand cmdHandler, SqlDataReader dataStream, BulkCopySimpleResultSet bulkCopyHandler, TdsParserStateObject stateObj, Boolean& dataReady)
   at System.Data.SqlClient.SqlDataReader.TryConsumeMetaData()
   at System.Data.SqlClient.SqlDataReader.get_MetaData()
   at System.Data.SqlClient.SqlCommand.FinishExecuteReader(SqlDataReader ds, RunBehavior runBehavior, String resetOptionsString, Boolean isInternal, Boolean forDescribeParameterEncryption)
   at System.Data.SqlClient.SqlCommand.RunExecuteReaderTds(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, Boolean async, Int32 timeout, Task& task, Boolean asyncWrite, Boolean inRetry, SqlDataReader ds, Boolean describeParameterEncryptionRequest)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method, TaskCompletionSource`1 completion, Int32 timeout, Task& task, Boolean& usedCache, Boolean asyncWrite, Boolean inRetry)
   at System.Data.SqlClient.SqlCommand.RunExecuteReader(CommandBehavior cmdBehavior, RunBehavior runBehavior, Boolean returnStream, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteReader(CommandBehavior behavior, String method)
   at System.Data.SqlClient.SqlCommand.ExecuteDbDataReader(CommandBehavior behavior)
   at System.Data.Common.DbCommand.System.Data.IDbCommand.ExecuteReader(CommandBehavior behavior)
   at LinqToDB.Data.DataConnection.ExecuteReader(CommandBehavior commandBehavior) in c:\projects\linq2db\Source\Data\DataConnection.cs:line 1132
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader() in c:\projects\linq2db\Source\Data\DataConnection.QueryRunner.cs:line 428
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__2b`1.MoveNext() in c:\projects\linq2db\Source\Linq\QueryRunner.cs:line 327

Result Message:	System.Data.SqlClient.SqlException : Must declare the scalar variable "@p0".

```

**Comment by arwyl** [comment]
I also tried
builder.AddParameter($"@p{i}", new LinqToDB.SqlQuery.SqlParameter(value.GetType(), $"@p{i}", value));

and

builder.Query.Parameters.Add(new LinqToDB.SqlQuery.SqlParameter(value.GetType(), $"@{expr.Member.Name}{i}", value));

also no luck..

**Comment by sdanyliv** [comment]
Hold on, i'll prepare sample in an hour,

**Comment by sdanyliv** [comment]
Unfortunately it is not possible with current sources. I have prepared PR to allow such query extension.

**Comment by arwyl** [comment]
thanks a lot for your help!

**Comment by sdanyliv** [comment]
So closing for now. New package is on MyGet.

**Comment by arwyl** [comment]
@sdanyliv unfortunately I encountered a major problem with this solution after upgrading to version 2.0.0.. The parameterized expression seems to be cached after first evaluation with the first parameter enumerable..

```
[Test]
		public void Linq2DbParametrizedContainsTests_Ensure_All_Parameters_Are_Parametrized()
		{
				using (var db = new TestDataConnection())
				{
					var ids = new int[] { 1, 2, 3 };

                                         // 5 users created in DB. With ids 1, 2, 3, 4, 5
					var query = db.Users.Where(x => Sql.Ext.In(x.Id, ids));
                                         // correct query with three parameters
					Console.WriteLine(query.ToString());

					Assert.AreEqual(3, query.ToList().Count);

					Assert.IsTrue(query.ToString().Contains("IN (@ids, @ids1, @ids2)"));

					ids = new int[] { 5, 6 };

					query = db.Users.Where(x => Sql.Ext.In(x.Id, ids));

					// same query as before.. With three parameters instead of two
					Console.WriteLine(query.ToString());

					// 3 instead of 1
					Assert.AreEqual(1, query.ToList().Count);
                                         // false
					Assert.IsTrue(query.ToString().Contains("IN (@ids, @ids1)"));
				}
		}
```

Output:
```
--  testDataProvider SqlServer.2008
DECLARE @ids Int -- Int32
SET     @ids = 1
DECLARE @ids1 Int -- Int32
SET     @ids1 = 2
DECLARE @ids2 Int -- Int32
SET     @ids2 = 3

SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[IsActive],
	[t1].[Guid],
	[t1].[AppointmentId]
FROM
	[Users] [t1]
WHERE
	[t1].[Id] IN (@ids, @ids1, @ids2)

--  testDataProvider SqlServer.2008
DECLARE @ids Int -- Int32
SET     @ids = 1
DECLARE @ids1 Int -- Int32
SET     @ids1 = 2
DECLARE @ids2 Int -- Int32
SET     @ids2 = 3

SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[IsActive],
	[t1].[Guid],
	[t1].[AppointmentId]
FROM
	[Users] [t1]
WHERE
	[t1].[Id] IN (@ids, @ids1, @ids2)
```

And the  Build method of IExtensionCallBuilder implementation of Sql.Ext.In extension is not called for second evaluation.. Do you have any ideas, how that can be fixed?


IExtensionCallBuilder implementation:
```
/// <summary>
	/// Builder for parametrized sql IN expression
	/// </summary>
	/// <seealso cref="LinqToDB.Sql.IExtensionCallBuilder" />
	public class InExpressionItemBuilder : Sql.IExtensionCallBuilder
	{
		/// <summary>
		/// Builds the parametrized sql IN expression
		/// </summary>
		/// <param name="builder">The builder.</param>
		/// <exception cref="ArgumentNullException">Values for \"In\" operation should not be empty - values</exception>
		/// <see cref="SqlExtensions.In{T}(Sql.ISqlExtension, T, T[])"/>
		/// <seealso cref="SqlExtensions.In{T}(Sql.ISqlExtension, T, System.Collections.Generic.IEnumerable{T})"/>
		public void Build(Sql.ISqExtensionBuilder builder)
		{
			var parameterName = (builder.Arguments[2] as MemberExpression)?.Member?.Name ?? "p";

			var values = builder.GetValue<System.Collections.IEnumerable>("values");

			if (values == null || !values.Any())
			{
				throw new ArgumentNullException("Values for \"In\" operation should not be empty", "values");
			}

			builder.Query.IsParameterDependent = true;

			foreach (var value in values)
			{
				var param = new SqlParameter(value?.GetType() ?? typeof(object), parameterName, value);
				builder.AddParameter("values", param);
			}
		}
	}
```

SqlExtensions class:

```
public static class SqlExtensions
	{
		/// <summary>
		/// Sql IN expression extension
		/// </summary>
		/// <typeparam name="T"></typeparam>
		/// <param name="ext">The ext.</param>
		/// <param name="field">The field.</param>
		/// <param name="values">The values.</param>
		/// <returns></returns>
		[Sql.Extension("{field} IN ({values, ', '})", IsPredicate = true, BuilderType = typeof(InExpressionItemBuilder))]
		public static bool In<T>(this Sql.ISqlExtension ext, [ExprParameter] T field, IEnumerable<T> values)
		{
			throw new NotImplementedException();
		}
    }
```

**Comment by MaceWindu** [comment]
Could you open new issue?

**Comment by sdanyliv** [comment]
Try to use `SqlQueryDependentAttribute`
```cs
public static class SqlExtensions
{
   /// <summary>
   /// Sql IN expression extension
   /// </summary>
   /// <typeparam name="T"></typeparam>
   /// <param name="ext">The ext.</param>
   /// <param name="field">The field.</param>
   /// <param name="values">The values.</param>
   /// <returns></returns>
   [Sql.Extension("{field} IN ({values, ', '})", IsPredicate = true, BuilderType = typeof(InExpressionItemBuilder))]
   public static bool In<T>(this Sql.ISqlExtension ext, [ExprParameter] T field, [SqlQueryDependent] IEnumerable<T> values)
   {
      throw new NotImplementedException();
   }
}
```
Reopening to track why `builder.Query.IsParameterDependent = true;` is not helped in this situation.

**Comment by arwyl** [comment]
@sdanyliv unfortunately, same result..

**Comment by sdanyliv** [comment]
I think i know where is problem. Without MapMember it is reproducible?

**Comment by arwyl** [comment]
@sdanyliv yes. Both with and without MapMember

**Comment by arwyl** [comment]
thanks a lot!

**Comment by arwyl** [comment]
@sdanyliv will the patch be available on nuget any time soon?

**Comment by sdanyliv** [comment]
We plan version 2.1.0 on next week. Could you please test this via MyGet?
But note that, unfortunately, MapMember will not work with caching.

**Comment by sdanyliv** [comment]
You can do this, if you implement **IExpressionPreprocessor**  interface in your DataConnection class. But it's not so easy, especially if `Contains` is hidden in another function that returns IQueryable.
But you can check my code in [EF integration](https://github.com/linq2db/linq2db.EntityFrameworkCore/blob/master/Source/LinqToDB.EntityFrameworkCore/LinqToDBForEFToolsImplDefault.cs#L559).

**Comment by arwyl** [comment]
thanks, will try it in a couple of days

**Comment by arwyl** [comment]
unfortunately my test still doesn't work
```
                                         for (int i = 0; i < 5; i++)
					{
						db.Insert(new User
						{
							Id = i
						});
					}

					var ids = new int[] { 1, 2, 3 };

					var query = db.Users.Where(x => Sql.Ext.In(x.Id, ids));

					Console.WriteLine(query.ToString());

					Assert.AreEqual(3, query.Count());

					Assert.IsTrue(query.ToString().Contains("IN (@ids, @ids1, @ids2)"));

					ids = new int[] { 5, 6 };

					var query2 = db.Users.Where(x => Sql.Ext.In(x.Id, ids));
                                         // same output as before
					Console.WriteLine(query2.ToString());
                                         // Message:   Expected: 0  But was:  3
					Assert.AreEqual(0, query2.Count());

					Assert.IsTrue(query2.ToString().Contains("IN (@ids, @ids1)"));
```

it works, when query is extracted to another method, but doesn't work, when queries are in the same method

**Comment by sdanyliv** [comment]
Have you tried my method?

https://github.com/linq2db/linq2db/blob/61a565fdc1d700580332ca32d133673d4a9c2c55/Tests/Linq/UserTests/Issue973Tests.cs#L47

**Comment by arwyl** [comment]
@sdanyliv yes. And, as I said, it works, when the expressions are not in two methods. But I'm afraid to let other developers, who will use this extension to shoot in their leg by using it in two execution of query in one method..

**Comment by sdanyliv** [comment]
Last try. Replace array with List.

**Comment by arwyl** [comment]
no, still nothing..
```
					for (int i = 0; i < 5; i++)
					{
						db.Insert(new User
						{
							Id = i
						});
					}

					var ids = new List<int?> { 1, 2, 3 };

					var query = db.Users.Where(x => Sql.Ext.In(x.Id, ids));

					Console.WriteLine(query.ToString());

					Assert.AreEqual(3, query.Count());

					Assert.IsTrue(query.ToString().Contains("IN (@ids, @ids1, @ids2)"));

					ids = new List<int?> { 5, 6 };

					var query2 = db.Users.Where(x => Sql.Ext.In(x.Id, ids));
					// same output as before
					Console.WriteLine(query2.ToString());
					// Message:   Expected: 0  But was:  3
					Assert.AreEqual(0, query2.Count());

					Assert.IsTrue(query2.ToString().Contains("IN (@ids, @ids1)"));
```

**Comment by sdanyliv** [comment]
Strange, will check exactly your sample.

**Comment by arwyl** [comment]
@sdanyliv could you reproduce the error?

**Comment by sdanyliv** [comment]
@arwyl, yes, i have reproduced error.
Problem is obvious but i don't not how to handle this correctly without loosing performance.
If you reuse variable `ids` we can not handle when this variable was changed and always compares data in cache with latest variable value.
IOW, if you want this functionality to be working - do not reuse local variables. For each query set values from new variable.

**Comment by arwyl** [comment]
@sdanyliv is there no way to disable caching for one particular query?

**Comment by sdanyliv** [comment]
Never tried this:
```cs
using (NoLinqCache.Scope())
{
   // query
}
```

**Comment by arwyl** [comment]
and no way to specify that from Sql.IExtensionCallBuilder implementation?

**Comment by sdanyliv** [comment]
Nope. We have to handle that differently in this case. 
Usually it should work as expected but not in such situation. 
Possible we can introduce something like this Sql.In(Sql.AsParameters(values)) sometimes.

But! There another way how to handle such queries: override `DataConnection.ProcessQuery` and return corrected SQL. Property `IsParameterDependent = true` in query should be set to true.

**Comment by arwyl** [comment]
@sdanyliv you know, I think I managed to autoreplace Contains to something parameterized.. To list of OR-s. Without extensions, cache disabling and stuff

If you have time, can you share your thoughts about this solution?


```
        // for parameterization of ConstantExpressions
	class ExpressionScopedVariables<T>
	{
		public T Value;
	}

	public class GetValuesExpressionReplacer : ExpressionVisitor
	{
		protected List<object> _values;

		public List<object> GetValues(Expression expr)
		{
			_values = new List<object>();
			Visit(expr);
			return _values;
		}

		protected override Expression VisitConstant(ConstantExpression node)
		{
			_values.Add(node.Value);
			return base.VisitConstant(node);
		}
	}

	public class ContainsToOrExpressionReplacer : ExpressionVisitor
	{
		protected Lazy<GetValuesExpressionReplacer> _getValuesExpressionReplacer = new Lazy<GetValuesExpressionReplacer>();
		protected override Expression VisitMethodCall(MethodCallExpression node)
		{
			if (node.Method.Name == "Contains")
			{
				var arg = node.Arguments[0];
				var obj = node.Object;

				// obj will be null, if Contains is called for IQueryable. That is handled ok by default
				if (obj != null && arg is MemberExpression)
				{
					IEnumerable values;

					var argMember = arg as MemberExpression;

					if (obj is MemberExpression)
					{
						var objectMember = Expression.Convert(obj, typeof(object));

						var getterLambda = Expression.Lambda<Func<object>>(objectMember);

						var getter = getterLambda.Compile();

						values = getter() as IEnumerable;
					}
					// case for NewArrayExpression, InitListExpression and so on
					// when used like: x => new List{...}.Contains(x.Id)
					else
					{
						values = _getValuesExpressionReplacer.Value.GetValues(obj);
					}

					if (values != null)
					{
						BinaryExpression res = null;

						foreach (object o in values)
						{
							var expressionScopedVariablesType = typeof(ExpressionScopedVariables<>).MakeGenericType(argMember.Type);

							var scope = Activator.CreateInstance(expressionScopedVariablesType);

							var getVariable = expressionScopedVariablesType.GetMember(nameof(ExpressionScopedVariables<object>.Value))[0];

							getVariable.SetValue(scope, o);

							var scopeExp = Expression.Constant(scope);

							var accessExpr = Expression.MakeMemberAccess(scopeExp, getVariable);

							var equalsExpr = Expression.Equal(arg, accessExpr);

							if (res == null)
							{
								res = equalsExpr;
							}
							else
							{
								res = Expression.Or(res, equalsExpr);
							}
						}

                                                  // case when res is null (Contains is called for empty collection) is handled ok by default
						if (res != null)
						{
							return res;
						}
					}

				}
			}

			return base.VisitMethodCall(node);
		}
	}

	class Linq2DbDataConnection : DataConnection, IExpressionPreprocessor
	{
		protected Lazy<ContainsToOrExpressionReplacer> _containsToOrExpressionReplacer = new Lazy<ContainsToOrExpressionReplacer>();

		public Linq2DbDataConnection(string connString) : base(connString)
		{
		}

		public Linq2DbDataConnection(IDataProvider dataProvider, string connString) : base(dataProvider, connString) { }

		/// <summary>
		/// Processes the expression.
		/// </summary>
		/// <param name="expression">The expression.</param>
		/// <returns></returns>
		public Expression ProcessExpression(Expression expression)
		{
			var replacedExpression = _containsToOrExpressionReplacer.Value.Visit(expression);
			return replacedExpression;
		}
	}
```


Test:
```
var ids = new List<int> { 1, 2, 3 };

var query = db.Users.Where(x => ids.Contains(x.Id) && x.IsActive);

var str = query.ToString();
Console.WriteLine(str);
Assert.IsTrue(str.Contains("@Value1"));
Assert.IsTrue(str.Contains("@Value2"));
Assert.IsTrue(str.Contains("@Value3"));

ids = new List<int> { 5, 6 };

query = db.Users.Where(x => ids.Contains(x.Id) && x.IsActive);

str = query.ToString();
Console.WriteLine(str);
Assert.IsTrue(str.Contains("@Value1"));
Assert.IsTrue(str.Contains("@Value2"));

query = db.Users.Where(x => new List<string> { "1", "2", "3", null }.Contains(x.Name) && x.IsActive);

str = query.ToString();
Console.WriteLine(str);
Assert.IsTrue(str.Contains("@Value1"));
Assert.IsTrue(str.Contains("@Value2"));
Assert.IsTrue(str.Contains("@Value3"));


query = db.Users.Where(x => new List<string>().Contains(x.Name) && x.IsActive);

str = query.ToString();
Console.WriteLine(str);
```


output:

```
DECLARE @Value1 Int -- Int32
SET     @Value1 = 1
DECLARE @Value2 Int -- Int32
SET     @Value2 = 2
DECLARE @Value3 Int -- Int32
SET     @Value3 = 3

SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[IsActive],
	[t1].[Guid],
	[t1].[AppointmentId]
FROM
	[Users] [t1]
WHERE
	(([t1].[Id] = @Value1 OR [t1].[Id] = @Value2) OR [t1].[Id] = @Value3) AND
	1 = [t1].[IsActive]

--  testDataProvider SqlServer.2008
DECLARE @Value1 Int -- Int32
SET     @Value1 = 5
DECLARE @Value2 Int -- Int32
SET     @Value2 = 6

SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[IsActive],
	[t1].[Guid],
	[t1].[AppointmentId]
FROM
	[Users] [t1]
WHERE
	([t1].[Id] = @Value1 OR [t1].[Id] = @Value2) AND 1 = [t1].[IsActive]

--  testDataProvider SqlServer.2008
DECLARE @Value1 NVarChar(4000) -- String
SET     @Value1 = N'1'
DECLARE @Value2 NVarChar(4000) -- String
SET     @Value2 = N'2'
DECLARE @Value3 NVarChar(4000) -- String
SET     @Value3 = N'3'

SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[IsActive],
	[t1].[Guid],
	[t1].[AppointmentId]
FROM
	[Users] [t1]
WHERE
	((([t1].[Name] = @Value1 OR [t1].[Name] = @Value2) OR [t1].[Name] = @Value3) OR [t1].[Name] IS NULL) AND
	1 = [t1].[IsActive]

--  testDataProvider SqlServer.2008
SELECT
	[t1].[Id],
	[t1].[Name],
	[t1].[IsActive],
	[t1].[Guid],
	[t1].[AppointmentId]
FROM
	[Users] [t1]
WHERE
	1 = 0 AND 1 = [t1].[IsActive]
```

**Comment by sdanyliv** [comment]
@arwyl, strange that this works, because cache compares expressions before `IExpressionPreprocessor` call.

For the future, we have `Transform` extension which gets rid of visitors usage and simplifies things a lot.

**Comment by arwyl** [comment]
@sdanyliv i Looked at https://github.com/linq2db/linq2db/blob/master/Source/LinqToDB/Linq/Query.cs GetQuery method
first it calls preprocessor.ProcessExpression, then it looks for query in cache

**Comment by sdanyliv** [comment]
You are right. 
Your transformation is not ideal and do not not handle situations with SelectMany when used Method that returns IQueryable and has `Contains` inside. You have to Invoke this method and grab Expression returned by this method.

I will continue to work with correct cache hit. Looks like we have problem here.
