### ISSUE TITLE
Issue connecting to db2

### ISSUE THREAD

**Issue by dconner2006** [linq2db/linq2db#980]
Describe your issue.
Getting an invalid argument when trying to connect
If you have a question, first try to check our [wiki](https://github.com/linq2db/linq2db/wiki) and search in [issues](https://github.com/linq2db/linq2db/issues) - maybe your question already answered there.

If you are seeing an exception, include the full exceptions details (message and stack trace).
{System.ArgumentException: Invalid argument
   at IBM.Data.DB2.DB2ConnPool.ReplaceConnectionStringParms(DB2Connection connection, String szValue, DB2ConnSettings& pSettings, DB2ConnSettingsInternal& pSettingsInternal, Boolean bAttach, Boolean pushDownStrAppended)
   at IBM.Data.DB2.DB2Connection.set_ConnectionString(String value)
   at IBM.Data.DB2.DB2Connection..ctor(String connectionString)
   at lambda_method(Closure , String )
   at LinqToDB.DataProvider.DynamicDataProviderBase.CreateConnectionInternal(String connectionString)
   at LinqToDB.DataProvider.DataProviderBase.CreateConnection(String connectionString)
   at LinqToDB.Data.DataConnection.get_Connection()
   at LinqToDB.Data.DataConnection.CreateCommand()
   at LinqToDB.Data.DataConnection.get_Command()
   at LinqToDB.DataProvider.DataProviderBase.InitCommand(DataConnection dataConnection, CommandType commandType, String commandText, DataParameter[] parameters)
   at LinqToDB.DataProvider.DB2.DB2DataProvider.InitCommand(DataConnection dataConnection, CommandType commandType, String commandText, DataParameter[] parameters)
   at LinqToDB.Data.DataConnection.InitCommand(CommandType commandType, String sql, DataParameter[] parameters, List`1 queryHints)
   at LinqToDB.Data.DataConnection.QueryRunner.ExecuteReader()
   at LinqToDB.Linq.QueryRunner.<ExecuteQuery>d__8`1.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at NewHLCS_Reports.GTBCount.GetData() in c:\users\c839962\documents\visual studio 2015\Projects\NewHLCS_Reports\NewHLCS_Reports\GTBCount.cs:line 34
   at NewHLCS_Reports.GTBCount.RunReport() in c:\users\c839962\documents\visual studio 2015\Projects\NewHLCS_Reports\NewHLCS_Reports\GTBCount.cs:line 25
   at NewHLCS_Reports.Program.Main(String[] args) in c:\users\c839962\documents\visual studio 2015\Projects\NewHLCS_Reports\NewHLCS_Reports\Program.cs:line 15
   at System.AppDomain._nExecuteAssembly(RuntimeAssembly assembly, String[] args)
   at System.AppDomain.ExecuteAssembly(String assemblyFile, Evidence assemblySecurity, String[] args)
   at Microsoft.VisualStudio.HostingProcess.HostProc.RunUsersAssembly()
   at System.Threading.ThreadHelper.ThreadStart_Context(Object state)
   at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state, Boolean preserveSyncCtx)
   at System.Threading.ExecutionContext.Run(ExecutionContext executionContext, ContextCallback callback, Object state)
   at System.Threading.ThreadHelper.ThreadStart()}
```
Exception message:
Stack trace:
```

### Steps to reproduce
Include a complete code listing (or project/solution) that we can run to reproduce the issue.
Connection string = 
 <add name="GTCount" connectionString="Server=topddp01.iss.bnr.com:4214;Database=ds1p;;UID==user;PWD=xxxxxx;CurrentSchema=OD;" providerName="DB2"/>
Partial code listings, or multiple fragments of code, will slow down our response or cause us to push the issue back to you to provide code to reproduce the issue.
 private List<TGTB_IDX> GetData()
        {
            using (var db = new DBGTBCount())
            {
                var query = from e in db.GetTable<TGTB_IDX>()
                            select e;

                return query.ToList();
            }
```c#
<code with error and mapping classes>
```

### Environment details
linq2db version: *1.10.0*  
Database Server: *E.g. PostgreSQL 9.6.3*  
Database Provider: *E.g. Npgsql 3.2.3*  
Operating system: *E.g. Windows 10*  
Framework version: *.NET Framework 4.6.2*

**Comment by dconner2006** [comment]
Connection string  
<add name="GTCount" connectionString="Server=topddp01.iss.bnr.com:4214;Database=ds1p;;UID==xxx;PWD=xxx;CurrentSchema=OD;" providerName="DB2"/>

**Comment by dconner2006** [comment]
connectionString="Server=topddp01.iss.bnr.com:4214;Database=ds1p;;UID==foc;PWD=xxx;CurrentSchema=OD;" providerName="DB2"

**Comment by sdanyliv** [comment]
Facepalm. Remove from message non your words. Only then it will be analysed.
Find edit button and read this one https://guides.github.com/features/mastering-markdown/

**Comment by dconner2006** [comment]
This is solved, The issue was my fault, I had two ;; after the Database=ds1p. Sorry
